### ISSUE TITLE
onboard @jacqueline-homan

### ISSUE THREAD

**Issue by jacqueline-homan** [gratipay/inside.gratipay.com#1002]
I will be working on renaming the files in the js folder (for example, renaming team.js as projects.js), and working on any other issue that Chad and the rest of the team needs/wants me to take on to work on.

**Comment by whit537** [comment]
[slack](http://gratipay.slackarchive.io/gratipay/-/1486054892.004768/1486057802.004962/1486057802004962/)

**Comment by whit537** [comment]
@jacqueline-homan May I add you as a contributor on GitHub so you can make PRs from branches in the main repo vs. a personal fork? That's our [normal workflow](http://inside.gratipay.com/howto/develop-software).

**Comment by whit537** [comment]
> I will be working on renaming the files in the js folder (for example, renaming team.js as projects.js)

This is https://github.com/gratipay/gratipay.com/issues/4318, for the record.

**Comment by whit537** [comment]
Added per [slack](http://gratipay.slackarchive.io/gratipay/-/1486055597.004868/1486065117.005055/1486056645004947/)! Welcome aboard! 💃
