### ISSUE TITLE
Organize open source workers

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#1006]
"[Why don't developers unionize?](https://news.ycombinator.com/item?id=13564440)"
"[The arc of open source software in the capitalist context is long, and it bends towards absurdity.](https://twitter.com/jashkenas/status/829817619410780160)"
"[an exaggeration, but only sort of](https://twitter.com/ag_dubs/status/829850842815668225)."
"[we need to unionize](https://twitter.com/FotoVerite/status/830153298116227072)"

What if Gratipay were a union representing open source workers?

**Comment by whit537** [comment]
I'm seeing this as an evolution of the idea that Gratipay convert to a worker-owned, open cooperative (#992).

**Comment by whit537** [comment]
Also relevant: "[an exaggeration, but only sort of](https://twitter.com/ag_dubs/status/829850842815668225)."

**Comment by whit537** [comment]
> What could I expect to change in my daily working life by joining your "new model union"?
>
> Unions got buy-in from workers because they offered tangible benefits to workers. Shorter days, medical care, better pay, and so on.

https://news.ycombinator.com/item?id=13564440

> programmers shouldn't have to be expert negotiators to get fair compensation and working conditions

https://twitter.com/substack/status/830163178013093892

> i hope unionizing can be done in modern ways without giving power to representatives

https://twitter.com/serapath/status/830204285329694720

**Comment by whit537** [comment]
I think there's a lot of room for collective _marketing_ before it ever comes to collective _bargaining_. Though https://github.com/gratipay/inside.gratipay.com/pull/937#issuecomment-265299879:

> You need to organize a strike. If there's no pain then you need to create pain. An amiable strike—just for an hour.

**Comment by nobodxbodon** [comment]
Would being a union help #987? Or, would that make Gratipay more appealing to companies?

**Comment by whit537** [comment]
@nobodxbodon It would help more on the supply side, with open source project maintainers.
