### ISSUE TITLE
Setup for basic A/B tests for the front page

### ISSUE THREAD

**Issue by webmaven** [gratipay/inside.gratipay.com#101]
Currently, the front page has around an 80% bounce rate, possibly because it is targeting receivers. I propose testing our current Hypothesis for 'Customer A' by running an A/B test on the front page content to see if we can move that needle significantly.

To set up a basic A/B test We'll need the following steps completed as prerequisites

- [x] @whit537 needs to sign up for Optimizely, their cheapest plan should be fine (30 day free trial, then $19 per month after trial period)
- [x] The Optimizely JS code needs to be included into the base template, or specifically into the front-page template: https://help.optimizely.com/hc/en-us/articles/200040095-Implementing-the-Optimizely-Snippet
- [x] ~~Turn on Optimizely integration for Segment: https://segment.com/docs/integrations/optimizely/~~
- [x] Turn on Optimizely integration with Google Analytics
- [x] Agree upon, and state a hypothesis we will try to validate 
- [x] Give access to Optimizely to the person who will set up the experiments
- [ ] ~~**BONUS** Add a 'thank you for signing up' page for people signing in for the first time~~ Didn't make it.
- [x] Set up one or more variations to run on the front page, including tracking the events we are trying to promote (signing in using any of the buttons)
- [x] turn on the experiment, wait for statistical significance and a bit more (shouldn't take more than a few days, perhaps as little as one day)
- [x] turn off the experiment, and evaluate the results

Note: I am not *certain* that the variations will end up in GA (Google Analytics) so that we can limit the analysis to first time visitors *and* segment by variation, but even if not, we should see a statistically significant change as first time visitors currently bounce at a ~75% rate., and we can also see Optimizely's own reports.

**Comment by whit537** [comment]
One down! :-)
