### ISSUE TITLE
Apply for HackerOne open source program

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#1014]
https://www.hackerone.com/blog/HackerOne-Professional-Free-For-Open-Source-Projects

**Comment by whit537** [comment]
@nobodxbodon Want to check this out? You should be able to find our previous conversations with the HackerOne customer success team in Freshdesk. Jo is our contact there. Want to reach out to her? :)

**Comment by nashe** [comment]
Are we still using the "basic" plan? Honestly, I can't find any page describing the exact differences between "basic" and professional / enterprise editions. It seems it would allow us to create _promotions_ (loyalty bonuses?), get duplicate detection (I thought that I already saw this feature with our current plan?), establish automation workflows and get access to more advanced statistics. 

I can try to contact them (note: I don't have access to Freshdesk right now) and see if we are eligible and what would be the new features. Maybe it could give us ideas and we could get #789 back on tracks!
