### ISSUE TITLE
Join TODO Group

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#1021]
h/t @jkingdon on [Twitter](https://twitter.com/jkingdon2000/status/841653370913882113).

> ### Should I join?
>
>There are lots of different ways in which open source is built, used, and released - and there are many foundations, groups, and communities for different aspects of this rich ecosystem. TODO is specifically intended as forum for companies’ open source program managers to come together. Members generally tend to represent companies who consider open source to be an adjunct their core business.

I hesitated to submit the "Join" [form](http://todogroup.org/join/), but then saw that SauceLabs is [on there](http://todogroup.org/members/), which for some reason felt relatable to me (moreso than Adobe, Comcast, Samsung, &c.), and also the positive feedback at https://github.com/gratipay/inside.gratipay.com/issues/1015#issuecomment-286191790 yesterday. Worst they can say is no, right? ¯\\\_(ツ)\_/¯

![screen shot 2017-03-14 at 10 18 40 am](https://cloud.githubusercontent.com/assets/134455/23904856/b9537c36-089f-11e7-98f7-c268f068e3dd.png)

**Comment by whit537** [comment]
We know Brandon on the [steering committee](https://github.com/todogroup/charter#todo-steering-committee-tsc).

**Comment by jkingdon** [comment]
Perhaps Google and Facebook and Square are more relatable​ (all companies which use, and release, a lot of open source)? I don't have an opinion about exactly how todogroup and gratipay might relate, but to give one example I do know, multiple member companies contribute to Ruby Together - https://rubytogether.org/members

**Comment by whit537** [comment]
The [contributors graph](https://github.com/todogroup/todogroup.github.io/graphs/contributors) is a very interesting list of people I might reach out to. 😳
