### ISSUE TITLE
Inside Gratipay is not accessible over HTTPS

### ISSUE THREAD

**Issue by rerb** [gratipay/inside.gratipay.com#1025]
It says, 

> Internal server error, program!

**Comment by rohitpaulk** [comment]
Hmm, seems to be working here: http://inside.gratipay.com/

@rerb Can you get us the URL that you were trying to hit? :)

Might have been a one time thing too, will check logs in a while.

**Comment by rerb** [comment]
Using Safari, http://inside.gratipay.com/ redirects to https://inside.gratipay.com/ and that reports the internal server error.

Using Firefox, http://inside.gratipay.com/ doesn't redirect to https://inside.gratipay.com/, and http://inside.gratipay.com comes up.

So http://inside.gratipay.com/ is not down.

**Comment by rohitpaulk** [comment]
Oh, gotcha. Still a valid bug for though - would be great to have https://inside.gratipay.com/ to be up too :) 

I see the `Internal server error, program!' screen now. Reopening.

**Comment by whit537** [comment]
Folding into #943. ☺️
