### ISSUE TITLE
Add Twitter to Freshdesk

### ISSUE THREAD

**Issue by mattbk** [gratipay/inside.gratipay.com#1026]
I think we can do this on our plan (#928, https://freshdesk.com/pricing)? https://support.freshdesk.com/support/articles/195544-adding-a-customized-twitter-stream-to-your-freshdesk

This would lump the support channels together, so I don't need to have a feed in Tweetdeck open for Gratipay.

**Comment by whit537** [comment]
I believe we used to do this. Do we funnel Facebook in there as well?

**Comment by mattbk** [comment]
Doesn't look like it. I don't have a "Social" tab.

**Comment by whit537** [comment]
@mattbk Do you have perms to do this?

**Comment by whit537** [comment]
Okay.

**Comment by whit537** [comment]
@mattbk Try now? I've upped your perms.

![screen shot 2017-03-29 at 8 49 10 am](https://cloud.githubusercontent.com/assets/134455/24455169/97eca7ac-145c-11e7-894e-2999bcd8121b.png)

**Comment by mattbk** [comment]
Can access! Playing with auto-ticketing, will adjust as needed. Closing for now.
