### ISSUE TITLE
File taxes

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#1027]
@JessWhit has been working on this. She writes:

> Can you identify expenses from either business in these categories?
>
>**Advertising**: Business cards, internet, radio, and TV ads
>
>**Equipment rental**: Van or truck rental or office equipment
>
>**Legal or professional services**: Fees paid to an attorney or other professional
>
>**Local transportation**: Parking, tolls, or taxis
>
>**Meals and entertainment**: Meals while traveling, lunch with client, or refreshments for open house.
>
>**Other business expenses**: Cell phone, dues, subscriptions, and training
>
>**Overnight travel expenses**: Transportation costs, Internet, phone or fax charges, and tips
>
>**Supplies**: Merchandise bought for sale to customers, print cartridges and printer paper (less than $200 and used within 12 months)
>
>**Taxes or licenses**: FICA, unemployment taxes, and property taxes

**Comment by kaguillera** [comment]
Will do...

**Comment by whit537** [comment]
@kaguillera and I talked about this IRL. Here's what we need:

1. Hand-roll a `pnc.csv` for the one month that we're missing because we didn't export soon enough (we should have a PDF to start from).
1. Write a script to iterate over all `pnc.csv`s for Jan - Dec 2016 and sum expenses by the categories given above.
1. We'll also need to account for payouts via Gratipay but let's start with PNC.

**Comment by whit537** [comment]
> either business

Ftr this refers to Gratipay, LLC and Chad Whitacre (me as a consultant). We only need to worry about the former here. ☺️

**Comment by kaguillera** [comment]
As requested Expenses information using the pnc.csv files from logs.

CHECK 101 - $220.00
CHECK 102 - $16.00
CHECK 103 - $500.00
CHECK 104 - $825.00
WITHDRAWAL XXXXX1851  - $1,000.00

Income - $11000.91

Total Other Business Expenses - $5135.39

Total Meals and Entertainment Expenses - $773.46

Total Overnight Travel Expenses - $1790.19

Total Supplies Expenses - $226.20

Total Advertising Expenses - $84.02

Total Legal or Professional Services Expenses - $280.72

Total Local Transportation Expenses - $54.55

The link to the script gist is [here](https://gist.github.com/kaguillera/0c21ccfb06485151726caf04224a75d0) let me know if you have trouble with it.

**Comment by kaguillera** [comment]
Oh the checks will have to be explained to your accountant/tax filer 😁

**Comment by whit537** [comment]
We can look at those Thursday here at HQ.

**Comment by whit537** [comment]
Legal or Professional Services:

CHECK 101 - $220.00 &rarr; https://github.com/gratipay/inside.gratipay.com/issues/319#issuecomment-169334194
CHECK 102 - $16.00 wilke, CPA
CHECK 104 - $825.00 luis villa, lawyer

Other business expenses:

CHECK 103 - $500.00 paramount coworking

**Comment by whit537** [comment]
```sql
gratipay::MAROON=> select date_trunc('year', "timestamp") as ts, sum(amount) from payments where direction='to-participant' and team='Gratipay' and participant != 'whit537' group by ts order by ts desc;
┌────────────────────────┬──────────┐
│           ts           │   sum    │
├────────────────────────┼──────────┤
│ 2017-01-01 00:00:00+00 │  1378.04 │
│ 2016-01-01 00:00:00+00 │ 11067.96 │
│ 2015-01-01 00:00:00+00 │ 10229.86 │
└────────────────────────┴──────────┘
(3 rows)

gratipay::MAROON=> select date_trunc('year', "timestamp") as ts, sum(amount) from payments where direction='to-participant' and team='Gratipay' group by ts order by ts desc;
┌────────────────────────┬──────────┐
│           ts           │   sum    │
├────────────────────────┼──────────┤
│ 2017-01-01 00:00:00+00 │  1388.89 │
│ 2016-01-01 00:00:00+00 │ 11164.62 │
│ 2015-01-01 00:00:00+00 │ 10229.86 │
└────────────────────────┴──────────┘
(3 rows)
```

**Comment by whit537** [comment]
😊

```
gratipay::MAROON=> select participant, sum(amount) as amount from payments where direction='to-participant' and team='Gratipay' and "timestamp" >= '2016-01-01'::timestamptz and "timestamp" < '2017-01-01'::timestamptz group by participant order by amount desc;
┌─────────────┬──────────┐
│ participant │  amount  │
├─────────────┼──────────┤
│ Gratipay    │ 11013.10 │
│ whit537     │    96.66 │
│ mattbk      │    32.28 │
│ rohitpaulk  │    18.00 │
│ JessaWitzel │     2.70 │
│ aandis.     │     1.17 │
│ Lurtz       │     0.30 │
│ clone1018   │     0.18 │
│ chrisdev    │     0.14 │
│ sseerrggii  │     0.06 │
│ nashe       │     0.03 │
└─────────────┴──────────┘
(11 rows)
```

**Comment by whit537** [comment]
So that's another $135.38 for Legal and Professional Services. 👍

@JessWhit @kaguillera Good to go?

```
gratipay::MAROON=> select sum(amount) from (select sum(amount) as amount from payments where direction='to-participant' and team='Gratipay' and participant != 'whit537' and participant != 'Gratipay' group by participant order by amount desc) _;
┌────────┐
│  sum   │
├────────┤
│ 135.38 │
└────────┘
(1 row)
```

**Comment by kaguillera** [comment]
So there is a error in the query above (i.e. no date constraint) The correct amount is of the Legal and Professional Services is $54.86

**Comment by whit537** [comment]
@JessWhit and @kaguillera worked on this together earlier today, I think she has what she needs to file.

**Comment by kaguillera** [comment]
Planning to categorize expenses base on the tax categories as we go forward with the accounting. This should make it easy for tax season.

**Comment by whit537** [comment]
Taxes filed!
