### ISSUE TITLE
Post about $ustain

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#1032]
We're co-organizing https://sustainoss.org/ (#920). In https://github.com/sustainers/website/issues/70, @jdorfman asks us to make a blog post on https://gratipay.news/. Here's a draft:

"[$ustain Open Source With Us](https://gratipay.news/5870acdc3ec4)"

Any objections? Feedback?

**Comment by whit537** [comment]
Ooh! Yay! Customizable slugs on Medium since last I checked. :-)

![screen shot 2017-04-06 at 2 16 22 pm](https://cloud.githubusercontent.com/assets/134455/24769218/b6918664-1ad3-11e7-9fa7-382e5031fd80.png)

**Comment by jdorfman** [comment]
:shipit:

**Comment by whit537** [comment]
We're live!

https://gratipay.news/
https://twitter.com/Gratipay/status/850414981355114500
