### ISSUE TITLE
Apply to Indie.vc

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#1034]
Reticketed from https://github.com/gratipay/inside.gratipay.com/issues/68#issuecomment-292318398/.

Indie.vc is genuinely exciting, and probably a better fit than Y Combinator (#1017).

http://www.indie.vc/join

**Comment by whit537** [comment]
Gosh, I really want [proper financials](https://github.com/gratipay/finances/issues/3). 😳

**Comment by whit537** [comment]
Stashing for later:

```
=> select sum(amount) from payments where team='Gratipay' and direction='to-team' and "timestamp" <= now() - '60 days'::interval and "timestamp" > now() - '90 days'::interval;
```

**Comment by whit537** [comment]
Really though we should include processing fee income in net revenue, and processing fee expenses as cost of goods sold.

**Comment by whit537** [comment]
Alright, leaving this alone for now. If we get invited for YC (#1017) then we should have a week or two before our interview, and Indie.vc's turn around is supposedly two weeks. We'd need to have a decision ready if/when YC makes an offer the day of any interview. If we want to have Indie.vc as an alternative to YC then there may be enough time to get in their pipeline between YC invite and interview. Meaning I don't have to sweat this today, I can keep chipping away at https://github.com/gratipay/gratipay.com/pull/4398 etc. 👍

**Comment by whit537** [comment]
https://twitter.com/Gratipay/status/850136111900971009

**Comment by whit537** [comment]
One of their portfolio companies is in Pittsburgh, to which I've asked a local friend for an introduction.

**Comment by whit537** [comment]
Per their [links page](http://www.indie.vc/links), I've asked for and received a Slack invite. Just introduced myself!

![screen shot 2017-04-07 at 2 15 42 pm](https://cloud.githubusercontent.com/assets/134455/24813613/b6c283da-1b9c-11e7-9d6b-d584a0511779.png)

**Comment by whit537** [comment]
Good lunch with Pittsburgh connection. Sounds like we are on the edge of their radar and it might be worth applying. Same story as usual, the money is part of it, the connections are more. Indie.vc is in the 15-20 company range right now and holds quarterly or semi-annual retreats.

The reason to do this would be to free up a bit more of my time, and also make funds available for others to get paid to work on Gratipay. Money in the top of our twyw funnel. That and the network + credibility to help us sign up company givers and maybe get into LF or other partnerships on #324.

Anyone have any inclination one way or another here?

**Comment by whit537** [comment]
The downside is the opportunity cost of the time this takes away from other things.

> What was your TTM revenue? *
> Net revenue the last 3 months, by month? *
> How much of that is recurring monthly net revenue? *
> What is your gross margin? *
> Timing to profitability or profitable? *
> What excites you most about your company's potential? What do you think it can become? *
> Define what success looks like for you and your business. *
> Have you tried in the past to raise venture capital? How did that go and why? *
> What about Indie.vc is appealing to you? Why is Indie.vc right for you instead of traditional venture capital? *
> How did you hear about us?

http://www.indie.vc/join

**Comment by whit537** [comment]
> Meaning I don't have to sweat this today, I can keep chipping away at gratipay/gratipay.com#4398 etc. 👍

👍 👍

**Comment by whit537** [comment]
I pinged Bryce in private Slack and let him know that we're interested in talking but probably won't get to applying in the next month or two because of focusing on https://github.com/gratipay/gratipay.com/pull/4305 & #920 #948.

**Comment by whit537** [comment]
> What was your TTM revenue? *

15,000

> Net revenue the last 3 months, by month? *

550, 392, 360

> How much of that is recurring monthly net revenue? *

100%

> What is your gross margin? *

100%

> Timing to profitability or profitable? *

1 to 3 years

> How much debt do you have if any? *

0

> What excites you most about your company's potential? What do you think it can become? *

Our immediate goal is to become the answer to the tragedy of the commons in open source. The space is heating up—Patreon is about to cross $150M in volume, CII moved $2M last year, Open Collective double in three months, plus Liberapay (fork of us), Bountysource, two more in the rumor mill. The industry is starting to care about open source sustainability. Someone is going to crack it.

Our bigger vision is to become the future of work. Jobs are a mechanism of artificial scarcity. Employment is late-stage, low-grade slavery. We envision a society of abundant, meaningful work without jobs.

> Define what success looks like for you and your business. *

First rung would be sustainability from revenue for our current team. Call that $250,000 per year in revenue, which at 5% of volume means $5M in volume. In our first growth run it took us three years to move our first $1M, but the industry is catching up, the timing is better now and we've learned our lessons.

Second rung would be a project on Gratipay making $250,000 per year.

10-year goal is 1,000+ projects on Gratipay making $250,000/yr+. That's when we start to see a new marketplace for "open work" emerge.

First real taste of the bigger vision is probably two or three decades out. 10,000+ "open organizations" making $2,500,000/yr+ each, and 1M+ people finding a living on Gratipay.

> Have you tried in the past to raise venture capital? How did that go and why? *

Not very seriously, no. We've interacted with a number of folks over the years (USV, YC, 500, etc.), but we've been too idealistic to get very far.

> What about Indie.vc is appealing to you? Why is Indie.vc right for you instead of traditional venture capital? *

You're almost as weird as we are. :-P

Seriously, though, we're structuring as a worker-owned cooperative, and profit-sharing is a much better financing fit than shares.

> How did you hear about us?

Bubbled to the surface on https://www.zebrasunite.com/resources, followed up with [] (Cotton Bureau).

**Comment by whit537** [comment]
@clone1018 @rohitpaulk @mattbk et al. ^^^ Hoping to submit in the next day or two. Lemme know how it looks! :-)

**Comment by mattbk** [comment]
Can't argue with your definition of success. :wink: 

> 10-year goal is 1,000+ projects on Gratipay making $250,000/yr+. That's when we start to see a new marketplace for "open work" emerge.

I would add "each" as in the next paragraph. I had to read them both twice to realize how ambitious you were being, and wasn't sure whether you meant $250,000 (wrong) or $250,000,000 (right) being moved in total.

**Comment by whit537** [comment]
> I would add "each" as in the next paragraph.

Done.

**Comment by clone1018** [comment]
It looks good to me.

**Comment by whit537** [comment]
Submitted!

> Thanks for applying! We'll try to let you know if we're planning on moving forward with next steps in the next two weeks. Due to the high level of applications, we can't provide detailed feedback on any company we pass on.  
>
> If you have any questions, just reach out to hello@indie.vc.

Will follow up in Slack ...

**Comment by whit537** [comment]
> Alright, Bryce, I went ahead and kicked off an application.
> Might be too early, since we’re _just_ at the beginning of our relaunch. It’s too early to be able to demonstrate traction.
> But I guess I wanted to get the conversation started sooner rather than later, so that we can track together over the summer.
> Let me know if you’re interested in next steps and what those might be! :slightly_smiling_face:

**Comment by whit537** [comment]
> Chad - thanks very much for considering Indie.vc and taking the time to apply. 
>
>Unfortunately we won’t be moving forward at this point. We’ve had over a thousand inquires and can only invest in a dozen companies per year.
>
>In hopes of being additive to your journey in building Gratipay, consider joining our Slack channel. It’s a growing community of 650 like-minded entrepreneurs building independent businesses with specific channels for sales, engineering, etc. so we share and learn from each other. If you care to join, please send an invite request to []@oatv.com.
>
>Our best as you continue to build.

**Comment by whit537** [comment]
From Bryce in Slack a couple weeks ago: "If not now, hang out here and let's keep building a relationship."

**Comment by whit537** [comment]
P.S. They said no.

**Comment by JessaWitzel** [comment]
Hey! Do you want to keep this open? What are the next steps in this ticket if so?

**Comment by whit537** [comment]
I don't, no.
