### ISSUE TITLE
Change how we pay for stuff

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#1040]
Right. Soooooo ... under #1027 @JessWhit and I have been looking at writing off lots more things as Gratipay expenses than what run through our PNC account. The reason is that as a single-member LLC, Gratipay is essentially a sole proprietorship for tax purposes. All of the money we collect counts for direct income to yours truly. It's as if the money went straight into my personal bank account at Citizens Bank instead of into the PNC account we use for operations. The same holds true for expenses. That is, whether I pay for something out of PNC with the Gratipay card or out of Citizens with my own debit card, if it's related to Gratipay then it's a Gratipay expense. @JessWhit has therefore been going back through our Citizens records and identifying Gratipay expenses. Think: coworking (Stack and Catapult), meals & entertainment, transportation (weekly bus fare), and also most of the France trip.

What are the implications here?

If our goal is transparency for the Gratipay community, it seems that we should just run these expenses through Gratipay's PNC account, rather than through my and @JessWhit's Citizens account. That will make it more obvious to us that we're in fact running in the red.

Our goal is also to make Gratipay a partnership (#196), which will impact the situation here as well. How?

**Comment by kaguillera** [comment]
> If our goal is transparency for the Gratipay community, it seems that we should just run these expenses through Gratipay's PNC account, rather than through my and @JessWhit's Citizens account. That will make it more obvious to us that we're in fact running in the red.

I agree this would make accounting easier also.
