### ISSUE TITLE
Add static content preview with Netlify

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#1042]
* [ ] somebody with admin right should register repository on https://app.netlify.com to add commit hooks
* [ ] add Netlify to list of our used services
* [ ] add 2nd person to Netlify admin interface
* [ ] add HTML scraping to fetch pages

**Comment by whit537** [comment]
Not sure what to do with this. What is Netlify and why do we want it?

**Comment by techtonik** [comment]
Netlify is a CI service that publishes static sites instead of build logs on every PR.

**Comment by whit537** [comment]
Ah, okay. How does it publish static sites? Jekyll? Or ... ?

**Comment by techtonik** [comment]
Build command and deploy dir are specified from web interface.

**Comment by whit537** [comment]
And what would the build command and deploy dir be for Inside Gratipay? We'd either have to write something that dumps all dynamic pages to static, or port to another system. I'm not sure either is worth the effort.

**Comment by techtonik** [comment]
Build: `make`
Deploy: `www`

**Comment by techtonik** [comment]
Ohh. I was thinking about `grtp.co`. Yes, I've got a public domain script that dumps dynamic pages to static.

**Comment by whit537** [comment]
> Ohh. I was thinking about `grtp.co`.

Hah! That makes a lot more sense. :-)

In that case let's move over to https://github.com/gratipay/grtp.co/issues/171 ...

**Comment by techtonik** [comment]
It is still make sense for PR reviews even with `wget`.
