### ISSUE TITLE
Go to Open Source Summit North America 2017

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#1044]
http://events.linuxfoundation.org/events/open-source-summit-north-america

September 11-13, 2017
Los Angeles

**Comment by whit537** [comment]
$150 hall pass

https://events.linuxfoundation.org/events/open-source-summit-north-america/attend/register

Might go up on June 24?

**Comment by whit537** [comment]
Cheap flights on [Spirit](https://www.spirit.com/), $168!

**Comment by whit537** [comment]
@jdorfman has graciously offered a couch to crash on. ❤️

**Comment by whit537** [comment]
I booked a flight arriving Sunday September 10 and departing Wednesday afternoon the 13th.

I registered for the hall pass. 💃

**Comment by whit537** [comment]
If I decide to take the penny puncher it looks like that will be +$30—65

**Comment by jdorfman** [comment]
@whit537 just bring 100 pre-stamped and rolled. Solved.

**Comment by whit537** [comment]
Sure but it's more fun to drag the thing around for two days, makes people curious. ;-)

**Comment by whit537** [comment]
Checked in and paid for penny puncher (+$80 roundtrip), printed boarding pass.

Bought a LAX &lrarr; Union Station roundtrip bus ticket for $19.50 on www.laxshuttletix.com.

**Comment by whit537** [comment]
I am going to Open Source Summit North America. It is happening.

**Comment by whit537** [comment]
Good conversations with Adobe and JSFoundation today. Also talked to Microsoft. Working up to the final boss (Jim Zemlin :).

**Comment by whit537** [comment]
Oh! I said hi to Linus, too. :)

**Comment by mattbk** [comment]
Microsoft might be on board for supporting R package development, they have their own R distribution: https://mran.microsoft.com/rro/

**Comment by jdorfman** [comment]
Good times

**Comment by whit537** [comment]
I'm really glad I went to this. The Linux Foundation has the most momentum of the open source foundations. They're three orders of magnitude off where we want to get to, but they seem to have the most vision. "Linux" is really too narrow a scope for what they encompass, but it's the name with the most recognition outside of tech. I strengthened my existing relationships with LF and started making new connections as well (briefly shook Jim's hand, etc.). I see some sort of partnership in our future. We shall see! :-)

Also had [fun with the penny puncher](https://twitter.com/massonpj/status/907877067349303296), of course. :D Established a good relationship with OSI (#1161).

Huge thanks to @jdorfman for hosting. Had a blast with that guy, experiencing the DTLA lifestyle (sans lazer tag) and hacking and scheming about how to make a dent in open source sustainability. 🙇 ❤️ 

Final tasks before closing this out:

- [ ] mail *Open Organization* book to Adobe contact
- [ ] do final accounting

**Comment by whit537** [comment]
# Total Cost: $592.97

## By Category

| Category              | Amount |
|:----------------------|-------:|
| meals & entertainment | 175.09 |
| travel                | 267.88 |
| conference            | 150.00 |

## Detail

| Date       | Description              | Category              | Amount |
|:-----------|:-------------------------|:----------------------|-------:|
| 2017-09-15 | LAX AIRP LA TIMES        | meals & entertainment |  18.49 |
| 2017-09-14 | OTO OTO EXPRESS          | meals & entertainment |   8.19 |
| 2017-09-14 | LA METRO 7TH ST          | meals & entertainment |   2.75 |
| 2017-09-14 | SQ *SPRING FOR COFFEE    | meals & entertainment |   9.50 |
| 2017-09-14 | LA CAFE                  | meals & entertainment |  18.27 |
| 2017-09-14 | MARRIOTT JW LA LIVE      | meals & entertainment |   4.37 |
| 2017-09-14 | YARD HOUSE               | meals & entertainment |  35.66 |
| 2017-09-13 | BOMBO FOODS AT THE GRA   | meals & entertainment |  16.15 |
| 2017-09-13 | MARRIOTT JW LA LIVE      | meals & entertainment |   5.37 |
| 2017-09-13 | LIVE BASIL PIZZA         | meals & entertainment |   9.41 |
| 2017-09-12 | COLES ORIGINAL FRENCH    | meals & entertainment |  46.93 |
| 2017-09-12 | LAXSHUTTLETIXCOM         | travel                |  19.50 |
| 2017-09-12 | SPIRIT AIRL              | travel                |  80.00 |
| 2017-09-11 | CURRITO BURRITOS WITHO   | meals & entertainment |   8.55 |
| 2017-08-11 | SPIRIT AIRL              | travel                | 168.38 |
| 2017-08-10 | ACTLinux Foundation      | conferences           | 150.00 |
