### ISSUE TITLE
Introduce aggregation story w/ npm announcement(s)

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#1045]
Follows on gratipay/gratipay.com#4427. How are we going to promote this new feature?

- [x] gratipay.news post: https://gratipay.news/integrating-npm-39333109419d
- [x] push to blogs
  - [x] https://thenewstack.io/contact/
  - [x] http://fossforce.com/contact/
  - [x] https://fossbytes.com/fossbytes-team/
  - [x] https://itsfoss.com/about/
- [x] Twitter: [one](https://twitter.com/Gratipay/status/862663593384439808), [two](https://twitter.com/Gratipay/status/864129371463970817)
- [x] IRC / Slack channels:
  - [x] Changelog slack
  - [x] Indie.vc slack
  - [x] freenode#npm
  - [x] freenode##Node.js
  - [x] freenode##javascript—getting some engagement
- [x] ~~1-on-1 email~~—punting to #969
- [x] on-site notification: https://github.com/gratipay/gratipay.com/pull/4149
- [ ] HN: ~~https://news.ycombinator.com/item?id=14360935~~ purged, retry later
- [ ] Product Hunt—need a landing page first
- [ ] https://www.reddit.com/r/opensource/

**Comment by whit537** [comment]
The most immediate marketing message here is that it is now much easier for npm packages to apply to join Gratipay as projects.

I'm inclined to use this opportunity to start telling our story around aggregation and the three-sided marketplace. On the one hand that telegraphs our strategy to our fellow travelers, but on the other hand with this release we'll be a step ahead on this path, and I think we want to start building awareness 
around this story so that we can see if there's any resonance in the marketplace. I think we have a unique take on the problem and that we're building something cool, but at this point we are very much [in search of product-market fit](https://github.com/gratipay/inside.gratipay.com/issues/987#issuecomment-272977798).

Here's a [blog post stub](https://medium.com/@whit537/apply-for-any-npm-package-with-three-clicks-9718ba28d6b2).

**Comment by whit537** [comment]
Bumping this up a level in scope from project to epic.

**Comment by whit537** [comment]
Post: https://gratipay.news/integrating-npm-39333109419d.

**Comment by whit537** [comment]
We'll need some kind of discovery mechanism ([search](https://github.com/gratipay/gratipay.com/issues/4434) will probably be easier than [bulk](https://github.com/gratipay/gratipay.com/issues/4416), though both would be nice) before we can go live with that.

**Comment by whit537** [comment]
Search PR in https://github.com/gratipay/gratipay.com/issues/4458.

**Comment by whit537** [comment]
I did some outreach on Slack/IRC and have also [posted](https://news.ycombinator.com/item?id=14360935) to HN.

I guess let's track uptake here?

```
gratipay::DATABASE=> select count(*) from teams_to_packages;
┌───────┐
│ count │
├───────┤
│     5 │
└───────┘
(1 row)
```

**Comment by whit537** [comment]
Leaving open to retry on HN.

**Comment by whit537** [comment]
@jdorfman to submit to Product Hunt once we have a landing page.

**Comment by rohitpaulk** [comment]
```
gratipay::DATABASE=> select count(*) from teams_to_packages;
 count
-------
     9
(1 row)
```

**Comment by whit537** [comment]
Our second order of magnitude! 💃

```
gratipay::DATABASE=> select count(*) from teams_to_packages;
┌───────┐
│ count │
├───────┤
│    10 │
└───────┘
(1 row)
```

And the person that [put us over the top](https://github.com/gratipay/project-review/issues/431) is the founder of npm! 😱  🙀  😍  😻

**Comment by whit537** [comment]
Adding https://www.reddit.com/r/opensource/ alongside HN and Product Hunt as places to go for our next push.

**Comment by whit537** [comment]
We're flat.

```
gratipay::DATABASE=> select count(distinct(owner)), count(team_id) from teams_to_packages tp join teams t on tp.team_id = t.id;
┌───────┬───────┐
│ count │ count │
├───────┼───────┤
│     7 │    10 │
└───────┴───────┘
(1 row)
```

**Comment by whit537** [comment]
[slack](https://gratipay.slackarchive.io/gratipay/page-100/ts-1495721423782681)

**Comment by jdorfman** [comment]
@whit537 landing page for reddit too.

**Comment by whit537** [comment]
> landing page for reddit too.

Separate or same as for Product Hunt?

**Comment by whit537** [comment]
I've started making progress on https://github.com/gratipay/gratipay.com/pull/4488. How about we aim to deploy that next week, and then make an HN/PH/Reddit push starting on Tuesday, June 13th?

cc: @jdorfman @jaimeyann @clone1018 @rohitpaulk @mattbk

**Comment by whit537** [comment]
Testing the Product Hunt waters ...

--------------

![screen shot 2017-06-02 at 11 13 07 am](https://cloud.githubusercontent.com/assets/134455/26732132/83410ed2-4784-11e7-9e8f-492829eb9014.png)

--------------

![screen shot 2017-06-02 at 11 17 57 am](https://cloud.githubusercontent.com/assets/134455/26732333/41c4cc0e-4785-11e7-844d-4808e6b949a6.png)

--------------

![screen shot 2017-06-02 at 11 18 41 am](https://cloud.githubusercontent.com/assets/134455/26732332/41c2bb6c-4785-11e7-985e-cc413223ea47.png)

**Comment by whit537** [comment]
```
gratipay::DATABASE=> select count(distinct(owner)) as nowners, count(team_id) as npackages from teams_to_packages tp join teams t on tp.team_id = t.id;
┌─────────┬───────────┐
│ nowners │ npackages │
├─────────┼───────────┤
│       9 │        14 │
└─────────┴───────────┘
(1 row)
```

**Comment by whit537** [comment]
I think we should not push to HN/PH/Reddit until we clean things up a lot more. Marketing on Twitter and IRC/Slack/email should be enough to start getting some traffic. The thing about HN/PH is that it seems more one-shot. I think we wait until things are tighter and we're more like beta quality because right now we're more like alpha quality.

**Comment by whit537** [comment]
I've started writing a post to announcing package.json discovery.

https://gratipay.news/pay-for-your-package-json-cb07341445ca

Here's the script I used to compute the 48% with 2+ and 7% with 10+ figures (based on a dump of the `emails` field from the `packages` table):

```python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, print_function, unicode_literals

import csv
from collections import defaultdict

counts = defaultdict(int)

for rec in csv.reader(open('emails.csv')):
    emails = rec[0].decode('utf8')[1:-1].split(',')
    for email in emails:
        counts[email] += 1

nmany = nmulti = 0
for email in counts:
    if counts[email] > 10:
        nmany += 1
    if counts[email] > 1:
        nmulti += 1
total = len(counts)

print(nmany , total, nmany / total)
print(nmulti, total, nmulti / total)
```

**Comment by whit537** [comment]
gratipay/gratipay.com#4507 is in! Last call for input on the "[Pay for your package.json](https://gratipay.news/pay-for-your-package-json-cb07341445ca)" announcement.

**Comment by whit537** [comment]
+2 from @jdorfman @mattbk in [slack](https://gratipay.slackarchive.io/gratipay/page-100/ts-1497626248905397).

**Comment by whit537** [comment]
https://gratipay.news/pay-for-your-package-json-cb07341445ca
https://twitter.com/Gratipay/status/875755128866971650

**Comment by whit537** [comment]
I'm going to go ahead and close this out since the first pieces are out. There will be ongoing additional marketing tasks that can have their own tickets.
