### ISSUE TITLE
Update certs

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#1051]
90 days is almost up! Time for our first (zero-indexed ;) Let's Encrypt! refresh. This is an urgent priority next week, because I'm gone the week after and our certs expire on the 11th.

- [x] Gratipay.com (gittip.co,gittip.com,gratipay.co,gratipay.com,gratipay.net,gratipay.org,www.gittip.co,www.gittip.com,www.gratipay.co,www.gratipay.com,www.gratipay.net,www.gratipay.org)
- [x] grtp.co
- [x] assets.gratipay.com (downloads.gratipay.com)
- [x] update docs: https://github.com/gratipay/inside.gratipay.com/pull/1059
- [x] rip out ACME Challenger: https://github.com/gratipay/gratipay.com/pull/4452

**Comment by clone1018** [comment]
Looks like our steps are:

1. Migrate from SSL:Endpoint to Heroku SSL (?)
1. DNS Change to point to new infrastructure 
1. Enable https://devcenter.heroku.com/articles/automated-certificate-management#setup

From: https://devcenter.heroku.com/articles/automated-certificate-management#migrating-from-ssl-endpoint

**Comment by clone1018** [comment]
```
» heroku certs:info --app gratipay
Fetching SSL certificate ankylosaurus-68672 info for ⬢ gratipay... done
Certificate details:
Common Name(s): gittip.co
                gittip.com
                gratipay.co
                gratipay.com
                gratipay.net
                gratipay.org
                www.gittip.co
                www.gittip.com
                www.gratipay.co
                www.gratipay.com
                www.gratipay.net
                www.gratipay.org
Expires At:     2017-05-11 23:37 UTC
Issuer:         /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
Starts At:      2017-02-10 23:37 UTC
Subject:        /CN=gittip.co
SSL certificate is verified by a root authority.
```

Now that i look at it I think that means we're already on Heroku SSL? If so upgrading should be as simple as `heroku certs:auto:enable`

```
 » heroku certs:auto --app gratipay
=== Automatic Certificate Management is disabled on gratipay
```

**Comment by clone1018** [comment]
Wonder why our common name is gittip.co

**Comment by whit537** [comment]
I think that was a mistake and I meant for it to be gratipay.com.

**Comment by clone1018** [comment]
Alright from what I can see, we're currently on "Heroku SSL" so we're already completely setup for Heroku's "Automated Certificate Management".

Their instructions say:
> Automated Certificate Management uses the same DNS configuration as our existing Heroku SSL (SNI) support. Although it might take some time to verify your DNS configuration, your app will continue to serve your existing SSL certificate while verification is taking place. Your app should continue to remain available at your custom domain throughout the process.

So I think our next step is to hit "I've done this"

![image](https://cloud.githubusercontent.com/assets/226638/25811323/834ecadc-33d8-11e7-96ba-8432f639683f.png)

**Comment by clone1018** [comment]
Alright. Research done for gratipay.com, I say we wait till after lunch and then hit the button so we can watch it.

Next up: grtp.co

**Comment by clone1018** [comment]
Added a checklist at the top

**Comment by whit537** [comment]
http://inside.gratipay.com/howto/install-a-tls-certificate

**Comment by whit537** [comment]
I'm good to go, @clone1018. 👍

**Comment by whit537** [comment]
Actually, we're comparing `dig` outputs. Mine:

```
$ dig gratipay.com ANY
;; Truncated, retrying in TCP mode.

; <<>> DiG 9.8.3-P1 <<>> gratipay.com ANY
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 3522
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;gratipay.com.                  IN      ANY

;; Query time: 8 msec
;; SERVER: 192.168.1.254#53(192.168.1.254)
;; WHEN: Mon May  8 14:40:01 2017
;; MSG SIZE  rcvd: 30

$
```

**Comment by clone1018** [comment]
Mine:
```
» dig gratipay.com ANY

; <<>> DiG 9.11.1 <<>> gratipay.com ANY
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 15293
;; flags: qr rd ra; QUERY: 1, ANSWER: 20, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;gratipay.com.			IN	ANY

;; ANSWER SECTION:
gratipay.com.		3600	IN	TXT	"v=spf1 include:email.freshdesk.com include:amazonses.com include:_spf.google.com -all"
gratipay.com.		3600	IN	TXT	"ALIAS for gratipay.com.herokudns.com"
gratipay.com.		3600	IN	MX	10 ASPMX.L.GOOGLE.com.
gratipay.com.		3600	IN	MX	20 ALT1.ASPMX.L.GOOGLE.com.
gratipay.com.		3600	IN	MX	30 ASPMX2.GOOGLEMAIL.com.
gratipay.com.		3600	IN	MX	30 ASPMX3.GOOGLEMAIL.com.
gratipay.com.		3600	IN	MX	20 ALT2.ASPMX.L.GOOGLE.com.
gratipay.com.		3600	IN	SOA	ns1.dnsimple.com. admin.dnsimple.com. 1433462702 86400 7200 604800 300
gratipay.com.		3600	IN	A	23.23.160.170
gratipay.com.		3600	IN	A	50.17.187.125
gratipay.com.		3600	IN	A	23.21.185.161
gratipay.com.		3600	IN	A	50.16.231.196
gratipay.com.		3600	IN	A	23.23.159.159
gratipay.com.		3600	IN	A	23.23.194.211
gratipay.com.		3600	IN	A	23.21.145.230
gratipay.com.		3600	IN	A	50.16.192.69
gratipay.com.		3600	IN	NS	ns3.dnsimple.com.
gratipay.com.		3600	IN	NS	ns1.dnsimple.com.
gratipay.com.		3600	IN	NS	ns2.dnsimple.com.
gratipay.com.		3600	IN	NS	ns4.dnsimple.com.

;; Query time: 101 msec
;; SERVER: 192.168.1.254#53(192.168.1.254)
;; WHEN: Mon May 08 10:47:05 CDT 2017
;; MSG SIZE  rcvd: 569

**Comment by whit537** [comment]
Confirmed via `dig @ns1.dnsimple.com gratipay.com ANY`. Let's do it!

**Comment by whit537** [comment]
Spot-checked with `gratipay.org`, `gittip.com`, `gittip.co` and they check out.

**Comment by clone1018** [comment]
I'm going to start this now via the Heroku Web UI

**Comment by whit537** [comment]
From IRL convo: we can remove gittip.org from our cert post-#877.

**Comment by clone1018** [comment]
I'm seeing the new cert live on gratipay.com:

```
Valid From: Mon, 08 May 2017 17:25:00 GMT
Valid Until: Sun, 06 Aug 2017 17:25:00 GMT
Issuer: Let's Encrypt Authority X3

**Comment by clone1018** [comment]
Next steps are moving Common Name to gratipay.com and removing gittip.org and www.gittip.org from our Heroku

**Comment by clone1018** [comment]
www.gittip.org and gittip.org have been removed. We're now:

![image](https://cloud.githubusercontent.com/assets/226638/25822381/169078d4-33fe-11e7-9406-6631185ab3de.png)

**Comment by clone1018** [comment]
Okay grtp.co is potentially solved at https://github.com/gratipay/grtp.co/pull/173

**Comment by clone1018** [comment]
Now I'm thinking about MaxCDN. It's a pain in the butt to generate certs locally, reset FTP passwords, upload well-known files and then upload and change certs. I propose we instead switch to their Shared SSL feature. 

>  Instead of using your own certificate, you use the certificate on our server. The upside of Shared SSL is being able to deliver content securely; the downside is not being able to control your certificate type. You must also share an IP address.
https://www.maxcdn.com/one/tutorial/ssl-options/

I'm not seeing us controlling our certificate type. The migration path is to disable SNI and enable Shared SSL

**Comment by whit537** [comment]
Sounds good to me, @clone1018. I say go for it.

**Comment by clone1018** [comment]
It turns out that MaxCDN has a nice hoverstate on the button mentioning that the Shared SSL product cannot work with your own custom domain and you must use their provided domain, eg `app-company.netdna-ssl.com`. Couldn't find it in their documentation though :(

**Comment by whit537** [comment]
DNS for grtp.co happening in https://github.com/gratipay/grtp.co/issues/174 ...

**Comment by whit537** [comment]
Done for grtp.co in https://github.com/gratipay/grtp.co/issues/174. Also done for `{assets,downloads}`. Docs updated in https://github.com/gratipay/inside.gratipay.com/pull/1059. Now to rip out the ACME challenger ...

**Comment by whit537** [comment]
https://github.com/gratipay/gratipay.com/pull/4452

**Comment by whit537** [comment]
Deployed, closing!
