### ISSUE TITLE
onboard @rohitpaulk

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/inside.gratipay.com#1054]
https://github.com/gratipay/inside.gratipay.com/issues/1053 ditto - to track permission changes

**Comment by rohitpaulk** [comment]
Trying to access Librato... 

I have access to our 1Password, but can't see any shared vaults.

![screen shot 2017-05-05 at 7 48 11 pm](https://cloud.githubusercontent.com/assets/3893573/25749549/8c377b52-31cc-11e7-93e5-8a891883a781.png)

**Comment by whit537** [comment]
Roger that, on my radar.

**Comment by whit537** [comment]
@rohitpaulk Try now?

**Comment by rohitpaulk** [comment]
Worked!
