### ISSUE TITLE
#BackTheStack 2

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#1057]
When we first launched five years ago we ran a campaign called [Back the Stack](https://github.com/gratipay/gratipay.com/issues/142). It's time to run another one.

Open source is in a tragedy of the commons, and there are only two ways to fix a tragedy of the commons: taxation (force) and social pressure (persuasion). We don't have tax authority &hellip; so let's try [social pressure](https://github.com/gratipay/inside.gratipay.com/pull/937#issuecomment-265299879)! 😁

> His first reaction was "You need to organize a strike. If there's no pain then you need to create pain. An amiable strike—just for an hour. You're selling an investment. You're selling prevention. That's difficult. Future pain is not real to them. Open source is opaque. I can assume that if one person gets hit by a bus someone else will take over.

Right, so pain is one option, but it might &hellip; backfire (shall we say) &hellip; if we were to go so far as to manufacture another Heartbleed. ;-)

How about pleasure? Gandy killed it with [FA5](https://www.kickstarter.com/projects/232193852/font-awesome-5). If he can raise $1M for FA on Kickstarter, shouldn't we be able to raise _at least_ $1M for the whole of open source using a similar methodology (timeboxing to manufacture urgency, professional video, perks)?

What would it look like to scale crowdfunding up to corporate scale? Instead of 30 days, six months. Instead of $100,000 as the initial target, $1,000,000. But still stick with the assurance contract: if we fail to reach $1,000,000 in six months, everyone gets their money back.

### Original

Reticketed from #987. @clone1018 and I have been talking about this here in Austin (#948), time to get something down here.

We envision a new product called Round (cf. Bountysource Salt vs. regular Bountysource) starting with a one-off manual #dothingsthatdontscale.

Gratipay Round is an expansion of the fundamental Gratipay process to take place over the course of a year instead of a week—at corporate scale instead of individual scale. It's like one giant payday where we aggregate *a lot* of money at once from as many companies as we can get, and distribute it in one big lump sum to each project. The name comes from the concept of a [funding round](https://en.wikipedia.org/wiki/Venture_round) in venture capital &hellip; we propose to "raise a round for open source." Round up! 😁  A round for opensource! Raise your glass! 🍻  Gratipennies are round! ☺️

First we recruit one or more companies and one or more project maintainers as launch partners, then we launch with a blog post and a landing page at gratipay.com/round. The process itself proceeds in six phases:

1. Sign up companies and move their money into escrow. Deadline: T+28 days.
1. Work with paid-in companies to develop a list of projects (no amounts yet).
1. Reach out to projects from (2) and invite them to participate. Deadline: T+56 days.
1. Finalize allocations with companies. Deadline: T+70 days.
1. Distribute funds, publishing a Distribution Report.
1. Six months later, publish an Impact Report.

That's the basic idea. Gonna see if we can get in some conversations with relevant people here this week—can we find any launch partners? How does it look from over there?

**Comment by techtonik** [comment]
This could be conveniently implemented with blockchain, money can be raised with Initial Coin Offering. I fail to completely see the final gameplay, tough.

**Comment by whit537** [comment]
Overnight brainstorm: use #BackTheStack for this instead of Round. Too much VC parallel will confuse people—this isn't an investment with a profit return.

**Comment by whit537** [comment]
Old #BackTheStack: https://github.com/gratipay/gratipay.com/issues/142.

**Comment by whit537** [comment]
In conversation yesterday @lognaturel suggested starting with projects instead of companies, since it's a certain kind of project that will be willing and able to receive funds (perhaps smaller/simpler rather than larger/complex projects). (Yes?)

I think the question there is whether the presence of committed projects makes it an order of magnitude easier to sign companies up. Because the crucial moment here that we need to achieve once and then replicate is to transfer money from a company bank account into the Gratipay escrow. That is the very hardest thing to achieve here and everything else should be organized around that.

**Comment by whit537** [comment]
For the allocation step (3) we should incorporate scoring to aid decision-making:

- https://libraries.io/unseen-infrastructure
- https://libraries.io/bus-factor
- https://ke4qqq.wordpress.com/2015/02/08/pony-factor-math/
- https://www.coreinfrastructure.org/programs/census-project

**Comment by clone1018** [comment]
I really like "Back the Stack", catchy and marketable.

**Comment by whit537** [comment]
Should we use backthestack.org for this? Looks like that's taken. Dot com?

**Comment by whit537** [comment]
I have a question: who is this for? It's not for _all_ of open source. Lots of open source is sustained just fine by existing models: corporate donations of labor, monetary donations through foundations. We should somehow quantify the segment of open source that we don't think is covered and needs attention and money.

**Comment by whit537** [comment]
I bought `backthestack.com`. The password reset from iwantmyname is visible in Gmail (delegated) but not in Freshdesk. I guess if it doesn't show up in an hour we should ping Freshdesk support about that, we can't be dropping messages.

**Comment by whit537** [comment]
There are two costs to overcome to make this worthwhile:

- On the giver side we need to overcome the **fear of being a sucker**. I need confidence that my peers are _also_ paying to fund the public good with a light-weight [assurance contract](https://en.wikipedia.org/wiki/Assurance_contract).
- On the receiver side we need to overcome the cost of accepting the money. There is a tax headache associated with receiving money, and also potentially a psychological burden of responsibility, so it has to be enough money to make it worth the hassle. We do this by raising a significant enough amount of money.

I like this [rule of thumb](https://gratipay.slackarchive.io/gratipay/page-97/ts-1494062301810260):

> You want to have some sort of very powerful improvement, some order of magnitude improvement, on some key dimension.

Vis-a-vis OC, that means raising $1M. Vis-a-vis LF that means funding hundreds of projects.

**Comment by mattbk** [comment]
> I need confidence that my peers are also paying to fund the public good. 

https://github.com/gratipay/gratipay.com/issues/236

**Comment by whit537** [comment]
@mattbk Yeah but I think we stick with pegging the social element to the community instead of the project. That's part of the value of doing a big campaign like this, we put up a page listing companies involved, and there's enough attention around the campaign itself that the reputational benefit accrues. We can avoid the weirdness of "this company gave me money so I owe them." Fiscal sponsors can buffer some of that as well.

What do you think of pegging non-anonymity to the thing as a whole instead of to individual projects?

**Comment by whit537** [comment]
Can we use 99designs for a logo and website for backthestack.com?

**Comment by mattbk** [comment]
@whit537, I'm afraid I don't follow.

**Comment by whit537** [comment]
Or maybe for illustration?

**Comment by whit537** [comment]
Follow what, sorry?

**Comment by whit537** [comment]
Dropping to [slack](https://gratipay.slackarchive.io/gratipay/page-97/ts-1494282250462026).

**Comment by whit537** [comment]
Current thinking: timebox fundraising to $1,000,000 over six months. That is the smallest amount of money that is interesting, and that is the shortest amount of time that is reasonable to expect giant companies to respond meaningfully within. Think of this as a giant, enterprise-scale Kickstarter. $1M is the low end. We're thinking an actual assurance contract like Kickstarter: if we fail to reach our target, we give back all of the money.

**Comment by clone1018** [comment]
I'm in support of the assurance contract if Gratipay doesn't have to eat the potential banking fees.

**Comment by whit537** [comment]
Current thinking:

First, **Decide for ourselves** whether this is really worth pursuing. Put some numbers on the size of the open source long tail. How much value exists to capture? What are [X and Y](http://startupclass.samaltman.com/courses/lec05/) as applied to open source?

> if you have a valuable company two things are true. Number one, that it creates "X" dollars of value for the world. Number two, that you capture "Y" percent of "X.” And the critical thing that I think people always miss in this sort of analysis is that "X" and "Y" are completely independent variables, and so "X" can be very big and "Y" can be very small. "X" can be an intermediate size and if "Y” is reasonably big, you can still have a very big business.

Then, **approach Indie.vc** (#1034) to help us capitalize this. We need a budget for producing content throughout the six-month campaign—this isn't just a one-time video as with Kickstarter. It's likely six videos, one per month.

Probably this is a business plan to write here.

**Comment by whit537** [comment]
If we can convince ourselves and Indie.vc that this has potential, we will have a lot of confidence to execute. Can we reach a decision with Indie.vc before Sustain (#920)? It would be great to bring that confidence with us, even if we're really just getting ready to start implementation.

**Comment by whit537** [comment]
I've staked out backthestack on Twitter.

**Comment by lognaturel** [comment]
Just popping in to say that "Back the Stack" is a great name! You all are visionaries and I am on a perpetual quest to limit scope so I might not have the best ideas for what you're trying to do.

**Comment by whit537** [comment]
Chat w/ @BenJam in the Libraries.io slack:

> Very interested to hear how you’d distribute a nominal 100k payment to all the project’s dependencies and I think that’s the sticking point. It’s basically the wealth redistribution problem that needs to be solved. Accumulation is being done particularly well by the likes of LF. But distribution less so. Thankfully that’s where we think we can help 
>
>> Ultimately I think the companies themselves have to decide how to distribute. It’s their money to give away, after all. I see two ways to help them: a) surface metrics like bus factor, etc., and b) give them tools to decentralize the task. I see Libraries.io aiding with (a). The idea with (b) is to productize [what Resig did](https://johnresig.com/blog/gittip-at-khan-academy/) w/ Khan’s giving on Gittip back in the day. Each dev had control over a portion of the overall budget.
>
> I would argue that most companies (operating at Enterprise level) don’t want to have to make a decision on which projects they support most. That they would rather believe (rightly or wrongly) that they’re a part of the solution, rather than being crippled by the need to understand everything.
> I think there *is* a place for options. i.e. ‘support CII projects in my stack, vs, support all CII projects’
>
>> Agreed! So probably what we do is have some default weighting based on metrics, with ability for one or more staff to tweak the weightings if desired. Or are you thinking that we have some other set of people that does the allocation?
>
> I think this is equivalent to asking everyone to be the chancellor when all you really need is a bit of lobbying. ultimately I think the watchers should make the decision.
>
>> So you think even the “give us a package.json” step is asking too much?
>
> it’s a hunch, but certainly my take is: organisations willing and able to understand the issue — which in itself is presenting a challenge — are unlikely to want to spend any more time on it than necessary. Paying taxes doesn’t need you to decide exactly how you want your money spent, but you have every right to vote for a candidate that promises to spend more money on bridges than roads.

(P.S. "I’m happy to be quoted on /most/ things on this channel, with the context that it’s an unedited stream of consciousness rather than a well thought out and practiced point of view" :)

**Comment by whit537** [comment]
Alright! Per https://github.com/gratipay/inside.gratipay.com/issues/948#issuecomment-301251090 and https://github.com/gratipay/inside.gratipay.com/issues/987#issuecomment-301754418, this idea met with a weak reception when we presented it to Salesforce and others. By contrast https://github.com/gratipay/gratipay.com/issues/1153 generated some excitement. Therefore, I'm closing this so we can focus on that.

!m *
