### ISSUE TITLE
onboard @clone1018

### ISSUE THREAD

**Issue by clone1018** [gratipay/inside.gratipay.com#1060]

**Comment by clone1018** [comment]
I need Sentry access to see why the site breaks!

**Comment by clone1018** [comment]
I'm in!

**Comment by clone1018** [comment]
I'd like to be able to deploy translations to transifex also. It's part of the deploy.sh script I have to comment out

**Comment by whit537** [comment]
I've invited you as an admin.

**Comment by whit537** [comment]
Alright, @clone1018! #1074 is in and so is https://github.com/gratipay/gratipay.com/pull/4522! It's time for #196!

As the sole member of Gratipay, there's no need for a week-long voting period on whether to invite you. I'm the only one voting! And in terms of wider community input, #196 has been open for 2+ years. ☺️

@clone1018 I invite you to become a member of Gratipay! Do you accept?

**Comment by whit537** [comment]
Per http://inside.gratipay.com/big-picture/operating-agreement.

**Comment by clone1018** [comment]
I gladly accept becoming an owner/member of Gratipay!

**Comment by whit537** [comment]
> Once invited, the individual must provide an SSN or ITIN and consent to this operating agreement in order to become a member of Gratipay.

- [x] consent to operating agreement
- [ ] provide SSN on https://gratipay.com/~clone1018/identities/US

**Comment by clone1018** [comment]
I don't see a SSN field on that?

**Comment by whit537** [comment]
@clone1018 Use "ID TYPE: Tax ID" no?

**Comment by whit537** [comment]
[slack](https://gratipay.slackarchive.io/gratipay/page-100/ts-1497644327916560)

**Comment by clone1018** [comment]
My SSN has been submitted.

**Comment by whit537** [comment]
Now to manually mark your identity as verified ... we have a script for that ...

**Comment by whit537** [comment]
Verified!

```
[gratipay] $ heroku run bash
Running bash on ⬢ gratipay... up, run.7141 (Hobby)
~ $ verify-identity.py 17660 US
[...]
~ $
```

**Comment by whit537** [comment]
Aaaaaaand ... that's it! Welcome aboard, friend. ☺️ 🙇
