### ISSUE TITLE
Does journalism qualify as open work?

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#1063]
https://www.theguardian.com/technology/2017/may/11/tech-innovation-silicon-valley-juicero

I want to give $1 to those guys through my Gratipay balance.

**Comment by whit537** [comment]
Yes! It certainly can. Also, we don't have a hard requirement on "open work" anymore as of #432.

Feel free to recruit the Guardian to join Gratipay! :-)

**Comment by techtonik** [comment]
@whit537 are we ready to share hour to hour story of Gratipocalypse? Using https://cartodb.github.io/odyssey.js/ or https://knightlab.northwestern.edu/projects/#storytelling

**Comment by whit537** [comment]
No? :)

**Comment by techtonik** [comment]
Yea. Dreams and stuff. )
