### ISSUE TITLE
#BackTheStack hashtag

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#1066]
Even though people are not much interested in campaigns and rallies to bring the problem of underpaid ecosystem (#1057), I think there is nothing wrong with reusing hash tag #BackTheStack to bring discussions about funding your open source basis to other parts of Internet.

We should definitely resurrect it with a tag on GitHub projects that work on this problem, add it to Medium posts about the problem, to presentations on fundraising and public projects, and to other sources.

 * [ ] propose it to GitHub projects
 * [ ] get feedback from Medium authors

Sounds good?

**Comment by whit537** [comment]
Go for it! :-)

**Comment by techtonik** [comment]
@nayafia would you be interested to pick #BackTheStack tag, spread the word and apply it to https://github.com/nayafia/lemonade-stand and other projects? =)

**Comment by whit537** [comment]
@techtonik In terms of casting the net wider, https://sustainoss.org/ is the brand that is gaining steam. Probably best to get involved over there, though we already passed on #BackTheStack in favor of #SustainOSS (discussion lost to sands of time in unlogged slack).

**Comment by techtonik** [comment]
SustainOSS is just one day event. Do you think I should apply?

**Comment by whit537** [comment]
@techtonik We do have [travel support](https://sustainoss.org/travel-support/) ... why not! :-)

**Comment by techtonik** [comment]
Applied. I wish there could be more time. Second day is a must, because great ideas come overnight, and even more happens on day 3 with drawing on whiteboards and trying to really prototype things. I would appreciate working with people who can calculate cost of living, and economic capacity.

**Comment by techtonik** [comment]
I think I won't get there even if approved. It is less than a month, and it might be unrealistic to get a U.S. visa in such short period.
