### ISSUE TITLE
Reach sustainability

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#1069]
Definition of done: Chad nets $85,000 out of Gratipay over a 12-month period.

**Comment by whit537** [comment]
I'm making about $6,500/mo from consulting right now and it's more or less the bottom rung of comfortability for our family where we live. That's where the $78,000 comes from.

**Comment by whit537** [comment]
I guess that pays for my current personal Gratipay payments though, so those aren't included. I more meant net conference and travel expenses (#920 #948).

**Comment by whit537** [comment]
Actually though I made more like $8k/mo for the first four months of the year, which is more like $96,000/yr.

**Comment by whit537** [comment]
Might need to put something in here about debt/financing but let's cross that bridge when we get to it. :)

**Comment by JessaWitzel** [comment]
Is this not a ticket anymore because you are looking for full time work or is this still the goal?

**Comment by whit537** [comment]
This is still very much the goal (for me).

**Comment by whit537** [comment]
Alright, gang. Sooooooooo ... @JessWhit and I decided over the weekend that it's time for me to stop working on Gratipay. Like, I quit. I'm throwing in the towel. Giving up. Admitting defeat. Walking away. I'm done. This is it. Fin. The end. All she wrote. End of the road. Last dance. Closing time.

We did so much amazing work last week on #1160! But it wasn't enough. It was too little, too late. Gratipay does not support my family, and isn't going to any time soon. I can't keep working 100-hour weeks like last week, which is what we would have to do for Gratipay to stand a chance of getting back off the ground. And what if it does take off? Growth is stressful, too. For startups, [even success hurts](http://blog.ycombinator.com/three-paths-in-the-tech-industry-founder-executive-or-employee/).

When I launched Gittip I was 33 years old. Now, in a few weeks, I'll turn 39. I have four kids who will start to leave the house soon. I've put my family through a _lot_ over the years, and it's time for me to shift my priorities back to them.

I can stick around through the end of the year to bring Gratipay in for a landing. Mostly though I will be job hunting with the goal of starting a new full-time job in January, 2018.

@JessWhit and I have a couple days head-start on processing this decision. After sleeping on it twice, it still feels like the right decision, so here we are.

I love you all. The thing that has kept me going on Gratipay more than anything all these years is you, the community of people collaborating together on this wild idea called Gratipay. We've tasted the future together, even if Gratipay won't be how it comes about. And you're my friends. 😢  THANK YOU for an amazing five and a half years!

!m * 💃

**Comment by whit537** [comment]
P.S. I called @clone1018 on the phone to break the news, since he's co-owner. Heading to slack now ...

**Comment by timothyfcook** [comment]
Well done. Onward to the vast and endless sea.

**Comment by adamstac** [comment]
Thank you for Chad for all your efforts over the years. Please stay in touch!

**Comment by calvinhp** [comment]
You’re doing good work! ❤️
