### ISSUE TITLE
Let's avoid using the word 'love'

### ISSUE THREAD

**Issue by tshepang** [gratipay/inside.gratipay.com#107]
I feel like we would lose nothing if we stop using the word *love* in our marketing material. Does anyone feel the same? The word is ambigous... what does love mean in the use of Gratipay? To me, admiring someone does not imply that I love them, as in the way I would love a friend, a romantic partner, or a descendant. I guess there are other kinds of love, but it's such an overused word that I feel it should be avoided if possible, unless we agree on exactly on what it means, and Gratipay should not be the place to provide such an explanation. Let's choose more precise words, like *admire* or *enjoy*.

Following is an example from [About](https://gratipay.com/about):

> Gratipay (formerly Gittip) is a way to make small weekly cash payments to people you love and teams you respect.

That line feels like it would be at least as effective (and less mushy) if it was:

> Gratipay (formerly Gittip) is a way to make small weekly cash payments to people and teams you respect.

I see *love* is used a lot in [the Mission](http://inside.gratipay.com/big-picture/mission) Explanation, with things like *Economy of love*. Am sure better words exist, like *Economy of kindness*, for example. Maybe even talk about a job you *enjoy* instead of one you *love*?

Anyways, the Mission itself could be something like:

> Our mission is to enable an economy of gratitude and generosity.

I don't see that as less effective than:

> Our mission is to enable an economy of gratitude, generosity, and love.

----

So, this word is:

* too ambiguous
* too mushy, which can be off-putting

**Comment by mattbk** [comment]
I could get behind this.  I would much prefer something like "people whose ideas you support or whose work you value " or something like that--the key being that Gratipay is for more than just creative endeavors.

**Comment by whit537** [comment]
Closing and moving conversation to https://github.com/gratipay/inside.gratipay.com/pull/431 (I forgot we had a ticket for this).
