### ISSUE TITLE
cashout status May 2017

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#1073]
I just want to check - does cashout currently work for Gratipay funded projects?

**Comment by whit537** [comment]
Yes! We payout automatically via PayPal and can handle Transferwise as a manual method.

**Comment by techtonik** [comment]
```
                        / --> [ Transferwise (manual) ]
[ Gratipay ] ---
                        \ --> [ PayPal (auto) ]
```
What % does PayPal take from 100$ sent from Gratipay?
Does Transferwise sends to bank account or to card number? Again, what is %?

**Comment by whit537** [comment]
Check out faq re: paypal, pretty sure it's there.

Not sure about Transferwise, we've only done one or two of them in the past few years.

**Comment by mattbk** [comment]
> Projects receive payouts via PayPal, which charges 2%. This fee is passed on to the project on payday and is capped at $1 for U.S. PayPal accounts.

https://gratipay.com/about/pricing

**Comment by techtonik** [comment]
This information is too far away. I don't know it it is possible to make it reachable in one click. 

If it is one click, I would also like a button to request my own supported method.

BTW, can we rename Pricing to Fees and reduce text a bit to data (in machine readable format) and a pointer to About page? Because for me Pricing is like a page with different plans.
