### ISSUE TITLE
Reenable invites to Slack

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#1084]
We've somehow flooded our invite queue with garbage invites, and Slack is now preventing us from inviting new folks.

> Please do not revoke invitations in an attempt to lift the limit. Invitation limits are not affected by revoked invitations. They are based solely on the acceptance rate of invitations that have already been sent.

https://get.slack.help/hc/en-us/articles/201330256#invitation_limits

[slack](https://gratipay.slackarchive.io/gratipay/page-100/ts-1495725601642922)

**Comment by whit537** [comment]
@rohitpaulk I think your name is on the invites because you set up our [slackin](http://inside.gratipay.com/appendices/chat). Pretty certain this is due to a security researcher spamming us via [Burp](https://en.wikipedia.org/wiki/Burp_suite). Really it's a security issue with Slackin.

![screen shot 2017-05-25 at 11 33 38 am](https://cloud.githubusercontent.com/assets/134455/26457422/08559d10-413e-11e7-9bf3-25c72eebf907.png)

**Comment by clone1018** [comment]
HackerOne strikes again!

**Comment by clone1018** [comment]
For the record I rejected a couple of invitations to not keep anyone out for now.

**Comment by whit537** [comment]
@clone1018 Doesn't help. 😞 

> Please do not revoke invitations in an attempt to lift the limit. Invitation limits are not affected by revoked invitations. They are based solely on the acceptance rate of invitations that have already been sent.

**Comment by clone1018** [comment]
That's disappointing...

**Comment by clone1018** [comment]
So no one can join our Slack right now unless they have a zetaweb email?

**Comment by whit537** [comment]
> So no one can join our Slack right now unless they have a zetaweb email?

Or something like that, yes.

> That's disappointing...

No kidding. 😞

**Comment by rohitpaulk** [comment]
😑

**Comment by whit537** [comment]
There's a PR to add reCAPTCHA, but it's rather stale: https://github.com/rauchg/slackin/pull/234.

**Comment by whit537** [comment]
Perhaps we just switch to this fork?

https://github.com/avatsaev/slackin

**Comment by whit537** [comment]
Okay, I've deployed the fork to http://inside.gratipay.com/appendices/chat. Now to beg. 😦

![screen shot 2017-05-25 at 5 29 42 pm](https://cloud.githubusercontent.com/assets/134455/26471489/e8a7f3be-416f-11e7-9c1d-0a2c8da51a5f.png)

**Comment by whit537** [comment]
I've cleared out the spam invites. Emailing Slack ...

**Comment by whit537** [comment]
https://gratipay.slack.com/help/requests/new

> Greetings!
>
> We put an insecure version of SlackIn in front of our organization, with the result that spammers filled our invite queue with garbage, and we are now wedged shut. 😞
>
> We have deployed a secure version of SlackIn that uses reCAPTCHA to avoid spam, and we have removed the garbage invites. Would you be willing to reset the invite limit on our account? Pretty please? 😬
>
>
>chad
>
P.S. Details at https://github.com/gratipay/inside.gratipay.com/issues/1084.

**Comment by whit537** [comment]
> I'm afraid I cannot look into your limit until a higher number of invites have been accepted (at least 50%). Please reach back out once you have hit this threshold, and I can revisit this for you.
>
>In the meantime though, I'd be happy to send you a shared invite link. You can send it to the people you'd like to invite to your team, so they can create accounts and join.
>
>If you're interested, please let us know the following:
>
> 1. Your team's URL (i.e., teamname.slack.com)
> 1. How many days you want the link to be valid (up to 30 days total).
> 1. The maximum number of signups you want this link to allow (up to 1000 new signups).
>
>Once I have this information, I'll generate a shared invite link and send it to you.

**Comment by whit537** [comment]
> Thanks for the reply, []. This sounds complicated. :-(
>
>As I understand it, it's not going to be possible for us to get back to the 50% threshold without some help. The reason is that we used [SlackIn](https://github.com/rauchg/slackin) to allow anyone on the Internet to initiate an invite. What happened is that a spammer or security researcher took advantage of this to flood our invite queue with garbage invites. So we have 50 pending invites that will never, ever be accepted. :-(
>
>I'm not sure what a "shared invite link" is, but if that's going to be the only way to allow people to join our Slack and get our accept ratio back up, I guess let's go for it. Please make it out for gratipay.slack.com for 30 days and 1000 invites, and when we hit one of those limits ... I guess I will ask you for another one?

**Comment by whit537** [comment]
> Thanks for the response Chad. I'm sorry about the circumstances here, and I wish I could offer a more elegant solution. :( Feel free to reach out when the link does expire, and I'll be more than happy to create another for you (if you haven't hit the 50% invite threshold by then).
>
>I’ve just enabled a link that up to 1,000 people can use to join Gratipay. It will expire on Sunday, June 25th. If you need to, you may deactivate the link before then. Here is the link for you to copy and share: https://join.slack.com/gratipay/shared_invite/MTg4NjAyODY4NjkxLTE0OTU4MTY0MzEtZWM4Mjc2YWYxNA
>
>You'll also receive a Slackbot notification with additional information. If you'd like, you can view, deactivate, or generate a new link by going to https://my.slack.com/admin/shared_invites.
>
>Again, my apologies for the less than ideal solution here. Please let me know if you have any trouble!

**Comment by whit537** [comment]
PR to switch from SlackIn + reCAPTCHA to shared invite in https://github.com/gratipay/inside.gratipay.com/pull/1085.

**Comment by whit537** [comment]
Looks like we might be able to generate our own in the future vs. contacting support?

![screen shot 2017-05-26 at 12 46 04 pm](https://cloud.githubusercontent.com/assets/134455/26504130/511fa7c4-4211-11e7-812f-3968a77e0657.png)

**Comment by whit537** [comment]
> The link will need to be regenerated by us once it expires (a tedious process, I know). This is why it isn't listed in our help center.

**Comment by whit537** [comment]
Slack has made shared invite link generation self-service. I think we should abandon SlackIn entirely.

**Comment by whit537** [comment]
I've added a recurring event on the 24th to [the calendar](http://inside.gratipay.com/appendices/calendar).

**Comment by whit537** [comment]
Docs in #1135. I've deleted the `gratipay-slackin` app at Heroku.
