### ISSUE TITLE
HowTo run support is 404

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#109]
http://inside.gratipay.com/howto/run-support is 404 linked from http://inside.gratipay.com/howto/onboard-yourself.

Does Aspen has some kind of DB for broken link tracking? (like wiki system does)

**Comment by whit537** [comment]
Definitely a bunch of broken links:

![screen shot 2015-04-01 at 1 11 12 pm](https://cloud.githubusercontent.com/assets/134455/6946763/9e169da6-d870-11e4-8407-f87415d431c5.png)

**Comment by techtonik** [comment]
I was trying to find some link checker wrapped into Python package that can be run locally.

**Comment by techtonik** [comment]
To be honest, I started to design one from scratch following a https://www.udacity.com/course/intro-to-computer-science--cs101 search engine tutorial.

**Comment by whit537** [comment]
http://inside.gratipay.com/howto/onboard-yourself is now folded into http://inside.gratipay.com/big-picture/welcome. Closing!
