### ISSUE TITLE
Add BitPay support

### ISSUE THREAD

**Issue by jhabdas** [gratipay/inside.gratipay.com#1094]
Throwing this in the mix since I'm picking it up to accept Bitcoin as a trial for my FOSS development efforts and donation-based mentoring. I have Stripe and PayPal integrated with my [AND CO](https://www.and.co/) account for professional services, but they rob me with transaction fees and I'd like to use the gratipay badge on my GH/Gitea repos when accepting donations for GNU/FSF/etc. related work.

https://bitpay.com/docs/donations

Most popular repo: https://github.com/bitpay/bitcore

payin info: https://bitpay.com/pay-with-bitcoin
payout info: https://bitpay.com/bitcoin-payouts

pricing: https://bitpay.com/pricing 

related: #974

**Comment by whit537** [comment]
Thanks @jhabdas. We have an account with Coinbase that we've used in the past, if/when we get back to bitcoin I think it makes sense to evaluate vendors then.

**Comment by jhabdas** [comment]
Sounds good. I saw Coinbase cannot support the US yet. But their mobile app is stellar and Coinbase supported in 33 countries worldwide. But the need is clear. And cryptocurrencies are taking off so quickly I'm not sure regulation in the States is going to be able to keep up.

http://coin.dance/
