### ISSUE TITLE
Tone and Messaging

### ISSUE THREAD

**Issue by mtrythall** [gratipay/inside.gratipay.com#11]
I know @whit537 is going to roll his eyes at this!

But we should think about defining some high level *suggestions* for how Gittip communicates. While individuals may shine at times, Gittip as a *thing* should be consistent.

This is strictly a design requirement. Uniformed tone and messaging creates a consistent and therefore trustworthy user experience.

**Comment by whit537** [comment]
Considering this initially addressed with the brand page, which is now at http://inside.gratipay.com/big-picture/brand/.
