### ISSUE TITLE
Interpret and filter CSP reports

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#1118]
With https://github.com/gratipay/gratipay.com/pull/4542 we are now sending CSP reports to Sentry, which makes them much more visible. That's great! But there's a lot of them. What do they mean? How should we process them?

**Comment by whit537** [comment]
They all use the `csp` logger:

https://sentry.io/gratipay/gratipay-com/?query=logger%3A%22csp%22

**Comment by whit537** [comment]
![screen shot 2017-07-18 at 2 41 05 pm](https://user-images.githubusercontent.com/134455/28341123-24c0bf44-6bc7-11e7-9925-800957e32fe0.png)

**Comment by whit537** [comment]
Worst addressed in https://github.com/gratipay/gratipay.com/pull/4552.

**Comment by rohitpaulk** [comment]
I've turned off notifications (slack/email) for `logger:csp` on Sentry due to the noise.

**Comment by whit537** [comment]
Sorta defeats the purpose, but understandable for now. 😛

**Comment by whit537** [comment]
https://github.com/gratipay/gratipay.com/pull/4552 doesn't solve the `style-src` problem in `widget.html`. We're [still getting](https://sentry.io/gratipay/gratipay-com/issues/310768669/) CSP violations, and Chrome is showing a different hash:

![screen shot 2017-07-24 at 7 10 19 am](https://user-images.githubusercontent.com/134455/28524817-4b4574ee-703f-11e7-96c5-475b233f0e88.png)

How is the hash computed, I wonder?

**Comment by whit537** [comment]
Ah! We have variable URLs in there, for assets.

```

<style>
--
  | body {
  | margin: 0;
  | padding: 0;
  | overflow: hidden;
  | }
  | button {
  | font: normal 12pt/12pt "Lato", sans-serif;
  | text-decoration: none;
  |  
  | width: auto;
  | overflow: visible;
  | display: inline-block;
  | cursor: pointer;
  |  
  | border: 1pt solid #999;
  | border-radius: 7pt;
  |  
  | background: #F7F7F6 url("https://assets.gratipay.com/button-bg.png?etag=HDqGyL5qCGOoHnue-Gh6uw~~") repeat-x bottom left;


```

**Comment by whit537** [comment]
Lol, and etags, so it's variable per-deploy. 🙈

**Comment by whit537** [comment]
Alright, back to the drawing board. 😛

**Comment by whit537** [comment]
@/mattrobenolt suggests (IRL at PyOhio) that we send CSP reports to a separate project for better filterability.
