### ISSUE TITLE
Let gratipay-or-bountysource.guide lapse

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#1128]
I put up http://gratipay-or-bountysource.guide/ once when I was freaking out about https://github.com/gratipay/inside.gratipay.com/issues/316. I don't think we need it anymore (if we ever did) and am ready to let the domain lapse. It's $39/yr we could spend elsewhere. Any objections?

**Comment by mattbk** [comment]
Agree.

**Comment by whit537** [comment]
The way iwantmyname.com works is that they bill you before the renewal takes place. So we've already paid but the renewal doesn't happen until September 12. Until then there is no "Cancel" knob in the UI. I've emailed support asking if we cancel the renewal and get a refund.

**Comment by whit537** [comment]
> I have cancelled the renewal for gratipay-or-bountysource.guide and have issued a refund which will appear on your credit card statement within 7 business days.\*

https://gratipay.freshdesk.com/helpdesk/tickets/9334
https://gratipay.freshdesk.com/helpdesk/tickets/9336
\*https://gratipay.freshdesk.com/helpdesk/tickets/9339
https://gratipay.freshdesk.com/helpdesk/tickets/9342
