### ISSUE TITLE
Add donation to shields.io to budget

### ISSUE THREAD

**Issue by mattbk** [gratipay/inside.gratipay.com#1133]
Since we seem to get getting a bunch of new projects from them (awareness, #1114), we should support them. https://gratipay.com/shields/

**Comment by whit537** [comment]
How much should we pay? What is the value we get from them?

- they host Gratipay badges for us
- they send us traffic
- we use some of their other badges on our own README

Looking through our [budget](https://docs.google.com/spreadsheets/d/1p3DpF9ZLEsViBx0685FwJaYN1vVScKVUgXHb2zyqXZg/edit#gid=1) I think they should be down towards the bottom. How about $1/wk?

**Comment by mattbk** [comment]
I am happy with that.
