### ISSUE TITLE
Apply for YC W2018

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#1139]
&larr; [S2017](https://github.com/gratipay/inside.gratipay.com/issues/1017)

- https://apply.ycombinator.com/
- [**Working draft**](https://docs.google.com/document/d/1lIgRz4pgb40D_yWI4r-DFIz686p7haCcg_hgcXZ1k6c/edit?usp=sharing)

**Comment by whit537** [comment]
@clone1018 I guess this time around you are officially a co-founder! :D

**Comment by whit537** [comment]
Deadline [last year](https://github.com/gratipay/inside.gratipay.com/issues/836#issuecomment-251426413) was October 4. That's 55 days away.

**Comment by clone1018** [comment]
For the record my other venture will also be applying for YC in this batch. I am down for full support for either but not both. Let me know what you want to do @whit537 .

**Comment by whit537** [comment]
Wellllll ... I was definitely planning to apply. Do you want to apply with me or not?

@rohitpaulk I was actually gonna ask you if you would be interested in joining for YC if accepted?

**Comment by whit537** [comment]
@kaguillera IRL has expressed willingness to reapply.

**Comment by rohitpaulk** [comment]
> @rohitpaulk I was actually gonna ask you if you would be interested in joining for YC if accepted?

I can't commit to full-time work, but I'd be willing to help as usual.

**Comment by whit537** [comment]
> I can't commit to full-time work, but I'd be willing to help as usual.

Okay, cool. The question at this point is who we should put down as co-founders on our application. Sounds like that's not the right fit for you right now. 👍

**Comment by whit537** [comment]
Basically, we *have* to put @clone1018 and I as co-founders, since we are in fact the co-owners of the legal entity. If @clone1018 can't commit to being in Mountain View for three months or even participating at all due to conflict w/ his other venture that is fine, we'll just have to note it on the application.

So at the point it looks like it will be @whit537 @clone1018 @kaguillera?

**Comment by clone1018** [comment]
I don't think choosing between the projects will be a decision I have to make. The chances of two projects I'm attached to getting into YC is astronomical. I can commit to being in Mountain View for three months and giving my support to Gratipay.

**Comment by whit537** [comment]
Woo-hoo! 💃 

!m @clone1018

**Comment by whit537** [comment]
Applications are due in 9 days.

> Thank you for applying for the Y Combinator Summer 2017 batch.
>
> Of all the companies we accept, 40% have applied more than once, and some applied several times.  We find that the best teams don't give up easily, and keep building their startups. These are the teams we love to see apply again.
> 
> So, if you've made progress with your startup, we invite you to reapply for the Winter 2018 batch.  We've even made it easy - all you need to do is update your application with what's changed.  
> 
> Applications are now open and the deadline is **October 3rd at 8pm PT**.

**Comment by whit537** [comment]
@clone1018 and I are going to try to record a video here. We texted @kaguillera but he is MIA on paternity leave. 😶

**Comment by whit537** [comment]
Video take 1! https://www.youtube.com/watch?v=RkLokvI7egY

**Comment by whit537** [comment]
Take 2: https://www.youtube.com/watch?v=Vaxl7wqtCdY

**Comment by whit537** [comment]
Take 3: https://www.youtube.com/watch?v=2kdhUK8ZeFE

**Comment by whit537** [comment]
Take 4: https://www.youtube.com/watch?v=-2EfRj2rp6M dern buzzer! 😜

**Comment by whit537** [comment]
Take 5: https://www.youtube.com/watch?v=Gr9-Iq5-7f8

**Comment by whit537** [comment]
Clipped at front, copied and this seems fine:

https://www.youtube.com/watch?v=hHpC76oTqIo

Okay! We have a video! 💃  📺

**Comment by whit537** [comment]
Application submitted, will post answers in a bit.

**Comment by whit537** [comment]
> Thanks for applying to Y Combinator. We're sorry to say that your startup was not selected to interview for the upcoming Y Combinator batch. Please don't take it personally. We carefully reviewed thousands of applications and since there's a limit on the number of startups we can interview in person, we had to turn away a lot of promising companies.
> 
> Unfortunately we can't give you individual feedback about your application. [This page explains why.](http://www.ycombinator.com/whynot/)
> 
> We're always trying to get better at this. It's alarming how often the last group to make it over the interview threshold ends up getting accepted to YC. That means there are surely other good groups that fall just below the threshold.
> 
> It's practically certain that groups we rejected will go on to create successful startups. If you do, we'd sincerely appreciate it if you'd send us an email telling us about it; we very much want to learn from our mistakes.
> 
> We hope you reapply for the next batch. In fact, we encourage it. Applying multiple times in no way counts against you and a surprisingly large number of companies are funded after applying more than once.
> 
> Best of luck,
> 
> —YC
