### ISSUE TITLE
onboard @buddiex

### ISSUE THREAD

**Issue by buddiex** [gratipay/inside.gratipay.com#1144]
Hello!!!

Excited to be here!. my first opensource adventure.

What do i need to do next :)

**Comment by whit537** [comment]
Welcome! Have you had a chance to try [installing Gratipay locally](https://github.com/gratipay/gratipay.com#quick-start)? What operating system are you on?

**Comment by buddiex** [comment]
I gat it working using docker.

**Comment by whit537** [comment]
Per [slack](https://gratipay.slackarchive.io/gratipay/page-100/ts-1503679792000058), I've invited @buddiex to the GitHub org and Gratipay team in order to view our project boards and contribute to the project.
