### ISSUE TITLE
Make a video

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#1155]
So I met a guy Rich (here at [Paramount](http://paparamount.com/)) who does [digital marketing](http://flashpoint.agency/), and he knows a guy Mike who does [video](https://groww.io/) and especially animated intro videos, and the two of them might be interested in joining our [twyw team](https://gratipay.com/Gratipay/distributing/) to help us market https://github.com/gratipay/gratipay.com/issues/4427.

So far I've been talking to Rich, catching him up on where we're at, the state of the market, and where we're headed. If we end up working together we'll no doubt have more tickets emerge, this seemed like a good place to start because it's something I've thought about when I think about a crowdfunding-style campaign like #1057.

**Comment by whit537** [comment]
I just watched Joseph Gordon-Levitt give a keynote at #1044, and learned about [HITRECORD](https://hitrecord.org/), which is GitHub for movies. I've signed up for an account. Can we use it to make a video?

https://hitrecord.org/challenges/new

![screencapture-hitrecord-org-challenges-new-1505236543648](https://user-images.githubusercontent.com/134455/30339279-5bae991a-97a3-11e7-9817-891af4b89004.png)

**Comment by whit537** [comment]
Rich and I are supposed to have a call with Mike on Twitter.

**Comment by JessaWitzel** [comment]
Hey! Did this call materialize?

**Comment by whit537** [comment]
No. I called Rich today and he sent an email to Mike and I, going to try to get on a call again this week but it's almost certainly too late to land this before Oct 2 for #1160.

**Comment by whit537** [comment]
Call w/ Rich this pm at 4, then tomorrow w/ Mike at 2 pm.

**Comment by whit537** [comment]
https://go.indiegogo.com/blog/2010/12/6-tips-for-a-good-pitch-video.html

**Comment by whit537** [comment]
Unfortunately a good video is a really important part of a crowdfunding campaign. Maybe @hurlothrumbo would help me make one at [Stack](http://www.stackpgh.com/) on Monday?

**Comment by whit537** [comment]
I started [a project on HITRECORD](https://www.hitrecord.org/projects/3335320/interests/all). 🙈

**Comment by whit537** [comment]
Whether or not anything comes through off of HITRECORD it was at least helpful to resolve the project into component parts.

I think what we want is a 30-second clip introducing Gratipay in general that can stand on its own (for when we're _not_ campaigning) and a second 30-second clip of me talking and pitching #BackTheStack in particular (but still in a way that can be reused in January so we don't _have_ to finish another video before then). Here's the text I came up with for the first part:

> Open source software is all around us. It’s in our phones, our cars, our banks and hospitals. Our companies and our society depend on it.
>
> But where does it come from?
>
> Half of open source comes from employees working on company time, and it gets paid for through developer salaries.
>
> Gratipay is the easiest way to pay for the other half, the half that’s written by the world-wide volunteer open source community.

And here's for the second part:

> Hi, I’m Chad Whitacre, founder of Gratipay. During our #BackTheStack campaign, we’re inviting your company to join a movement to pay for open source software. Open source makes your developers 20% more productive. Paying for open source increases innovation, and reduces risk. Show your leadership by investing in the volunteer open source community. Pay for open source today on Gratipay.

I could voice both parts or just the second.

I envision some sort of live footage behind the first part (woman staring out the passenger window of a moving car while fiddling with her phone? people working on laptops?), and me talking for the second part.

**Comment by hurlothrumbo** [comment]
This all sounds good to me. We should be ready to shoot this tomorrow at Stack, with camera op & equipment.

Suggested rewrite for first section:

> Open source software is all around us -- in our phones, our cars, our banks and hospitals. It fills the gaps between better known products. We don't always know when we're using it. But our companies and our society depend on it.
> 
> But who makes open source software?
> 
> Half of open source comes from employees working on company time, and it is paid for by these companies through the developers' salaries.
> 
> The other half is written by the world-wide volunteer open source community, on spec and simply because it is needed. We've come up with an easy way to start paying for this half: Gratipay.

**Comment by whit537** [comment]
Agree first section could use some work. Audience is a) managers at companies with budget authority to pour money into https://gratipay.com/, and b) developers at companies who will lean on their managers to pour money into https://gratipay.com/. Theoretically they already know about open source software. We are reminding them that it exists and that they do in fact want to pay for it wink wink nudge nudge.

**Comment by whit537** [comment]
This is clocking in at about 33 seconds:

> Open source software is tucked away in our phones, our cars, our banks and hospitals. Our companies and our society depend on it.
>
> Half of open source comes from employees on company time. The other half comes from a world-wide network of volunteers that also needs to be paid. Too much is at stake not to pay for open source.
>
> Gratipay is the easiest way to pay the open source community, so that it can continue to provide the high quality, low cost software that your company relies on.

**Comment by whit537** [comment]
The latter part is about 25 seconds, so we should be able to keep the vid under 60 seconds total.

**Comment by whit537** [comment]
Worked on memorizing this on the bus in:

1. Open source software is tucked away in our phones, our cars, our
banks and hospitals.

2. Our companies and our society depend on it.


-----------------------


1. Half of open source comes from developers working on company time.

2. The other half comes from a world-wide network of volunteers, and they need
to be paid, too.

3. There's too much at stake not to pay the volunteer open source community.


-----------------------


1. Gratipay is the easiest way for your company to pay the open source
community for the software you actually use.


-----------------------


1. Hi, I'm Chad Whitacre, founder of Gratipay.

2. During our #BackTheStack campaign, we invite your company to join the
movement to pay the open source community.

3. Demonstrate your leadership.

4. Invest in the open source community today, on Gratipay.

**Comment by whit537** [comment]
Shooting wrapped, back at the apartment to edit. Hoping there's enough footage to put together something usable!

**Comment by whit537** [comment]
Rough cut: https://www.youtube.com/watch?v=o8f_Mkhf99g

Content is all wrong in light of https://github.com/gratipay/gratipay.com/pull/4658, but we're ready for feedback on the general vibe.

**Comment by whit537** [comment]
Got a second round of footage on the roof, @ChrisECJohns is working up another cut. Hoping we'll have time for a third round of footage if needed before final edit.

**Comment by whit537** [comment]
[slack](https://gratipay.slackarchive.io/gratipay/page-100/ts-1506781216000027)

**Comment by whit537** [comment]
Draft 2: https://www.youtube.com/watch?v=oYZPllSsH-4

**Comment by whit537** [comment]
Sounds like content clips and b-roll really need to be edited together. Hopefully we have what we need! :D

**Comment by whit537** [comment]
Final Draft: https://www.youtube.com/watch?v=W_dnzfpmpG4

**Comment by whit537** [comment]
Okay! Video is good. !m @ChrisECJohns 💃 

Can we make it great? 😄 

From @EdOverflow in [slack](https://gratipay.slackarchive.io/gratipay/page-100/ts-1506862567000055):

>The video starts with a loud and sudden static sound.
>Like a "click".
>I would recommend: 
> - Adding #BackTheStack somewhere in the video;
> - Cutting to gratipay.com at some point with the narration in the background. Show how Gratipay works when entering details in the new landing page.

There are a few more content changes I would like to see if we can manage it. Planning to give @ChrisECJohns a call and see what's possible in the next few days.

**Comment by whit537** [comment]
Okay! Just spoke with @ChrisECJohns by phone. We are planning to meet at Stack tomorrow morning at 8 am to film a few more pieces, which I am going to script before we arrive.

**Comment by whit537** [comment]
Script so far:

https://docs.google.com/a/zetaweb.com/document/d/1tRswcgQ9MK_BXgnyOPVJNw-VBiHrUvr9osedsUU78hc/edit?usp=sharing

**Comment by whit537** [comment]
Alright, I think we can do this as follows (suggested edits on the doc):

1. Replace "And that's what we're working on at Gratipay." (0:35) with new content along these lines: "At Gratipay, we’re asking, 'What if we ran a funding campaign for the entire open source community?' And that’s what the #BackTheStack campaign is about. We want to make it easy for every company to be part of a shared investment in open source."
1. Cut "So we’re excited to give your company a chance to participate in this shared investment." and run straight into "The wonderful thing about a shared investment [...]".
1. Move the bit about Libraries.io to after the shared investment bit.
1. Cut from "Talk about the value" and replace with new content as follows: "Talk with your team and ask, how much more productive does open source make us? Put a dollar figure on it. Start with even just $1,000 per developer per year. Divide it into quarterly installments, that’s $250 per developer that we’re inviting you to invest in open source. Go to Gratipay.com and fill out the form. We’ll send you an invoice, and we’ll follow up with a report on the impact that your investment had in the open source community."

**Comment by whit537** [comment]
So that's two new chunks of content we need to capture, plus some rejiggering.

Then:

- fix the click at the beginning
- show #BackTheStack during "And that's what ... is all about"
- show gratipay.com over top of the call to action at the end
- fade audio at the end
- trim before rendering

**Comment by whit537** [comment]
Wrapped third shoot, went over the above ^^^ with @ChrisECJohns, aiming for another cut in a day or two. Hopefully final! 💃

**Comment by whit537** [comment]
Got a phone call from @ChrisECJohns, he is aiming to ship something tonight. 👍

**Comment by whit537** [comment]
This thing is looking AWESOME in situ. 😍 

![screen shot 2017-10-04 at 8 37 24 pm](https://user-images.githubusercontent.com/134455/31206108-e0c7ae32-a943-11e7-9428-bda2a9c0d4eb.png)

**Comment by whit537** [comment]
Here's a #BackTheStack logo.

![backthestack](https://user-images.githubusercontent.com/134455/31206121-ecd368a6-a943-11e7-9e37-a09a7efc68d5.png)

**Comment by whit537** [comment]
Final: https://www.youtube.com/watch?v=prJmlm2n5Tg

I say "$250" instead of "$250 per developer." 😞

Needs subtitles.

**Comment by whit537** [comment]
Landing in https://github.com/gratipay/gratipay.com/pull/4671.

**Comment by whit537** [comment]
Closing! So amazing, @ChrisECJohns. Awesome work! THANK YOU!!!!!!!!!!!!! 🙇  🙏  💗

Reticketing captions as https://github.com/gratipay/inside.gratipay.com/issues/1195.
