### ISSUE TITLE
Partner with OSI

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#1161]
@massonpj and I talked at OSSummit (#1044) about a partnership between Gratipay and the [Open Source Initiative](http://opensource.org/), especially in view of Gratipay's relaunch (#1160):

- [x] **Pre-req:** Gratipay relicenses its software using OSI-approved licenses (CC0 [is out](https://opensource.org/faq#cc-zero)). 😬 
- [x] Gratipay donates $250 to the OSI ([$1,000 tier](https://opensource.org/sponsors) prorated for ~three months left in the year).
- [x] Gratipay puts the OSI logo on the homepage, with text like "In partnership with ..."
- [ ] OSI puts Gratipay logo on https://opensource.org/sponsors
- [x] Gratipay only funds projects that use OSI-approved licenses.

**Comment by whit537** [comment]
> Gratipay relicenses its software using OSI-approved licenses

- `gratipay.com`: https://github.com/gratipay/gratipay.com/pull/4626
- `grtp.co`: https://github.com/gratipay/grtp.co/pull/183
- `simplate.vim`: https://github.com/AspenWeb/simplate.vim/pull/14
- `postgres.py`: https://github.com/gratipay/postgres.py/pull/62

**Comment by whit537** [comment]
> - [&hellip;]
> - Gratipay only funds projects that use OSI-approved licenses.

Should add:

- Gratipay and OSI cross-promote each other! 💃

**Comment by mattbk** [comment]
> Gratipay only funds projects that use OSI-approved licenses.

This applies to the new homepage funding model, right? Others will still be able to give to projects regardless of license?

**Comment by whit537** [comment]
> This applies to the new homepage funding model, right? Others will still be able to give to projects regardless of license?

Yes. Yes, I expect so, but we should be clear on that with @massonpj.

**Comment by whit537** [comment]
Could this play into https://github.com/gratipay/inside.gratipay.com/issues/1168?

**Comment by whit537** [comment]
Aiming for a call in ~1hr.

**Comment by whit537** [comment]
Just wrapped the call. We are good to proceed as outlined above. Also talked about #1168 a bit.

**Comment by JessaWitzel** [comment]
I'd love to hear opinions in light of our convo on Slack.

**Comment by whit537** [comment]
Membership dues: paid!

**Comment by whit537** [comment]
OSI logo on Gratipay homepage will come under https://github.com/gratipay/gratipay.com/pull/4648.

Gratipay logo on https://opensource.org/sponsors ... I mailed this logo file.

![gratipay](https://user-images.githubusercontent.com/134455/30833149-b94e10e6-a21b-11e7-9aaa-d6d09fd4ce4c.png)

**Comment by whit537** [comment]
Final relicense held up by a CI failure ... https://github.com/gratipay/postgres.py/pull/62

**Comment by whit537** [comment]
> I mailed this logo file.

Also apprised @massonpj of our plans on https://github.com/gratipay/inside.gratipay.com/issues/1160.

**Comment by whit537** [comment]
Relicensing: done!

Last TODO on here is getting the Gratipay logo on https://opensource.org/sponsors. ☺️ 

![30833149-b94e10e6-a21b-11e7-9aaa-d6d09fd4ce4c](https://user-images.githubusercontent.com/134455/31049437-1adc1022-a601-11e7-885e-222985c4240c.png)

**Comment by massonpj** [comment]
Up: https://opensource.org/sponsors Can you please check the links?

So let me add some to do's...

* Press release announcing sponsorship. I can draft something and send it over. Can you please provide
  * a few quotes on why Gratipay is sponsoring the OSI; value of open source/OSI; etc.
  * boilerplate for "About Gratipay"
* Confirm @whit537 that you're our "Sponsor Contact."
* Send me social media account info

Thanks all - Patrick

**Comment by whit537** [comment]
So awesome, @massonpj. Thank you! 🙇 

Confirmed I am the sponsor contact. chad@gratipay.com +1-412-925-4220

https://twitter.com/Gratipay and https://www.facebook.com/Gratipay for social

Quotes:

> The first step in managing a shared investment in a commons such as open source is to clearly define the boundaries of the commons, and OSI has been the international steward of the open source definition since the beginning. OSI's work is therefore a key enabler for Gratipay's goal of making it easy for every company to invest in open source together. We're excited to sponsor OSI and build the open source movement with them!

Boilerplate:

> Gratipay is the easiest way for companies to invest in open source together. Since launching five years ago, we've helped dozens of companies invest over $1 million in hundreds of open source projects. This month we are launching #BackTheStack, the first ever joint funding campaign for the entire open source community. Visit https://gratipay.com/ to learn more and get involved.

S'okay?

**Comment by whit537** [comment]
@massonpj After an overwhelming week last week trying to [launch](https://github.com/gratipay/inside.gratipay.com/issues/1160) the #BackTheStack marketing campaign, I've decided that I don't have the energy to invest to make the campaign a success, and that after 5 1/2 years it's time for me to be [done with Gratipay](https://github.com/gratipay/inside.gratipay.com/issues/1069#issuecomment-335488726).

Our team is [working out](https://github.com/gratipay/inside.gratipay.com/issues/1196) the implications of my departure for Gratipay overall. In the meantime we should probably hold off on any press release or other shared promotion with OSI.

Sorry for the sharp left turn, hopefully I'm catching you in time to avoid too much wasted effort.

Thanks for being willing to partner with us! All the best in supporting projects that support open source!

**Comment by massonpj** [comment]
Gulp! Was it something I said? Coming in new, I'm simply not aware of all the work and stress you and the Gratipay folks have had--I am sure this was a tough decision and not taken lightly. Let me know if there is anything I can do for you, the project, or even other folks working with you (sorry I was not able to meet more of them). 

Also, I am happy to refund the sponsorship contribution if Gratipay is winding down.

Patrick

**Comment by whit537** [comment]
Thanks @massonpj. Nothing you said, of course. :) Happy to let the sponsorship contribution stand, we should've linked up with you years ago. Keep up the good work!
