### ISSUE TITLE
Distribute funds

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#1162]
Placeholder for conversation about how to distribute funds gathered via the [new homepage](gratipay/gratipay.com#4598), once we have funds to distribute. 😬

So far I've got a conversation going with the JS Foundation (and the Linux Foundation by extension). Should reach out to PSF as well?

**Comment by whit537** [comment]
Thinking about various methods as tied to goals at https://github.com/gratipay/inside.gratipay.com/issues/1177#issuecomment-333268514.

I think we should try distributing the first $100,000 using Libraries.io data.

**Comment by whit537** [comment]
https://libraries.io/experiments/unseen-infrastructure

or https://libraries.io/search?q= which is by Source Rank — top 1,000 that respond within 30 days, weighted by Source Rank?

Would need to come up with an email contact list based on either set and mail them to see who wants to participate.

**Comment by whit537** [comment]
In the video #1155 we are heading towards using footage that talks about "partnering with Libraries.io to fund unseen infrastructure."

**Comment by andrew** [comment]
👍 happy to help mine to email addresses from the top 1000 projects repositories

**Comment by whit537** [comment]
> 👍 happy to help mine to email addresses from the top 1000 projects repositories

Love it, thank you! Also bringing in @BenJam's comments from https://github.com/gratipay/inside.gratipay.com/issues/1160#issuecomment-333520144. Can we reach a decision on unseen-infra vs. digital-infra vs. top-1000?

>> gets split however Libraries.io sez we should split it.
>
>^ easier said than done. Certainly there's a function of splitting the money by 
>
>* the amount the thing is used
>* the amount of support the thing already has
>* the amount of people already working on it
>* the amount of work the project looks like it already has
>
>I think the [/unseen-infrastructure](https://libraries.io/experiments/unseen-infrastrcuture) list is a better starting point than  the [/digital-infrastructure](https://libraries.io/experiments/digital-infrastruture) list as there are good indicators that those projects need more support, but it won't solve all your problems. 
>
>@andrew and I have been thinking about collecting data on a project's financial support. We'll spike that out tomorrow together: https://github.com/librariesio/libraries.io/issues/1744

**Comment by whit537** [comment]
## Proposal

_For first $100k, will decide beyond that as it becomes clear that we'll need to ... ☺️_

- Scope to unseen-infra.
- Mine emails—how many uniques will we find, I wonder?
- Compute distribution ratio according to number and rank of unseen projects.
- Send offer ... "We would like to offer you at least $___ for your work on ____. [Click here] within 30 days to claim this offer."
- Claiming offer means agreeing to some terms from us:
  - contractor relationship w/ Gratipay, LLC, essentially
  - something about expectation—doesn't bind to specific work, but we will report on number of bugs fixed, etc. and the more stories the better
- After thirty days we calculate final amounts based on who has opted in, and send out payments as lump sum via PayPal.

**Comment by andrew** [comment]
I wonder what percentage of /unseen-infra have no active person behind them, compared to /digi-infra 🤔 

Another potential would be to put the offer up in public for work on the project if the project is active enough to be confident there will be someone to merge prs? Although that only really covers code contributions, much more tricky to manage some kinds of non-code contributions.

**Comment by BenJam** [comment]
Proof of work is a difficult problem to solve. its easiest if you set the task first but then the problem you are likely trying to solve is paying for time to set the tasks.

If you have pure donation on one side and contractor relationships on the other is it still a donation? What are you promising anyone who donates? If there are no promises then I would try to keep away from the difficult problems :)

**Comment by mattbk** [comment]
IMHO the funds should be untied from specific work. That's been the Gratipay model thus far, as opposed to the Bountysource model (pay $ for specific work) or the Patreon model (pay $ for general work but you get unrelated perks back).

**Comment by whit537** [comment]
> Another potential would be to put the offer up in public for work on the project if the project is active enough to be confident there will be someone to merge prs?

If it's active enough to accept funds then it's active enough to farm out to others w/o us getting in they, no? We give the money to the project, what they do from there is their problem, I think. Could use Bountysource, OC, etc.

> If you have pure donation on one side and contractor relationships on the other is it still a donation? 

It's certainly not a tax-deductible charitable donation, if that's what you mean (at least not for this first iteration ... perhaps down the line). It's a payment to Gratipay, LLC for open source software. Our main promise is a follow-up report on the impact of their "investment" (not _technically_ an investment either 😆  ... the weird middle-ground of crowdfunding).

**Comment by whit537** [comment]
Follow-up report (#1172) will include:

- stats (e.g., "nn tickets closed vs. same period last year")
- stories for human interest ("We interviewed Substack, here's what he had to say ...")

**Comment by rohitpaulk** [comment]
> IMHO the funds should be untied from specific work. That's been the Gratipay model thus far, as opposed to the Bountysource model (pay $ for specific work) or the Patreon model (pay $ for general work but you get unrelated perks back).

Rather than phrasing this as "We'll give you money to meet the following expectations", we could phrase it as a cycle of "Here's money for the great job you've done in the past" -> "More work/progress to show => Likelihood of more money in the future".

**Comment by BenJam** [comment]
^ Interesting. With a wink and a nudge a windfall payment for work already completed on the assumption that it could be 'reinvested' by the individual if needed. I like it.

**Comment by BenJam** [comment]
This leave the door open to the individual taking as much as they like without blowback from the community.  If the community deems the maintainer exorbitant they will stop contributing. It's self-regulating. Only problem is split between maintainer groups rather than individuals. As I say, the problem is already hard enough :)
