### ISSUE TITLE
onboard @Changaco

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#1166]
@EdOverflow is asking to add @Changaco to our HackerOne program ([slack](https://gratipay.slackarchive.io/gratipay/page-100/ts-1505642565000055), cf. https://github.com/liberapay/liberapay.com/pull/699#issuecomment-330044885).

You still up for this, @Changaco?

**Comment by Changaco** [comment]
@whit537 Yes.

**Comment by whit537** [comment]
Invite sent! :)

**Comment by Changaco** [comment]
Received and accepted. I'm looking at the report @EdOverflow linked to in slack (<https://hackerone.com/reports/127218>).

**Comment by Changaco** [comment]
I've requested joining <https://github.com/orgs/gratipay/teams/gratipay/members> to facilitate work on #1196.

**Comment by whit537** [comment]
Granted!
