### ISSUE TITLE
Partner with LF

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#1167]
The [Linux Foundation](https://www.linuxfoundation.org/) is the [biggest](https://gratipay.news/open-source-captures-almost-none-of-the-value-it-creates-9015eb7e293e) FLOSS non-profit. Can we work with them?

**Comment by whit537** [comment]
I have call scheduled with [Jim Zemlin](https://en.wikipedia.org/wiki/Jim_Zemlin) (executive director) for this coming Friday.

**Comment by whit537** [comment]
Could this play into https://github.com/gratipay/inside.gratipay.com/issues/1168?

**Comment by whit537** [comment]
Yeah that was a seriously sub-par performance on my part. Underprepared and rushed. 😞

**Comment by whit537** [comment]
I rambled and asked too many amateur questions ("Dude, didn't you listen to my keynote?") and did a terrible job of presenting any coherent picture of what Gratipay is about or asking for.

At the very end I snuck in a quick "ask" which he basically heard as "Can we put your logo on our homepage?" 🙊 crap!crap!crap!crap! and he of course was like "gtfo" (in a nice way) and I tried to back-pedal and he said I should talk to another guy ([Mike Dolan](https://www.linkedin.com/in/michaelkdolan/), whom I met at Sustain #920) and then his next call joined the line and I was like OKTHANKSBYECLICK.

**Comment by JessaWitzel** [comment]
What did you learn? Now would be a good time to think about what you should have asked, what research you should have done, and make a list of talking points to keep you focused during your next meeting.

**Comment by whit537** [comment]
I did sorta tie it back to his keynote tho because he has this model of the four stages of corporate open source adoption (and ftr, I _did_ try watching his keynote but I was on the hall pass and the livestream cut out):

1. consumption
1. participation
1. contribution
1. leadership

And I was saying that even at stage (4) companies are still consumers with regard to some portion of open source, and that's the piece we're looking at. How big is it? How can we help companies come full circle and pay for that piece just as they "pay" for the other three pieces with developer time?

Another framing: how big is the "Heartbleed/CII" problem? (Jim pretty much single-handedly launched [CII](https://www.coreinfrastructure.org/) after Heartbleed.) Is it solved? CII is $1,000,000 to 14 projects. Is that enough? How do we go to $100,000,000 to 14,000 projects?

From what I could tell he is much more focused on moving companies from (1) through to (4). Circling back to pay for (1) is not on his radar.

Ideally we're skating ahead of the puck, and as the industry matures we will be the obvious choice to help complete the loop.

**Comment by whit537** [comment]
Email sent:

> Thanks for the call, Jim.
>
>May I summarize what I think I heard, in terms of the open source adoption cycle?
>
>1. consumption
>1. participation
>1. contribution
>1. leadership
>
>What I think I heard is that:
>
>- LF's main focus is helping companies move through the cycle from (1) up through (4).
>- Gratipay's main focus is helping companies, once they reach (4), to circle back and pay for (1), i.e., the portion of open source—and in particular the _volunteer_ portion—of which they are still largely just a consumer.
>- Some parts of LF such as CII also help companies pay for (1).
>
>Are existing efforts to pay for (1) enough? Is the market already efficient? These are the questions that Gratipay is out to answer. I will open a conversation with Mike Dolan to communicate our findings and look for potential partnership opportunities.
>
>Let me know if I misheard anything, and keep up the good work!

**Comment by whit537** [comment]
To Mike:

> Chad Whitacre here, we met at Sustain (I'm the guy from Pittsburgh :). I'm working on this startup, Gratipay, and I just had a call with Jim Zemlin after meeting him at #OSSummit last week (call summary below). He suggested I follow up with you.
> 
> We're getting ready to relaunch Gratipay around the idea of being the easiest way for companies to pay for open source, and I wanted to open a conversation with the Linux Foundation so that we can be in touch and keep an eye out for partnership opportunities as we proceed.
> 
> Would any of these times work for you for an initial call?
> 
>  Tuesday, September 26 at 11 am US/Eastern
>  Wednesday, September 27 at 11 am
>  Monday, October 2 at 11 am

**Comment by whit537** [comment]
Jim's keynote is now up:

https://www.youtube.com/watch?v=4x1r3Osu1Kg
