### ISSUE TITLE
standardize nomenclature

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#117]
We call them `tips`, `gifts`, and `payments` (at least). I think we should standardize on `payments`.

**Comment by whit537** [comment]
Copying over from https://github.com/gratipay/gratipay.com/issues/3511#issuecomment-122895483:

> the word "Subscriptions" just seems ... unilluminating. To me, a subscription is something that I receive in exchange for payment; but the whole point of gratipay is that I'm giving money without expectation of receiving anything in return (unless you count warm fuzzies). So every time I see "Subscriptions", my brain stumbles a little.

**Comment by tshepang** [comment]
I do not like the word *subscription* in this case as well. Why was it chosen?

**Comment by whit537** [comment]
I was looking (on https://github.com/gratipay/gratipay.com/pull/3414) for a word to describe the recurring, scheduled payments that people set up, which are then concretely instantiated in actual payments each payday. "Subscription" seemed to capture this, but I can see that it doesn't entirely fit with the idea of *voluntary* payments:

> The [subscription business model](https://en.wikipedia.org/wiki/Subscription_business_model) is a business model where a customer must pay a subscription price to have access to the product/service. The model was pioneered by magazines and newspapers, but is now used by many businesses and websites.

Heh: 

![screen shot 2015-07-22 at 9 51 20 am](https://cloud.githubusercontent.com/assets/134455/8826844/3cb32842-3057-11e5-9058-021f1748ec9f.png)

There's our exemplar. ;-)

We used to call these "tips," which captures the voluntary nature of the payments, but not the scheduled recurring nature of the payments.

What's a better word to use here?

**Comment by tshepang** [comment]
**give**; I expect that it should be clear to the user that the giving is recurring, especially since there's no once-off giving; when that comes, we can have **give** and **give once** options

**Comment by whit537** [comment]
Comments in light of [Gratipay 2.0](https://medium.com/gratipay-blog/gratipay-2-0-2453d3c53077):

On the one hand, we seem to have fallen out on the **Payment** side more than the **Gift** side. On the other hand, we are still emphasizing *voluntary* payments, which I think is a crucial distinction. We're carving out a niche between strict payments and strict donations. Money moving on Gratipay 2.0 is not primarily a charitable donation, because it *is* given in view of some value I receive directly (as opposed to value someone else receives, e.g., victims of a natural disaster). However, I receive the value *first* and *then* make the payment. The payment is *voluntary*. That's the important point. Gratipay doesn't offer or optimize for rewards (cf. Patreon, Kickstarter).

Wikipedia really is our best example. While Wikimedia is technically a charity, my payments to them are a response to the value I freely, directly receive from Wikipedia. It's technically a donation, but I think it's more accurately called a *voluntary payment*. As a gift, it's a *reciprocal* gift, given in a spirit of gratitude (more so than guilt, one hopes!) for the "first gift" of Wikipedia. From "[Resentment](https://medium.com/gratipay-blog/resentment-2c621dbd7541)":

> There are two gifts on Gittip, and the first gift is my free labor. The money on Gittip is a second gift, a reciprocal gift, given in view of the first. Tegan Mulholland was right to call Gittip “the opposite/complement of a gift economy.”

Gratipay 2.0's primary clarification was that the giver of free labor and receiver of voluntary payments is an open *group* of individuals rather than a single individual.

Payments are clearly monetary, while gifts needn't be monetary. It could be that talking about "voluntary payments" makes way for us to speak of the labor freely shared as the true "gift" on Gratipay. We enable payments motivated by gratitude for gifts freely given and received.

**Comment by whit537** [comment]
I don't think we should do what @colindean [suggest]() and utilize *both* terms, **Payment** and **Gift**.  The only distinction I see you making there, @colindean, is in the motivation of the giver, rather than in any technical consideration, yes? If that's our distinction, I think it's too fine for us to track.

Interesting that I gravitated towards the word "giver" there, while still thinking in terms of "payments."

> A giver makes voluntary payments to a receiver.

Post-2.0, we do have the ~user and Team distinction to work with as well.

> A ~user makes voluntary payments to a Team.

**Comment by whit537** [comment]
As far as `subscriptions` goes, is this too weird?

`intentions`

I have an intention to voluntarily pay a Team $1 per week.

**Comment by whit537** [comment]
We record `intentions` to make `voluntary_payments`.

```sql
ALTER TABLE subscriptions RENAME TO intentions;
ALTER TABLE payments RENAME TO voluntary_payments;
```

(Note that `voluntary_payments` would get subsumed by the `ledger` under https://github.com/gratipay/gratipay.com/pull/3618.)

**Comment by whit537** [comment]
I think `intentions` is too weird. We can't use that in the UI: it'll be too confusing to people. WTF does "intentions" mean? I mean, right? What do we want to say in the UI? Back to "Giving" and "Receiving" there? In which case `ALTER TABLE subscriptions RENAME TO gifts;`? What about `pledge` (Patreon's term)?

**Comment by whit537** [comment]
We *could* use `intentions` for the table, and "Giving" and "Receiving" in the UI.

**Comment by whit537** [comment]
Though Receiving is now tied to a Team, not a ~user. For a ~user, the parallel concept is now "Taking."

**Comment by whit537** [comment]
Quick UI mockup:

![screen shot 2015-07-29 at 9 31 37 pm](https://cloud.githubusercontent.com/assets/134455/8973918/3a91eb56-3639-11e5-87d0-f2ccee29d56e.png)

Though now that I see it, a "Teams" tab seems more natural. Why?

![screen shot 2015-07-29 at 9 31 28 pm](https://cloud.githubusercontent.com/assets/134455/8973921/428cc54c-3639-11e5-90b4-52698231e992.png)

Then on the Team side:

![screen shot 2015-07-29 at 9 29 19 pm](https://cloud.githubusercontent.com/assets/134455/8973898/f4f5c39c-3638-11e5-9123-31fe6f6cf212.png)

**Comment by whit537** [comment]
> We *could* use `intentions` for the table, and "Giving" and "Receiving" in the UI.

Though if we're going to do that, we may as well use `subscriptions` under the hood. We could even talk about "voluntary subscriptions," in keeping with "voluntary payments."

**Comment by whit537** [comment]
```sql
ALTER TABLE subscriptions RENAME TO voluntary_subscriptions;
ALTER TABLE payments RENAME TO voluntary_payments;
```

**Comment by whit537** [comment]
Would the modifier "voluntary" help at all with "subscriptions" and "payments," @techtonik @tshepang @colindean @mattbk et al.?

**Comment by whit537** [comment]
If we used `intentions` for the table, then we could model one-off giving in there as well. It would become in effect a kind of queue. We would pop the queue during payday (maybe even out-of-band someday?) to find out whom to actually charge and payout to. Each record could include a counter of the number of times it had been fulfilled, and a number of times it is intended to be fulfilled.

**Comment by whit537** [comment]
```sql
ALTER TABLE subscriptions RENAME TO intentions;
DROP TABLE payments; -- folded into `ledger`
```

Or maybe `instructions`:

```sql
ALTER TABLE subscriptions RENAME TO instructions;
```

> I instructed my broker to buy the stock.

The ~user is instructing us to charge them for a voluntary payment to a Team.

Conversely, the ~user is instructing us to take a certain amount of a Team's funds for themselves.

```sql
ALTER TABLE subscriptions RENAME TO payment_instructions;
ALTER TABLE payroll RENAME TO payroll_instructions;
```

**Comment by whit537** [comment]
> A giver instructs Gratipay to make voluntary payments to a receiver.
> A ~user instructs Gratipay to make voluntary payments to a Team.
> A ~user instructs Gratipay to take voluntary payroll from a Team.

**Comment by whit537** [comment]
This is actually a pretty important ticket, I think.

**Comment by whit537** [comment]
`payment_instructions` is long. `voluntary_payment_instructions` is even longer.

**Comment by whit537** [comment]
I mean, `subscriptions` is kinda long.

**Comment by whit537** [comment]
Revision of https://github.com/gratipay/inside.gratipay.com/issues/117#issuecomment-67247317 in light of 2.0 and my recent blabbering:

* **~user.** A person who has created an account on Gratipay, regardless of its state or income.
* **Team.** A company that has applied for and been approved to receive voluntary payments and distribute voluntary payroll on Gratipay.
* **Money.** Accepted store of value, e.g. government-issued currency (US Dollars) ~~or cryptocurrency (Bitcoin)~~ [https://github.com/gratipay/inside.gratipay.com/issues/201#issuecomment-102010517].
* **Voluntary Payment.** A single event of movement of `money`, always in the *past*, for which *something* was exchanged. That is, a two way shift of value; full [consideration](https://en.wikipedia.org/wiki/Consideration) *in advance*.
* **Payment Instruction.** An instruction from a `~user` to Gratipay to send a `payment` in the *future* with `full consideration` in advance, automated by Gratipay.
* **Receiver** or **Recipient**. An entity that receives a `voluntary payment`. The terms should be used interchangeably according to proper English usage, but *receiver* should be preferred when either works grammatically. Every `receiver` is a `Team`; not every `Team` is a `receiver`.
* **Giver.** An entity who makes a `voluntary payment` to a `recipient` or `receiver`. Every `giver` is a `~user`; not every `~user` is a `giver`.
* **Taker.** An entity who takes a `voluntary payroll` from a `Team`. Every `taker` is a `~user`; not every `~user` is a `taker`.
* **Gratipayers.** A `~user` who actively works for/on Gratipay, and generally, but not necessarily, takes a share of the revenue (`voluntary payments`) to the Gratipay Team on Gratipay. 

cc: @colindean et al.

**Comment by whit537** [comment]
Really vibin' on the **voluntary** payment. Our special sauce. :sake: :sandal: :santa:

**Comment by colindean** [comment]
I don't have the spare brain time to review the whole thing, but that summary looks fine to me.

**Comment by whit537** [comment]
YESSSSSSSSSSSSSSSSSSSS!!!!!!!!!!!!!!!!!!!!!!!!!!

I LOVE YOU, @colindean! :dancer:

**Comment by whit537** [comment]
We're trying to find that knife-edge between patronization and mutual respect. Gratipay wants you to go to your friend's performance because you love your friend, not because you feel obligated and guilty.

**Comment by whit537** [comment]
Aaaaaaaand I'm Ballmer Peakin'. :kissing_smiling_eyes:

**Comment by whit537** [comment]
PR for `payment_instructions` in https://github.com/gratipay/gratipay.com/pull/3652.

**Comment by whit537** [comment]
Hard to argue with https://www.youtube.com/watch?v=d5_r4ORI6j8.

**Comment by whit537** [comment]
"Gratipay—*voluntary* payments and payroll for open work."

**Comment by whit537** [comment]
"Gratipay: Voluntary Payments and Payroll

**Comment by whit537** [comment]
My proposal is:

 - We use `payment_instructions` and `payroll_instructions` as our database table names instead of `subscriptions` and `payroll`.
 - In communication with users, we take care to refer to "*voluntary* payments and payroll."
 - We expect the `payments` table to fold into the `ledger` under https://github.com/gratipay/gratipay.com/pull/3618.

**Comment by whit537** [comment]
- In the UI we present "Giving" and "Teams" tabs to ~users, and "Receiving" and "Members" tabs to Teams.

**Comment by tshepang** [comment]
I like **voluntary payments**; it's a lot less ambiguous than **gift**.

Regarding the tagline, how about:

> Gratipay: voluntary payments for open work

Payroll is not needed there I feel. That's something someone will discover as they find out more. Payroll sounds like it applies people who are formally employed.

**Comment by tshepang** [comment]
I thin we should have *payments* and *payroll*... adding *instructions* does not help anyone understand these things better, and makes for overlong names.

**Comment by whit537** [comment]
*Payments* and *payroll* are ambiguous with regard to time: are they actual movements of money, or the instructions to do so? Adding "instructions" makes it clear. Code is read more often than written, so a longer name that adds significant clarification is okay.

**Comment by whit537** [comment]
> Payroll sounds like it applies people who are formally employed.

Yes! And, as with payments, *voluntary* payroll is the crucial distinction. When we bring back our payroll feature (https://github.com/gratipay/gratipay.com/issues/3433), it will fit within the formality of the existing framework of employment law (#242), but with the crucial modifier—*voluntary*.

> Payroll is not needed there I feel. That's something someone will discover as they find out more.

Recall that our primary customer is the Team owner/manager. Our pitch to this person *does* include both payments and payroll. However, since we don't actually provide payroll right now and aren't going to for a while, it could make sense for us to drop it for that reason.

**Comment by colindean** [comment]
One concern that should probably be addressed:

If it’s called payroll, someone is going to want to tax it.

**Comment by whit537** [comment]
> If it’s called payroll, someone is going to want to tax it.

Yes! See https://github.com/gratipay/inside.gratipay.com/issues/211#issuecomment-109518669 for a discussion of the alternative, though #242 is the best place to continue this discussion.

**Comment by tshepang** [comment]
It's interesting that we have to appeal to 2 user types: someone that gives and someone that takes. Why are you here, in the tagline, addressing only someone that takes? Removing the **payroll** addresses both types at the same time.

Anyways, what about adding **recurring** in there? I think it's a good idea too add it.

**Comment by whit537** [comment]
> It's interesting that we have to appeal to 2 user types: someone that gives and someone that takes. Why are you here, in the tagline, addressing only someone that takes?

I'm actually addressing the Team owner, which, qua Team owner, neither gives nor takes, but rather receives and distributes. Gratipay's customer is ~hannibal:

[![](https://cloud.githubusercontent.com/assets/134455/8984428/8ff6792a-369f-11e5-9e4c-4a99702cfc30.png)](http://interactive.blockdiag.com/?compression=deflate&src=eJxLyslPzk7JTExXqOZSUEjMyUxOVYjOSUxKzbFVqgNzlWKBEkn5SQhhIAcs6AgXCslIBfJCUhNzwRIQY3TtgGJAAqjcmgsoml6UX1qgUAJUBLYLpB9MZSTm5WUmJeYgLICJgA2r5aoFAFqfMTE)

**Comment by whit537** [comment]
> Anyways, what about adding **recurring** in there? I think it's a good idea too add it.

Yeah, maybe.

**Comment by tshepang** [comment]
hm, interesting:

> **receive** instead of **take**
> **distribute** instead of **give**

fair enough

**Comment by mattbk** [comment]
I don't think payroll needs to be in there either.

**Comment by whit537** [comment]
@tshepang 

~alice **gives** to The A Team.
The A Team (owned/managed by ~hannibal) **receives** from ~alice.
The A Team (owned/managed by ~hannibal) **distributes** to ~bob.
~bob **takes** from The A Team.

**Comment by whit537** [comment]
| subject | verb | object |
|:-------|:----|:---|
| ~alice | **gives** to | The A Team |
| The A Team<br>*owned/managed by ~hannibal* | **receives** from | ~alice |
| The A Team<br>*owned/managed by ~hannibal* | **distributes** to | ~bob |
| ~bob | **takes** from | The A Team |

**Comment by whit537** [comment]
| | subject | verb | object |
|:---|:-------|:----|:---|
| payment | ~alice | **gives** to | The A Team |
| payment | The A Team<br>*owned/managed by ~hannibal* | **receives** from | ~alice |
| payroll | The A Team<br>*owned/managed by ~hannibal* | **distributes** to | ~bob |
| payroll | ~bob | **takes** from | The A Team |

**Comment by whit537** [comment]
~hannibal is our customer, and we offer him both payments and payroll.

**Comment by tshepang** [comment]
I've very happy with these 4 words. We should try hard to stick with them.

**Comment by whit537** [comment]
:dancer:

**Comment by whit537** [comment]
"Giving" refers to payments from the ~user's, i.e., the giver's, point of view.
"Receiving" refers to payments from the Team's, i.e., the receiver's, point of view.
"Distributions" refers to payroll from the Team's, i.e., the distributor's, point of view.
"Taking" refers to payroll from the ~user's, i.e., the taker's, point of view.

**Comment by whit537** [comment]
```
"Giving"         refers to  payments  from the  ~user's  point of view.
"Receiving"      refers to  payments  from the  Team's   point of view.
"Distributions"  refers to  payroll   from the  Team's   point of view.
"Taking"         refers to  payroll   from the  ~user's  point of view.
```

**Comment by whit537** [comment]
~hannibal is our primary customer.
~alice is ~hannibal's primary customer, and our secondary customer.
~bob is ~hannibal's employee (contractor, agent, co-owner, etc.), and our secondary customer.

**Comment by whit537** [comment]
Okay! We seem to have converged, and I've deployed #3652, so with that, let's consider this ticket closed! :-)

**Comment by whit537** [comment]
!m *

**Comment by whit537** [comment]
These terms should make their way into a Glossary: https://github.com/gratipay/inside.gratipay.com/issues/243.

**Comment by mattbk** [comment]
"Teams" is still confusing nomenclature for people who are working alone.  https://twitter.com/jelovirt/status/627178972460224512

**Comment by whit537** [comment]
We've started moving back towards "subscriptions" in some contexts at https://github.com/gratipay/gratipay.com/issues/3677#issuecomment-130799800.

**Comment by webmaven** [comment]
We can start a GLOSSARY.md file as part of this repo to collect terms and definitions. Thoughts?

**Comment by rohitpaulk** [comment]
> We can start a GLOSSARY.md file as part of this repo to collect terms and definitions. Thoughts?

I think it'd be better to update what we have on http://inside.gratipay.com/big-picture/sa/

**Comment by webmaven** [comment]
@rohitpaulk I think we need something more like a shared document to facilitate the discussion of what the terminology should even *be*, as well as defining those terms, which would, once we reached a stable point, determine DB table renames etc., as well as provide the content for a glossary page on the site.

**Comment by whit537** [comment]
> We can start a GLOSSARY.md file as part of this repo to collect terms and definitions. Thoughts?

We have a ticket for that: #243.

>  I think we need something more like a shared document

The *.spt files *are* shared documents, no?

**Comment by webmaven** [comment]
@whit537:
> The .spt files are shared documents, no?

True, they can serve as such within Github about as well as a markdown file.

**Comment by techtonik** [comment]
**payment** is not **giving** unless you **pay what you want**.

For **payment** you should have guarantee to get something in exchange (and governments protect and enforce this). For **giving** you can not assume you will receive anything. That's a big difference. Patreon is about giving, for example. I would not think about them as good as I have now if they were just about paying.

**Comment by tshepang** [comment]
@techtonik isn't Patreon about guaranteeing something in exchange? I thought each donation was linked to some project... e.g. a song.

**Comment by whit537** [comment]
@tshepang Not necessarily. They now allow both models, though from their marketing and site copy you'd think the pegged-to-something model was it.
