### ISSUE TITLE
Generate leads

### ISSUE THREAD

**Issue by JessaWitzel** [gratipay/inside.gratipay.com#1170]
Compile a list of contacts for @whit537  to approach regarding partnership with Gratipay. Looking for clued-in CTOs at small-ish startups. 

Examples from @EdOverflow : GitLab, Assembla

**Comment by whit537** [comment]
Sources of leads for the list:

https://github.com/ossfriendly/open-source-supporters
http://phk.freebsd.dk/VML/
https://www.patreon.com/evanyou
https://fund.django-rest-framework.org/topics/funding/
https://www.djangoproject.com/fundraising/
https://rubytogether.org/
https://opencollective.com/webpack

**Comment by whit537** [comment]
cc: @richbrey11

**Comment by whit537** [comment]
https://docs.google.com/spreadsheets/d/1iO2pfWz4H_izx3pyCMITR1Yi8im7mtPVL-_kNbZZCHI/edit#gid=0

(should be private to @JessaWitzel @richbrey11 and myself)
