### ISSUE TITLE
Put together a press list

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#1174]
For #1160.

cc: @Richbrey11

**Comment by Richbrey11** [comment]
Hey there whit537, Would it be ideal for me to just share a google docs link here for the list? I will be adding contacts over time.

**Comment by whit537** [comment]
Yes but let's keep perms tight on it so we don't leak contact details. Can share with myself and @JessaWitzel, probably anyone else who asks.

**Comment by Richbrey11** [comment]
Press list has been started. https://docs.google.com/spreadsheets/d/1ZBB3O09tdWptIM9Ki964cSMXzPa-zVKGmV64KKRz7Uk/edit?usp=sharing

cc: @whit537

**Comment by Richbrey11** [comment]
Sounds good. @JessaWitzel please shoot me your email address so I can give you access rich@flashpoint.agency

**Comment by whit537** [comment]
@Richbrey11 How about podcasts? Worth a list of its own? Four weeks is tight to schedule and release but could be a traction channel for us.

**Comment by whit537** [comment]
Draft from @JessaWitzel:

https://docs.google.com/document/d/1JLk5oO64wIjXdpRRNfgpkuWY2h8zsjhmC0N_F4QBUCY/edit
