### ISSUE TITLE
Set goals

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#1177]
I think our first reward tier should be a hand-written thank you note with stickers and a heart coin for the first donors up to $100,000.

Assuming for the moment that we reach that ... what next?

**Comment by whit537** [comment]
Could we find some interesting project that we could hire Libraries.io to do and publish the results?

Does OSI have any of those fancy scarfs left?

**Comment by whit537** [comment]
@dmk246 has said she's willing to help with writing the thank-you notes. Stickers are #1176.

**Comment by whit537** [comment]
Talking this through with @chrisecjohns ... what about we offer different distribution algorithms at 
different levels? I think @andrew was suggesting similarly the other day.

| running total ($) | amount ($) | method |
|-----:|---------:|:-------------| 
| 100,000 | 100,000 | according to Libraries.io metrics (SourceRank?) |
| 250,000 | 150,000 | voting by companies |
| 500,000 | 250,000 | fellows program |
| 1,000,000 | 500,000 | consortium of non-profits |
| ??? | ??? | ??? |

**Comment by mattbk** [comment]
I'm a little confused by levels/tiers. You seem to be using them in aggregate rather than per giving company?

**Comment by mattbk** [comment]
Or is it per-company aggregate? Over multiple campaigns, for example?

**Comment by whit537** [comment]
@mattbk Fair enough. I've split out https://github.com/gratipay/inside.gratipay.com/issues/1184 for rewards, keeping this for overall campaign goals. I guess my thinking is that unlocking things at certain goal levels could incentivize contribution w/o as much overhead as rewards entail.
