### ISSUE TITLE
onboard @streaak

### ISSUE THREAD

**Issue by streaak** [gratipay/inside.gratipay.com#1181]
Hello everyone,
I'm streaak2 on bugcrowd and hackerone. I'm currently a bug Hunter trying to make the world a better place and gain some knowledge at the same time. 
I realized that the way I can improve my learning skills is to work on the triage team of a company and I hence would like to be a part of the triage team on gratipay. This would help me out as a bug Hunter but would also help keep gratipay secure.  
Thanks for providing the opportunity. 

Best regards,
Streaak2

**Comment by EdOverflow** [comment]
Hi @streaak,

I have sent you invite to join our Hackerone bug bounty program. We look forward to working with you.

**Comment by whit537** [comment]
Welcome! :-)

[slack](https://gratipay.slackarchive.io/gratipay/page-100/ts-1506787186000058)

**Comment by streaak** [comment]
Thanks guys :)
