### ISSUE TITLE
onboard @sxcurity

### ISSUE THREAD

**Issue by sxcurity** [gratipay/inside.gratipay.com#1183]
Hello!
My name is Corben, and I'm a bug hunter & security analyst.
I would love the opportunity to:
* Protect Gratipay customers
* Help investigate security issues via HackerOne 
* Better myself as a security researcher
* Better the community by being as helpful and kind as I can! 

Thanks much! 👍

**Comment by EdOverflow** [comment]
Hi @sxcurity,

Welcome to the team. I have sent you invite to join our Hackerone bug bounty program. We look forward to working with you.
