### ISSUE TITLE
onboard @karelorigin

### ISSUE THREAD

**Issue by karelorigin** [gratipay/inside.gratipay.com#1189]
Hi (Ed),

My name is Karel and I am a bug bounty hunter.
I'm hoping to help Gratipay by joining their HackerOne team and reviewing/traiging security reports, so that valid reports can reach Gratipay's developers quicker.

**Comment by EdOverflow** [comment]
Hi @karelorigin,

Welcome to the team. I have sent you invite to join our Hackerone bug bounty program. We look forward to working with you.
