### ISSUE TITLE
establish a proper AML program

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#119]
To date, we've drafted off of Balanced for compliance with AML regulations. Now that they're going out of business, we may need to take more control of our processing infrastructure (https://github.com/gratipay/gratipay.com/issues/67), and that means owning AML compliance. Getting turned down by Payoneer (https://github.com/gratipay/gratipay.com/issues/481) and Transpay (https://github.com/gratipay/gratipay.com/issues/417) —_update:_ and Citizens (https://github.com/gratipay/gratipay.com/issues/3366) —indicates that we're not yet mature enough in this area. What are we lacking?

Transpay provided some guidance at https://github.com/gratipay/gratipay.com/issues/417#issuecomment-26090590. Then, over at https://github.com/gratipay/inside.gratipay.com/issues/118#issuecomment-68272547, I discovered [this PDF](http://www.fatf-gafi.org/media/fatf/documents/recommendations/pdfs/FATF_Recommendations.pdf). I think mostly we need to collect better identity information for our users. Yes?

**Comment by whit537** [comment]
This is probably a subset of #122.

**Comment by whit537** [comment]
Ticket description updated. Previously:

> Reticketed from #180
>
> digest this:
>
> "International Standards on Combating Money Laundering and the Financing of Terrorism & Proliferation"
> http://www.fatf-gafi.org/media/fatf/documents/recommendations/pdfs/FATF_Recommendations.pdf

**Comment by whit537** [comment]
> FINRA provides a template for small firms (Word format 164 KB) to assist them in fulfilling their responsibilities to establish the AML compliance program required by the Bank Secrecy Act and its implementing regulations and FINRA Rule 3310.

http://www.finra.org/industry/anti-money-laundering-template-small-firms

**Comment by whit537** [comment]
> [T]he Financial Industry Regulatory Authority, Inc. (FINRA) is a private corporation that acts as a self-regulatory organization (SRO).

http://en.wikipedia.org/wiki/Financial_Industry_Regulatory_Authority

**Comment by whit537** [comment]
> An anti-money laundering (AML) program is a set of procedures designed to guard against someone using the firm to facilitate money laundering or terrorist financing. The main components that must be included are: 1) internal policies, procedures, and controls reasonably designed to assure compliance with the Bank Secrecy Act and implementing regulations; 2) appointment of a designated compliance officer to oversee the program's day-to-day operations; 3) an ongoing training program; and 4) an independent audit.

https://www.nfa.futures.org/NFA-faqs/compliance-faqs/anti-money-laundering/

**Comment by whit537** [comment]
Here's the template:

https://docs.google.com/document/d/1kJenJegSRFimWGbGL8N3uXPWEravOqTIxcKhnLv4C6Y/edit?usp=sharing

**Comment by whit537** [comment]
Just got off the horn with @clone1018. He's going to take a first pass at this tonight. The task is to skim the [FATF recommendations](http://www.fatf-gafi.org/media/fatf/documents/recommendations/pdfs/FATF_Recommendations.pdf), and then write an AML policy for Gratipay, starting with FINRA's template.

@clone1018 I sent you an invite to edit this doc:

[Gratipay AML Policy](https://docs.google.com/document/d/1zlTuFFyqMmTgXhdEKWLDfxrV2WAss6Q53KpdlX5JvoU/edit?usp=sharing)

Here's a clean copy of the template for reference:

[AML Policy Template](https://docs.google.com/document/d/1kJenJegSRFimWGbGL8N3uXPWEravOqTIxcKhnLv4C6Y/edit?usp=sharing)

**Comment by whit537** [comment]
!m @clone1018

**Comment by clone1018** [comment]
I took a first look tonight, only got about half way done. I have the
document downloaded and I'll be doing more tomorrow morning. This will be
at least a weekend project.

**Comment by whit537** [comment]
!m @clone1018 

By "the document" you mean FATF, yes?

**Comment by clone1018** [comment]
Yeah, 2/3 done reading it now. It seems more geared to countries implementing their own FAFT programs but there's tons of nuggets of information I'm noting down.

**Comment by whit537** [comment]
Had a call with @clone1018, he's going to post some notes he's been taking on FAFT. I'm going to try to put something together quickly for Citizens (https://github.com/gratipay/gratipay.com/issues/3366) that captures our current state as well as where we're headed with this ticket.

**Comment by clone1018** [comment]
Posted at: https://github.com/gratipay/gratipay.com/issues/3366#issuecomment-106922059 before I saw this :)

**Comment by whit537** [comment]
From @clone1018 at https://github.com/gratipay/gratipay.com/issues/3366#issuecomment-106922059: 

>Couple of important notes from: http://www.fatf-gafi.org/media/fatf/documents/recommendations/pdfs/FATF_Recommendations.pdf
>
P#14D10: No anonymous accounts or fake names? May not apply.
>
P#63H15: Enhanced CDD measures for "high risk", mentions geographic risk factors?
>
P#65H17c: countries with effective AML systems are low risk
>
P#65H20: Enhanced CDD measures
>
P#65H21: Simplified CDD measures (low risk) **what we should be doing**

**Comment by clone1018** [comment]
Thanks @whit537 :D

**Comment by whit537** [comment]
:-)

**Comment by whit537** [comment]
!m @clone1018

**Comment by whit537** [comment]
I'm drafting a "Manage Risk" howto for IG, to include a section on AML.

**Comment by whit537** [comment]
[*Bank Secrecy Act / Anti-Money Laundering Manual*](http://www.ffiec.gov/bsa_aml_infobase/documents/BSA_AML_Man_2014_v2.pdf) (442 pp.)

Also in HTML:

> This Federal Financial Institutions Examination Council (FFIEC) Bank Secrecy Act (BSA) /Anti-Money Laundering (AML) Examination Manual provides guidance to examiners for carrying out BSA/AML and Office of Foreign Assets Control (OFAC) examinations. An effective BSA/AML compliance program requires sound risk management; therefore, the manual also provides guidance on identifying and controlling risks associated with money laundering and terrorist financing. The manual contains an overview of BSA/AML compliance program requirements, BSA/AML risks and risk management expectations, industry sound practices, and examination procedures. The development of this manual was a collaborative effort of the federal and state banking agencies1 and the Financial Crimes Enforcement Network (FinCEN), a bureau of the U.S. Department of the Treasury, to ensure consistency in the application of the BSA/AML requirements. In addition, OFAC assisted in the development of the sections of the manual that relate to OFAC reviews. Refer to Appendices A (“BSA Laws and Regulations”), B (“BSA/AML Directives”), and C (“BSA/AML References”) for guidance.

http://www.ffiec.gov/bsa_aml_infobase/pages_manual/OLM_002.htm

**Comment by whit537** [comment]
There's also ...

>This *Bank Secrecy Act/Anti-Money Laundering Examination Manual for Money Services Businesses* provides guidance to examiners for performing Bank Secrecy Act (BSA) examinations.
>
As the administrator of the BSA, the Financial Crimes Enforcement Network (FinCEN) has delegated authority to the Internal Revenue Service (IRS) to examine the anti-money laundering (AML) program of money services businesses (MSBs).
>
An effective AML program requires sound risk management; therefore, the manual also provides guidance on identifying and controlling risks associated with money laundering and terrorist financing. The manual contains an overview of AML program requirements, BSA/AML risks and risk management expectations, sound industry practices, and examination procedures. The development of this manual was a collaborative effort of the IRS, state agencies responsible for MSB regulation, the Money Transmitter Regulators Association (MTRA), the Conference of State Bank Supervisors (CSBS), and FinCEN, a bureau of the U.S. Department of the Treasury. The goal is to ensure consistency in the application of the BSA requirements.

[*Bank Secrecy Act / Anti-Money Laundering Examination Manual for Money Services Businesses*](http://www.fincen.gov/news_room/rp/files/MSB_Exam_Manual.pdf) (FinCEN, 2008. 159 pp.)

**Comment by whit537** [comment]
http://en.wikipedia.org/wiki/Know_your_customerhttp://en.wikipedia.org/wiki/Know_your_customer

**Comment by whit537** [comment]
Gold!

>#### Third-Party Payment Processors—Overview
>
**Objective.** *Assess the adequacy of the bank’s systems to manage the risks associated with its relationships with third-party payment processors, and management’s ability to implement effective monitoring and reporting systems.*
>
Nonbank or third-party payment processors (processors) are bank customers that provide payment-processing services to merchants and other business entities. Traditionally, processors contracted primarily with retailers that had physical locations in order to process the retailers' transactions. These merchant transactions primarily included credit card payments but also covered automated clearing house (ACH) transactions221, remotely created checks (RCC),222 and debit and prepaid cards transactions. With the expansion of the Internet, retail borders have been eliminated. Processors now provide services to a variety of merchant accounts, including conventional retail and Internet-based establishments, prepaid travel, telemarketers, and Internet gaming enterprises.
>
Third-party payment processors often use their commercial bank accounts to conduct payment processing for their merchant clients. For example, the processor may deposit into its account RCCs generated on behalf of a merchant client, or process ACH transactions on behalf of a merchant client. In either case, the bank does not have a direct relationship with the merchant. The increased use of RCCs by processor customers also raises the risk of fraudulent payments being processed through the processor's bank account. The Federal Deposit Insurance Corporation (FDIC), Office of the Comptroller of the Currency (OCC), and Financial Crimes Enforcement Network (FinCEN) have issued guidance regarding the risks, including the BSA/AML risks, associated with banking third-party processors.

http://www.ffiec.gov/bsa_aml_infobase/pages_manual/olm_063.htm

**Comment by whit537** [comment]
Damn. That is seriously gold. That's the documentation for government regulators conducting examinations of banks regarding their third-party processor risk assessment programs. This is exactly what I've been looking for.

**Comment by whit537** [comment]
Footnote 223:

> *FDIC Clarifying Supervisory Approach to Institutions Establishing Account Relationships with Third-Party Payment Processors*, FDIC FIL-41-2014, July 28, 2014;
>
*Payment Processor Relationships Revised Guidance*, FDIC FIL-3-2012, January 31, 2012;
>
*Risk Management Guidance: Payment Processors*, OCC Bulletin 2008-12, April 24, 2008;
>
*Risk Management Guidance: Third Party Relationships*, OCC Bulletin 2013-29, October 30, 2013; and 
>
*Risk Associated with Third-Party Payment Processors*, FinCEN Advisory FIN-2012-A010, October 22, 2012.

@copiesofcopies You might be interested in these. ^^^

**Comment by whit537** [comment]
Okay! Here's what I have so far:

http://inside.gratipay.com/howto/manage-risk

I want to add a fourth section on Consumer Protection and then give it another going-over before sending it off to Citizens. Hopefully I can do that this weekend.

**Comment by whit537** [comment]
I scanned the [table of contents](http://www.ffiec.gov/bsa_aml_infobase/pages_manual/manual_online.htm) for FFIEC's Examination Manual for other relevant sections. Here's what I turned up:

| Overview | Examination Procedures |
|:---|---|
| [**Customer Identification Program**](http://www.ffiec.gov/bsa_aml_infobase/pages_manual/OLM_011.htm) | [Examination Procedures](http://www.ffiec.gov/bsa_aml_infobase/pages_manual/OLM_012.htm) |
| [**Customer Due Diligence](http://www.ffiec.gov/bsa_aml_infobase/pages_manual/OLM_013.htm) | [Examination Procedures](http://www.ffiec.gov/bsa_aml_infobase/pages_manual/OLM_014.htm) |
| [**Automated Clearing House Transactions**](http://www.ffiec.gov/bsa_aml_infobase/pages_manual/OLM_059.htm) | [Examination Procedures](http://www.ffiec.gov/bsa_aml_infobase/pages_manual/OLM_060.htm) |
| [**Third-Party Payment Processors**](http://www.ffiec.gov/bsa_aml_infobase/pages_manual/OLM_063.htm) | [Examination Procedures](http://www.ffiec.gov/bsa_aml_infobase/pages_manual/OLM_064.htm) |

**Comment by whit537** [comment]
FinCEN's doc has a 16-page section on anti-money laundering programs (43-61).

**Comment by whit537** [comment]
### Gratipay's Position in the AML Policing Environment

```
Documentation

  FATF ────────────────→ BSA ─────────────────→ Citizens' ───────────→ Gratipay's
                         │                       underwriting           underwriting
                         └ law (aka statutes)    procedures             procedures
                           │
                           └ regulations
                             │
                             ├ FinCEN guidance and rulings
                             │
                             └ examination manuals

Scope

  international ───────→ country (U.S.A.) ────→ bank ────────────────→ us
```

1. Anti-money laundering (**AML**) is a catch-all term for policing of the global financial system against *funding of crime* (and, in particular, terrorism). Related, but separate: **anti-fraud** refers to policing against *theft* (including both identity theft and monetary theft).

1. The **international community**'s AML recommendations are in [FATF](http://www.fatf-gafi.org/media/fatf/documents/recommendations/pdfs/FATF_Recommendations.pdf) (2012, 130 pp.). The audience here is countries writing their AML laws.

1. The **U.S. of A.**'s AML law is the Bank Secrecy Act (BSA, 1970; strengthened in the USA PATRIOT Act of 2001; here's a thread [unpacking the laws and regulations](https://github.com/gratipay/inside.gratipay.com/issues/201) a bit). There are a number of federal- and state-level institutions involved in policing the U.S. financial system to enforce the BSA; the FFIEC collects them together, and [publishes an examination manual](http://www.ffiec.gov/bsa_aml_infobase/pages_manual/manual_online.htm) ([PDF](http://www.ffiec.gov/bsa_aml_infobase/documents/BSA_AML_Man_2014_v2.pdf), 2014, 442 pp.): afaict these are the most detailed instructions available for the regulators who are actually doing the policing. The biggest institutional player is FinCEN (who farm their auditing work out to the IRS), and they also [publish an examination manual](http://www.fincen.gov/news_room/rp/files/MSB_Exam_Manual.pdf) (2008, 159 pp.). FinCEN, etc., police U.S. banks and other financial institutions (of which, btw, here is [a taxonomy](https://github.com/gratipay/inside.gratipay.com/issues/192#issuecomment-100048271)).

1. **Citizens** is the U.S. bank we're trying to do business with (https://github.com/gratipay/gratipay.com/issues/3366). They have an underwriting department that is responsible for (among other things) implementing the AML programs required by the BSA to the satisfaction of FinCEN, etc.'s regulators.

1. **Gratipay** is us. We are a third-party payment processor (TPPP). Per [31 CFR § 1010.100(ff)(5)(ii)(B)](http://www.ecfr.gov/cgi-bin/text-idx?SID=368bfe5df617f990d014eade2b231d08&mc=true&node=pt31.3.1010&rgn=div5#se31.3.1010_1100), we are *not* regulated directly by FinCEN, etc. TPPPs are kind of like "lite" versions of a full-fledged, general-purpose money transmitter: we provide our customers with limited, indirect access to the financial system. Since the access we provide is limited, we're [not a big enough risk](http://www.gpo.gov/fdsys/pkg/FR-2011-07-21/pdf/2011-18309.pdf) for FinCEN to regulate: "[payment processing] is a relatively controlled flow of money that poses little money laundering risk" (p. 43593). However, we *are* [a bigger risk to banks](http://www.ffiec.gov/bsa_aml_infobase/pages_manual/OLM_063.htm) than most of their clients: "Processors generally are not subject to BSA/AML regulatory requirements. As a result, some processors may be vulnerable to money laundering[, etc.]" Therefore, we are *indirectly* regulated, because we're basically sub-regulated by any BSA-regulated entity we want to do business with: "Payment processors pose greater money laundering and fraud risk [to their banking partners] if they do not have an effective means of verifying their merchant clients' identities and business practices. Risks are heightened when the processor does not perform adequate due diligence on the merchants for which they are originating payments" (ibid.). As such, we basically need to implement a lite version of the heavy-duty compliance program that a directly-regulated institution such as Citizens implements. Fortunately, the examination manuals (together with the higher-level laws, etc.) give us a *lot* of insight into what such a program entails.

**Comment by whit537** [comment]
*Un*fortunately, what such a program entails is collecting identity information from our customers and independently verifying it, which is a lot of work to get done before Monday. O.O

**Comment by whit537** [comment]
P.S. I found this a helpful summary/intro to financial institution AML compliance programs: http://blog.volkovlaw.com/2013/06/aml-compliance-kyc-and-due-diligence/.

**Comment by whit537** [comment]
##### Know Your Customer (KYC)

  1. Customer Identification Program (CIP)
   1. collecting identity information
   1. independently verifying identity information
  1. Customer Due Diligence (CDD)&mdash;Having identified them, are they suspicious?
  1. Extended Due Diligence (EDD)&mdash;If they are high-risk, are they really not suspicious?

**Comment by whit537** [comment]
I made a pass through the FFIEC's sections on CIP (notes on https://github.com/gratipay/gratipay.com/issues/3289), and CDD (#219). I've already gone through the section on TPPP, which I incorporated into [Manage Risk](http://inside.gratipay.com/howto/manage-risk). I'm going to go through the fourth section I flagged, about ACH, then I intend to read the AML section of the FinCEN manual. I'll leave notes on both of those here.

**Comment by whit537** [comment]
Once I'm done reading the manuals, next steps will be to write more of Manage Risk, and decide what we need to get implemented before we're comfortable reapproaching Citizens (https://github.com/gratipay/gratipay.com/issues/3366).

**Comment by whit537** [comment]
I just spent some time thinking through the meaning of the terms ACH credit and ACH debit. I have an intuitive understanding that "ACH credit" is what we do when we payout to a user, and "ACH debit" is what we would do if we allowed users to fund their accounts via ACH. I just reviewed the meaning of [debits and credits](http://www.accountingcoach.com/debits-and-credits/explanation) in accounting to solidify my understanding of these terms in the ACH context.

![screen shot 2015-05-30 at 10 11 59 pm](https://cloud.githubusercontent.com/assets/134455/7900265/258fde9c-0719-11e5-8a1d-0656512dba4e.png)

**Comment by whit537** [comment]
> Because cash is involved in many transactions, it is helpful to memorize the following:
>
 - Whenever cash is *received*, debit **Cash**.
 - Whenever cash is *paid out*, credit **Cash**.

http://www.accountingcoach.com/debits-and-credits/explanation/2

**Comment by whit537** [comment]
That is, the terms debit and credit in the ACH context are used with reference to the originator of the transaction (not the receiver). This makes sense to me.

**Comment by whit537** [comment]
> ACH transactions that are originated through a TPSP (that is, when the Originator is not a direct customer of the ODFI) may increase BSA/AML risks, therefore making it difficult for an ODFI to underwrite and review Originator transactions for compliance with BSA/AML rules.<sup>215</sup> Risks are heightened when neither the TPSP nor the ODFI performs due diligence on the companies for whom they are originating payments.
>
----
<sup>215</sup> A bank's underwriting policy should define what information each application should contain. The depth of the review of an originator's application should match the level of risk posed by the originator. The underwriting policy should require a background check of each originator to support the validity of the business.

http://www.ffiec.gov/bsa_aml_infobase/pages_manual/OLM_059.htm

**Comment by whit537** [comment]
(Gratipay is a TPSP.)

**Comment by whit537** [comment]
>For relationships with TPSPs, CDD on the TPSP can be supplemented with due diligence on the principals associated with the TPSP and, as necessary, on the originators. Adequate and effective CDD policies, procedures, and processes are critical in detecting a pattern of unusual and suspicious activities because the individual ACH transactions are typically not reviewed. Equally important is an effective risk-based suspicious activity monitoring and reporting system. In cases where a bank is heavily reliant upon the TPSP, a bank may want to review the TPSP’s suspicious activity monitoring and reporting program, either through its own or an independent inspection. The ODFI may establish an agreement with the TPSP, which delineates general TPSP guidelines, such as compliance with ACH operating requirements and responsibilities and meeting other applicable state and federal regulations. Banks may need to consider controls to restrict or refuse ACH services to potential originators and receivers engaged in questionable or deceptive business practices.

**Comment by whit537** [comment]
> ACH transactions can be used in the layering and integration stages of money laundering.

Took a brief excursion into the [three stages of money laundering](https://www.moneylaundering.ca/public/law/3_stages_ML.php): placement, layering (structuring), and integration.

**Comment by whit537** [comment]
> The potentially higher risk inherent in IATs should be considered in the bank's ACH policies, procedures, and processes.

**Comment by whit537** [comment]
> With respect to domestic ACH transactions, the ODFI is responsible for verifying that the Originator is not a blocked party and making a good faith effort to ascertain that the Originator is not transmitting blocked funds.

**Comment by whit537** [comment]
Citizens is the ODFI. Gratipay is a TPSP that sits between the Originator and the ODFI.

**Comment by whit537** [comment]
> Similarly, banks that have relationships with TPSP should assess the nature of those relationships and their related ACH transactions to ascertain the bank's level of OFAC risk and to develop appropriate policies, procedures, and processes to mitigate that risk.

**Comment by whit537** [comment]
> [...] select a sample of higher-risk customers, including TPSPs [...]

http://www.ffiec.gov/bsa_aml_infobase/pages_manual/OLM_060.htm

**Comment by whit537** [comment]
> A review of the account opening documentation, including CIP documentation, may be necessary in making these determinations.

See https://github.com/gratipay/gratipay.com/issues/3289.

**Comment by whit537** [comment]
Turning to the AML section of the FinCEN [manual](http://www.fincen.gov/news_room/rp/files/MSB_Exam_Manual.pdf) ...

**Comment by whit537** [comment]
> Furthermore, the program must be fully implemented and reasonably designed to meet the BSA requirements. Policy statements alone are not sufficient; practices must coincide with the MSB’s written program.

**Comment by whit537** [comment]
> At a minimum, the MSB’s AML program must include the following four pillars:
- Policies, procedures, and internal controls designed to ensure ongoing compliance;
- Designation of individual(s) responsible for coordinating and monitoring day-to- day compliance;
- Training for appropriate personnel; and
- Independent review to monitor an adequate program.

**Comment by whit537** [comment]
> It is important for MSB management to create a culture of compliance to ensure staff adherence to the MSB’s AML program. The level of sophistication of the internal controls should be commensurate with the size, structure, risks, and complexity of the MSB.

**Comment by whit537** [comment]
> Many of the areas discussed in this section will probably not be present in smaller operations. However, the general principle that the MSB should have some type of internal controls to mitigate risk applies to all MSBs, regardless of size.

**Comment by whit537** [comment]
> [T]he MSB’s monitoring systems to identify, research, and report suspicious activity should be risk-based[.]

"Risk-based" seems to be a key word (cf. https://github.com/gratipay/gratipay.com/issues/3289#issuecomment-107085600). I take it to mean that we don't attempt to investigate all activity equally, but rather focus our efforts where we assess risk to be highest.

**Comment by whit537** [comment]
> Alternatively, did management merely document the requirements with little or no regard to actual BSA compliance and AML program implementation?

**Comment by whit537** [comment]
> Some examples of control activities that could be in place include: computer programs in a point-of-sale system that require all fields to be completed; error recognition in these programs if invalid data is entered; dollar limits on transactions that will be processed without a manager’s approval; systems that automatically prompt an employee to obtain additional recordkeeping information when applicable; and clear instructions on types of customer identification that will be accepted as proof of identity.

**Comment by whit537** [comment]
> Law enforcement inquiries and requests can include grand jury subpoenas and National Security Letters (NSLs). Policies, procedures, and processes should ensure such inquiries and requests are handled appropriately.

**Comment by whit537** [comment]
> While the title of the individual responsible for overall BSA compliance is not important, his or her level of authority and responsibility within the MSB is critical.

**Comment by whit537** [comment]
This sort of language keeps recurring: "the MSB’s overall risk level (based on products, services, customers, geographic locations, etc.)".

**Comment by whit537** [comment]
Okay! Done with the AML program section. I went back and scanned the table of contents. The following sections generally deal with reporting requirements. An initial section confirms my understanding of what "risk-based" means:

> Risk-Based Approach to BSA Examinations
>
To ensure that MSBs have in place the processes necessary to identify, measure, monitor, and control risk exposures, examinations have increasingly emphasized evaluating the appropriateness of these processes. While the examiner will always perform some transactional testing under a risk-based examination approach, the amount of transaction testing will be reduced when the examiner determines that internal risk-management processes are adequate or risks are minimal.

**Comment by whit537** [comment]
Reporting requirements seem to fall under two major headings:

 - suspicious activity reports (SARs)
 - currency transaction reports (CTRs)

As mentioned at https://github.com/gratipay/inside.gratipay.com/issues/219#issuecomment-107102712, I'm not sure these apply to us, since we're not actually an MSB or financial institution generally.

**Comment by whit537** [comment]
I guess that's it for tonight. Tomorrow, I hope to implement https://github.com/gratipay/gratipay.com/issues/3289 and #219, and update [Manage Risk](http://inside.gratipay.com/howto/manage-risk), so that on Monday we can give something to Citizens (https://github.com/gratipay/gratipay.com/issues/3366) that we're proud of and confident in.

**Comment by whit537** [comment]
!m *

**Comment by whit537** [comment]
Zooming back out to here from a vendor evaluation at https://github.com/gratipay/gratipay.com/issues/2449#issuecomment-107104800 ... it looks like fundamentally what we need to do is (a) verify the identity of the people we're doing business with, and (b) ensure that said people are not criminals (and, in particular, terrorists).

**Comment by whit537** [comment]
Alright, so we need to collect identity and perform sanction screening. How are we going to do that?

**Comment by whit537** [comment]
The third piece is suspicious activity monitoring. What does that mean and how do we do it?

**Comment by whit537** [comment]
> The criteria to decide when a report must be made varies from country to country but generally is any financial transaction that does not make sense to the financial institution, is unusual for that particular client or appears to be done only for the purpose of hiding or obfuscating a transaction.

https://en.wikipedia.org/wiki/Suspicious_activity_report

**Comment by whit537** [comment]
We're *not* an MSB, but since we're [subregulated by MSBs](https://github.com/gratipay/inside.gratipay.com/issues/119#issuecomment-107081615), the [law for MSB AML programs](http://www.ecfr.gov/cgi-bin/text-idx?node=se31.3.1022_1210) is a useful starting point for us. An abbreviation of the regulations, to which [the examination manual overview](https://www.ffiec.gov/bsa_aml_infobase/pages_manual/OLM_007.htm) maps pretty directly:

>An effective anti-money laundering program is one that is reasonably designed to prevent the money services business from being used to facilitate money laundering and the financing of terrorist activities.  The program shall be commensurate with the risks posed by the location and size of, and the nature and volume of the financial services provided by, the money services business. The program shall be in writing, and a money services business shall make copies of the anti-money laundering program available for inspection to the Department of the Treasury upon request. At a minimum, the program shall:
>
1. Incorporate policies, procedures, and internal controls reasonably designed to assure compliance with this chapter.
2. Designate a person to assure day to day compliance with the program and this chapter.
3. Provide education and/or training of appropriate personnel concerning their responsibilities under the program, including training in the detection of suspicious transactions to the extent that the money services business is required to report such transactions under this chapter.
4. Provide for independent review to monitor and maintain an adequate program.

http://www.ecfr.gov/cgi-bin/text-idx?node=se31.3.1022_1210

**Comment by whit537** [comment]
Hey @clone1018, wanna be our designated person to assure day to day compliance with the program and this chapter? :]

**Comment by whit537** [comment]
> Alright, so we need to collect identity and perform sanction screening.

We also need to verify *business* identity, aaaaand that's more complicated.

**Comment by whit537** [comment]
Learnings from sales call with [ID Checker](http://www.idchecker.com/) over on https://github.com/gratipay/gratipay.com/issues/2449: **document verification** is different from **identity verification**. KYC refers to the latter(?), which involves checking provided information (name, address, dob) against government databases, "or a consumer credit bureau, most likely." **Sanction screening** is the third step in the process.

**Comment by whit537** [comment]
I just watched http://www.prolibraries.com/player/?embed=f1bb17c85deae61276ec1762cfe302e0.

**Comment by whit537** [comment]
Context: http://www.moneylaunderingconference.com/2015/. Discovered by googling the name of the SVP for AML and Sanctions Compliance at Citizens, who didn't personally sign the letter we received from them on gratipay/gratipay.com#3366. ;-)

**Comment by whit537** [comment]
My favorite part of the René Bruelhart video was his answer at about 29:30 to the question, "What have you learned? What is the template for turning around these troubled situations?" **tl;dr**—(1) What are the real issues? Don't rush. (2) Who are your partners? Bring them in. (3) Really *go* for it.

> First, sit back, and think about, "What are we talking about? What are the real issues here?" Don't try to make a quick fix. Sometimes it's appropriate, but, most often—especially when you have, let's say, more fundamental issues—sit back. "What are we talking about?"
>
And, then, who are your partners? Who are the players involved? Which are the different relevant factors you have to respect, because quite often you're just looking to your department. You do that the whole day, and you don't even know what is going on outside of the door or somewhere else within the bank or within the financial institution. So, what are the factors of a success story? What are the players you have to bring in? And then, bring them in. Because once you start a process, and you have the process to be changed two or three or four times, you will fail.
>
So, it's better to invest a little bit more time to set up a proper process, to really pave the path forward, and then to go for it. And there are always hurdles coming. But if you're convinced, go for it. Really go for it. And don't go into too many compromises there, because, again, if you're gonna change you're game plan, you're gonna lose.

**Comment by mattbk** [comment]
Just to keep on top of this because it's blocking gratipay/gratipay.com/issues/3671, what are the next steps?

**Comment by whit537** [comment]
Next step is building a vault, so we can store personally identifying information, so we can verify identity.

**Comment by webmaven** [comment]
@whit537 Do you actually have to *build* a vault? Isn't there some sort of document vault-as-a-service or open source app you could use?

**Comment by whit537** [comment]
@webmaven Check out https://github.com/gratipay/gratipay.com/issues/3504, some options surfaced on there.
