### ISSUE TITLE
Post #BackTheStack ad on RtD

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#1192]
@ericholscher at https://github.com/gratipay/inside.gratipay.com/issues/1160#issuecomment-333260948:

> Also I'm happy to run a Community Ad for this campaign:
> http://docs.readthedocs.io/en/latest/ethical-advertising.html#community-ads

🎉  💃 

[Read the Docs Advertising Prospectus.pdf](https://github.com/gratipay/inside.gratipay.com/files/1349585/Read.the.Docs.Advertising.Prospectus.pdf) (shared w/ perms)

**Comment by ericholscher** [comment]
Any update here? I'd like to run a MOSS ad at the end of the month, so would like to get this running sooner.
