### ISSUE TITLE
onboard @B3nac

### ISSUE THREAD

**Issue by B3nac** [gratipay/inside.gratipay.com#1193]
Hello Gratipay team,

My name is Kyle and I am a security researcher. Currently I'm active duty Air Force and pursing a degree in Software Development and Security. I want to use my spare time helping with security related issues on Gratipay. 

My focus:

-Help protect Gratipay from security vulnerabilities via audits and black box testing.

-Reproduce, Investigate, diagnose and fix security issues on your HackerOne program.

-Be a team player and help make the world and Gratipay a better place.

**Comment by EdOverflow** [comment]
Hi @B3nac,

Welcome to the team. I have sent you invite to join our Hackerone bug bounty program. We look forward to working with you.
