### ISSUE TITLE
Caption the video

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#1195]
Reticketed from https://github.com/gratipay/inside.gratipay.com/issues/1155.

**Comment by whit537** [comment]
@ChrisECJohns exported an SCC file which Google [claims]() is their "preferred file format," but I'm getting en error uploading it:

![subs](https://user-images.githubusercontent.com/134455/31298253-50651d5a-aab7-11e7-84e8-1a2fe876ee97.png)

Here's the file:

https://gist.github.com/whit537/e1fdf2a820175bc3a9ecbdf5c1c0844f

**Comment by techtonik** [comment]
What an awful format. Where is the text?
