### ISSUE TITLE
Thank you, Chad

### ISSUE THREAD

**Issue by Juanlu001** [gratipay/inside.gratipay.com#1198]
Dear @whit537,

I was extremely sad when I read last week that [you were leaving Gratipay](https://github.com/gratipay/inside.gratipay.com/issues/1069#issuecomment-335488726). On the other hand, [despite following you since 2014](https://twitter.com/Pybonacci/status/503959143552909312), I never really had the determination to contribute to the community or, you know, put money in there, which at this point makes me ashamed. Therefore, I felt compelled to write here a short, public acknowledgement of what your work has meant to me as a minuscule tribute, and invite others to do the same in this issue.

I cannot speak on behalf of the open source community as a whole, so I'm speaking only on behalf of myself: your work has been a strong influence for me. Every time I have lengthy conversations "with myself" in public, regarding some design decision or implementation detail of some of my open source projects, I think of [your\* "Open Company" initiative](https://medium.com/@whit537/draft-open-company-manifesto-90da530d5c13) - an idea that is, perhaps, too ahead of its time. [From the website](http://www.opencompany.org/about/):

> Trust is the foundation of the economy. The law establishes a minimum baseline of trustworthiness, and the status quo for companies is to operate near this baseline. What if we tried to _maximize_ trust?

We are all well aware of several initiatives to fund open source, that have reached varying degrees of maturity and success. But every time I read on any of them, I think: "there was a time when Chad Whitacre was living entirely on the donations received via the platform he is creating". Shake away your sense of defeat: this was an amazing achievement, and I admire you for that.

Gratipay suffered from some "incidents", a name change, the Balanced Payments disaster, and probably more crisis and redefinitions that I missed. But the trace of Chad's resilience, openness, and humanity stay publicly in GitHub issues, IRC logs, Slack archives, video interviews and more. He admitted all his mistakes in public, some times in painful ways. And in doing so, the rest of us had the opportunity to learn from them.

The Gratipay vision is a very powerful one, and it's a pity that its relaunch didn't take place in the end. But for me, you are still an innovator, a strong person that deserves recognition.

Thanks Chad for trying so hard all these years. Thanks for leading by example, for resisting, for pivoting over and over again. Thanks for admitting that, at some point in life, family is the most important and valuable thing we have - I am sure they will give you their warmest support.

I probably could have emailed you instead of writing this issue, but if Chad Whitacre has taught me anything, it's that some things are better done in the open: all of them :)

Thank you Chad. I wish you the best luck!

<sup>\* Although, in fact, [Gratipay is the second open company](https://gratipay.news/the-second-open-company-4cbab7ca1a47) :)</sup>

**Comment by whit537** [comment]
Thank you so much for posting this, @Juanlu001. Your words mean a lot to me. 🙇

All the best to you, and I hope we get to meet in person some day! :-)

**Comment by colindean** [comment]
👍 to all of the above.
