### ISSUE TITLE
Coderbits calls us Gittip, not Gratipay

### ISSUE THREAD

**Issue by seanlinsley** [gratipay/inside.gratipay.com#120]
Coderbits users are allowed to link to Gratipay from their profile page, but we're still named Gittip on the site. This ticket is for tracking that change.

https://coderbits.com/prufrock123

![screen shot 2014-12-29 at 3 08 50 pm](https://cloud.githubusercontent.com/assets/688886/5573132/5fddb728-8f6d-11e4-984f-d72f83bb52b8.png)

[(wasn't sure which repo this ticket should be on)](https://botbot.me/freenode/gratipay/msg/28494731/)

**Comment by whit537** [comment]
I was going to top this up but their profiles are 500 and on Twitter it seems that they're in the middle of an incident: https://twitter.com/coderbits/status/639109275176992768.

**Comment by whit537** [comment]
Oh, wait ... that's from September. Is Coderbits still alive?

**Comment by whit537** [comment]
No.

![screen shot 2016-03-31 at 4 07 11 pm](https://cloud.githubusercontent.com/assets/134455/14189348/ccefc3dc-f75a-11e5-908c-2095af40c731.png)

https://twitter.com/search?q=coderbits&src=typd.

------------

![screen shot 2016-03-31 at 4 08 06 pm](https://cloud.githubusercontent.com/assets/134455/14189349/ccf04dc0-f75a-11e5-99af-87a26b0e17fe.png)

https://twitter.com/PaulThompson_/status/710465409347092480
