### ISSUE TITLE
Renew gdr.rocks

### ISSUE THREAD

**Issue by mattbk** [gratipay/inside.gratipay.com#1201]
https://gratipay.freshdesk.com/a/tickets/10124

If this doesn't get renewed (per pending decision at #1196), what breaks?

**Comment by whit537** [comment]
Nothing. I think somewhere (maybe in slack?) I discussed dropping it. It was for the "gratipay dependency resolver" during the initial spike-out of npm (actually pypi?) integration, but it never materialized so we don't need it.

**Comment by mattbk** [comment]
👍
