### ISSUE TITLE
"Sell" to Liberapay

### ISSUE THREAD

**Issue by chadwhitacre** [gratipay/inside.gratipay.com#1217]
Reticketed from https://github.com/gratipay/inside.gratipay.com/issues/1196.

I propose that we sell Gratipay assets to Liberapay ... whatever they want for $1.

Two week voting period starting now.

**Comment by chadwhitacre** [comment]
I vote in favor.

**Comment by chadwhitacre** [comment]
Based on https://github.com/gratipay/inside.gratipay.com/issues/1196#issuecomment-353316367 I guess we are looking at:

- The five domains `gratipay.{com,news,net,org}` and `gittip.com`.
- The two additional domains `{grtp,gttp}.co` if we can't get the registry to protect those for us.
- The Gratipay Twitter account.

**Comment by chadwhitacre** [comment]
Looking at https://github.com/liberapay/liberapay.org/issues/32 ...

Do you want the logo? The database?

**Comment by chadwhitacre** [comment]
cc: @Zatalyz

**Comment by Changaco** [comment]
> Do you want the logo?

Yes, if it's okay with you we may want to reuse the Gratipay logo. Especially the one in FontAwesome.

> The database?

Yes. I'm not sure what we'll do with it but I think it could be useful.

**Comment by Changaco** [comment]
Ping @clone1018

**Comment by clone1018** [comment]
I vote in favor.

**Comment by chadwhitacre** [comment]
Resolution passed!

**Comment by chadwhitacre** [comment]
Sorry ... voting period closed!

I count 100% in favor.

Count becomes official in 24 hours. ☺️

**Comment by chadwhitacre** [comment]
Official. Passed!
