### ISSUE TITLE
Hand off to Liberapay

### ISSUE THREAD

**Issue by chadwhitacre** [gratipay/inside.gratipay.com#1218]
Reticketing from https://github.com/gratipay/inside.gratipay.com/issues/1196 post-#1217 so we have a clear record.

- [x] domains
  - [x] `gratipay.com`
  - [x] `gratipay.news`
  - [x] `gratipay.net`
  - [x] `gratipay.org`
  - [x] `gittip.com`
  - [x] `grtp.co` (if the registry won't protect it)
  - [x] `gttp.co` (if the registry won't protect it)
- [x] Twitter account
- [x] database
- [x] logo
- [x] ~~cash~~
- [x] GitHub org (give admin permission to @Changaco and/or @liberapay-admin)
- [x] publish final blog post about handoff

**Comment by chadwhitacre** [comment]
Reached out to .CO:

![screen shot 2018-01-18 at 3 28 52 pm](https://user-images.githubusercontent.com/134455/35119878-53cc1332-fc64-11e7-8d66-141a283e1d0f.png)

**Comment by chadwhitacre** [comment]
No response from .CO.

@Changaco I've emailed you transfer codes for the seven domains.

**Comment by chadwhitacre** [comment]
> In general I had been thinking we'd take the last of our money and use it to pay for domain names for a few years to keep things online. We have $545 in the bank right now.

We are down to $486.26. Our current monthly costs are:

- $3.00 to DNSimple for DNS hosting
- $12.00 to PNC for our bank account

I think instead of paying for the domain names we should just give Liberapay the cash and let you use it as you would like.

Note that `gratipay.news` is supposed to renew on January 28 (six days). Depending on lockout timeframes we may need to renew that over here before transferring.

**Comment by Changaco** [comment]
> @Changaco I've emailed you transfer codes for the seven domains.

I got them, but transferring all these domains to the registrar Liberapay uses would cost €143.50, so I suggest that you give me access to Gratipay's iwantmyname account instead.

**Comment by chadwhitacre** [comment]
Heard back from .CO:

> Hi ¿
> 
> Thanks for contacting .CO — Please email them at support@pop.co so that they can let you know if exist something in order to protect those domains from malicious takeover
> 
> Thank you, and we can’t wait to see what you are building on your new .CO!
> 
> - The .CO Team

That sounds to me like a breakdown in communication. :-/

**Comment by chadwhitacre** [comment]
> give me access to Gratipay's iwantmyname account

Sounds like a plan. How about I change the email address and then you can generate a password reset? What address would you like me to use?

**Comment by Changaco** [comment]
admin at liberapay.com

**Comment by chadwhitacre** [comment]
Done!

![screen shot 2018-01-24 at 4 52 54 pm](https://user-images.githubusercontent.com/134455/35359168-100f0362-0127-11e8-9cf8-82796ccc42d9.png)

**Comment by chadwhitacre** [comment]
@Changaco Since that address is already linked on Twitter, how about using admin+gratipay at liberapay.com over there?

![screen shot 2018-01-24 at 4 54 29 pm](https://user-images.githubusercontent.com/134455/35359249-5dc1a6f0-0127-11e8-940e-62bb4ecc00ec.png)

**Comment by Changaco** [comment]
Got the confirmation email from iwantmyname.

Okay for admin+gratipay.

**Comment by chadwhitacre** [comment]
@Changaco Twitter handed over. I think we should do a final blog post on https://gratipay.news/ once the hand-off is complete. Let's coordinate on a Twitter announcement once we publish.

**Comment by chadwhitacre** [comment]
Re: logo the heart-coin shape is here:

https://github.com/gratipay/gratipay.com/blob/master/www/assets/heart-coin.black.svg

That's probably the file you want, ya?

**Comment by Changaco** [comment]
Password resets done for iwantmyname and twitter.

**Comment by Changaco** [comment]
> I think we should do a final blog post on https://gratipay.news/ once the hand-off is complete.

Sounds good to me.

**Comment by chadwhitacre** [comment]
Re: cash ... there may be costs associated with #1205. Let me see how far I can get with that in the next week or so before we make a final disbursement.

Re: database ... how do you want me to deliver this to you? We have weekly backups going back to the beginning. Do you want them all or just the final snapshot?

**Comment by Changaco** [comment]
Regarding the logo it's more of a symbolic hand-off. I guess you could formally state that the logo's copyright and implicit trademark are transferred to the Liberapay nonprofit organization, maybe that would please the lawyers (if we had any).

**Comment by Changaco** [comment]
Regarding the database I think the final snapshot is enough. Maybe throwing in the last backup before Gratipay 2.0 makes sense? I don't remember if any data was deleted.

**Comment by Changaco** [comment]
gratipay.news has been renewed.

I've updated the contact info so the next invoice will be addressed to me & Liberapay instead of Chad & Gratipay.

I've also checked and updated the settings of all domains:

- gttp.co was still pointing to the Digital Ocean IP address 198.199.102.190 which is now used by someone else, I've removed the A record
- all domains using the DNSimple name servers have been switched to iWantMyName or Cloudflare
- gratipay.com, .org, and .net are now in Liberapay's Cloudflare account

**Comment by chadwhitacre** [comment]
![screen shot 2018-01-29 at 10 46 09 am](https://user-images.githubusercontent.com/134455/35519240-b16bb9f4-04e1-11e8-8c2e-30a0191137a7.png)

**Comment by chadwhitacre** [comment]
I formally state that the logo's copyright and implicit trademark are transferred to the Liberapay nonprofit organization. :)

**Comment by chadwhitacre** [comment]
![screen shot 2018-01-29 at 10 51 34 am](https://user-images.githubusercontent.com/134455/35519495-6a99bca0-04e2-11e8-9f0c-1fcc836814de.png)

**Comment by chadwhitacre** [comment]
Actually, that was probably premature. I think @clone1018 and I should be co-owners on the GitHub org until we resolve #1205 and close down the LLC.

**Comment by chadwhitacre** [comment]
Sooooo ... @Changaco would you mind reinviting us? 😬

**Comment by chadwhitacre** [comment]
🙇 

![screen shot 2018-01-29 at 11 03 04 am](https://user-images.githubusercontent.com/134455/35520108-10cb0a6a-04e4-11e8-853a-435aa983e243.png)

**Comment by chadwhitacre** [comment]
I've reinvited @clone1018.

**Comment by chadwhitacre** [comment]
@Changaco Turns out Gratipay still has a DropBox account. Are you comfortable using DropBox to transfer the database file? If so I will email you a link.

**Comment by chadwhitacre** [comment]
Also, ftr, please preserve the MX records for `gratipay.com` so I can access email while we wind down the LLC.

**Comment by chadwhitacre** [comment]
@Changaco How would you like to do the db transfer? SFTP? Dropbox? ...?

**Comment by Changaco** [comment]
I would feel better if the file was encrypted end-to-end (so, not Dropbox). I suggest https://framadrop.org/ with "Delete at first download" on.

(A direct transfer via WebRTC would be cool, I found <https://file.pizza/> and <https://www.sharedrop.io/> after a quick search, but I trust the folks behind Framadrop more.)

**Comment by chadwhitacre** [comment]
Okay @Changaco, I've emailed you a Framadrop link (24-hour, delete-on-download).

I don't think we're going to be able to send you any cash, because I think what little we have left should go towards #1220.

**Comment by Changaco** [comment]
Email received, downloading the file.

**Comment by chadwhitacre** [comment]
@Changaco I just sent the latest. We may have deleted `toots` or something but `tips` and `transfers` should still be in there (we kept those for history pages). If you see missing tables from pre-2.0 that you want let me know and I can dig up another backup.

**Comment by Changaco** [comment]
Download and decompression complete. I'll do the rest tomorrow.

**Comment by Changaco** [comment]
I've loaded the DB backup and started to take a look.

One simple thing we could do with the data is bring back user pages on gratipay.com. A message explaining that Gratipay shut down would be nicer than a GitHub 404 page.

Another thing we could do is email users who sent or received money in 2017 to inform them of the Gratipay shutdown and the hand-off to Liberapay. That would be less than 600 people AFAICT.

**Comment by Changaco** [comment]
@chadwhitacre Do you want to write the blog post draft announcing the hand-off, or should I?

**Comment by chadwhitacre** [comment]
@Changaco If you've got the energy to, go ahead.

**Comment by Changaco** [comment]
gttp.co has expired. I guess that means auto-renewal was mistakenly disabled.

iwantmyname is asking for €84 to restore the domain, that's a €40 [restore fee](https://iwantmyname.com/domains/restore-prices) on top of the normal €44 yearly rent.

**Comment by chadwhitacre** [comment]
@Changaco Are you planning to just let it go?

**Comment by Changaco** [comment]
No, I've just been wondering if we can take the risk of dodging the restore fee by waiting or if we should just pay it.

I do wish we had some logs to see who is still using the domain, or at least how much it's used. I should have set that up when I had the chance.

**Comment by chadwhitacre** [comment]
> No, I've just been wondering if we can take the risk of dodging the restore fee by waiting or if we should just pay it.

My sense is that it's a significant risk. I don't fully understand the ins and outs, but I know at least GoDaddy has an [expiring domains auction](https://www.godaddy.com/help/bid-on-expiring-domains-893).

**Comment by Changaco** [comment]
I've made the payment to restore the domain.

**Comment by Changaco** [comment]
The domains are now configured so that we have logs of requests. Currently there are around 6 requests per minute (both domains combined).

**Comment by Changaco** [comment]
(So far I haven't found the time and inspiration to write a blog post about the hand-off.)

**Comment by chadwhitacre** [comment]
Draft: [Vive Liberapay!](https://medium.com/@chadwhitacre/vive-liberapay-93e485429045)

Intending to publish today, as it is the sixth anniversary of the conception of Gittip.

**Comment by chadwhitacre** [comment]
Here are the final `charts.json` and `payment-distribution.json` from the Gratipay stats page:

https://gist.github.com/chadwhitacre/fff5a2c398e2c042bd41ed96419f3823

**Comment by chadwhitacre** [comment]
Here is some [code](https://gist.github.com/chadwhitacre/4ba8e8dd6e3d66896b6d3e482852b065) to merge the Gratipay and [Liberapay](https://gist.github.com/chadwhitacre/25322b979225ed0bb6be0bb1e1787007) numbers together into [a CSV](https://gist.github.com/chadwhitacre/b1953204e241b79fc0bf15d76ab5f0ed). Amounts are converted to EUR based on historical rate [data](https://gist.github.com/chadwhitacre/660da50cca7b780bfe6a56c251599b60) (from [here](https://fred.stlouisfed.org/series/DEXUSEU)), and dates are normalized to Monday to fold weeks together.

**Comment by chadwhitacre** [comment]
![chart 2](https://user-images.githubusercontent.com/134455/39938186-217b64b8-5520-11e8-951f-9541fcd9c13c.png)

https://docs.google.com/spreadsheets/d/1uCSbevDviHbMUsDn4syOpRmxLBs9GbFZyEQ82sKBNSM/edit?usp=sharing

**Comment by chadwhitacre** [comment]
Final draft: [Vive Liberapay!](https://gratipay.news/vive-liberapay-93e485429045)

**Comment by chadwhitacre** [comment]
Fixed the title (yes?): [Vive la Liberapay!](https://gratipay.news/vive-la-liberapay-14057a25eacb)

**Comment by chadwhitacre** [comment]
Published! 💃

https://gratipay.news/vive-la-liberapay-14057a25eacb

**Comment by Changaco** [comment]
> Fixed the title (yes?)

No, "Vive Liberapay!" was correct. However "Vive la Liberapay!" could be considered a wordplay, it sounds somewhat like "Vive la Liberté!", so it's actually kind of funny.

**Comment by chadwhitacre** [comment]
@Changaco Sorry. 😞 Do you want me to change it or leave it? It's too late to change the URL slug unless we delete and recreate the post, which would break existing links ([e.g.](https://twitter.com/kennethreitz/status/995294825464455169)).

**Comment by chadwhitacre** [comment]
... but we can change the title easily enough.

**Comment by chadwhitacre** [comment]
I changed the title. I guess the URL path can be an inside joke. :o)

**Comment by techtonik** [comment]
https://gratipay.news/vive-la-liberapay-14057a25eacb

**Comment by Changaco** [comment]
https://twitter.com/Gratipay/status/996329607463923712

**Comment by chadwhitacre** [comment]
Too bad Medium isn't picking up the chart image to include on Twitter ... I think it's cause the resolution is too low?

**Comment by prodoxx** [comment]
Woah!

**Comment by payfittest** [comment]
👍
