### ISSUE TITLE
Flush money via PayPal MassPay

### ISSUE THREAD

**Issue by chadwhitacre** [gratipay/inside.gratipay.com#1219]
## MassPays

1. https://www.paypal.com/activity/masspay/MPA-8X3U65VFBYQMW
1. https://www.paypal.com/activity/masspay/MPA-3SPG7EDFLJ298
1. https://www.paypal.com/activity/masspay/MPA-SHFNU2CLL6GFE
1. https://www.paypal.com/activity/masspay/MPA-H4GXTPZZFY8Q4
1. https://www.paypal.com/activity/masspay/MPA-YWX7H2DCNZ5GQ

----------

Reticketing from https://github.com/gratipay/inside.gratipay.com/issues/1205#issuecomment-358768541:

> Where we have an email address, we can try sending via PayPal even if not explicitly linked to PayPal.
> 
> ```
> gratipay-bak=# select count(*), sum(balance) volume, email_address is not null as > have_email_address from participants where balance > 0 group by email_address is not null;
> ┌───────┬──────────┬────────────────────┐
> │ count │  volume  │ have_email_address │
> ├───────┼──────────┼────────────────────┤
> │  3162 │ 91861.94 │ f                  │
> │   602 │ 12928.67 │ t                  │
> └───────┴──────────┴────────────────────┘
> (2 rows)
> 
> gratipay-bak=#
> ```

**Comment by Changaco** [comment]
```sql
SELECT sum(p.balance)
  FROM participants p
 WHERE exists (select 1 from email_addresses e where e.participant_id = p.id)
    OR exists (select 1 from elsewhere e where e.email like '%@%' and e.participant = p.username);
   sum    
----------
 63171.28
```

**Comment by chadwhitacre** [comment]
Probably worth individually contacting the top 100 or so folks. Could we clear out half the money that way?

```
gratipay-bak=# select count(*), sum(balance) from (select username, balance from participants where balance > 1000 order by balance desc) foo;
┌───────┬──────────┐
│ count │   sum    │
├───────┼──────────┤
│    13 │ 24934.11 │
└───────┴──────────┘
(1 row)

gratipay-bak=# select count(*), sum(balance) from (select username, balance from participants where balance > 500 order by balance desc) foo;
┌───────┬──────────┐
│ count │   sum    │
├───────┼──────────┤
│    28 │ 34907.09 │
└───────┴──────────┘
(1 row)

gratipay-bak=# select count(*), sum(balance) from (select username, balance from participants where balance > 200 order by balance desc) foo;
┌───────┬──────────┐
│ count │   sum    │
├───────┼──────────┤
│    90 │ 54300.34 │
└───────┴──────────┘
(1 row)

gratipay-bak=# select count(*), sum(balance) from (select username, balance from participants where balance > 100 order by balance desc) foo;
┌───────┬──────────┐
│ count │   sum    │
├───────┼──────────┤
│   216 │ 71718.69 │
└───────┴──────────┘
(1 row)

gratipay-bak=#
```

**Comment by chadwhitacre** [comment]
```
gratipay-bak=# select sum(balance) from (select username, balance from participants order by balance desc limit 100) foo;
┌──────────┐
│   sum    │
├──────────┤
│ 56240.30 │
└──────────┘
(1 row)

gratipay-bak=#
```

**Comment by chadwhitacre** [comment]
On the other hand a lot of that is probably also included in https://github.com/gratipay/inside.gratipay.com/issues/1219#issuecomment-367676915, so makes sense to first do the general blast via PayPal and then follow up with targeted based on state of play at that point.

**Comment by chadwhitacre** [comment]
We have multiple email addresses for some people, for others we have none.

- [x] generate a list of `amount, email address, ..., email address`
- [x] spit out a masspay CSV with `amount, email address`
- [x] determine the aggregate amount
- [x] move enough funds into the PayPal account to cover the masspay
- [x] publish a blog post describing what we're doing
- [x] sort out fee downcharge: https://github.com/gratipay/inside.gratipay.com/issues/1219#issuecomment-442312840
- [x] **submit [a test run of] the masspay!** with an explanation and link to the blog post
- [x] ensure that the explanation and link to the blog post look okay
- [x] **submit the masspay!** with an explanation and link to the blog post
- [x] mark successes as complete
- [ ] retry failures with next email address
- [ ] repeat until there are no more remaining balances with available addresses
- [x] for large balances (threshold TBD), try to track down an email address through manual searching
- [ ] repeat
- [ ] call it a day, see what the remaining total escrow balance is and zoom back out to #1205

**Comment by chadwhitacre** [comment]
Code: https://github.com/gratipay/logs/tree/master/misc/1205

**Comment by chadwhitacre** [comment]
Well, code _and data_. Will (cross?)post code publicly as it develops.

**Comment by chadwhitacre** [comment]
Per inspection, nobody has more than five addresses on file.

Tooling:

- [x] SQL query to give `balance, email 1, ..., email 5` > `payouts.csv`
- [x] script to take `payouts.csv` and `blacklist.csv` as inputs and output a MassPay CSV input file
- [x] script to take MassPay output file and generate/update a `blacklist.csv`

**Comment by chadwhitacre** [comment]
```
gratipay-bak=# \i payout.sql
SELECT 3764
gratipay-bak=# \copy tmp to 'payouts.csv' with csv header
COPY 3764
gratipay-bak=#
```

```sql
  SELECT p.balance
       , (select count(*) from elsewhere e where e.email like '%@%' and e.participant = p.username) as n
       , p.username
       , p.email_address as address_1
       , (select e.email from elsewhere e where e.email like '%@%' and e.participant = p.username limit 1) as address_2
       , (select e.email from elsewhere e where e.email like '%@%' and e.participant = p.username offset 1 limit 1) as address_3
       , (select e.email from elsewhere e where e.email like '%@%' and e.participant = p.username offset 2 limit 1) as address_4
       , (select e.email from elsewhere e where e.email like '%@%' and e.participant = p.username offset 3 limit 1) as address_5
    INTO tmp
    FROM participants p
   WHERE balance > 0
ORDER BY n desc, balance desc;
```

**Comment by chadwhitacre** [comment]
> To get started, upload a CSV or TXT file of up to 5,000 payment recipients.

Fits in a batch. 👍

**Comment by chadwhitacre** [comment]
> organize your recipient information into the 3 required fields:
> 
>     • Recipients’ email addresses, mobile phone numbers, or PayPal IDs
>     • Payment amounts
>     • Currency type

**Comment by chadwhitacre** [comment]
Per old logs, currency type is `usd`

**Comment by chadwhitacre** [comment]
```
$ ./genmasspay.py
62072.15
$ cat genmasspay.py
```

```python
#!/usr/bin/env python3
import csv
from collections import OrderedDict
from decimal import Decimal as D

payouts = csv.reader(open('payouts.csv'))
masspay = csv.writer(open('masspay.csv', 'w+'))
headers = next(payouts)
blacklist = set(open('blacklist.csv').read().splitlines())
total = D('0.00')

for row in payouts:
    balance = row[0]
    addresses = list(OrderedDict.fromkeys(row[3:]))
    for address in addresses:
        if not address or address in blacklist:
            continue
        masspay.writerow([address, balance, 'usd'])
        total += D(balance)
        break

print(total)
```

**Comment by chadwhitacre** [comment]
![screen shot 2018-11-27 at 5 16 04 pm](https://user-images.githubusercontent.com/134455/49115204-27059d00-f268-11e8-9e7a-b3a8551fea2b.png)

**Comment by chadwhitacre** [comment]
![screen shot 2018-11-27 at 5 16 35 pm](https://user-images.githubusercontent.com/134455/49115228-3c7ac700-f268-11e8-8e0c-457bcc209351.png)

**Comment by chadwhitacre** [comment]
Will give that time to clear (trip fraud?) and write up a blog post!

**Comment by chadwhitacre** [comment]
💃

**Comment by chadwhitacre** [comment]
This [evening](https://www.meetup.com/Pittsburgh-Code-Supply/events/256571013/), I hand-delivered $420 in cash to someone who is friends with someone who had money escrowed with us. 💃

**Comment by chadwhitacre** [comment]
What about fees on PayPal don't we have to downcharge or somesuch?

**Comment by chadwhitacre** [comment]
Transfer complete!

![screen shot 2018-12-10 at 11 49 16 am](https://user-images.githubusercontent.com/134455/49747565-aa17f180-fc71-11e8-8b2a-ceb4180f005e.png)

**Comment by chadwhitacre** [comment]
Prepping a chart for the blog post.

```
gratipay-bak=# \i charts.sql
UPDATE 2827
UPDATE 720
UPDATE 204
UPDATE 13
UPDATE 2112
┌──────┬──────────┐
│  n   │    s     │
├──────┼──────────┤
│   13 │ 24934.11 │
│  204 │ 46884.58 │
│  720 │ 24591.42 │
│ 2827 │  8380.50 │
└──────┴──────────┘
(4 rows)

┌──────┬──────────┐
│  n   │    s     │
├──────┼──────────┤
│    7 │ 14153.18 │
│  127 │ 29339.36 │
│  422 │ 14244.29 │
│ 1556 │  4335.32 │
└──────┴──────────┘
(4 rows)

gratipay-bak=#
```

```sql
alter table tmp add column bucket int default 0;
update tmp set bucket=0 where balance >= 0 and balance < 10;
update tmp set bucket=1 where balance >= 10 and balance < 100;
update tmp set bucket=2 where balance >= 100 and balance < 1000;
update tmp set bucket=3 where balance >= 1000;

alter table tmp add column has_email bool default false;
update tmp
   set has_email=true
 where coalesce(address_1, address_2, address_3, address_4, address_5) is not null
      ;

select count(balance) n, sum(balance) s from tmp group by bucket order by bucket desc;
select count(balance) n, sum(balance) s from tmp where has_email group by bucket order by bucket desc;

```

**Comment by chadwhitacre** [comment]
```
gratipay-bak=# select has_email e, sum(balance) s from tmp group by has_email;
┌───┬──────────┐
│ e │    s     │
├───┼──────────┤
│ f │ 42718.46 │
│ t │ 62072.15 │
└───┴──────────┘
```

**Comment by chadwhitacre** [comment]
```
gratipay-bak=# select sum(balance) from tmp;
┌───────────┐
│    sum    │
├───────────┤
│ 104790.61 │
└───────────┘
```

**Comment by chadwhitacre** [comment]
https://medium.com/@chadwhitacre/gratipay-payout-aeb2e985d537

https://docs.google.com/spreadsheets/d/1Ybb6_UeCI-HtQ8WuTN1YcPmRi30w-pERGZ4koRBJzeg/edit?usp=sharing

![screen shot 2018-12-10 at 2 05 40 pm](https://user-images.githubusercontent.com/134455/49754660-b194c600-fc84-11e8-9c06-dd044e5ec868.png)

**Comment by chadwhitacre** [comment]
Submitted to https://gratipay.news/:

https://gratipay.news/paypal-push-aeb2e985d537

cc: @Changaco

**Comment by chadwhitacre** [comment]
I've confirmed that I have access to the {paypal,support}@gratipay.com email addresses.

**Comment by chadwhitacre** [comment]
Hmm ... actually ... maybe we should manually pursue the n=13 that are > $1000 first? And then do a masspay for the long tail?

**Comment by chadwhitacre** [comment]
Yeah let's do that: #1225.

**Comment by chadwhitacre** [comment]
Published: https://gratipay.news/flushing-the-system-aeb2e985d537.

**Comment by chadwhitacre** [comment]
Gearing up for a masspay! Need to figure out fee ...

![screen shot 2018-12-14 at 12 39 34 pm](https://user-images.githubusercontent.com/134455/50018444-5e30b980-ff9d-11e8-9def-f653d8a6ab54.png)

**Comment by chadwhitacre** [comment]
Also have to expect min payout variance ($1 vs. $20). Hoo boy.

**Comment by chadwhitacre** [comment]
https://github.com/gratipay/logs/commit/5d086ef9456b0920ff0baea67d2cb805dfa6fa91

```
$ ./genmasspay.py 
               n                $
           ------------- ------------------
  settled     18 ( 0.5%)  27,196.57 (26.0%)
remaining  3,746 (99.5%)  77,594.04 (74.0%)
    total  3,764         104,790.61

  masspay  2,096 (55.7%)
    gross                 46,932.82 (44.8%)
      fee                    454.07
      net                 46,474.61
remainder                      4.14
$
```

**Comment by chadwhitacre** [comment]
Ooh yay! Yes the numbers are off in PayPal but if I click "View All" I get a detailed listing that include fees, I should be able to weed out (almost?) all of the $20 fee caps through there! 💃

![screen shot 2018-12-14 at 1 57 37 pm](https://user-images.githubusercontent.com/134455/50021845-4dd20c00-ffa8-11e8-9ace-69cd2094fbb1.png)

**Comment by chadwhitacre** [comment]
https://github.com/gratipay/logs/commit/54755faec3030a7f6c59e70f51a1b1e6387acd94 💃

```
$ ./genmasspay.py 
               n                $
           ------------- ------------------
  settled     18 ( 0.5%)  27,196.57 (26.0%)
remaining  3,746 (99.5%)  77,594.04 (74.0%)
    total  3,764         104,790.61

  masspay  2,062 (54.8%)
    gross                 46,932.48 (44.8%)
      fee                    583.85
      net                 46,344.83
remainder                      3.80
$
```

![screen shot 2018-12-14 at 2 07 59 pm](https://user-images.githubusercontent.com/134455/50022309-ad7ce700-ffa9-11e8-821f-a3efecf8d2ae.png)

**Comment by chadwhitacre** [comment]
Okay! I think I'm going to go for it ...

**Comment by chadwhitacre** [comment]
> Final Gratipay Payout
>
> Greetings! You have been carrying a balance on Gratipay (aka Gittip), and we would like to send you your money using PayPal. Details: https://gratipay.news/aeb2e985d537. Thanks! :)

**Comment by chadwhitacre** [comment]
Last call ...

https://github.com/gratipay/logs/commit/09f4ce9c7ce7008f2cb815eb7bac2c01cea4ef74

```
$ ./genmasspay.py 
               n                $
           ------------- ------------------
  settled     18 ( 0.5%)  27,196.57 (26.0%)
remaining  3,746 (99.5%)  77,594.04 (74.0%)
    total  3,764         104,790.61

  masspay  2,062 (54.8%)
   target                 46,932.48
remainder               -      3.80
                         ----------
   actual                 46,928.68 (44.8%)
      fee               -    583.85
                         ----------
      net                 46,344.83
$
```

![screen shot 2018-12-14 at 2 17 50 pm](https://user-images.githubusercontent.com/134455/50022698-0e58ef00-ffab-11e8-816f-8389ef5d063e.png)

**Comment by chadwhitacre** [comment]
😳

![screen shot 2018-12-14 at 2 20 07 pm](https://user-images.githubusercontent.com/134455/50022807-5ed04c80-ffab-11e8-86be-c882ce07b22a.png)

**Comment by chadwhitacre** [comment]
💃

> You sent a Mass Payment of $46,928.68 USD
> 
> Summary
> 
> Denied (58)             $2,273.11 USD
> Claimed (1408)          $29,751.52 USD
> Unclaimed (596)         $14,320.20 USD

**Comment by chadwhitacre** [comment]
![screen shot 2018-12-14 at 2 26 01 pm](https://user-images.githubusercontent.com/134455/50023095-33019680-ffac-11e8-9b00-92041ee55b09.png)

💃 💃 💃 💃 💃 💃 💃 💃 💃 💃 💃

**Comment by chadwhitacre** [comment]
https://www.paypal.com/activity/masspay/MPA-8X3U65VFBYQMW

**Comment by chadwhitacre** [comment]
First response! :D

> Awesome!
> 
> Is there a way for me to see what this is for?

-------

> Thanks for asking, []! Payments on Gratipay/Gittip were anonymous (in order to be no strings attached!), so we can't say exactly who paid you for what ... but in general it was probably for your awesome and inspiring open source work! :)

**Comment by chadwhitacre** [comment]
Second!

> Hi, I’m only been vaguely aware of gratipay back when it was gittip.
>
> And today I got notification from PayPal that I just received $31.81.
>
> Why?  Where did that come from?  I’ve never asked anyone to pay to Gratipay nor have I ever heard of anyone doing so.

------

> Thanks for getting in touch, []! Looks like you had a handful of patrons back in 2014/2015. Probably grateful [] users? I've been a grateful [] user, too! Thanks for your work! :)
> 
> The reason you're getting this money now is that Gratipay shut down a year ago and I'm finally getting around to [flushing the system](https://gratipay.news/flushing-the-system-aeb2e985d537).
> 
> The reason you haven't heard about this money prior to now is that we didn't have an email address on file for you. As a last resort we harvested your email from your GitHub account in order to get you your money before finally going to bed for the night.
> 
> Hope that helps explain! Cheers! :)

**Comment by jiri-janousek** [comment]
Thanks for the payment :-)

**Comment by chadwhitacre** [comment]
Third! Updated the post with a FAQ.

https://gratipay.news/flushing-the-system-aeb2e985d537

**Comment by chadwhitacre** [comment]
https://github.com/gratipay/logs/commit/f65c388bf62472cb940ae92ae23357d986693b49

```
$ ./genmasspay.py 
               n                $
           ------------- ------------------
  settled  1,472 (39.1%)  59,508.19 (56.8%)
remaining  2,292 (60.9%)  45,282.42 (43.2%)
    total  3,764         104,790.61

  masspay    608 (16.2%)
   target                 14,620.86
remainder               -      0.98
                         ----------
   actual                 14,619.88 (14.0%)
      fee               -    161.52
                         ----------
      net                 14,458.36
$
```

**Comment by chadwhitacre** [comment]
I guess we give it 30 days to see what converts from Unclaimed to Returned?

![screen shot 2018-12-14 at 5 23 01 pm](https://user-images.githubusercontent.com/134455/50033035-ed9d9300-ffc4-11e8-8c84-4fabeba4b342.png)

**Comment by chadwhitacre** [comment]
https://github.com/gratipay/logs/commit/e84f54228f5ada500797b611cd6d229688e30694

```
$ ./genmasspay.py 
               n                $
           ------------- ------------------
  settled  1,498 (39.8%)  60,325.04 (57.6%)
remaining  2,266 (60.2%)  44,465.57 (42.4%)
    total  3,764         104,790.61

  masspay    582 (15.5%)
   target                 13,804.01
remainder               -      0.96
                         ----------
   actual                 13,803.05 (13.2%)
      fee               -    152.90
                         ----------
      net                 13,650.15
$
```

![screen shot 2018-12-15 at 9 26 30 am](https://user-images.githubusercontent.com/134455/50044003-870f8800-004b-11e9-9453-fa9250cd2416.png)

**Comment by chadwhitacre** [comment]
Ftr PayPal makes it pretty easy to connect a second email address to an existing account. I just did that for `chad+aspen@zetaweb.com`. 😬

**Comment by chadwhitacre** [comment]
https://github.com/gratipay/logs/commit/c02f9d5790db84c9d04d72ca9e8434b3bd921fc3

```
$ ./genmasspay.py 
               n                $
           ------------- ------------------
  settled  1,523 (40.5%)  61,102.95 (58.3%)
remaining  2,241 (59.5%)  43,687.66 (41.7%)
    total  3,764         104,790.61

  masspay    557 (14.8%)
   target                 13,026.10
remainder               -      0.95
                         ----------
   actual                 13,025.15 (12.4%)
      fee               -    143.73
                         ----------
      net                 12,881.42
$
```

![screen shot 2018-12-17 at 7 10 23 am](https://user-images.githubusercontent.com/134455/50086483-332bad00-01cb-11e9-8529-78ac47b52eb4.png)

**Comment by chadwhitacre** [comment]
I've gone through accounts with no email down to $100 and have manually located an email address (mostly by [harvesting GitHub](https://gist.github.com/chadwhitacre/d4cb21261e41a2da1dc3bc7f86e6879c) and reaching out on Twitter). I have started a transfer of another $20,000 from New Alliance to PayPal (leaving about $23,000 remaining in New Alliance). Once that clears I will process another MassPay. Perhaps I will locate emails for accounts down to $69 to cover the third [quartile](https://github.com/gratipay/inside.gratipay.com/issues/1205#issuecomment-446011658) by volume ...

I am going to manually pay out a few based on representations I made on Twitter that these would go out today/tomorrow.

**Comment by chadwhitacre** [comment]
https://github.com/gratipay/logs/commit/8afd2aaa92792ea8c75e53f0d2f00f3bf392df4f

Done down to $69. 👍

```
(env) $ ./genmasspay.py 
               n                $
           ------------- ------------------
  settled  1,554 (41.3%)  65,861.96 (62.9%)
remaining  1,654 (43.9%)  38,928.65 (37.1%)
    total  3,764         104,790.61

  masspay     89 ( 2.4%)
   target                 14,858.58
remainder               -      0.00
                         ----------
   actual                 14,858.58 (14.2%)
      fee               -     87.31
                         ----------
      net                 14,771.27
(env) $
```

**Comment by chadwhitacre** [comment]
Made those few individual payouts as well.

**Comment by chadwhitacre** [comment]
Okay! Got another MassPay [ready](https://github.com/gratipay/inside.gratipay.com/issues/1205#issuecomment-449151366) ...

**Comment by chadwhitacre** [comment]
Submitted with https://github.com/gratipay/logs/commit/a9a25b71e167720e0d4b5fe29ade270cec39bf06!

https://www.paypal.com/activity/masspay/MPA-3SPG7EDFLJ298

**Comment by chadwhitacre** [comment]
MassPay № 2 is still "Processing," making me kinda nervous ...

**Comment by chadwhitacre** [comment]
Yoi! Called PayPal, stuck on (silent) hold a loooong time (long enough to read the captions on all of the Bergeron's Christmas [cards](https://imgur.com/gallery/dmK2X)). Sounds like they're stumped! The dude was like, "the resolution specialist's manager is going to give you an email"—like, this was super weird for him. 😂

🤞

**Comment by chadwhitacre** [comment]
https://github.com/gratipay/logs/commit/ca14c79d1cf2b5aa8b39366248377c9f510353a9

```
$ ./tick.py 
               n                $
           ------------- ------------------
    ready     91 ( 2.4%)  14,704.73 (14.0%)
  pending    508 (13.5%)  14,337.03 (13.7%)
 complete  1,542 (41.0%)  61,826.70 (59.0%)
   failed  1,623 (43.1%)  13,922.15 (13.3%)
    total  3,764         104,790.61

  masspay     91 ( 2.4%)
   target                 14,704.73
remainder               -      0.00
                         ----------
   actual                 14,704.73 (14.0%)
      fee               -    142.37
                         ----------
      net                 14,562.36
$
```

**Comment by chadwhitacre** [comment]
Second masspay processed!

![screen shot 2018-12-22 at 8 54 53 pm](https://user-images.githubusercontent.com/134455/50380132-dfd2b800-062b-11e9-993b-f1926faf3670.png)

**Comment by chadwhitacre** [comment]
https://github.com/gratipay/logs/commit/7ed351d3c8e3edaa005104a1774b9d927c192b23

```
$ ./tick.py 
               n                $
           ------------- ------------------
    ready      0 ( 0.0%)       0.00 ( 0.0%)
  pending    475 (12.6%)  14,617.08 (13.9%)
 complete  1,663 (44.2%)  76,175.55 (72.7%)
   failed  1,626 (43.2%)  13,997.98 (13.4%)
    total  3,764         104,790.61

  masspay      0 ( 0.0%)
   target                      0.00
remainder               -      0.00
                         ----------
   actual                      0.00 ( 0.0%)
      fee               -      0.00
                         ----------
      net                      0.00
$
```

**Comment by chadwhitacre** [comment]
![screen shot 2018-12-22 at 11 43 12 pm](https://user-images.githubusercontent.com/134455/50380836-5dee8900-0643-11e9-9ec4-51059ba36474.png)

**Comment by chadwhitacre** [comment]
With #1226 we have another batch of masspays to submit! 💃



```
$ ./tick.py 
                 n                $
             ------------- ------------------
      ready    350 ( 9.3%)   2,959.62 ( 2.8%)
    pending    462 (12.3%)  11,257.56 (10.7%)
   complete  1,683 (44.7%)  81,326.50 (77.6%)
     failed  1,269 (33.7%)   9,246.93 ( 8.8%)
      total  3,764         104,790.61
 incomplete  2,081 (55.3%)  23,464.11 (22.4%)

     volume              1,003,648.55
  disbursed                983,144.06 (98.0)%

    masspay    350 ( 9.3%)
     target                  2,959.62
  remainder               -      0.65
                           ----------
     actual                  2,958.97 ( 2.8%)
        fee               -     56.08
                           ----------
        net                  2,902.89
$
```

**Comment by chadwhitacre** [comment]
Fee caps updated in https://github.com/gratipay/logs/commit/2767fc6419cf849d09b16fc01bfcb9012bd41271 ...

**Comment by chadwhitacre** [comment]
Lines up ...

```
$ ./tick.py 
                 n                $
             ------------- ------------------
      ready    350 ( 9.3%)   2,959.62 ( 2.8%)
    pending    462 (12.3%)  11,257.56 (10.7%)
   complete  1,683 (44.7%)  81,326.50 (77.6%)
     failed  1,269 (33.7%)   9,246.93 ( 8.8%)
      total  3,764         104,790.61
 incomplete  2,081 (55.3%)  23,464.11 (22.4%)

     volume              1,003,648.55
  disbursed                983,144.06 (98.0)%

    masspay    350 ( 9.3%)
     target                  2,959.62
  remainder               -      0.66
                           ----------
     actual                  2,958.96 ( 2.8%)
        fee               -     56.57
                           ----------
        net                  2,902.39
$
```

![screen shot 2019-01-02 at 5 55 30 pm](https://user-images.githubusercontent.com/134455/50616700-a1ed5380-0eb7-11e9-9a64-5812e12ef253.png)

**Comment by chadwhitacre** [comment]
Sent!

**Comment by chadwhitacre** [comment]
Hopefully this one doesn't take as long to post! 😆

**Comment by chadwhitacre** [comment]
Posted! 💃 

![screen shot 2019-01-02 at 6 01 54 pm](https://user-images.githubusercontent.com/134455/50616907-85055000-0eb8-11e9-9ab5-9b7d6f40f2af.png)

Fixed a bug in https://github.com/gratipay/logs/commit/b4ae65b5e6f3edc5fc7342deff5f51ac9a55b640 that overstated disbursed as 98% when it's still 97.7%.

```
$ ./tick.py 
                 n                $
             ------------- ------------------
      ready    350 ( 9.3%)   2,959.62 ( 2.8%)
    pending    462 (12.3%)  11,257.56 (10.7%)
   complete  1,683 (44.7%)  81,326.50 (77.6%)
     failed  1,269 (33.7%)   9,246.93 ( 8.8%)
      total  3,764         104,790.61
 incomplete  2,081 (55.3%)  23,464.11 (22.4%)

     volume              1,003,648.55
  disbursed                980,184.44 (97.7)%

    masspay    350 ( 9.3%)
     target                  2,959.62
  remainder               -      0.66
                           ----------
     actual                  2,958.96 ( 2.8%)
        fee               -     56.57
                           ----------
        net                  2,902.39
$
```

Can we get to 98% over the next month or two!?!? 🤞

**Comment by chadwhitacre** [comment]
https://github.com/gratipay/logs/commit/de5d6c33c7a3bba5c2fa0bd56f17e31d010ec311

```
$ ./tick.py 
                 n                $
             ------------- ------------------
      ready      1 ( 0.0%)       9.23 ( 0.0%)
    pending    590 (15.7%)  12,252.61 (11.7%)
   complete  1,891 (50.2%)  83,093.68 (79.3%)
     failed  1,282 (34.1%)   9,435.09 ( 9.0%)
      total  3,764         104,790.61
 incomplete  1,873 (49.8%)  21,696.93 (20.7%)

     volume              1,003,648.55
  disbursed                981,951.62 (97.8)%

    masspay      1 ( 0.0%)
     target                      9.23
  remainder               -      0.00
                           ----------
     actual                      9.23 ( 0.0%)
        fee               -      0.18
                           ----------
        net                      9.05
$
```

**Comment by chadwhitacre** [comment]
Single ready payout handled manually in https://github.com/gratipay/logs/commit/f96489d5cbb268660173170c429102d94ae8da77. 👍

```
$ ./tick.py 
                 n                $
             ------------- ------------------
      ready      0 ( 0.0%)       0.00 ( 0.0%)
    pending    590 (15.7%)  12,252.61 (11.7%)
   complete  1,892 (50.3%)  83,102.91 (79.3%)
     failed  1,282 (34.1%)   9,435.09 ( 9.0%)
      total  3,764         104,790.61
 incomplete  1,872 (49.7%)  21,687.70 (20.7%)

     volume              1,003,648.55
  disbursed                981,960.85 (97.8)%
$
```

Okay! Now we wait ...

**Comment by chadwhitacre** [comment]
Third MassPay:

https://www.paypal.com/activity/masspay/MPA-SHFNU2CLL6GFE

Consolidated links in issue description.

**Comment by chadwhitacre** [comment]
First masspay is complete! I think we should wait for the other two to complete before issuing the next masspay.

![screen shot 2019-01-19 at 2 54 25 pm](https://user-images.githubusercontent.com/134455/51431649-2a7b2c00-1bfa-11e9-955b-56d795cdb257.png)

**Comment by chadwhitacre** [comment]
Second complete.

![screen shot 2019-01-21 at 6 10 14 pm](https://user-images.githubusercontent.com/134455/51503213-d57d1880-1da7-11e9-8dc4-811fed1d2e1a.png)

**Comment by chadwhitacre** [comment]
Third complete!

![screen shot 2019-02-01 at 8 29 00 pm](https://user-images.githubusercontent.com/134455/52157809-14d91e00-2660-11e9-8296-6ec3f6d0d222.png)

**Comment by chadwhitacre** [comment]
Fourth MassPay sent!

![screen shot 2019-02-01 at 8 37 14 pm](https://user-images.githubusercontent.com/134455/52157936-3981c580-2661-11e9-9f07-eb2874125ec8.png)

**Comment by chadwhitacre** [comment]
Worth doing! 💃

![screen shot 2019-02-01 at 8 39 51 pm](https://user-images.githubusercontent.com/134455/52157970-8fef0400-2661-11e9-88d2-1deba7c3ea06.png)

**Comment by chadwhitacre** [comment]
![Screen Shot 2019-03-13 at 9 15 13 PM](https://user-images.githubusercontent.com/134455/54324716-328d9180-45d5-11e9-9185-b6cef825de33.png)

**Comment by chadwhitacre** [comment]
![Screen Shot 2019-03-13 at 9 57 37 PM](https://user-images.githubusercontent.com/134455/54325961-155bc180-45db-11e9-8c10-a20879b20bbd.png)

**Comment by chadwhitacre** [comment]
Fifth MassPay complete!

![Screen Shot 2019-04-24 at 8 12 49 AM](https://user-images.githubusercontent.com/134455/56658515-cd639c00-6668-11e9-9ea1-f7e9608205c0.png)
