### ISSUE TITLE
understand obligations re: policing illegality

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#122]
Reticketed from https://github.com/gratipay/inside.gratipay.com/issues/118#issuecomment-68334387:

> Gratipay may even be obligated to pass on these reports to authorities as a "we believe this user may be doing something illegal, but they're using our site legally, so you might want to look into it so that we can terminate their account if you find that they're going something illegal."

**Comment by whit537** [comment]
Reopening because we've decided to hire a lawyer to pursue this question further.

**Comment by whit537** [comment]
Reopening because we've decided to hire a lawyer to pursue this question further.

**Comment by whit537** [comment]
Sent:

> Hey [person], we met a while back through [other person]. I have a startup that used to be called Gittip and is now called Gratipay. We're a crowdfunding platform. This past year we've had some users join our site, whom others are claiming are criminals. Long story short, I need some legal advice on my responsibilities as a platform for policing user behavior.
> 
> Is that something you or someone else at [your firm] could help me with? What do you need from me to put a quote together?
> 
> Thanks! :)

**Comment by mattbk** [comment]
+1

**Comment by whit537** [comment]
Email sent to another lawyer contact:

> I've got a legal matter I could use advice on. I run a social payments site called Gratipay and I need to understand what my responsibilities are for policing the off-site behavior of my users. Seems like [your firm] mostly focuses on IP. Do you have a recommendation for someone who could help me with liability for policing users?

**Comment by whit537** [comment]
https://www.wilmerhale.com/

[IRC](https://botbot.me/freenode/gratipay/2015-04-17/?msg=36874964&page=1)

**Comment by techtonik** [comment]
I don't think Gratipay should be a policeman of the Internet. If people feel that somebody is receiving money for illegal activities, they should escalate the problem with authorities, who should investigate and issue a ban order. If we will be banning users just because other users complain about their offsite behavior, we will use our auditory. Open culture, unfortunately, means that conflicts  of opinions are inevitable, and you don't want to be the weapon in those dirty wars.

**Comment by whit537** [comment]
@techtonik The question here is what our legal obligations are, not what our preferences are.

**Comment by whit537** [comment]
We have a lawyer now, but no money. Let's revisit this when we have money to have our lawyer advise us on this.

**Comment by whit537** [comment]
Closing as moot in light of the team review in [Gratipay 2.0](https://medium.com/gratipay-blog/gratipay-2-0-2453d3c53077).
