### ISSUE TITLE
Fold back down to single-member LLC

### ISSUE THREAD

**Issue by chadwhitacre** [gratipay/inside.gratipay.com#1223]
We brought @clone1018 on as a second owner in #196. That complicates his life and mine with things like #1222 for little added value now that we're closing up shop. It seems like we should release you again, @clone1018, effective end of 2017 if we can. Thoughts?

**Comment by clone1018** [comment]
Does it matter if you remove me? I was still technically a second owner during the 2017 tax period right?

**Comment by chadwhitacre** [comment]
It doesn't matter for 2017 but it would matter for 2018 and beyond. It's going to take a year or five to resolve #1220 and #1205.

**Comment by chadwhitacre** [comment]
https://github.com/gratipay/inside.gratipay.com/blob/c67ee769a5530ba8b35677e9bac250a4da4e2e81/www/big-picture/operating-agreement.spt#L53

Looks like you're free to say you left Gratipay the day you started, @clone1018, if you want to make your life easier by not having to deal with #1222 #1220 etc.

**Comment by chadwhitacre** [comment]
(In view of the fact that you didn't really take any money last year, only 52¢, and your share of the loss is so small, $38.)

**Comment by chadwhitacre** [comment]
I guess technically you took 24¢ as a contractor and 28¢ in guaranteed payments as an owner. 😅

```
gratipay-bak=# select sum(amount) from payments where team='Gratipay' and direction='to-participant' and "timestamp"::text > '2017-01-01' and "timestamp"::text < '2017-06-17' and participant='clone1018';
┌──────┐
│ sum  │
├──────┤
│ 0.24 │
└──────┘
(1 row)

gratipay-bak=# select sum(amount) from payments where team='Gratipay' and direction='to-participant' and "timestamp"::text > '2017-06-17' and "timestamp"::text < '2018' and participant='clone1018';
┌──────┐
│ sum  │
├──────┤
│ 0.28 │
└──────┘
(1 row)

gratipay-bak=#
```

**Comment by chadwhitacre** [comment]
@clone1018 and I just talked on the phone, and agreed for him to remove himself from Gratipay effective just after he joined, to avoid entangling him in #1220 #1222 and whatever else arises.

@clone1018 I will let you close this ticket to signal your assent, ya?

**Comment by clone1018** [comment]
:)

**Comment by chadwhitacre** [comment]
You are a pioneer, @clone1018! xoxo
