### ISSUE TITLE
figure out recording of retreat

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#123]
Last year we hired someone to record all of Saturday:

 - Session 1: https://www.youtube.com/watch?v=Dmwo28A5vd8
 - Session 2: https://www.youtube.com/watch?v=ILScnYBkkO4
 - Session 3: https://www.youtube.com/watch?v=_Lz6S7OmbGI
 - Session 4: https://www.youtube.com/watch?v=7lz-oKv9bhI

It was uploaded after the fact.

I was kind of thinking we may just buy our own camera/mic this year. What parts do we want to record? Do we want to try to livestream, or upload after the fact again?

This is a bit hotter than expected due to #118.

**Comment by whit537** [comment]
If we want to record for hours on end like last time, should we be dumping straight to a hard drive?

**Comment by seanlinsley** [comment]
@whit537 I'm not sure what your question is, exactly. I'm currently taking a look at https://www.obsproject.com/ which should let us stream & record.

**Comment by whit537** [comment]
@seanlinsley I was thinking about hardware. I don't have a clear picture of what we'd need. Maybe we can swing by BestBuy after I pick yinz up?

**Comment by whit537** [comment]
@clone1018 gave me the raw video and audio files. I'm going to sync them up and upload to YouTube.

**Comment by whit537** [comment]
I ended up making a new ticket for getting the videos on YouTube: #130.
