### ISSUE TITLE
take on board EFF's article on harassment

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#127]
"[Facing the Challenge of Online Harassment](https://www.eff.org/deeplinks/2015/01/facing-challenge-online-harassment)"
by [Nadia Kayyali](https://www.eff.org/about/staff/nadia-kayyali) and [Danny O'Brien](https://www.eff.org/about/staff/danny-obrien-0)
January 8, 2015

> In the nearly 25 years that EFF has been defending digital rights, our belief in the promise of the Internet has only grown stronger. The digital world frees users from many limits on communication and creativity that exist in the offline world. But it is also an environment that reflects the problems in wider society and grants them new dimensions. Harassment is one of those problems.

**Comment by whit537** [comment]
Made a first pass through. "Empower Users, Really" is a good section that relates to what we were saying at the retreat about giving users the tools they need to create their own "safe space" within Gratipay (e.g., https://github.com/gratipay/gratipay.com/pull/3077). Also, our communities feature lends itself to point two:

> - Better ways for communities to collectively monitor for harassing behavior and respond to it— rather than, as now, placing the burden on individuals policing their own social media streams.

**Comment by seanlinsley** [comment]
Related: https://jilliancyork.com/2015/01/09/a-note-from-kathy-sierra/

**Comment by whit537** [comment]
Interesting.

**Comment by techtonik** [comment]
The same concerns about free speech are raised against Facebook -
http://www.nbcnews.com/storyline/paris-magazine-attack/je-suis-facebook-mark-zuckerbergs-post-raises-free-speech-questions-n282956

Belarus have just passed a law when every online resource becomes mass
media. That's means that if you're not careful to speak about what you
think, potentially every person can fill a complain and government will
bring you down after third warning. I fear that businesses that cross the
interest with communities will take great advantage of that.
