### ISSUE TITLE
Giving used to be centralized

### ISSUE THREAD

**Issue by colinta** [gratipay/inside.gratipay.com#131]
I liked that more.  Is it coming back?

I just spent many minutes (maybe 5-10) in frustration trying to get to the "edit my giving" page.  Couldn't find it, couldn't find it, finally for no particular reason at all I opened a profile, and saw "edit" there.

I think this should be done from this screen:

**Comment by colinta** [comment]
![screen shot 2015-01-16 at 5 32 04 pm](https://cloud.githubusercontent.com/assets/27570/5786653/dc65473e-9da5-11e4-92e5-5f6b05647192.png)

**Comment by colinta** [comment]
And YES, I was actually increasing my contribution to gratipay!  Great work, love gratipay.

Except for the decision about infinitechan that was f-ing retarded.  Pedophiles, people PE-DO-PHILES.  NO, you say F-ING NO to pedophiles!  Geez.  Bad bad bad call there.  Kick those f*cks OUT.  You know they get over $200 in evil-doer money from your site?  You better not be sleeping at night because of this, it's downright despicable.

*ahem* Anyway, I hope you bring back centralized editing of "giving" and I hope you kick out people who are well known evil-doers.  Racist groups also should get the boot.  OBVIOUSLY.

**Comment by colindean** [comment]
The restoration of the feature to mass adjust tips is being tracked on the app's issue tracker: gratipay/gratipay.com#3107.

Discussions on user behavior in general is spread among other issues on this tracker, as well as privately in accordance with [how Gratipay handles reports of terms violations](http://inside.gratipay.com/howto/handle-terms-violations). 

I'm going to close this as a duplicate for now. Thanks for using and especially donating to Gratipay!
