### ISSUE TITLE
Multilingual support for inside.gratipay.com

### ISSUE THREAD

**Issue by slaivyn** [gratipay/inside.gratipay.com#132]
http://inside.gratipay.com does not seem to support multilingual (while https://gratipay.com does).
If this support could be added I would be happy to help for the French translation.

**Comment by colindean** [comment]
:+1:

**Comment by whit537** [comment]
Thanks @slaivyn! Inside Gratipay is our internal company portal, and our working language is English. Is there specific content that you'd like to see translated? I.e., I could see translating the mission statement and maybe some other higher-level docs, but on the other hand I don't see as big a need to translate the HOWTOs. Do you think we should translate the whole IG site?

**Comment by slaivyn** [comment]
I believe that "the big picture" pages are quite important to let non English speakers understand what's the philosophy behind Gratipay (there is few information on gratipay.com).
I agree with you for the HOWTOs: people who would be interested by them would probably be quite comfortable with English.

**Comment by whit537** [comment]
Okay, so how about we handle this with language directories under `/big-picture/`. I started a branch for this but hit a limitation in the old version of Aspen we're using. We'll have to upgrade first (#133).

**Comment by slaivyn** [comment]
Fine for me. Let me know when it is ready :)

**Comment by whit537** [comment]
@slaivyn Will do. I've started an i18n PR in #134. I roughed in a translation of the Welcome! page (using Google Translate) to illustrate the file structure I'm thinking of.

**Comment by whit537** [comment]
We should be able to write some nav helpers to link to translations automatically.

**Comment by techtonik** [comment]
If translation is just a separate page, how to keep translations in sync?

**Comment by slaivyn** [comment]
@techtonik I think the content is not changed often. If a ticket is created in Github for each change the translation requrest could be handled in the same ticket
