### ISSUE TITLE
use Gratipay money to send Chad to events

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#139]
I can't personally afford to go to any events this year. Is my/our presence important enough to justify spending company money to send me to any of these?

 - ~~#142 Jubilee Professional~~
 - #148 Center for Human Flourishing launch
 - ~~#145 Libre Planet~~
 - ~~#111 PyCon~~
 - #114 OuiShareFest
 - #87 #Cinderblocks
 - #138 Open Company Summit

**Comment by whit537** [comment]
I guess the way to do this is to estimate the cost for each event and the expected return.

**Comment by rohitpaulk** [comment]
How much do we have in operations?

**Comment by tshepang** [comment]
Of those, I think you should not miss Open Company Summit... you started the initiative after all.

**Comment by rohitpaulk** [comment]
I don't think that it's possible to estimate the 'expected return' for each event. 

If the costs are affordable, I don't see a reason for you to not attend :)

**Comment by techtonik** [comment]
Go Ahead! =)

**Comment by whit537** [comment]
| Ticket | Event | Registration ($) | Travel ($) | Total ($) | Community | Draw | Dates | Location |
| ---- | ----- | ---- | -------- | ---- | ---------- | -------- | ------ | --------- |
| #142 | [Jubilee Professional](http://professional.jubileeconference.com/)| 0 | 0 | 0 | Christians | 200 | Feb 20 | Pittsburgh |
| #145 | [Libre Planet](https://libreplanet.org/2015/) | 90 to 800 | 500 | 600 to 1,300 | FSF | 300 | March 21-22 | Boston |
| #111 | [PyCon](https://us.pycon.org/2015/) | 500 | 1,000 | 1,500 | Python | 2,500 | April 8-16 | Montréal |
| #114 | [OuiShareFest](http://2015.ouisharefest.com/) | 300 | 2,000 | 2,300 | collaborative economy | 1,000 | May 20-22 | Paris |
| #87 | [#Cinderblocks](https://www.eventbrite.com/e/cinderblocks2-tickets-6811480321) | 320 | 180 | 500 | patient advocates | 100 | June 4-6 | Grantsville, MD |
| #138 | [Open Company Summit](https://github.com/opencompany/www.opencompany.org/issues/142) | 0 | 800 | 800 | OCI + SF or Portland | 15 | [???](https://github.com/opencompany/www.opencompany.org/issues/151) | Probably SF or Portland |

**Comment by whit537** [comment]
There's some cost estimates for the six events on the radar.

> I don't think that it's possible to estimate the 'expected return' for each event.

I think you're right. There's such a huge element of serendipity in any event like these. Who knows who we'll meet where that just really gets what we're doing?

**Comment by whit537** [comment]
My estimates could be firmed up. They're ballparks based on past travel I've done. We only have about $3,700 in the bank, and we're not really saving up any money right now. My estimates above tally to $6,400, so clearly we need to make some decisions, because even if we're able to buckle down and only spend half of my estimates, that'd be $3,200 and we don't want to spend that much of our cash.

Jubilee is free to Gratipay and is coming up in a few days, so it's probably just noise to even have it on the list. Let's consider only the other five (noting that there could be other events we're not even aware of, but we're at the point where we need to decide about these ones). Here's how I would rank them in terms of what I am most interested in going to:

 1. **OuiShareFest**&mdash;This represents a new community for Gratipay, and it's one where I *think* we'll play well. It's really expensive, however, mostly because of the plane ticket. But I'd get to visit @Changaco to boot, which ain't nothing. Ideally we'd land some version of gratipay/gratipay.com#126 first.
 1. **OCI**&mdash;I think we still have people in SF who like us; they just can't say so on Twitter anymore. I'm interested to test this hypothesis by going out there. OCI is a convenient excuse, if that in fact comes together. Even if it doesn't I still might want to make a trip out later this year.
 1. **PyCon**&mdash;The decision we make here will be personally meaningful to me because I have a lot of friends in the Python community. I have no idea to what extent Gratipay still has any support left here and whether it's worth trying to cling to it.
 1. **#Cinderblocks**&mdash;This is outside the box for us. Could be gold, could be a dud. No way to know, but it's the cheapest option because it's close to Pittsburgh.
 1. **Libre Planet**&mdash;I'm kind of interested in visiting Boston, because I haven't been up there since launching Gratipay, but honestly I fall out more as a BSD/open guy than GPL/FSF. I'm not super-enthused about this one.

One of our conclusions at the [retreat](https://medium.com/gratipay-blog/at-our-second-retreat-we-met-our-third-users-5b473a2d1464) was that we wanted to build awareness and find new markets beyond open-source/tech by going to conferences and hanging out with non-nerds. Red dots!

![1-dphvmjkdmcidtju_1ntlog](https://cloud.githubusercontent.com/assets/134455/6223143/b1ebdeda-b62f-11e4-9e21-1c8d3dae2c24.jpeg)

That would point towards OuiShareFest and #Cinderblocks. PyCon, OCI, and Libre Planet are in our old open-source niche, where we're basically dead in the water. Participating in any of those feels to me like blowing on coals to see if there's any heat left.

We want to find the people who can't not work on the commons. Where are they?

**Comment by whit537** [comment]
I want to say that **Libre Fest** is out by process of elimination, but I can't quite bring myself to yet. It's moderately expensive for a relatively small crowd. However, it's surely full of people who can't not work on the commons, right? But is it too close to the tech diversity no fly zone?

I feel like there's a big decision between **OuiShareFest** and **PyCon**. I backed out of PyOhio due to a combination of controversy and finances. Am I going to do the same with PyCon? But even if we go to no other events, do we want to spend over half our money on sending me to OuiShareFest? That's a big risk.

I feel like I should go to **#Cinderblocks** because it's cheap and close and who knows? Of these five it best fits the non-nerds/new markets bill. It's not until summer so we've got some time on the cash flow.

I have no idea at this point if **OCI** is going to come together. If it does there's a [budget](https://gratipay.com/OpenCompany/members/) that I might be able to tap, and if it doesn't then maybe we save up over the summer for an SF trip next fall.

**Comment by whit537** [comment]
Proposed: **OutShareFest** and **#Cinderblocks**, and we'll deal with **OCI** when it firms up. No **Libre Fest** or **PyCon**, because we're looking for new markets and hanging out with non-nerds.

**Comment by Changaco** [comment]
Alternative: go to either **Libre Fest** or **PyCon** instead of **OuiShareFest**, because looking for new markets doesn't mean that you should abandon the original one, plus the total cost would be lower.

> **OuiShareFest**—This represents a new community for Gratipay

Yes and no, as you know some of them have already joined, e.g. https://gratipay.com/mbauwens/.

> But I'd get to visit @Changaco

You'd still have to actually come to me, or me to you, since I'm not in Paris.

**Comment by chrisdev** [comment]
No Chad at Pycon :disappointed:

**Comment by whit537** [comment]
> You'd still have to actually come to me, or me to you, since I'm not in Paris.

@Changaco How hard would it be to get to you? Few hours on a train? In the U.S. I'd probably rent a car.

> Yes and no, as you know some of them have already joined

It's encouraging that Michel has joined. I see that as an indication that we should pursue this community further.

**Comment by whit537** [comment]
> No Chad at Pycon :disappointed:

@chrisdev Well, @kaguillera did all right at PyOhio, I am sure you will do fine at PyCon, if in fact I don't end up going. :-(

**Comment by whit537** [comment]
Alternative: Go to **#Cinderblocks** and **OCI**, and skip the rest. Instead, save the money and keep building Gratipay.

**Comment by whit537** [comment]
At this point we're now losing money every week, and we should expect to need to pay lawyers for #122. I'm feeling like OuiShare is out of reach financially.

**Comment by whit537** [comment]
I have another commitment during PyCon, a big retirement party for my dad on Friday, April 10. PyCon booths run from Thursday night through Saturday afternoon, so there's really no way I can make it work.

@chrisdev Do you want to staff the booth by yourself, or should I cancel it? I'm fine either way. Want to have a call to discuss?

**Comment by whit537** [comment]
I'm adding #148 for consideration. Relatively cheap and would pick up on #142, which was tentatively successful.

**Comment by chrisdev** [comment]
I can try to staff the boot myself but I Wish I had the penny punch!!
However, I'm hoping that someone else from Gratipay will also turn up.
There is the possibility of room sharing thing which can reduce the cost of  attending PyCon.
I've already have made the hotel booking thinking that my wife wanted to come, however she thinks that Montreal is just be going to be too cold

**Comment by whit537** [comment]
We do have one free registration with the booth. Shall I ask if we can transfer that to you, @chrisdev?

**Comment by chrisdev** [comment]
The only thing is that i've registered already?
Do we have anyone in Montreal/Canada who can also go.
They can room with me

**Comment by whit537** [comment]
@chrisdev Let's move over to #111 ...

**Comment by whit537** [comment]
Decided against #145 and #114. PyCon is a go (#111). I'm expecting to go to #87, and SF at some point later this year. I want to visit [Sudoroom](https://gratipay.com/sudoroom/). Closing this ticket because I think the general question is answered: we can use some budget for events.
