### ISSUE TITLE
invite API client authors to house repos under Gratipay org?

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#140]
They'd still keep perms. This worked well for https://github.com/badges, and in Gratipay-land we do have a precedent in https://github.com/gratipay/grtp.co and https://github.com/gratipay/gratipay-badge.

API implementations: https://github.com/gratipay/gratipay.com#api-implementations

Any objections to extending the invitation?

**Comment by rummik** [comment]
@whit537 Don't forget https://github.com/gratipay/gratipay-everywhere, another project that was brought under the org

**Comment by webmaven** [comment]
:+1:

**Comment by whit537** [comment]
Seeing no objections, I think it's safe to do this ... once we regain enough momentum to actually see third-party clients again. :-)
