### ISSUE TITLE
go to Jubilee Professional

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#142]
http://professional.jubileeconference.com/

Some friends of mine run it. I went a few years ago.

**Comment by whit537** [comment]
I managed to swing a free ticket, so I'm planning to be there (it's this Friday).

**Comment by clone1018** [comment]
Don't forget to practice your elevator pitch.

**Comment by whit537** [comment]
"Gratipay is a platform for crowdfunding the commons. You know how on Wikipedia they have that 'donate to us' thing at the top? We provide that for everyone else. For example, my friend Felicia here runs a website called Ambridge Connection, and we're working with her to fund her website on Gratipay."

How's that?

**Comment by whit537** [comment]
I want to get people actually signed up and giving. Like, on their phone while we're standing there. The "Who inspires you?" angle is probably stronger for that. The only problem is that our mobile experience sucks and so does our Facebook friend-finding experience. :-(

It's been instructive to onboard people onto GitHub as part of http://www.ambridgeboro.org/index.asp?Type=B_BASIC&SEC={664BA0C4-2F8F-43B4-A42B-F118C8DF7B81}&DE={662B9E1E-AB4F-43C0-BF77-97A18507F235}. GitHub is pretty good though even they have some rough edges. We are a far cry from pretty good. I feel like if I take the "Who inspires you?" tack then I'm going to end up just embarrassing myself. :-(

**Comment by whit537** [comment]
*sigh*

**Comment by whit537** [comment]
> Stripe is one of the most successful startups we've funded, and the problem they solved was an urgent one. If anyone could have sat back and waited for users, it was Stripe. But in fact they're famous within YC for aggressive early user acquisition.
> 
Startups building things for other startups have a big pool of potential users in the other companies we've funded, and none took better advantage of it than Stripe. At YC we use the term "Collison installation" for the technique they invented. More diffident founders ask "Will you try our beta?" and if the answer is yes, they say "Great, we'll send you a link." But the Collison brothers weren't going to wait. When anyone agreed to try Stripe they'd say "Right then, give me your laptop" and set them up on the spot.

http://paulgraham.com/ds.html

**Comment by whit537** [comment]
Done.

https://twitter.com/whit537/status/570680521862324224
https://twitter.com/whit537/status/570680694487310338
https://twitter.com/whit537/status/570681059966394368
