### ISSUE TITLE
join the Open Innovation Network?

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#143]
Received in private email:

> Hello there Open Innovation fan!
> 
> My name is Shane Coughlan and I am from Open Invention Network (OIN). We are a community organisation that helps protect Linux-related technology from patent tension. I want to talk about working together.
> 
> OIN has a community of over 1,250 projects and companies that pledge never to use patents aggressively over Linux System technology. It is extremely diverse, ranging from companies like Google, Dropbox, Verizon, Red Hat and LG Electronics to projects like CentOS, Gentoo, KDE and OpenStack. Everyone makes the same patent non-aggression pledge. This makes it clear that no matter how big or small the project or company, we all agree that there should be no patent conflict around Linux and related technology.
> 
> Our goal is to create a non-aggression “standard of behaviour” and we have come a long way towards accomplishing that. This is now the largest community in the world to address patent challenges. We would like your help to go even further. We want your project to support patent non-aggression and make this important principle even stronger.
> 
> Our community is free, lowers risk for everyone and it only takes three minutes to complete our non-aggression pledge online:
> http://www.openinventionnetwork.com/joining-oin/license-agreement/
> 
> Please help us push patent aggression out of Open Source. Whether you see this as a contribution to software freedom or pragmatic method of risk reduction, your support is deeply appreciated. It would be fantastic if you could be a part of our community.
> 
> Regards
> 
> Shane
> 
> Micro FAQ:
> 
> Q: How did you find me?
> A: I browsed GitHub looking for interesting projects. Part of my job is to make sure we have lots of projects as well as companies in the OIN community. We want to ensure that everyone can benefit from Linux patent non-aggression.
> 
> Q: What do you mean by “Linux”?
> A: We mean something we call the “Linux System”, which is the Linux kernel plus 2,200 other software packages. The full list of current packages is here:
> http://www.openinventionnetwork.com/joining-oin/linux-system/linux-system-table/?cat_id=7&type=table
> 
> Q: Why don’t you just protect all Open Source from patent aggression?
> A: We use a patent license to make the non-aggression pledge “real.” This is similar but different to the way the GNU GPL license makes Linux kernel distribution terms “real.” The patent license needs to be specific about what is covered, so we make a list of software packages.
> 
> Q: What about software packages not in the Linux System?
> A: We update the Linux System about once a year and add new packages each time.
> 
> Q: What’s the catch?
> A: If you make this pledge, you can’t use patents against the Linux System.
> 
> Q: What now?
> A: Please go here and pledge your support for patent non-aggression:
> http://www.openinventionnetwork.com/joining-oin/license-agreement/
> ## 
> 
> Shane Coughlan
> Global Director of Licensing
> Open Invention Network

**Comment by whit537** [comment]
> Greetings from Takamatsu, Japan! I sent you a mail a few weeks ago about the OIN community of Linux patent non-aggression. I wanted to check in and make sure you received it.
> 
As I said in my first mail, OIN has a community of over a thousand projects and companies (we have over 1,300 participants now). Everyone in this community pledges support of patent non-aggression around Linux System technology. We would like you to do this too. Even if you have no patents, your voice in support of non-aggression supports our mission.
> 
Pledging non-aggression over the Linux System takes just two minutes online and costs nothing:
https://www.openinventionnetwork.com/joining-oin/join-now/
> 
I hope your project can participate in our community. You would be joining projects like CentOS, Mozilla and OpenStack and companies like Red Hat, Twitter and Google in promoting the idea of a non-aggression “standard of behaviour” for Open Source. It does not matter how big or small you are. Your support means a lot.
> 
I am happy to answer any questions and to explain in more detail why our pledge of Linux patent non-aggression is so important for Open Innovation.
> 
Regards

**Comment by whit537** [comment]
I'm inclined to go ahead and sign us up. Any objections?

**Comment by colindean** [comment]
I'm not sure of its value to Gratipay, or Gratipay's value to it. Gratipay doesn't seem to be affected by Linux patent non-aggression.

I guess it's free marketing at least.

**Comment by whit537** [comment]
Here's the actual license agreement: http://www.openinventionnetwork.com/joining-oin/oin-license-agreement/.

**Comment by whit537** [comment]
Here's their Wikipedia page: http://en.wikipedia.org/wiki/Open_Invention_Network.

**Comment by whit537** [comment]
Seems legit but I want to understand it better before joining.
