### ISSUE TITLE
extended validation

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#144]
We need to go through a verification flow again with StartSSL post-#73 (pressing because of https://github.com/gratipay/gratipay.com/issues/3160). Let's go ahead and get extended validation! That will give us a nice big green `Gratipay, LLC` in the address bar:

![screen shot 2015-02-13 at 4 42 20 pm](https://cloud.githubusercontent.com/assets/134455/6195780/4ee22a3e-b39f-11e4-9dc9-51c2ca8e2f56.png)

**Comment by whit537** [comment]
>Thank you for your Extended Validation request. In order to proceed with it we need some additional documents from you:
>
  1. A signed acknowledgment of the StartCom Extended Validation Subscriber Agreement. You can find it here
     https://www.startssl.com/extended-validation-application-request-en.pdf
  2. A lawyer’s opinion letter completed by your internal or external legal counsel (lawyer/Attorney/Notary).
  3. Company bank accounts.
  4. A scanned copy of your credit card (front only).
>
Thank you in advance.

**Comment by whit537** [comment]
They're asking for a voided check for the company bank account. We don't have checks. We can get them free from Ally, it'll take 10 days and I'm not sure they'll have the name Gratipay on them.

**Comment by whit537** [comment]
I have the opinion letter from a notary, hopefully it's sufficient. I'll scan and upload it next chance I get, along with the credit card.

**Comment by whit537** [comment]
Opinion letter uploaded. Credit card uploaded, too, but as with the bank account it has my name on it and not Gratipay's, so I'm not sure they'll accept it.

**Comment by whit537** [comment]
Okay! The plot thickens like pea soup :ramen:. I just called Ally to ask about changing the name on the account from `Chad Whitacre` to `Gratipay, LLC`, aaaaaand it turns out they don't offer business accounts, only personal accounts(!). I guess we're going to have to set up a different account at a new bank before proceeding. :-/

Reticketed as #149.

**Comment by benhc123** [comment]
All for a new SSL certificate!

**Comment by captn3m0** [comment]
EV certificates are not really worth the trouble, imo.

>We did not find that extended validation provided a significant advantage in
identifying the phishing attacks tested in this study. [...]

- [citation](http://www.adambarth.com/papers/2007/jackson-simon-tan-barth.pdf)

**Comment by whit537** [comment]
Interesting. Eight years old, though. Anything more recent, now that EV has been out for a while?

**Comment by captn3m0** [comment]
- [Interesting HN Thread](https://news.ycombinator.com/item?id=8344238)
- [EV certs don't work](https://www.blackhat.com/presentations/bh-usa-09/SOTIROV/BHUSA09-Sotirov-AttackExtSSL-SLIDES.pdf) - Basically says EV = non EV

There are some startups on the HN thread offering cheap EV certs. You might wanna compare prices.

**Comment by chrisdev** [comment]
I think EV is more of a branding/confidence thing. You have to look at the sites in your niche and see if they are using EV certs. So i've noticed that Patreon and Kickstarter don't use EVs. But Chase, BOA, ALLY use them.

BTW I get my certs from namecheap. But i'm going to try startssl for my next project.

**Comment by captn3m0** [comment]
For cheap SSL, I'm currently using CloudFlare free SSL plan on my personal projects.

**Comment by whit537** [comment]
We already have a cert vendor, StartSSL.

Twitter: Yes. Facebook, Google+: No.

**Comment by whit537** [comment]
The notary I used as a notary public, not a latin notary(!), so StartSSL wouldn't count their opinion of us. Given that and @captn3m0's input, I went ahead and called off the extended validation process. Unless @chrisdev wants to champion EV for Gratipay, I'm inclined to close this as wont-fix.

**Comment by colindean** [comment]
I'm not convinced of the value of EV for Gratipay at this time, per [this security.SE answer](https://security.stackexchange.com/questions/15865/what-are-the-advantages-of-ev-certificate).
