### ISSUE TITLE
Simplify information architecture of Inside Gratipay

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/inside.gratipay.com#146]
Current state: 

| The Big Picture | How To | Appendices |
| --- | --- | --- |
| Welcome to Gratipay | Advocate for users | Application Health |
| Mission | Behave well | Calendar |
| Brand Guidelines | Build Gratipay | Chat |
| Audience | Configure a Bank Account | Colophon |
| Product Overview | Configure Paypal | Communication Channels |
| System Architecture | Deal With Bad Behavior | Finances |
| Source Code | Format Source Code | See Also |
|  | Handle Security Issues | Survey |
|  | Handle Terms Violations | Who Has Access to What |
|  | Label GitHub Issues |  |
|  | Manage Queues |  |
|  | Onboard Yourself |  |
|  | Respond to Haters |  |
|  | Review Accounts |  |
|  | Run a Script |  |
|  | Run MassPay |  |
|  | Run Payday |  |
|  | Shuffle Escrow |  |
|  | Support Users |  |
|  | Tell People about Gratipay |  |
|  | Train New Contributors |  |
|  | Translate Gratipay |  |

To simplify this, I'm thinking of grouping the how-tos into 3 different categories - **Development** related, **Admin** related and **General**. 

| General Guides | Development Guides | Admin Guides |
| --- | --- | --- |
| Advocate for users | Build Gratipay | Configure a Bank Account |
| Behave Well | Format Source Code | Configure Paypal |
| Deal with Bad Behaviour | System Architecture | Handle Security Issues |
| Label GitHub issues | Source Code | Handle Terms Violations |
| Manage Queues | Run a Script | Review Accounts |
| Onboard Yourself |  | Run MassPay |
| Respond to Haters |  | Run PayDay |
| Tell People about Gratipay |  | Shuffle Escrow |
| Train New Contributors |  | Support Users |
| Translate Gratipay |  |  |

**Comment by whit537** [comment]
Can you stop by IRC? :)

**Comment by rohitpaulk** [comment]
@whit537 - I wish I could. I left a comment somewhere on Freshdesk that I thought you'd see - ISP problems, so no IRC, SSH etc for about 2 weeks.

**Comment by whit537** [comment]
@rohitpaulk Gotcha, did see the comment. Didn't stick that IRC was affected. :-(

See you in a bit! :-)

**Comment by whit537** [comment]
To the matter at hand: I agree that the Howto section is starting to get unwieldy. I suggest that we list only six or eight of them on the homepage and link to `/howto/` for the rest. Possible ways to decide which we list on the homepage:

 1. manual curation
 1. popularity (page views?)
 1. user-specific favoriting (requires auth infrastructure unless we go with localstorage)

Tagging them is also a fine idea (we could implement (1) with a "featured" tag) but I think fundamentally we want to trim the list on the homepage.

**Comment by rohitpaulk** [comment]
A thought: The number of articles look like a lot when they're presented **all at once** to the user. What if we showed an expanded/collapsed view like Twitter does: 

![screenshot from 2015-02-16 22 52 15](https://cloud.githubusercontent.com/assets/3893573/6216295/ae358080-b62e-11e4-923e-ec2843bdb08f.png)

**Comment by whit537** [comment]
@rohitpaulk That's a possibility, but that requires imposing a strict hierarchy on HOWTO, which I'm not sold on. I envision over time that we'll end up with quite a few HOWTOs. I don't think that imposing a hierarchy on them is the best way to organize them. I think non-hierarchical tagging and search make more sense.

**Comment by rohitpaulk** [comment]
> I think non-hierarchical tagging and search make more sense.

+1 on search. I don't see why a hierarchical organization is bad though. (As long as we have a 'general'/miscellaneous category for stuff that doesn't belong to a specific group)

> I envision over time that we'll end up with quite a few HOWTOs

Definitely. I think that every how-to will fall under one of the following groups: 
- Development
- Design
- Finance
- Admin
- General

One more example that might be closer to our use case than twitter's API docs: 

![screenshot from 2015-02-16 23 23 58](https://cloud.githubusercontent.com/assets/3893573/6216803/547f4936-b633-11e4-82d1-5006ab1ef8fb.png)

@whit537 - Can you think of an example similar to ours in which 'non-hierarchical tagging' works well?

I see non-hierarchical tagging as something you'd use when you have to curate content generated by users - like Medium does. When we're in charge of content and how we present it, isn't it cleaner if we enforce logical grouping?

**Comment by whit537** [comment]
Okay, I'm fine giving a hierarchical ordering a try. :-)

**Comment by rohitpaulk** [comment]
Great :)
