### ISSUE TITLE
switch to libre fonts

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#147]
Reticketed from https://github.com/gratipay/gratipay.com/issues/707#issuecomment-74351053:

> I seems the Gratipay logotype is made with a proprietary font, http://www.myfonts.com/fonts/mti/mundo-sans/std-bold/
> 
> I'd like to suggest using a libre font :)

**Comment by whit537** [comment]
Ftr, we're using [Ideal Sans](http://www.typography.com/fonts/ideal-sans/overview/).

**Comment by colindean** [comment]
Maybe @brareme would be up for searching for something that looks similar, if we want to go down this route?

**Comment by whit537** [comment]
http://open-foundry.com/
