### ISSUE TITLE
go to Center for Human Flourishing launch

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#148]
https://www.tkc.edu/news/king%E2%80%99s-announces-launch-center-human-flourishing

**Comment by whit537** [comment]
I met some of these folks at Jubilee Pro (#142). I think there could be some interest here in the work we're doing, and tickets were free so I went ahead and registered one. I can probably find a friend to stay with in New York and bus fare is cheap.

**Comment by kaguillera** [comment]
+1

**Comment by whit537** [comment]
I've decided not to go. After [talking with Scott](https://botbot.me/freenode/gratipay/2015-03-02/?msg=33172608&page=1) yesterday, I think we need to focus on entrepreneurs by partnering with incubators and accelerators. A trip to NYC may still be in order but I'm not going to rush it this weekend, because this event is not going to be entrepreneur-dense.
