### ISSUE TITLE
switch to a new bank

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#149]
Ally only offers personal accounts, and we really should have a business account. Precipitated by #144.

**Comment by whit537** [comment]
I looked at [PNC](https://www.pnc.com/en/small-business/banking/business-checking-overview.html) and [Citizens](https://www.citizensbank.com/small-business/) because they have local branches. PNC has an online application but Citizens doesn't. I have my main personal account at Citizens, so I'm familiar with it.

**Comment by whit537** [comment]
Citizens closes in 7 minutes, so I'll stop by tomorrow.

**Comment by whit537** [comment]
I opened an account at Citizens, though I need to stop by Monday with some additional paperwork.

 - [ ] move a chunk of money over there
 - [ ] update payment details at all vendors
 - [ ] close the Ally account

**Comment by whit537** [comment]
I've set up online banking for our Citizens account. It'll take a couple days to verify the Ally account, and then we can transfer money over.

**Comment by whit537** [comment]
I verified our Ally account at Citizen and initiated a transfer for $2,500.00. That'll land on the 12th (three days) and will leave $1,143.04 at Ally.

**Comment by whit537** [comment]
I updated our account at Gratipay so that future funds will go to Citizens instead of Ally. Now for vendors ...

**Comment by whit537** [comment]
From [finances](http://inside.gratipay.com/appendices/finances):

- [ ] Heroku
- [ ] Travis	
- [ ] Freshdesk
- [ ] PagerDuty
- [ ] iWantMyName
- [ ] GitHub
- [ ] Sentry
- [ ] Transifex
- [ ] StartSSL
- [ ] Typography.com
- [ ] DigitalOcean
- [ ] MaxCDN
- [ ] Librato
- [ ] Coveralls.io
- [ ] LastPass
- [ ] DNSimple

**Comment by whit537** [comment]
Are we actually using coveralls? I’m logging in to update billing, and they’re asking me for a new permission: “Commit statuses: Read and write access.” I don't want to give them that.

**Comment by whit537** [comment]
StartSSL won't remove our current credit card because we used it recently. Turkeys.

**Comment by whit537** [comment]
Payouts confirmed going to new account.

**Comment by whit537** [comment]
Last call on Coveralls before I cancel it ...

**Comment by clone1018** [comment]
Kill it

**Comment by whit537** [comment]
I signed into Coveralls and don't see any invoices. I also can't find any Coveralls charges in Ally. I've deleted my Coveralls account. Case closed.

**Comment by whit537** [comment]
Erm. Ahem. Right.

**Comment by whit537** [comment]
Three more tasks on https://github.com/gratipay/inside.gratipay.com/issues/149#issuecomment-76480774. :blush:

**Comment by whit537** [comment]
Nothing has hit Ally for 49 days.

**Comment by whit537** [comment]
I'm not sure what the relationship is between our savings (escrow cold storage) account at Ally and our checking account there.

**Comment by whit537** [comment]
It looks like with gratipay/gratipay.com#67 we're going to end up trying to use a Citizens account for our escrow, with card charges settling there via Braintree and ACH originating from there if we can (https://github.com/gratipay/gratipay.com/issues/3366). We should set up an escrow account at Citizens, then move Ally escrow to Citizens escrow, then move Ally operations to Citizens operations. Then we can close Ally.

**Comment by whit537** [comment]
We need the rest of the money from Ally in order to get started with a lawyer (#193). I went ahead and called Ally and asked them to close our two accounts there, sending the operations funds to Citizens and the escrow to New Alliance. We earned interest on the escrow funds so we need to keep track of that; for now it's enough to make sure that we have transaction history as of the account close date. I'm told we'll still have access to transaction history on Ally once the accounts are closed (there'll be a final prorated interest payment that we'll want to know about). I'll also make sure we have our statements in https://github.com/gratipay/logs.

**Comment by whit537** [comment]
Statements uploaded in https://github.com/gratipay/logs/commit/80620c4e6260a3488cda150c586fe59cd51f9935.

**Comment by whit537** [comment]
Notification from Ally that the account is closed: https://gratipay.freshdesk.com/helpdesk/tickets/2051.

**Comment by whit537** [comment]
Blech. Transaction is still available, but it looks like the operations balance may have been sent to the wrong place. :-( The last four of the account number match our Citizens operations account, but perhaps the routing number is wrong because it shows `NEW ALLIANCE FCU DDA` (whereas the other shows `NEW ALLIANCE FCU SAV`).

> Account Closed - Apr 30, 2015
Details for this account will be available online for 60 days from the closed date.

**Comment by whit537** [comment]
I'm on hold with Ally. She's calling over to operations to determine whether the funds were sent to the wrong place or whether it's simply a matter of the name on the transaction being wrong.

**Comment by whit537** [comment]
Yikes. Okay! They screwed up. They sent the money to the wrong place. They're pulling it back (3 to 5 business days) and then we have to call back and initiate another transfer to the right place, which they do have on file.

![bankerr](https://cloud.githubusercontent.com/assets/134455/7430518/6d2d6b5a-efe2-11e4-8aed-d729c68c8ac4.jpg)

**Comment by whit537** [comment]
Reversal hasn't posted in Ally yet.

**Comment by whit537** [comment]
We're down to $193 in Citizens after paying on #193. Heh. 193 get! :-)

![screen shot 2015-05-04 at 1 27 45 pm](https://cloud.githubusercontent.com/assets/134455/7458315/6ca7fd0e-f261-11e4-982e-14f57e3935a2.png)

**Comment by whit537** [comment]
Money is back in Ally. I called Ally and reinitiated the account closure, with the remaining balance going to Citizens.

**Comment by whit537** [comment]
The $1,003.18 is out of Ally but not yet landed in Citizens, and we're down to $131.12 there. However, we've received [an email](https://gratipay.freshdesk.com/helpdesk/tickets/2111) that our Citizens account "has been enabled for **Transfer Funds** service," which gives me some solace. "This service enables you to complete transfers between accounts by the next business day." Hopefully that means they also initiated the transfer today, to land on Monday? I believe our next major bill is Heroku for $90 on Monday. We can cover that without the Ally transfer, but the next bill to hit is Piwik on Wednesday for $65 and we won't have enough for that without the transfer. :four_leaf_clover:

**Comment by dylmye** [comment]
I've found that if you ask Heroku support nicely they'll give you up to a week extension, or 24 hours if the payment bounces. You could use this to pay Piwik. (or use a free alternative?) 
</lurker>

**Comment by whit537** [comment]
Thanks @dylmye ... prompted by your comment I just checked again, and thankfully the $1,003.18 has landed! :dancer: :dollar: :money_with_wings: :moneybag: 

Let's keep those ideas in mind for next time&mdash;hoping there isn't one! :-)
