### ISSUE TITLE
trust verified emails for support?

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#150]
Our habit when fielding support requests has been to ask for the first eight digits of the user's API key from their Gratipay account page as a security confirmation. Now that we have verified emails (https://github.com/gratipay/gratipay.com/pull/2752), are we willing to rely on that to ensure the identity of support requests? What about email spoofing?

**Comment by whit537** [comment]
Question arose here: https://gratipay.freshdesk.com/helpdesk/tickets/1730.

**Comment by whit537** [comment]
http://en.wikipedia.org/wiki/Email_spoofing

**Comment by whit537** [comment]
http://en.wikipedia.org/wiki/Email_authentication

**Comment by whit537** [comment]
I can't find that Freshdesk exposes SPF/DKIM information in their UI. I've submitted a support request to them to ask about this.

**Comment by whit537** [comment]
I decided to trust the email in question on [FD1730](https://gratipay.freshdesk.com/helpdesk/tickets/1730), because it was coming from Gmail, and when I checked in Gmail (which underlies Freshdesk for us) it looked fine. Leaving this open to establish a general policy.

**Comment by whit537** [comment]
> Does Freshdesk expose a message's SPF or DKIM information anywhere in the UI?

And ...

> I'm afraid to say that we don't expose the message SPF or DKIM info in the UI.

**Comment by whit537** [comment]
I think that, without a way to verify email identity easily from within Freshdesk, we should treat verification via email as an ad-hoc process we utilize for cases such as FD1730, but don't generally rely on.

**Comment by whit537** [comment]
Objections?

**Comment by rohitpaulk** [comment]
> I think that, without a way to verify email identity easily from within Freshdesk, we should treat verification via email as an ad-hoc process we utilize for cases such as FD1730, but don't generally rely on.

+1

**Comment by whit537** [comment]
Hearing none ...
