### ISSUE TITLE
up our support game

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#152]
Let's talk about support! There are four of us participating regularly on Freshdesk now: myself, @rohitpaulk @benhc123 @Changaco. Can we get on the same page about what constitutes an excellent support experience?

This conversation is precipitated by [FD1730](https://gratipay.freshdesk.com/helpdesk/tickets/1730):

> **close account**
>
I have $4.64 on my account
>
> Your UI/UX is so confusing I don't want to deal with it anymore and I certainly won't use it ever again.
>
Distribute the funds to classes for your programmers to take UX classes, because frankly, the UX sucks. Nice idea though, just terrible implementation.

To which @benhc123 responded:

> We'll happily take the $4.64 on your account and put it into the Gratipay team funds which will indirectly go to our programmers and their continued development of the user experience.

I responded in a private note:

> I'm frustrated at you for responding to this request in the way that you did. I'll explain why later, but for now, please don't respond to any more support requests. Thanks.

Aaaaaaaaand that brings us to this ticket. :-)

**Comment by whit537** [comment]
The first reason I was frustrated at your response, @benhc123, is that you made a false promise: we don't have the ability to take over user funds and close their accounts without directly manipulating the database. For a really upset user like this one, we may indeed decide to manually manipulate the database in order to fulfill their request. But that's not something you have permission to do, which means that @rohitpaulk @Changaco or I would have had to complete this request. It's good that you responded quickly, but at the very least you should've left a private note for the rest of us, something along these lines:

> I don't have access to fulfill this request, but given that it's the weekend and the user is really upset I thought it best for me to reply promptly.

The second reason I was frustrated with your response is that you didn't verify the user's identity before making promises about what we would do. Usually we do this by asking for their username and the first eight digits of the API key from their Gratipay account page. Any other means of verifying the user's identity should, again, have been documented on the ticket in a private note, something like:

> Here's the user's account: [blah]. I found it by searching based on [blah]. Their email is verified so I think we should trust their identity without further confirmation.

I'm not sure you had enough access to even determine the user's account, though. And since the user was so upset, it *was* probably best not to ask them to sign back into Gratipay to find their API key.

For this particular case, I would have greatly appreciated a response from you along these lines:

> Thanks for getting in touch and sorry for the frustration. :-(
>
> I don't have the authority to fulfill your request myself, but I'll follow up with those who do when they're back around on Monday.

Zooming out, the general reason I'm frustrated with you is that you are confusing users because you don't appear to have properly digested [our documented guidelines for support](http://inside.gratipay.com/howto/support-users).

 - On [FD](https://gratipay.freshdesk.com/helpdesk/tickets/1676), you confused the user by asking whether to close a ticket, and linking them to the Freshdesk web app. Both of these are documented no-nos.
 - On [FD1695](https://gratipay.freshdesk.com/helpdesk/tickets/1695), you confused the user by not linking to their Gratipay account page; it's documented that you *should* link there. You also linked to the Freshdesk web app again.

That's the wider context in which I experienced your response on [FD1730](https://gratipay.freshdesk.com/helpdesk/tickets/1730). From my point of view, you now have a history of confusing our users, because you're not observing our documented guidelines for support. You're also not communicating sufficiently with the rest of us via private notes (I didn't receive an acknowledgement from you on [FD1676](https://gratipay.freshdesk.com/helpdesk/tickets/1676), nor on [FD1730](https://gratipay.freshdesk.com/helpdesk/tickets/1730)). I propose that you don't post any further support responses without having @rohitpaulk @Changaco or I review your response first. We can use private notes and IRC for this.

Q1: Am I off base or being unfair here?

Q2: Are we agreed on reviewing @benhc123's support responses?

Q3: What changes (if any) do we need to make to [Support Users](http://inside.gratipay.com/howto/support-users)?

**Comment by rohitpaulk** [comment]
> I propose that you don't post any further support responses without having @rohitpaulk @Changaco or I review your response first. We can use private notes and IRC for this.

I think that's overkill, if @benhc123 has read this ticket - it's highly unlikely that he's going to make any of these mistakes again :)

> What changes (if any) do we need to make to Support Users?

We haven't mentioned much about private notes there - other than that, I think the information is sufficient.

**Comment by benhc123** [comment]
Hi Guys,

Sorry about this. I guess I was partly annoyed at this user for making a complaint which contained: "Distribute the funds to classes for your programmers to take UX classes, because frankly, the UX sucks." but I understand that's no excuse for giving awful support especially as in his own special way, this user was trying to give feedback.

@whit537, this won't happen again. I am familiarising myself with the support guide and will make sure I don't repeat this mistake.

Apologies again.

**Comment by benhc123** [comment]
I'm fine with my support responses being reviewed.

**Comment by whit537** [comment]
[IRC](https://botbot.me/freenode/gratipay/2015-03-09/?msg=33716180&page=1)

**Comment by whit537** [comment]
> We haven't mentioned much about private notes there

Done in https://github.com/gratipay/inside.gratipay.com/commit/3de339cf0fca182b89aedbcd02fc79aec1931b4b.

> it's highly unlikely that he's going to make any of these mistakes again

I just went back and checked: @benhc123 included the Freshdesk URL in both [FD1676](https://gratipay.freshdesk.com/helpdesk/tickets/1676) and in [FD1695](https://gratipay.freshdesk.com/helpdesk/tickets/1695), but he sent both of those replies before my response to him on 1676. So hopefully you're right, @rohitpaulk. :)

> Sorry about this. [...] I am familiarising myself with the support guide and will make sure I don't repeat this mistake.

Thanks. Let's provide the best support experience we can! :-)

> I'm fine with my support responses being reviewed.

Cool. I'll feel more comfortable if we can do this for two or three support cycles. Thanks. :-)
