### ISSUE TITLE
bring back #gittip logs

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#153]
Currently https://botbot.me/freenode/gittip/ redirects to https://botbot.me/freenode/gratipay/, which means that we've lost the logs from #gittip ([IRC](https://botbot.me/freenode/gratipay/2015-03-10/?msg=33806643&page=1)). Word from @mtrythall in [IRC](https://botbot.me/freenode/lincolnloop/2015-03-10/?msg=33827868&page=1) (w/ pm follow-up) is that this was an intentional change in response to a support request from @rohitpaulk on Feb 21:

> Hey!
>
I'm a Gratipay dev, and recently noticed that our previous channel logs (https://botbot.me/freenode/gittip/) now results in a 404. We have a lot of open tickets on GitHub that rely on references to conversations in that channel for context.
>
Can you please being https://botbot.me/freenode/gittip/ back up?

My recollection is that I confused us by searching for something in Gratipay botbot logs and discovering they only went back through August, 2014. Looks like that [happened on Feb 5](https://botbot.me/freenode/lincolnloop/2015-02-05/?msg=31335932&page=1).

@rohitpaulk Can you give us some insight on what you were seeing? I think what we want is what we had: both https://botbot.me/freenode/gittip/ and https://botbot.me/freenode/gratipay/.

**Comment by rohitpaulk** [comment]
Before I sent that email, https://botbot.me/freenode/gittip/ and all links to it were resulting in 404s. 

I asked for exactly what you did, to have the old page restored. I got a reply saying that this was fixed, but it was just redirected. I did send them an email once again on 26th Feb mentioning that redirection isn't what we want, and that it doesn't solve our problem - haven't received a reply yet.

> Hi Michael, 

> botbot.me/freenode/gittip is now redirected to botbot.me/freenode/gratipay :) The previous links still don't work though, here's an example - 

> https://botbot.me/freenode/gittip/msg/6893124/

**Comment by whit537** [comment]
@rohitpaulk Okay, thanks for being proactive. Did you document your interactions with Lincolnloop? Is there another ticket I missed, or an IRC reference?

**Comment by rohitpaulk** [comment]
> Did you document your interactions with Lincolnloop?

@whit537 - I really don't know why I didn't, I should have. :) I guess this was when IRC wasn't working for me. Could've opened a ticket though - won't happen again.

**Comment by whit537** [comment]
@rohitpaulk No worries, just wondered if I had missed it. :-)

!m @rohitpaulk

**Comment by whit537** [comment]
I just got bit by this, clicking the IRC link at https://github.com/gratipay/gratipay.com/issues/1583#issuecomment-26160262.

**Comment by rohitpaulk** [comment]
Looks like we're back to a [404](https://botbot.me/freenode/gittip/).

**Comment by whit537** [comment]
cc: @ipmb

**Comment by ipmb** [comment]
Discussing it here https://github.com/BotBotMe/botbot-web/issues/135. I'll try to push something through this week.

**Comment by whit537** [comment]
Thanks @ipmb! :-)

**Comment by ipmb** [comment]
Merged the gittip logs into gratipay and put a redirect in place so the old links work.

**Comment by rohitpaulk** [comment]
!m @ipmb

**Comment by whit537** [comment]
Thanks @ipmb! :-)
