### ISSUE TITLE
set up an office

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#155]
Transpay compliance rejected us in part, "due to multiple companies located at same home address" (https://github.com/gratipay/gratipay.com/issues/417#issuecomment-78266767).

**Comment by colindean** [comment]
Probably appropriate to consider a coworking space. 

I know you're pretty adamant about staying in Ambridge. Is there a coworking space there?

If you just need a mailbox and desk, I'll bet that one or more of the coworking spaces in Pittsburgh might fill that need for you. @metamesh uses [The Hardware Store](http://www.workhardpgh.com) run by [Josh Lucas](https://twitter.com/sixfloors) in Allentown.

**Comment by whit537** [comment]
I would love to buy a building in downtown [Ambridge](https://medium.com/gratipay-blog/meet-ambridge-8b9b2b6f8628). We could have a lot of fun making the first floor a pay-what-you-want restaurant. :dancer:

**Comment by clone1018** [comment]
@whit537 A building or THE building :D

**Comment by whit537** [comment]
@clone1018 Highly unlikely it will be THE building. It's off the market right now and I doubt we'll be able to afford it anytime soon anyway. :-(

I think we should start with something smaller in the 500 or 600 block of Merchant.

**Comment by whit537** [comment]
Okay! Our new address (starting in May) is:

Gratipay, LLC
651 Merchant Street
Suite B
Ambridge, PA 15003
USA

$50/mo for a desk in the basement. :-)

**Comment by whit537** [comment]
Keeping open through May when we actually start there.

**Comment by clone1018** [comment]
!m @whit537

**Comment by techtonik** [comment]
!m @whit537 

$50/m for a desk in the basement is a cool price. I guess that's $25 for square meter? =)

**Comment by techtonik** [comment]
:camera: :european_post_office: :rice_scene:

**Comment by whit537** [comment]
I backed out of the basement office when the Gratipocalypse hit. Closing.
