### ISSUE TITLE
Dashboard for metrics

### ISSUE THREAD

**Issue by captn3m0** [gratipay/inside.gratipay.com#157]
At @SDSLabs, I've worked on a publicly visible dashboard that lets us monitor metrics for various apps. Its not available online, so here's a screenshot: 

![screenshot from 2015-03-15 17 58 39](https://cloud.githubusercontent.com/assets/584253/6655960/e608ae4c-cb3c-11e4-8f07-1420dff020f1.png)

Its based on shopify/dashing, which is a ruby+sinatra based framework for building dashboards. We track all sorts of metrics, including facebook likes (which is useless) to number of people watching our live stream, which helps us a lot.

Since I've worked on this before, I'd be willing to do this for gratipay as well. Would something like this be useful? If yes, let me know what metrics you'd like to track. Metrics should be aggregate preferably as that leaves less scope for privacy leaks.

A few suggestions:

- Commit counts
- Issues closed/open in freshdesk
- Visitor count?
- Money transfered via gratipay (perhaps even across categories such as CC/paypal/bitcoin)
- More analytics metrics such as bounce rates

Some of these would require API endpoints in the main app, and some would require integrations with github etc.

**Comment by Changaco** [comment]
We already have a [Librato Dashboard](https://metrics.librato.com/share/dashboards/42hmoj9j?source=production) for metrics that are of interest to developers, and the [Stats page](https://gratipay.com/about/stats) for metrics that can be of interest to Gratipay users in general.

**Comment by whit537** [comment]
@captn3m0 The pain point I'm feeling right now is related to [queues](http://inside.gratipay.com/howto/manage-queues). I would appreciate a table on that page that gave me numbers for the following queues:

 - open support tickets (from Freshdesk)
 - open issues (across all repos)
 - open PRs not ready for review (across all repos: `~Review` where that label exists; none otherwise)
 - open PRs ready for review (across all repos: `Review` where that label exists; all otherwise)
 - open [security](http://inside.gratipay.com/howto/handle-security-issues) issues (`security` label across all repos + [security repos](https://github.com/gratipay?query=security-))
 - open [violations](http://inside.gratipay.com/howto/handle-terms-violations) issues

**Comment by captn3m0** [comment]
A few queries:

- would a breakdown for open issues be helpful (say top 3 repos as well)
- security repos are private, so I'm guessing an org-wide token would be needed
- How are the current stats generated? Is it on a cron?

**Comment by whit537** [comment]
> How are the current stats generated?

Which stats are you referring to? The Librato dashboard consumes log output via a Heroku [log drain](https://devcenter.heroku.com/articles/log-drains). The stats page does [database queries](https://github.com/gratipay/gratipay.com/blob/1804/www/about/stats.spt).

> would a breakdown for open issues be helpful (say top 3 repos as well)

Yes.

> security repos are private, so I'm guessing an org-wide token would be needed

Yes, we'll configure that in the process environment during deployment.

**Comment by whit537** [comment]
This should actually go under `/appendices/queues` rather than inline on the [Manage Queues](http://inside.gratipay.com/howto/manage-queues) howto. You can either implement inline as a simplate, or a standalone service that we iframe in (see [other examples](https://github.com/gratipay/inside.gratipay.com/tree/b9bf7931d769bc0992146a8f5576ff4a05b901ee/www/appendices)).

**Comment by whit537** [comment]
I want to be able to click through to the queues themselves.

**Comment by captn3m0** [comment]
I'm not that good at python, so I'm thinking I'll expose it as a json/jsonp endpoint in a simple app. I'll start working on it.

**Comment by whit537** [comment]
Let's have groupings in the table for Support, Review, WIP, and Issues. Here's a sketch:

| Support | 10 |
| ----------- | ----- |
| **Review** | **10** |
| [repo-1]() | 5 |
| [repo-2]() | 3 |
| [repo-3]() | 1 |
| [repo-4]() | 1 |
| **WIP** | **20** |
| [repo-1]() | 10 |
| [repo-2]() | 6 |
| [repo-3]() | 2 |
| [repo-4]() | 2 |
| **Issues** | **500** |
| [security]() | 4 |
| [violations]() | 1 |
| [repo-1]() | 450 |
| [repo-2]() | 40 |
| [repo-3]() | 3 |
| [repo-4]() | 2 |

**Comment by whit537** [comment]
!m @captn3m0 

Thanks! :-)

**Comment by captn3m0** [comment]
I'm thinking it makes sense to link these to site-wide search results where needed (multi repo results) and direct repo search when it makes sense.

For eg security count would be site-wide search. Now looking at <http://freshdesk.com/api>

**Comment by whit537** [comment]
> I'm thinking it makes sense to link these to site-wide search results where needed (multi repo results) and direct repo search when it makes sense.

Yup, sounds good.

**Comment by captn3m0** [comment]
Putting links here for documentation:

- [List of open security issues in all gratipay repos](https://github.com/search?l=&q=user%3Agratipay+label%3Asecurity&ref=advsearch&state=open&type=Issues&utf8=%E2%9C%93) - Will hopefully include private repos as well
- [Freshdesk list of tickets](http://freshdesk.com/api#view_all_ticket) - Doesn't seem to include number of tickets. Might have to paginate

Can someone think of any other providers (other than github/freshdesk) that we might need?

**Comment by whit537** [comment]
@captn3m0 You should see an invite to Freshdesk. Once you sign in you should have access to the support queue (but not the other queues in Freshdesk, we'll handle those later).

**Comment by captn3m0** [comment]
Could you clarify what WIP means? Is it PRs tagged with `3 - Work in Progress` label?

**Comment by whit537** [comment]
Yup! :-)

**Comment by whit537** [comment]
This has gone cold. Closing.
