### ISSUE TITLE
promote Gratipay users during PyCon

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#160]
Over on #111, @chrisdev proposed the idea of using the Gratipay booth/presence at PyCon to cross-promote Gratipay users within the Python community. We're looking specifically for **project** users, because when an open-source *project* is really successful, that translates into potential opportunities for many *individuals*, including and especially non-rock-stars.

The purpose of this ticket is to brainstorm and recruit and plan with potential partner projects for this PyCon cross-promotion.

So ... is this you? Is your project interested in partnering with us on this? :-)

**Comment by chrisdev** [comment]
Targets:
https://gratipay.com/readthedocs/
https://gratipay.com/bitprophet/ - Fabric
https://gratipay.com/djangogirls/ -
https://gratipay.com/mitsuhiko/ - Flask
https://gratipay.com/zzzeek/ - SQLAlchemy
https://gratipay.com/CallbackWomen/
I'm looking for Python teams. But some of these important projects are represented by single individuals on Gratipay.

**Comment by whit537** [comment]
@chrisdev In that case we should coach them through configuring their team/project on Gratipay. Many of these were set up years ago when we were focused much more heavily on individuals.

**Comment by whit537** [comment]
https://gratipay.com/pyladiessf/
https://gratipay.com/BotBotme/

**Comment by chrisdev** [comment]
@whit537 :+1: Nice choices. Did not know that they were there (discovery :frowning: )

**Comment by chrisdev** [comment]
>In that case we should coach them through configuring their team/project on Gratipay. Many of these were set up years ago when we were focused much more heavily on individuals.

* We will reach out to them at Pycon.
* Maybe we need to do a blog post extolling the virtues of teams.
* Drip email campaign (email is not just for bad news ! )

**Comment by whit537** [comment]
https://twitter.com/Gratipay/status/580091885198381057

**Comment by chrisdev** [comment]
Do we need a blog post about this? Do we email folks also

**Comment by whit537** [comment]
> Do we email folks also

Yes.

**Comment by whit537** [comment]
~~https://gratipay.com/djangogirls/~~ https://twitter.com/olasitarska/status/556859365958107136

**Comment by chrisdev** [comment]
Ok I noticed they joined about 2 weeks ago. Claims that they have guidelines we have them too.

**Comment by whit537** [comment]
> Ok I noticed they joined about 2 weeks ago.

They joined in late December, a few weeks before the tweet I linked.

**Comment by chrisdev** [comment]
Ok

**Comment by whit537** [comment]
> You should talk to @SaltStackInc! Super popular project with a lot of awesome contributors.

https://twitter.com/failvarez/status/580148236419133440

**Comment by chrisdev** [comment]
@whit537 any positive responses to this?

**Comment by whit537** [comment]
Salt doesn't really have a need for funding. Django Girls appears to be going with Patreon, though they still have a Gratipay account so I suppose we could email them. CallbackWomen appears to be active on Gratipay, but isn't tagged Python (they're tagged Ruby).

**Comment by chrisdev** [comment]
Wondering if someone like pydanny/audrey meets our criteria? They're not a team but CookieCutter alone has 60 contributors. Maybe we could encourage them to formalise themselves as a team?

**Comment by whit537** [comment]
I can't bring myself to email Ola and Ola, because of https://twitter.com/olasitarska/status/556859365958107136. Sorry. :-(

**Comment by whit537** [comment]
@chrisdev I need to let you or someone else be the one to reach out to people in the Python community. :-(

**Comment by chrisdev** [comment]
@whit53  i'll can with some rejection in my life :smile:  I can use @citruspi 's email template in #111  But do I send the emails under my own email address or the git marketing team or ???

**Comment by citruspi** [comment]
@chrisdev if you wanted to split it 50/50 so you don't have to deal with as much possible rejection and work, I'd be happy to email people also. :wink:

**Comment by chrisdev** [comment]
@citruspi don't really mind the rejection but I like the idea of a 50/50 split. On a physical letter we could both sign. Wish there was something similar for email

**Comment by citruspi** [comment]
@chrisdev We could both sign the email with our GPG key.

**Comment by whit537** [comment]
I would say keep it simple. You can cc: each other and I think that'll be enough. Let's review @citruspi's template:

>Hey {{ user }},
>
Gratipay appreciates the awesome work you do for the Python community.
>
We're planning on having a special promotion at PyCon 2015 to help highlight
people and teams who do awesome work and to help them get more funding
using Gratipay.
>
We've selected five different people and teams to take part in the promotion, and
you're one of them!
>
As part of the promotion, we will be encouraging people who visit the Gratipay
booth to give to people and teams who do awesome, specifically you.
We will also provide a dashboard at our booth which will highlight your project and
and the progress that has been made towards achieving your funding goal.
>
By the end of the conference we would like to make sure that you have reached 100%
of your funding goal.
>
Let us know if you're interested in partnering with us in the promotion.
>
- Gratipay

**Comment by whit537** [comment]
A couple tweaks:

 - You can and should say that you're with Gratipay, but we want to use a personal voice and sign it with your name. "Hey! I'll be representing Gratipay at PyCon ...," etc.
 - Let's present this as an open invitation, not an exclusive "we've selected"
 - Let's underpromise and overdeliver. Let's not promise anything about a dashboard or percentage of funding. If those happen great, but they're non-essential.
 - Let's end with a direct yes/no question instead of an open-ended "let us know."
 - Let's keep the "ask" simple: "May we use you as an example of a project to support on Gratipay?"
 - Let's focus on *projects* as much as we can (instead of *individuals*).

@citruspi Want to write a revision?

**Comment by chrisdev** [comment]
Agree with the focus on projects but sometimes the projects are represented on Gratipay as individuals. So I would target mitsuhiko buy not Kenneth Reitz for example. Although, now that I've written this I'm not so sure anymore :disappointed:

**Comment by whit537** [comment]
https://gratipay.com/PycodersWeekly/

cc: @myusuf3

**Comment by chrisdev** [comment]
@citruspi @whit537 
https://gratipay.com/julython/

**Comment by chrisdev** [comment]
Vim python mode 
https://gratipay.com/klen/

**Comment by myusuf3** [comment]
@whit537 thanks! We can do whatever formalization you guys need us to do. We are fairly big community that reads the newsletter ~20K. cc: @chrisdev

**Comment by chrisdev** [comment]
@myusuf3 :+1:  I'm a subscriber to the newsletter its a must read for me

**Comment by myusuf3** [comment]
:100:

**Comment by citruspi** [comment]
@whit537 @chrisdev 

Revised edition

---

Hey {{ project }},

I'm {{ name }} and I'll be representing Gratipay at PyCon 2015.

Gratipay appreciates the great work you do for the Python community.

We're planning a special promotion at PyCon 2015 to help highlight projects that
benefit the community. We're inviting projects who are interested in promoting
themselves through Gratipay to work with us to accomplish this.

As part of the promotion, we will be encouraging people who visit the Gratipay
booth to give to these projects.

Would you be interested in being highlighted as part of the promotion?

\- {{ name }}

**Comment by whit537** [comment]
@citruspi :shipit:

**Comment by whit537** [comment]
https://twitter.com/Gratipay/status/582658908885413888

**Comment by chrisdev** [comment]
@whit537 @citruspi I think we ready to send out some email :smile_cat: 
How do we propose to proceed?

**Comment by citruspi** [comment]
@chrisdev @whit537 

Are we going to use our personal email accounts? Or is there a Gratipay marketing email account that @chrisdev and I should send them from?

**Comment by gravyboat** [comment]
Hey @whit537 this is failvarez from twitter (guy who posted about Salt). While the organization itself doesn't need funding, we have a group here: https://gratipay.com/for/saltstack/ that consists of both members of the open source community that just work on the project, as well as those who work for the company. Last time I checked no one from our organization was receiving any sort of donation for their Salt contributions.

When you compare the number of Gratipay members versus the contributors to the main Salt repo, the ratio is huge. This is also surprising considering Salt is one of the most active projects on all of GitHub, yet even our #2 contributor (s0undt3ch, 4692 commits, 245,000 lines of code) makes $0.00 on Gratipay. This disconnect between donating to people who contribute to such a popular project, and people actually getting donated to is why I brought it up. While the organization itself is well funded, the open source contributors don't receive anything.

**Comment by whit537** [comment]
> While the organization itself is well funded, the open source contributors don't receive anything.

Thanks for jumping in @gravyboat. That definitely sounds like a potential partnership. I think it falls outside the scope of what makes sense for PyCon, because our primary goal is to introduce Pythonistas to Gratipay by suggesting projects they could fund. Can we move that convo to #165?

**Comment by thatch45** [comment]
@whit537 I never have followed up with you, I really should have. Timing for us right now is iffy, we are just very swamped. I will try to find some time to get more involved with you guys!

**Comment by whit537** [comment]
No worries, @thatch45. Maybe @chrisdev @citruspi will have a chance to catch up with you at PyCon. :-)

**Comment by whit537** [comment]
I punched another 150 pennies, so I have 350 ready to send. Bank tomorrow.

**Comment by citruspi** [comment]
@chrisdev @whit537 Have we started emailing Gratipay users yet?

**Comment by chrisdev** [comment]
@whit537 @citruspi Was wondering about this. Do we have a list of emails?

**Comment by citruspi** [comment]
@whit537 @chrisdev PyCon is in two days. We really need to get started on this.

**Comment by chrisdev** [comment]
@citruspi, @whit537 how do we progress this?

**Comment by citruspi** [comment]
@whit537 @chrisdev So, PyCon is tomorrow...

**Comment by whit537** [comment]
!m @citruspi @chrisdev et al.

**Comment by webmaven** [comment]
Results?
