### ISSUE TITLE
reach out to SaltStack

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#165]
From @gravyboat on #160:

> While the organization itself doesn't need funding, we have a group here: https://gratipay.com/for/saltstack/ that consists of both members of the open source community that just work on the project, as well as those who work for the company. Last time I checked no one from our organization was receiving any sort of donation for their Salt contributions.
>
When you compare the number of Gratipay group members versus the contributors to the main Salt repo, the ratio is huge. This is also surprising considering Salt is one of the most active projects on all of GitHub, yet even our #2 contributor (s0undt3ch, 4692 commits, 245,000 lines of code) makes $0.00 on Gratipay. There is a big disconnect between donating to people who contribute to such a popular project, and people actually part of the group who are also working on the project. While the organization itself is well funded, the open source contributors don't receive anything.

**Comment by whit537** [comment]
Mail sent to @thatch45:

>Greetings, friend. :-) Chad Whitacre here from Gittip, now Gratipay. We've met at PyCons past. In planning our strategy for this year's booth, we were talking about projects we could cross-promote with, and someone brought up Salt. Here's the ticket:
>
https://github.com/gratipay/inside.gratipay.com/issues/160
>
The key line is, "While [SaltStack, Inc.] is well funded, the open source contributors don't receive anything."
>
Is this disparity something that's on your radar at all? Would you be interested in a phone call about how Gratipay could help SaltStack distribute funds to the contributor community? How about today or tomorrow at 11am your time (US/Mountain, ya?)?

**Comment by gravyboat** [comment]
Hey @whit537, thanks for following up on this! More than anything I'd honestly like to see the big companies that use Salt contributing back to the community as opposed to SaltStack itself! A lot of us enjoy working on the project so I didn't mean what I said in a harsh manner as though the contributors deserve something, it would just be cool to see.

**Comment by whit537** [comment]
@gravyboat Gotcha, sorry for quoting you out of context. If @thatch45 ends up being interested in a call then maybe you can join us? :-)

**Comment by gravyboat** [comment]
@whit537 I'm in the middle of moving right now so chances are slim, but I can try to make it if possible. Tom and I have met on several occasions already so he knows we all want to make those fat stacks off our open source contributions. ;)

**Comment by thatch45** [comment]
@gravyboat is all about good ideas :) We all hold you in high regard!

**Comment by whit537** [comment]
This has cooled. Closing.
