### ISSUE TITLE
evaluate `Ready to Start` label

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#166]
We have a `Ready to Start` label, which is intended to help new contributors find something to work on. I doubt the effectiveness of the `Ready to Start` label in helping new contributors get started. Do we have evidence that any new contributors have actually used the label? @rohitpaulk? @techtonik? @ESWAT? et al.?

**Comment by rohitpaulk** [comment]
@whit537 - I used to search issues by `ready to start`, and I think it's useful. It's just a tag, and even if you don't think it's 'useful', it doesn't do any harm - I don't really see the point in getting rid of it.

**Comment by whit537** [comment]
Fair enough.
