### ISSUE TITLE
booth or whatevs at music festival?

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#174]
Try one first. Find one first.

**Comment by whit537** [comment]
https://www.google.com/search?q=pittsburgh+music+festival

**Comment by whit537** [comment]
http://thrivalfestival.com/
http://deutschtownmusicfestival.org/
http://www.stripdistrictmusicfest.com/
http://www.3riversartsfest.org/
http://www.wyep.org/smf2014

**Comment by kaguillera** [comment]
+1 Once I am here I am willing to help.

**Comment by whit537** [comment]
Closing marketing tickets related to individual giving, since we gave that up (#180).
