### ISSUE TITLE
Broken 'Source Code' link.

### ISSUE THREAD

**Issue by kocsenc** [gratipay/inside.gratipay.com#178]
In the table of contents, there is a link with the text `source code`. 

This link is broken and redirects to `http://inside.gratipay.com/big-picture/src` and it gives me a 404.

**Comment by whit537** [comment]
Thanks for the report, and sorry for the trouble. However, I'm unable to reproduce the problem. When I visit this link:

http://inside.gratipay.com/big-picture/src

I get a redirect to:

https://github.com/gratipay/

```
$ curl -I http://inside.gratipay.com/big-picture/src
HTTP/1.1 302 Found
Connection: keep-alive
Location: https://github.com/gratipay/
Date: Wed, 08 Apr 2015 18:38:15 GMT
Server: Aspen! Cheroot!
Via: 1.1 vegur

$
```

Can you give me more precise steps to reproduce the 404?

**Comment by kocsenc** [comment]
Further research has shown it may be a Safari-only error. 
Error seems to be
`cannot parse response. NSURLErrorDomain`

See [screenshot](http://imgur.com/u57KS8x).

This, of course, can mean that it is out of Gratipay's scope to fix.

**Comment by colindean** [comment]
I'm able to reproduce it on Safari Version 8.0.4 (10600.4.10.7) on OSX 10.10.2.

**Comment by colindean** [comment]
I went to [every page that redirects](https://github.com/gratipay/inside.gratipay.com/search?utf8=%E2%9C%93&q=request.redirect) and am seeing this behavior on all of them.

**Comment by colindean** [comment]
I tried to go to http://aspen.io/response/, which redirects to http://aspen.io/api/response/, and it works.

```
[colin@kid dnsimple-inadyn (master)]$ curl -vvv http://inside.gratipay.com/big-picture/src
* Hostname was NOT found in DNS cache
*   Trying 184.73.183.101...
* Connected to inside.gratipay.com (184.73.183.101) port 80 (#0)
> GET /big-picture/src HTTP/1.1
> User-Agent: curl/7.37.1
> Host: inside.gratipay.com
> Accept: */*
>
< HTTP/1.1 302 Found
< Connection: keep-alive
< Location: https://github.com/gratipay/
< Transfer-Encoding: chunked
< Date: Wed, 08 Apr 2015 23:51:17 GMT
* Server Aspen! Cheroot! is not blacklisted
< Server: Aspen! Cheroot!
< Via: 1.1 vegur
<
* transfer closed with outstanding read data remaining
* Closing connection 0
curl: (18) transfer closed with outstanding read data remaining
[colin@kid dnsimple-inadyn (master)]$ curl -vvv http://aspen.io/response/
* Hostname was NOT found in DNS cache
*   Trying 23.23.253.78...
* Connected to aspen.io (23.23.253.78) port 80 (#0)
> GET /response/ HTTP/1.1
> User-Agent: curl/7.37.1
> Host: aspen.io
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
* Server Cowboy is not blacklisted
< Server: Cowboy
< Date: Wed, 08 Apr 2015 23:58:50 GMT
< Connection: close
< Location: /api/response/
< Via: 1.1 vegur
<
* Closing connection 0
```

I'm going to bet that it's this:

```
< Server: Aspen! Cheroot!
```

HTTP/1.1 [§14.38](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.38) combined with [§3.8](http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.8) and [§2.2](http://www.w3.org/Protocols/rfc2616/rfc2616-sec2.html#sec2.2) lead me to believe that a `!` is not allowed in that header, and Safari is choking on it.

```
Server                = "Server" ":" 1*( product | comment )
product              = token ["/" product-version]
product-version  = token
comment        = "(" *( ctext | quoted-pair | comment ) ")"
ctext          = <any TEXT excluding "(" and ")">
quoted-pair    = "\" CHAR
```

**Comment by whit537** [comment]
>  a ! is not allowed in that header, and Safari is choking on it.

This could explain behavior that @seanlinsley saw a while ago (don't have the ticket handy). Let's verify this hypothesis and then open an issue/PR at Aspen.

**Comment by whit537** [comment]
cc: @pjz

**Comment by whit537** [comment]
Bug confirmed:

![screen shot 2015-04-09 at 10 01 10 am](https://cloud.githubusercontent.com/assets/134455/7068301/6274db34-de9f-11e4-8a72-129cc0298e8b.png)

**Comment by whit537** [comment]
Able to reproduce locally:

![screen shot 2015-04-09 at 10 02 44 am](https://cloud.githubusercontent.com/assets/134455/7068333/9b7b3478-de9f-11e4-9b76-98dfe7000c65.png)

**Comment by pjz** [comment]
Possibly relevant: http://stackoverflow.com/questions/27458839/error-domain-nsurlerrordomain-code-1017-the-operation-couldn-t-be

**Comment by whit537** [comment]
Doesn't look like it's the `Server` header:

```
$ curl -I http://localhost:8536/big-picture/src
HTTP/1.1 302 Found
Location: https://github.com/gratipay/
Server: Aspen
Connection: close
Date: Thu, 09 Apr 2015 14:06:17 GMT

$
```

**Comment by whit537** [comment]
I do see this:

```
$ curl http://localhost:8536/big-picture/src
curl: (18) transfer closed with outstanding read data remaining
```

**Comment by whit537** [comment]
The other thing is that we're using an old version of Aspen on IG (0.28.3, current is 0.37). Let's revisit this after #133.

**Comment by techtonik** [comment]
Aspen is upgraded to 0.37. Can you test if the bug is gone?

**Comment by kocsenc** [comment]
Kocsen here, the URL that was originally causing the bug (`http://inside.gratipay.com/big-picture/src`) is working right. 

I'm on Safari 8.0.7

**Comment by techtonik** [comment]
!m @kocsenc
