### ISSUE TITLE
`make run` fails

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#182]
```
inside.gratipay.com$ make run
make: *** No rule to make target `local.env', needed by `run'.  Stop.
```
What should be there?

**Comment by whit537** [comment]
`local.env` with some keys (similar to gratipay.com). If you figure out which keys they are you could add to README. :-)

**Comment by techtonik** [comment]
Well, inside site works ok without `local.env`, so it looks like unnecessary complication to me.

**Comment by whit537** [comment]
What happens if you edit `Makefile` to remove the dependency of `run` on `local.env`? Does `honcho` fail?

**Comment by techtonik** [comment]
No. It works ok. I tested PR #183 locally with that change.

**Comment by whit537** [comment]
Okay, PR to remove it then?

**Comment by techtonik** [comment]
@whit537 I stuffed the removal into the last commit of PR #181 .
