### ISSUE TITLE
prune team

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#188]
With Changaco [leaving](http://changaco.oy.lc/blog/goodbye-gratipay/) and a generally heightened threat environment, it seems like a good time to remove GitHub contributors that haven't been involved for a while. I'm going to ping people here as I remove them.

**Comment by whit537** [comment]
I'm going to prune from the Gratipay team as well (though I'll let Changaco remove himself from there).

**Comment by whit537** [comment]
I'm going through the API to determine who has made recent commits. I don't see that we can get comment counts out of the API.

**Comment by whit537** [comment]
https://github.com/tzachz/github-comment-counter

**Comment by whit537** [comment]
Yeah, I'm not gonna bother with comments.

**Comment by whit537** [comment]
Here's the script I came up with:

```python
import json
import time
import sys


WEEK = 60 * 60 * 24 * 7
MONTH = 60 * 60 * 24 * 30
NOW = time.time()
nmonths = int(sys.argv[1]) if len(sys.argv) > 1 else 1


# https://api.github.com/repos/gratipay/gratipay.com/stats/contributors
contributors = json.load(open('contributors.json'))

# hand-produced from https://github.com/orgs/gratipay/people
team = set(open('team.txt').read().splitlines())

active = set()

for c in contributors:
    username = c['author']['login']
    if username not in team:
        continue
    weeks = c['weeks']
    for w in reversed(weeks):
        if w['c'] > 0:
            if NOW - w['w'] < MONTH * nmonths:
                active.add(username)

for name in sorted(active):
    print name
```

**Comment by whit537** [comment]
| activity threshold (months) | additional users |
|:-------------------------------------:|---------------------|
| 1 | kaguillera, rohitpaulk, techtonik, whit537 |
| 2 |  |
| 3 | benhc123 |
| 4 | clone1018, colindean, rummik, seanlinsley |
| 5 | greggles |
| 6 |  |
| 7 |  |
| 8 | oakes |
| 9 | ericmeltzer |
| 10 | chrisdev |
| 11 | ivanmushketyk, patcon, sim6 |
| 12 | Aaron1011, pjf |
```

**Comment by whit537** [comment]
Seems like a pretty natural division at ~6 months ago.

**Comment by whit537** [comment]
So here's a list of active contributors (plus pjz for Aspen and captn3m0 for #157):

```
benhc123
clone1018
colindean
greggles
kaguillera
rohitpaulk
rummik
seanlinsley
techtonik
whit537
pjz
```

**Comment by whit537** [comment]
| Person | On Gratipay Team | On GitHub Team | Active |
|---|:---:|:---:|:---:|
| Aaron1011 | ✓ | ✓ |   |
| Aspen | ✓ |   |   |
| Changaco | ✓ |   |   |
| ESWAT | ✓ | ✓ |   |
| HeidiMGardner | ✓ |   |   |
| Lurtz | ✓ |   |   |
| Martijn | ✓ |   |   |
| MikeFair | ✓ | ✓ |   |
| abnor | ✓ | ✓ |   |
| aisipos | ✓ |   |   |
| benhc123 | ✓ | ✓ | ✓ |
| bewithsahilsaif | ✓ |   |   |
| bmann | ✓ | ✓ |   |
| brareme | ✓ |   |   |
| buttscicles | ✓ |   |   |
| captn3m0 | ✓ | ✓ | ✓ |
| cellhelmetMike | ✓ |   |   |
| chrisdev | ✓ | ✓ |   |
| clone1018 | ✓ | ✓ | ✓ |
| colindean | ✓ | ✓ | ✓ |
| cummingsrob |   | ✓ |   |
| dmk246 | ✓ | ✓ |   |
| dsernst | ✓ | ✓ |   |
| ericmeltzer |   | ✓ |   |
| ethangj | ✓ | ✓ |   |
| fox | ✓ |   |   |
| galuszkak | ✓ | ✓ |   |
| geNAZt |   | ✓ |   |
| greggles | ✓ | ✓ | ✓ |
| heidigardner |   | ✓ |   |
| hurlothrumbo | ✓ |   |   |
| ivanmushketyk | ✓ | ✓ |   |
| jeresig |   | ✓ |   |
| joealcorn |   | ✓ |   |
| joeyespo | ✓ | ✓ |   |
| kaguillera | ✓ | ✓ | ✓ |
| lyndsysimon | ✓ |   |   |
| matthewfl |   | ✓ |   |
| mtrythall | ✓ | ✓ |   |
| mw44118 | ✓ |   |   |
| nejstastnejsistene |   | ✓ |   |
| oakes | ✓ | ✓ |   |
| patcon | ✓ | ✓ |   |
| pjf | ✓ | ✓ |   |
| pjz | ✓ | ✓ | ✓ |
| ptillemans | ✓ |   |   |
| raghav007bisht |   | ✓ |   |
| rohitpaulk | ✓ | ✓ | ✓ |
| rummik | ✓ | ✓ | ✓ |
| seanlinsley | ✓ | ✓ | ✓ |
| sim6 | ✓ | ✓ |   |
| simon-weber |   | ✓ |   |
| techtonik | ✓ | ✓ | ✓ |
| thiagoponte | ✓ |   |   |
| twolfson | ✓ | ✓ |   |
| wheatpond | ✓ |   |   |
| whit537 | ✓ | ✓ | ✓ |
| wilkie | ✓ | ✓ |   |
| zwn | ✓ | ✓ |   |

**Comment by whit537** [comment]
Let's mix in translators ...

**Comment by whit537** [comment]
We're going to have to deal more fully with translators separately. They're not well-integrated into the Gratipay teams structure. #189

**Comment by whit537** [comment]
Why isn't ESWAT on the active list? https://github.com/gratipay/gratipay.com/pull/3229

**Comment by whit537** [comment]
He's not in https://api.github.com/repos/gratipay/gratipay.com/stats/contributors.

**Comment by whit537** [comment]
Why not?

**Comment by whit537** [comment]
Meh. I'm not gonna sweat it too much, I wanna get this done. Added him to the active list.

**Comment by whit537** [comment]
Here are the people who are on the GitHub team but do not have recent commits, batched in tens because that's the most we can @mention at once.

Aaron1011
MikeFair
abnor
bmann
chrisdev
cummingsrob
dmk246
dsernst
ericmeltzer
ethangj

galuszkak
geNAZt
heidigardner
ivanmushketyk
jeresig
joealcorn
joeyespo
matthewfl
mtrythall
nejstastnejsistene

oakes
patcon
pjf
raghav007bisht
sim6
simon-weber
wilkie
zwn

**Comment by whit537** [comment]
@Aaron1011 @abnor @bmann @cummingsrob @dsernst @ericmeltzer @ethangj @galuszkak @geNAZt @heidigardner

Thanks for your work on Gratipay in the past! We're doing some team clean-up, and we've removed you from our team on GitHub and/or Gratipay. See the ticket I'm posting this on for context. If you'd like to get involved again in the future, we'd love to have you! :-)

**Comment by whit537** [comment]
@ivanmushketyk @jeresig @joealcorn @joeyespo @matthewfl @MikeFair @mtrythall @nejstastnejsistene @oakes @patcon @pjf

Thanks for your work on Gratipay in the past! We're doing some team clean-up, and we've removed you from our team on GitHub and/or Gratipay since we haven't seen you in a while. See the ticket I'm posting this on for more context. If you'd like to get involved again in the future, we'd love to have you! :-)

**Comment by whit537** [comment]
@raghav007bisht @sim6 @simon-weber @wilkie @zwn

Thanks for your work on Gratipay in the past! We're doing some team clean-up, and we've removed you from our team on GitHub and/or Gratipay since we haven't seen you in a while. See the ticket I'm posting this on for more context. If you'd like to get involved again in the future, we'd love to have you! :-)

**Comment by joeyespo** [comment]
Fair enough. Best of luck, all! :smiley:

**Comment by whit537** [comment]
Thanks @joeyespo! :-)

**Comment by whit537** [comment]
@mvdkleijn @bewithsahilsaif @brareme @thefoxis @mw44118

Thanks for your work on Gratipay in the past! We're doing some team clean-up, and we've removed you from the Gratipay team on Gratipay since we haven't seen you in a while. See the ticket I'm posting this on for more context. If you'd like to get involved again in the future, we'd love to have you! :-)

**Comment by patcon** [comment]
Heh. Interesting idea to set team members via a public, programmatic heuristic. Makes it so it's never any hard feelings or decision when folks are added/removed.

But bummed about context of this change :(

**Comment by sim6** [comment]
:(
I am preparing a new pull request

**Comment by mw44118** [comment]
I love gratipay but have no budget for working on this.  Besides the
technical war has been won.

**Comment by whit537** [comment]
@sim6 Nice! Happy to add you back. :-)

**Comment by whit537** [comment]
Thanks for your support @mw44118 @patcon @joeyespo. Hope to keep seeing you around, and happy to have you back on the Gratipay team any time. :-)

**Comment by pjf** [comment]
Oh my! That's a great looking table you've got there! No probs with the team status change; apprently my life is now completely dominated by trying to manage the entire Kerbal Space Programme modosphere. o_O

Keep being awesome!

~ pjf

**Comment by techtonik** [comment]
Awesome. I think it also worth to record all people into the project history.

**Comment by tshepang** [comment]
@techtonik `git log` not enough?

**Comment by whit537** [comment]
Cheers @pjf! See you around! :-)
