### ISSUE TITLE
find a lawyer

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#193]
It's time to firm up, with professional legal advice, our analysis of a number of risks (highest priority first):

 1. not being a money transmitter (#192)
 1. not funding terrorism (#119)
 1. working with payment processors (https://github.com/gratipay/gratipay.com/issues/67)
 1. policing off-site behavior (#122)
 1. structuring our Payroll feature (https://github.com/gratipay/gratipay.com/issues/2569)
 1. reviewing our terms (https://github.com/gratipay/gratipay.com/issues/3367)
 1. writing up a contractor agreement (https://github.com/gratipay/gratipay.com/issues/1443)

In choosing whom to work with, here are the (prioritized) criteria I have in mind:

 1. Ability to advise us well on a range of issues.
 1. Comfort level with open culture.
  1. Are they okay showing up on our [finances](http://inside.gratipay.com/appendices/finances)?
  1. Are they okay with us making decisions publicly on GitHub?
  1. Are they okay with us posting their advice publicly on GitHub?
  1. Are they themselves willing to post publicly on GitHub?
 1. Affordability.

**Comment by whit537** [comment]
I had a call with [Aaron Williamson](http://torekeland.com/about/aaron-williamson) from Tor Ekeland, and I have calls scheduled with [WilmerHale](https://www.wilmerhale.com/) and [Chestek Law](http://chesteklegal.com/).

Here are the criteria I have in mind:

 - Ability to advise us well on a range of issues.
 - Comfort level with open culture.
  - Are they okay showing up on our [finances](http://inside.gratipay.com/appendices/finances)?
  - Are they okay with us making decisions publicly on GitHub?
  - Are they okay with us posting their advice publicly on GitHub?
  - Are they willing to post publicly on GitHub?
 - Affordability.

**Comment by whit537** [comment]
Called, left a message with http://www.saul.com/attorneys/adam-kelson.

**Comment by whit537** [comment]
Left a message with http://www.klgates.com/emerging-payment-systems-practices/.

**Comment by whit537** [comment]
Followed up with emails to Adam and Bob.

**Comment by whit537** [comment]
Googling for payment systems law turns up:

 - http://www.dwt.com/practices/PaymentSystems/
 - http://www.paulhastings.com/area/payment-systems ← represented Coinbase, e.g. ([ref](http://www.dfs.ny.gov/legal/vcrf_0500/20140828%20-%20VC%20Proposed%20Reg%20Comment%2096%20-%20Coinbase.pdf))
 - http://www.pillsburylaw.com/payments

**Comment by whit537** [comment]
Heard from WilmerHale, but since I had reached out to licensing and our focus has shifted to regulatory compliance, the conversation was short (he referred me to their [financial services](https://www.wilmerhale.com/financial_institutions/) practice).

**Comment by whit537** [comment]
I'm in an email conversation with Bob Zinn from K&L Gates. We're coordinating a time to meet (and I pointed him at this ticket :-).

**Comment by techtonik** [comment]
> `4. policing off-site behavior`

Controlling what users do off-site is none of Gratipay business. Or putting it other way - if Gratipay want to be a policeman of the Internets it will lose its users.

**Comment by whit537** [comment]
@techtonik Please discuss that on the relevant ticket, not here.

**Comment by whit537** [comment]
Just wrapped a call with Pam. She declined to take us on since payment systems is outside of her practice, but offered to put us in touch with others who might a) be able to help, and b) "get" open source (as she does). I linked her to this ticket so she can share it around.

**Comment by whit537** [comment]
From Aaron:

> I enjoyed our conversation yesterday about Gratipay's business and legal concerns. I think that your progressive approach to governance, employee compensation, and customer pricing is interesting and exciting, and I'd love to have the opportunity to work with you on reducing your exposure while maintaining your commitment to those ideals.
>
I want to be up front that my firm does not have prior experience with regulation of money transmitters & money services businesses. That said, it's an area we're interested in developing experience in, and we're confident that we could effectively counsel Gratipay on its obligations. We advise clients on similarly complex regulations, such as OFAC export controls and SEC securities regulations. There would of course be a learning curve for us in this area, and we would not bill Gratipay for the time required for us to get us up to speed on the FinCEN and state registration and reporting requirements.
>
Regardless of whether you choose to work with us on the money transmitter issues, we're available to advise you on the corporate, employment, and governance issues we discussed. Please let me know if you'd like to set up a time to speak further about working together.

**Comment by whit537** [comment]
Heh. :-)

http://lawyersongithub.com/

**Comment by whit537** [comment]
Pam:

> I just looked at the ticket and see you spoke with Aaron Williamson. I think very highly of him; he is an excellent lawyer and if he is willing to take on the work I would suggest using him. I don't think I can find anyone more suited for the work than he is. (And you can post this comment on the ticket if you'd like).

**Comment by tshepang** [comment]
take Aaron

**Comment by whit537** [comment]
Okay! So we have three open leads at this point. Here's what I'm seeing:

**Aaron Williamson** (Tor Ekeland)
 - Very high marks for "open company" comfort level
 - Low marks for payment systems expertise
 - Mid-range price

**Bob Zinn** (K&L Gates)
 - Very high marks (presumably) for payment systems expertise
 - Low to medium marks (presumably?) for "open company" comfort level
 - High price (presumably)

**Adam Kelson** (Saul Ewing)
 - Low to medium marks for payment systems expertise
 - Low to medium marks (presumably) with "open company" comfort level
 - Mid-range price (presumably)

**Comment by whit537** [comment]
@tshepang Aaron does look like he could be a good fit for us, yes. However, if Bob is at all comfortable with our "open company" culture, then it could make sense to use Bob for the high-risk payment systems questions since presumably he's well-versed in those: 1, 2, and 3 in the ticket description. I doubt it will make sense for Bob to look at 4, 5, 6, or 7 for us, so there would still be plenty for Aaron to help us with.

I like that Bob is in Pittsburgh and that he asked to meet me face-to-face. Despite advances in technology, real life is still the highest emotional bandwidth channel of communication, and for important legal matters that extra bandwidth could be valuable. Adam is also in Pittsburgh, and we've met before.

**Comment by tshepang** [comment]
I find Aaron attractive because:

- He comes highly recommended
- He's willing to do it for free in the beginning
- He already deals with some other money matters

This is not to say mine is a strong objection of course... go with the one you feel is the best fit.

**Comment by whit537** [comment]
To Aaron:

>Thanks for the positive response! At this point we have two other leads still open, and we're converging on a decision. You can find details on our ticket about [finding a lawyer](https://github.com/gratipay/inside.gratipay.com/issues/193).
>
A few more questions for you:
>
May we start with [a smaller initial retainer]?
>
May we be public about the rate/fees we pay you?
>
Are you comfortable showing up on our [finances](http://inside.gratipay.com/appendices/finances) (click the year tabs to see our detailed transaction history)?
>
Are you willing to use GitHub to communicate with us?
>
Are you willing for your communications with us to show up publicly on GitHub by default (whether you post directly or I copy/paste)?
>
We do make some allowances for private communication (e.g., [security](http://inside.gratipay.com/howto/handle-security-issues), [terms violations](http://inside.gratipay.com/howto/handle-terms-violations), [customer support](http://inside.gratipay.com/howto/support-users)), but only in well-defined circumstances. For the matters listed at the top of the "find a lawyer" ticket, I would hope to have those conversations publicly.
>
Thanks, Aaron! :-)

**Comment by whit537** [comment]
From Adam:

> Happy to chat about your legal needs – Monday would be best.  I don’t have specific experience with the money transmitter regulations, but let me make sure one of my colleagues does.    If we don’t I’ll shoot you a note so I don’t waste your time, but it would still be worth talking about how we can be helpful in other areas.

To Adam:

> Thanks Adam. We have a ticket on [finding a lawyer](https://github.com/gratipay/inside.gratipay.com/issues/193) that has more specifics on what we're looking for help with. Let me know if you think Saul could be a good fit ...

**Comment by copiesofcopies** [comment]
Hi @whit537, @tshepang, and @techtonik! I am comfortable communicating on Github. When I worked at the Software Freedom Law Center, we worked as much as possible in plaintext (markdown and LaTeX) and collaborated on documents via svn (git wasn't around when the repository was set up). I also advised a number of clients with a similar preference for working in the open, so I had to get comfortable with the fact that my emails would sometimes show up on publicly archived mailing lists ;) 

As I explained to @whit537 on our call, there are circumstances in which tracking everything publicly can create legal risk, and not necessarily because you're doing anything intentionally wrong, so if we work together I will likely recommend that certain things remain private, at least for a time. These precautions are not about hiding what you are doing, but allowing you to experiment and make mistakes without taking on undue legal risk.

In particular, I think that it's best to receive and deliberate on your attorneys' advice in private, preserving the attorney-client privilege, before you make the results of those deliberations public. In fact, every attorney is under an obligation to preserve the attorney-client privilege in communications with clients. The privilege is the client's -- you are free to waive it by making those communications public, but your attorney is not. So I would feel obligated to provide any privileged advice privately, regardless of what you decided to do with it subsequently.

Good luck with your search!

**Comment by whit537** [comment]
Thanks for jumping in, @copiesofcopies! :dancer:

> Probably the most interesting thing there is the code I used to scrape FLOSS license data from Github for a presentation.

Hooray for Python! :snake: 

> I will likely recommend that certain things remain private, at least for a time.
> I would feel obligated to provide any privileged advice privately, regardless of what you decided to do with it subsequently.

Okay, we can work with that. The two possible patterns I see for still using GitHub to communicate are:

 - One private repo for all legal issues. We would receive and digest your advice there, and copy/paste over to relevant public issues.
 - One private repo per legal issue, that we publish in full once the issue is resolved.

The former is how we [handle terms violations](http://inside.gratipay.com/howto/handle-terms-violations), the latter is how we [handle security issues](http://inside.gratipay.com/howto/handle-security-issues). I'd prefer the latter for legal issues, because eventually divulging our entire deliberation helps ensure that we truly act in such a way that we have nothing to hide. However, there are some technical limitations on GitHub that shape what we can do:

 - We can't hide/publish individual issues, only repos, so it's technically burdensome to separate out and publish a single issue from a private repo that also contains other issues that *aren't* ready to be published. We basically have to copy and paste, and we lose some of the honesty and transparency punchiness of cleanly divulging our entire conversation ("What did they leave out?").
 - Private repos cost money, so we only want to adopt `one-repo-per-legal-issue` if we're confident that we can publish the repo eventually. We don't want to end up with lots of tiny one-issue private repos that we have to pay extra to keep around.

@copiesofcopies Looking at the issues listed at the top of this ticket, do you have a sense of whether we'd be able to determine at the outset that we could conduct our conversations in such a way that we could eventually publish them? Or would you want to pursue the `one-legal-repo-to-rule-them-all` approach?

**Comment by whit537** [comment]
From Aaron:

> I responded to the Github thread, so hopefully that answers that question :) We can work with [a smaller advance]. I will have to talk to my partners about making our fees public.

To Aaron:

>Thanks for jumping in on GitHub! :D I've followed up there on the question of how specifically we could use GitHub to communicate about legal matters.
>
Thanks for flexing on the advance, too. As far as divulging rates/fees goes:
>
 - It's easier for me if I can share your specific hourly rates publicly with the people in the Gratipay community, so that they can help me make good decisions about how we're spending our money. However, if you're not comfortable with that, then I can keep your specific hourly rates confidential.
>
 - It would be rather more difficult for me to keep our total aggregate payments to you confidential, because we log our entire bank transaction history and balance on our finances spreadsheet.
>
Let me know what you're comfortable with here.

**Comment by copiesofcopies** [comment]
@whit537 we would be comfortable with aggregate fees being reported publicly. As for which approach to take on the legal-issues repo, my suggestion would be to keep an always-private repo for legal issues, and to make public only summaries of the outcome of private deliberations. There are countless ways in which, by publishing the advice you considered and rejected, you could expose Gratipay to substantial liability.

**Comment by whit537** [comment]
> [W]e would be comfortable with aggregate fees being reported publicly.

Cool, thanks.

> [M]y suggestion would be to keep an always-private repo for legal issues, and to make public only summaries of the outcome of private deliberations.

Okay.

**Comment by whit537** [comment]
Alright, @copiesofcopies. Let's go for it! :dancer: 

I've created a new private repo and I've invited you to it. I'm not ready to make a decision yet on whether we adopt `repo-per-issue` or `one-big-repo`. Let's start with a private repo for the money transmitter issue (#192) since that's the most pressing concern, and Gratipay can decide later whether to expand that repo or make new ones.

Let me know the best way to make payment and how else to proceed. For billing and such let's please use vendors@gratipay.com.

Okay! Huzzah! :D

[!m](http://motivate.im/) @copiesofcopies

**Comment by whit537** [comment]
I've notified Bob and Adam of our decision.

**Comment by whit537** [comment]
Leaving this open until the ink is dry ...

**Comment by copiesofcopies** [comment]
I look forward to working with you, @whit537 and all! I'll send an engagement letter over shortly.

**Comment by whit537** [comment]
Having some back and forth with Bob. My latest reply:

>You're clearly the more experienced and connected attorney. However, I'm juggling a number of pieces under [a fast-looming deadline](https://medium.com/gratipay-blog/balancedshutdown-3a9fdb32e9c6), and in the end I had to make a judgement call on this this week [balancing all factors](https://github.com/gratipay/inside.gratipay.com/issues/193#issuecomment-97432285) with only $3,500 in total operating cash.
>
You caught my attention when you said you wanted to meet in person, rare to find that. Hopefully I'll survive this crunch and we'll have a chance to connect over more demanding challenges down the line. Happy to recommend you in the meantime, good to know we have your expertise in Pittsburgh.

**Comment by whit537** [comment]
Engagement letter received in https://gratipay.freshdesk.com/helpdesk/tickets/2050.

**Comment by whit537** [comment]
To: Aaron

>Here is the executed engagement letter. I've created a Chase QuickPay account, because that is the fastest free method of payment I saw among the available options. It'll take another day or two to verify our bank account with Chase, and then I'll initiate the payment, which will take a couple more days to clear. Hopefully by next Monday the funds will have settled in your account and we can get to work! :-)

**Comment by whit537** [comment]
From: Aaron

> I think the fastest free (to Gratipay) method is probably a credit or debit card payment via Lawpay - does that not work for you? If you’re trying to save us fees, I appreciate it, but you really don’t have to worry about it :)

To: Aaron

>Fair enough. Wasn't sure if you assessed the processing fee to us or not. :-)
>
Payment made! What's next? See you on [our private GitHub repo]?

**Comment by whit537** [comment]
Now that we're using private GitHub repos for legal matters, it seemed best to me to constrain the Owners team on GitHub to only actual legal owners of Gratipay, LLC (the Owners team has access to all repos). That means I've moved @clone1018 @seanlinsley @rohitpaulk from the Owners team; now it's just me. We've got #72 for broadening ownership to a cooperative model, and I've just reticketed #196 for bringing on a second owner as low-hanging fruit to reduce our single point of failure.

**Comment by clone1018** [comment]
Ouch. :(

**Comment by clone1018** [comment]
Bus factor is now at 1

**Comment by whit537** [comment]
@clone1018 SEe #196.
