### ISSUE TITLE
bring on a second owner

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#196]
Right now Gratipay, LLC is a sole proprietorship, and I'm the sole proprietor. This creates a single point of failure that is dangerous for Gratipay: what if something happens to me? We've had a little bit of conversation on #72 about broadening ownership to more of a cooperative model that would ensure the longevity of the organization. This ticket is about bringing on just one more owner as low-hanging fruit to at least address the single point of failure.

**Comment by whit537** [comment]
I nominate @clone1018.

**Comment by Karmak23** [comment]
@whit537 perhaps i'm off-topic, but what about [SPI-INC](http://www.spi-inc.org/) to own things ?

**Comment by clone1018** [comment]
I would be honored to become a second owner in Gratipay, LLC. I've been a part of the team since Mar 5, 2014 and I have the technical knowhow and training to continue running Gratipay in Chad's place. 

So, totally down for it, when do you want to do a Hangout @whit537 ?

**Comment by tshepang** [comment]
Wow, it feels like it's been a lot longer @clone1018. Maybe because you were active in Issues?

**Comment by whit537** [comment]
@Karmak23 Not a bad suggestion. Reticketed as #197.

@clone1018 Huzzah! :dancer:

Executing this is probably a matter of having @copiesofcopies help us with an ownership agreement.

On the one hand, it could make sense to wait and see what's left once the Gratipocalypse settles down. On the other hand, now that we're deep into private legal discussions, I would love having someone else involved in those discussions.

**Comment by whit537** [comment]
Dusting this off to say that I am making a will (kind of rushing it before traveling for #314 :-/ ), and I am leaving Gratipay, LLC to "Luke Strickland of Dallas, Texas."

**Comment by whit537** [comment]
P.S. That's actually in my actual will (not just something I posted here on GitHub). Need to clarify clarified by @clone1018 during #948.

**Comment by whit537** [comment]
This'll be obsolete if we land #72 first, which seems possible.

**Comment by whit537** [comment]
Not obsolete ... complete!

!m @clone1018 * 💃 🌻

**Comment by whit537** [comment]
```
gratipay::DATABASE=> UPDATE participants SET is_owner = true WHERE username = 'clone1018';
UPDATE 1
gratipay::DATABASE=> select username from participants where is_owner;
┌───────────┐
│ username  │
├───────────┤
│ whit537   │
│ clone1018 │
└───────────┘
(2 rows)

gratipay::DATABASE=>
```
