### ISSUE TITLE
transfer ownership to an existing non-profit

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#197]
@Karmak23 mentions http://www.spi-inc.org/ at https://github.com/gratipay/inside.gratipay.com/issues/196#issuecomment-100078002.

I'm also aware of https://sfconservancy.org/.

**Comment by techtonik** [comment]
Ownership of what? The code is public domain. What else is needed?

**Comment by techtonik** [comment]
This can be actually very beneficial to SF conservancy, but I am not sure they are eligible to be called an Open Company. For example, I do not see any public discussion board (forum or list).

I had a debate with them one day when they failed to crowd source the money for their NPOAcct idea. The point was that AGPL accounting software has no value for people, who'd like to build and propose their own services on top of that platform, and that the absolute freedom for software is without any copyright restriction. I have the impression that people don't agree with me, but YMMV.

**Comment by whit537** [comment]
Yeah, I can see potentially partnering with organizations such as these, but I don't see momentum in the direction of transferring ownership.
