### ISSUE TITLE
reach out to known-good receivers re: new terms

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#198]
Gratipay is adopting new terms of service for receivers, for two reasons:

 - There is legal uncertainty regarding our old terms (https://github.com/gratipay/inside.gratipay.com/issues/192).
 - We are pivoting (https://github.com/gratipay/inside.gratipay.com/issues/180).

Receivers will need to apply under these new terms and have us accept their application in order to receive payments through Gratipay. These terms are still in [active development](https://github.com/gratipay/gratipay.com/issues/3390) and will unfortunately exclude a number of people who have been receivers on Gratipay in the past (specifically: individuals, and non-open-culture projects).

The purpose of this ticket is to establish contact with the Gratipay receivers that we know we want on the platform going forward (namely, open-culture projects), to ensure that as many of you as possible are able to provide input into this process, to accept our new terms when they are available, and to get back on track with your Gratipay payments as quickly as possible if you so choose.

We welcome your feedback, and we'll announce the specific steps you will need to take as soon as possible.

**Comment by whit537** [comment]
```sql
  select username, receiving
    from participants
   where receiving >= 10 
     and claimed_time is not null 
     and not is_closed
     and is_suspicious is not true
     and not anonymous_receiving
order by receiving desc;
```

162 results

**Comment by whit537** [comment]
I'm going to hand-curate a list of receivers from those 162 and then reach out to them by personal email individually.

**Comment by whit537** [comment]
My initial analysis:

| n | category | verdict |
|---:|:--------------|------------|
| 35 | open-culture projects | Yes! |
| 9 | non-open-culture projects | No. |
| 118 | individuals | Ouch. Wat do? |

There's a conversation to have about the 118 individuals, but that's for https://github.com/gratipay/inside.gratipay.com/issues/180. Here we're focused on the 35 that we definitely *want* on Gratipay.

**Comment by whit537** [comment]
Here they are:

http://gratipay.com/activeadmin
http://gratipay.com/BotBotme
http://gratipay.com/by_codebar
http://gratipay.com/CallbackWomen
http://gratipay.com/catapultpgh
http://gratipay.com/chtotalism
http://gratipay.com/Citizens%20Cooperative
http://gratipay.com/cityasacampus
http://gratipay.com/civicrm-lts
http://gratipay.com/codeandsupply
http://gratipay.com/CountrCultrLabs
http://gratipay.com/cpantesters
http://gratipay.com/DrupalCoreGittipTeam
http://gratipay.com/esdiscuss
http://gratipay.com/GoodBoyDigital
http://gratipay.com/Gratipay
http://gratipay.com/Homebrew
http://gratipay.com/jsonresume
http://gratipay.com/js_bin
http://gratipay.com/Kiberpipa
http://gratipay.com/MailpileTeam
http://gratipay.com/noisebridge
http://gratipay.com/NuvolaPlayer
http://gratipay.com/omnicommons
http://gratipay.com/pocmakerspace
http://gratipay.com/ProjectTox
http://gratipay.com/readthedocs
http://gratipay.com/riseup.net
http://gratipay.com/SFBayAreaRentersFed
http://gratipay.com/Shields
http://gratipay.com/sudomesh
http://gratipay.com/sudoroom
http://gratipay.com/TransH4CK
http://gratipay.com/ucoin

**Comment by whit537** [comment]
Those of you paying close attention will notice that I've revised away a few "clear yeses." More conversations to be had about that, but again, let's focus on the clear cases here.

**Comment by whit537** [comment]
Leaving Gratipay aside, we have 31 users in scope here. We have emails on file for 13 of them. I'm going to manually scrounge up emails for the rest and send them a message through our `email_queue`.

**Comment by whit537** [comment]
Okay, I have emails for all 31. I guess I'll send BCC using support@gratipay.com Gmail since `email_queue` depends on `participants.email_address` and we don't have that for everyone here.

**Comment by whit537** [comment]
[Looks like](https://support.google.com/a/answer/166852?hl=en) Gmail's BCC limit is 500, so we should be good there.

**Comment by rohitpaulk** [comment]
We can send emails through our queue for people who don't have a verified email address (like how we send the initial verification emails), but doing it through gmail would probably be far simpler.

**Comment by whit537** [comment]
To: support@gratipay.com
BCC: 31

>Greetings!
>
I'm writing because an organization or project you represent has been receiving money through Gratipay, and we want to keep you as a user if we can, as we emerge from some recent [upheaval](https://medium.com/gratipay-blog/gratipocalypse-42fd0ec0d9e8).
>
As you may have heard, Gratipay has stopped processing payments because of [legal uncertainty](https://github.com/gratipay/inside.gratipay.com/issues/192) regarding our old terms of service. In developing our new terms, we are [pivoting](https://github.com/gratipay/inside.gratipay.com/issues/180) to focus exclusively on users such as you: projects related to open culture.
>
You will need to apply in order to use Gratipay again, and the application process is not yet in place. That said, if you are receiving this message then **we want you on Gratipay**, and the purpose of this message is to ensure that as many of you as possible are able to [provide input into the development of our new terms](https://github.com/gratipay/gratipay.com/issues/3390), and to get back on track with your Gratipay payments as quickly as possible if you so choose.
>
I'm sorry for the disruption. I know you trusted us with your income and it's a big deal for us to do this to you. Please get in touch publicly or privately if there is anything I can clarify.
>
chad
>
P.S. Here is a list of who received this message.
