### ISSUE TITLE
process silverhook's terms feedback

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#204]
Ticketing so it doesn't slip off the radar.

https://github.com/gratipay/gratipay.com/pull/3408#issuecomment-102071881

**Comment by rohitpaulk** [comment]
Copying the comment over...

> OK, I managed to skim quickly through the ToS (excluding the PP and other referenced terms).

> First of all, I find it very laudable that the ToS are easily readable and take only ~ 8 pages :clap:

> Regarding the content itself, I think it is fine, however there are some points I would like to have clarified (preferebly in the ToS itself) or I have comments about:

> - In §2.1 you already mention “Teams” without defining them before. Later the ToS lay out how to estabilish a team, but do not explicitly define a Team. While it may be implicitly understood what it is, having an explicit definition would be good. If I understand §2.2 correctly, even one member is enough to constitute a Team. Also, it would be useful to explicitly define what the relationship between “You” and “Team” is.
> - Is the primary aim of §5.3 to idemnify Gratipay or to hold Team Owners liable? The first part of the paragraph reads as if it is about idemnification of Gratipay, but the last sentence seems quite strongly to push the liability onto the Team Owner.
> - Personally, I find using CC0 for Gratipay.com in §6.1 as a really nice touch and a fresh approach. I take it you do understand the implications of this, though.
> - Staying on the topic of copyright, in §7.1 the copyright license that Participant grants to Gratipay is relatively broad to what Gratipay actiually needs at the time. While §7.2 clarifies what this license permits Gratipay to do, I would welcome a provision where it explicitly stated for which purposes Gratipay may use it.
> - If I understand §4.3 correctly in connection with §8.1(2), it is not allowed to fund something like LOIC through Gratipay. (I’m just checking, not complaning.)
> - The wording of §10.1 “subject to certain state laws” seems to be ambiguous whether an NPO (e.g. KDE e.V. or GNOME Foundation) would need to comply with laws concerning charitable solicitations in their own jurisdiction or State of Pennsylvania.
> - Regarding the “without notice to you” provisions in §11.4 and §12.1, I would very much like to be informed of it, just as under §17.2.
> - On that topic, it would be really nice if you could add a possibility for community involvement in the process of changing the ToS & PP, similar to the one in §4.5 (when a Team is being estabilshed).

> Other than that, regarding content I have nothing to complain about. It looks pretty good to me :smile_cat:

> As for the form, I very warmly recommend to read (and apply) the suggestions in this short blog post on how to make HTML legal documents (such as the MPL) look nice. I especially agree with the “no all caps” rule – no-one reads all caps paragraphs, so they are not emphesised, but hidden by it. :stuck_out_tongue_closed_eyes:

**Comment by silverhook** [comment]
_Copying the source of the comment, so the links and markup work as well. (Sorry for the duplication)_

OK, I managed to skim quickly through the ToS (excluding the PP and other referenced terms).

First of all, I find it very laudable that the ToS are easily readable and take only ~ 8 pages :clap: 

Regarding the content itself, I think it is fine, however there are some points I would like to have clarified (preferebly in the ToS itself) or I have comments about:

- In §2.1 you already mention “Teams” without defining them before. Later the ToS lay out how to estabilish a team, but do not explicitly define a Team. While it may be implicitly understood what it is, having an explicit definition would be good. If I understand §2.2 correctly, even one member is enough to constitute a Team. Also, it would be useful to explicitly define what the relationship between “You” and “Team” is.
- Is the primary aim of §5.3 to idemnify Gratipay or to hold Team Owners liable? The first part of the paragraph reads as if it is about idemnification of Gratipay, but the last sentence seems quite strongly to push the liability onto the Team Owner.
- Personally, I find using CC0 for Gratipay.com in §6.1 as a really nice touch and a fresh approach. I take it you do understand the implications of this, though.
- Staying on the topic of copyright, in §7.1 the copyright license that Participant grants to Gratipay is relatively broad to what Gratipay actiually needs at the time. While §7.2 clarifies what this license permits Gratipay to do, I would welcome a provision where it explicitly stated for which purposes Gratipay may use it.
- If I understand §4.3 correctly in connection with §8.1(2), it is not allowed to fund something like [LOIC][loic] through Gratipay. (I’m just checking, not complaning.)
- The wording of §10.1 “subject to certain state laws” seems to be ambiguous whether an NPO (e.g. KDE e.V. or GNOME Foundation) would need to comply with laws concerning charitable solicitations in their own jurisdiction or State of Pennsylvania.
- Regarding the “without notice to you” provisions in §11.4 and §12.1, I would **very** much like to be informed of it, just as under §17.2.
- On that topic, it would be really nice if you could add a possibility for community involvement in the process of changing the ToS & PP, similar to the one in §4.5 (when a Team is being estabilshed).

Other than that, regarding content I have nothing to complain about. It looks pretty good to me :smile_cat: 

As for the form, I very warmly recommend to read (and apply) [the suggestions in this short blog post][nice] on how to make HTML legal documents (such as the [MPL][mpl]) look nice. I especially agree with the “no all caps” rule – no-one reads all caps paragraphs, so they are not emphesised, but hidden by it. :stuck_out_tongue_closed_eyes: 

Well, I hope this does not sound too grave. Non of there seem to me as deal-breakers, but it would still be nice to work on it, if possible.

[loic]: https://en.wikipedia.org/wiki/Low_Orbit_Ion_Cannon
[nice]: http://lu.is/blog/2011/08/22/making-html-legal-documents-like-mpl-look-good/
[mpl]: https://www.mozilla.org/MPL/2.0/

**Comment by rohitpaulk** [comment]
> Copying the source of the comment, so the links and markup work as well. (Sorry for the duplication)

Perfect, I've deleted my previous comment.

**Comment by whit537** [comment]
This has been plowed into https://github.com/gratipay/gratipay.com/pull/4117#issuecomment-262336157.
