### ISSUE TITLE
Missing service in "See Also" page

### ISSUE THREAD

**Issue by gamedevsam** [gratipay/inside.gratipay.com#205]
Just found out about this (unapologetically libertarian) service. Keep working out the kinks, it'll be worth it in the long run. Please check out this service and add it to the "See Also" page:

https://assembly.com/

Cheers!

**Comment by whit537** [comment]
Good catch, @gamedevsam. We've known about Assembly for a while, they definitely belong on See Also. @rohitpaulk has done some work on Assembly, he [shared his experience](https://botbot.me/freenode/gratipay/2015-02-19/?msg=32363111&page=1) a couple months ago.

**Comment by whit537** [comment]
I believe I first heard about Assembly from @jkwade, ftr.
