### ISSUE TITLE
GCUC

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#207]
http://www.shareable.net/blog/the-original-spirit-of-coworking-still-alive-at-gcuc-2015-conference

**Comment by whit537** [comment]
http://gcuc.co/

**Comment by whit537** [comment]
Not quite where I want to be. If anyone else wants to go and rep Gratipay ([Toronto in September](http://canada.gcuc.co/)—@patcon? :) ), go ahead and reopen.

**Comment by patcon** [comment]
Thanks for thinking of me @whit537, but I'm in SF for a bit as of this week :)

**Comment by whit537** [comment]
:heart: @patcon :-)
