### ISSUE TITLE
mcdonc / Agendaless

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#208]
Picking up from https://github.com/gratipay/gratipay.com/issues/3446#issuecomment-104002248 ...

**Comment by whit537** [comment]
>Actually, now that I think of it, it's a lot more useful to me to receive payments to my personal account so I don't have to wait for Agendaless to cut me a check; this feature has saved my bacon a number of times when things got tight. I could create an Agendaless account, but it'd be tied to my own personal account, which might be a little shady. Thoughts?

@mcdonc I think we can find a way to make this work.

The goal with Gratipay Teams is to encourage growth and sharing of both work and revenue: if you end up with a great contributor that helps a lot with your projects, how can we deal them into the revenue stream that your projects are generating? If someone does some marketing and sales for your projects to increase revenue, how can we deal them in as well?

We want to see lots of little businesses spring up around open source (open work).

We're not going to have it done for this week, but we have a Payroll feature [on deck](https://github.com/gratipay/gratipay.com/issues/3450) that's designed to distribute Gratipay revenue to a team "owner" and zero or more "members."

#### Proposal: Agendaless

Once we have Payroll, this would be the full-fledged way to structure your situation on Gratipay 2.0:

 - an `~Agendaless` user
 - an `Agendaless` team, owned by `~Agendaless`
 - a `~mcdonc` user that is a member of the `Agendaless` team
 - `~mcdonc` takes a certain amount/percentage from `Agendaless`, and the rest goes to `~Agendaless`

(Note that only `Teams` can receive money, but only `~users` can withdraw money.)

With the Payroll feature, you would indeed receive payments directly to your bank account. Agendaless would then account for this as income to Agendaless and payments to you.

Now, as low-hanging fruit, you could start with this setup:

 - an `Agendaless` team on Gratipay that is owned by `~mcdonc`
 - `~mcdonc` receives all the money that comes in to `Agendaless`

Agendaless would account for this the same way as the more evolved setup (with the `~Agendaless` user) as income to Agendaless and payments to you. It'd be up to you and Agendaless to decide if you're comfortable with this. From Gratipay's point of view it'd be fine for now, provided that it evolves into the full-fledged setup described above.

#### Alternative 1: mcdonc, Inc.

You *could* go with:

 - a `mcdonc, Inc` team on Gratipay that is owned by `~mcdonc`
 - `~mcdonc` receives all the money that comes in to `mcdonc, Inc.`

However, that basically makes you a sole proprietor, personally responsible for any payroll accounting issues associated with bringing others onto the team. I imagine you'd rather offload that responsibility. :-)

#### Alternative 2: Pylons/Pyramid

Another way to approach this would be decide that your tips so far have been mostly for Pyramid (let's say), and migrate to ... maybe a `PylonsProject` team? Something like this:

 - a `~PylonsProject` user
 - a `Pyramid` team, owned by `~PylonsProject`
 - a `~mcdonc` user that is a member of the `Pyramid` team
 - `~mcdonc` takes a certain amount/percentage from `Pyramid`, @bbangert takes some, etc. and whatever is left drains to `~PylonsProject`

Does this give you an idea of how we're trying to shape things over here? Can you work with this, @mcdonc?

**Comment by mcdonc** [comment]
Thanks a lot for thinking about this @whit537 .  I'll ponder it a bit.

**Comment by stevepiercy** [comment]
I like the Alternative 2: Pylons/Pyramid approach.

I have some follow up questions.
1. What would happen if the Owner of Team leaves the team (death, prison, boredom)?
1. How can a Team Member who is not yet a Team Owner become a Team Owner?
1. Should there be more than one user in the role of Team Owner?
  1. If so, then how would payouts be split amongst users in the role of Team Owners?

**Comment by mcdonc** [comment]
I'm also leaning that way FWIW (the Pylons/Pyramid approach).  Thanks for the help!

**Comment by whit537** [comment]
https://gratipay.freshdesk.com/helpdesk/tickets/2262

**Comment by whit537** [comment]
@stevepiercy Right now the schema is one owner per team (there's [an `owner` column](https://github.com/gratipay/gratipay.com/blob/1855/sql/schema.sql#L414-L415) in the `teams` table). Worst case, we can manually `update teams set owner='newowner' where slug='pylonsamid'` (I actually just did this for another team). Probably we'll at least make this operation available in an admin UI in the future. Really I don't see a reason it can't be a user-facing UI.

Anyway, the current recommendation would be:

 1. Sign up for Gratipay using the [Pylons](https://twitter.com/pylons) Twitter account. Gratipay access then becomes a function of Twitter access, and you have to worry about Twitter succession anyway in the bored-to-death-in-prison case, so you get both birds for the price of one.
 1. While signed into Gratipay as your new ~Pylons user, [apply for a new team](https://gratipay.com/new). The ~Pylons user will be the owner of the team.
 1. Once the team is approved, add your individual Gratipay user accounts (~mcdonc, ~stevepiercy, ~benbangert, etc.) as "members" of the team. You'll each be able to take some of the money, and the rest will go into the PayPal or bank account linked to ~Pylons to be used for hosting, etc.

One major caveat: step (3) depends on us [bringing back the payroll](https://github.com/gratipay/gratipay.com/issues/3433) feature. Sorry. :-(

Other than that, is this a workable solution?

**Comment by tshepang** [comment]
Nice prison joke there @whit537

**Comment by stevepiercy** [comment]
@whit537 thank you. A user-facing UI for this feature would be good.

I think the current recommendation is workable.

We will need to work out the Pylons Twitter account access.

@mcdonc I don't know whether the Pylons Project actually has a bank account. We might want to set up a business bank account with a credit union, or one person could use their own bank account (I just did the latter for a small project [Knop](https://github.com/knop-project/knop)). Setting up a business bank account has a lot more paperwork and organizational work, too.

**Comment by whit537** [comment]
@tshepang :-)

@stevepiercy Cool. I've reticketed enabling teams to change ownership as https://github.com/gratipay/gratipay.com/issues/3515.

**Comment by stevepiercy** [comment]
FWIW, for my tiny project [Knop](https://github.com/knop-project/knop), the issue of assuming responsibility for taxes and legal matters as noted in the new [terms section 5.iii](https://gratipay.com/about/policies/terms-of-service). is not really an issue until and if it [receives at least $600 per year](http://www.irs.gov/Businesses/Small-Businesses-&-Self-Employed/Reporting-Payments-to-Independent-Contractors). If that time comes, it would be a good problem to have. So until then, I'll accept the following option.

> Now, as low-hanging fruit, you could start with this setup:
> * an Agendaless team on Gratipay that is owned by ~mcdonc
> * ~mcdonc receives all the money that comes in to Agendaless

For the greater projects under, and for the organization, the Pylons Project, that's a whole 'nuther situation.

**Comment by whit537** [comment]
I believe this is resolved in https://github.com/gratipay/team-review/issues/51.
