### ISSUE TITLE
decide how to handle unsubscribe requests

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#235]
We recently sent two email blasts to all of our users, [one](https://github.com/gratipay/gratipay.com/issues/3385#issuecomment-100040443) for the Gratipocalypse  and [another](https://github.com/gratipay/gratipay.com/issues/3510) for Gratipay 2.0/Year Three. We didn't include unsubscribe links in these emails, for at least technical reasons: our unsubscribe infrastructure depends on notification types, and we don't have an appropriate notification type for these messages. We've received some unsubscribe requests:

https://gratipay.freshdesk.com/helpdesk/tickets/2264
https://gratipay.freshdesk.com/helpdesk/tickets/2271
https://gratipay.freshdesk.com/helpdesk/tickets/2275
https://gratipay.freshdesk.com/helpdesk/tickets/2269

How should we handle these requests?

**Comment by whit537** [comment]
I say "*for at least* technical reasons" because it's not clear to me whether the two messages we sent out count as "transactional and relationship messages" according to [CAN-SPAM](http://www.gpo.gov/fdsys/pkg/USCODE-2011-title15/html/USCODE-2011-title15-chap103.htm), which is the law we're under here, enforced by the [FTC](https://www.ftc.gov/tips-advice/business-center/guidance/can-spam-act-compliance-guide-business).

15 U.S.C. § 7702(2)(B):

> The term “commercial electronic mail message” does not include a transactional or relationship message.

15 U.S.C. § 7702(17):

>**(17) Transactional or relationship message**
**(A) In general**
The term “transactional or relationship message” means an electronic mail message the primary purpose of which is—
(i) to facilitate, complete, or confirm a commercial transaction that the recipient has previously agreed to enter into with the sender;
(ii) to provide warranty information, product recall information, or safety or security information with respect to a commercial product or service used or purchased by the recipient;
(iii) to provide—
(I) notification concerning a change in the terms or features of;
(II) notification of a change in the recipient's standing or status with respect to; or
(III) at regular periodic intervals, account balance information or other type of account statement with respect to,
>
a subscription, membership, account, loan, or comparable ongoing commercial relationship involving the ongoing purchase or use by the recipient of products or services offered by the sender;
(iv) to provide information directly related to an employment relationship or related benefit plan in which the recipient is currently involved, participating, or enrolled; or
(v) to deliver goods or services, including product updates or upgrades, that the recipient is entitled to receive under the terms of a transaction that the recipient has previously agreed to enter into with the sender.

**Comment by whit537** [comment]
After reviewing [FTC's FAQ](https://www.ftc.gov/tips-advice/business-center/guidance/can-spam-act-compliance-guide-business), I think we blurred the lines with these two messages. They *could* have been framed in such a way that they were transactional messages, and probably *should* have been ("important change in terms of service"), but instead they were framed more as marketing messages. I propose that we:

 - [ ] Apologize to the people who have asked to unsubscribe: "I'm sorry. We won't send you any more messages like that."
 - [ ] Not send out any more marketing messages until we have a general-purpose mechanism that includes a proper unsubscribe link (https://github.com/gratipay/gratipay.com/issues/2521).
 - [ ] Consider removing the option to turn charge notifications off, since those are clearly transactional.
 - [ ] Consider replacing the unsubscribe link with a notice for global terms notifications: "This is an important transactional or relationship message associated with your Gratipay account. To avoid receiving messages like this in the future, please [close your Gratipay account](https://gratipay.com/about/me/settings/close)." We should only use that option for major terms of service changes&mdash;hopefully not for a while!

**Comment by whit537** [comment]
> We should only use that option for major terms of service changes—hopefully not for a while!

Though, actually: do we want to send out another notification for receivers under Gratipay 1.0 once we're ready to open up team registration generally (i.e., link it on the site)?

**Comment by clone1018** [comment]
One quick note, we could potentially lean on Mandrill to do the heavy
lifting now. Mandrill can automatically append the unsubscribe footer to
our emails and then manage that list for us. They also offer the ability to
export it for later.

**Comment by whit537** [comment]
I've responded to the four users linked in the description.

@clone1018 I considered using Mandrill's blacklist here, but it seems like we want to keep one source of truth here.

**Comment by whit537** [comment]
> Consider removing the option to turn charge notifications off, since those are clearly transactional.

I guess it doesn't hurt to let people opt-out of charge notifications, does it?

**Comment by whit537** [comment]
CAN-SPAM doesn't mean we *can't* let people opt out of transactional messages if we want to.

**Comment by whit537** [comment]
Explaining in the message why there's no unsubscribe reticketed as https://github.com/gratipay/gratipay.com/issues/3516.
