### ISSUE TITLE
Add Glossary page

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#243]
From https://github.com/gratipay/inside.gratipay.com/issues/224#issuecomment-109052351

Probably on http://inside.gratipay.com/appendices/glossary to clarify what all buzzwords are about:
- ACH
- PCI
- CDD - https://github.com/gratipay/inside.gratipay.com/issues/219

This could be split into sections to indicate the value of these terms to GP. It should also include examples related to GP and links to where it is used. Pictures and visuals! There is a clear lack of those.

**Comment by techtonik** [comment]
* AML - https://github.com/gratipay/inside.gratipay.com/issues/119

**Comment by techtonik** [comment]
* Fiscal Sponsorship - https://github.com/gratipay/gratipay.com/issues/3529

**Comment by whit537** [comment]
https://github.com/gratipay/inside.gratipay.com/issues/117#issuecomment-126345440

**Comment by webmaven** [comment]
We need to create an .spt for the glossary to work on the content, even before it is exposed through the web. What's the best place to create it?

**Comment by whit537** [comment]
@webmaven I've stubbed one out in #418:

https://github.com/gratipay/inside.gratipay.com/edit/glossary/www/appendices/glossary.spt

**Comment by webmaven** [comment]
@whit537 :bow:

**Comment by techtonik** [comment]
@webmaven take a look at #418 for some terminology.

**Comment by webmaven** [comment]
@techtonik, thanks for the pointer. I'll see what I can do later today.

And @whit537, thanks also for making that a branch.

**Comment by whit537** [comment]
@webmaven :frog:
