### ISSUE TITLE
Implement 404 testing strategy

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#245]
How do we do 404 testing? It looks like we don't have automation to back this up and run at least monthly.

(if we do have this strategy, this should be put into some entrypoint Maintenance Quests document)

**Comment by techtonik** [comment]
Features creeping:
* [ ] stats on redirects from old 404 pages (needed for fixing old links on the internets)

**Comment by whit537** [comment]
We check for 404s in https://github.com/gratipay/gratipay.com/blob/1855/tests/py/test_pages.py#L19-L58, but I don't believe we do any *external* link checking.

**Comment by whit537** [comment]
You want 404 checking on Inside Gratipay, right?
