### ISSUE TITLE
Learn to use tools of visual communication and teach new people how to do this

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#247]
We need to upgrade our communication ways to visual communication. One person can spend more time to transform information in visual way, like diagram, and it will save time for other people on reading and also keep it fun if there is some art embedded in it.

Sometimes drawing a diagram is faster than describing it in words. Sometimes text description is a must to resolve uncertainties. It all depends on situation, but in general the skill to do a diagram quickly to present some analysis or check the claim, is a must have for any contributor in a modern way. For an example, see https://github.com/gratipay/inside.gratipay.com/issues/244#issuecomment-110123075 and diagram after it.

```
saving time
for readers  -->  less teal deers  -->  less bounce-rate  -->  wider reach  -->  more help
             -->  more hours in a day  -->  more stuff being done  -->  better GP
```

**Comment by techtonik** [comment]
* [ ] add tools and time-savers to inside.gratipay.com/appendices/colophon
* [ ] link to examples of how to use them
* [ ] implement achievements

**Comment by rohitpaulk** [comment]
That's interesting, @techtonik :)

**Comment by techtonik** [comment]
Tool: Blockdiag Online

http://interactive.blockdiag.com/
http://blockdiag.com/en/blockdiag/attributes/node.attributes.html#examples

**Comment by whit537** [comment]
!m @techtonik @tk0miya

Blockdiag is great! See https://github.com/gratipay/inside.gratipay.com/issues/244#issuecomment-110768483. :-)

> need ability to render PNG to clipboard to paste to GitHub from there quickly

I tried using a few online conversion tools, but in the end I ended up just opening the SVG in a new tab (using the "[Download for this diagram(SVG)](http://interactive.blockdiag.com/image?compression=deflate&encoding=base64&src=eJx9Uk1P4zAQvfMrhnAlVRCnqHyoGCpWWqACdtHycTDJKFh1PZHtUBDiv2M7htBNii9xZt6befM8j5KKeSl4BW8bAMlMPJNN4K4gSXo_2cqy3V3Gkm2w-GLb4PJJWHzw4CMuuSqwhKunxpa0VN-IeZ5l64mNEQqNgb_CCOpolUZUw5TfWHEJjFw_rcwXQ2M5jJ_xV01SHn6TNHUnz5OQvhRmDjNNleaLQcygzPQAgkEuGb6wl_aV-VjfmbGvWGlqaqgD1dsNQFqgsty68vs1aau5sOOQ6V4gz52RGyHYdnUykmvkC7MZJHWzjv8DMUlugupeTYqCGmVNH3KJEnkL2hllEIVH4Hsn-jFOlJo4URzgUyZjeT6dxvJDm-GbTaRMhUovFB62hsBqzIOurBY1joeTyZEzSFm3JvfqjOs52lryApM18Bt01qzJnXFVUUj_KPn4179P09p7aywtaik8vv2_Jg0nc3QV3DrORmwUKd3pUVY3sNfALbawwLguwYkUfrFW5u9rOjGFpmV7P8cluIFDO5iyP330hJ36wtTYWPlW1AvnaHz39w9Z-DQV)" link at the bottom of [interactive blockdiag](http://interactive.blockdiag.com/)) and taking a screenshot from there using my OS's normal screenshotting functionality. That works well enough, but [a PNG save straight from blockdiag](https://bitbucket.org/blockdiag/blockdiag_interactive_shell/issue/4/save-as-png) would be nice, too. :)

**Comment by techtonik** [comment]
**Tool**: StoryMap JS and Storyline JS

https://storymap.knightlab.com/
http://timeline.knightlab.com/

**Why?**

We need to tell the story of Gratipay evolution after its birthday. ...

(an attempt to dump my state of mind turned into 2kB story, which I will post into separate issue)

The story is necessary to make it clear how Gratipay, from a service that is open and friendly to all people, became landlocked within US borders and surrounded by spikes, shields, landmines and protective gear.

We will also need some a few maps showing where Gratipay is active and what transfers are possible. I have a vision how it looks like, but don't have skills to share. =)

**Comment by whit537** [comment]
> Sometimes drawing a diagram is faster than describing it in words.

Did you appreciate https://github.com/gratipay/inside.gratipay.com/issues/119#issuecomment-107081615? :)

> The story is necessary to make it clear how Gratipay, from a service that is open and friendly to all people, became landlocked within US borders and surrounded by spikes, shields, landmines and protective gear.

I would tell a counter-narrative, about how Gratipay established itself as a legitimate participant within the global financial and legal system while preserving it's open and friendly soul, thereby introducing a seed of true change into the host system.

**Comment by whit537** [comment]
What are the action items left to close this, @techtonik?

**Comment by whit537** [comment]
What are the action items left to close this, @techtonik?

**Comment by whit537** [comment]
Hearing none ...
