### ISSUE TITLE
onboard @kzisme

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#253]
Got a first PR from @kzisme at https://github.com/gratipay/gratipay.com/pull/3559.

@kzisme Here's a ticket to help you get onboarded. Any random questions you have about contributing to Gratipay, feel free to ask them here. How can we help you contribute more?

**Comment by kzisme** [comment]
Is there anything specific that needs done that could be considered entry level?

**Comment by whit537** [comment]
> Is there anything specific that needs done that could be considered entry level?

@kzisme We have several email notifications we want to start sending out. https://github.com/gratipay/gratipay.com/issues/3526 is probably the easiest to start with. Look good?

>Also - as I go through older issues that are still open should I drop a comment if they should be closed if they haven't been just yet?

Yes, please!

**Comment by whit537** [comment]
@kzisme May I add you as a collaborator on GitHub? That will allow you to create topic branches in our main repo, as well as work with labels on issues.

**Comment by kzisme** [comment]
@whit537 My goal is to try to address at least one issue/day, so we'll see how that shapes up.  If you have any other suggestions and such don't hesitate to let me know.  

Also I'll drop a line here if I have any other questions :)

**Comment by kzisme** [comment]
@whit537 You're more than welcome to.  I've been reading more about Gratipay as well - does an mailing list currently exist?

**Comment by whit537** [comment]
> You're more than welcome to.

Awesome, thanks! Invite sent. :)

Once we [bring back our payroll feature](https://github.com/gratipay/gratipay.com/issues/3433) we can add you there as well.

> I've been reading more about Gratipay as well - does an mailing list currently exist?

You mean an internal development mailing list? Naw, we just use GitHub. :-)

Here's the [documentation for our communication channels](http://inside.gratipay.com/appendices/channels).

> Also I'll drop a line here if I have any other questions :)

Perfect. We can close this once you have a couple good PRs under your belt.

BTW, have you been able to set up a local Gratipay dev environment?

**Comment by kzisme** [comment]
>have you been able to set up a local Gratipay dev environment?

I haven't had time to do that just yet - I'll try to do that tonight.  Thus far, I've been reading about the dependencies and such.  

>You mean an internal development mailing list? Naw, we just use GitHub. :-)

Well, I'm just happy to see some activity!  I hope I can offer some sort of help and learn a bit :)

**Comment by whit537** [comment]
> Thus far, I've been reading about the dependencies and such.

The heaviest dependency is Postgres. What OS are you using?

**Comment by kzisme** [comment]
Currently, Windows 7/8 (depending on machine)

**Comment by whit537** [comment]
Okay, iirc in the past I've had good luck with [these Postgres installers](http://www.enterprisedb.com/products-services-training/pgdownload#windows) on Windows. We're on 9.3 in production.

**Comment by kzisme** [comment]
@whit537 I'll spend my spare time during the day today playing catch-up on docs and where Gratipay currently stands.  There seems to be a lot going on with #3399 and I'm reading through all that trying to get an understanding.  

It's a lot to take in + looking at code :package: 

Oh - I'll check that installer out!  Thanks for the link, I'm considering buy a new dev machine in the near future as well :)

**Comment by whit537** [comment]
Yeah, #3399 is big right now. Check [the Radar](https://github.com/gratipay/inside.gratipay.com/labels/Radar) for current status.

**Comment by kzisme** [comment]
Sifting through #3399 and the Radar for now - I suppose I'll add what I can without getting in the way :+1:

**Comment by kzisme** [comment]
@whit537 I got Postgres installed and working last night - I suppose the next challenge for me is getting Make/gcc toolchain running so that I can build the project.

**Comment by whit537** [comment]
@kzisme We don't have a good Windows development story right now, I'm afraid. @techtonik has been working on a Vagrant-based solution (want to give us a status update on that, @techtonik?). If you're installing directly into Windows I think it'd make more sense to try to install pre-compiled binaries of our Python dependencies that have C extensions (e.g., psycopg2) rather than trying to build them yourself. Also, I'm not sure of the state of Aspen on Windows; over on https://github.com/gratipay/aspen-python/issues/442 we're looking at implementing continuous integration for Aspen, after which we should do the same for Gratipay.

**Comment by kzisme** [comment]
Yeah I'm not surprised - Windows always makes building any project a hassle.  

>install pre-compiled binaries of our Python dependencies that have C extensions

I suppose I'll look into how to do this today 

Also, if you dont mind me asking  what sort of dev environment/OS do you use?

**Comment by whit537** [comment]
Personally? I'm on Mac OS.

**Comment by whit537** [comment]
> Windows always makes building any project a hassle.

But it's ubiquitous, cheap, and easy. :)

**Comment by kzisme** [comment]
>But it's ubiquitous, cheap, and easy. :)
 As long as it's possible to get it working :-P

**Comment by rohitpaulk** [comment]
@kzisme - If you're okay with running an Ubuntu VM within Windows, run [this script](https://github.com/gratipay/gratipay.com/blob/master/scripts/bootstrap-debian.sh) on a fresh image, followed by `make run` and you should be ready to go :dancer:

**Comment by kzisme** [comment]
@rohitpaulk That's a pretty quick way to get up and running!  I'll take a look at setting up a VM today :smiley:

**Comment by whit537** [comment]
!m @rohitpaulk @kzisme

**Comment by kzisme** [comment]
@whit537 Just starting to get a VM up and running - I'm curious though....What market is Gratipay focused on?  More on the individual or a team?  

Just been reading and thinking a lot :smirk:  I've been keeping up with all that's been happening as well.  Great progress in the past week even :D

**Comment by whit537** [comment]
@kzisme Good question! We recently pivoted to focus more on teams. The ticket for the pivot is, serendipitously, #180! :dancer:

**Comment by kzisme** [comment]
@whit537 Do you know how most people find out about Gratipay?  I've been looking around at our competitors, and I was surprised to find out where some of them have found business (or users).  

One of the things I have been thinking about is trying to market Gratipay towards individuals/teams for Twitch channels.  I saw Patreon does the same, but reaching - or at least making our presence(or impending presence with 2.0) known to individuals/teams.  

The reason these users would possibly be interested in something like Gratipay is because they either 
1.  They haven't passed the threshold of followers to generate funds from viewers 
2. Haven't found sponsorship from a company, but have a decently sized following

Just throwing ideas around :smile_cat:

**Comment by kzisme** [comment]
@whit537 What email is it best to reach you at for other questions?  I have a few random ones I'd like to bounce off of you - if you don't mind :D

**Comment by whit537** [comment]
chad@zetaweb.com—I'll probably bounce them back to public channels, though. ;-)

**Comment by kzisme** [comment]
That's fine :) they would probably be useful to others as well. I know most
of your policies for transparency and openness - I'll shoot you an email
today

**Comment by techtonik** [comment]
About Vagrant status on Windows and testing.

Well, last time I checked **Vagrant worked ok**. The last issue fixed was https://github.com/gratipay/gratipay.com/issues/3000 After which I was not not able to run the JavaScript tests, but it appeared common problem for all setups https://github.com/gratipay/gratipay.com/issues/3069

So, run:
```
vagrant up
```
and it should be fine.

I myself abandoned Vagrant, because it was extremely slow on my Vista 32, and recent updates killed my custom hack for memory expansion back from 8Gb to 3Gb. =/

Right now **I am testing GP on Windows completely from online IDE's**. [CodeEnvy](https://codenvy.com) was good and truly inspirational. It looks like complete Cloud IDE, but there was problems to get Dockerfile correctly, and the way it shows logs also appeared to be limited for me. So I switched to [Koding](https://koding.com/R/techtonik), which is more like web based terminal with tabs, editor and full fledged Ubuntu. I really like the simplicity of the interface.

Also, if you want to try Koding, the link above is a referral like, which gives something like 500Mb of space to both you and me on sign in. But the default space is quite ok - `Usage 1.77 GB of 2.82 GB` for https://inside.gratipay.com/

**Comment by kzisme** [comment]
Sent you an email :)

**Comment by whit537** [comment]
Yeah, I started writing you a reply but it started turning into a blog post, and I figured I should prioritize #3567. :)

**Comment by whit537** [comment]
https://github.com/gratipay/gratipay.com/issues/3567, that is. ;-)

**Comment by kzisme** [comment]
@whit537 no worries at your leisure :) #3567 has been busy today

**Comment by kzisme** [comment]
@whit537 I've come up with a few more questions I'll send your way. At your leisure :)

**Comment by whit537** [comment]
@kzisme I've been sitting for a while on your email about getting involved in open-source, and learning and contributing more. I think the easiest way to answer would be in person. You're in Akron, right? What's your schedule like during the week? Want to co-work for a day in Youngstown? I know a great coffee shop there. How about Thursday the 16th or 23rd?

**Comment by whit537** [comment]
> I'm also curious if you've ever worked on a chrome extension of any kind :)

@kzisme Not to speak of. We do have https://github.com/gratipay/gratipay-everywhere and it needs a maintainer. Want to take it over? :-)

**Comment by kzisme** [comment]
Currently I'm interning in Strongsville, Ohio 8-5 M-F.  This should lessen in August when the school year begins, but then I being classes at the end of August.  I'm be fine with co-working for a day when we figure out what works :D

**Comment by kzisme** [comment]
@whit537 I'd be interested in taking it over - as long as I'm capable (I still have just been reading about how extensions work).  

My main concern with finding work before/after graduation is just making sure I know enough/am capable of - doing entry level -> Junior level work o.O

**Comment by whit537** [comment]
Learn to [ask good questions](http://www.catb.org/esr/faqs/smart-questions.html).

Write a lot of code.

Read other people's code.

Try lots of stuff because there's no substitute for experience.

Design from the outside in. Build from the inside out.

Data structures are more important than algorithms. Get the data structures right and the algorithms write themselves.

[Don't make fun of people for admitting they don't know things](http://xkcd.com/1053/). Don't be afraid to admit you don't know things.

ESR's doc is limited: it only covers online interaction, and it's too gruff. In face-to-face conversation the rules are different. Learn to ask "What's that?" when someone mentions something you don't know about. Google is a crutch for non-face-to-face contexts. You'll always learn more from a knowledgeable person than you will from Google, because you can only get *social* context from people.

When you're stumped by a hard bug, try Science Lite™:

1. State the problem.
1. Collect facts.
1. State a hypothesis.
1. Design a test.
1. Perform the test.
1. Repeat as necessary.

Live-blog bugs on GitHub tickets. Discipline yourself, don't get distracted.

Form good habits!

**Comment by kzisme** [comment]
@whit537 I've read that ask good questions link before!  It's a great resource.  

For me, the hardest part for most projects/jobs/whatever is getting started and finding direction.  I've been reading and thinking about how the chrome extension should work and will work, but implementing it.  

Currently I've just being trying to dedicate more time to writing code and reading others (especially in down time at work)

**Comment by whit537** [comment]
> the hardest part for most projects/jobs/whatever is getting started and finding direction

Design from the outside in. Build from the inside out.

"Design from the outside in," means, start with the end-result you want to deliver. So, for example, with the Chrome extension: how do you want it to behave? What do you want the user experience to be? Right now it adds a Gratipay link on a couple sites (GitHub, Twitter). Does it behave the way we want? Why or why not? Start with the user experience. If you're not the user, then find users to talk to.

User needs should be where you find direction. It's also helpful to talk to others on the project to come up with requirements together.

**Comment by kzisme** [comment]
Hmm that's a good way to think about it.  The other extension I want to create is just a tagging system for posts - the technical side is what I'm struggling with on that project.

**Comment by whit537** [comment]
Live-blogging your requirements gathering is also a good practice, even if no-one else is explicitly talking with you. If the rest of us can see your thought process, then we can jump in with an idea or suggestion.

**Comment by whit537** [comment]
By "live-blogging" I mean making a GitHub ticket and dumping a stream of consciousness there.

**Comment by kzisme** [comment]
Do these methods generally work for the technical side of things as well?

**Comment by whit537** [comment]
I definitely use the live-blogging approach for technical challenges. Doing so forces me to put some thought into the questions I'm asking. "What technology do I need to learn? What APIs are available? What have other people done that is similar and I can learn from or borrow? Given what's readily available, how should I design the solution to my problem?" Etc.

**Comment by whit537** [comment]
This also helps keep me on track, because when I find myself off in the weeds I can scroll back up and be like, "No, where was I again?" and get back on track.

**Comment by kzisme** [comment]
Alright!  Thanks for the tips thus far - I enjoy asking questions and conversing about software, and especially other people's experiences.  

If you think I'm up to working on the extension I'd be fine with trying something.  It would be a good catalyst to starting my own small project as well.  I have a few projects I would like to work on in my spare time too...just haven't started them (though I've thought a lot about them)

**Comment by whit537** [comment]
> If you think I'm up to working on the extension I'd be fine with trying something.

@kzisme Cool. Two starting points in gratipay-everywhere: You could fix https://github.com/gratipay/gratipay-everywhere/issues/34, and/or review https://github.com/gratipay/gratipay-everywhere/pull/29.

**Comment by kzisme** [comment]
Alright I'll try to take a look tonight :dancer:

**Comment by whit537** [comment]
Seems like you're off and running, @kzisme. Welcome aboard! :-)

**Comment by whit537** [comment]
Reopening to help @kzisme get a PR under his belt.

Waddya say, @kzisme? Can you remind me: do you have Gratipay.com installed locally? That's the first step ...

**Comment by kzisme** [comment]
@whit537 So any tasks you would like me to look at?  

I'm on winter break now as well, so I can put some more time towards this (depends on work schedule)

I do not currently on my Mac - I'll try to do that now.

**Comment by kzisme** [comment]
@whit537 Currently cloning the repo - and installed progresql with brew

**Comment by whit537** [comment]
> I'm on winter break now as well, so I can put some more time towards this (depends on work schedule)

Awesome!

> I do not currently on my Mac - I'll try to do that now.

Cool. Ping here if you get stuck.

> So any tasks you would like me to look at?

There are a few tickets about inefficiencies in the admin experience on the site ... low priority overall but fairly straightforward, and maybe a low-pressure place to start. Wanna pick one of these?

https://github.com/gratipay/gratipay.com/issues/3879
https://github.com/gratipay/gratipay.com/issues/3845
https://github.com/gratipay/gratipay.com/issues/3548
https://github.com/gratipay/gratipay.com/issues/3121

**Comment by whit537** [comment]
> Currently cloning the repo - and installed progresql with brew

Cool. If you find any snags with brew-installed postgres let's make sure we note them in the README if needed, m'kay?

Signing off for tonight ...

!m @kzisme :dancer:

**Comment by kzisme** [comment]
Currently - I cloned the repo, created a virtualenv, and installed postgres without a hitch.

Although I'm currently getting this error when following the local quick start.

```
[kevinzita@Godric~/projects/gratipay.com$] sudo -u postgres createuser --superuser $USER
sudo: unknown user: postgres
[kevinzita@Godric~/projects/gratipay.com$] sudo postgres createuser --superuser $USER
"root" execution of the PostgreSQL server is not permitted.
The server must be started under an unprivileged user ID to prevent
possible system security compromise.  See the documentation for
more information on how to properly start the server.
[kevinzita@Godric~/projects/gratipay.com$] 

```

So I suppose after this step I have to run ``createdb gratipay`` and then fill the db with fake data based on the schema.  

First time messing with postgresql

**Comment by whit537** [comment]
Okay ... you need to figure out how `brew`-installed Postgres sets up permissions and user accounts, and then either adapt the README instructions to whatever your Postgres is already configured for, or modify your Postgres permissions to conform to what the README expects. Does that give you enough to go on?

**Comment by kzisme** [comment]
Hopefully I'll take a look when I get off work this evening. I was just following the quick start guide last night

**Comment by kzisme** [comment]
@whit537 brew installed 9.4.5 postgres.  Which instructions are you referring to?  I'm looking at the ["Local Database Setup"](https://github.com/gratipay/gratipay.com#local-database-setup) area in README.  

So, currently I'm confused and stuck since I'm not sure which permissions are expected.

**Comment by rohitpaulk** [comment]
@kzisme - What happens when you run just `postgres createuser --superuser $USER` without `sudo`?

Hop on IRC if you're free and we'll try to get this sorted out together :)

**Comment by rohitpaulk** [comment]
From http://exponential.io/blog/2015/02/21/install-postgresql-on-mac-os-x-via-brew/, it looks like brew creates a user by default using the logged in user's name (kevinzita, in your case), so you might be able to skip the `createuser` step..

**Comment by kzisme** [comment]
I'll check tomorrow! I work until 3pm then I'll try again. What channels do
you frequent?

I appreciate the help!

**Comment by rohitpaulk** [comment]
> What channels do you frequent?

Just [#gratipay](https://botbot.me/freenode/gratipay/) :)

**Comment by kzisme** [comment]
Alright! I'll be in there tomorrow afternoon.

**Comment by kzisme** [comment]
@rohitpaulk  I'm online now!

**Comment by kzisme** [comment]
Also running ``postgres createuser --superuser $USER``

returns

``postgres: invalid argument: "createuser"``

**Comment by rohitpaulk** [comment]
@kzisme - Try just `createuser --superuser $USER` (without the `postgres`)?

**Comment by kzisme** [comment]
```
 createuser: could not connect to database postgres: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```

**Comment by kzisme** [comment]
```
The files belonging to this database system will be owned by user "kevinzita".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

initdb: directory "/usr/local/var/postgres" exists but is not empty
If you want to create a new database system, either remove or empty
the directory "/usr/local/var/postgres" or run initdb
with an argument other than "/usr/local/var/postgres".
```

**Comment by kzisme** [comment]
<img width="1280" alt="screen shot 2015-12-20 at 16 27 31" src="https://cloud.githubusercontent.com/assets/3493562/11920216/9b450622-a736-11e5-8057-b3f65e7c7c0b.png">

Success!  !m @rohitpaulk and @whit537 for hanging in there through my questions!

**Comment by rohitpaulk** [comment]
Aha, we're close

**Comment by rohitpaulk** [comment]
> pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start

**Comment by rohitpaulk** [comment]
Perfect :)

**Comment by kzisme** [comment]
After running the provided commands - make test and make run worked.  

Any other tips about stopping the service or general things I might run into @rohitpaulk?

I gotta run some errands ,but I'll look at it soon.

**Comment by whit537** [comment]
Nice! :dancer: 
!m @kzisme @rohitpaulk

**Comment by kzisme** [comment]
@whit537 Should I have (or do I have to) request access to fresh desk?

**Comment by rohitpaulk** [comment]
> how do I access the admin panel within my local Gratipay account

Set `is_admin` on your local user to `true`. You can do this by running a SQL query via the postgres console (`$ psql -d gratipay`). Does that help?

**Comment by kzisme** [comment]
Alright just going to update with some progress - Postgres seems super cool BUT it's the first cli db system I've used (My db design course used MSSQL)

```
[kevinzita@Godric~/projects/gratipay.com$] psql -d gratipay
psql (9.4.5)
Type "help" for help.

gratipay=# SELECT table_name
gratipay-#   FROM information_schema.tables
gratipay-#  WHERE table_schema='public'
gratipay-#    AND table_type='BASE TABLE';
      table_name      
----------------------
 elsewhere
 tips
 exchange_routes
 transfers
 exchanges
 absorptions
 paydays
 communities
 community_members
 statements
 takes
 events
 emails
 email_queue
 balances_at
 participants
 payroll
 payments
 payment_instructions
 teams
(20 rows)
```

Alright - so it appears I have to add my local user after querying the ``participants`` table.  

Currently looking for a way to get Postgres to properly align everything after I submit a query...
(Still looking)

So I am currently signed in via Github (locally), but I am not listed as a participant - must I add myself via Postgres Query - or since I signed in will (or should I have been added)

**Comment by mattbk** [comment]
If you signed in with Github, you should be in the participants table. Wish I could help with Postgres, but I downloaded a GUI (Mac) to help visualize the database.

**Comment by kzisme** [comment]
@mattbk Which GUI Client did you (or do you) use?

**Comment by rohitpaulk** [comment]
@kzisme - I've used http://www.sequelpro.com/ on the Mac

**Comment by mattbk** [comment]
I use https://eggerapps.at/postico/ for the little that I do in the db.

**Comment by kzisme** [comment]
@rohitpaulk Are you able to hop on IRC for a bit?

**Comment by kzisme** [comment]
Update:

So - I tried Sequelpro - looked into it further and it seems that it's only meant for MySQL.

Took another crack at the cli console and found my username by doing the following:

```
gratipay=# SELECT * FROM participants WHERE username = kzisme;
ERROR:  column "kzisme" does not exist
LINE 1: SELECT * FROM participants WHERE username = kzisme;
                                                    ^
gratipay=# SELECT * FROM participants WHERE id = 101;
-[ RECORD 1 ]----------+------------------------------------------------------
username               | kzisme
session_token          | 6ccbc715f24440c0aa63206f04990419
session_expires        | 2015-12-22 10:54:42.374986+00
ctime                  | 2015-12-21 02:47:55.266991+00
claimed_time           | 2015-12-21 02:47:55.276749+00
is_admin               | f
balance                | 0.00
anonymous_giving       | f
balanced_customer_href | 
is_suspicious          | 
id                     | 101
username_lower         | kzisme
api_key                | 
avatar_url             | https://avatars.githubusercontent.com/u/3493562?s=160
is_closed              | f
giving                 | 0.00
taking                 | 0.00
is_free_rider          | 
email_address          | 
email_lang             | 
is_searchable          | t
old_auth_usage         | 
notifications          | {}
notify_charge          | 3
braintree_customer_id  | 
ngiving_to             | 0
ntaking_from           | 0
status_of_1_0_payout   | completed
```

**Comment by rohitpaulk** [comment]
> looked into it further and it seems that it's only meant for MySQL

Whoopsy, sorry about that :) We use MySQL at work, hence the confusion

**Comment by rohitpaulk** [comment]
> SELECT * FROM participants WHERE username = kzisme;

You'll need single quotes around `kzisme`

**Comment by kzisme** [comment]
Ah, is that why it was searching for columns instead of rows? I figured it was something small like that :)

**Comment by rohitpaulk** [comment]
I used to use double quotes instead of single quotes and get the same error... Turns out that a single quote is used for a string constant, but double quotes are used for identifiers.

From http://www.postgresql.org/docs/9.4/static/sql-syntax-lexical.html:

> A string constant in SQL is an arbitrary sequence of characters bounded by single quotes ('), for example 'This is a string'. To include a single-quote character within a string constant, write two adjacent single quotes, e.g., 'Dianne''s horse'. Note that this is not the same as a double-quote character (").

> There is a second kind of identifier: the delimited identifier or quoted identifier. It is formed by enclosing an arbitrary sequence of characters in double-quotes ("). A delimited identifier is always an identifier, never a key word. So "select" could be used to refer to a column or table named "select", whereas an unquoted select would be taken as a key word and would therefore provoke a parse error when used where a table or column name is expected. The example can be written with quoted identifiers like this:

**Comment by kzisme** [comment]
Awesome!  I've began looking at #3548 and have pinged you there :dancer:

**Comment by rohitpaulk** [comment]
!m @kzisme

**Comment by whit537** [comment]
@kzisme Seems like you're as onboarded as you're gonna be for now, eh? :-)

**Comment by kzisme** [comment]
@whit537 I would have to agree :)
