### ISSUE TITLE
notify former receivers of new terms of service

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#254]
We emailed people about the Gratipocalypse and Gratipay 2.0. However, we didn't do the best job of communicating just how drastic the changes were. Some users have gotten the impression that we just stopped processing payments for one week, and that payments would resume without them having to do anything ([e.g.](https://gratipay.freshdesk.com/helpdesk/tickets/2243)). In fact, we stopped processing payments entirely, and users have to sign up all over again to start receiving payments again.

I don't think we should email blast our entire user base again (see #235), but I *do* think it could make sense to email only people who were receiving on Gratipay 1.0, with a clear message about the fact that we've stopped processing payments, we're not collecting any more money for them, and they need to apply if they want to keep using Gratipay.

**Comment by techtonik** [comment]
> with a clear message

For me that's the major issue. Explaining why in a few words.

**Comment by techtonik** [comment]
Can we have a short one line answers to those?

> we stopped processing payments entirely

Why?

> users have to sign up all over again to start receiving payments again

Why?

> we're not collecting any more money for them

Why?

>  they need to apply if they want to keep using Gratipay

Why?
What changed?
What was wrong before?

**Comment by kzisme** [comment]
From a relatively new perspective about what/how/when/why Gratipay operates - I feel as though sending out an email to current users would be the best option, and (since I think we're moving towards supporting open companies as well now) reaching out to open companies about the upcoming 2.0

Just my two cents :sunglasses:

**Comment by whit537** [comment]
Let's do this once we have [Gratipay 2.1](https://github.com/gratipay/gratipay.com/issues/3399#issuecomment-112110512).

**Comment by webmaven** [comment]
It would likely be helpful if the [gratipay](/gratipay/gratipay.com) and [inside.gratipay.com](/gratipay/inside.gratipay.com) repos were to have 2.1 milestones.

**Comment by whit537** [comment]
Closing. See https://github.com/gratipay/inside.gratipay.com/issues/380.
