### ISSUE TITLE
partner with Aristotle (Integrity product line)

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#259]
Reticketed from https://github.com/gratipay/gratipay.com/issues/2449.

**Comment by whit537** [comment]
To: integritysales@aristotle.com

> Greetings!
>
I'm interested in your Integrity: ID-Direct product. Could we set up a call to discuss?
>
Thanks.

From: Aristotle

> Sure what times work well for you this week?

To: Aristotle

> Thanks, []. How about Wednesday or Thursday at 10am US/Eastern?

From: Aristotle

> How about 10AM EDT Thursday?
>
That works for me.  Do you want me to call you?

To: Aristotle

>Sounds good, []. You can call me on my cell, 412-925-4220.
>
Thanks! :-)

**Comment by whit537** [comment]
~30 minute call with rep. They bring in 40% of their revenue from US, 60% internationally. They think in terms of population coverage by country. Some examples:

 - Australia—"We do Australia for Western Union"
 - Central Europe—"We perform very well, except for Greece (due to transliteration issues)."
 - Singapore—"Strong," "50% of the people electronically"
 - Russia—40-45% (Cyrillic transliteration issues)
 - India, China—Some presence. 30M records in India (2%)
 - Indonesia, Malaysia—weak

They only charge for positive matches.

Three products:

 1. **idv**—we give them name, address, dob, NIN, they return a result. Some base global coverage and then "supplemental gateways" that have to be "turned on" individually.
 2. **manual**—we give them a document scan, they return info ("We might have an iframe, most use our API"). A team of agents in Salt Lake City reviews compliance queues 24/7.
 3. **face to face**—Someone in Bulgaria or Pakistan (high-risk) can Skype with someone in Salt Lake City to prove their identity.

(1) is $1.99 per check (no difference between US and non-US. No monthly minimum or setup fee. Can prepay $5,000 or $10,000 for lower rates.

(2) and (3) seem to priced together: $1,000 monthly minimum, $3.49 for (2) and an extra 50¢ for (3).

**Comment by whit537** [comment]
IDV includes sanction screening (OFAC, PEP, dozen others).

**Comment by whit537** [comment]
"Usually what people do is idv and if that fails escalate to manual."

**Comment by whit537** [comment]
Since we can't afford manual, we could at least do idv. US is what we really need since Zipmark is US-only anyway.

**Comment by rohitpaulk** [comment]
What's NIN?

**Comment by whit537** [comment]
national identity number

**Comment by whit537** [comment]
[MNDA](https://drive.google.com/file/d/0ByDJ5uiG6Hp3bHJaeGQ5ME84d0k/view)

**Comment by whit537** [comment]
To: Aristotle

> Thanks for passing that along. I need a little time to discuss the MNDA with our lawyer. We're actually an open-source company. All our source code is open and as much of our internal discussions, as well. We've only ever dealt with partners that have public API documentation, need to figure out how to proceed here ...

**Comment by whit537** [comment]
This has gone cold. Reopen if ever.
