### ISSUE TITLE
review Shields

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#264]
Picking up from https://github.com/gratipay/inside.gratipay.com/issues/234#issuecomment-111232069 and https://github.com/gratipay/inside.gratipay.com/issues/234#issuecomment-111426973 ...

**Comment by whit537** [comment]
>Shields revenue comes from donations. It doesn't have a legal entity, though. If it did, it probably would be a nonprofit, and I probably would need to read a lot more about French law on the subject.
>
However, given the current situation, if I need to set up a nonprofit, it will be easier for me to use a system that allows personal donations, at the expense of the possibility of sharing the workload and the donations.

@espadrine I'm fine with no nonprofit or legal entity for now, as long as you're clear that if/when you're able to start sharing revenue, you'll need to figure out what the implications of that are for you (i.e., are there sole proprietorships in France? Or *must* you incorporate in order to pay employees/contractors? etc. ...). I just don't want you to be surprised.

>>Who are your users?
>Those who download content from img.shields.io, use the shields library or its API.
>>How do you get them to pay you?
>They donate if they want to keep the service running.

I've updated the Revenue Model text to read:

>Those who download content from img.shields.io, use the shields library or its API donate if they want to keep the service running.

https://gratipay.com/shields/

And I've approved the team. :)

You okay with that change?

**Comment by espadrine** [comment]
That change is fine. Thanks!

**Comment by whit537** [comment]
Great, thanks @espadrine! :-)

**Comment by espadrine** [comment]
@whit537 Is there a way to change the profile statement at https://gratipay.com/~Shields/? It is already a bit outdated, and will soon be even more outdated once we switch away from Heroku.
