### ISSUE TITLE
review book's projects

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#265]
https://gratipay.com/act/
https://gratipay.com/cpan-io/
https://gratipay.com/cpan-book/

**Comment by whit537** [comment]
Prior discussion on https://github.com/gratipay/inside.gratipay.com/issues/234.

**Comment by whit537** [comment]
@book I'm still hung up on the juxtaposition between:

> The software is given away under an Open Source license. I don't make money from it.

... and ...

> My plan is to share revenue with people who make consistent contributions to my modules.

Picking up @ribashi's phrasing, can we use this for your "revenue model" text?

> We receive money from our fellow colleagues who wish to thank us for "[EXCELLENT OUTSTANDING WORK *ALREADY COMPLETED*](http://blogs.perl.org/users/peter_rabbitson/2014/02/i-bought-a-weekly-round-for-my-friends.html)."

Would you be okay with that?

**Comment by whit537** [comment]
(mangled the @mention in that last comment, soooooo ... cc: @ribasushi)

**Comment by book** [comment]
Yes, I'm okay with that.

We're not getting paid for doing what we do, people just use money as a easy token to express gratitude. :-)

**Comment by whit537** [comment]
Okay! I've updated your three teams:

 - https://gratipay.com/act/
 - https://gratipay.com/cpan-io/
 - https://gratipay.com/cpan-book/

Approved! Approved! Approved! :-)

**Comment by book** [comment]
Triple thanks!
