### ISSUE TITLE
onboard @rorepo

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#268]
Hey @rorepo, if you have any general questions about Gratipay code or processes as you work on https://github.com/gratipay/gratipay.com/pull/3573 and whatever else, feel free to ask them here. :-)

**Comment by rorepo** [comment]
Thanks @whit537 :-) I'm sure I'll have a lot of questions, by and by. At the moment I'm trying to get a feel of the system. The fake data bit seemed a nice (and safe :-)) place to start - I noticed there was no team data in the dev environment.

**Comment by whit537** [comment]
@rorepo Agreed, that's a good place to start and something we need. Let us know if you have any questions! :-)

**Comment by whit537** [comment]
@rorepo Thanks for https://github.com/gratipay/gratipay.com/pull/3582. May I add you as a collaborator on GitHub? Among other things, that will enable you to make your PRs from branches in our main repo, which is our usual pattern.

**Comment by rorepo** [comment]
Thanks, @whit537. I would be happy to be added as a collaborator on GitHub.

**Comment by whit537** [comment]
Yay! Invite sent. :)

**Comment by whit537** [comment]
@rorepo Seems like you're off and running. Any questions before we close this out?

**Comment by rorepo** [comment]
Thanks @whit537, I think this can be closed. I'll raise questions as needed when I get into unfamiliar territory.

**Comment by whit537** [comment]
!m @rorepo @mattbk
