### ISSUE TITLE
Can I create a Team for a brand new project?

### ISSUE THREAD

**Issue by webmaven** [gratipay/inside.gratipay.com#269]
I am starting a couple of brand new github projects that will for a short time be largely empty (https://github.com/webmaven/open-strategy-book is one), although all other criteria will be met.

I've been putting off creating my Teams until there was something substantial in those repos, but was wondering if I was perhaps putting things off for no reason.

**Comment by whit537** [comment]
> Can I create a Team for a brand new project?

Yes! :-)

**Comment by webmaven** [comment]
OK, I'll get off my ass and do so (soon-ish). :boot: :book: :boom:
