### ISSUE TITLE
Git rid of `website.fs` for Aspen upgrade

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#271]
To unwedge Aspen upgrade, the https://github.com/gratipay/inside.gratipay.com/pull/263#issuecomment-113729983 need to be fixed.

From @whit537: 

* [ ] Add state to the parameters for add_nav_current_to_context
* [ ] Throw a import pdb; pdb.set_trace() inside add_nav_current_to_context
* [ ] Poke around inside the state dict to find the right object you need. There maybe an fspath available, or you may need to use dispatch_result.fs.

**Comment by whit537** [comment]
@techtonik Here's the docs for understanding what the `state` dict is:

> Functions in the algorithm can use any name from the current state dictionary as a parameter, and the value will then be supplied dynamically via [`dependency_injection`](http://dependency-injection-py.readthedocs.org/en/latest/index.html#module-dependency_injection).

http://algorithm-py.readthedocs.org/en/latest/#algorithm.Algorithm

And:

http://algorithm-py.readthedocs.org/en/latest/#algorithm.Algorithm.run

**Comment by techtonik** [comment]
Fixed by ffbae67, but this doesn't make `nav_current` available in template context automatically.
