### ISSUE TITLE
Gratipay as a donation service

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#273]
Currently there are two models:
- donation (Gittip, Gratipay 1.0)
- economy (Gratipay 1.0, 2.0+)

In Gratipay 1.0 we got problems when donation model grew into economy model. Because economy is regulated by financial institutions and we were just not ready yet to tackle all the complexity. But that's changing and we are heading to economy model that is plugged into standard economy. We are forced to do this, because otherwise we'll die because of accusations of `money laundering` and ... (forgot that was the second reason).

But this comes at a price of sacrificing our donation service. I think it should be preserved at all cost, because of simplicity of the idea of giving to others without the involved complexity of the teams and strings attached. This significantly lowers the barrier to entry to use more advanced (and demanding from the legal standpoint) team/payroll feature. Dealing with the complexity of the law is the unique proposition of Gratipay and simple donation model is the critical part for providing understanding.

@espadrine (from shields.io) in #264 mentioned the phrase "**it will be easier for me to use a system that allows personal donations, at the expense of the possibility of sharing the workload and the donations**" and I believe that's true for other people as well.

If I understand the legal system for preventing `money laundering`, it people want to reuse donations, they need to reenter them into the system again (losing some percentage). Because `money laundering` is when somebody pays to somebody indirectly. I still don't understand why it is so strictly regulated (tax evasion?). But if we make donations open, it is not clear why we need to do this, because we have full traceability from giver to receiver even if it is a long chain.

Anyway, until the matter is clarified, we need to give people the choice:
1. use donation model - money donated to you can not be shared with others
2. use economy model - you establish legal entity in your region and use Gratipay to manage your open payroll and track flows

It is as well possible to provide a tool to *translate donations* into money that can be legally used by proving that donations are legal (this is different from `money laundering`, because the latter is illegal mechanism to *make* money clear, and we provide legal mechanism to help people *prove* that it is clear). It may be (or even should be) made as easy as moving funds from one balance to other. "Legalize the GP (gold pieces)!" =)

So, to continue on this ticket. Let's make it clear that **donations is safe sandbox** and describe *legal obligations towards accepting donations* (such as upper limit or necessary tax or ... whatever for you region - for example, in Belarus you need to register the donation of > certain amount with president's office).

Then describe the process of "level up" so that you can give the money to other people.

So donation route become parallel, and it to put the money from donation route further into the chain, it needs to be converted (using legal means, of course).

We also may provide a *parallel routes for donations*, such as if a person has a PayPal account. In this case GP just answers a question "how can I donate money to this person/project" without actually providing its own mechanism. But we can provide means to ensure that it is legal and all taxes are paid.

So, donation is the most simple process. In the levels of complexity:

Level 1. 1 giver and 1 receiver.
* [ ] find out requirements for giver and for receiver in general 
  * [ ] find out requirements for giver by givers region
  * [ ] find out requirements for receiver in receivers region
  * [ ] find out requirements for giver by receivers region
  * [ ] find out requirements for receiver in givers region

Level 2. many givers and 1 receiver.

Level 3. many givers and many receivers (team)

Sounds good? =) I may be able to draw a diagram as I see it.

**Comment by techtonik** [comment]
s/economy model/open economy model/ !

**Comment by chrisdev** [comment]
@techtonik here's an actual implementation of what you are trying to get with
http://joinfundclub.com
Kinda clunky but it gets around the money transfer/KYC issue by letting the project/team that you are donating to "host" their own donation form. Of course Gratipay could help with this somehow ..

**Comment by whit537** [comment]
Closing as gloriously inactionable.
