### ISSUE TITLE
on-site notification about Gratipay 2.1

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#274]
Suggested in https://gratipay.freshdesk.com/helpdesk/tickets/2405.

Gratipay 2.1: https://github.com/gratipay/gratipay.com/issues/3399#issuecomment-112110512.

Sending an email notification for Gratipay 2.1 is https://github.com/gratipay/inside.gratipay.com/issues/254.

**Comment by whit537** [comment]
Oops.

https://github.com/gratipay/gratipay.com/issues/3584

**Comment by techtonik** [comment]
For inside.gratipay.com it looks like we need a history.
