### ISSUE TITLE
wrestle with issues occasioned by uncanny likeness to Ross Ulbricht

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#275]
Reticketed from https://github.com/gratipay/inside.gratipay.com/issues/270 after going down the :rabbit: hole on [this Silk Road story](http://www.wired.com/2015/04/silk-road-1/), by Joshuah Bearman for *Wired*.

I feel like Ross Ulbricht's doppelgänger. We have similar cultural backgrounds. We both have connections to Pennsylvania (I know a guy that knew him at Penn State). We're both idealistic thirty-somethings who started economic experiments with rhetoric about "non-coercion" and "making the world a better place." I ran [payday 94 at the cafe whence he administered Silk Road](https://github.com/gratipay/gratipay.com/issues/2165) (Bearman inexplicably names a different cafe). Aaaaaaaand we look like pretty much the same dude, ... wiiiiiiiiiiiith the same penchant for being photographed stern-faced aaaaaand shirtless:

![chad](https://cloud.githubusercontent.com/assets/134455/8344412/6fd88068-1aaf-11e5-9da4-e4e1aac11a0d.jpg) &nbsp;  &nbsp; ![ross](https://cloud.githubusercontent.com/assets/134455/8344465/22442c98-1ab0-11e5-806c-fe4e8ac335ff.jpg)

*sigh*

What's going on here?

**Comment by whit537** [comment]
Along the way, I read a good chunk of the content from [this old Frontline piece on the War on Drugs](http://www.pbs.org/wgbh/pages/frontline/shows/drugs/cron/), and watched a bit of Cody Wilson: a [segment](https://www.youtube.com/watch?v=HK6-kbdHE2A) he did with Glenn Beck, and part of a [talk](https://www.youtube.com/watch?v=v3zx8kyVtGM) he gave to what appears to be a libertarian student group at the University of Texas.

**Comment by whit537** [comment]
A couple key take-aways from Bearman:

> And so, DPR’s principled, technological stand against the war on drugs slid into murder. Like so many revolutionaries before him, the idealist became an ideologue, willing to kill for his beloved vision. At one point, DPR corrected Inigo that this action was not revenge; it was justice—a new justice, according to the law of the Silk Road.

The conclusion of the piece also takes into account the corruption of one of the agents who was trying to catch Ulbricht:

> Their simultaneous moral turns, so intertwined, reinforced the one theme that barely appeared during Ross’ trial: how easy it is to forget the solidity and consequences of the real world when you live online.

##### The Real World

I want Gratipay to reinforce and enable our local lives, the lives that each of us pursue away from the computer screen. I want Gratipay to provide an economic foundation for life ... life that can't be captured on the Internet. Therefore, I resonate with the theme identified here, and as I've [said before](https://github.com/gratipay/gratipay.com/issues/3390#issuecomment-100681742), I love the idea of using Gratipay to fund hackerspaces, and I'm tickled that Gratipay in fact has been and is being used this way, because hackerspaces represent the real world. Real life, face-to-face interaction, to me, is where the ideals Gratipay stands for find their fullest expression.

The first thing I come away from this :rabbit: hole thinking is, how can we do more of that? I want a map on Gratipay of spaces that are funded on Gratipay. I want Gratipay events, hosted at these spaces and elsewhere. I want a dedicated Gratipay headquarters here in Ambridge.

##### Law and Anonymity

The second thing the story of the Silk Road makes me think about is Gratipay's relationship to the law on the one hand, and to personal privacy and anonymity on the other. My instinct is that our account of Openness has something vital to contribute here.

**Comment by whit537** [comment]
Frankly, I've been astonished to [learn lately](https://github.com/gratipay/inside.gratipay.com/issues/119) the extent to which strong identity verification is table stakes for participation in the global economy. It's really happened in the past 10 or 15 years, from what I can tell. Since 9/11, the trend in government has been to strengthen identity verification requirements imposed on banks and other financial institutions. Consquently, companies have appeared in the marketplace to provide this for banks. [Trulioo](https://www.trulioo.com/) (#256) boasts a database of 3 billion government-registered identities in 40+ countries, with India supposedly contributing another billion or so later this year. [ID Checker](http://www.idchecker.com/) (#257) boasts a template library with "over 3500 different ID documents from every country in the world." This is remarkable. Facebook, by comparison, only has 1.5 billion active users, and that's just online social history, not government-registered identity. Wow!

This fast-moving global consolidation of government identification gives me the willies. It makes me feel vulnerable, afraid, and even, at times, paranoid. I occasionally fantasize about federal agents showing up at my door, after me for who-knows-what? This makes me want to read [*The Trial*](http://www.kafka-online.info/the-trial.html).

**Comment by whit537** [comment]
It makes me feel **resentment** towards the State.

I see Silk Road as an attempt to cope with similar feelings of resentment towards the State through **rebellion**. Silk Road and its successors flaunt the law, emboldened by decentralized networks and strong cryptography. Yesterday, I downloaded Tor, registered an account on [Agora](http://www.agoradrugs.com/), and browsed around. The spirit of rebellion is alive and well. Cody Wilson exhibits a similar spirit. "The tree of liberty must be refreshed from time to time with the blood of patriots and tyrants," etc.

And yet, soaking for a bit in the Silk Road case, and in the larger story of the drug war, I'm struck by how blurry the line is between cop and criminal. I recall a Matthew Teague story that *The Atlantic* published in 2006, "[Double Blind](http://www.theatlantic.com/magazine/archive/2006/04/double-blind/304710/)," which explored the same theme in the context of the British government and the IRA. I'm acquainted with corrupt cops in Ambridge. It seems really easy for individuals, especially those prone to violence and greed, to slip back and forth across the border between the lumbering abstractions of "government" and "crime."

Corruption in government only fuels my feeling of resentment.

**Comment by whit537** [comment]
In fact, my perception or awareness of corruption in the State is essential to my feeling of resentment towards it. The global consolidation of identity gives me the willies to the extent that I don't trust the State to virtuously handle the attendant responsibility. Germany has some of the strongest data privacy laws because of their experience with National Socialism.

**Comment by whit537** [comment]
So does that mean I trust the German state more than the U.S.?

**Comment by clone1018** [comment]
I don't really think this is an issue or something that belongs Inside Gratipay. This is mostly your personal opinion (which can apply but I don't think does in this case).

**Comment by clone1018** [comment]
I agree with 

> The first thing I come away from this :rabbit: hole thinking is, how can we do more of that? I want a map  > on Gratipay of spaces that are funded on Gratipay. I want Gratipay events, hosted at these spaces and > elsewhere. I want a dedicated Gratipay headquarters here in Ambridge.

**Comment by whit537** [comment]
> I don't really think this is an issue or something that belongs Inside Gratipay.

Here's the question for Gratipay: Are we willing to pay the table stakes for participation in the global financial system? Do we trust the State enough to comply with its demand for strong identity verification?

I'm pretty sure the answer is, "Yes." First, because otherwise there's either no Gratipay, or we decide that bitcoin is the answer, which is a non-starter. Secondly, though, *I* want strong identity verification for Gratipay itself! I have pretty much no idea who Changaco is, yet I extended him a great deal of trust with Gratipay. I have a little better idea who others of you are whom we've given database access, etc. But imagine we have 100 million users. Clearly, in that case, we want your name, address, dob, drivers license, and passport on file with Gratipay, LLC, along with key fobs and whatever else. It would be reckless and irresponsible to our users *not* to take such precautions. The owners or some board of Gratipay, LLC should have the same access to my personally identifying information.

Accepting this is challenging for Gratipay in at least three ways:

 1. We're going to have to [up our infosec](https://github.com/gratipay/gratipay.com/issues/3504).
 1. It seems likely that we won't be allowed to open-source the code that talks to Trulioo, etc. Proprietary code goes against our culture and our processes, and it will pose a challenge to keep parts of our codebase private while the rest is public.
 1. There's a strong strain of privacy and anonymity activism on the Internet and in open-source. Requiring strong identity verification will alienate such folks.

**Comment by whit537** [comment]
> Accepting this is challenging for Gratipay in at least three ways:

But for purposes of bringing this thread in for a landing, the question is whether we're philosophically willing to go there in terms of strong identity verification.

**Comment by whit537** [comment]
I think the answer is yes. Comment/reopen if you disagree or aren't sure.

**Comment by webmaven** [comment]
@whit537:
> Frankly, I've been astonished to learn lately the extent to which strong identity verification is table stakes for participation in the global economy

Well, sort of. Rather, it has been forcing a starker division between 'white' and 'black' markets, with much fewer shades of grey allowed in-between. Of course, the rich and powerful have their own ways of shielding themselves from unwanted scrutiny of financial transactions, which have continued to evolve under pressure from those pushing for transparency.

Conclusion: If Gratipay actually gets big enough, there will be more options for circumventing identity requirements available, so yes, comply with strong identity verification for the foreseeable future, and reevaluate periodically.
