### ISSUE TITLE
review Detexify

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#277]
Ping @kirel. Can we get a revenue sharing plan on https://gratipay.com/detexify/? What are your thoughts there?

**Comment by kirel** [comment]
Since the banner on the site currently approximately covers the server cost, gratipay would actually be a surplus. If ever (I currently doubt it) there were regular contributions I think I should add people to something like a "core team" and share revenue among that team equally.

**Comment by whit537** [comment]
Thanks, @kirel. I've approved https://gratipay.com/detexify/ after adding this text:

> I will add people to something like a “core team” and share revenue among that team equally.

You okay with that?

**Comment by kirel** [comment]
Absolutely.

**Comment by whit537** [comment]
Cool, thanks. Welcome aboard! :-)
