### ISSUE TITLE
Wrong amount transfered to Paypal

### ISSUE THREAD

**Issue by c-geek** [gratipay/inside.gratipay.com#278]
Hello there,

I'm the founder of ucoin project (https://ucoin.io). It officially receives [$16,05/w](https://gratipay.com/~ucoin/receiving/).

I officially receives [$14,59](https://gratipay.com/~c-geek/receiving/). But the 2 last payrolls I received $0,54 on PayPal.

Could you please help me understand where I am wrong?

**Comment by c-geek** [comment]
I mean, if you are completely overwhelmed by the remaining work to do on Gratipay and do not have time to dig in this issue, just tell me.

I just need to know :-)

**Comment by whit537** [comment]
Sorry @c-geek, we are behind on support requests, yes. I will try to look into this for you before this week's payday.

**Comment by whit537** [comment]
The "Receiving" page is showing out of date information. :(

**Comment by whit537** [comment]
(I'm surprised we still have it in the UI, actually.)

**Comment by c-geek** [comment]
So do you mean we only have $0,54 donation/week now?

I guess we won't be able to understand what is really going under the hood while Gratipay 2.0 is not finished. Doesn't matter. Hope to this Gratipay working again. :-)

**Comment by rohitpaulk** [comment]
Hey @c-geek, 

The team [ucoin](https://gratipay.com/ucoin/) has [your profile (c-geek)](https://gratipay.com/~c-geek/) as the owner. 2 existing tips were migrated, the total being $0.55. Hence, the **total** amount the ucoin team receives now is **$0.55**. Paypal's fees amount to $0.01, so you should be receiving $0.54 every week.

The $14.59 that you used to receive every week included your `take` from the [~ucoin participant](https://gratipay.com/~ucoin/). The ucoin participant received $16.05 every week in tips.

I think that it would have made more sense to create the [ucoin team](https://gratipay.com/ucoin/) using the [~ucoin participant](https://gratipay.com/~ucoin/) as an owner. We don't have an option to change the owner in the UI, but I guess we can manually switch the owner and migrate the tips in your case. Once that is done, you should be receiving **$16.05** (*refer note*) per week (through the ucoin team).

cc: @whit537

*Note*: Provided none of your subscribers change the amounts, and their CCs don't fail.

**Comment by c-geek** [comment]
@rohitpaulk

Well, I would be very gratiful if you could do this manual switch.

**Comment by rohitpaulk** [comment]
@whit537 - Shall I proceed with this?

**Comment by whit537** [comment]
@rohitpaulk Go for it! Thanks for tracking this down. :-)

!m @rohitpaulk @c-geek

**Comment by c-geek** [comment]
Still the same :confused:

**Comment by rohitpaulk** [comment]
I'm working on this.

**Comment by rohitpaulk** [comment]
Subscriptions deleted.

**Comment by rohitpaulk** [comment]
Owner changed from `~c-geek` to `~ucoin`

**Comment by rohitpaulk** [comment]
Tips migrated.

**Comment by rohitpaulk** [comment]
Verifying amounts..

```sql
SELECT SUM(amount) FROM subscriptions WHERE team='ucoin' AND is_funded; # => 16.05
```

**Comment by rohitpaulk** [comment]
Hey @c-geek - This is done. Please attach a paypal email to the `~ucoin` account, and you should receive a payout next Thursday. :)

**Comment by c-geek** [comment]
OK, done too for e-mail address on my side. Thanks.

Just a last question: what happened to the last 3 weeks donations of **$14.59** made to ~ucoin? Were they just canceled? Since I see a balance of $0.00 on ~ucoin participant.

**Comment by c-geek** [comment]
OK, I received $10,83. It is probably the right amount.

**Comment by whit537** [comment]
> what happened to the last 3 weeks donations of $14.59 made to ~ucoin?

Unfortunately we did not process these donations. Since the [Gratipocalypse](https://medium.com/gratipay-blog/gratipocalypse-42fd0ec0d9e8) we have only been processing donations to Teams, no longer to ~users. Sorry. :(
