### ISSUE TITLE
document bitcoin processes

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#28]
Reticketing from https://github.com/gittip/www.gittip.com/issues/2148:

> I'd love a documented process on how we actually manage bitcoin at some point (just to reduce your bus factor a bit)

**Comment by rohitpaulk** [comment]
We don't do bitcoin anymore, closing this.

**Comment by techtonik** [comment]
Still the answer about why `Credit Card -> BTC` is illegal is not easy to understand. Even without BTC, blockchain is the future of transactions. If we can validate the ownership of BTC account (like Coinbase could be an authority), I don't see why we can't do transfers.
