### ISSUE TITLE
onboard @mattbk

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#280]
Reticketed from https://github.com/gratipay/inside.gratipay.com/issues/279#issuecomment-117810689.

I've set up permissions for you at Freshdesk, @mattbk. Are you able to login and see the support queue? What can I answer about http://inside.gratipay.com/howto/support-users?

**Comment by whit537** [comment]
https://gratipay.freshdesk.com/helpdesk/tickets/2500 :dancer:

**Comment by mattbk** [comment]
Yes, I can log in and do things.  Will help as I can.

**Comment by whit537** [comment]
@mattbk Awesome. Let's leave this open for a week or two in case anything comes up.

**Comment by whit537** [comment]
@mattbk Re: https://github.com/gratipay/gratipay.com/issues/3455#issuecomment-118934633 ... we need to add you as a collaborator on GitHub. May I do that? :-)

**Comment by mattbk** [comment]
Sure.  I'll try not to break things.

**Comment by whit537** [comment]
Invite sent! :-)

**Comment by mattbk** [comment]
I'll consider this and get back to you: https://github.com/gratipay/inside.gratipay.com/issues/283#issuecomment-120561966

**Comment by mattbk** [comment]
@whit537 I think I can accept the admin bit so I can look at history pages now that they are working again.

**Comment by whit537** [comment]
@mattbk Done! :-)

**Comment by whit537** [comment]
@mattbk Shall we consider you on-boarded?

**Comment by mattbk** [comment]
One more question.  How do I actually do this?
>@mattbk May I give you admin bit on Gratipay? That will enable you to, among other things, clear users such as FD2523 for 1.0 payouts.

**Comment by whit537** [comment]
I ended up answering this at https://github.com/gratipay/inside.gratipay.com/issues/287#issuecomment-123079268.

**Comment by whit537** [comment]
@mattbk Not finding it now but I believe you asked somewhere about making edits, yes? I see at https://github.com/gratipay/gratipay.com/issues/3628#issuecomment-123049048 that you've found our docs for making PRs. For quick changes that just change site copy, you can click the "Edit" pencil from within GitHub [on the master branch](https://github.com/gratipay/gratipay.com/blob/master/www/about/pricing.spt):

![screen shot 2015-07-20 at 8 03 34 pm](https://cloud.githubusercontent.com/assets/134455/8790301/6e1b27f6-2f1a-11e5-8a6f-01ac5bd570c5.png)

Just make sure at the bottom that you select "Create a **new branch**":

![screen shot 2015-07-20 at 8 00 42 pm](https://cloud.githubusercontent.com/assets/134455/8790308/7ac05d46-2f1a-11e5-9deb-f4b222ee98fb.png)

**Comment by mattbk** [comment]
I think we can consider me sufficiently onboarded.

**Comment by whit537** [comment]
!m @mattbk

**Comment by mattbk** [comment]
If you give me post permission for the Facebook page, I can start dribbling information out there when I have time, unless @kaguillera wants to trade me Twitter for Facebook ;-)

**Comment by whit537** [comment]
Gosh, I guess that means I need to login to Facebook. :-)

> unless [@kzisme] wants to trade me Twitter for Facebook ;-)

No reason you both can't do both, eh? :-)

**Comment by mattbk** [comment]
I typed that, left the room, and immediately realized I had the wrong name. :(

**Comment by whit537** [comment]
NEVER LEAVE THE ROOM!!!!!!!!!!!!!!!

**Comment by whit537** [comment]
j/k :)

Wanna link your Facebook account to ~mattbk and I'll add it to the page?

**Comment by whit537** [comment]
@kzisme You cool if I share the Twitter creds with @mattbk?

**Comment by kzisme** [comment]
No worries the more the merrier :)

**Comment by whit537** [comment]
@kzisme Cool, thanks! :-)

@mattbk Or let me know your Facebook username (here or via chad@zetaweb.com) ...

**Comment by whit537** [comment]
@mattbk Twitter creds sent to your gmail (picked from Freshdesk).

**Comment by whit537** [comment]
/me notices that that differs from your ~mattbk email

**Comment by mattbk** [comment]
Re: https://github.com/gratipay/inside.gratipay.com/issues/502#issuecomment-184695698

As you can see from all the commits at https://github.com/gratipay/grtp.co/pull/112, I think I've gotten the base functionality down (at least for the limited scope of the PR), but I'm not sure how to make Travis okay with it. I think the issue is looking for ~user data, but getting team data from public.json and failing.

Any insight would be appreciated.

**Comment by mattbk** [comment]
@whit537 I'm also avoiding Facebook as much as possible these days, unfortunately.

**Comment by whit537** [comment]
> I'm also avoiding Facebook as much as possible these days, unfortunately.

Good on ya. ;-)

**Comment by whit537** [comment]
@mattbk You can't keep onboarding forever. :-P

**Comment by whit537** [comment]
@mattbk Want access to Sentry so you can debug https://github.com/gratipay/gratipay.com/issues/4478?

**Comment by mattbk** [comment]
I thought you weren't seeing entries in Sentry?

**Comment by whit537** [comment]
Wasn't but then did: https://github.com/gratipay/gratipay.com/issues/4478#issuecomment-319349388.
