### ISSUE TITLE
configure Gratipay's PayPal

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#281]
We are receiving money into a PayPal account (https://github.com/gratipay/gratipay.com/issues/3567#issuecomment-113337747), but there is a $500 per month withdrawal limit. We have to add an SSN and credit/debit card to lift the limit.

![screen shot 2015-07-03 at 7 34 09 am](https://cloud.githubusercontent.com/assets/134455/8498534/ed390742-2155-11e5-9e4b-60ca71d87408.png)

I tried adding my SSN and got:

![screen shot 2015-07-03 at 7 30 41 am](https://cloud.githubusercontent.com/assets/134455/8498516/a85434da-2155-11e5-8251-036f969cff1b.png)

So ... blocking on #196? :(

**Comment by whit537** [comment]
Ideally we'd also configure PayPal to automatically pass through to PNC, so we don't have to manually withdraw money.

**Comment by whit537** [comment]
![screen shot 2015-07-03 at 7 38 56 am](https://cloud.githubusercontent.com/assets/134455/8498579/98124692-2156-11e5-9969-2cf30707a047.png)

**Comment by whit537** [comment]
We should have a page like this:

![screen shot 2015-07-03 at 7 39 53 am](https://cloud.githubusercontent.com/assets/134455/8498600/c667146e-2156-11e5-9113-b4d7f20b7d4d.png)

**Comment by whit537** [comment]
As a workaround, I've signed up for [a PayPal debit card](https://www.paypal.com/webapps/mpp/debit-card). It should arrive in 7-10 days. With this, we should be able to pay our bills directly out of our PayPal operations account.

**Comment by kaguillera** [comment]
To remove the limit on my paypal account I just added my PNC debit card since I don't have a SSN and it works ( atleast it said so)

**Comment by whit537** [comment]
Well, shucks. That worked! !m @kaguillera

**Comment by whit537** [comment]
I want to set up auto-sweep but these [old instructions](https://www.paypal-community.com/t5/PayPal-Mobile-Other-Services/how-do-I-turn-auto-sweep-on/td-p/372380) don't seem to apply anymore.

**Comment by whit537** [comment]
Don't want to call PayPal support from this coffee shop. Will call ... Monday?

**Comment by whit537** [comment]
I've received the debit card, but I'm considering not activating it now that we can withdraw to PNC. Why would we want it now? Let me see about auto-sweep ...

**Comment by whit537** [comment]
Blam. :-)

![screen shot 2015-07-17 at 8 49 05 am](https://cloud.githubusercontent.com/assets/134455/8747411/c6d00cac-2c60-11e5-8533-f2ed75ec05ef.png)

**Comment by whit537** [comment]
Hmm ... didn't ask about canceling the card while I was on the phone. Now it's easier to activate than to cancel it, so that's what I've done. Case closed.

**Comment by whit537** [comment]
Well, I guess I'll leave this open until we see our first auto-sweep post to PNC. I expect that to be initiated tonight, and clear by next Wednesday or so.

**Comment by whit537** [comment]
Yup, cleared.
