### ISSUE TITLE
find a CPA

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#285]
We should have a proper accounting framework in place for our escrow, with an annual independent review or audit to make sure we're a) not making any unintentional errors, and b) don't have anyone stealing money. Reticketed from https://github.com/gratipay/gratipay.com/pull/3618.

**Comment by whit537** [comment]
Looks like my go-to accounting firm got bought up a few years ago:

http://www.accountingtoday.com/news/Hill-Barth-King-HBK-Acquires-Carson-61682-1.html

http://www.hbkcpa.com/

**Comment by whit537** [comment]
http://hbkcpa.com/services/assurance/audits-of-non-public-companies/
http://hbkcpa.com/locations/pittsburgh-pennsylvania/

**Comment by whit537** [comment]
https://www.google.com/search?q=crowdfunding+accountants
https://www.google.com/search?q=open+source+accountants

**Comment by whit537** [comment]
crowdfundcpa.com is owned by www.artesiancpa.com.

> Audits starting at $3,500*
>
>*Costs of audit services can vary greatly dependent upon the nature of the entity, its transactions, industry, the condition of the financial records and financial statements.

**Comment by whit537** [comment]
http://www.accountingtoday.com/news/crowdfunding-jobs-act-jim-brendel-63508-1.html
http://www.heincpa.com/
http://www.heincpa.com/Bio/james-brendel-cpa-cfe/

**Comment by whit537** [comment]
To CPAs, "crowdfunding" means [the JOBS act](https://en.wikipedia.org/wiki/Jumpstart_Our_Business_Startups_Act).

**Comment by whit537** [comment]
[Audit vs Review vs Compilation](http://www.nonprofitaccountingbasics.org/audit/audit-vs-review-vs-compilation)

[Difference Between Compilation, Review and Audit](http://www.bmss.com/news-story.php?cn=172)

> The difference is the level of service, which is determined by your needs and what your creditors and/or investors require.

**Comment by whit537** [comment]
http://www.bmss.com/accounting-auditing.php

**Comment by whit537** [comment]
Inspired by https://github.com/gratipay/inside.gratipay.com/issues/193#issuecomment-97425987:

https://www.google.com/search?q=accountants+on+github

Nada mucho.

**Comment by whit537** [comment]
Maybe Patreon and/or Bountysource would have a recommendation?

**Comment by whit537** [comment]
Heeeeere's what audits are for:

http://www.ambridgeconnection.com/local-news/police-charge-ambridge-water-authority-employee-with-theft

:disappointed:

**Comment by whit537** [comment]
https://plus.google.com/103884012820955997871/about

**Comment by whit537** [comment]
Called (724) 709-7624 from that G+ page. "You have reached a number that is no longer in service. Please check the number and try again."

**Comment by whit537** [comment]
Called 724-266-2669 from http://www.ambridgeboro.org/index.asp?Type=B_DIR&SEC=%7BC99E7D2D-DB8B-43A3-8BA3-7F301AB84BEA%7D&DE=%7B16A6A011-9799-4CA5-A732-8A5EC7F3F9A4%7D. Same message!

**Comment by whit537** [comment]
To: mcturnleycpa@comcast.net
Subject: help with crowdfunding company?

> Greetings! I run a crowdfunding company here in sunny Ambridge, Pennsylvania, and am in need of a CPA to help me set up an accounting framework for the escrow we manage. I expect we'll also need regular review/audit in the future as well. Is this something you'd be interested in helping us with? Would you be available next Monday or Thursday at 10am for an initial meeting?

**Comment by whit537** [comment]
lol

> Delivery to the following recipient failed permanently:
>
>     mcturnleycpa@comcast.net

Apparently we've found the Dark Knight of CPAs.

**Comment by whit537** [comment]
[Manta](http://www.manta.com/c/mm8snr0/mark-turnley-cpa)! The first time you've ever given me useful information, Manta.

http://mcturnley.com/
(724) 371-0887
info@mcturnley.com
2919 Duss? That's not far from Blue Canary.

**Comment by whit537** [comment]
Success! Called and left my info with the secretary. "We recently moved to New Brighton."

**Comment by whit537** [comment]
We currently have about $150,000 in escrow for about 5,000 users.

**Comment by mattbk** [comment]
> We currently have about $150,000 in escrow for about 5,000 users.
That's one of those interesting stats that might help people realize Gratipay is bigger than it seems.  I know the escrow is going away, but still.

**Comment by whit537** [comment]
The escrow is on https://gratipay.com/about/stats, though other stats are broken there. I didn't find a ticket for cleaning up the stats page post-2.0, so I made https://github.com/gratipay/gratipay.com/issues/3626.

**Comment by whit537** [comment]
Recommendation from a friend: https://plus.google.com/112330445661125229993/about

**Comment by whit537** [comment]
To: [Keith Barfield](http://www.bmss.com/details.php?cn=422)
Subject: setting up books for crowdfunding site?

>Greetings! My name is Chad Whitacre, and I run a small crowdfunding site called Gratipay. We're three years old and we've reached a point where we could use some professional accounting help. Specifically, we need to implement a proper accounting framework for our escrow, which currently stands at about $150,000 for almost 5,000 users. Once we get a framework in place, we'd like to establish a periodic review or audit.
>
Is this something your firm could help us with? Would any of the following times work for an introductory call?
>
Thursday, July 23 (tomorrow) at 10am US/Eastern
Monday, July 27 at 2pm
Thursday, July 30 at 10am

**Comment by whit537** [comment]
Bringing over from https://github.com/gratipay/gratipay.com/pull/3618#issuecomment-122983165:

To: a friend in accounting

>Good to run into you the other day!
>
Can I buy you lunch at K&N some day this week or next? How about this Thursday (July 23) or next Monday (July 27)?
>
In addition to generally catching up, I'd love to pick your brain about setting up a chart of accounts for the escrow for the crowdfunding company I'm running (Gratipay).

**Comment by whit537** [comment]
http://wilkecpa.com/

**Comment by whit537** [comment]
To: [Peter Fleming](http://wilkecpa.com/team)
Subject: setting up books for crowdfunding escrow

> Greetings! [] gave me your name. I run a small crowdfunding site called Gratipay. We're three years old and we've reached a point where we could use some professional accounting help. Specifically, we need to implement a proper accounting framework for our escrow, which currently stands at about $150,000 for almost 5,000 users.
>
Is this something you could help us with? Would you have any availability next Monday, Wednesday or Thursday for an initial conversation?

**Comment by whit537** [comment]
> Good to hear from you and I am happy to hear of your success.
 >
My availability on those days you mentioned next week is as follows:
>
[]
>
Let me know what works.

Me:

> Thanks, Peter. Would you be up for a face-to-face meeting? How about I find you in Carnegie on Wednesday at 2pm?

**Comment by whit537** [comment]
> That works – see you then.

:dancer:

**Comment by whit537** [comment]
Yessssssss. Okay! Just wrapped up an initial consultation w/ Mr. Fleming. Short story is we're on the right track with https://github.com/gratipay/gratipay.com/pull/3618 and he can help us finish designing a proper accounting system. Picking up over there ...
