### ISSUE TITLE
IRC is still alive?

### ISSUE THREAD

**Issue by galuszkak** [gratipay/inside.gratipay.com#288]
https://botbot.me/freenode/gratipay/2015-07-17/?msg=44822149&page=1

It will be great to do something about that. :+1:

**Comment by mattbk** [comment]
That's funny, I just tried IRC for the first time yesterday.

**Comment by whit537** [comment]
IRC was downgraded in https://github.com/gratipay/inside.gratipay.com/commit/d96b25e10317b33061f7204f65241b6a23a797e0. If anyone enlivens it again then update [Communication Channels](http://inside.gratipay.com/appendices/channels).
