### ISSUE TITLE
pay a designer

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#298]
I'm [thinking](https://github.com/gratipay/inside.gratipay.com/issues/290#issuecomment-126133345) about hiring a visual designer. We've [tried for years](https://github.com/gratipay/gratipay.com/issues/3248#issuecomment-81365745) to recruit and retain designers on our team, and we haven't succeeded. We've [paid a lawyer](#193). We're [paying a CPA](#285). Should we pay a visual designer?

One of Mako Hill's main points in "Problems and Strategies in Financing Voluntary Free Software Projects" (#179) is that "[W]hen it comes to voluntary work and paid labor, you can have one or the other but not both," a process called "crowding out." He goes on to suggest:

> One useful model that shares common ground with the idea of funding capacity described above suggests funding primarily non-technical work. Paying people to do the equivalent of project management, book-keeping, or writing funding applications for a conference can be less controversial and less divisive than paying someone to write code; it can avoid crowding out coders while filling unfilled or neglected roles.

Paying a lawyer and a CPA fall pretty clearly in the realm of funding work that's outside the scope of what those of us in Gratipay core are volunteering to work on. Paying a visual designer gets closer to the core, though. Will you volunteers resent Gratipay if we pay a designer $~~100~~125/hr?

**Comment by whit537** [comment]
> I took a look at Gratipay and your concerns are definitely in my wheelhouse. I'd love to get together and have a conversation about how I can help you out! I am available for most of the afternoon tomorrow so just let me know a time and place that works best for you and I will be there.
>
Thank you for thinking of me to help you out, I really appreciate it!

**Comment by whit537** [comment]
Just wrapped up an initial meeting. She's going to get me a quote for a few hours of brand exploration: https://github.com/gratipay/gratipay.com/issues/3665.

**Comment by whit537** [comment]
> I hope that your vacation went well and you got to relax a little bit! I am following up per our conversation last Friday. I am still very excited to help you out with Gratipay. Attached is the letter agreement provide through Inquiri for your review. This document covers, a payment schedule and the deliverables promised along with payments. Once you have had a chance to look over it, I would be happy to accept any changes you'd like to make. Otherwise, if you are happy with how this looks, we can get to signing the document and work will begin next Monday, August 17th. 

She quoted us 10 hours at $125/hr.

> We're not going to be able to afford 10 hours right now. :-(
>
Can I get back to you for a re-quote once we've saved up a bit?
>
Sorry for the run-around. :-/

**Comment by whit537** [comment]
https://github.com/gratipay/gratipay.com/issues/3665#issuecomment-229486876

**Comment by whit537** [comment]
We have $5,500 in the bank now. I propose that we budget some of that for a designer.

**Comment by kzisme** [comment]
I pinged someone to see if they have anyone that would be cool with the project and helping as well - will report back when I hear something.

**Comment by whit537** [comment]
Okay! I just wrapped up a [follow-up](https://github.com/gratipay/gratipay.com/issues/3665#issuecomment-237610727) meeting with @skippylafarge. He's willing to work with us for $40/hr, billed monthly. I explained our open finances to him, as well as our open work process centered on GitHub.

I think it's clear that we need some design expertise, and we don't have that expertise in our contributor community at this point. Eventually I think we _do_ want designers on the Gratipay team itself. But we haven't landed [takes](https://github.com/gratipay/gratipay.com/issues/3994), and even then we can't easily get money back out of our operations account into Gratipay to distribute. There's also the matter that the rest of us are *not* making $40/hr anytime soon. Until we are further along—and we need design in order to get there!—I think we need to work with an "outsider," so to speak, and try to keep a handle on any tension that introduces. This is where I think it can help that @skippylafarge and I (and @kaguillera) will be able to work together in person, though of course decisions aren't real until posted back to GitHub.

@skippylafarge Can you share some of your work with us before we make a final decision to proceed here?

**Comment by skippylafarge** [comment]
Hi all!  I'm Jim and I design/develop with [Boolean Party](http://boolean.party).

In the name of recent work, here's a prototype I put together for a client last week (not yet responsive): [http://age-of-confusion.herokuapp.com](http://age-of-confusion.herokuapp.com)

The beginnings of a re-design for Paystub.io (responsive): [Home](http://portfolio.boolean.party) [Dashboard](http://portfolio.boolean.party/dashboard.html)

Also some logo and print work:

![logos](https://cloud.githubusercontent.com/assets/10200456/17976201/79eabcc2-6aba-11e6-89a5-da06e8de3210.jpg)
![print](https://cloud.githubusercontent.com/assets/10200456/17976202/79ec9b5a-6aba-11e6-81f5-8ab91094faf0.jpg)

**Comment by whit537** [comment]
Alright, @skippylafarge and I just sat down and talked this through. I'd be happy to work with @skippylafarge as a member of Team Gratipay. However, if Gratipay is going to procure outside design expertise, we need to go with someone with a stronger web portfolio.

With that, I'm going to close this ticket. The question whether to pay a designer is answered in principle. Let's use a different ticket to find the right external partner.

!m @skippylafarge 
!m *
