### ISSUE TITLE
get underwritten by PayPal

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#305]
In https://github.com/gratipay/gratipay.com/issues/63 we saw indications that PayPal would be reluctant to underwrite us. Since then, we've flown under their radar without incident, and in https://github.com/gratipay/gratipay.com/issues/3567 we fell back wholly on PayPal for payouts because it was the only option left to us to survive the Balanced shutdown. The fact that [Patreon uses PayPal](https://patreon.zendesk.com/hc/en-us/articles/203913489-What-are-my-options-to-receive-payment-) in a way very similar to us could mean that PayPal is more open now than they were a couple years ago, but still, this is risky for us. Patreon has way more clout than we do, and we have a history of rejection: [Stripe](https://github.com/gratipay/gratipay.com/issues/67#issuecomment-6553374), [Payoneer](https://github.com/gratipay/gratipay.com/issues/481#issuecomment-13623423) (which Patreon also uses), [Transpay](https://github.com/gratipay/gratipay.com/issues/417#issuecomment-78266767), [Stripe](https://github.com/gratipay/gratipay.com/issues/3245#issuecomment-91112973) (again), [Citizens](https://github.com/gratipay/gratipay.com/issues/3366#issuecomment-108917675), and sort-of [Zipmark](https://github.com/gratipay/gratipay.com/issues/3491#issuecomment-114222474) (fizzle-out more than outright rejection). One of these days we're going to get this right! :-)

**Comment by whit537** [comment]
On the positive side, since [first interacting with PayPal](https://github.com/gratipay/gratipay.com/issues/63), we *have* been [underwritten explicitly as a third-party payment aggregator (TPPA) by Braintree](https://github.com/gratipay/gratipay.com/issues/3287#issuecomment-96732426). Braintree put us on to the challenges associated with TPPAs in the first place, leading to https://github.com/gratipay/gratipay.com/issues/67. They were our [next option](https://github.com/gratipay/gratipay.com/issues/77) after Stripe rejected us the first time, but then Balanced came along and we took a three-year detour with them. In the mean time, Braintree was acquired by ... PayPal! So, who knows? Maybe our relationship with Braintree will strengthen our position with PayPal now. :-)

**Comment by whit537** [comment]
This is a [confusing page](https://www.paypal.com/webapps/mpp/bigcommerce/security/risk-underwriting). It's PayPal branded, but "powered by Braintree" ... is Bigcommerce a particular product, I guess?

![screen shot 2016-01-27 at 11 28 30 am](https://cloud.githubusercontent.com/assets/134455/12620175/23e6948a-c4e9-11e5-8000-db550b5e326b.png)

**Comment by whit537** [comment]
Some searching prompted by https://github.com/gratipay/inside.gratipay.com/issues/736#issuecomment-262044540 turns up:

>It’s been known for some time that PayPal now requires file-sharing and related services to obtain pre-approval to a set of [strict standards](https://torrentfreak.com/images/paypalp2p.jpg), but Soulseek was actually given a questionnaire to complete in order to validate its service with PayPal.
>
>Reproduced in full below, it’s the clearest indication yet that copyright holders are breathing heavily down PayPal’s neck and if they didn’t actually write the questionnaire themselves, they certainly played a massive role in its production.

https://torrentfreak.com/file-sharing-sites-paypal-account-returns-after-eff-intervention-160227/

![paypalp2p](https://cloud.githubusercontent.com/assets/134455/20497799/93cb46f6-aff8-11e6-8a98-abfbe85d43c9.jpg)

**Comment by whit537** [comment]
We probably need legal help to navigate this process.

**Comment by whit537** [comment]
In the mean time, renewed motivation for https://github.com/gratipay/gratipay.com/issues/726, eh @rohitpaulk? 😳

**Comment by kaguillera** [comment]
😱  

P.S. I find myself screaming often these days, why?

**Comment by whit537** [comment]
You know too much? :-P
