### ISSUE TITLE
draw $2,000 back to whit537

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#306]
I [invested](https://github.com/gratipay/inside.gratipay.com/issues/209#issuecomment-106919893) $2,000 a few months ago to cover #282. I could use that money back. Any objections to me gradually drawing that out?

**Comment by tshepang** [comment]
nope

**Comment by rohitpaulk** [comment]
I'd mark this as 'Ready to Start' if we had that label on IG :stuck_out_tongue:

**Comment by whit537** [comment]
Cool, thank you. :-)

**Comment by whit537** [comment]
Actually, let's keep this open to track.

**Comment by whit537** [comment]
I withdrew $200 the other day.

**Comment by whit537** [comment]
I forgot about this. I think we should block this on getting caught up on our books, to see where exactly my equity account stands right now.

**Comment by whit537** [comment]
Closing to clean out IG now that we have a separate finances repo. Maybe I'll reticket in a glorious post-https://github.com/gratipay/finances/issues/3 future.

**Comment by whit537** [comment]
We now have $4,004 in the bank post-#867. May I repay myself $1,000?

**Comment by kaguillera** [comment]
No Problem on my end

**Comment by whit537** [comment]
I got bogged down reconciling the expense report with our bank history.

**Comment by whit537** [comment]
> May I repay myself $1,000?

Done, with receipt sent to vendors@gratipay per our coalescing accounting policy.
