### ISSUE TITLE
Document bitcoin pay-in process

### ISSUE THREAD

**Issue by patcon** [gratipay/inside.gratipay.com#31]
Wasn't sure where to start for this ticket (or what system to ask for access to):
http://gittip.freshdesk.com/helpdesk/tickets/112

Seems like the "Common Questions" section is where this would logically be:
http://building.gittip.com/policies/run-support

cc: @whit537

**Comment by whit537** [comment]
Moot with https://github.com/gratipay/inside.gratipay.com/issues/201#issuecomment-102010517.
