### ISSUE TITLE
Building blocks of Open Source Economy

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#317]
Transparency.
Confidence.
Gratitude.

Simplifying things, providing transparency of the flow for everybody, clearing from legal fears and instilling a sense of confidence - this is a basis for forming a new type of economy.

The economy is a complicated system, and it was hacked numerous times. Also the larger economy always eats up the smaller one. So designing a proper gameplay is a lengthy process that needs research and experiments.

First, I'd like to concentrate on scenario where Gratipay can be used by Enterprises to give back something to community, matching donations of their employers to people outside. For this, we still need the component that allows you to say how much $$$ you are going to spend to support the specific person.

Then we need to provide clear status for the recipient person if getting donations from Gratipay is legal in the country of residence, how much taxes is needed to pay to be clear, and how to apply for tax refunds from donation.

... to be continued ...

**Comment by techtonik** [comment]
If the person is unable to receive the money through Gratipay, the exact reason should be stated:
- not registered
- legal uncertainty
- too much taxes and time
- other

In that case, the source user can choose to redirect the money to research legal issues in the country of residence of specific person. This way we will make money work. We are not using the person name to market some research - research support decision is independent from a desire to help some person. But the actual target should be linked to this person.

... to be continued ...

**Comment by techtonik** [comment]
Gratitude is not always about donations. Paying for someone's services, such as hosting etc. is also a great help. Providing a way to state monthly goals **and** automatically ensuring that funds will be spent on hosting, makes it easier for different companies and sponsors to support certain targets in person's life that are close to their vision. So, taxes and legal clearance is required to research and do this.

... to be continued ...

**Comment by techtonik** [comment]
So, the primary goal is to build a **the cashflow graph**. There people can see who donated to who, how the funds are redirected, who values what. Exporting the graph allows to see how much in percentages something is valued, what is the distribution. This allows to quickly match donation scheme.

**Comment by whit537** [comment]
!m @techtonik

**Comment by whit537** [comment]
You are our resident master of inactionable tickets, @techtonik. :-)

**Comment by whit537** [comment]
Closing as inactionable.

**Comment by techtonik** [comment]
@whit537 yea, abnormal levels of thyroid hormones affects my mood and concentration to finish things off, so I guess it can't be fixed easily, but at least know I the reasons. =)
