### ISSUE TITLE
figure out where to hold the retreat

### ISSUE THREAD

**Issue by clone1018** [gratipay/inside.gratipay.com#322]
It's time once again to start the retreat organizational process. For two years in a row now we've hosted it at @whit537's house and it was [really fun](http://blog.gittip.com/post/74460469599/with-first-retreat-gittip-team-becomes-a-reality/) and [an amazing experience](https://medium.com/gratipay-blog/at-our-second-retreat-we-met-our-third-users-5b473a2d1464)

Related material about Chad's house: https://github.com/gratipay/gratipay.com/issues/1780#issuecomment-31362555

Please chime in a couple of choices of where you'd like the retreat and I'll tally them all up.

Thanks :thumbsup: 

## Votes

**Comment by whit537** [comment]
!m @clone1018

**Comment by whit537** [comment]
P.S. There's [a hotel in town](http://www.staycobblestone.com/pa/ambridge/) that should be open before January.

**Comment by clone1018** [comment]
We need to get an expectation of people too.

**Comment by kzisme** [comment]
Ambridge, or The Burgh are sweet :)

**Comment by clone1018** [comment]
Ping @gratipay/owners and @gratipay/gratipay

**Comment by clone1018** [comment]
@whit537 that hotels rates are ~219/night for two people. Maybe it'll change when they open but that's enormously expensive.

**Comment by techtonik** [comment]
Getting to US is not cheap yet. =)

**Comment by whit537** [comment]
@clone1018 January 1-3?

**Comment by clone1018** [comment]
@whit537 Yeah, that's probably a good amount of time if we estimate a few stragglers hanging out after :)

**Comment by whit537** [comment]
Sure, official program from Friday night through Sunday and informal hangout before/after. "[Work festival](http://www.integralarchive.org/essay-tim.htm)." :dancer:

**Comment by whit537** [comment]
Just wanted to pin down the dates so I can ping/warn Jess. :-)

**Comment by whit537** [comment]
@mattbk You gonna come to the retreat this year? :-)

**Comment by timothyfcook** [comment]
I'm might actually be able to join this year : )

**Comment by clone1018** [comment]
I'm always in favor of @whit537's house it's available, it's created some of my favorite memories, but if it's too much or Chad is uncomfortable with it I'm up for most other options.

**Comment by whit537** [comment]
Hey @JessWhit, can we use the house for the retreat again this year? :-)

**Comment by whit537** [comment]
@timothyfcook Huzzah! :dancer:

**Comment by clone1018** [comment]
@whit537 ever here back from Jess?

**Comment by whit537** [comment]
Kind of. She's been day-dreaming about buying the house next door at Sheriff's sale to host the retreat. That'd be in future years, however, as it goes up in January (post-2016 retreat).

I'll bring it up again ...

**Comment by clone1018** [comment]
Cool, we can always find something else if something ends up happening.

**Comment by JessWhit** [comment]
Fine by me!

**Comment by whit537** [comment]
:dancer: !m @JessWhit :dancer:

**Comment by kzisme** [comment]
:dancer:

**Comment by clone1018** [comment]
I'm gonna go under the assumption that Chad's house is the location. We can reopen if we need to.

**Comment by whit537** [comment]
!m @clone1018
