### ISSUE TITLE
implement Companies as a Service

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#324]
In an epic :rabbit2:-hole with @dougwilson starting at https://github.com/gratipay/inside.gratipay.com/issues/211#issuecomment-109494621, I introduced the concept of "company-in-a-box" or "company as a service" (CaaS):

> [Our goal](https://github.com/gratipay/inside.gratipay.com/issues/211#issuecomment-109518669) is to streamline [the] process [of organizing a company] for you. Our goal is to do for organizing a company what Stripe did for credit card processing, by developing a 90%-case-solution that is simultaneously simple and legal.

As I've kicked this idea around with @timothyfcook and others—@webmaven has long been on this wavelength, [e.g.](https://github.com/gratipay/inside.gratipay.com/issues/180#issuecomment-100542810)—it seems to have legs. This is an idea that, at the very least, deserves its own ticket. This is that ticket. :-)

In particular, the question of @rohitpaulk's relationship to Gratipay, LLC (#242) leads back to this idea.

**Comment by whit537** [comment]
@stevepiercy has been [vibin'](https://github.com/gratipay/gratipay.com/issues/3556#issuecomment-120597262) on this as well:

> However, there is another type of Entity not mentioned: the loose Association of developers who contribute work to a FOSS project. The Association lacks any legal status, as well as the resources to attain legal status (no Social Security Number, Employer Identification Number, Articles of Incorporation, Bylaws, bank account, business license, etc.). PayPal can and does freeze assets for such Associations. Maybe an Association is an Entity, or it doesn't fit the Gratipay model, or something else?

**Comment by whit537** [comment]
More @stevepiercy [goodness](https://github.com/gratipay/gratipay.com/issues/3539#issuecomment-123921581):

> For the purposes of this draft, and for those who wish to become Team Owners, I think it is important to emphasize section 5.iii in the new terms. Assuming the role of Team Owner has greater responsibility and more duties than an ordinary User, and constitutes a significant change from the ordinary User perspective. Currently the draft has no mention of tax or other additional responsibility for this role. Thanks for your consideration.

**Comment by whit537** [comment]
I can't find it on GitHub, but at some point I started using this language: "We are trying to build a system that is robust enough to be legal, and simple enough to be accessible to people that are used to working together on open-source projects."

**Comment by whit537** [comment]
As mentioned at https://github.com/gratipay/inside.gratipay.com/issues/242#issuecomment-135587886:

> @chrisdev points out [Estonia](http://www.investinestonia.com/en/) as a jurisdiction that has much more favorable corporate taxes. What if we figured out how to make "companies as a service" with Estonia as the underlying jurisdiction, and then we voluntarily paid them after all? :dancer:

**Comment by whit537** [comment]
We want to deliver a simple experience for both ~picard and ~crusher.

[![screen shot 2015-08-27 at 9 21 01 pm](https://cloud.githubusercontent.com/assets/134455/9537032/8c3ea9c4-4d01-11e5-8089-c3f7658a2ea4.png)](http://inside.gratipay.com/big-picture/customers/)

**Comment by whit537** [comment]
To implement the simple case, we should look at finding one or three jurisdictions where we can domicile all of the Teams that are created on Gratipay. Beyond that, we can either go a Stripe or a Braintree route:

 - Stripe requires that you only use their merchant account (cf. iOS).
 - Braintree allows you to bring your own merchant account (cf. Android).

We are looking for jurisdictions that make it easy for Team owners to start a company, *and* for Team members to join the company. Picking up with the analysis at https://github.com/gratipay/inside.gratipay.com/issues/242#issuecomment-110828325, I think we should seriously consider co-ownership as the preferred model, both for pragmatic and ideological reasons. The pragmatic question is fully entwined with the choice of jurisdiction.

The fewer jurisdictions we have, the more predictable the process is for all of our users (Team owners and members). We want people to be able to move fluidly between Teams on Gratipay.

**Comment by whit537** [comment]
It seems likely to be the case that we'll find some jurisdictions (Germany? Austria?) where it's difficult for a person to join a Team that is domiciled in a different jurisdiction.

Though if ownership is the model through and through, maybe that really will make it simpler? Surely an Austrian can own a company domiciled in Estonia? I don't at all trust that "surely."

**Comment by whit537** [comment]
Possible law firm to help with this: http://www.whitecase.com/.

**Comment by whit537** [comment]
> finding one or three jurisdictions

Stripe and Braintree each have a handful of banks that they are abstracting for the rest of us.

**Comment by whit537** [comment]
This depends on proper identity verification (https://github.com/gratipay/gratipay.com/issues/3289), which depends on building a vault (https://github.com/gratipay/gratipay.com/issues/3504).

**Comment by whit537** [comment]
Like, we might get this done in 2017. :-)

**Comment by whit537** [comment]
@chrisdev at https://github.com/gratipay/inside.gratipay.com/issues/242#issuecomment-135796658:

> The process for setting up a Company in Estonia starts with the acquisition of an EE Card
https://e-estonia.com/e-residents/about/ - 50 Euro
The E Residency Card comes with an API that allows for digital signing.
Your can then use this to set up an Estonian based company https://e-estonia.com/component/e-business-register/
I found this about the cost and benefits https://www.quora.com/What-are-the-costs-benefits-of-incorporating-a-tech-startup-in-Estonia-if-you-are-from-America
Of course you'll probably need a lawyer to validate this stuff. Extra so if you're a US citizen :smile:

**Comment by galuszkak** [comment]
In Poland there is somehing called  AIP (Academic Incubators of Enterprenurship). You don't have to set up company. You just make agreement with them and they give legal entity for free. AFAIR it's not too much restricted and open to most people.

**Comment by whit537** [comment]
Interesting. Thanks for the tip, @galuszkak! :-)

**Comment by chrisdev** [comment]
Payment Gateways available in Estonia https://www.shopify.com/payment-gateways/estonia

There is also something called SEPA which (Single Euro Payments Area) compliant, meaning a EUR deposit from another SEPA country should not be subject to any fees. 

Also of course TransferWise is an Estonian Startup

**Comment by whit537** [comment]
Estonia basically already offers a company as a service:

> Estonian companies can be established, registered, and administered entirely online. In 2009 Estonia received a Guinness World Record for “fastest time to register a new legal entity” – just 18 minutes.

https://e-estonia.com/e-residents/services-and-benefits/

Maybe we should just leave it to them? :-)

cf. #438

**Comment by whit537** [comment]
@mitar points in #324 to a new company, [Open Collective](), that is pursuing (more-or-less) companies-as-a-service. See their blog posts:

 - "[A New Form of Association for the Internet Generation — part 1](https://medium.com/@xdamman/a-new-form-of-association-for-the-internet-generation-part-1-6d6c4f5dd27f)"
 - "[A New Form of Association for the Internet Generation — part 2](https://medium.com/@xdamman/a-new-form-of-association-for-the-internet-generation-part-2-fe6d8415f444)"

Key quote (from part 1): "If you can’t fix a layer down the stack, abstract it and move on." In particular, they're pursuing the fiscal sponsorship route (cf. @webmaven at https://github.com/gratipay/inside.gratipay.com/issues/180#issuecomment-100501970).

**Comment by whit537** [comment]
> With Stripe Atlas, entrepreneurs can easily incorporate a U.S. company, set up a U.S. bank account, and start accepting payments with Stripe. Starting today, it’s available to developers and entrepreneurs globally.

https://stripe.com/atlas

**Comment by chrisdev** [comment]
> With Stripe Atlas, you can establish a C-Corporation for your business in Delaware.

Gratipay is a C-Corpotation as opposed to an S Corporation correct?  
A  C corp is better for those not looking for VC?  I never remember this! 

So team members can easily incorporate  in the US for about $500 using Atlas.  
They will have bank accounts in the US so that  ACH is available to them.

Will this help w.r.t to issues of labour law, employment tax compliance and so on? 
However, you will be shifting the burden of tax compliance away from Gratipay and onto the team members.

**Comment by whit537** [comment]
Gratipay itself is actually an LLC (organized in Pennsylvania, not Delaware). My main takeaway from Stripe's new product is that they can't make it as easy as one would like:

We’re trying to streamline and standardize the process of setting up a new company.
>
That said, we’re not providing tax and legal advice. Stripe Atlas users have access to a legal guide prepared by Orrick, a tax guide prepared by PwC, and a free consultation call with an expert from PwC. PwC and Orrick will not provide tailored tax advice unless you engage them to represent you directly as a client.
>
If you have your own legal counsel or tax advisors, we also recommend speaking to them as you decide whether and how to set up your business with Atlas.

https://stripe.com/atlas/faq#taxlegal

**Comment by whit537** [comment]
Could we implement this by partnering with existing open source fiscal sponsors?

http://www.spi-inc.org/
https://sfconservancy.org/
etc.

![screen shot 2017-01-19 at 5 23 39 pm](https://cloud.githubusercontent.com/assets/134455/22127951/46b75894-de6c-11e6-91ce-be5852b1220b.png)

**Comment by whit537** [comment]
> Seconded. I think we’re all in the same boat here, and I’ll go out on a limb here and say that we all collectively know that what Joshua reported is by no means an isolated incident but a pattern that has been festering. Plus, we are probably all agreed that of all functions SPI carries out on behalf of its associated projects, disbursing the funds earmarked for them in a timely and low-overhead manner is the single most important one. It is the one that _has_ to work, or SPI isn’t a functioning fiscal sponsor in any sense of what that means.

http://lists.spi-inc.org/pipermail/spi-general/2016-December/003649.html

Hmm ... seems like a problem we could help with! :thinking:

**Comment by whit537** [comment]
> Just to make it clear that I have a stake in this, ArduPilot lost a $1k partnership donation because I couldn't get an answer from the treasurer on how to do a wire transfer.  I don't believe I ever got an answer to that question actually.

http://lists.spi-inc.org/pipermail/spi-general/2016-December/003654.html

Pain points galore! 😱

**Comment by whit537** [comment]
> Furthermore, SPI donated some money to Software Freedom Conservancy to help with the creation of tools that will make reimbursements easier. While there hasn't been a lot of progress until recently, Conservancy hired someone a few months ago so we're also expecting to see progress in that area.
>
> We'll have another face-to-face board meeting in February and these topics (reimbursements, treasurer reports, getting paid admin help) are a big item on the agenda.
>
>Martin
>
>President, Software in the Public Interest, Inc.

**Comment by whit537** [comment]
This just keeps getting better!

> If you hire a "bookkeeper off the street", they won't understand fiscal sponsorship.  They won't have the software [0] they need to properly cross-categorize expenses against account and temporarily restricted funds simultaneously.  Plus, most bookkeepers that you can hire part-time at a reasonable contract rate don't know a thing about keeping books for a charity and how it differs from for-profit.  Even *if* you hire charity-specialist bookkeepers (who are rare), they are not likely familiar with fiscal sponsorship, and they *certainly* won't know how to communicate with geeks seeking reimbursements who, say, are going to be annoyed at things like top-reply, Word document attachments, and the like.

http://lists.spi-inc.org/pipermail/spi-general/2016-December/003659.html

This whole thread is gold. *And* I just caught @bkuhn on IRC despite his being at LCA! Really curious to see where this goes ...

**Comment by nobodxbodon** [comment]
Sounds like great opportunity there. Do you consider straighting out our finances a critical pre-condition for such partnership, especially accoding to the last reference?

**Comment by whit537** [comment]
@nobodxbodon Yes, but I also expect any potential partnership to unfold over time. This isn't going to happen next week, just wanted to start the conversation to see if it flowers.

**Comment by whit537** [comment]
I get the impression that Conservancy doesn't really feel much pain here. SPI on the other hand ... I found them on irc.oftc.net in #spi and have dropped a line.

**Comment by whit537** [comment]
To: board@spi
Subject: possible partnership?

> Greetings!
> 
> Martin Zobel-Helas and Dimitri John Ledkov suggested in IRC that I introduce myself here. My name is Chad Whitacre, and I represent an organization called [Gratipay](https://gratipay.com/), which is a crowdfunding platform for free and open source software projects. We've been around for almost five years (we were called Gittip at first), and we are ourselves a [free software project](https://github.com/gratipay/gratipay.com) and an [open organization](http://inside.gratipay.com/big-picture/welcome).
> 
> Gratipay has signed up many small projects whose owners are unprepared for the tax burden that comes with accepting funds. We are not ourselves a fiscal sponsor, and we're [interested in partnering](https://github.com/gratipay/inside.gratipay.com/issues/324) with an existing organization such as SPI rather than developing this capability ourselves. We would love to be able to refer our customers to SPI for fiscal sponsorship.
>
>Here's what it would look like to get a partnership off the ground today:
>
> - SPI signs up for a Twitter account (unless there already is one that I missed?).
> - SPI uses its new Twitter account to sign up for a Gratipay account.
>
>With that in place, SPI would be able to start serving projects on Gratipay that are interested in fiscal sponsorship.
>
>Additionally, SPI could add some or all of it existing associated projects to Gratipay as an additional way to accept donations. We collect (via credit card) and disburse (via PayPal) funds on a weekly basis.
>
>However, my understanding from chats in IRC is that SPI has a significant pain point around disbursement of funds (not so much around collection in the first place, which is adequately handled already via PayPal and Click & Pledge). I would be happy to discuss feature additions to Gratipay that could make the disbursement process easier for SPI. For example, we could add an expense reimbursement feature so that projects could disburse to their contributors directly from Gratipay, with reporting for SPI as required.
>
>Finally, a word about cost: Gratipay does not take a cut of payments. Instead, we're funded [on Gratipay](https://gratipay.com/Gratipay/) just like any other project on Gratipay. We pass through upstream processing fees at cost. Donors are responsible for credit card charges, so the only cost for SPI would be PayPal's processing fee for payouts (2%, capped at $1).
>
>Would SPI be interested in this partnership? What questions can I answer here? Would my attending the next board meeting be a good next step?
>
> Thanks for your time and efforts in making free software sustainable!

**Comment by whit537** [comment]
I've emailed the director of the [JS Foundation](https://js.foundation/):

> We (Gratipay) are in the process of [integrating npm](https://github.com/gratipay/gratipay.com/pull/4305) in order to make it easier for companies to fund the long tail of open source. As we bring these generally smaller projects online, we would love to partner with JSF and/or LF to be able to offer fiscal sponsorship. The flow could/would be something like this:
>
> - Project joins Gratipay.
> - On Gratipay, project requests to join JSF.
> - On Gratipay, JSF accepts (or rejects) project.
> - Gratipay handles flow of funds for project, with accounting to JSF.
>
> Any interest? Worth a conversation?

**Comment by whit537** [comment]
I'm emailed the [new director](https://medium.com/@nodejs/hello-im-mark-hinkle-the-new-executive-director-of-the-node-js-foundation-ask-me-anything-86a5f5417619) of the Node Foundation:

_Subject:_ fund the long tail of open source?

> Congrats on your new appointment, Mark. :-)
>
>I'm working on funding the long tail of open source through a startup, Gratipay. Our strategy is to build on package managers to help companies pay for the open source they actually use.
>
>We're looking for fiscal sponsors to partner with. I've had conversations with [] and [] recently, and figured I'd email you as well. The idea would be to make this a profit center for the Node Foundation as you'd see a percentage of dollar volume to sponsored projects.
>
>May I suggest some possible times for a call? And/or buy you lunch during OSCON? :)
>
>Thanks for your time.
