### ISSUE TITLE
distributing -> sharing

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#325]
Reticketing from https://github.com/gratipay/gratipay.com/pull/3721, and following on from #117 ...

What do we think of `sharing` instead of `distributing`?

**Comment by mattbk** [comment]
Interesting that it could be used as a verb by both the team (sharing among ~users) and the ~user (sharing from the team).

Could be confusing if people associate it with the "sharing economy" of Uber, bikeshare, etc.

**Comment by whit537** [comment]
I had an idea for sharing: if we go with parents-eat-first for payroll, then it could be interesting to track `sharing` for each ~user as the amount of money they could've taken but didn't. Surfacing this number would reward people who exert a lot of influence in a Team *and* share the value they've created with others, and it'd help with discovery of Teams with work available.

Let's say Team Enterprise receives $2,000 per week. Here's what the taking/sharing chart might look like:

| balance ($) | ~user | `taking` ($) | `sharing` ($) |
|---:|:---|---:|---:|
| 2,000 | ~starfleet | 400 | 1,600 |
| 1,600 | ~picard | 400 | 1,200 |
| 1,300 | ~riker | 300 | 1,000 |
| 1,000 | ~data | 50 | 950 |
| 950 | ~yar | 250 | 700 |
| 700 | ~troi | 150 | 550 |
| 550 | ~crusher | 150 | 400 |
| 400 | ~laforge | 150 | 250 |
| 250 | ~worf | 150 | 100 |
| 0 |  |  |  |

The `sharing` for the Team itself would be the amount left after everyone's take: $100. Advertising this number on Team pages and listings would nicely indicate how much room there is for new members on a Team.

**Comment by whit537** [comment]
> Could be confusing if people associate it with the "sharing economy" of Uber, bikeshare, etc.

Funny, I didn't even think of that association, but I think it may actually be one we *want*, no?

One of the few email newsletters I subscribe to is www.shareable.net. See also #303 and #314. I.e., I think we want to make connections within the sharing economy.

**Comment by whit537** [comment]
Actually, I think it makes more sense for the Team's `sharing` to be the sum of its members' `sharing` (relative to the Team), and have the remaining left over be the Team's `available` or `remaining` or something like that.

**Comment by whit537** [comment]
> the Team's `available` or `remaining` or something like that.

`surplus`? Mockup:

![screen shot 2015-08-31 at 1 51 22 pm](https://cloud.githubusercontent.com/assets/134455/9585869/69938e6a-4fe7-11e5-9625-d7b02e60bd02.png)

**Comment by kaguillera** [comment]
1+ for surplus

**Comment by whit537** [comment]
We're [dropping](https://github.com/gratipay/gratipay.com/pull/4016) the word "payroll." As I work on bringing back [Ƭ̵̬̊](http://parkerhiggins.net/2013/01/writing-the-prince-symbol-in-unicode/) for Team Gratipay, I'm casting about for a word to use—in the branch name, even—and that brings me back around here. Am I stubbing out `DistributionMixin` ... or `SharingMixin`?

![screen shot 2016-05-05 at 10 21 10 pm](https://cloud.githubusercontent.com/assets/134455/15062623/ccd1151a-130f-11e6-87f0-5c23fa923453.png)

**Comment by whit537** [comment]
> and the ~user (sharing from the team).

I think we'd still keep "taking" around for talking about Team payments to ~users *from the user's point of view*. I like the way "sharing" reinforces the mutuality of the team. As an individual, I am "taking"—a bit stingy, yes—_but!_ as a member of the Team, I am part of a generous "sharing" collective. The Team members _allow each other_ to take. In that light, "distribute" actually sounds more centrally controlled than we want. "Sharing" better captures the decentralization of control inherent in the system.

Updating https://github.com/gratipay/inside.gratipay.com/issues/117#issuecomment-126369596:

```
"Giving"     refers to  payins   from the  ~user's  point of view.
"Receiving"  refers to  payins   from the  Team's   point of view.
"Sharing"    refers to  payouts  from the  Team's   point of view.
"Taking"     refers to  payouts  from the  ~user's  point of view.
```

**Comment by whit537** [comment]
Alright, I'm gonna leave this open while continuing work on https://github.com/gratipay/gratipay.com/issues/3994. Let's circle back here once the appropriate PR is on deck.

**Comment by whit537** [comment]
"Sharing" also suggests that we have `shares` in the database, rather than `takes`. I guess we don't want to shade to far into ownership (legally speaking), but we *do* need to think about improving ~~payroll~~ ~~twyw~~ *sharing* to work with percentages instead of absolutes. Hmmm ...

**Comment by whit537** [comment]
Ironic that ownership "shares" in traditional corporations are the opposite of actual sharing, in that they're not take-what-you-want. Perhaps against that backdrop we *do* keep talking about "takes"—differentiates and keeps us clear of confusion about _legal_ ownership.

**Comment by kaguillera** [comment]
suggestions for the replacement of the word "takes":
- accepts
- partakes (a little weird)
