### ISSUE TITLE
bring our Mandrill reputation back up

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#327]
We slipped from "Excellent" to "Good" at https://github.com/gratipay/inside.gratipay.com/issues/318#issuecomment-136476164.

**Comment by whit537** [comment]
> An account's reputation can be **Poor**, **Good**, or **Excellent**.

https://mandrill.zendesk.com/hc/en-us/articles/206274698-About-Reputation-and-Hourly-Quota

**Comment by whit537** [comment]
Ick! We're spammy! :disappointed: 

![screen shot 2015-08-31 at 3 33 31 pm](https://cloud.githubusercontent.com/assets/134455/9588344/b444b0de-4ff5-11e5-8ab5-85cd4edf4e93.png)

**Comment by whit537** [comment]
"[Reputation Context](https://mandrill.zendesk.com/hc/en-us/sections/200775507-Reputation-Context)"
Details about reputation calculations and tips for improving your reputation and hourly quota

"[High Spam Complaint Rate](https://mandrill.zendesk.com/hc/en-us/articles/205583477-High-Spam-Complaint-Rate)"

**Comment by whit537** [comment]
> In general, **industry standards recommend a complaint rate under .1%.**

**Comment by whit537** [comment]
Interesting that the spam complaint rate isn't included in the weekly email summaries, which explains why it's gotten so bad without us noticing. :-/

**Comment by whit537** [comment]
Wait, sorry ... that's probably the "Complaint rate."

**Comment by clone1018** [comment]
Our companies Mandrill rep has hovered at good since day one. And we use it purely for transactional receipts, no advertising emails.

**Comment by clone1018** [comment]
![image](https://cloud.githubusercontent.com/assets/226638/9588684/39b6085a-4fef-11e5-8864-8fc54d8194ba.png)

**Comment by whit537** [comment]
!m @clone1018 

I want to be excellent, though! :-/

**Comment by clone1018** [comment]
Yeah, we really want to hit it too. Wanted to share my stats so hopefully we can figure this sneaky algorithm out :P

**Comment by whit537** [comment]
Thank you for sharing! :-)

**Comment by whit537** [comment]
Your spam rate is 0.08: under their 0.1 recommendation, and *still* in the bottom quintile!

**Comment by whit537** [comment]
We're back to Excellent the past two weeks. :shrug:

https://github.com/gratipay/inside.gratipay.com/issues/389#issuecomment-155092504
https://github.com/gratipay/inside.gratipay.com/issues/395#issuecomment-157397422
