### ISSUE TITLE
have someone run Twitter

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#331]
On #236, I documented my decision to stop paying attention to Twitter. Now that we've [announced the 1.0 refund](https://medium.com/gratipay-blog/140-000-97d54e6d40ed), we'd like to start driving traffic to the site.

I'm not going to start using Twitter again, but @mattbk has been supporting folks on Twitter using his personal account, and maybe it's time to dust off the official Gratipay Twitter again for marketing purposes.

@mattbk Do you want to run the official Gratipay Twitter account?

**Comment by tshepang** [comment]
That would be so kool. Twitter may have issues, but it can really be a great marketing platform.

**Comment by mattbk** [comment]
I am much more comfortable in a support role than a marketing role.  At most, my use of the official account would be for that purpose and retweeting good things people say about Gratipay.  I'm not sure I am interested at this time since I run several other twitter accounts.

**Comment by tshepang** [comment]
Just re-tweeting the good things would be better than what we have at the moment from the official account :-)

**Comment by whit537** [comment]
@mattbk Okay. :-)

@tshepang Do *you* want to run the Twitter account? :-)

**Comment by whit537** [comment]
I'm so close ...

![screen shot 2015-09-07 at 6 56 30 pm](https://cloud.githubusercontent.com/assets/134455/9723583/4474a096-5592-11e5-90ac-25f817e5f4f5.png)

**Comment by tshepang** [comment]
I don't have enough confidence to do it. I'm also not involved enough with Gratipay.

**Comment by kzisme** [comment]
If there is some form of collaboration on marketing posts (or if the role
just includes replying to inquires) I could be of some assistance.

What was the previous use for the Gratipay Twitter?

**Comment by whit537** [comment]
@kzisme It was a significant source of growth for us for several years.

**Comment by kzisme** [comment]
If nobody else wants to I would be more than willing to help out :smile_cat:

**Comment by whit537** [comment]
Awesome, thanks @kzisme! :dancer: 

To be honest, though, I'm a little nervous about throwing you to the wolves. :bird: :wolf: 

@tshepang @mattbk Would either or both of you be willing to support @kzisme by paying attention to our Twitter activity and helping him use it effectively? If @kzisme has a question about how to respond to something, could he ping you for help thinking it through?

**Comment by mattbk** [comment]
That's cool with me.  I would just let the grumpy people go and focus on helping people who seem confused.

**Comment by whit537** [comment]
Awesome, thanks @mattbk. :-)

@kzisme I've emailed Twitter login info to kzita@kent.edu (from your GitHub profile). Have at it! :-)

**Comment by whit537** [comment]
> If there is some form of collaboration on marketing posts

I think the [blog](https://medium.com/gratipay-blog) is the canonical source for our marketing messages. E.g., right now we want to talk about the 1.0 refund coming up next month.

**Comment by tshepang** [comment]
@kzisme you can reach me at @tshepang_dev

**Comment by whit537** [comment]
@kzisme Were you able to login to Twitter? Here's a link we could share:

http://endlessparentheses.com/donations-donations-donations.html

**Comment by kzisme** [comment]
@whit537 Just successfully logged in.  Sorry for the wait!  I've been a bit busier than expected this week.  Also, what are your expectations on tweet frequency?

Just checked out the blog and posted a tweet about it. 

If you dislike(or have suggestions) it let me know and if you know anything else that needs posted (maybe a separate ticket can be created for Twitter collaboration/links/stuff)

@tshepang @mattbk Thanks for offering to help.  My personal Twitter can also be found @kzisme

**Comment by whit537** [comment]
https://twitter.com/Gratipay/status/642024625178836992

Yay! I love seeing that up there, @kzisme! Thanks for stepping forward! :dancer: 

!m @kzisme 

> Also, what are your expectations on tweet frequency?

Twitter is a real-time medium, of course. Do you think you'll be able to check in at least every day or two?

> If you dislike(or have suggestions) it let me know and if you know anything else that needs posted (maybe a separate ticket can be created for Twitter collaboration/links/stuff)

Maybe we can use the Radar tickets for this? Seems like any links we'd want to share on Twitter we'd also want to share with each other, and the Radar is the best place for that right now.

**Comment by kzisme** [comment]
@whit537 Easily - with at least 1-5 posts a week I think.  I've checked it between every class today.  

I feel like that would be good!  Just another small section for Twitter/Grati-News?  

Once payroll comes back I could also tweet about weekly payments/rollouts.  Currently, I feel like it will be more news oriented.

**Comment by whit537** [comment]
> Easily - with at least 1-5 posts a week I think. I've checked it between every class today.

You rock! :-) :rocket: :guitar: 

> I feel like that would be good! Just another small section for Twitter/Grati-News?

Cool. I think as stuff comes up during the week we can share it on the Radar and you can decide what is tweet-worthy, and vice-versa. :-)

> Once payroll comes back I could also tweet about weekly payments/rollouts. Currently, I feel like it will be more news oriented.

Yeah, I think it's also a good idea to promote our (approved) Teams like you did with Endless Parentheses.

**Comment by kzisme** [comment]
I appreciate the kind words!  

Sounds good!

My thinking was that the author (if they use Twitter) would like to see us sharing his work/posts and it would project us to a larger audience (their specific audience as well)

**Comment by whit537** [comment]
Agreed. What's your plan for deciding what accounts to follow?

**Comment by kzisme** [comment]
I reviewed the current people we are following and I feel that the Gratipay Twitter should follow any team that uses Gratipay, Authors that link to Gratipay, Developers/Collaborators of Gratipay, and anything related to Open Work or FOSS.  

Your thoughts?

**Comment by whit537** [comment]
(Reopening since it seems that we're still having a good conversation here. :-)

**Comment by whit537** [comment]
> Your thoughts?

@mattbk @tshepang ^^^? :)

**Comment by mattbk** [comment]
I trust whoever is running Twitter to follow the right people and tweet the right things.

**Comment by tshepang** [comment]
Maybe "anything related to Open Work or FOSS" is too broad. There's too much our there. Other stuff sounds good.

**Comment by kzisme** [comment]
I shall keep that in mind

**Comment by whit537** [comment]
Seems like we're off the ground with this.

!m @kzisme
