### ISSUE TITLE
sponsor Speak Freely next month

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#334]
[Jessica Jackley](https://en.wikipedia.org/wiki/Jessica_Jackley) is speaking in Pittsburgh next month, promoting her [book](http://www.amazon.com/-/dp/0679643761). I have a (free) ticket to attend the talk. Sponsorships for the event are [$500](http://www.eventbrite.com/e/18258923933) and include a dinner afterwards.

Why do I think Gratipay should be a part of this?

**Comment by whit537** [comment]
Pittsburgh.

Social entrepreneurship.

**Comment by whit537** [comment]
Gratipay wants to be a part of both, because we believe in both.

We haven't been part of the Pittsburgh startup scene since the Gittip Crisis. Been holed up out here in Ambridge.

Obviously we've got [a social mission](http://inside.gratipay.com/big-picture/mission), but we haven't really built associations as a brand along these lines. I'm not even sure exactly what that means, but somehow Gratipay belongs in the same thought as Watsi, Kiva, B-Corps, cooperatives, the sharing economy ("[owning is the new sharing](http://www.shareable.net/blog/owning-is-the-new-sharing)"), etc.

**Comment by whit537** [comment]
I'm leaning towards yes on this.

**Comment by mattbk** [comment]
I like it.

**Comment by kzisme** [comment]
I agree that it would make sense to sponsor it :)

**Comment by whit537** [comment]
Alright, let's do it! :dancer: 

> *Event Sponsorship*
>
Help keep Speak Freely events free for attendees, and join the awesome group of sponsors! Includes thanks from the stage, logo inclusion on all online/offline collateral, social mentions, sponsor table, (1) invitation to the sponsors dinner with our #SpkPgh guest. more. *Custom series sponsorships also available.

**Comment by whit537** [comment]
Done!

**Comment by whit537** [comment]
Well, sponsorship ticket purchased, anyway. The event is 3+ weeks away. ;-)

**Comment by whit537** [comment]
I ordered her [book](http://www.amazon.com/-/dp/0679643761) yesterday (personal spend, not Gratipay).

**Comment by whit537** [comment]
I'm excited about this. Thanks for permission to go! :-)

**Comment by whit537** [comment]
I finished *Clay, Water, Brick* this morning.

**Comment by whit537** [comment]
To: Fygment

> Gents
>
> Finished *Clay, Water, Brick* this morning. Gratipay all set to sponsor? What do you need from me?
>
Thanks!

**Comment by whit537** [comment]
> Thank you!!!
>
Great read, right?!
>
Please send us a high res version of your logo, and let me know if you'd like use of a table to showcase Gratipay at the venue.
>
Cheers,

-----------

>Logo: http://inside.gratipay.com/assets/gratipay.svg 
>
Would love table space, yes. I'll bring the penny punch! :-)
>
Book was great. So many obvious similarities ... chewing on "lessons learned" for Gratipay.

**Comment by whit537** [comment]
Coming up day after tomorrow.

@kaguillera I believe I have a ticket for you to attend the talk (not the dinner afterwards) if you want. We We could still meet at Blue Canary and then head back down to the city in the afternoon. Up for it? :)

I'll double-check on the ticket ...

**Comment by whit537** [comment]
To: Fygment
Subject: transfer (free) ticket for this Wednesday?

> I believe I registered a free ticket + the sponsor ticket for Wednesday. May I transfer the free ticket to someone else?
>
Eventbrite order no.: []
Transfer to: Kwesi Aguillera ([])
>
We have table space? Setup at 5:30?
>
Thanks!

**Comment by whit537** [comment]
> thanks for your email. you can bring several people under your sponsorship, so just let me know their names, and I'll add who you'd like to the guest list. 
>
Yes - Setup is at 5:30pm - lemme know if there's anything I can be doing for you in the meantime. 

--------------

> Cool, thanks. Kwesi Aguillera is the only other one besides me. See you tonight! Pumped! :D

**Comment by whit537** [comment]
I picked up 300 pennies this morning.

**Comment by whit537** [comment]
Leaving in 1.5 hrs.

**Comment by kzisme** [comment]
Have a great time :) I look forward to seeing how it goes!

**Comment by whit537** [comment]
@kzisme If you start driving soon, you could join us! :-)

**Comment by whit537** [comment]
Here we go!

@kzisme My cell is 412-925-4220 if you decide at the last minute to make the trip. :smile:

**Comment by kzisme** [comment]
Sent you a text :)

**Comment by whit537** [comment]
Back. Event went well. @kaguillera and I set up our table along with four others in the main lobby/entryway. We had about 1.5 hrs of mingling crowds before the event began, and about 30 minutes afterwards. We punched maybe 50 pennies, talked to folks. We used the [8' heart coin](https://github.com/gratipay/gratipay.com/issues/2985) as a rug. Worked on my pitch, especially for non-geeks. Don't feel like I've quite nailed it. Talked a bit about "cooperatives" and "coworking spaces" instead of "open-source projects" (but talked about those, too). We're inventing the future, I think is part of the problem. We made a little table card with [the Gratipay wordmark](http://inside.gratipay.com/assets/gratipay.bw.svg) that was crucial for communicating the name.

My friend Kit that co-runs Fygment (producers of the event) brought Jessica over and introduced her. Kit gave us a plug from the stage at the end of the event ("Make sure you get your penny punched before you leave") and invited us to set up at the next Speak Freely as well. Went to the sponsor dinner afterwards, chatted a tiny bit with Jessica and met a number of others (including [Eric Davis](http://elliott-davis.com/lawyers/), who may be able to help us with https://github.com/gratipay/inside.gratipay.com/issues/242). I don't feel like I was on my A game, especially talking with Jessica. For example, I neglected to introduce @kaguillera. :disappointed: I guess I'm rusty. Feels good to get out there again, though.

All in all, I feel it was a successful re-debut. We are back in the Pittsburgh start-up scene, and Jessica definitely knows about us now, if somewhat superficially. She punched pennies to take home. :-)

Looking forward to #384!

**Comment by whit537** [comment]
To: Jessica Jackley
Subject: Thanks for punching pennies. :)

> Jessica,
>
Great to meet you and hear you speak this evening. I think what you're doing is great, and there's a lot I'd love to ask you and talk to you about. I guess tonight wasn't the night for a full conversation, though. Maybe some day ...
>
Until then, best wishes, and keep up the great work! :-)
