### ISSUE TITLE
onboard @yifeiwu

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#336]
@yifeiwu Any questions you have as you start hacking on Gratipay, ask them here! :-)

**Comment by yifeiwu** [comment]
Thanks Chad. I'm a bit new at this and python development, so thank you for bearing with me. Is there like a wiki for FAQ's from new contributors? 

My specific question: Do you have any tips on setting up a local testing environment? I'm guessing I need to use pip to install everything from this textfile
https://github.com/gratipay/gratipay.com/blob/master/requirements_tests.txt

**Comment by whit537** [comment]
@yifeiwu Check out the README for installation instructions:

https://github.com/gratipay/gratipay.com#quick-start

What operating system are you on?

**Comment by yifeiwu** [comment]
Ok, I'll give it a try. I'm on a Ubuntu 14 virtualbox

**Comment by whit537** [comment]
Okay, make sure you have the [dependencies for Ubuntu](https://github.com/gratipay/gratipay.com#dependencies):

$ sudo apt-get install postgresql-9.3 postgresql-contrib libpq-dev python-dev

**Comment by yifeiwu** [comment]
Getting this error during `make run` step.

david@david-VirtualBox:~/gratipay.com$ make run
PATH=env/bin:/usr/local/heroku/bin:/home/david/.rbenv/plugins/ruby-build/bin:/home/david/.rbenv/shims:/home/david/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games env/bin/honcho run -e defaults.env,local.env web
2015-09-14 21:30:03 [12432] [INFO] Starting gunicorn 18.0
2015-09-14 21:30:03 [12432] [INFO] Listening at: http://0.0.0.0:8537 (12432)
2015-09-14 21:30:03 [12432] [INFO] Using worker: sync
2015-09-14 21:30:03 [12437] [INFO] Booting worker with pid: 12437
pid-12437 thread-47613122378368 (MainThread) Reading configuration from defaults, environment, and kwargs.
pid-12437 thread-47613122378368 (MainThread)   base_url                                              default                 
pid-12437 thread-47613122378368 (MainThread)   changes_reload         False                          default                 
pid-12437 thread-47613122378368 (MainThread)   changes_reload         True                           environment variable ASPEN_CHANGES_RELOAD=yes
pid-12437 thread-47613122378368 (MainThread)   charset_dynamic        UTF-8                          default                 
pid-12437 thread-47613122378368 (MainThread)   charset_static         None                           default                 
pid-12437 thread-47613122378368 (MainThread)   colorize_tracebacks    True                           default                 
pid-12437 thread-47613122378368 (MainThread)   indices                [u'index.html', u'index.json', u'index', u'index.html.spt', u'index.json.spt', u'index.spt'] default                 
pid-12437 thread-47613122378368 (MainThread)   list_directories       False                          default                 
pid-12437 thread-47613122378368 (MainThread)   logging_threshold      0                              default                 
pid-12437 thread-47613122378368 (MainThread)   media_type_default     text/plain                     default                 
pid-12437 thread-47613122378368 (MainThread)   media_type_json        application/json               default                 
pid-12437 thread-47613122378368 (MainThread)   project_root           None                           default                 
pid-12437 thread-47613122378368 (MainThread)   project_root           .                              environment variable ASPEN_PROJECT_ROOT=.
pid-12437 thread-47613122378368 (MainThread)   renderer_default       stdlib_percent                 default                 
pid-12437 thread-47613122378368 (MainThread)   show_tracebacks        False                          default                 
pid-12437 thread-47613122378368 (MainThread)   show_tracebacks        True                           environment variable ASPEN_SHOW_TRACEBACKS=yes
pid-12437 thread-47613122378368 (MainThread)   www_root               None                           default                 
pid-12437 thread-47613122378368 (MainThread)   www_root               www/                           environment variable ASPEN_WWW_ROOT=www/
pid-12437 thread-47613122378368 (MainThread) project_root is relative to CWD: '.'.
pid-12437 thread-47613122378368 (MainThread) project_root set to /home/david/gratipay.com.
pid-12437 thread-47613122378368 (MainThread) Found plugin for renderer 'jinja2'
pid-12437 thread-47613122378368 (MainThread) Renderers (*ed are unavailable, CAPS is default):
pid-12437 thread-47613122378368 (MainThread)   json_dump        
pid-12437 thread-47613122378368 (MainThread)   jsonp_dump       
pid-12437 thread-47613122378368 (MainThread)   stdlib_template  
pid-12437 thread-47613122378368 (MainThread)   stdlib_format    
pid-12437 thread-47613122378368 (MainThread)   jinja2           
pid-12437 thread-47613122378368 (MainThread)   STDLIB_PERCENT   
pid-12437 thread-47613122378368 (MainThread) Won't log to Sentry (SENTRY_DSN is empty).
pid-12437 thread-47613285316352 (Thread-1) Traceback (most recent call last):
pid-12437 thread-47613285316352 (Thread-1)   File "/home/david/gratipay.com/gratipay/cron.py", line 26, in f
pid-12437 thread-47613285316352 (Thread-1)     func()
pid-12437 thread-47613285316352 (Thread-1)   File "/home/david/gratipay.com/gratipay/main.py", line 84, in <lambda>
pid-12437 thread-47613285316352 (Thread-1)     cron(env.update_cta_every, lambda: utils.update_cta(website))
pid-12437 thread-47613285316352 (Thread-1)   File "/home/david/gratipay.com/gratipay/utils/__init__.py", line 145, in update_cta
pid-12437 thread-47613285316352 (Thread-1)     website.support_current = cur = int(round(nreceiving_from / nusers * 100)) if nusers else 0
pid-12437 thread-47613285316352 (Thread-1) TypeError: unsupported operand type(s) for /: 'int' and 'tuple'

**Comment by whit537** [comment]
@yifeiwu That error may be spurious, try hitting http://localhost:8537/ anyway?

Even if it's spurious, we should fix it, of course. It's ticket as #3771, and I've added a +1 for you there. Sorry for the error!

**Comment by yifeiwu** [comment]
Hmm, the gunicorn is loading up the site on my local browser and I'm working on getting the tests to pass now. However, there's an error during the make fake step. Not sure if that's supposed to happen or if I'm missing something..


david@david-VirtualBox:~/gratipay.com$ make fake
env/bin/honcho run -e defaults.env,local.env env/bin/fake_data fake_data
Traceback (most recent call last):
  File "env/bin/fake_data", line 9, in <module>
    load_entry_point('gratipay==1913', 'console_scripts', 'fake_data')()
  File "/home/david/gratipay.com/gratipay/utils/fake_data.py", line 386, in main
    prep_db(db)
  File "/home/david/gratipay.com/gratipay/utils/fake_data.py", line 265, in prep_db
    """)
  File "/home/david/gratipay.com/env/lib/python2.7/site-packages/postgres/__init__.py", line 357, in run
    cursor.run(sql, parameters)
  File "/home/david/gratipay.com/env/lib/python2.7/site-packages/postgres/cursors.py", line 92, in run
    self.execute(sql, parameters)
  File "/home/david/gratipay.com/env/lib/python2.7/site-packages/psycopg2/extras.py", line 288, in execute
    return super(NamedTupleCursor, self).execute(query, vars)
psycopg2.ProgrammingError: trigger "process_transfer" for relation "transfers" already exists

make: *** [fake] Error 1

**Comment by whit537** [comment]
@fenryxo hit the same error and reported it at #3780. There is a test and a fix at #3782 waiting to be reviewed and merged. :-)

**Comment by whit537** [comment]
Sorry, that's https://github.com/gratipay/gratipay.com/issues/3780 and https://github.com/gratipay/gratipay.com/issues/3782. :-)

**Comment by whit537** [comment]
First PR, yay! #3772 :D

**Comment by yifeiwu** [comment]
Indeed, time to find new toy :)

**Comment by whit537** [comment]
@yifeiwu Seems like you know your way around Gratipay, ya? Gonna go ahead and close this out. Reopen if you want. :-)
