### ISSUE TITLE
get together with kzisme

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#337]
How about it, @kzisme? :-)

What days are good for you? Wanna come out to Ambridge or should we meet in Youngstown or Salem?

**Comment by kzisme** [comment]
I just checked distances and to Salem it's 1 hour and fives minutes for me and it's one hour and six minutes for you.  That would be my choice unless you have any other ideas! 

I'm free Monday, Wednesday, and Friday(s) as well as weekend days.  How are your upcoming weeks looking?

**Comment by kzisme** [comment]
@whit537 I'm also going to be buying a Macbook Pro tomorrow...I'm not sure which is more worth the money...  

13" with 256GB SSD, 2.7Ghz dual core i5, 8GB RAM
or...
15" 256GB SSD, 2.2Ghz i7, 16GB RAM

**Comment by whit537** [comment]
Awesome! How about this Monday (9/14) or next (9/21) in Salem? The place to meet is Friends Roastery, 474 East State Street, Salem, Ohio 44460. They're open from 7am to 4pm. 

And I would probably go for the larger screen and more RAM, but that's just me. :-)

**Comment by kzisme** [comment]
9/21 Would work better for me.  I'm typing this on my new Mac! :)

Any tips for setting up a nice dev environment o.O

**Comment by whit537** [comment]
Okay, 9/21 it is!

> I'm typing this on my new Mac! :)

Nice! :dancer: :computer: 

I know a lot of people use [homebrew](http://brew.sh/).

**Comment by whit537** [comment]
@kzisme I need to reschedule. I've been in the hospital for the past three days learning about [IIH](https://en.wikipedia.org/wiki/Idiopathic_intracranial_hypertension)(!), so I'm behind on getting ready for the [meeting](https://github.com/gratipay/gratipay.com/pull/3653#issuecomment-136474315) with the CPA on Wednesday to have him review the [accounting refactor](https://github.com/gratipay/gratipay.com/pull/3786). Aaaaaaaaand then we're into the [advances refund](https://github.com/gratipay/gratipay.com/issues/3763) and then the big [1.0 refund](https://github.com/gratipay/gratipay.com/issues/3539), so I think we should revisit this in mid-October.

Sorry. :-/

**Comment by kzisme** [comment]
No worries!  I just got a new part time job as well, so we can just leave this open for future planning/discussion.  

Hope your kids are doing well now!  If you need assistance with anything just ping me :)

**Comment by whit537** [comment]
Ping @kzisme. :-)

What days are good for you these days?

**Comment by kzisme** [comment]
My schedule is updated every two weeks on Thursdays for my part time job.  Other than that school is still only on Tuesdays and Thursdays.  How about you?

**Comment by whit537** [comment]
Maybe @kaguillera could spend Tuesday night at my place and we could all three meet in Salem on Wednesday. Waddya think, @kaguillera? How early can you get up in the morning? :-)

**Comment by kaguillera** [comment]
Is that next week? Let me check the transportation and get back to you.

**Comment by kzisme** [comment]
I suppose last week didn't workout.  

How are the coming weeks looking @whit537 @kaguillera

**Comment by whit537** [comment]
This week is bad because of #384 and also my kids have the day off school Wednesday. Can we try for next week on the 18th?

**Comment by kzisme** [comment]
I'm working from 6-10pm  So, ideally the morning would work for me - to have adequate time to return for work that evening.

**Comment by whit537** [comment]
Could still work. Friends Roastery is open from 7am to 4pm. I think @kaguillera would aim to be there pretty close to when they open, you could find us there whenever is convenient for you. There's a good place for lunch nearby and we can have you out by 4 to get back for work at 6. How's that sound?

**Comment by kaguillera** [comment]
Is this the place in Ohio?

**Comment by whit537** [comment]
@kaguillera Yes!

**Comment by kzisme** [comment]
@whit537 I'll probably know tomorrow yes/no.  I have stuff I need to get done before Thursday and I worked 12.5 hours today :'(

**Comment by whit537** [comment]
I picked up a fever in NYC and haven't shaken it yet. I need to cancel tomorrow. :disappointed: 

Next week is bad because of #403. Can we reschedule for Dec 2?

**Comment by kzisme** [comment]
Sounds good for now :) get well soon!

**Comment by whit537** [comment]
Temperature check for Dec 2. Whitacres seem to finally be over the fevers, meaning @kaguillera can hopefully stay with us Tuesday evening for a Wednesday departure. I feel it this time, it might actually come together!

Eh, @kaguillera @kzisme?

**Comment by whit537** [comment]
@kzisme How does tomorrow look for you? I just talked to @kaguillera by phone and it sounds like he's up for it! :-)

**Comment by kzisme** [comment]
Unfortnately, I keep getting scheduled 35+ hours a week at work so I cannot make it tomorrow :disappointed:

**Comment by whit537** [comment]
Ah, well. One of these days! :-)

Catch that, @kaguillera? No trip to Ohio tomorrow.

**Comment by kzisme** [comment]
Soon though :)

**Comment by whit537** [comment]
@kzisme How's your schedule this week? Available on Wednesday? :-)

**Comment by whit537** [comment]
Back on the back burner. :-)
