### ISSUE TITLE
Edit links are broken in the inside

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#338]
http://inside.gratipay.com/appendices/diff/bountysource
Its edit link goes to `https://github.com/gratipay/inside.gratipay.com/edit/master/www//index.spt` https://github.com/gratipay/inside.gratipay.com/edit/master/www//index.spt and it should be https://github.com/gratipay/inside.gratipay.com/blob/master/www/appendices/diff/bountysource.spt

**Comment by techtonik** [comment]
Noted in #316

**Comment by techtonik** [comment]
This is here https://github.com/gratipay/inside.gratipay.com/blob/6dd9bccd761f624bfe0ecae98883af591d30e496/nav.py#L28 but I have no idea when `parent` can be None, or what the `slug` is. Need more comments,

**Comment by whit537** [comment]
Fixed in https://github.com/gratipay/inside.gratipay.com/commit/9292d7d88f2d109a8779b75d3464056e9a7a2419. The Bountysource page was outside of the proper site navigation structure.
