### ISSUE TITLE
Go to International Conference on Crowdeconomy (ICC-2015 - Minsk, Belarus)

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#346]
@whit537 and guys - you should apply to join the conference with the talk - http://crowdconference.by/en/ - and I could finally meet you in RL.

**Comment by whit537** [comment]
Would be fun! Personally I can't afford the flight and time on short notice. :-(

**Comment by techtonik** [comment]
That's a pity, but.. if you're going to submit as a speaker, you may ask for sponsorship.

**Comment by whit537** [comment]
Do you know anyone involved in organizing it?

**Comment by techtonik** [comment]
Yes. I know guys who won the invitation to the conference by winning nomination for "the best solution for crowdeconomy" in local FinTech hackaton organized last week. I will get the contacts. Do you have some reference materials of the talk for the conf that I can forward to them?

**Comment by whit537** [comment]
##### Building a Crowdeconomy of Gratitude

>  In this talk I will share lessons learned from the first three years of building Gratipay, an international crowdeconomy based on gratitude, generosity, and love. We are unique among crowd-funding platforms because we're self-funded by voluntary payments through our own platform. Founded in June, 2012, we peaked at 3,000 active users and $60,000 in monthly volume before collapsing and relaunching six months ago. Lessons learned include: how to navigate the global financial system, how *not* to run a community, how to manage an "open company" while respecting user privacy, and how to compete with Silicon Valley.

Does that look like a good abstract to you, @techtonik? If so we can fill out the outline as needed ...

**Comment by whit537** [comment]
P.S. Do you think this can really happen? I can only go if travel and lodging are paid for. :-(

**Comment by techtonik** [comment]
@whit537 sorry for the time limit, I haven't got any new yet. Seems like we're just missing the deadline.

**Comment by techtonik** [comment]
@whit537 I've just submitted the request through official contact form at http://crowdconference.by/contacts Hopefully guys will be able to get here to comment directly.

**Comment by techtonik** [comment]
If not, then I will try to post responses as soon as I get online, but I also gave your chad@zetaweb.com address, so it may happen you receive something there. =)

**Comment by whit537** [comment]
Okay! :-)

**Comment by techtonik** [comment]
On Tuesday guys have been told that organizers can not make decision until Monday. Because the person in charge is not in Minsk. I can't believe it happens now, in the age of online communications, but let's hope that the absence reply is just because of negotiations with the sponsors.

**Comment by techtonik** [comment]
No response from organizers over two weeks. I am sorry for the poor organization. I guess it is their first experience.
