### ISSUE TITLE
have an accountant review our books

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#350]
Reticketed from #308.

**Questions:**

 - [x] Where does the processing fee buffer show up on the balance sheet? `Escrow:Fee Buffer`
 - [x] At what point should we stop making changes to parts of our books?
 - [x] How'd we do with the $1.50 first payout?
 - [x] How do we account for escrow changes over time? Income statement? Cashflow? A dedicated report? Income statement.
 - [x] Opening balance, or owner's equity?

**Comment by whit537** [comment]
> We'll need to come up with some policies, published on Inside Gratipay, for recording financial transactions and reconciling with our bank accounts. I'm not going to worry about that for this ticket. I've reticketed having an account review our books as #350, let's pick up with that there.

https://github.com/gratipay/inside.gratipay.com/issues/308#issuecomment-143831352

**Comment by whit537** [comment]
Perhaps Jim Johnson from KDC would be good for a first pass (https://github.com/gratipay/inside.gratipay.com/issues/72#issuecomment-166722473).

**Comment by whit537** [comment]
Bringing over from https://github.com/gratipay/inside.gratipay.com/pull/390#issuecomment-170421354:

To: CPA
Subject: meeting to review Gratipay's books

> Greetings and Happy New Year!
>
We've done a lot of work on Gratipay's books since the last time you and I talked, back in September. I think we've now got a pretty good system in place, and we're close to reconciling our first month—June, 2012. We're aiming to be fully caught up in Q3, after which I'd like to talk about our first audit.
>
Before then, though, I'd appreciate a meeting to make sure we're on the right track with how we've got the books set up. Wednesdays and Thursdays are best for me, but I can make most days work. Can you fit us in anytime soon?

**Comment by whit537** [comment]
We're looking at Thursday morning, January 28.

**Comment by whit537** [comment]
@kaguillera and I are planning to meet with the CPA at 8am on the 28th. Yesssssssss.

**Comment by whit537** [comment]
Pinged Peter to make sure we're still on for tomorrow. @kaguillera and I are figuring out bus schedules ...

**Comment by whit537** [comment]
Meeting is confirmed.

**Comment by whit537** [comment]
Okay! Good meeting. Let's summarize ...

**Comment by whit537** [comment]
The escrow shouldn't be on the income statement, it should get it's own column/report: https://github.com/gratipay/finances/issues/8.

The fee buffer shouldn't be on the income statement: https://github.com/gratipay/finances/issues/9.

It's fine to roll our own accounting system based on Ledger and GitHub. The U.S. Government certifies the accounting systems of its contractors, and it has certified spreadsheet-based systems before. GitHub's change management through commit history and PR commenting and workflow is "audit-friendly." "As long as it balances," we're fine. In addition to the balance sheet and income statement, the other reports we're likely to need are cash flow, account detail, and eventually aging reports.

We should always include an amount in the line items in our dat files; we shouldn't depend on ledger's implicit balancing of transactions. "Otherwise this is a good ledger." :v: It's okay to fudge the dates somewhat for the sake of grouping related items together.

Retained earnings (or accumulated deficit, for a loss) is for past years' activity. We should be posting income and expenses against `Equity:Current Activity`: https://github.com/gratipay/finances/issues/10.

CPAs provide three services related to books:

 - compilation—preparing financial statements
 - review—negative affirmation, "We did not find anything" wrong.
 - audit—positive affirmation

Wilke provides an estimate but bills hourly. Audits run 2-3x the time/cost of a review. To perform a review/audit, they need the balance sheet/income statement, and source data (it's okay that we don't have source data for Samurai because the amounts were small—"not material"). We can schedule a review/audit anytime during the year. Tax season is obviously busiest, easier to schedule other times of year. Driven by the demands of those requiring the reporting (regulated entities may have 90 or 120 days after close of year).

We adopted a policy for when to allow editing files; README update in https://github.com/gratipay/finances/pull/11.

The $1.50 payout could've been a loan from Chad to Gratipay if it had been repaid immediately. Since it wasn't, an owner investment is fine.

Okay!

**Comment by whit537** [comment]
In general, @kaguillera and I had the impression that Peter was pleased with what he saw. "This is an excellent month-closing process," he said of our PR approach. "[T]his is a good ledger," of our dat files. "These annotations here [referring to comments in the dat file] will be valuable not only for outside auditors, but for you internally when you go back and look at this a year from now." "What I like about GitHub is that it gives you a nice audit trail, something that QuickBooks only recently added." :dancer:

**Comment by whit537** [comment]
Am I missing anything, @kaguillera?

**Comment by whit537** [comment]
@kaguillera Ready to close this when you are. :)

**Comment by kaguillera** [comment]
LGTM. This can be closed. :+1:

**Comment by whit537** [comment]
!m @kaguillera

**Comment by whit537** [comment]
Oh! One thing I forgot to mention: we'll be able to schedule a review/audit once we are all caught up with the books (https://github.com/gratipay/finances/issues/3).

**Comment by whit537** [comment]
The bill came to $266, and we had $250 in a retainer. I got a bill for $16 and sent a check today.
