### ISSUE TITLE
1.0 payout for techtonik

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#363]
Hi, @whit537.

Can you send my balance to Bitcoin 1MECDWWHBViCgfe3NkrHnKxpjeo3qiyPNr for 1.0 payout? And also tell me exact decimal value so that I can see how much will be lost on the way. Manual test of the dead route, but still worthy info.

**Comment by whit537** [comment]
[Can't do bitcoin](https://github.com/gratipay/inside.gratipay.com/issues/201#issuecomment-102010517). How about [Transferwise](https://transferwise.com/) or a check in the mail?

**Comment by techtonik** [comment]
So, the summary is that route `Credit Card -> Bitcoin`.is illegal. What about Coinbase - they do it somehow? I can send a request to transfer from it.

**Comment by rohitpaulk** [comment]
From https://github.com/gratipay/inside.gratipay.com/issues/201#issuecomment-111029913 -

> @whit537 send an announcement why we killed Bitcoin. Am I right that it is because we tried to send stuff between Bitcoin to Credit Card (through Coinbase)? And for doing this we need a costly license of money transmitter. What was the last price, BTW?

> Getting licensed as a money transmitter means going through a lengthy and costly approval process ... 48 times. Because it's such a complex process, there is no fixed price; the order-of-magnitude estimate is "millions." It's the cost of producing web pages such as these:

> https://www.coinbase.com/legal/licenses

**Comment by techtonik** [comment]
Ok. So I need to create a PayPal account and follow the standard procedure.

**Comment by techtonik** [comment]
Created account, but it looks like I've missed the deadline. Is it possible to still jump in the train?

**Comment by whit537** [comment]
@techtonik Did you get your payout? We [lifted the deadline](https://medium.com/gratipay-blog/1-0-money-available-indefinitely-39c07bd031b).

**Comment by whit537** [comment]
Closing. 1.0 payouts are available indefinitely.
