### ISSUE TITLE
revise public disclosure policy

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#370]
@Hammadqureshi reports that public disclosure on H1 is unusual for companies to initiate, and is seen by researchers as a threat to their competitive advantage against other researchers.

Here's a listing of public disclosures: http://h1.nobbd.de/.

The suggestion is that we don't publicly disclose on H1, though disclosing elsewhere (Inside Gratipay?) would be more in line with H1 researcher expectations. Yes @Hammadqureshi?

**Comment by Hammadqureshi** [comment]
Yes.

**Comment by whit537** [comment]
I think we continue to disclose publicly, because we are an open company.
