### ISSUE TITLE
blog appears empty

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#371]
To: Our Friends at Medium
Subject: empty publication page!

> Greetings!
> 
> My publication's front page is empty!
> 
> https://medium.com/gratipay-blog
> 
> I surmise that this is because the "latest" stories have a date cutoff now. Is that right? If so, can we change that back? :-)
> 
> Thanks!

**Comment by whit537** [comment]
I've been going back and forth with Medium support on this. I believe it's still an open bug.

**Comment by whit537** [comment]
Yup, still open.

> So sorry! We didn't forget about you! It's taking longer than expected. I'll keep bugging people to get this solved.

**Comment by mattbk** [comment]
I can see things?

![image](https://cloud.githubusercontent.com/assets/3729038/12358587/8f22c16c-bb73-11e5-95f6-bacb32c9f4ec.png)

**Comment by whit537** [comment]
Yeah, I guess the bug is that it cuts off after a certain date. When we hadn't published in a while it was empty. Now it shows a few items but it should list the 10 most recent.

**Comment by whit537** [comment]
> Bump.

**Comment by whit537** [comment]
> Hello old friend,
>
We might have found what's causing this issue. Stories that came into the publication before a certain date are not in a good state. So they might not be showing up in the latest section. 
>
Can you try removing all of them and re-adding them?
>
Please let me know if this works.

**Comment by whit537** [comment]
> Yikes! Okay, I'll look into that, thanks for the tip. Will that reset the published date for those pieces?

**Comment by whit537** [comment]
> No worries! Their published date won't change.

**Comment by mattbk** [comment]
I think this ist still working, move to close.
