### ISSUE TITLE
Seems like Patreon got hit by FinCEN too

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#373]
https://www.reddit.com/r/KotakuInAction/comments/3e3w59/finally_received_a_response_from_fincen_about/

> The business in question, Patreon.com is not currently registered with FinCEN as a Money Services Business (MSB). Upon review, if our agency determines that the business meets the definition of a MSB as defined in the Bank Secrecy Act (BSA) regulations, we will take the proper steps to ensure that they are aware, and compliant with all of the BSA rules and regulations for MSBs. Thank you for your concern, and bringing this to our attention.

We need an issue explaining this stuff about MSB. And BSA sounds dangerous for any kind of open culture. Need to know what are they so secret about and why.

**Comment by whit537** [comment]
> It was brought up a while ago when GratiPay stopped taking money for 8chan and all of a sudden got a visit from FinCEN and had to change how their business worked to fall in line with the law and that Patreon was probably in a similar situation and isn't following the law.

https://www.reddit.com/r/KotakuInAction/comments/3e3w59/finally_received_a_response_from_fincen_about/ctb8vuu

> We need an issue explaining this stuff about MSB. And BSA sounds dangerous for any kind of open culture. Need to know what are they so secret about and why.

We've hashed this to death in multiple tickets (#192 #119 #201). I don't think we need another ticket about this.

**Comment by whit537** [comment]
P.S. Interesting (but unactionable) news items like this should be posted on [the Radar](https://github.com/gratipay/inside.gratipay.com/labels/Radar). :-)

**Comment by techtonik** [comment]
@whit537 this MSB BSA product is spread all over Github. I'd enjoy a single source of reference about that that I can link to.
