### ISSUE TITLE
HackerOne Submissions

### ISSUE THREAD

**Issue by Hammadqureshi** [gratipay/inside.gratipay.com#374]
How can i add someone who filled a duplicate to the original report ? Also how can i remove one ? @whit537 

reference : https://hackerone.com/reports/82267 reported a duplicate. Invited and them removed.

**Comment by whit537** [comment]
@Hammadqureshi Do you see an "(Add participant)" link in the sidebar?

![screen shot 2015-10-21 at 10 48 18 am](https://cloud.githubusercontent.com/assets/134455/10640109/429db8c2-77e1-11e5-9e1f-c29f365621e8.png)

**Comment by whit537** [comment]
@Hammadqureshi Also I think you can maybe add them when you close the bug as a duplicate.

**Comment by Hammadqureshi** [comment]
I see it. I will try it once we receive a duplicate submission.

**Comment by Hammadqureshi** [comment]
Closed for now.
