### ISSUE TITLE
So, how do we report spam?

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#375]
For example, https://gratipay.com/~jaklinbadr/

**Comment by mattbk** [comment]
There's the [suspicious] flag, but I don't know what happens after that.

**Comment by techtonik** [comment]
@mattbk I don't see where to set the flag in the new interface (which I like for its simplicity, BTW).

**Comment by mattbk** [comment]
It's on the bottom of the ~user profle image for me when logged in as admin (or whatever status I have).

**Comment by techtonik** [comment]
I don't see it, which means ordinary users can not report spam to us.

**Comment by mattbk** [comment]
Yup, it doesn't make sense.

**Comment by rohitpaulk** [comment]
Duplicate of https://github.com/gratipay/gratipay.com/issues/3060?

**Comment by techtonik** [comment]
@rohitpaulk could be the dupe, but there should be some manual way also if the button does not work. I also don't like "report user" name.

**Comment by mattbk** [comment]
This is the closest I've found: http://inside.gratipay.com/howto/handle-terms-violations, and the following are linked from there: https://github.com/gratipay/gratipay.com/issues/2992 and https://github.com/gratipay/gratipay.com/issues/3058.

**Comment by whit537** [comment]
Closing as a dupe of https://github.com/gratipay/gratipay.com/issues/3060.
