### ISSUE TITLE
Establish criteria for sending emails to all users

### ISSUE THREAD

**Issue by mattbk** [gratipay/inside.gratipay.com#376]
Many people didn't learn about the attempted 1.0 refund.  I'm sure there are other very important things that people haven't learned about this summer, either.

Are there rules that can be applied to determine how important a particular thing is and whether it is email-worthy?

**Comment by whit537** [comment]
For additional background, see: https://github.com/gratipay/inside.gratipay.com/issues/235.

**Comment by whit537** [comment]
With https://github.com/gratipay/gratipay.com/pull/3843 we'll have a way for users to unsubscribe from "News & Announcements." With that in place we could potentially adopt a more frequent schedule—should we announce every [blog post](https://medium.com/gratipay-blog/latest)?

**Comment by whit537** [comment]
Also, an announcement may not need to go to all users (in the case of the 1.0 refund we only needed to notify people with a balance).
