### ISSUE TITLE
apologize and communicate about the state of 1.0 money

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#380]
We didn't communicate well enough about the 1.0 refund (https://github.com/gratipay/gratipay.com/issues/3539):

 - https://twitter.com/GrahamDumpleton/status/655605545995382784
 - https://twitter.com/3v4l_org/status/655381901851664384<br>== https://gratipay.freshdesk.com/helpdesk/tickets/3284
 - https://twitter.com/st58/status/650115640162803712
 - https://twitter.com/twolfsn/status/652725466164539392<br>== https://github.com/gratipay/team-review/issues/85#issuecomment-148526556

Seems like we owe folks an apology, and probably an email. Let's start with a blog post ...

**Comment by whit537** [comment]
Here's a first draft: https://medium.com/gratipay-blog/sorry-for-the-bad-communication-541131a8392a.

**Comment by whit537** [comment]
How's that look, @mattbk @kzisme et al.?

**Comment by whit537** [comment]
> We have now upgraded our email notification settings to handle “News & Announcements,”

Note: that is a forward-looking statement. :-)

**Comment by mattbk** [comment]
It's straight to the point, but what do you actually mean by "settings to handle "News & Announcements""?

**Comment by whit537** [comment]
> what do you actually mean by "settings to handle "News & Announcements""?

Adding a checkbox here:

![screen shot 2015-10-21 at 5 01 00 pm](https://cloud.githubusercontent.com/assets/134455/10650041/5913bc62-7815-11e5-802b-09b650730515.png)

**Comment by whit537** [comment]
I dialed back the promises a bit and linked to https://github.com/gratipay/gratipay.com/pull/3843.

Last call for input before publishing ...

**Comment by kzisme** [comment]
Im good with it :)

**Comment by whit537** [comment]
@kzisme How does this look? Will this address the concerns people are expressing on Twitter?

https://medium.com/gratipay-blog/sorry-for-the-bad-communication-541131a8392a

**Comment by whit537** [comment]
Heh. :-)

!m @kzisme 

Okay! Here we go ...

**Comment by whit537** [comment]
Alright @kzisme, here is the final link:

https://medium.com/gratipay-blog/sorry-for-the-bad-refund-communication-f2daaef4d403

**Comment by whit537** [comment]
Updated to link to https://github.com/gratipay/inside.gratipay.com/issues/376.

**Comment by whit537** [comment]
@kzisme Can we talk a bit about communication tactics? [This tweet of ours](https://twitter.com/Gratipay/status/656892601698799617) displays a classic mistake of so-called "[outrage management](http://psandman.com/index-OM.htm)":

> Telling people to “Calm down!” is obviously not how this goal is best accomplished. The strategies that actually work turn out to be profoundly counterintuitive: apologizing for your mistakes, giving others credit for your improvements, acknowledging their grievances and concerns, etc.

[Sandman's site](http://psandman.com/) contains an overwhelming abundance of guidance on responding well to outrage. Revisiting it now, I notice he has a new-ish post up specifically about [outrage management on social media](http://psandman.com/col/social-media.htm):

>While the rise of social media has made outrage management more important (more obviously important and more short-term important), it hasn’t affected the basics. When outraged people are venting, what they have to say invariably includes a lot of crap. And it invariably includes valid grievances. In social media or anywhere else, the core of outrage management is still paying attention to people’s grievances, then echoing their grievances to show you have understood them accurately, and then validating the aspects of their grievances that have some validity – avoiding the temptation to rebut the invalid aspects (the crap) instead.
>
Outrage management is pretty obviously the right thing to do vis-à-vis the outraged person herself. Outraged people get more outraged when you ignore them or rebut them (even if – especially if – you’re right). But they often calm down when you validate their valid complaints.

How can we apply Sandman's [article](http://psandman.com/col/social-media.htm) to our current situation?

**Comment by whit537** [comment]
@kzisme I see we *do* apologize [here](https://twitter.com/Gratipay/status/656578906196201472), e.g. Maybe "Don't fret!" is okay in context. I do think we should respond individually to anyone who @mentioned us on Twitter about this, with a link to the [latest post](https://medium.com/gratipay-blog/sorry-for-the-bad-refund-communication-f2daaef4d403). Thoughts?

**Comment by kzisme** [comment]
@whit537 I'm sorry about that :/ 

After reading over Sandman's article it really does make sense.  I just worded the reply in that way since I've seen others in that manner.  

>It is a blessing in disguise that stakeholder outrage has become more and more dangerous to ignore, thanks mostly to social media.

I feel like addressing the problems sooner could be beneficial.  I think it took us (maybe) a week to gear the gears working with a blog post about the 1.0 refund. 

That ~or~ the tweets all came in around the same time.  

Being proactive is the best option and replying to those specific users with the newest post was my next action.

**Comment by whit537** [comment]
> I'm sorry about that :/

Honestly it's not a huge deal, I just noticed it and it reminded me of Sandman and then I found his social media article, which I think is great info for us! :-)

> [T]he core of outrage management is still:
>
 1. paying attention to people’s grievances, then
 2. echoing their grievances to show you have understood them accurately, and then
 3. validating the aspects of their grievances that have some validity – avoiding the temptation to rebut the invalid aspects (the crap) instead.

It *is* possible to go too far with this (I've seen Freshdesk's own customer support do this, for example; they come across as insincere and trying too hard), but I don't think that's our weak point yet. :-)

Hopefully Sandman's article addresses some of the concern you [articulated](https://github.com/gratipay/inside.gratipay.com/issues/364#issuecomment-147165710), that "Twitter is slightly irritating because it's like shouting across a busy street to someone and expecting them to hear your full thought..."

**Comment by whit537** [comment]
> Being proactive is the best option and replying to those specific users with the newest post was my next action.

Awesome. :-)

!m @kzisme 

> I feel like addressing the problems sooner could be beneficial. I think it took us (maybe) a week to gear the gears working with a blog post about the 1.0 refund.

You could be right. On the one hand we don't want to come out with a blog post too early, but we also don't want to be too late. The four tweets linked on the [post](https://medium.com/gratipay-blog/sorry-for-the-bad-refund-communication-f2daaef4d403) range from October 2—immediately after the deadline—through October 18. One thing we *didn't* do but could have is to make a GitHub issue specifically to discuss the problem, so that the process would go something like this:

 1. Receive negative feedback ("outrage") on Twitter.
 1. Immediately create a GitHub ticket to start discussing the problem in more depth.
 1. Use the ticket to monitor the issue, collect further Twitter conversation, and decide when a more formal communication (blog post, email [#376]) is called for and what it should be.

Does that sound right, @kzisme? Maybe we need a "Manage Outrage" howto ...

**Comment by whit537** [comment]
The nice thing about a GitHub ticket is that it can be pretty quick to create—much quicker than a blog post—and we immediately have something to offer the upset person: "Sorry for the mistake, working on a fix [here] (github)."

This all puts me in mind of Thing 7:

> Here’s an even more terrifying alternative I often recommend to clients – with no takers so far. Decentralize your social media response. Give your local frontline managers some outrage management training, and then authorize them to respond to social media complaints without needing to clear the response with corporate or legal. Or go whole hog: Authorize everyone in your organization, top to bottom, to participate freely in social media conversations about your organization – not as spokespeople but just as themselves, contributing their own knowledge, experience, and opinion. This guarantees the speed, spontaneity, and credibility that social media require and formal organizational responses can’t provide.
> 
It also guarantees that from time to time some employee will say something way off the mark, arousing brand-new outrage the organization will need to manage. I nonetheless believe this is what the future will look like: a conversational free-for-all via social media in which your organization’s formal voice will be just one of many, and your employees’ desire to join in whenever they choose will be unstoppable. That’s not such a bad future if your employees are well-disposed toward your organization and understand how to manage stakeholder outrage.
> 
Unfortunately, this era of decentralized social media responsiveness probably won’t come to pass until millennials take over your organization.

:-)

**Comment by whit537** [comment]
This is awesome, btw. I feel like we're developing an important capacity here. This is a pretty tame "crisis" (if we can even call it that), and this is a great chance to learn some skills and develop some policies that will serve us well in the future.

!m @kzisme @mattbk *

**Comment by kzisme** [comment]
>One thing we didn't do but could have is to make a GitHub issue specifically to discuss the problem, so that the process would go something like this:

I feel like each concern could/should have a ticket created for that user, and just sent the link to further speak about it.  (So I agree).  

So, when replying to these specific users (who were outraged) should I just link the newest blog post and tell them to have a look?

**Comment by whit537** [comment]
> I feel like each concern could/should have a ticket created for that user

So for the four linked on "[Sorry for the Bad Refund Communication](https://medium.com/gratipay-blog/sorry-for-the-bad-refund-communication-f2daaef4d403)," would you have made four GitHub tickets, or one?

> [S]hould I just link the newest blog post and tell them to have a look?

Yeah, I would propose that we:

 1. Send out a general message "Hey, sorry for the bad communication, etc., etc. [link]."
 2. Reply specifically to each individual user ([magic of mentions](https://github.com/gratipay/inside.gratipay.com/issues/368#issuecomment-148494856) ;-) who said something "@mention Here's a follow-up, sorry again, etc. etc."

We on the same page? Or what was your plan?

**Comment by kzisme** [comment]
Would that be useful in the long run?  (Creating a specific ticket per user to further talk about issues and concerns from Twitter or other outlets?  

>So for the four linked on "Sorry for the Bad Refund Communication," would you have made four GitHub tickets, or one?

Yup!  As long as that is the newly desired action to "outrage".  If this is the desired reaction then there are a few more questions I have.  

> Yeah, I would propose that we:....

Yup!  

1. New tweet sending out the new blog post addressing the problems/concerns. 
2. Individually address users who had issues and direct them to the new post.  

We're on the same page I think :page_with_curl:

**Comment by kzisme** [comment]
Do you think opening a ticket for each user to address possible outrage @whit537 or is that a little too much action on our end?

**Comment by whit537** [comment]
@kzisme IMO it's a little too much. I think since they all have the same concern, one ticket is enough. And I think this is that ticket. :-)

Thoughts?

**Comment by kzisme** [comment]
@whit537 Sorry for the late reply - been a busy past couple of days.  I've reached out to a few of the users who were confused/outraged and posted the blog post as well.  

I'll close this for now but this is a useful ticket if we encounter outrage in the future :+1:

**Comment by whit537** [comment]
Nice work! !m @kzisme. :-)
