### ISSUE TITLE
go to Platform Cooperativism

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#384]
http://platformcoop.net/

They bagged Stallman(!).

**Comment by whit537** [comment]
I've registered.

I have an Airbnb pending for $112.

Megabus will be $70 to $100.

I'm emailing the organizers to ask about sponsorship opportunities. Based on that I expect to ask if Gratipay can cover some or all of this. I'll go even if Gratipay can't cover it.

**Comment by whit537** [comment]
>Nathan,
>
Chad Whitacre here from [Gratipay](https://gratipay.com/) (née Gittip). I just registered for Platform Cooperativism! You had me at Stallman. ;-)
>
Are there any sponsorship or partnership opportunities still available? What do those look like?
>
chad
>
P.S. Tracking on our side [here](https://github.com/gratipay/inside.gratipay.com/issues/384).

**Comment by whit537** [comment]
Room is booked.

**Comment by whit537** [comment]
Trying to set up drinks with an acquaintance for the 12th, waiting to finalize bus ticket until I hear back.

**Comment by whit537** [comment]
> So glad you'll be there! Good to hear from you.
>
We're getting pretty close to the wire here, so it may be hard to fully recognize the sponsorship in the program and so forth. Sponsors have generally contributed between $3-10K. Some are in-kind, such as taking care of livestreaming or covering travel for key speakers. And I think since we're so close to the end of the preparation process, the Partner category wouldn't really make sense. 
>
In any case, it would be great to have your support in getting the word out about this crazy event.

**Comment by whit537** [comment]
@kzisme Can you help promote https://twitter.com/platformcoop (as you deem appropriate) over the next couple weeks?

**Comment by whit537** [comment]
> Fair enough. $3k+ is out of our budget, anyway. :-)
>
I've [asked](https://github.com/gratipay/inside.gratipay.com/issues/384#issuecomment-152071692) our Twitter guy to help promote the event, and I'll look forward to meeting you in person in a couple weeks! Keep up the great work!

**Comment by whit537** [comment]
> Great, thanks! I appreciate the outreach. Be well!

**Comment by kzisme** [comment]
@whit537 Will do :)

**Comment by kzisme** [comment]
@whit537 Is this an event or is it just a talk?  I'm trying to find more info on it to write some posts for it, but am having trouble.

**Comment by whit537** [comment]
@kzisme It's a two-day event in New York, trying to steer the "sharing economy" away from corporate interests (Airbnb, Uber, etc.) and more towards collective ownership.

**Comment by kzisme** [comment]
@whit537  Sent out a few tweets :)

**Comment by whit537** [comment]
Nice, thanks! :-)

**Comment by whit537** [comment]
This is in a few days. I'd better book a bus! :)

**Comment by whit537** [comment]
Done. $67.50. Heading out Thursday during the day, heading back Saturday overnight.

**Comment by whit537** [comment]
> Trying to set up drinks with an acquaintance for the 12th

P.S. Fell through.

**Comment by whit537** [comment]
> If platform coops are our only hope, then we’re in big trouble. The movement is in its infancy. There are several fundamental, interrelated legal, financial, and organizational challenges to the process of forming platform coops. New organizational forms need to be worked out, which will take years. Meanwhile, Death Star platforms will conquer more territory at a new, faster version of Internet time. Their global blitzkrieg will continue apace.
>
The aforementioned conference, [Platform Cooperativism](http://platformcoop.net/), hopes to address this through what organizers are calling a coming out party for the cooperative internet.

http://www.shareable.net/blog/how-platform-coops-can-beat-death-stars-like-uber-to-create-a-real-sharing-economy

**Comment by whit537** [comment]
> Over 1,000 people have registered.

!

**Comment by whit537** [comment]
@kzisme Consider retweeting https://twitter.com/Shareable/status/663046884752142336 and https://twitter.com/platformcoop/status/664246257309712384 and in general cross-promoting @Shareable along with @platformcoop. Ya?

**Comment by whit537** [comment]
To: Neal Gorenflo
Subject: see you this weekend?

Chad Whitacre here from Gratipay. Last we touched base you had just returned from OuiShare and we had just relaunched as Gratipay 2.0.
>
I'm writing because I just finished "Death Stars" and I'm all fired up! Platform Coops is definitely something Gratipay wants to contribute to.
>
I'm planning to be at Platform Cooperativism this weekend. I don't see your name on the participants list ... are you going to be there? I'd really love to buy you lunch ...

**Comment by whit537** [comment]
To: Nathan and Trebor
Subject: Room for one more? :-)

> Nathan and Trebor,
>
I'm really excited to attend Platform Cooperativism this weekend! Thanks for all your hard work putting this event together! :D
>
I'm writing to ask: Is there any chance you'd be willing and able to add [Gratipay](https://gratipay.com/) to the Ecosystem Infrastructure panel on Saturday morning?
>
Gratipay is a payments platform for cooperative projects (more or less). We've processed $1,000,000 since launching three years ago, and currently process about $5,000 monthly for ~120 "teams," including [Sudo Room](https://gratipay.com/sudo-room/).
>
Three distinctives:
>
 1. We are an "[open company](http://inside.gratipay.com/big-picture/welcome)," blurring the lines between users, collaborators, owners, and staff.
 1. We invented "[take-what-you-want](https://gratipay.com/about/features/payroll)" salaries to solve the problem of distributing revenue when those lines are blurred.
 1. We don't take a cut of payments—we are funded on our own platform via pay-what-you-want.
>
I'm really excited about Platform Cooperativism and would love for Gratipay to be a part of this movement right from the outset, if possible. So waddya say? Is there room for one more on the Ecosystem Infrastructure panel? If not, is there another way Gratipay could participate?
>
One way or another, I will see you on Friday! Keep up the great work! :-)

**Comment by whit537** [comment]
From: Neal

> Chad, thanks so much for reading my post, the offer of lunch, and your generous recurring donation [note: I set up $10/mo from personal].  All of this made my day.
>
Unfortunately, I can't make the conference, the timing just didn't work for me.  I would love to go.  Perhaps we can Skype after.  Curious about the latest version of Gratipay.

To: Neal

>Ah, well. I suspected that might be the case, since you weren't listed as a participant. :-)
>
Instead of Skype, would you be at all open to a "Hangout On Air" that would be live-streamed and archived on YouTube? That would make our conversation more shareable, as it were. ;-)

I'll track this further on [the Radar](https://github.com/gratipay/inside.gratipay.com/labels/Radar).

**Comment by whit537** [comment]
From: Nathan

> It's good to hear from you, and I appreciate you spelling out the connections between Gratipay and Platform Cooperativism. I'm afraid that we are way too late in the game to add someone new to the session. The programs are already printed, and we are already pushing our time limits as it stands. If someone drops out at the last minute, I could look into the possibility of adding you in their place. But for the moment, the only opportunity would be for you to sign up to hold a 50-minute small workshop for interested people. If you're interested, let me know which slot you'd like from these choices:
>
http://platformcoop.net/schedule/friday-workshops
http://platformcoop.net/schedule/saturday-workshops
>
It could be great, for instance, to have a workshop on the idea of the "open company," which I think is an important model that I'd love to see more people exposed to.

**Comment by whit537** [comment]
To: Nathan

> Thanks, Nathan. Understood. I haven't had good luck with the open-space workshop format at other conferences. In my experience, it's too hard to build enough buzz around a last-minute, quasi-formal session to see significant attendance. I'll look forward to promulgating open companies and learning from others in the hallway track! :-)
>
Keep up the great work! Almost there!

**Comment by whit537** [comment]
Any objections to Gratipay reimbursing me for the Airbnb and Megabus expenses?

| Description | Amount ($) | 
|:------|-------:|
| Airbnb | 112.00 |
| Megabus | 67.50 |
| **Total** | **179.50** |

And, any objections to me expensing Gratipay for food and incidentals once I get back?

**Comment by whit537** [comment]
> And, any objections to me expensing Gratipay for food and incidentals once I get back?

Actually: Any objections to me paying w/ the Gratipay card while I'm out there?

**Comment by whit537** [comment]
Who do you want me to meet while I'm there?

http://platformcoop.net/participants

**Comment by webmaven** [comment]
No objection from me. :wink:

**Comment by whit537** [comment]
@webmaven Thanks! :grin:

**Comment by whit537** [comment]
> They bagged Stallman(!).

[Ish](http://platformcoop.net/schedule/special-lunch-session-with-richard-stallman). :-/

**Comment by kzisme** [comment]
@whit537 Sorry for the slow reply!  re-tweeted both and posted once again about the event :)

**Comment by whit537** [comment]
@kzisme Thanks! :-)

**Comment by techtonik** [comment]
No objections. An awesome place to be inspired! =)

**Comment by whit537** [comment]
Thanks @techtonik! Turned out to be an *awesome* conference. Hoping to write up a report here now that I'm back online ...

**Comment by whit537** [comment]
[Platform Cooperativism](http://platformcoop.net/) was *great*. Recalling my experience of [frustrated potential](http://whit537.org/2012/09/fame-diverse-but-could-have-gone-deeper) at XOXO 2012, I implemented a suggestion I [picked up](https://github.com/gratipay/inside.gratipay.com/issues/364#issuecomment-145543317) from *Traction* (p. 181):

> **Schedule meetings and dinners ahead of time.** Identify your top targets and find a way to engage them individually at the show.

I didn't schedule any meetings ahead of time, but I did go through all the speaker profiles and identify 17 that seemed especially worth meeting or hearing for one reason or another. A new conference friend commented towards the end of the second day, "You really prepared a lot for this conference, didn't you?" I showed them the 80+ pages I had printed out and read on the bus ride to New York. :-)

Of course, there was plenty of serendipity as well. Right off the bat, I was completely surprised when a New School freshman (unaffiliated with the conference) called out my name on the stairway, and she turned out to be an old friend's daughter(!). Later on, I ran into a couple Pittsburgh friends attending the conference, Ron and Eva from the [Pittsburgh Chamber of Cooperatives](http://pittsburghchamber.coop/), with whom I had coffee. I drank on Friday night with Plone old-timer Jonah Bossewitch, and met new friends like Tom, Spud, A.D, and Theis. I also punched a lot of pennies with people! They were a hit particularly with the security guards. :-)

I discovered a healthy undercurrent of Gratipay awareness, right from the opening session, where I landed next to @tlevine. A Gratipay lurker, he is interested in helping @kaguillera with accounting. :dancer: @tlevine joked, "Everybody knows about Gratipay." I replied, "Wow! Really?" and then the guy in front of us (Jack; didn't get his last name or username) turned around and raised his hand and said, "I know about Gratipay!" We promptly punched pennies. :-) I later found myself in conversation with Joel Dietz (of [Swarm](https://swarm.fund/)), Jerry Michalski (of [REX](http://therexpedition.com/)), and Peter (missed his last name and affiliation). [Joel](https://gratipay.com/~fractastical/) and [Jerry](https://gratipay.com/~jerrymichalski/) were familiar with Gratipay. Max Dana, founder of a new project called [External Revenue Service](http://externalrevenue.us/), was like, "Yeah, a lot of people are telling me to check out Gratipay." ERS is aiming in roughly the same direction as Gittip/Gratipay 1.0 was (pay-it-forward gifts to individuals). I wished him good luck, and gave him a hard time for not having written any code yet. :-) Janelle Orsi, a lawyer and founder of the [Sustainable Economies Law Center](http://www.theselc.org/), reminded me that she had participated in #192 (her first time commenting on someone else's GitHub repo, I was flattered to learn), as had @mitar "the fish." :fish:

By far, though, the most important moment of serendipity was when I struck up a conversation with [Sumana Harihareswara](http://www.harihareswara.net/), a tech feminist who was broadly familiar with the Gittip Crisis (though she wasn't herself a Gittip user). She was generous enough to skip the final plenary on Friday for a lengthy conversation about the Gittip Crisis and Gratipay's response to it (#319). She has *just* started a consulting company called Changeset to help open source projects with emotional labor, and I've asked her to send us a bill for the time she spent. If it doesn't make sense for Gratipay to cover it, I'll cover it personally.

So much, then, for serendipity. As to my planned goals: one was to connect with lawyers, particularly those who might be able to help us with #242. To that end, I attended a legal workshop offered by Janelle. She's not taking new clients, but she may be able to help us find the right person when the time comes. I also went to a panel on legal issues. I didn't introduce myself to anyone since they were mostly focused on unions.

Another reason I didn't end up introducing myself to more lawyers is that I came to see, over the course of the conference, that #242 is but one of six major areas of work in front of us. I found myself wanting to zoom out and look at the big picture before pushing further on any one.

1. ~~legal foundation for payments~~ addressed in Gratipay 2.0
1. ~~community management~~ addressed in Gratipay 2.0
1. accounting (#367)
1. governance (#72)
1. legal foundation for payroll (#242; entangled with governance)
1. tech debt (e.g., https://github.com/gratipay/gratipay.com/issues/3617, https://github.com/gratipay/aspen.py/issues/526)
1. product development
1. marketing

With our abundance of work top-of-mind, I listened to Robin Chase, founder of Zipcar and author of *Peers, Inc.*, make a plea for urgency (all the more urgent because of Paris): "Hasten evolution to avoid revolution." Most of her audience preferred revolution. I heartily agree with her. Interestingly, she was also one of the few folks present (Meetup founder and CEO Scott Heiferman being another) with real experience scaling a platform. Robin pushed back on the conceit, prevalent at the conference, that if only we sprinkle enough blockchain on an open-source municipal decentralized autonomous cooperative, we can Facebook Uber's MySpace. Building platforms is incredibly hard work, and, in Robin's view, requires pragmatism ... and capital.

Last time we looked at taking venture capital (#68) was under Gittip/Gratipay 1.0. The reason we couldn't then was that accepting money from investors would dilute the incentive for anyone *else* to give to Gratipay. Gifts to Gratipay under 1.0 were no-strings-attached. Why should I give expecting nothing in return, when others are giving and earning interest? Under Gratipay 2.0, payments now have strings attached: we are asking people to voluntarily pay Gratipay because of the service we are providing. It occurred to me while I was at the conference that this difference may be significant enough to reopen the discussion with VCs.

[The Collaborative Fund](http://www.collaborativefund.com/) is the VC firm I'm aware of whose rhetoric most closely aligns with ours (USV would be the second; https://github.com/gratipay/gratipay.com/issues/239). Jessica Jackley (#334) is involved. [Kanyi Maqubela](http://kanyi.me/) is as well, and I introduced myself to him after the financing panel on which he sat. He agreed to schedule an open call. On the flip side, Jerry Michalski has agreed to introduce us to Robin. If we're entering into discussions with VCs, it would be great to have someone like her help us navigate the process.

Whether or not we take venture capital, we also need to find more paying customers. I think [Loomio](https://www.loomio.org/) should be a customer of ours, so I introduced myself to [MJ Kaplan](http://blog.loomio.org/2014/03/15/our-people-from-across-the-seas-mj-kaplan/). In general, I think Enspiral and Loomio are doing great work and I'd love to partner with them. Maybe we can look at Loomio for making governance decisions (cf. #72)?

Honestly, speaking of exposure and marketing, Gratipay should've been on stage at this conference. The only reason we weren't was a simple lack of awareness in the right circles (as I say, there *was* an undercurrent of awareness). One of my main goals, therefore, was to get on the organizers' radar, so that we're part of the conversation in the future. I did briefly shake Trebor's hand, but I have slightly more history with Nathan, so I focused on connecting with him. Obviously, he was swamped with responsibilities during the conference, but I was able to interact with him a few times, and sat next to him during Michel Bauwen's videocast. Afterwards, I went ahead and laid it out for him:

> Swarm raised $1M *for themselves* with mostly a TC Crib to show for it. External Revenue Service has written zero lines of code. Gratipay has processed $1M *for actual customers* for 3+ years. Why put Swarm and ERS onstage and not Gratipay? When I read your stuff I'm filled with panic because I feel like, "Ah!!!!!! We've been doing and talking about exactly this for years!!!!"

He responded:

> The first I understood how deeply Gratipay is aligned with what we're talking about here was when you emailed me three days ago [see above at https://github.com/gratipay/inside.gratipay.com/issues/384#issuecomment-155659417]. Let's have a call in a couple weeks and work on this.

Phew! On top of everything else that happened, I consider that a resounding "mission accomplished" for Gratipay at Platform Cooperativism. :dancer:

**Comment by whit537** [comment]
Reopened #68, and reticketed conversations with Kanyi (#397), Robin (#398), and Nathan (#399).

**Comment by mitar** [comment]
Have you talked to [Robin Hood](http://www.robinhoodcoop.org) people? It might be interesting for you.

Anyway, nice meeting you in person. :-)

**Comment by rohitpaulk** [comment]
!m @whit537 :)

**Comment by kzisme** [comment]
I'm glad you were able to attend for Gratipay @whit537 !m :)

**Comment by techtonik** [comment]
Nice report. Where do you get those expenses stuff? Is it copy/paste from some HTTPS admin or could be automated?

**Comment by tlevine** [comment]
I wasn't joking.

**Comment by whit537** [comment]
> Have you talked to Robin Hood people? It might be interesting for you.

No, but those folks were amazing. When they were on stage I had a hard time figuring out if they were completely bullshitting or just partially bullshitting. :-)

> Anyway, nice meeting you in person. :-)

Definitely! Likewise! :dancer: Good luck poking the dinosaur out there in Berkeley. ;-)

> Where do you get those expenses stuff? Is it copy/paste from some HTTPS admin or could be automated?

Copy/paste from PNC's website. Once we're up and running with financial statements (#390) these sorts of things will be reflected there.

> I wasn't joking.

Corrected. :-)

> ($1.69?)

I remembered: I bought a bottle of water on the overnight back to Pittsburgh.

**Comment by whit537** [comment]
Jay Cassano's write-up in Shareable: "[Platform Cooperativism Conference Disrupts Silicon Valley's Disruptions](http://www.shareable.net/blog/platform-cooperativism-conference-disrupts-silicon-valleys-disruptions)."

**Comment by whit537** [comment]
From: Kenneth

> Thanks for reaching out and it was great to meet you this past weekend! I do have images of the penny punching at the reception and can provide you a contact sheet. Do you have any idea how you may wish to use the images? This will give me a better idea as to licensing. 

----------

> I'd like to use one of the images on this Medium post:
>
https://medium.com/gratipay-blog/a-platform-cooperative-almost-94cd5900840f

**Comment by webmaven** [comment]
Related to Platform Cooperativism in concept (although there seems to be some overlap in people and groups): https://medium.com/enspiral-tales/doing-more-together-together-seeding-a-collaborative-technology-alliance-82243ea30d41

**Comment by webmaven** [comment]
Nice list of fellow-traveller orgs: http://platformcoop.net/schedule/owning-is-the-new-sharing-actually-existing-platform-co-ops

**Comment by webmaven** [comment]
List of projects in the CTA: https://cta.hackpad.com/Tools-projects-and-initiatives-of-the-CTA-zJkyGIUZtEc

**Comment by whit537** [comment]
Found some photos!

https://www.flickr.com/photos/treborscholz/albums/72157661354244001

**Comment by whit537** [comment]
[![22482888794_55f53f7f4d_c](https://cloud.githubusercontent.com/assets/134455/11288786/c83230ec-8ef4-11e5-9127-5219e0b39c91.jpg)](https://www.flickr.com/photos/treborscholz/22482888794/)

Janelle's legal workshop ...

[![22687270647_c095822e73_c](https://cloud.githubusercontent.com/assets/134455/11288807/e623e85c-8ef4-11e5-9eb5-6d6754970bbc.jpg)](https://www.flickr.com/photos/treborscholz/22687270647/)

... with @mitar (that's the back of his head :).

----

[![22687374887_f31fa6ce52_c](https://cloud.githubusercontent.com/assets/134455/11288821/f45d1b00-8ef4-11e5-9f7e-d1851d632134.jpg)](https://www.flickr.com/photos/treborscholz/22687374887/)

Putting a bug in Doug Rushkoff's ear. ;-)

------------

[![23052786152_b6a9a1d696_c](https://cloud.githubusercontent.com/assets/134455/11288927/ee4413c6-8ef5-11e5-9e2d-fa68d86bbad3.jpg)](https://www.flickr.com/photos/treborscholz/23052786152/)

Jack! "I know about Gratipay!"

----------

[![22688324087_0d1101e62c_c](https://cloud.githubusercontent.com/assets/134455/11288984/6efa6434-8ef6-11e5-94c2-106b60116213.jpg)](https://www.flickr.com/photos/treborscholz/22688324087/)

[![23079593146_afd2c9b7f0_c](https://cloud.githubusercontent.com/assets/134455/11288870/70facfe0-8ef5-11e5-93fb-f0619591118e.jpg)](https://www.flickr.com/photos/treborscholz/23079593146/)

Punching pennies! :dancer:

**Comment by whit537** [comment]
To: Trebor
Subject: permission to use photo?

> Great work on Platform Cooperatives! It was a stimulating time, catching up with some old friends and meeting many new ones.
>
I'm writing to ask permission to use a photo from your Flickr account in Gratipay's blog post about the conference. Here's the photo:
>
https://www.flickr.com/photos/treborscholz/23079593146/
>
And here's the (draft) post:
>
https://medium.com/gratipay-blog/a-platform-cooperative-almost-94cd5900840f
>
I'm happy to provide attribution, of course. :-)
>
Would you be okay with this usage?

Not sure how this will interact with my conversation with Kenneth, whom I haven't heard back from as of yet.

**Comment by whit537** [comment]
From: Trebor

> Sure. The photographer's name is Kenneth Ho.

---------

> Thanks, Trebor!

**Comment by whit537** [comment]
To: Kenneth

> I found this one in Trebor's Flickr:
>
https://www.flickr.com/photos/treborscholz/23079593146/
>
What would be the cost to use that one in our Medium post?
>
https://medium.com/gratipay-blog/a-platform-cooperative-almost-94cd5900840f
>
I'd like to get this taken care of, so I can get the blog post out the door tonight or tomorrow at the latest.
>
I approached Trebor as well (he has the photos listed as BY-NC-SA), and he was fine with us using it. At this point I'm not sure how to proceed, whether Trebor has the right to the photos or you do. Let me know ...
>
Thanks, Kenneth! :-)

**Comment by whit537** [comment]
Reopening until the blog post is live, I guess. :)

**Comment by whit537** [comment]
Alright, so Trebor's response indicates that he thinks he can grant permission to use the photo. If I don't hear back from Kenneth by tomorrow I'll proceed on that understanding (i.e., I'll publish with the photo), and we can handle Kenneth's reply as it comes.

**Comment by whit537** [comment]
From: Kenneth

> Hey Chad, 
>
I have rights to the image. Please see [attached](https://github.com/gratipay/inside.gratipay.com/files/39718/Lightroom.2015-11-14_TNS_Coop084.CR2.and.15.others.pdf). We can certainly get you that image that you’d provided the link to. I just ask that you provide a link back to my website and use the image I’ll provide you with (watermarked).

Okay! Proceeding with that ...

**Comment by whit537** [comment]
![2015-11-14_tns_coop095](https://cloud.githubusercontent.com/assets/134455/11290888/a90b2b38-8f08-11e5-8ec1-0ea252aa6537.jpg)

**Comment by whit537** [comment]
To: Trebor

> We ended up using a watermarked version from Kenneth. The write-up is live. We're planning to post it to Twitter tomorrow.
>
https://medium.com/gratipay-blog/a-platform-cooperative-almost-94cd5900840f
>
Cheers! :-)

**Comment by whit537** [comment]
> Nice list of fellow-traveller orgs presented at the conference: http://platformcoop.net/schedule/owning-is-the-new-sharing-actually-existing-platform-co-ops

P.S. @webmaven That was the session Sumana and I skipped. Opportunity cost! :-/
