### ISSUE TITLE
Email spoofing

### ISSUE THREAD

**Issue by Hammadqureshi** [gratipay/inside.gratipay.com#386]
The report https://hackerone.com/reports/93157 on HackerOne is about spoofing emails of gratipay.com. This is basically a missing best practise issue which advise the web application to use "-" instead of "~"
in the SPF record. 
It is a misconfiguration. Even google is also using ~ instead of -. 
Suggestions ?

**Comment by whit537** [comment]
I've responded on HackerOne. Let's keep security conversations there, please.

**Comment by Hammadqureshi** [comment]
OK
