### ISSUE TITLE
reapply for a Shuttleworth Fellowship

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#388]
https://www.shuttleworthfoundation.org/applications/

Previous attempts: [2012](https://github.com/gratipay/gratipay.com/issues/297), [2013](https://github.com/gratipay/gratipay.com/issues/704).

### Drafts
- [application form](https://www.shuttleworthfoundation.org/application-form/)
- [**working draft**](https://docs.google.com/document/d/1oHPUEdyu4c5bZmGwwt-G4bOApVFlpRJ0La7R-BJwuno/edit?usp=sharing)
- [draft 2](https://docs.google.com/document/d/1muPQ4JqaM4nnsqwfhmiB2f4eRGTxy-PHUeLdkpLtWV8/edit?usp=sharing)
- [draft 1](https://docs.google.com/document/d/1cJP99JtfPCRMrII4oWsbEx2ihfrrdLyG5fjeKL64oOg/edit?
usp=sharing)

### Todo
- [x] video
- [x] resume
- [x] dozens?

**Comment by whit537** [comment]
> Applications for the September 2016 fellowship intake open on 1 December 2015.

**Comment by kzisme** [comment]
I hope this works out :)

**Comment by techtonik** [comment]
I'd like to participate to clean the obstacles for cross-border funding of open source projects. Doing this requires researching legal requirements in different countries, but we can make a simple framework that people in these countries can follow to find out how it works for them.

**Comment by whit537** [comment]
Applications are open: https://www.shuttleworthfoundation.org/application-form/.

**Comment by whit537** [comment]
Due April 1.

**Comment by techtonik** [comment]
I can't wait so long.

**Comment by whit537** [comment]
@techtonik Yeah, this isn't instant gratification. :)

**Comment by techtonik** [comment]
I need to find some funding very quick and every grant program requires to fill a lot of papers and wait a year or more. And I need something to eat in two weeks and if I won't find anything close to Gratipay, I will have to reformat my neural network back to comply with corp. ethics and workflow. It is sad.

**Comment by whit537** [comment]
> Applications for the March 2017 fellowship intake close on 15 October 2016.

https://shuttleworthfoundation.org/

**Comment by whit537** [comment]
I really want to get to this.

**Comment by whit537** [comment]
Alright! https://github.com/gratipay/inside.gratipay.com/issues/836 is in, this one is next. :shamrock:

**Comment by whit537** [comment]
The deadline was extended to November 1 in https://github.com/ShuttleworthFoundation/shuttleworthfoundation.org/commit/88950cb530184bdfe1da69c4d56f7a7c5a5402ad.

**Comment by whit537** [comment]
I just watched a couple Cory Doctorow interviews because he the final boss of Shuttleworth this year and I've never really engaged with his work too much.

https://www.youtube.com/watch?v=E4y3btcBD-o
https://www.youtube.com/watch?v=ZEEgb1cAwvk

He is a very articulate person. 😶

**Comment by techtonik** [comment]
My association with all that that simple payment system with taxes is good, but bears is no interests to anyone, because it is a simple commercial project (despite of openness), but if you read about Aaron Swartz, there could be more to add into that.

**Comment by whit537** [comment]
https://changelog.com/podcast/221

**Comment by whit537** [comment]
http://www.crimeflare.com/doctorow.html

Wow. Prescient.

**Comment by whit537** [comment]
https://www.shuttleworthfoundation.org/application-pointers/

Most of the advice is "what not to do." The one relevant one (emphasis mine):

- “The Facebook for…” or “Like a social networking site for…”: Facebook and other social networking sites exist. They are theme agnostic and allow you to engage with others around any topic/theme/identity of your choosing. They also already have millions of users. Why does your theme/topic/subset of people need their own site? Why can’t they just use Facebook or similar? What will make this specific group come to your version? How will you let them know about it? **Same goes for “crowdfunding platform for…”.**

The positive advice:

- Address your application to us and customise it accordingly. Generic proposal material does not tell us why we should specifically support you.

- Let us understand your context. Making it as real as possible allows us to understand your frustrations and see the applicability of your solution.

- Openness is not an add on. It is a fundamental approach to both participation and intellectual property. Other than that, there are no absolute rules, only strong suggestions.

Re: video:

- Picture quality on your video is less important than sound quality. If we are distracted by trying to understand what you say, your message will not come across.

- When compiling your video, assume the viewer has not read your documentation. Set the scene, but ensure that you mention your specific idea as early as possible in the video.

- Focus on what you want to do next. We would like to hear about how far you’ve come, but this is not a history lesson. It is a pitch on how you are going to change history.

**Comment by whit537** [comment]
Also:

- We want to support the exploration of a specific solution to a specific problem[.] We are looking for a specific result in change in behaviour.

**Comment by whit537** [comment]
> Any guidance on how many applications are expected? And how many will be on the shortlist that @/doctorow sees? Would you be able to provide any examples of successful past applications, to illustrate https://www.shuttleworthfoundation.org/application-pointers/?

https://twitter.com/whit537/status/786213273045651456
https://twitter.com/whit537/status/786220556471250944

**Comment by whit537** [comment]
From my current draft:

> During our initial run, we had dozens of tech companies on board, including Stripe, Heroku, Digital Ocean, and Khan Academy.

Dozens? Really?

**Comment by whit537** [comment]
Okay! Draft 2 ready for [review](https://docs.google.com/document/d/1oHPUEdyu4c5bZmGwwt-G4bOApVFlpRJ0La7R-BJwuno/edit?usp=sharing). I was looking at the wrong number on the character count and went over the 1500-character limit on some of the answers, so I'll have to revise those down. I also need a resume, a video, and a fact-check on the number of tech companies we had on Gittipay 1.0.

**Comment by whit537** [comment]
>> Any guidance on how many applications are expected? And how many will be on the shortlist that @/doctorow sees?
>
We have no quota, we see what we get in any given round and shortlist what we believe in. Average success rate is 1/100.

https://twitter.com/ShuttleworthFdn/status/786464006882156544

>> Would you be able to provide any examples of successful past applications, to illustrate https://www.shuttleworthfoundation.org/application-pointers/?
>
We have the successful candidates on our site https://www.shuttleworthfoundation.org/fellows/  Some of their application videos are still on YouTube. Best advice is to submit what YOU think is right. We want to fund your idea, not your idea of what you think we want to see.

https://twitter.com/ShuttleworthFdn/status/786463033073762304
https://twitter.com/ShuttleworthFdn/status/786463428764368896

**Comment by whit537** [comment]
> Some of their application videos are still on YouTube.

Here are the videos I found by searching for "shuttleworth $name" on YouTube, representing 26% (10 / 39) of current and past fellows. Some are reapplications for additional funding.

| Fellow | Link |
|:--------|:--------|
| Isha Datar | https://www.youtube.com/watch?v=l9DPaa9rssg |
| Peter Cunliffe-Jones | https://www.youtube.com/watch?v=8pHecygUPu4 |
| Aaron Makaruk | https://www.youtube.com/watch?v=qalD--ZkAwg |
| Johnny West | https://www.youtube.com/watch?v=lEQ4ZF8RiLQ<br>https://www.youtube.com/watch?v=H6dv5LDVlA0<br>https://www.youtube.com/watch?v=24q_TUeX_fY<br>https://www.youtube.com/watch?v=7vagys3gPpg<br>https://www.youtube.com/watch?v=LIcDKMzOBX4<br>https://www.youtube.com/watch?v=v5nbCI8SBls |
| Luka Mustafa | https://www.youtube.com/watch?v=bRgUJiXQ7QQ |
| Peter Murray-Rust | https://www.youtube.com/watch?v=HZ8qkKNMvWA |
| Rory Aaronson | https://www.youtube.com/watch?v=s6aSElNmVUU |
| Daniel Lombraña González | https://www.youtube.com/watch?v=LuKAXLJo8gE |
| Marcin Jakubowski | https://www.youtube.com/watch?v=nr2xJbD49lo |
| Kabir Bavikatte | https://www.youtube.com/watch?v=rt5IjgOWTm8 |

**Comment by whit537** [comment]
Alright, the video is a lot more work here than over in #836. It's five minutes instead of one, and doesn't have constraints around production quality.

**Comment by whit537** [comment]
Shuttleworth CEO on the fellowship program: https://www.youtube.com/watch?v=-pX2Kv-y_PE

**Comment by whit537** [comment]
"access to knowledge and information"

**Comment by whit537** [comment]
I wonder how current that is. Video dates from 2012.

**Comment by whit537** [comment]
(Because we're not really about access to knowledge and information and education. 😶 )

**Comment by whit537** [comment]
I think we should build this around open work.

**Comment by whit537** [comment]
Started a separate doc for the [video script](https://docs.google.com/document/d/1YLqskSd0SrSqaUWAVhELY0lFZ3tNaeQ3LFU6ES3a_5A/edit?usp=sharing).

**Comment by whit537** [comment]
I've asked a friend if he has a camera I can borrow.

**Comment by whit537** [comment]
He said to use an iPhone. :-)

@kaguillera makes the point that even if I rerecord a different video for this than for next week's [lightning talk](https://github.com/whit537/openorg/issues/6), I could/should try to write the content to highly overlap between the two as an optimization.

**Comment by whit537** [comment]
We should have a history part of the video, for which I think it makes sense to use the [chart](https://gratipay.com/about/stats).

![screen shot 2016-10-31 at 11 54 20 am](https://cloud.githubusercontent.com/assets/134455/19860856/c74dd9b0-9f60-11e6-8651-4187db3d6890.png)

**Comment by whit537** [comment]
[Pronounciation](https://www.youtube.com/watch?v=mZvZnx903lM) of [Karien Bezeidenhout](https://www.shuttleworthfoundation.org/team/karien-bezuidenhout/) (she and I [spoke](https://github.com/gratipay/gratipay.com/issues/704#issuecomment-17288794) three years ago; I recall that I was sitting on a park bench near the Brooklyn Bridge—a stunning view but a terrible connection!).

**Comment by whit537** [comment]
[video script](https://docs.google.com/document/d/1mDqwEKWcPNIg7NkjEG23OCXNy38iWFn18q7M-phI63Y/edit?usp=sharing)

**Comment by whit537** [comment]
My plan is to write and record a video in the next two hours, and then use [impress.js](https://github.com/bartaz/impress.js/) to add some movement to the video—as much as I'm able to get done before the deadline.

**Comment by whit537** [comment]
> YouTube uses 16:9 aspect ratio players. The YouTube player automatically adds black bars to videos in the player so that videos are displayed correctly without cropping or stretching, no matter the size of the video or the player.

https://support.google.com/youtube/answer/6375112

**Comment by whit537** [comment]
Same page ^^^

> If you upload a 16:9 video at its original aspect ratio (1280x720 recommended) ... 	The video will fill the YouTube widescreen 16x9 player.

**Comment by whit537** [comment]
GIF doesn't quite do it justice.

![njpxv6dnbm](https://cloud.githubusercontent.com/assets/134455/19878740/c70f9ea4-9fc2-11e6-88c6-1bc7821d3ec5.gif)

**Comment by whit537** [comment]
https://www.youtube.com/watch?v=tGhLmWn3G60

**Comment by whit537** [comment]
https://soundcloud.com/ck_quasar etc.

**Comment by whit537** [comment]
https://soundcloud.com/ck_quasar/rain

**Comment by whit537** [comment]
I queried people we charged on June 19, 2014 (just before #319 came to a head), and came up with this list of 20 companies (sorted by amount charged, descending):

1. andyet
1. stripe
1. balanced
1. MaxCDN
1. digitalocean
1. engineyard
1. Bountysource
1. cos.io
1. khanacademy
1. Lincoln Loop
1. breezeweb_ca
1. [anonymous_giving]
1. Team Rubber
1. getsentry
1. openconcept_ca
1. Runscope
1. hypatiadotca
1. CodioHQ
1. Kitely
1. card.com

Off the top of my head, I know that list is missing at least two:

1. Klarna
1. TeeSpring

**Comment by whit537** [comment]
> Dozens? Really?

So not dozens, no. 20+.

**Comment by whit537** [comment]
Maybe "a couple dozen," if we want to assume there are at least two _more_.

**Comment by whit537** [comment]
[One](https://gratipay.com/~Team%20Rubber/) is still giving.

**Comment by whit537** [comment]
Okay, I just did a first cut filming myself talking. I bet I went 10 minutes, the camera ran out of room after two.

**Comment by whit537** [comment]
Just finished a second take. I bought a [program](https://imazing.com/) to unload files from an iPhone (iTunes is a mess for that 👿 ), leaving enough room for about 10:30. I was almost done! :)

Okay! Let's trim this in half ...

https://www.youtube.com/watch?v=yG0x_Xc_c98

Feelin' good ...

**Comment by whit537** [comment]
Got it down to about nine minutes. I'm recording audio on my laptop for better quality.

| n | starting<br>timestamp | duration | segment |
|:---|:-----------|:----------|:-----------|
| 1 | 0:07 | 0:41 | intro & thanks |
| 2 | 0:48 | 0:28 | overview |
| 3 | 1:16 | 0:42 | what is gratipay? |
| 4 | 1:58 | 2:09 | why is it interesting? open source funding crisis |
| 5 | 4:07 | 1:34 | now distribution - take-what-you-want |
| 6 | 5:43 | 2:43 | the really exciting thing - open organizations! |
| 7 | 8:26 | 0:29 | outro |
|  | 8:55 | | |

**Comment by whit537** [comment]
Started a [scratchpad](https://docs.google.com/spreadsheets/d/10fxb4WnfvkwxiDvrBRUS1i6orPMCGp7Yny53MH93iSk/edit?usp=sharing) so I don't have to manually do timestamp math.

I've got (1) (2) (3) and (7) preeeeetty tight. The main content sections need work.

I'd really like to sync this up to a song if I can. [Current pick](https://www.youtube.com/watch?v=yG0x_Xc_c98). Added to scratchpad ... hmmm ...

**Comment by whit537** [comment]
Alright, so I have five sections to nail:

1. intro, thanks, & overview—0:54
2. what is gratipay and why does funding open source matter?—1:30
3. take-what-you-want—1:30
4. open organizations!—1:29
5. outro—0:37

**Comment by whit537** [comment]
I'd better do each one individually and then edit them together. It'll be way too hard to sync up every single one with the music in one tae.

**Comment by whit537** [comment]
[First rough cut](https://www.youtube.com/watch?v=SSCD-h0fbVs). I wanted to make sure I could get the audio and video knit together before recording the rest of the audio. Okay! Here we go ...

**Comment by whit537** [comment]
Got a usable take for (2)!

**Comment by whit537** [comment]
(3)!

**Comment by whit537** [comment]
H*ckin NAILED it! OMG WOW. So the drama over here is that I set up to record on our third floor ... but we have somebody staying with us during the week right now (off of Airbnb). He usually gets home between 6 and 8. I was REALLY stressed out trying to finish recording before he got home—I had a whole setup in place and I have a ton of editing still to do, no time to rerecord or even really setup somewhere else. I heard the door crack the very second I finished what I knew was gonna be the final take. H*CK. YEAH. 💃 🌻 👍 💸 

At least I hope it was the final take. Now I have to edit it all together. Hopefully everything fits. :-) 🐭

Okay! Supper and then editing! 💃

**Comment by dmk246** [comment]
@whit537 WOOHOO!! Exciting!

**Comment by whit537** [comment]
Alright, so my next task is to figure out how I'm going to line up video and audio in iMovie. I think it might be better to line them up using ffmpeg before importing them, because iMovie is a bit of a pita.

**Comment by whit537** [comment]
Yeah, ffmpeg is waaaaaay easier. 👍

**Comment by whit537** [comment]
http://stackoverflow.com/questions/11779490/how-to-add-a-new-audio-not-mixing-into-a-video-using-ffmpeg
http://superuser.com/questions/982342/in-ffmpeg-how-to-delay-only-the-audio-of-a-mp4-video-without-converting-the-au

```
ffmpeg -itsoffset 2 -i 0-intro-thanks-overview.mov -i 0-intro-thanks-overview.m4a -map 0:v -map 1:a -c copy -shortest 0.mov
```

**Comment by whit537** [comment]
Golly. Now I can't get this `0.mov` file to show up in iMovie as a clip—even a rejected one. :-/

**Comment by whit537** [comment]
Yeah, I can import the raw `*.mov` but not the one ffmpeg produces. 😞

**Comment by whit537** [comment]
I considered upgrading iMovie to 10.1.3 for $15 (I'm on 8.0.6), but the reviews scared me off. I kind of even considered Final Cut Pro for $300, but it says it's compatible with macOS 10.11.4 and higher, and I'm on 10.10.5.

**Comment by whit537** [comment]
I am rerunning the file through ffmpeg (`ffmpeg -i 0.mov 00.mov`). I'm seeing some error messages—maybe it is cleaning up the file?

![screen shot 2016-11-01 at 11 07 32 pm](https://cloud.githubusercontent.com/assets/134455/19915355/0c12efea-a088-11e6-99db-298117ca1c54.png)

**Comment by whit537** [comment]
Okay! Done. Doesn't load with an initial black screen in QuickTime Player ... good sign? How about iMovie? 🙈

**Comment by whit537** [comment]
Generating thumbnails is taking longer ... 👍

**Comment by whit537** [comment]
BLAM!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by whit537** [comment]
The file size is a lot smaller. Probably recompressing? ¯\\\_(ツ)\_/¯

**Comment by whit537** [comment]
```
ffmpeg -itsoffset 2.85 -i 1-what-is-gratipay.mov -i 1-what-is-gratipay.m4a -map 0:v -map 1:a -c copy -shortest 1.mov
```

**Comment by whit537** [comment]
Looks like it's the `-c copy` option that screws up iMovie. I did `ffmpeg -i 1.mov -c copy 11.mov` and iMovie can't handle it.

**Comment by kaguillera** [comment]
deadline? You are getting me scared 🙈

**Comment by whit537** [comment]
Though `-c copy` is waaaaaay faster, so it's good for finding the right time offset (since QuickTime Player _does_ play the resulting video, albeit with a blank first frame or so; it just stymies iMovie).

**Comment by whit537** [comment]
> deadline? You are getting me scared 🙈

Pfffffft. We've got almost 3.5 hours left! :-)

**Comment by kaguillera** [comment]
oh ok I thought that it was 12:00 pm our time

**Comment by whit537** [comment]
This should go pretty quick once I've got the audio and video tracks knit together. Of course I still need to dust off my resume as well as the text answers ... wanna [review those](https://docs.google.com/document/d/1oHPUEdyu4c5bZmGwwt-G4bOApVFlpRJ0La7R-BJwuno/edit?usp=sharing)? :-)

**Comment by kaguillera** [comment]
Thing is I have done plenty video editing in iMove so if I was there I could have helped

**Comment by whit537** [comment]
Nah, midnight Pacific.

**Comment by kaguillera** [comment]
Looking at it now at [text answer](https://docs.google.com/document/d/1oHPUEdyu4c5bZmGwwt-G4bOApVFlpRJ0La7R-BJwuno/edit?usp=sharing)

**Comment by whit537** [comment]
```
ffmpeg -itsoffset 2.5 -i 2-take-what-you-want.mov -i 2-take-what-you-want.m4a -map 0:v -map 1:a -shortest 2.mov
```

**Comment by whit537** [comment]
```
ffmpeg -itsoffset 2.55 -i 3-open-organizations.mov -i 3-open-organizations.m4a -map 0:v -map 1:a -shortest 3.mov
```

**Comment by kaguillera** [comment]
I like it. No complaints (which actually scares me. 🙈 ). You answered all the questions as I think that should be answered given Gratipay's vision and mission (and yours).

**Comment by whit537** [comment]
Okay! `3.mov` encoded. Now to stitch them together in iMovie! Then I'll add in the mp3, and export it, and then I figured on doing a screen capture of the [impress js](https://github.com/gratipay/inside.gratipay.com/issues/388#issuecomment-257481333) with the video embedded. Then we upload that to YouTube—and I think that's it! Hopefully the screencap doesn't kill the quality _too_ badly. 😁

**Comment by whit537** [comment]
I removed the old iMovie project and event, made a new project, and am importing the four videos into a new event.

**Comment by whit537** [comment]
I wonder if it'll make sense to drive the impress programmatically during the screencast. How many takes will it take me to get it close enough, driving it manually?

**Comment by kaguillera** [comment]
I was thinking the same thing...but do you have the time.

**Comment by whit537** [comment]
> I was looking at the wrong number on the character count and went over the 1500-character limit on some of the answers, so I'll have to revise those down.

Actually, only one answer is long ("What are you going to do to get there?").

**Comment by whit537** [comment]
Fixed.

**Comment by whit537** [comment]
Exporting from iMovie! The whole program is painfully slow! I rebooted and everything! 😩

> I was thinking the same thing...but do you have the time.

Once this is exported it'll be time to find out! :D

**Comment by whit537** [comment]
Oh no.

It's now saying two hours to export, and the deadline is in 1:20. 👖

![screen shot 2016-11-02 at 1 38 55 am](https://cloud.githubusercontent.com/assets/134455/19917850/2e875844-a09d-11e6-8246-6d3961d50a36.png)

**Comment by whit537** [comment]
Alternative is to hack it with ffmpeg?

**Comment by whit537** [comment]
I also have a Windows desktop here. Can I make it happen with Movie Maker more quickly?

**Comment by whit537** [comment]
Now it's threatening 3 hours at times.

Movie Maker is installing on the PC.

I just plugged in a hard drive to get the raw files off.

This is ridiculous.

**Comment by whit537** [comment]
Okay, files are on the drive.

I don't know if Movie Maker will take mov files. If not I guess I'll have to use ffmpeg on this machine to convert them to something Windows can work with.

**Comment by whit537** [comment]
Frighteningly simple and fast ... if it works!

```
ffmpeg -i 0.mov -c copy 0.avi
ffmpeg -i 1.mov -c copy 1.avi
ffmpeg -i 2.mov -c copy 2.avi
ffmpeg -i 3.mov -c copy 3.avi
```

**Comment by whit537** [comment]
Eff. I think this drive is Mac only.

**Comment by whit537** [comment]
Could also maybe re-encode at a smaller size.

**Comment by whit537** [comment]
Alright, the AVI files are not coming through.

I've tried different export options from iMovie and they all are taking forever.

**Comment by whit537** [comment]
Holy heck. Okay!

**Comment by whit537** [comment]
I catted the four clips together with no music or other fanciness. Came out to 5:02. Uploading to YouTube now!

**Comment by whit537** [comment]
https://www.youtube.com/watch?v=aYeCbK7kFdE

**Comment by whit537** [comment]
Couldn't have been closer!

![screen shot 2016-11-02 at 2 59 33 am](https://cloud.githubusercontent.com/assets/134455/19919335/6c69729a-a0a8-11e6-84f6-9dad01e3d19f.png)

**Comment by whit537** [comment]
Alright, just watched the video. I guessssssssss ............. that's my Shuttleworth video! O.o

..........................................................

🐝

**Comment by whit537** [comment]
That was ridiculous. Can't make this stuff up.

**Comment by whit537** [comment]
I didn't even look at my resume. I just pulled it out of git history on whit537.org. I have very little idea what it says.

**Comment by whit537** [comment]
That timestamp tho ... O.o

![screen shot 2016-11-02 at 3 13 06 am](https://cloud.githubusercontent.com/assets/134455/19919617/5a986e5c-a0aa-11e6-8466-45015646cf9f.png)

**Comment by whit537** [comment]
Write "Okay!" on my tombstone.

**Comment by whit537** [comment]
Okay! I'm going to spend a little more time trying to get the edited version together. I can add one of those annoying full-screen click targets overtop of the old video, pointing to the new one.

**Comment by whit537** [comment]
iMovie is painfully slow. I think it's because I'm working with the full HD videos (1920 x 1080). I'm going to try:

1. Using ffmpeg to knit the raw videos together, properly spaced out.
1. Doing the screencast.
1. Using ffmpeg to knit together the video from the screencast with the audio from (1).

**Comment by whit537** [comment]
I've extracted the first and last frames from each of the four clips. Some of them are a little scary but I guess that's okay. The idea is to switch away quickly in each case to other slides.

`count-frames.sh`:

```sh
#!/bin/sh

# http://stackoverflow.com/questions/2017843/
# ffprobe |grep nb_frames is bad because of duplicate frames

ffprobe -v error -count_frames -select_streams v:0 \
    -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 01.mov
ffprobe -v error -count_frames -select_streams v:0 \
    -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 04.mov
ffprobe -v error -count_frames -select_streams v:0 \
    -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 07.mov
ffprobe -v error -count_frames -select_streams v:0 \
    -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 10.mov
```

`extract-frames.sh`:

```sh
#!/bin/sh

# extract first and last frame of each movie
# http://stackoverflow.com/questions/5248283/

ffmpeg -y -i 01.mov -vf "select='eq(n,0)'" -vframes 1 00.png 
ffmpeg -y -i 04.mov -vf "select='eq(n,0)'" -vframes 1 03.png 
ffmpeg -y -i 07.mov -vf "select='eq(n,0)'" -vframes 1 06.png 
ffmpeg -y -i 10.mov -vf "select='eq(n,0)'" -vframes 1 09.png 

ffmpeg -y -i 01.mov -vf "select='eq(n,1201)'" -vframes 1 02.png 
ffmpeg -y -i 04.mov -vf "select='eq(n,1788)'" -vframes 1 05.png 
ffmpeg -y -i 07.mov -vf "select='eq(n,1920)'" -vframes 1 08.png 
ffmpeg -y -i 10.mov -vf "select='eq(n,3013)'" -vframes 1 11.png 
```

**Comment by whit537** [comment]
Now to knit together a loop of a single frame and a movie. Let's try with just 00.png and 01.mov to begin with. I was having trouble with this last night.

**Comment by whit537** [comment]
Alright, this is way squidgy. 😞

I'm gonna go back to iMovie and slog it out ...

**Comment by whit537** [comment]
Alright! I guess I'll check in on that later today.

**Comment by whit537** [comment]
I do think the version with music is better.

**Comment by whit537** [comment]
That is, I think this is worth finishing, rather than leaving the raw version as the only version out there.

**Comment by whit537** [comment]
Video is exported. Just gave @kaguillera a live performance of the video (me talking + soundtrack) together with the impress presentation. Currently looking at implementing the transitions in javascript for predictability. There are some tight transitions that will be hard to hit manually.

**Comment by whit537** [comment]
Found a good technique to drive transitions programmatically. Now just need the timestamps ...

**Comment by whit537** [comment]
It's actually really difficult to see where I am in this video with subsecond resolution. iMovie shows me tenths of a second ... but only below 10 seconds(?).

**Comment by whit537** [comment]
[Got it](https://addons.videolan.org/p/1154032/)!

![screen shot 2016-11-02 at 3 19 08 pm](https://cloud.githubusercontent.com/assets/134455/19943902/cf966ba4-a10f-11e6-8ec0-5fefb5b3ec8a.png)

**Comment by whit537** [comment]
Okay! I've got the timings done. Now to screencap this and merge the audio with the new video. Then it's up to YouTube! I have 1.5 hrs.

**Comment by whit537** [comment]
Just showed it to @dmk246 and @trishinPA. A couple of the transitions drag out a bit too long. Not much to be done about that now. :-/

**Comment by whit537** [comment]
I'm trying to figure out why the video isn't covering the canvas area properly.

![screen shot 2016-11-02 at 4 36 11 pm](https://cloud.githubusercontent.com/assets/134455/19946432/8471106a-a11a-11e6-958c-b6725e75094c.png)

**Comment by whit537** [comment]
Got it!

**Comment by whit537** [comment]
Screencap time!

**Comment by whit537** [comment]
The frame-rate is pretty bad. Maybe if I scale back to 960 x 480?

**Comment by whit537** [comment]
Harumph. I've got one that's of acceptable quality, but I had to go down to 640 x 360. :-/

**Comment by whit537** [comment]
I'd better move on to remerging with the audio.

**Comment by whit537** [comment]
(I just did cmd-- in the browser to scale it down.)

**Comment by whit537** [comment]
Alright, it's a bit rough but it's up: https://www.youtube.com/watch?v=QDQSk1WSqNs.

I've added an annotation to the [raw version](https://www.youtube.com/watch?v=aYeCbK7kFdE), though annotations apparently don't show up on mobile.

**Comment by whit537** [comment]
Pretty sick of hearing myself say "I envision a society" at this point. :-)

**Comment by whit537** [comment]
:sleeping_bed:

**Comment by dmk246** [comment]
@whit537 I can't access the first (new) link....the raw version link works .... but it could be just me too! However ...wanted to check so if it's not loading ..you'll know!

**Comment by whit537** [comment]
I found a Microsoft [utility](https://www.microsoft.com/en-us/download/details.aspx?id=10732) that provides up to 60 fps. I copied the impress over to the desktop here at the house and am recording it right now at full res and 30 fps. Eeeeeee!!!!!

**Comment by whit537** [comment]
@dmk246 I yanked the new link because the quality was so bad. 😞  Working on another edit ...

**Comment by dmk246** [comment]
@whit537 oh good! Glad that you knew! Good luck!!

**Comment by whit537** [comment]
I am encoding from the xesc file that Expression Encoder produced, to mp4. I added a red background that goes away when the video starts (a clapper of sorts) and also Expression Encoder provides millisecond precision on the play head, as well as frame-by-frame seek. That means we should be able to sync up the audio to the video much more precisely.

**Comment by whit537** [comment]
I'm nervous about drift between the audio and video. Like, even if they're synced up at the beginning, they may get out of sync as the video goes on.

**Comment by whit537** [comment]
I don't know how big the mp4 file is going to be, but right now it's about 1% of the input file size after about 15 minutes.

**Comment by whit537** [comment]
It could be [bigger](https://social.msdn.microsoft.com/Forums/expression/en-US/b6e70b08-8182-44ba-8923-30ca54973740/why-are-encoded-wmv-or-mp4-files-bigger-than-the-original-xesc-file?forum=encoder). 😳

**Comment by whit537** [comment]
Alright, I killed it. I'm not going to run my computer for 24+ hours to encode this.

**Comment by whit537** [comment]
I'm [letting go](https://twitter.com/whit537/status/794170822114078720) of the edit. Shuttleworth is getting raw footage—straight from the ❤️.

**Comment by whit537** [comment]
From: Shuttleworth
Subject: We are reviewing your Shuttleworth Application

> Dear Chad
>
Thank you for applying to be a March 2017 Shuttleworth Foundation Fellow.  It is humbling to us that you have spent your time and energy on the change you wish to make, and explaining it to us by way of a Fellowship application.
>
We are now in the process of reviewing all of the applications. We expect to select no more than 4 new Fellows, which means the competition is tough. We want you to know that you, who are brave enough to re-imagine the world in which we live, are doing a great job, and we thank you for that. Even if you do not make it through to the next round, don't be discouraged or disheartened. Continue making the change you want to see in the world. 
>
We will be in touch over the next few weeks to let you know where you are in the process.
>
Kind regards,
Shuttleworth Foundation Team

**Comment by whit537** [comment]
Re: Fellowship Application

>Dear Chad,
>
>Thank you for submitting an application for the Shuttleworth Foundation Fellowship Programme. We have received many excellent applications, so making a decision has been a difficult task.
>
>We appreciate the passion and commitment to social change that went into your submission. However, in relation to other applications received, it was not the best fit for this particular Fellowship. With a limited number of spots available, unfortunately we will not be offering you a Fellowship this year.
>
>Thanks again for the time and effort invested in the application and review process. We wish you all the best in finding the right support for your endeavour.
>
>Kind regards,
>Shuttleworth Foundation Team
