### ISSUE TITLE
make business cards

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#391]
I don't want to take the puncher to #384. People ask for business cards.

**Comment by kzisme** [comment]
What sort of items/information would you want on the card?  

(aside from the normal first + last, address, email, phone)

**Comment by whit537** [comment]
Nada mucho. Really plain.

**Comment by kzisme** [comment]
I have an idea :smile_cat: 

Give me a few minutes and I'll let you know what I have going on.

**Comment by whit537** [comment]
:exclamation:

**Comment by kzisme** [comment]
![chadcarddraft](https://github-cloud.s3.amazonaws.com/assets%2F3493562%2F10958691%2Fd60f92de-833e-11e5-88c5-6ff4d53a3856.jpg)

![chadcarddraftbg](https://github-cloud.s3.amazonaws.com/assets%2F3493562%2F10958692%2Fda0b6bf6-833e-11e5-8d58-d09eb3c640b1.jpg)

**Comment by kzisme** [comment]
Obviously it looks strange on a white background - it's the standard size 2 x 3.5in

That's about as simple as I could come up with (the brown heard could be changed to black or the back (bottom image could be changed as well)

I'm not super happy with the font, but that's easily fixed as well.  I figured this is a decent enough draft - as I haven't done much image stuff lately.

**Comment by kzisme** [comment]
Oh, the Gratipay heart could also be removed and we could use other images to separate the two text areas.  Really depends what you want with you :smiley_cat:

**Comment by whit537** [comment]
Thanks for working on this! Can we go even plainer?

```
+---------------------------------------------------------------------------+
|                                                                           |
|                                                                           |
|       __    ______   __     _____           _   _                   
|      / /   / /___ \  \ \   / ____|         | | (_)                  
|     | |   / /  __) |  | | | |  __ _ __ __ _| |_ _ _ __   __ _ _   _ 
|     | |  < <  |__ <   | | | | |_ | '__/ _` | __| | '_ \ / _` | | | |
|     | |   \ \ ___) |  | | | |__| | | | (_| | |_| | |_) | (_| | |_| |
|     | |    \_\____/   | |  \_____|_|  \__,_|\__|_| .__/ \__,_|\__, |
|      \_\             /_/                         | |           __/ |
|                                                  |_|          |___/ 
|                                                                                                               
|
|    Chad Whitacre, Founder
|    chad@zetaweb.com
|                                                                           |
|                                                                           |
+---------------------------------------------------------------------------+
```

Let's also be careful to preserve the aspect ratio of the [wordmark](http://inside.gratipay.com/assets/gratipay.svg).

**Comment by whit537** [comment]
Also: Probably simpler/cheaper to leave the reverse blank, no?

**Comment by kzisme** [comment]
Most likely would be cheaper i included it for the sake of having a back if
necessary.

I'll re-work something tonight or tomorrow :) didn't know how plain you
wanted!

**Comment by whit537** [comment]
Lost momentum on this.
