### ISSUE TITLE
introduce Gratipay to Nathan Schneider

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#399]
http://www.therowboat.com/

Co-convener of http://platformcoop.net/.

Reticketed from #384.

**Comment by whit537** [comment]
To: Nathan
Subject: open call re: Gratipay?

>I trust you've made it safely home and have caught your breath a bit after Platform Cooperativism. A stimulating event! Good work. :-)
>
I'm writing to follow up on our brief exchange at the conference about doing a call together between Thanksgiving and mid-December, to introduce you more fully to what we're doing over in Gratipay-land, and consider how it relates to platform cooperativism. Still up for it? Do any of these times work for you?
>
December 3 at 11am (MST—yes?) 
December 9 at 11am
December 10 at 11am
>
Let me know! :-)
>
P.S. Here's our write-up about the event, if you're interested:
>
https://medium.com/gratipay-blog/a-platform-cooperative-almost-94cd5900840f

**Comment by whit537** [comment]
> Good to hear from you, Chad. Let's do December 10. And I love the Github issue thread—great discussion, in a great medium. I like how it demonstrates a bit about how your community works.

----------

> December 10 it is! We're still good for Google Hangouts on Air, yes? I'll plan to email you to reconfirm the day before, and I'll email you the link to join the Hangout when the time comes.
>
Speaking of GitHub issues, here's the one where we're tracking our conversation:
>
https://github.com/gratipay/inside.gratipay.com/issues/399
>
And I believe I've just found your GitHub account ... :-)

cc: @nathanairplane :rowboat: :airplane: :question:

**Comment by whit537** [comment]
@nathanairplane Reading http://www.therowboat.com/open-journalism/, you may be interested in https://github.com/gratipay/team-review/issues/108. ;-)

**Comment by whit537** [comment]
I was reminded over on #412 about a piece from a couple years ago, "[Open Products](https://changelog.com/open-products/)," where I talked about open-sourcing consumer products, which is related to the idea of platform cooperatives. I didn't address ownership *de jure*, though I would say that open-source does involve a *de facto* sharing of ownership and control. I've suggested [elsewhere](https://github.com/opencompany/www.opencompany.org/issues/21#issuecomment-31260256) that "transparency is about sharing *information*, and openness is about sharing *control*." Platform Cooperatives offers the helpful corrective that, actually, *cooperatives* are about sharing control. :-)

**Comment by whit537** [comment]
https://www.youtube.com/watch?v=YgxkGELtKME

**Comment by whit537** [comment]
Okay! Thank you for the stimulating conversation, @nathanairplane. I look forward to continuing to explore these themes together with you in the future. :-)

**Comment by nathanairplane** [comment]
Thank you, Chad. What a pleasure. I look forward to more.
