### ISSUE TITLE
Where does documentation such as this belong?

### ISSUE THREAD

**Issue by zwn** [gratipay/inside.gratipay.com#4]
I am trying to put on the user's hat and trying to find out what I would expect not knowing the insides of gittip. I'd like to talk about user identification which does somewhat fall into IA but some might argue it is SA. It partially documents the current behavior and partially suggests some changes (maybe it is the equivalent of a PEP?) I have in mind a text such as this:

Gittip user is identified by an immutable numerical id that is currently unaccessible from the UI. The user can change its username which changes the url to get to the profile. Changing the username does not change the users identity.

Similar behavior can be seen on other sites, most notably Github, Twitter or Google (principle of least surprise). In addition Google provides immutable url exposing the internal id as well as the url based on the username.

When a gittip user (with immutable numerical id) tips someone using the /on/* pages, the intention is to give money to the person represented by that account. The user expects to see such an action represented in its history overview (events, audits..?). The platform and username of the receiver at the time the tip was initiated should be noted. If the receiver changes its name over time or its elsewhere account is attached to a gittip user id, the current info should be shown with a link to the current destination.

When elsewhere account is attached to a gittip user id, all tips associated with the elsewhere account should go to the governing gittip user id. However when the elsewhere account is detached again, all tips to this account should become *hanging* again (not claimed).

There is no principal reason why only one account from each platform should be allowed to be connected to a gittip user id.

The common property of an elsewhere account is the ability of its owner to prove the ownership. Therefore email, persona and similar fail under this category. However bitcoin address does not (unless there exist a way to prove ownership which I doubt).

**Comment by whit537** [comment]
Closing old tickets. We've changed a lot since this ticket was written.
