### ISSUE TITLE
introduce Gratipay to Neal Gorenflo

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#403]
http://www.shareable.net/users/neal-gorenflo

Reticketed from https://github.com/gratipay/inside.gratipay.com/issues/395#issuecomment-155976513.

**Comment by whit537** [comment]
> the 25th works at 11am PST

----------

> Awesome! I'll confirm next week and email you the link to the Hangout when the time comes.

**Comment by whit537** [comment]
I sent Neal a confirmation email about tomorrow's call.

@kzisme This could be something for Twitter. I'm scheduled to do a Google Hangout on Air with the co-founder of Shareable tomorrow at 2pm EST (11am PST).

**Comment by whit537** [comment]
Heard back from Neal, sounds like we're on in an hour! :-)

**Comment by whit537** [comment]
https://www.youtube.com/watch?v=ICUIDhR6MW0

**Comment by whit537** [comment]
/me sends join link to Neal ...

**Comment by whit537** [comment]
:dancer:

**Comment by kzisme** [comment]
Shared link on Twitter :) most likely will share again this week at some point.

**Comment by whit537** [comment]
Nice, thanks @kzisme! :-)
