### ISSUE TITLE
capitalize

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#405]
Businesses cost money to build. How are we going to capitalize Gratipay? Options:

- cashflow
- debt (#78, #406, #864)
- VC (#68)
- grants (#388, #637, #836)
- crowdfunding (#870)

**Comment by whit537** [comment]
http://www.coopcapital.coop/coopcapital
http://www.fao.org/docrep/003/w5069e/w5069e06.htm
http://www.co-oplaw.org/topics-2/financing/
http://cultivate.coop/wiki/Obtaining_Start_Up_Capital_for_Cooperatives
http://cultivate.coop/wiki/Cooperative_capital
http://www.geo.coop/node/60

**Comment by techtonik** [comment]
I don't mind as long as it is open. =)

**Comment by techtonik** [comment]
But of course it is a pity that we are not able to pull it off with crowdfunding. So, we need those to normalize our income, not to make it a primary source. Because otherwise we are trading our hope for a better economy. By normalizing I mean that:

1. People pay what they want (in $$$)
2. But after they receive ($$$) and pay their living cost (minimal wage), there not much left to share
3. From the sum that is left (the reminder) you need something to enjoy your life (movies, medicine, cars, travel etc.)
4. Everything that is left is the sum that you can share (the budget)
5. For many people this budget is ... ? (how much, BTW is a average budget - do we have some https://gratipay.com/stats/ page)
6. So let's assume that for some people 100% of the budget is about $10
7. And in our current economy this budget is "washed away" from our economy with (minimal wage) that Gratipay members needs to receive in order to cover their own expenses

I think budget for giving on Gratipay 1.0 was about 50% of what I received and FinCEN basically took away that from me. I don't earn anything at all right now to cover my living expenses which are about $200 / month. So now I don't have any budget.

So, "normalizing" is needed to make sure we have an equal budget to spend. For some people even $1 is more than they can spend. For some $50 is the absolute top. I'd say that for most people in current economy are comfortable to spend 1% of their salary, so if you're earning $500, it is just $5 a month. The alternative economy will be self-sufficient only if people will be able to spent 100% of their salary on Gratipay. Until then we can crowdsource (people will be paying us for transparency and for helping open teams stay open and transparent) or use the tools like capital (shares and assets) available from the current system to *match* the donations that we receive.

**Comment by whit537** [comment]
> Outside equity is more complicated for a cooperative business than a traditional for-profit business. First, in California, cooperatives are not permitted to have “outside” or non-member investors. Thus these investors need to become members of the cooperative most likely as a separate class of “investor” members. Second, cooperative businesses follow the principle that voting rights are based on one’s membership in the cooperative, not on one’s investment of capital. This is different from a traditional capitalist enterprise in which ownership and voting are based on the number of shares an individual owns. In a cooperative, ownership and voting are based on your membership. Thus, no one member should have more votes than another.
>
This is a problem when a cooperative tries to attract capital investors, because such investors typically would like to have increased ownership and voting rights based on their capital investment. They may not be familiar with the concept of cooperative ownership and may not be interested in giving up the rights they would otherwise have in a conventional corporation.

http://www.co-oplaw.org/topics-2/financing/

**Comment by whit537** [comment]
Contra:

> I've been working on a [platform](http://communityforge.net/) for 7 years, but the idea that it had to take over the world never occurred to me.
>
[...]
>
My organisation, [Community Forge](http://communityforge.net/) offers free hosting & support for 140 active communities, some of which donate back to pay expenses. That project became what it is without writing any invoices, incurring any risk or any debt.

http://www.geo.coop/story/death-star-platforms

**Comment by whit537** [comment]
http://www.cuttingedgecapital.com/financing-strategies/

h/t Jim Johnson (https://github.com/gratipay/inside.gratipay.com/issues/72#issuecomment-166668883)

**Comment by mattbk** [comment]
I don't have a handle on the financials, but is there an estimate of how many teams/how much money would be needed to sustain Gratipay at a given percentage of donations?

**Comment by whit537** [comment]
@mattbk A fair question. It depends on what we mean by "sustain." In one sense, Gratipay is sustainable now: we are able to cover our hosting costs out of our income, and we have enough volunteer labor to perform basic maintenance and do a little product and business development.

I've been thinking that if we *were* to take capital, we should use it intelligently to grow at a sustainable rate. I would hate to see us "fly and die" by burning through a million dollars in a year and then having to give up. Much better to use capital slowly to grow one notch at a time rather than 10 notches all at once.

**Comment by mattbk** [comment]
> In one sense, Gratipay is sustainable now: we are able to cover our hosting costs out of our income, and we have enough volunteer labor to perform basic maintenance and do a little product and business development.

The "volunteer labor" is the gap that needs to be filled, then. Agree with your other points.

**Comment by whit537** [comment]
I learned about "social impact loans" at https://www.youtube.com/watch?v=MmksnIsEJPk#t=39m37s (https://github.com/gratipay/inside.gratipay.com/issues/421#issuecomment-167798171).

**Comment by whit537** [comment]
"[How I Stumbled Upon The Internet’s Biggest Blind Spot](https://medium.com/@nayafia/how-i-stumbled-upon-the-internet-s-biggest-blind-spot-b9aa23618c58)"

I'm embarrassed to say that I had forgotten that Nadia had been at Collaborative Fund. She and I [spoke](https://www.youtube.com/watch?v=tNhncmK5r2U) a year before I met Jessica (#334) or Kanyi (#397). Maybe time to reach out again? :)

**Comment by whit537** [comment]
> Under the radar, slowly and steadily, and without ever taking a dime in outside funding or spending more than it earned, MailChimp has been building a behemoth. According to Ben Chestnut, MailChimp’s co-founder and chief executive, the company recorded $280 million in revenue in 2015 and is on track to top $400 million in 2016. MailChimp has always been profitable, Mr. Chestnut said, though he declined to divulge exact margins. The company — which has repeatedly turned down overtures from venture capitalists and is wholly owned by Mr. Chestnut and his co-founder, Dan Kurzius — now employs about 550 people, and by next year it will be close to 700.
>
As a private company, MailChimp has long kept its business metrics secret, but Mr. Chestnut wants to publicize its numbers now to show the road less traveled: If you want to run a successful tech company, you don’t have to follow the path of “Silicon Valley.” You can simply start a business, run it to serve your customers, and forget about outside investors and growth at any cost.

http://nytimes.com/2016/10/06/technology/mailchimp-and-the-un-silicon-valley-way-to-make-it-as-a-start-up.html

**Comment by mattbk** [comment]
> If you want to run a successful tech company, you don’t have to follow the path of “Silicon Valley.” You can simply start a business, run it to serve your customers, and forget about outside investors and growth at any cost.

Yes. This is what we focus on for [ENDracing](http://endracing.com).

**Comment by whit537** [comment]
Picking up from https://github.com/gratipay/inside.gratipay.com/issues/868#issuecomment-257191759 ... and reviewing the options in the ticket description here ...

**Cashflow** is what we've been doing. It's painfully slow.

**Debt** isn't really available to us, because to get a loan we need assets or income, and we don't have enough of either.

**VC** has been a problem for us because an exclusive ownership structure doesn't fit our mission or ethos.

**Grants** might be a good option, though we'll almost certainly need to convert to an actual non-profit to make this work.

**Crowdfunding** will only work if we have a hook, something to offer in return and build some buzz around.

**Comment by whit537** [comment]
This ties directly into the question of our ownership structure (#72). I don't think remaining a for-profit is the right way for us, but I'm still very much on the fence between cooperative and non-profit.

**Comment by whit537** [comment]
Well, one way or another Shuttleworth (#388) is due today, so I'm going to focus on that for now.

**Comment by whit537** [comment]
Here's a 65-page report on [financing cooperatives](https://ica.coop/sites/default/files/352_ICA_Coop_Capital.pdf).

**Comment by whit537** [comment]
TechShop's DIY investment crowdfunding page: http://www.techshop.ws/invest.html.

**Comment by whit537** [comment]
> Loans of $5,000 to $500,000 are available for one to ten years. For projects of up to $1 million or more, we can partner with other lenders.

http://sharedcapital.coop/borrow/

**Comment by kaguillera** [comment]
Do we generate enough funds to pay a monthly loan installment?

**Comment by mattbk** [comment]
[No?](https://docs.google.com/spreadsheets/d/1p3DpF9ZLEsViBx0685FwJaYN1vVScKVUgXHb2zyqXZg/edit?ts=581fd232#gid=1)

**Comment by whit537** [comment]
I had a brainstorm this morning. Perhaps we could use a two-tier legal structure in order to access capital while preserving cooperative ownership. Gratipay, LLC, our current entity, would be the cooperative (#72, etc.), and we would form a new entity, Gratipay, Inc., that is majority owned by Gratipay, LLC. That way the cooperative retains control, while letting us deal in capitalists on their usual terms.

**Comment by whit537** [comment]
[fundraising.pdf](https://github.com/gratipay/inside.gratipay.com/files/961600/fundraising.pdf)

**Comment by techtonik** [comment]
https://en.wikipedia.org/wiki/Initial_Coin_Offering - we can resurrect Gratipay as a [fat protocol](http://www.usv.com/blog/fat-protocols) with automatic tax payment from recurrent weekly donations.
