### ISSUE TITLE
run an "open sales" experiment

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#412]
See https://github.com/naspeh/mailur/issues/4. Let's reach out to 127 more FLOSS projects and see what happens. :-)

Reticketed from https://github.com/gratipay/inside.gratipay.com/issues/402.

**Comment by whit537** [comment]
Let's get the ~~script~~ pattern right so we're as non-dick-ish as possible.

**Comment by whit537** [comment]
To find projects to reach out to:

https://github.com/trending
http://pycoders.com/
https://changelog.com/
https://wdrl.info/

**Comment by whit537** [comment]
#### Pattern

For each project:

 1. Research! Read and learn about the project. Download it and try it out. Look for existing discussions of money within their community, as well as current funding methods they employ.
 1. One possible outcome here is that people will freak out when they find out what we're up to, and be like "Never make a ticket in **my** repo!" Let's try really hard not to make a ticket in their repo. :-)
 1. Propose that they accept voluntary payments. Offer multiple options for this (Flattr, Bountysource, Gratipay, Patreon), and disclose that you're from Gratipay. Talk about burnout and the benefit of thinking about funding at every stage of a project to ensure the long-term success of the project.
 1. Politely engage in whatever conversation ensues. Don't try to stay where you're not wanted. Adopt a really, really light touch.

**Comment by whit537** [comment]
Consider going specifically after platform cooperatives (aka [open products](https://changelog.com/open-products/)).

**Comment by whit537** [comment]
/me pulls up from writing a script to download repo info including star count.

**Comment by whit537** [comment]
> One possible outcome here is that people will freak out when they find out what we're up to, and be like "Never make a ticket in **my** repo!" If/when that happens, let's try really hard not to make a ticket in their repo. :-)

Probably also polite to cross-check top maintainers with closed accounts on Gratipay. If someone has closed their account, we shouldn't bug them.

**Comment by whit537** [comment]
This falls under the heading of a Traction experiment.

**Comment by techtonik** [comment]
@whit537 I think we need to have something working first or at least a roadmap with problems that we haven't solved. Maybe we need a "process framework" that will guide people through the "pipeline of legal compliance", and while everybody enjoys the ride navigating and checking the stuff, people can unleash more problems and add them to the tree. In the end we will have a graph, a state machine with all actions that are required to bring anyone from one state to another.

**Comment by mattbk** [comment]
http://www.gpsbabel.org/contribute.html

Although I must echo @techtonik and say "should we be selling before there is a completed product?"

**Comment by whit537** [comment]
> I think we need to have something working first or at least a roadmap with problems that we haven't solved.

We already have both! :-) We move about $5,000 pre month for 100+ teams—that is *something* working—and here is [our roadmap](https://github.com/gratipay/inside.gratipay.com/issues/419#issuecomment-159432367).

> should we be selling before there is a completed product?

Yes! :-) This was one of the main points of *Traction*, and I think they're right. The question hinges on the scope of what we're building. Are we building a product, or a business? A business is more than a product, it is a system for bringing a product to market. *Traction* suggests that product development and marketing should each occupy 50% of a startup's attention.

Remember: [We are building viable open businesses. We are building viable open businesses. We are building viable open businesses.](https://github.com/gratipay/gratipay.com/issues/3677#issuecomment-130777007)

**Comment by mattbk** [comment]
http://www.crantastic.org/about
