### ISSUE TITLE
Apply 12factor principles

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#414]
I've just stumbled upon http://12factor.net/ and reading it right now..

**Comment by whit537** [comment]
Yeah, that was written by Heroku's founding CTO. By using Heroku, we are fairly assured of applying the 12factor principles. :-)

**Comment by techtonik** [comment]
Aha! There are of limitation on Heroku, but they are smart guys. =)

**Comment by whit537** [comment]
Anything specific you want to call for here, @techtonik? To me it looks like we're already observing this by virtue of our using Heroku.

**Comment by whit537** [comment]
Closing as already done (via Heroku).
