### ISSUE TITLE
Revise Heroku // Add custom buildpack

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#415]
Looks like we need (#410) to build our own buildpack for Heroku, because it doesn't vendorize dependencies (https://github.com/heroku/heroku-buildpack-python/issues/261).

 * [  ] document deployment process
   * [  ] explain what is Heroku
   * [  ] explain what is buildpack
 * [  ] fork Python buildpack
   * [  ] add command to use our vendorized dependencies

Document what buildpack are used to set repeatable and common environments, but they don't ues Makefile.

 * [  ] add multiple buildpacks for SASS, npm etc.

**Comment by whit537** [comment]
@techtonik We vendor in dependencies over on `gratipay.com`. Why is that not an option here on IG?

**Comment by whit537** [comment]
In fact, I'm seeing `vendor/` here as well. Are we simply not invoking `pip install` properly?

**Comment by techtonik** [comment]
Not we, Heroku.

**Comment by whit537** [comment]
@techtonik Okay, I believe vendored packages are working properly under Heroku over on `gratipay.com`. Compare here with there?

**Comment by techtonik** [comment]
@whit537 can you paste the build log? I don't have access to see it.

**Comment by techtonik** [comment]
I believe Gratipay doesn't work on Windows anymore, because it is unable to download binary wheels there after https://github.com/gratipay/gratipay.com/pull/3292 was reverted.

**Comment by whit537** [comment]
Closing because this is overkill. Please provide more information.
