### ISSUE TITLE
inside.gratipay.com repo does not have a CONTRIBUTING.md file.

### ISSUE THREAD

**Issue by webmaven** [gratipay/inside.gratipay.com#417]
For consistency's sake, even though it is self-referential, I think we should more or less duplicate [the file in the gratipay.com repo](/gratipay/gratipay.com/blob/master/CONTRIBUTING.md).

**Comment by techtonik** [comment]
This will create a loop. If people need another document to say that they CAN contribute right now, then it should be the first thing at the top. But yes, CC0 is welcoming and should be visible. Not sure about CONTRIBUTING.md name though. It sounds strange. "contributing" is something you add to common pot, and the pot is not yours, and when you work on inside stuff, that means you do it for yourself, I mean for the team of people who already think in the same way as you. So you're already included if you got as far as filling a pull request.

**Comment by webmaven** [comment]
I realize it is a bit meta, but improving the processes by which we improve Gratipay is a valid area of contribution.

What I am suggesting here is merely a minor improvement of the *documentation* of how we improve Gratipay, if someone were to come across this repo first for some reason. The documentation doesn't *have* to be in the form of a copy of [the file in the gratipay.com repo](/gratipay/gratipay.com/blob/master/CONTRIBUTING.md), it could instead just be a section added to the existing [README](/gratipay/inside.gratipay.com/blob/master/README.md) file.

There are other improvements that can be made to this repo's README, and I'll be glad to take a stab at a new-and-improved version if no one else is interested in doing so.

@techtonik:
> [This will create a loop.](https://github.com/gratipay/inside.gratipay.com/issues/417#issuecomment-159374348)

So?

**Comment by techtonik** [comment]
@webmaven I just added my 0.02 cents - no need to seek consensus for me on this issue - everything that helps people to get onboard is welcome.
