### ISSUE TITLE
use Loomio

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#420]
[Loomio](https://www.loomio.org/) is a tool for group decision making. How does it compare with GitHub Issues? Would it be better than GitHub Issues in a cooperative (#72) and/or holacratic (#404) future? What kinds of decisions would it be better for?

**Comment by whit537** [comment]
> Greetings! I represent a payments company called Gratipay, and to be honest, I think Enspiral/Loomio and Gratipay should be friends and partners. Over at Gratipay we're starting to think more seriously about our formal governance. Loomio is a tool we're considering adopting (https://github.com/gratipay/inside.gratipay.com/issues/420) and Enspiral is an example we're considering following (https://github.com/gratipay/inside.gratipay.com/issues/72#issuecomment-159727340).
>
My immediate purpose for asking to join this group is to lurk and observe Loomio in action. May I? :-)

![screen shot 2015-11-25 at 4 09 37 pm](https://cloud.githubusercontent.com/assets/134455/11409588/078ce4b4-938f-11e5-8762-5d8f66ad9898.png)

https://www.loomio.org/g/WmPCB3IR/loomio-community

**Comment by whit537** [comment]
https://github.com/loomio/loomio/issues/2756 having been resolved, I've created a Gratipay group on Loomio:

https://www.loomio.org/g/NFuLByXn/gratipay

**Comment by whit537** [comment]
It's currently as wide-open a possible, so feel free to experiment with it. :-)

**Comment by whit537** [comment]
Alright! I've been lurking the [Loomio Loomio](https://www.loomio.org/g/WmPCB3IR/loomio-community), and now have started poking around at [a clean Gratipay group](https://www.loomio.org/g/NFuLByXn/gratipay) (I was waiting for https://github.com/loomio/loomio/issues/2756). Loomio is basically **a piece of software that formalizes the usual +1/-1 open-source voting process** (cf. this [request for same inside GitHub](https://github.com/isaacs/github/issues/9) and this [attempt to deliver](https://www.bountysource.com/extension)). The heart of Loomio is a discussion board with a "proposals" feature alongside it, with [all sorts of suggestions](http://blog.loomio.org/2015/09/18/9-ways-to-use-a-loomio-proposal-to-turn-a-conversation-into-action/) for how to use this feature. Loomio itself doesn't seem to encode any more formal structure than that (cf. https://github.com/gratipay/inside.gratipay.com/issues/404#issuecomment-160113156).

I'm finding that, in practice, Loomio gets stretched well beyond its core decision-making design—in a bad way, where it ends up looking a lot like [yet another forum](https://www.loomio.org/g/C7I2YAPN/loomio-community-installing-loomio). When am I supposed to use [GitHub](https://github.com/loomio/loomio/pull/2755#issuecomment-159738902)? [Trello](https://trello.com/b/tM6QGCLH/loomio-roadmap)? [Loomio](https://www.loomio.org/d/LuAlGpC3/introduce-yourself-to-the-loomio-community?comment=859614)? Notably, while there are prominent pie charts on the side of those threads that have a proposal, there is no big "Close" or "Merge" button at the bottom of every thread, as there is on GitHub. Launching proposals is easy, but landing them appears harder. I'm seeing threads that are [years old](https://www.loomio.org/d/q9AiRnZN/join-forces-with-diaspora) and others that are seemingly [intended to live forever](https://www.loomio.org/d/LuAlGpC3/introduce-yourself-to-the-loomio-community)(!).

In other words, if we use Loomio, we should be clear about *why* and *how* we want to use it.

For most decisions, it's not clear to me that Loomio provides sufficient value over GitHub issues to justify the introduction of an additional channel and source of truth. Certainly I don't think we should use it as a customer support forum.

Loomio could add value when we want a formal vote. To the best of my knowledge, we've only called for a vote once, for [the first rename attempt](https://github.com/gratipay/gratipay.com/issues/138#issuecomment-7408743). I can imagine us needing to vote more formally more often in a cooperative future (#72), and Loomio could be part of the answer to the question of [how to run an annual meeting over the Internet](https://github.com/gratipay/inside.gratipay.com/issues/72#issuecomment-159733572). Along those lines, I'm intrigued to learn more under #421 about how Enspiral Ventures are constituted, and function in practice.

**Comment by Sirjazzfeet** [comment]
Github has a programmer centric user interface and terminology, with a lot of clutter for the non-programmer. So I think Loomio or something like it can go a long way towards living up to the value of openness, lowering the entry barrier for newcomers, most of whom will perhaps not be programmers.

**Comment by whit537** [comment]
> Github has a programmer centric user interface and terminology, with a lot of clutter for the non-programmer. So I think Loomio or something like it can go a long way towards living up to the value of openness, lowering the entry barrier for newcomers, most of whom will perhaps not be programmers.

@catskul and I were discussing this very idea earlier this evening. I live in his hometown, Ambridge, where we've been piloting a project [using GitHub issues for citizen engagement](https://github.com/ambridge/ambridge). That's where I am especially on the fence about Loomio vs. GitHub. I've gone ahead and ticketed https://github.com/Ambridge/Ambridge/issues/70 about moving to Loomio for citizen engagement in Ambridge.

I'm more comfortable sticking with GitHub for Gratipay, because of the momentum we have, and the fact that we're primarily building software. GitHub isn't *that* cluttered if you're only looking at Issues.

**Comment by Sirjazzfeet** [comment]
Its true you can get use to GitHub, I'm use to it now and its easy for me. But clearly not the most open interface for newcomers, so will increase inequality and decrease diversity somewhat.

**Comment by whit537** [comment]
On another view, downplaying GitHub because "it's too hard" reinforces the idea that programming and technology are only for a special class of people who are "good enough" for it. You've gotten over the GitHub hump, @Sirjazzfeet. The same is true for citizens of Ambridge. If we focus more on outreach and education, we can decrease the confidence barrier to participating in collaborative online projects, which almost always have a software component in addition to a managerial aspect. Siloing those two aspects seems to me to *decrease* equality and diversity. Lets not underestimate people! :-)

**Comment by Sirjazzfeet** [comment]
If we want to be open we have to accept the world as it is. Most people are not programmers and never will be. So it presently is for a specialised class of people- in America, mostly middle class white males. So simply ignoring that is discrimination against sex and race, amplifying inequality - not "open". On a slightly seperate note: do you assume that everyone needs to learn to code?

**Comment by whit537** [comment]
> Most people are not programmers and never will be.

Agreed. Participation in open source can and should take many forms besides coding.

> On a slightly seperate note: do you assume that everyone needs to learn to code?

No. I'm suggesting that people can use GitHub Issues *without* learning to code, and that doing so can help dissolve a barrier to participation in open source. Everyone can be *comfortable around* code—if they're not, we're doing something wrong.

> simply ignoring that
> Education is good

Right. When I say we need to "focus more on outreach and education," I'm talking about intentional, active work, not passive wishful thinking. For example, I'm currently on-site consulting for a startup that has had 80 interns in the past three years, 50% of whom are women, many of whom they've subsequently hired. This fact is the result of a highly intentional pedagogical process. I find it inspiring! :-)

**Comment by whit537** [comment]
Since GitHub issues functions like a mailing list, this article on the way email "reproduces certain pathologies" is relevant this conversation. I think the main take-away for us here is this advice:

> Actively seek alternatives to email for decision making processes of any importance, especially those involving how the group works internally, items relating to strategy, or issues where a quorum really should be in place.

https://austerityprotests.wordpress.com/2015/05/03/email-etiquette-for-virtual-collectives/

That's how I think we should use Loomio.

**Comment by mattbk** [comment]
Isn't any discussion going to act (in essence) like a mailing list? Messages along a temporal axis are subject to most of the problems listed at that link, regardless of the platform used.

**Comment by whit537** [comment]
@mattbk Yes, but Loomio gives you the ability to collect a vote and thereby make sure you have a quorum of the people you care about weighing in.

**Comment by Sirjazzfeet** [comment]
I do think we should use both. Github leaning towards technical management and updates, Loomio leaning more towards organisational discussions and decisions. Or something like along those lines.

**Comment by kaguillera** [comment]
+1 for using both as @Sirjazzfeet suggested

**Comment by mattbk** [comment]
+1 on that as well.

**Comment by whit537** [comment]
I've been lurking in the Loomio Community on Loomio. Here's the first instance I've noticed of a Loomio proposal "[done right](https://www.loomio.org/d/CeMFoapG/ux-engaging-people-with-notification-emails-without-overwhelming-them-with-noise)."

**Comment by whit537** [comment]
> I noticed your group’s free trial has expired.
>
I’d appreciate if you were able to answer a few quick questions:
>
 - ​How is your group enjoying Loomio?
 - Is there anything that you are finding difficult?
 - What could we do to make the experience of your group better?
 - Has your group discussed which [pricing plan](https://www.loomio.org/pricing) suits you best? (e.g. Gift, Standard or Plus)
 - Is there any other arrangement that would better suit you?
>
Thanks in advance for your answers!

**Comment by whit537** [comment]
I've been using Loomio for real for the first time this week, in the "[Buy Twitter](https://www.loomio.org/g/PKBSd1xn/)" group (likely to shift emphasis soon). The main thing I miss vis-a-vis GitHub is the ability to close issues. It's possible to record the outcome of a proposal, but the sense of finality is missing, IMO.

**Comment by whit537** [comment]
After using Loomio for real, I don't see enough value in it to introduce it as an additional source of truth beyond GitHub. Reactions let us [quasi-vote](https://github.com/gratipay/inside.gratipay.com/issues/867#issuecomment-257543399) as well as we could on Loomio.
