### ISSUE TITLE
bring back no-strings-attached gifts to individuals

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#423]
Looks like we've lost the baby. I mean Gratipay was born as Gittip with no strings attached. Today we are heading towards some organizational process that nobody has time to follow. Regardless of what we choose to protect us from atrocities of legal system, there is still a way we can help people to do what we did - help to tip each other.

For that, we should not do money transfer on behalf of people. Then we are not MSB (money transfer business) and not helping money laundering. Let's just help people do transfer themselves. How it works?

The person assigns how much does he/she wants to redistribute to others through Gratipay. But he doesn't add any credit card to that or something. Instead, on each week that person takes the distribution graph out of Gratipay and transfers the listed amounts through blockchain manually. We then validate through blockchain that he transferred the money to the (Bitcoin) accounts listed as recipients, and make a record.

That's a hack to get back Gratipay 1.0 back online.

**Comment by whit537** [comment]
> we are heading towards some organizational process that nobody has time to follow

Meaning holacracy (#404), yes?

**Comment by whit537** [comment]
> Let's just help people do transfer themselves. How it works?

http://liberapay.com/
https://recurrency.us/
https://www.patreon.com/
https://bitcoin.org/en/

**Comment by whit537** [comment]
Retitled. Let's use this for the ticket that @mattbk asked for, bringing back Gratipay 1.0 (have a link, @mattbk?).

**Comment by mattbk** [comment]
I'm not sure to what you are referring?
