### ISSUE TITLE
onboard @sammyshj

### ISSUE THREAD

**Issue by sammyshj** [gratipay/inside.gratipay.com#424]
Are there any summer internship opportunities at Gratipay for summer 2016 for the role of Software Engineering?

**Comment by whit537** [comment]
Thanks for inquiring, @sammyshj! We'd be happy to have you, yes! :-)

What are your goals for an internship? What is your skillset and what areas are you specifically interested in?

I am re-titling this ticket to reflect our practice of onboarding new developers—interns or not. :-)

**Comment by sammyshj** [comment]
Hello @whit537 ,

I have worked mostly with C++, Python and web technologies(JavaScript, Python web MVC frameworks). Most of my work is linked to my Github account. I am more interested in back-end. This involves everything from creating APIs, handling database queries or handling the requests to a web server.
I will be having break from university during the summers(May-July) during which I can give my full time. Are there any projects that I could work on during that time? Also, does Gratipay offer any such kind of internships for university students?

Hoping to hear back from you soon. Thanks!

**Comment by whit537** [comment]
> Are there any projects that I could work on during that time?

Yes, there are a lot of projects! May is a ways off, though, it's hard to know what will need to be done then. Want to get started on something now? :-)

> Also, does Gratipay offer any such kind of internships for university students?

We've never done a formal internship before, no. Are you looking to do an internship for credit?

**Comment by mattbk** [comment]
See also attached resume at https://gratipay.freshdesk.com/helpdesk/tickets/3508 (login required). Going to close that ticket since things are happening here.

**Comment by sammyshj** [comment]
Hello @whit537 ,
Yes, I can look at the work going on right now and then decide which project looks interesting!
Regarding the internship, it is not for credit. I like contributing to software and writing code that affects many users from around the globe and I think that an internship is a very good opportunity to carry this out.

**Comment by whit537** [comment]
Awesome! The first step would be to install Gratipay locally. We provide instructions in the [README](https://github.com/gratipay/gratipay.com#readme). Any questions you have at all, feel free to ask them on this ticket. That's what it's for! :-)

**Comment by sammyshj** [comment]
Yes, I have installed Gratipay locally. Now, do I work on an issue from the issue tracker, or is there something else to work on?

**Comment by mattbk** [comment]
Hi @sammyshj, have you looked over http://inside.gratipay.com?

Everything there is to do is in github issues. In the Radar tickets (here at https://github.com/gratipay/inside.gratipay.com/issues), @whit537 gives an overview of what we should be working on each week.

**Comment by whit537** [comment]
Nice! Yeah, let's find you a good first ticket to work on ...

**Comment by whit537** [comment]
I'm looking at https://github.com/gratipay/gratipay.com/milestones/Team%20Basics and https://github.com/gratipay/gratipay.com/milestones/Pivot, those are our current milestones ...

**Comment by whit537** [comment]
I almost want to put you on https://github.com/gratipay/gratipay.com/issues/835, switching to immutable ids everywhere in our database schema. That would help you get familiar with our schema, which is really foundational to the app. It seems like you should be able to chip away at it piece by piece. Interested in that, @sammyshj? If so we can pick up the conversation over there ...

**Comment by whit537** [comment]
Closing since we seem to have lost you, @sammyshj. Drop a line if you want to pick back up! :-)
