### ISSUE TITLE
Create menu for the retreat

### ISSUE THREAD

**Issue by clone1018** [gratipay/inside.gratipay.com#426]
So we'll be feeding an abnormal amount of people, and that means thinking about what we make for breakfast/lunch/dinner each day. Me and Miguel are down for cooking all/most of the meals. We enjoyed it last time and we didn't burn anything! Of course anyone else can cook instead or help us out.

Here's our vomit thoughts so far:
Hopefully for Dinner on Friday @whit537 will invite some of his townmates, and we can have a nice gathering like last year. We had Sheppards Pie last year, but it was a LOT of prep peeling the potatoes.

We'd like to make some crazy tacos one of the nights, things like fried avocado and friend chicken tacos. They're crazy good and easy to make.

More later, let me know your ideas.

**Comment by whit537** [comment]
> an abnormal amount of people

Probably not as abnormal as last year. Hopefully still a party Friday though, yes.

> Create menu for the retreat
> vomit thoughts

Hmm ... ;-)

**Comment by whit537** [comment]
I have a friend that makes sushi. Was thinking of inviting him for Friday?
