### ISSUE TITLE
fix markdown regressions from switch to mistune

### ISSUE THREAD

**Issue by mattbk** [gratipay/inside.gratipay.com#428]
http://inside.gratipay.com/howto/build-gratipay

**Comment by whit537** [comment]
:-(

I also noticed `---` on http://inside.gratipay.com/big-picture/welcome not getting turned into `—` (mdash).

It's something to do with a change in markdown renderer, I think.

@techtonik Weren't you involved with that? Do you remember what change we made?

**Comment by mattbk** [comment]
As well as http://inside.gratipay.com/howto/tell-people-about-gratipay, but I imagine several pages have issues.

**Comment by whit537** [comment]
For the `---` the issue is that we never reimplemented [SmartyPants](https://daringfireball.net/projects/smartypants/) when switching to mistune (https://github.com/gratipay/inside.gratipay.com/pull/339; cf. https://github.com/lepture/mistune/issues/57). Not sure about the HTML leakage ...

**Comment by whit537** [comment]
@techtonik Are you able to work on this?

**Comment by whit537** [comment]
https://pypi.python.org/pypi/smartypants/

Does it match what we were getting [from Hoedown](https://github.com/hoedown/hoedown/blob/980b9c549b4348d50b683ecee6abee470b98acda/src/html_smartypants.c) via misaka?

**Comment by techtonik** [comment]
@whit537 sorry, I got ill - a week with temperature, and nerve in my right hand is aching so it is very painful to type. I hope that it will be better tomorrow. To catch things like this early we should add spider test like awesome-bot for links. Also I don't see where this build page is linked from through google `info:` query.
