### ISSUE TITLE
delegate team review more

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#435]
Can we talk about team review? My sense is that we're getting into a groove with it, and I'd like to partially extricate myself from the process so I can more pay attention to other things. Seems like a lot of what we're seeing are `Details` back-and-forths. In those cases my preference would be to not be involved, in the same way that I'm not involved in level 1 email support. I'd like to only be involved in `Brand Fit?` cases and maybe some of the more difficult `Open Work?` cases.

@mattbk Are you willing to run point on L1 team review? You've already got admin permissions on Gratipay.com, so you have what you need to actually approve or reject teams. I propose that if you and either @webmaven or @kaguillera give a team the ol' "LGTM," then you can proceed to approve them without needing to hear from me explicitly. Would you be comfortable with that?

The burden will be on me, then, to flag any team review tickets with `Brand Fit?` or `Open Work?` in the first week they're open, to signal that I want to be involved in reviewing that team further. Of course, you can also @mention me in on any you think I'll care about.

Waddya say, @mattbk? :-)

**Comment by mattbk** [comment]
The main issue with that is needing someone else who will update the details in the database. If "make teams editable" is landed, then life would be easier.

**Comment by whit537** [comment]
Ah, excellent point. Okay, setting this to `Blocked` on that.

**Comment by webmaven** [comment]
:+1:

**Comment by whit537** [comment]
@mattbk This this unblocked now?
