### ISSUE TITLE
brainstorm name-brand potential customers

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#436]
Who should be accepting payments on Gratipay?
- **Wikipedia**
- **Internet Archive**—donation receipts are signed by Wendy Hanamura, Director of Partnerships
- **Firefox**

**Comment by mattbk** [comment]
https://github.com/fisharebest/webtrees is one I use. Is this issue about large targets?

**Comment by whit537** [comment]
@mattbk Yes, let's make this about large targets. Who would we be proud to have on Gratipay? A reference customer that we can use in conversation with others ... "Well, [Wikipedia] is a customer ..."

**Comment by mattbk** [comment]
https://github.com/Homebrew/homebrew

**Comment by whit537** [comment]
@mattbk They used to be active: https://gratipay.com/~Homebrew/. Want to reach out in a ticket in their repo? :-)

**Comment by mattbk** [comment]
https://github.com/gratipay/inside.gratipay.com/issues/446#issuecomment-166681169

> Would [GitLab] be interested in using Gratipay?

**Comment by whit537** [comment]
I mean, while we're dreaming: Panera ran [a pay-what-you-want experiment](http://paneracares.org/guidelines/) for a few years. Bon Jovi's is [still going](http://www.jbjsoulkitchen.org/en/about).

**Comment by mattbk** [comment]
See also https://github.com/gratipay/gratipay.com/issues/1149.

**Comment by whit537** [comment]
Let's Encrypt

https://letsencrypt.org/2016/09/20/what-it-costs-to-run-lets-encrypt.html

**Comment by whit537** [comment]
What about a bundle? "Give to the Open Internet ... we'll distribute amongst these fine organizations."

**Comment by mattbk** [comment]
> What about a bundle? 

User-curated bundles would be neat someday...

**Comment by whit537** [comment]
We had a similar idea back in the day: https://github.com/gratipay/gratipay.com/issues/449. I like "bundles" better.

**Comment by mattbk** [comment]
It's also similar to proportional giving.

**Comment by whit537** [comment]
> donation receipts are signed by Wendy Hanamura, Director of Partnerships

Tweeted and called (there was a number on the receipt as well)—talked to Chris the office manager. I am registered for lunch next Friday as part of #867, should be able to meet Wendy then. 👍

**Comment by whit537** [comment]
Gonna move that conversation into Pipedrive (#851, #855).

**Comment by whit537** [comment]
I've pitched Mozilla at https://github.com/mozilla/donate.mozilla.org/issues/1637. 😳

**Comment by whit537** [comment]
I've got Pipedrive deals going for Wikimedia, Mozilla, Internet Archive, and Homebrew ([cf.](https://twitter.com/whit537/status/794303153822961664)). Closing!
