### ISSUE TITLE
Unpause Piwik

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/inside.gratipay.com#437]
Reticketed from https://github.com/gratipay/gratipay.com/issues/3034#issuecomment-164366047

> I'd like to work on analytics for users - Is it okay if I setup a Piwik instance on Digital Ocean? Do we have a team account there that I can be added to?

**Comment by whit537** [comment]
> Do we have a team account there that I can be added to?

Done. Note that our primary Digital Ocean account is in LastPass, so I think you should have access to it if you need to "sudo" there in the future.

**Comment by rohitpaulk** [comment]
> Because your email address is already associated with a DigitalOcean account, you’ll need to register with a different address to join Gratipay’s team.

:disappointed:

**Comment by rohitpaulk** [comment]
I've linked another one of my email IDs.

**Comment by whit537** [comment]
Yeah that's an unfortunate limitation of Digital Ocean's team implementation. :-/

Maybe https://digitalocean.uservoice.com/forums/136585-digitalocean/suggestions/8410464-re-approach-the-way-teams-are-implemented is relevant?

**Comment by rohitpaulk** [comment]
Yep, voted :)

**Comment by whit537** [comment]
:-)

**Comment by whit537** [comment]
Closing in light of https://github.com/gratipay/inside.gratipay.com/issues/600#issuecomment-216349297.
