### ISSUE TITLE
incorporate in Estonia

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#438]
Reticketed from https://github.com/gratipay/inside.gratipay.com/issues/199#issuecomment-100655302 and https://github.com/gratipay/inside.gratipay.com/issues/242#issuecomment-135587886.

> The Republic of Estonia is the first country to offer e-Residency — a transnational digital identity available to anyone in the world interested in administering a location-independent business online.

The purpose of moving Gratipay to Estonia would be to make it easier to convert to a worker-owned cooperative (#72), because our workers are citizens of many different countries.

**Comment by whit537** [comment]
> “e-Estonia” is a term commonly used to describe Estonia’s emergence as one of the most advanced e-societies in the world – an incredible success story that grew out of a partnership between a forward-thinking government, a pro-active ICT sector and a switched-on, tech-savvy population.

https://e-estonia.com/

**Comment by techtonik** [comment]
Estonia is awesome. Let's try to create Gratipay LLC. Estonia. =)

**Comment by whit537** [comment]
> Estonia is proudly pioneering the idea of a country without borders.

https://e-estonia.com/e-residents/about/

Yeah, we're gonna do this.

**Comment by whit537** [comment]
> Estonia is awesome. Let's try to create Gratipay LLC. Estonia. =)

@techtonik Let's do it! :dancer:

**Comment by whit537** [comment]
> e-Residency does not confer citizenship, tax residency, residence or right of entry to Estonia or to the European Union. The e-Resident smart ID card is not a physical identification or a travel document, and does not display a photo.

**Comment by whit537** [comment]
Alright everyone, who's in? :-)

https://apply.e-estonia.com/

**Comment by rohitpaulk** [comment]
:hand:

**Comment by whit537** [comment]
!m @rohitpaulk

**Comment by whit537** [comment]
I've got the application all filled out, but looks like I'll need to run up to CVS to get a photo taken:

![screen shot 2015-12-15 at 9 29 54 am](https://cloud.githubusercontent.com/assets/134455/11813268/753c917e-a30e-11e5-8e07-558058c8377a.png)

**Comment by whit537** [comment]
> Furthermore, in Estonia company income is not taxed, and taxes are paid only upon profit distribution to shareholders.

Hmm ... this is a counter-indication to modeling payroll (https://github.com/gratipay/gratipay.com/issues/3433) as profit distributions.

**Comment by whit537** [comment]
What's Estonia's tax rate?

**Comment by whit537** [comment]
> Estonian resident companies and permanent establishments of the foreign entities (including branches) are subject to income tax only in respect of all distributed profits (both actual and deemed), including:
>
 - corporate profits distributed in the tax period;
 - gifts, donations and representation expenses;
 - expenses and payments not related to business.
>
Fringe benefits are taxable at the level of employer. The employer pays income tax and social tax on fringe benefits.
>
All distributions are subject to income tax at the rate of 20% of the amount of taxable payment. The transfer of assets of the permanent establishment to its head office or to other companies is also treated like a distribution. As of 1 January 2009, dividends paid to non-residents are no longer subject to withholding tax at the general rate of 20%, irrespective of participation in the share capital of the distributing Estonian company. However, various withholding taxes may still apply to other payments to non-residents if they do not have a permanent establishment in Estonia or unless the tax treaties otherwise provide.
>
As the tax period of corporate entities is a month, the income tax shall be returned and paid monthly by the 10th day of the following month.

http://www.investinestonia.com/en/investment-guide/tax-system#section-corporate-income-tax

**Comment by whit537** [comment]
http://www.lawyersestonia.com/

**Comment by whit537** [comment]
> As of 1 January 2009, dividends paid to non-residents are no longer subject to withholding tax at the general rate of 20%, irrespective of participation in the share capital of the distributing Estonian company. 

What if Gratipay, LLC forms Gratipay Estonia, LLC as a subsidiary, and we are all non-resident shareholders in Gratipay Estonia, LLC?

**Comment by whit537** [comment]
I have reached tab collapse.

![screen shot 2015-12-15 at 12 09 35 pm](https://cloud.githubusercontent.com/assets/134455/11817810/c467ded2-a324-11e5-884b-3840a9e5d33a.png)

**Comment by whit537** [comment]
I am down rabbit holes on Estonian tax law and owner draws.

> An entry for "owner's drawing" in the financial records of a business represents money that a company owner has taken from the business for personal use. Owner's draws are routine occurrences in small businesses. They don't qualify as business expenses, however. Rather, they are distributions of company profits -- much like the dividends that a corporation would pay.

http://smallbusiness.chron.com/owners-drawing-accounting-24805.html

**Comment by whit537** [comment]
Braintree is listed on https://e-residency.zendesk.com/hc/en-us/articles/205207751-Online-payment-providers.

**Comment by techtonik** [comment]
I know that I need to pay ~12% on everything I get from Estonia. We have simplified rules. I will ask lawyers on Thursday.

**Comment by whit537** [comment]
> What if Gratipay, LLC forms Gratipay OÜ as a subsidiary, and we are all non-resident shareholders in Gratipay OÜ?

The alternative is to form Gratipay OÜ, transfer all of the assets from Gratipay, LLC to Gratipay OÜ, and then liquidate Gratipay, LLC. So far it looks like our member-owners can either be e-residents or not. We would pay 20% on distributions to the former.

**Comment by whit537** [comment]
What about VAT?

**Comment by whit537** [comment]
[Estonian law, in English](https://www.riigiteataja.ee/tutvustus.html?m=3)

**Comment by whit537** [comment]
![screen shot 2015-12-15 at 3 57 52 pm](https://cloud.githubusercontent.com/assets/134455/11823897/a755d950-a344-11e5-94e8-b6d89f7c6d4d.png)

> **Your application has been submitted!**
>
Thank you, your application has been submitted successfully and a confirmation e-mail has been sent to you.
>
If your application is approved, your e-Resident smart ID-card will be delivered to the Estonian foreign representation or service point specified in the application.
>
Please note that the whole process until the delivery of the e-Resident smart ID-card takes about a month. The Estonian Police and Border Guard Board will keep you informed about the application process by sending progress update e-mails.
>
If you have any questions, please be free to contact us at e-resident@gov.ee.

**Comment by whit537** [comment]
Another question: how fluidly can we change shares? If that's the basis for take-what-you-want payments then we need to be able to change shares easily.

**Comment by whit537** [comment]
https://github.com/open-eid :-)

**Comment by whit537** [comment]
Alright, I don't know if Estonia is going to be the answer for us, but the next step is to become an e-resident, and I've got the ball rolling on that. We shall see! :-)

**Comment by tormi** [comment]
Hi, https://community.eresnetwork.eu/ might also give some answers ;)

**Comment by whit537** [comment]
Thanks, @tormi! :-)

**Comment by whit537** [comment]
> Estonian Police and Border Guard Board has granted e-Residency to [CHAD WHITACRE.] 
>
You will be notified upon the document’s arrival to the place of issue marked on the application form.

**Comment by chrisdev** [comment]
:+1: @whit537 
An update on my status. My certificates are now setup correctly.  I think is would have been easier (at least on the Mac 0S X) to use the `DigiDoc` and `ID-card util` apps that are available the Mac App store. Does not look like I can setup the mobile based app  according to  http://www.id.ee/index.php?id=36915
>  In order to apply for Mobiil-ID, first consult your mobile operator and sign a Mobiil-ID Agreement. Make sure you take along your ID-card.

I'm going to ask my mobile operator about this tomorrow just to see the look on their faces!

One problem is that it looks like we've got to use a Notary to initially register companies as we do not have addresses in Estonia according to http://www.rik.ee/en/company-registration-portal/e-residency
> Company needs to have an Estonian address. It is not allowed to register P.O. box as an address. 
They provide a list at https://www.notar.ee but who to choose?

Also  stumbled across services like http://eng.liivikas.ee/ that provide a one stop. My friend's company in Belize offers similar services for Belize, so I know that this is a legitimate business practice but I'm not sure that it is wise to go down this route? 

Going to mail some of these guys tomorrow

**Comment by whit537** [comment]
My card is in D.C.! Time to schedule a trip ...

**Comment by chrisdev** [comment]
👍🏼

**Comment by techtonik** [comment]
Starting from February the fee will be 100€ instead of 50€ https://e-estonia.com/e-residents/apply/

**Comment by whit537** [comment]
I never got a response to my email, so I just called. They'll hold my card for up to 6 months. I'm thinking I'll sync up the pick-up with my next visit to Charlottesville for COS, which should be in the next month or two, but not Feb 23-34, because that's the [Estonian national holiday](https://en.wikipedia.org/wiki/Estonian_Declaration_of_Independence)! :dancer:

**Comment by whit537** [comment]
They asked for a week or two of lead time to schedule an appointment.

**Comment by whit537** [comment]
Ghost went with Singapore: https://blog.ghost.org/moving-to-singapore/.

**Comment by whit537** [comment]
> the 2nd most efficient economy on the planet

Switzerland is no. 1, and the USA is no. 3, [btw](http://reports.weforum.org/global-competitiveness-report-2015-2016/competitiveness-rankings/).

**Comment by whit537** [comment]
Estonia is 30th.

**Comment by chrisdev** [comment]
Singapore Corporate banking not so friendly to startups
http://www.guidemesingapore.com/doing-business/finances/corporate-bank-account-opening-singapore

**Comment by Changaco** [comment]
Funny how Ghost's post doesn't mention [human rights in Singapore](https://en.wikipedia.org/wiki/Human_rights_in_Singapore), isn't it?

**Comment by chrisdev** [comment]
@Changaco in the  comments a few people raised the Human Rights issue he does really have not have a good answer given that Ghost is a blogging platform and a non-profit to boot!
> What I *will* say is that we care very deeply about freedom of speech, and every country in the world - without exception - has warts to work on as a result of its history.

**Comment by whit537** [comment]
At this point I'm leaning towards keeping the U.S. LLC as our primary entity, because #72 is moving towards keeping a slimmer legal structure (so there's less pressure to find a legal structure that optimizes for fluid international ownership), and we've already got an LLC set up and we have experience with it. We would then potentially use an Estonian ÖU as a subsidiary to hold a euro bank account. I'm given to understand that Estonia assesses tax on payments from subsidiary to parent; would this apply to *escrow* movements as well?

**Comment by techtonik** [comment]
Belarus is not even in the list of Economies, and human right index is lower than Singapore. But for me the poverty is the reason for most problems - if you don't have money, you don't have rights (lawyers and the stuff).

**Comment by whit537** [comment]
> My card is in D.C.! Time to schedule a trip ...

Scheduled for 12:45 this Friday, June 10!

**Comment by chrisdev** [comment]
👍 I found that on OSX the free Apps in the store  ID-card-utility and DigiDoc 3 were the easiest way to get started!

**Comment by whit537** [comment]
Thanks @chrisdev! Trying to get those working now ...

**Comment by whit537** [comment]
Alright, I'm stuck trying to set up forwarding for my chad.william.whitacre@eesti.ee email address(!). I was able to login to the website using my card, though. That's something.

**Comment by whit537** [comment]
They've rolled out [fully remote company formation](https://medium.com/e-residency-blog/a-new-era-for-location-independent-entrepreneurs-has-begun-ece91cbf8876), no visits necessary ... except for those in the US.
