### ISSUE TITLE
Get back on track with user review

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/inside.gratipay.com#443]
`Unreviewed Accounts (N = 416)`

We have 416 unreviewed accounts! I was digging into history for https://github.com/gratipay/gratipay.com/issues/3878, and we have users who haven't been reviewed for 6 months :confused: 

cc: @whit537, @mattbk

**Comment by mattbk** [comment]
Also, http://inside.gratipay.com/howto/review-accounts is a little out of date.

**Comment by rohitpaulk** [comment]
```sql
SELECT COUNT(DISTINCT(p.username))
  FROM participants p
  JOIN current_payment_instructions cpi ON cpi.participant = p.username -- Only those with tips
 WHERE braintree_customer_id IS NOT NULL
   AND p.is_suspicious IS NULL
   AND NOT is_closed;

=> 68
```

**Comment by whit537** [comment]
As a workaround since this queue is collapsed, I've been only reviewing users during payday where giving > 0.

**Comment by rohitpaulk** [comment]
I [ran Participant.update_giving](https://github.com/gratipay/gratipay.com/pull/3876#issuecomment-165138585) on the entire DB over at #3876, which refreshed a few stale values. 

Viewing the review dashboard on my local, I see ~10 users who have a giving > 0 now.

**Comment by rohitpaulk** [comment]
^ Oh sorry - those values are from *before* payday :)

**Comment by whit537** [comment]
Done!

!m @rohitpaulk
