### ISSUE TITLE
participate in "Made with Creative Commons" project

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#444]
Creative Commons is working on a book project, [*Made with Creative Commons: A book on open business models*](https://www.kickstarter.com/projects/creativecommons/made-with-creative-commons-a-book-on-open-business/description). In their latest email, they are still looking for case studies:

> We need your help though. We could still use more ideas about companies, organizations, and creators to profile. Many of you are sending in suggestions, so please keep them coming! There are no bad ideas. The more possibilities we have to explore, the better the final book will be.

Why not Gratipay? We [use CC0](https://github.com/gratipay/gratipay.com/blob/master/COPYING), after all. :-)

**Comment by whit537** [comment]
To: Sarah and Paul
Subject: Gratipay is an open payments company

> Sarah and Paul,
>
Greetings! I'm responding to your call for additional business models to explore for the Made with Creative Commons book project. I am part of a startup called [Gratipay](https://gratipay.com/), which is a payments company focused on open source and the collaborative economy. We've been around for about three years, and have been exploring the concept of an "open company," experimenting with such things as "take-what-you-want" salaries.
>
Thanks for your work, and let me know if you'd be interested in a conversation! :-)
>
P.S. As you might expect, I'll need to at least summarize our email thread publicly for the Gratipay community. Here's our internal ticket about it. If you'd prefer that I copy your responses verbatim, or simply move the conversation to GitHub, let me know! :-)

**Comment by sarahpearson** [comment]
Thanks, Chad! Can you help us understand exactly how Gratipay uses CC0 (or other CC legal tools) in its business model? Feel free to point me to something online if that is easier. Once we have a baseline understanding, we can determine how it might fit with the other profiles we have so far. Thank you!

**Comment by whit537** [comment]
@sarahpearson Thanks for jumping in here! :-)

We pretty closely curate the people and organizations that we permit to receive money through Gratipay, and one of the criteria in our [review process](http://inside.gratipay.com/howto/review-teams) is what we call "open work." The part of open work we've spent the most time thinking about and experimenting with—because it's the least well-understood—is how to compensate voluntary labor: how do you split revenue among open source contributors? among wiki editors? etc. However, a more straightforward part of our definition of open work (which to be honest I'm not sure we've really made clear yet in all of our documentation and site copy, partly because it's so obvious), is that the product or service that our receivers provide should be freely/openly licensed.

Most of our customers to date are open source projects, though we also have a few co-working spaces and maybe some other things. While Gratipay itself [uses CC0](https://github.com/gratipay/gratipay.com/blob/1933/COPYING) for its code, my hunch is that most of our customers probably are using OSI-approved software licenses, with perhaps CC licenses for documentation. Non-software projects with CC licenses would certainly be something we'd love to see as we review new Team applications. To be honest, though, I don't know off the top of my head the extent to which our current users are using CC licenses. Does that sound like an interesting angle to explore further?

**Comment by sarahpearson** [comment]
Thanks @whit537. It does sound really interesting! For this particular book though, we're specifically looking for non-software examples of CC licensing that are baked into the business model. I'm not sure Gratipay is the right fit based on what you said above, but I'll add it to the list of possibilities to discuss with my co-author.

**Comment by whit537** [comment]
@sarahpearson We would love to see more non-software projects on Gratipay, but yeah, we are definitely software-heavy right now. I'm going to go ahead and close this ticket. If you decide you'd like to pursue the conversation further, we can reopen.

All the best! :-)
