### ISSUE TITLE
gratipay badge?

### ISSUE THREAD

**Issue by jparicka** [gratipay/inside.gratipay.com#445]
I've been looking and I'm lost.
How can I add the gratipay badge on my readme.md file?  https://github.com/ProjectCloudly/Cloudly/blob/master/README.md
Pls advice.  Thank you.  :)

**Comment by mattbk** [comment]
Do you mean a badge like one of those shown here: https://github.com/gratipay/grtp.co?

**Comment by jparicka** [comment]
Cool, thanks!
