### ISSUE TITLE
migrate to GitLab

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#446]
GitLab is gettin' [nicer and nicer](https://about.gitlab.com/blog/). They now use GitLab as their primary feedback loop for GitLab, via award emoji! :-)

Is it time to make the move yet? We're certainly more philosophically aligned with [them](https://about.gitlab.com/about/) than we are with GitHub. Maybe we should test it out with a small project?

**Comment by mattbk** [comment]
I was sort of wondering why Gratipay wasn't built in GitLab.

Would they be interested in using Gratipay?

**Comment by Changaco** [comment]
It's getting nicer… but it's still missing a basic feature: [watching a repository](http://feedback.gitlab.com/forums/176466-general/suggestions/5427278-watch-a-repo).

**Comment by whit537** [comment]
@mattbk Think that'd be one for https://github.com/gratipay/inside.gratipay.com/issues/436?

@Changaco Hmm ... yeah, maybe a blocker.

**Comment by whit537** [comment]
See also: https://github.com/dear-github/dear-github/ and https://github.com/dear-github/dear-github/issues/56.

I predict 2016 will be the Year of GitLab ... which means we may make the jump in 2017. ;-)

**Comment by whit537** [comment]
> You can modify the notification level on each particular project (or globally for your account) to the `Watching` state. You will receive an email for everything that happens in your project.

https://gitlab.com/gitlab-org/gitlab-ce/issues/3414#note_2712093

Does that only apply to projects one owns/is a member of?

**Comment by DouweM** [comment]
GitLab employee here, found this thread via https://github.com/dear-github/dear-github/issues/56 :)

> It's getting nicer… but it's still missing a basic feature: watching a repository.

@Changaco You can actually star a repository (like https://gitlab.com/gitlab-org/gitlab-ce) and see its activity on your "Starred Projects" dashboard: https://gitlab.com/dashboard/projects/starred

> Does that only apply to projects one owns/is a member of?

@whit537 Yeah, the "Watching" notification level only applies to projects one is a member of. Getting email for every new issue on a project you're not a member of is not (currently) possible.

Let me know if you have any other questions!

**Comment by whit537** [comment]
Thanks @DouweM.

> Getting email for every new issue on a project you're not a member of is not (currently) possible.

Can you link us to the ticket for this on the GitLab repo?

**Comment by DouweM** [comment]
@whit537 I'm not aware of one, the closest thing is the [feedback thread](http://feedback.gitlab.com/forums/176466-general/suggestions/5427278-watch-a-repo), but we're moving away from the feedback forum and moving to issues for everything. Feel free to create an issue!

**Comment by Changaco** [comment]
Watchers don't want to log into GitLab regularly to check for activity, they want notifications to come to them.

**Comment by whit537** [comment]
> Feel free to create an issue!

Done! :-)

https://gitlab.com/gitlab-org/gitlab-ce/issues/9013

**Comment by mattbk** [comment]
How big is the GitLab userbase? Are we losing out on not being able to tag people directly?

**Comment by DouweM** [comment]
@mattbk I don't have a number right now, but if you want I can get back to you on that. 

I don't think the smaller user base will be an issue, because the people you would be likely to want to @mention, core team members, users filing issues or users contributing code, have already created a GitLab.com to be able to do that that.

Of course you lose some amount of discoverability and the immense network effect that GitHub brings with it, but how much of a problem that will be depends on the project. We certainly haven't had seen any decrease in people contributing when we moved the main GitLab repository from https://github.com/gitlabhq/gitlabhq to https://gitlab.com/gitlab-org/gitlab-ce :)

**Comment by whit537** [comment]
> For this reason, we feel that having GitLab as a home for safe, open, collaborative development requires being an open source platform itself.

https://about.gitlab.com/2016/01/11/being-a-good-open-source-steward/

**Comment by whit537** [comment]
> If my speculation is right, what will the impact be? GitHub have established themselves as The Place to host our public projects. Surely losing this will be a major blow to free and open source. Well, happily, no. This is how it happens: we construct, and then when we reach a plateau, the wolves come along, destroy what we make, and liberate us to go forth and do better. Psychopaths are the garbage collectors of human society.
>
Whither the ZeroMQ community? I'm going to begin using GitLab for my own projects, and if that works, I'll aim to move the ZeroMQ projects that I care for, to GitLab, after discussion and consensus.
>
Thanks for all the fish, GitHub. And to all GitHubbers, thank you a million times. You did the impossible, and you did it right, and I wish you all the best for your next projects. Hugs. :)

http://hintjens.com/blog:111

**Comment by whit537** [comment]
GitHub's new pricing (#617) pushes us further in this direction.

**Comment by whit537** [comment]
> It's getting nicer… but it's still missing a basic feature: watching a repository.

This [seems](https://gitlab.com/gitlab-org/gitlab-ce/issues/9013#note_12070584) to have been released in 8.8 and deployed.

**Comment by whit537** [comment]
From @sampablokuper in https://github.com/gratipay/inside.gratipay.com/issues/724:

> Please could Gratipay migrate its entire code-base and bug tracker to a code hosting and bug-tracking service that does not *fail* the [GNU Ethical Repository Criteria Evaluations](https://www.fsf.org/news/gnu-releases-ethical-evaluations-of-code-hosting-services)?
>
GitLab is probably a reasonable compromise:
>
- it *[passes](https://www.gnu.org/software/repo-criteria-evaluation.html)* (albeit imperfectly) the GNU Ethical Repository Criteria;
- it supports Git as a first-class DVCS;
- its interface is quite similar to GitHub's;
- it has a large and active user base.

**Comment by whit537** [comment]
The big thing GitLab is missing is critical mass. Reopen when open source has moved there.
