### ISSUE TITLE
onboard @tlevine

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#448]
Reticketing from https://github.com/gratipay/inside.gratipay.com/pull/390#issuecomment-166792602.

> January 4 on is good.
> 
> And it happens that I was thinking over the past few days about when to visit Ambridge. How about the end of March or first week of April?

**Comment by whit537** [comment]
@tlevine If you're feeling whimsical, I believe @clone1018 and Miguel will still be at my house the week of Jan 4 (#392). And/or March into April is fine, too. Do you want to put a date on the calendar now or wait until we get closer?

**Comment by tlevine** [comment]
I want to do week of January 4, but I haven't decided on the exact dates
yet. Do you have any preference on the dates? In case it matters, I
think I'll need a ride from Pittsburgh.

**Comment by whit537** [comment]
We should be able to get you a ride out to Ambridge from Pittsburgh, or suggest a bus depending on the time of day you arrive (the [BCTA Route 1](http://bcta.com/route-1-schedule/) is preferable, but the [PAT Route 14](http://www.portauthority.org/rt/14.pdf) also works). I'm pretty sure (read: hoping that) @clone1018 and Miguel will be at my house all week. I expect @kaguillera will join us on Wednesday and we may see him Thursday as well. I want to sync you up with @kaguillera, so maybe aim to be here for Wednesday?

**Comment by whit537** [comment]
Ping @tlevine. Still interested in working on Gratipay's books with us? Gonna pull off a trip to Ambridge? :-)

**Comment by tlevine** [comment]
It sounds like you want something different from what I had originally
thought, so I dunno if I'm interested in that. Perhaps this will be more
clear when discussed verbally.

Something between like March 25 and April 5 would be a good time to go
to Ambridge.  March 25 is approximate, and April 5 is reasonably firm.

On a completely different note, I was thinking about seeing if I can, as
my one-person consulting sole proprietorship company, buy health
insurance for my sole employee. And now that I'm thinking about
Gratipay, I ponder whether one could start a company entirely for the
purpose of hiring people in order to provide them with health insurance;
moreover, I suspect you have thought about whether this is possible, and
I am curious if you have further comments on this idea.

And in case you are curious as to why I got onto this topic, I had been
unclear as to whether I'd go to Ambridge partly because I wasn't so
clear as to whether I would want to be in the United States at all.  I
have been considering avoiding the United States so I don't have to
figure out how to buy health insurance. But I think I have figured it
out, and I think also that I am required to have USA health insurance or
pay the penalty even if I'm not in the USA; to avoid it, I have to
reside legally in another country or spend at least 330 days within the
tax year outside of the USA.

**Comment by whit537** [comment]
Gosh, I'm not a health insurance expert, but I'm pretty sure best practice is to have health insurance. :-)

I'll be pretty busy with family stuff the weekend of March 25-27 (Easter celebrations—you're welcome to join us :). Between March 28 and April 5 is pretty clear, though.

> It sounds like you want something different from what I had originally thought, so I dunno if I'm interested in that. Perhaps this will be more clear when discussed verbally.

Maybe this is worth pinning down before you make the trip? We don't want to waste your time. ;-)

What Gratipay needs is someone to enter data into our (shiny new!) [accounting system](https://github.com/gratipay/finances). This basically means taking CSV dumps from our bank and upstream processor accounts, and building text files like [this one](https://github.com/gratipay/finances/blob/b9ea24aae20a6b3cedb2556d094ddf4237ce7d9b/FY2013/2012-06.dat) via a PR flow on GitHub. Generating the text files can and should be scripted to some extent, so it seems to me that we're looking for someone with some level of chops in both accounting and scripting.

Does that sound at all close to what you're interested in? What are you interested in? :-)

**Comment by tlevine** [comment]
On 01 Mar 14:34, Chad Whitacre wrote:
> I'll be pretty busy with family stuff the weekend of March 25-27 (Easter celebrations—you're welcome to join us :). Between March 28 and April 5 is pretty clear, though.

Okay then let's at least do March 28 to April 5.

On 01 Mar 14:34, Chad Whitacre wrote:
> What Gratipay needs is someone to enter data into our (shiny new!) [accounting system](https://github.com/gratipay/finances). This basically means taking CSV dumps from our bank and upstream processor accounts, and building text files like [this one](https://github.com/gratipay/finances/blob/b9ea24aae20a6b3cedb2556d094ddf4237ce7d9b/FY2013/2012-06.dat) via a PR flow on GitHub. Generating the text files can and should be scripted to some extent, so it seems to me that we're looking for someone with some level of chops in both accounting and scripting.
> 
> Does that sound at all close to what you're interested in? What are you interested in? :-)

Now it sounds like you do want what I had originally thought.
This sounds good. I am generally interested in easy stuff.

Do the bank and processors provide more standard formats than CSV?

I have been meaning to write something to convert Open Financial
Exchange format (http://www.ofx.net/) or Quicken Interchange Format
(https://web.archive.org/web/20100222214101/http://web.intuit.com/support/quicken/docs/d_qif.html)
to Ledger format.

**Comment by whit537** [comment]
> Now it sounds like you do want what I had originally thought.
This sounds good. I am generally interested in easy stuff.

Cool. Most of the hard work is done, the rest is mostly grunt work to catch up on past history and then monthly maintenance to stay up to date with finances.

> Do the bank and processors provide more standard formats than CSV?

CSV is the lowest common denominator. Fine if you want to explore more esoteric formats.

Sounds like we're generally on the same page and a late-March/early-April trip could be fruitful. Wanna let me know when you line up a bus ticket? I can pick you up downtown or recommend a local bus to get you out to Ambridge.

!m @tlevine :dancer:

**Comment by tlevine** [comment]
On 01 Mar 18:55, Chad Whitacre wrote:
> > Do the bank and processors provide more standard formats than CSV?
> 
> CSV is the lowest common denominator. Fine if you want to explore more esoteric formats.

CSV is not a common denominator because CSV from different institutions
might be different. But I suppose we can check for the other formats
when I'm in Ambridge, because I might not do much before then.

On 01 Mar 18:55, Chad Whitacre wrote:
> Sounds like we're generally on the same page and a late-March/early-April trip could be fruitful. Wanna let me know when you line up a bus ticket? I can pick you up downtown or recommend a local bus to get you out to Ambridge.

I have booked a train that arrives in Pittsburg in the morning of March
27. I could stay in Pittsburg for a night or meet you that evening in
Ambridge.

**Comment by whit537** [comment]
> I have booked a train that arrives in Pittsburg in the morning of March 27.

Nice! 

> I could stay in Pittsburg for a night or meet you that evening in Ambridge.

Lemme check with my family and get back to you ..

**Comment by whit537** [comment]
cc: @JessWhit

**Comment by tlevine** [comment]
On 01 Mar 14:34, Chad Whitacre wrote:
> What Gratipay needs is someone to enter data into our (shiny new!) [accounting system](https://github.com/gratipay/finances). This basically means taking CSV dumps from our bank and upstream processor accounts, and building text files like [this one](https://github.com/gratipay/finances/blob/b9ea24aae20a6b3cedb2556d094ddf4237ce7d9b/FY2013/2012-06.dat) via a PR flow on GitHub. Generating the text files can and should be scripted to some extent, so it seems to me that we're looking for someone with some level of chops in both accounting and scripting.

There is a good chance that I will decide to use GnuCash.
In case I do that, this will be helpful.
https://github.com/MatzeB/pygnucash

My preference is still to generate rough ledger files programmatically
and then reconcile in a text editor, but I might be faster in GnuCash.

**Comment by whit537** [comment]
Could do. We can hash it out when you're here but I think that if we can converge on ledger format in the repo then it doesn't matter how you generate them.

**Comment by tlevine** [comment]
How annoying would it be if we postpone my visit?
I'm getting tired of moving around so much.
We could talk about accounting on the phone or something.

**Comment by whit537** [comment]
Zero annoying. :-)

How about a video call next Wednesday or Thursday (30th / 31st) at 2pm US/Eastern?

**Comment by tlevine** [comment]
How about the Wednesday or Thursday after that, any time of day?
Or any day next week

**Comment by tlevine** [comment]
Actually tomorrow or Thurday is just fine too, but phone might be easier
for me on those days.

**Comment by tlevine** [comment]
Monday or Tuesday would be convenient because I have other meetings
those days and can thus group my distractions.

**Comment by whit537** [comment]
@tlevine Let's aim for Tuesday. What's a good time?

**Comment by whit537** [comment]
Actually, I'm busy Tuesday morning ... between 1 and 4 would be best for me.

**Comment by tlevine** [comment]
Let's do 1 pm. I'll have until 3 pm, in case we need it.

**Comment by whit537** [comment]
Cool. I probably have something at 2pm now but I can see about bumping that a bit ...

**Comment by tlevine** [comment]
Scheduling this might be more work than it's worth because we might not
have much to talk about yet. Wanna just call or otherwise poke me any
day after today?

Phone is +1 229 516 1541
Handle on oftc and Freenode is tlevine

**Comment by whit537** [comment]
Sounds good. Let's keep 1pm Tuesday penciled in, I'm gonna aim for that.

**Comment by tlevine** [comment]
https://chatb.org/#WJAWYFVCQSDUVX

**Comment by whit537** [comment]
This seems to have cooled. ✌️
