### ISSUE TITLE
Precompile all sass

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#461]
I want to upgrade libsass and see that it doesn't break anything. Do we have an ability to replace our dynamic aspen .css files with generated statics?

**Comment by whit537** [comment]
I believe we have this over on gratipay.com. Look in `gratipay/wireup.py`.

**Comment by techtonik** [comment]
I see. https://github.com/gratipay/gratipay.com/blob/1934/gratipay/wireup.py#L268 Cool.
