### ISSUE TITLE
Changaco and whit537 finally meet?

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#464]
Reticketed from https://github.com/liberapay/liberapay.com/issues/1#issuecomment-171235452.

@JessWhit and I are planning to be in France in May for OuiShare Fest (#314).

@Changaco The Fest runs through Friday night, and we fly out Tuesday evening (May 24). Does it make sense for you to meet us in Paris? At this point I think we're also open to traveling within France after the Fest. We'll need to decide fairly soon, though, so we can book rooms. Any ideas? :)

**Comment by Changaco** [comment]
I should be able to meet you in Paris, but you can also come visit Normandy. There are plenty of things to see, the Mont Saint-Michel for example, and a lot of WW2-related stuff.

You can get from Paris to Caen easily, by bus/carpool/train, and from there to many other towns in the county by bus/carpool. My dad can drive us around too (though there would be a communication barrier since you don't speak french and he doesn't speak english).

**Comment by whit537** [comment]
I was thinking it might be interesting to visit the beach, because a number of the landing craft used on D-Day were manufactured here in Ambridge. I'll have to talk to @JessWhit and see what she is interested in. Thanks for the invite!

> you don't speak french and he doesn't speak english).

Not yet! Je suis ... on my third Duolingo lesson. :)

**Comment by Changaco** [comment]
> I was thinking it might be interesting to visit the beach

Indeed lots of people like to visit the beaches. There's also the [Mémorial de Caen](http://normandy.memorial-caen.com/) and other museums.

> Not yet! Je suis ... on my third Duolingo lesson. :)

:-) So, have you figured out how to [pronounce my nickname](https://botbot.me/freenode/gratipay/2014-05-07/?msg=14339439&page=2#14339439) yet? :D

**Comment by whit537** [comment]
Not yet, still [working on my Rs](https://www.youtube.com/watch?v=MrjMJ_PAlB8). ;-)

**Comment by whit537** [comment]
@SimonSarazin has invited us (at https://github.com/liberapay/liberapay.com/issues/64#issuecomment-178644904) to Lille for "an event on the 'take what you want' idea, in preparation of an event in the north of France that we organise since 10 years (http://roumics.com)." From IRL conversation, it sounds like @JessWhit is interested in at least a day trip outside of Paris (train ride?). OuiShare Fest (#314) runs through the evening of May 20, and we fly out on the evening of the 24th, so we have May 21, 22, and 23 to work with.

@SimonSarazin Do those dates line up with what you are planning?

@Changaco Would Lille be a good place to meet up?

**Comment by SimonSarazin** [comment]
Hi @whit537 it's perfect for me at this time. I can host you in Lille with @JessWhit if needed and i'm quite sure (juste have to validate it) we could pay the Paris-Lille travel with our non profit organisation.

**Comment by SimonSarazin** [comment]
@Changaco it's also possible to host and pay the travel to Lille for you

**Comment by whit537** [comment]
@SimonSarazin Thanks for the generous offer! I'll discuss with @JessWhit and get back to you ...

**Comment by Changaco** [comment]
@whit537 Lille is as good a place as any I suppose, it's just a slightly longer trip for me.

@SimonSarazin Thanks, that could make it easier.

**Comment by whit537** [comment]
Let's go for it, @SimonSarazin! What date works best for you?

**Comment by SimonSarazin** [comment]
As you prefer, i have the days free at this moment :)

Le jeu. 11 févr. 2016 15:45, Chad Whitacre <notifications@github.com> a
écrit :

> Let's go for it, @SimonSarazin <https://github.com/SimonSarazin>! What
> date works best for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gratipay/inside.gratipay.com/issues/464#issuecomment-182893287>
> .
>
-- 

Simon Sarazin
0684284240

**Comment by whit537** [comment]
@SimonSarazin Let's go for ... Samedi! :fr: :smile:

**Comment by whit537** [comment]
/me forces himself to post that before checking that he got the word right. :)

**Comment by SimonSarazin** [comment]
@Changaco @whit537 Is it ok for you if we do the intervention on Liberapay and Gratipay on monday 23th afternoon in Lille ? We could present the two platform and discuss about the "take what you want" system
I think we could be around 50 people, maybe more, interested on the event.

Before that, we can do what you want on 21/22. Stay a little in Paris, visit Lille, go in Normandie, visit the north on the seaside (Boulogne sur mer, Cap Blanc nez)

It's ok to take in charge the train or car Paris - Lille and Lille - Paris (or other point of departure if it's Normandie for @Changaco ) with the non profit  [ANIS](http://www.anis.asso.fr/) organisation.

**Comment by whit537** [comment]
That should work for @JessWhit and I. We fly out on Tuesday, so we may or may not be able to stay in Lille on Monday night (I'll have to look up our flight time and see about travel to the airport). Perhaps we can come up to Lille on Sunday?

**Comment by SimonSarazin** [comment]
Yes of course on Sunday ! It depends on the airport, but from "Paris-Charles De Gaulle", it's less than one hour from Lille by train.

**Comment by whit537** [comment]
> Yes of course on Sunday !

Merci! Je vais dire avec @JessWhit et répondre. :-)

> It depends on the airport, but from "Paris-Charles De Gaulle", it's less than one hour from Lille by train.

Ah, nice! That's less time than I thought. Yay for high-speed rail! 🚄  We are flying from Charles De Gaulle, yes. Our flight is at 1:35 pm, but it looks like we should [have no trouble](http://www.thetrainline-europe.com/plan/lille-europe-to-aeroport-paris-charles-de-gaulle-tgv?departDate=2016-05-24&departTime=morning) getting to the airport on Tuesday morning.

Thanks again for the invitation, @SimonSarazin, and the offer to host us and cover our travel. We're getting excited for our trip! :-)

**Comment by Changaco** [comment]
@SimonSarazin Sorry I haven't answered sooner. I'm okay with going to Lille on Sunday and doing the thing on Monday. :-) I'll probably be coming from Caen, and if we coordinate I can meet @whit537 and @JessWhit in Paris and take the train to Lille with them.

**Comment by whit537** [comment]
> I can meet @whit537 and @JessWhit in Paris and take the train to Lille with them.

👍 

Let's arrange a meeting time and place before we fly. I'm planning to be offline while we're in France, though I'm at least hoping to have some kind of cell phone access.

**Comment by Changaco** [comment]
I was thinking of simply meeting you at the train station: I leave Caen at 8:54am, arrive in Paris-Gare-St-Lazare at 10:46, go straight to the other train station Paris-Gare-du-Nord where I meet you, we hop on the train to Lille which departs at 11:40 (TGV 7035), and at 12:48 we're there.

Would that work for you @SimonSarazin?

**Comment by SimonSarazin** [comment]
Perfect, i'll be there at 12h48 in Lille to receive you :-)

**Comment by Changaco** [comment]
Great, then I guess the only thing left to do is buy the tickets. :-)

**Comment by whit537** [comment]
@Changaco Jess and I are planning to go straight from Lille to the airport pretty early on Monday morning—I assume you won't be joining us for that leg of the journey (correct?). Therefore, I'm thinking that I will book 3 tickets up to Lille (we should book together so we can be seated together), and 2 back to the airport. I'll let you book your own return trip. Sound right?

P.S. My understanding (https://github.com/gratipay/inside.gratipay.com/issues/464#issuecomment-209516876) is that ANIS well be able to reimburse us.

**Comment by whit537** [comment]
> Monday morning

Scratch that: *Tuesday*

**Comment by whit537** [comment]
Old info [suggests](https://www.tripadvisor.com/ShowTopic-g187070-i12-k4087850-How_to_buy_cheaper_TGV_tickets-France.html) that buying [from SNCF](http://en.voyages-sncf.com/en/) is significantly cheaper than through the main US distributor, [Rail Europe](https://www.raileurope.com/), but for three seats on TGV 7035 I'm seeing €141 (~$163) vs. $174. Forex fees would bring close the gap, but then I also see this fine print: "All bookings are subject to a handling fee of $18 unless otherwise noted."

On SNCF's site I'm seeing options to select seats before landing on the final booking page:

![screen shot 2016-05-03 at 7 57 42 am](https://cloud.githubusercontent.com/assets/134455/14982491/cc3416f0-1104-11e6-8275-9f38ae39a9b5.png)

On Rail Europe I'm prompted to enter identity information, without seeing options to choose seats yet:

![screen shot 2016-05-03 at 7 59 51 am](https://cloud.githubusercontent.com/assets/134455/14982532/09e326f8-1105-11e6-8e09-99990eb7d48d.png)

**Comment by Changaco** [comment]
I haven't decided anything for the return trip yet, I think I'll keep my options open for now (I might carpool or take a bus if it's convenient).

We definitely should book the 3 tickets up to Lille together, but you don't have to be the one to do that, it would be simpler for me or @SimonSarazin to take care of it.

**Comment by whit537** [comment]
I like the "Print at Home" option I'm seeing from Rail Europe. Do I have that option with SCNF? The alternative seems to be to pick up in person, which we could presumably do when we land at CDG, though not having a smart card [may slow that down](http://parisbytrain.com/buying-tgv-tickets/).

**Comment by whit537** [comment]
> We definitely should book the 3 tickets up to Lille together, but you don't have to be the one to do that, it would be simpler for me or @SimonSarazin to take care of it.

Okay, I will leave that in your hands, then. :-)

Let me know if you need anything from me for that.

**Comment by whit537** [comment]
> I like the "Print at Home" option I'm seeing on Rail Europe. Do I have that option with SNCF?

Yes.

![screen shot 2016-05-03 at 8 44 24 am](https://cloud.githubusercontent.com/assets/134455/14983427/4def0bc2-110b-11e6-8ac4-7189334550f1.png)

**Comment by whit537** [comment]
... aaaaand this is where SNCF asks for identity information as well.

![screen shot 2016-05-03 at 8 47 46 am](https://cloud.githubusercontent.com/assets/134455/14983493/c71b1130-110b-11e6-981d-c673e1d68452.png)

**Comment by Changaco** [comment]
Yeah, I'm seeing the same. The identity information is required for e-tickets, without it you have to get the tickets at the train station before boarding.

**Comment by whit537** [comment]
👍 

![screen shot 2016-05-03 at 8 55 00 am](https://cloud.githubusercontent.com/assets/134455/14983711/e0ae3234-110c-11e6-9d55-b96d83c10b35.png)

**Comment by whit537** [comment]
> Yeah, I'm seeing the same. The identity information is required for e-tickets, without it you have to get the tickets at the train station before boarding.

I've sent you our identity info in private email.

**Comment by whit537** [comment]
@Changaco Careful, though! Don't do like I did and mix up the first and last name. 😞

**Comment by whit537** [comment]
![screen shot 2016-05-03 at 9 10 26 am](https://cloud.githubusercontent.com/assets/134455/14984077/eb650d18-110e-11e6-969b-2b8972c978d0.png)

**Comment by whit537** [comment]
Phew.

![screen shot 2016-05-03 at 9 11 27 am](https://cloud.githubusercontent.com/assets/134455/14984115/15e076c2-110f-11e6-854a-f32b93c44da8.png)

**Comment by Changaco** [comment]
> I've sent you our identity info in private email.

Received. :-) I assume the dates are correct and not a copy-paste fail.

I've reserved the tickets on https://www.captaintrain.com/, total is €169.5 for 1 Caen→Paris and 3 Paris→Lille. I'm working out payment with @SimonSarazin in private email.

**Comment by whit537** [comment]
> I assume the dates are correct and not a copy-paste fail.

Yes! They are correct. :-)

**Comment by Changaco** [comment]
I've paid for the tickets and sent the bill to @SimonSarazin for reimbursement.

The e-tickets have arrived in my inbox and I've relayed the relevant ones to @whit537. I can print them along with mine if you want.

> Yes! They are correct. :-)

:-)

**Comment by whit537** [comment]
> The e-tickets have arrived in my inbox and I've relayed the relevant ones to @whit537.

Received, thank you! 💃

**Comment by Changaco** [comment]
I've received €169.5 from ANIS by bank transfer as reimbursement for the tickets.

**Comment by whit537** [comment]
We met, and we have a picture to prove it! I need to get it off @JessLloydWhit's phone and send it to @Changaco to filter ... ;-)

**Comment by whit537** [comment]
Finally got the pictures off @JessWhit's phone and I've emailed them to @Changaco for filtering ...

**Comment by whit537** [comment]
https://twitter.com/CatalystMEL/status/734655015114182657 😳

**Comment by Changaco** [comment]
(I did receive the pictures, they're still sitting in my inbox.)

**Comment by whit537** [comment]
@Changaco I think we need a (filtered) picture here before we can close. I realize it took me a while to get the pictures _into_ your inbox ... ;-)

**Comment by Changaco** [comment]
I finally passed one of the photos through a few filters, here's the result:

![img_0189-mod](https://cloud.githubusercontent.com/assets/1581590/17838921/7a8c043a-67d9-11e6-9d32-01fde9c6c707.jpg)

I'll let you close the issue Chad. :-)

**Comment by whit537** [comment]
That's not very filtered, @Changaco! :-P

I forget whether this was before or after I spilled the hot tea into your and Carole's laps. 🍵  😢 

Memorable, anyway. Cheers, @Changaco! 💃

**Comment by Changaco** [comment]
It's actually significantly filtered and downsized compared to the original, but the black contours make our faces look quite real. :-)

I'm pretty sure it was well after you spilled Carole's tea. ;-)
