### ISSUE TITLE
delegate payday

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#467]
@clone1018 @rohitpaulk You two want to start running payday alternating weeks? A cord of three strands is not easily broken. I'd love to leave my computron at home during #314.

**Comment by rohitpaulk** [comment]
:+1: Let's do a trial run today? I'll be able to start by around 8PM IST..

**Comment by whit537** [comment]
> I'll be able to start by around 8PM IST..

Yesssssssss! [Looks like](http://www.timeanddate.com/worldclock/converted.html?iso=20160114T20&p1=54&p2=418) that is 9:30 am my time ... about 30 minutes. I'll start going through the team review queue now ...

**Comment by whit537** [comment]
> alternating weeks

Alternating months might be better, less guessing about "am I on this week?"

**Comment by clone1018** [comment]
:+1: for me too, if you need the additional support I'm always up for it.

**Comment by whit537** [comment]
!m @clone1018 

What kind of schedule do you think we should adopt?

**Comment by clone1018** [comment]
Alternating months sounds fine to me, gives everyone a break. Might have a knowledge gap when you come back after 2 months but I guess that's what docs are for

**Comment by whit537** [comment]
We could try week by week, too. The only thing is we don't want to screw up and have someone forget it's their week, but I guess with three of us to remind each other and pinch-hit if necessary it's maybe not a big deal.

**Comment by whit537** [comment]
Since @rohitpaulk didn't quite get to finish today due to PayPal permissions (#468 → #469) it seems like he should have another shot next week. I guess let's try month by month and see how that goes, eh?

January—@rohitpaulk
February—@clone1018
March—@whit537
April—@rohitpaulk
May—@clone1018
June—@whit537

**Comment by clone1018** [comment]
What time do we want to standardize on? Making calendar reminders hah

**Comment by whit537** [comment]
@clone1018 We haven't observed a standard time in the past. How about ~1430 UTC like we did today? That should be 8 pm @rohitpaulk's time, 9:30 am mine, and 8:30 am yours. Also: it seems like a good idea to have a second person on hand in case issues come up. Always better to have two eyes/hands in a crisis, ya? That will also help with cross-training.

**Comment by whit537** [comment]
I've updated https://github.com/gratipay/inside.gratipay.com/issues/467#issuecomment-171721394 to include a concept of pilots and copilots.

**Comment by clone1018** [comment]
I can't make 8:30 my time, I'm still commuting. 9:30-10:30 would work unless something crazy happens at work.

**Comment by whit537** [comment]
Well, it looks like @rohitpaulk is your copilot, so I guess he's the one you have to coordinate with. ;-)

**Comment by whit537** [comment]
@rohitpaulk You on payday today?

**Comment by rohitpaulk** [comment]
Yep, I'll be here in 15-20 mins

**Comment by whit537** [comment]
Cool. :)

**Comment by rohitpaulk** [comment]
> I can't make 8:30 my time, I'm still commuting. 9:30-10:30 would work unless something crazy happens at work.

9:30 - 10:30 your time works for me, @clone1018

**Comment by whit537** [comment]
> 9:30 - 10:30 your time works for me, @clone1018

@rohitpaulk So we're on the same page: that matters next month, right? This month you are the [pilot](https://github.com/gratipay/inside.gratipay.com/issues/467#issuecomment-171721394). :-)

**Comment by rohitpaulk** [comment]
Yep, correct

**Comment by whit537** [comment]
Re: https://github.com/gratipay/inside.gratipay.com/issues/477#issuecomment-173593193 ...

> I see a suspicious user, and I don't have access to the violations repo...

@rohitpaulk I've made a new "Payday Runners" team with you, @clone1018, and I on it, with read/write access to violations as well as logs.

**Comment by whit537** [comment]
@rohitpaulk Once we're done with #477, let's make sure you have DigitalOcean access to use for future paydays.

**Comment by whit537** [comment]
@rohitpaulk We don't use that cursor again until `update_balances`, right after the log line we saw emitted. The calls to `capture_card_holds` use a different db connection (because we want the balances to be updated immediately after a successful charge), and the fact that we *did* see "Updating balances" suggests to me that we successfully charged everyone.

**Comment by whit537** [comment]
> We don't use that cursor again

I *thought* I'd already written this once. :-)

Deleting in favor of https://github.com/gratipay/inside.gratipay.com/issues/477#issuecomment-173632418 ...

**Comment by whit537** [comment]
Looks on #485 like @rohitpaulk has DO access, so we're set on that.

#485 was the last payday of January. Next month, @clone1018 is the pilot and @rohitpaulk is the copilot. Which means that, in the greater interest of Gratipay, I should take the day off next Thursday, February 4. Offline all day. Inaccessible. Checked out. In the woods.

Are we ready for this, @clone1018 @rohitpaulk!? :open_mouth:

**Comment by clone1018** [comment]
I'm ready! I'm going to refresh myself on all of the documentation this week, will you be available on Thursday @rohitpaulk ? I'm planning on doing it around 10AM CST

**Comment by rohitpaulk** [comment]
That's 9:30 PM my time - yes, I should be available :) :airplane:

**Comment by clone1018** [comment]
Delegation successful? We have a bus factor of 3 now for basic payday

**Comment by whit537** [comment]
:+1: 

I guess @rohitpaulk can close the ticket if he's ready? :)

**Comment by rohitpaulk** [comment]
:beers:

**Comment by whit537** [comment]
:beers:

**Comment by clone1018** [comment]
I liked running payday but I can't wait till @whit537 takes over next week!

**Comment by whit537** [comment]
With #628 we are *really* closed here. :-)

!m @clone1018 @rohitpaulk
