### ISSUE TITLE
get @rohitpaulk into PayPal

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#469]
Reticketed from #468.

**Comment by rohitpaulk** [comment]
Talked to them on the phone - They say that it isn't possible to login with just a username, and that it should be an email (the username you sent me in the mail wasn't an email, just a plain username). 

I told her that I'm pretty sure that it worked for my colleague in the US, but I'll check with him to make sure. 

Did you use my email address when linking the user, @whit537? Any other info that I can provide them to identify the user you created?

**Comment by rohitpaulk** [comment]
I tried using a VPN, I get a slightly different error message - 

The indian version said "Please check your entries and try again"
The US version said "Some of your info isn't correct. Please try again."

**Comment by whit537** [comment]
@rohitpaulk I am able to login using just the username (not an email address) ... but! I just revisited the email I sent you, and I got the password wrong in there! Check your email for the correct password.  Sorry! D:

**Comment by rohitpaulk** [comment]
> and I got the password wrong in there!

DUDE :sweat: 

I can login fine without the VPN, looks like we're good for today! :)

**Comment by whit537** [comment]
I'm so sorry for the runaround! D:

All's well that ends well? :flushed:

**Comment by rohitpaulk** [comment]
:tropical_drink:
