### ISSUE TITLE
Review and document backup policies

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#470]
Reticketed from #468.

My current practice is to store the backups taken during payday on an external hard drive.

What else do we have going on? What should we do?

**Comment by whit537** [comment]
We are getting [daily backups](https://postgres.heroku.com/databases/gratipay-heroku-postgresql-maroon#snapshots) in Heroku ([docs](https://devcenter.heroku.com/articles/heroku-postgres-backups)).

```
$ heroku pg:backups schedules
=== Backup Schedules
DATABASE_URL: daily at 4:00 (UTC)
$
```

**Comment by whit537** [comment]
> **[Morgan Stanley To Pay $1M SEC Fine For Security Lapse](http://www.darkreading.com/operations/morgan-stanley-to-pay-$1-million-sec-fine-for-security-lapse/d/d-id/1325851)**: A Morgan Stanley employee copied customer data to his personal laptop, which was subsequently hacked, resulting in the SEC fine for failing to protect customer data.

https://summitroute.com/blog/2016/06/12/downclimb/

**Comment by kaguillera** [comment]
😱

**Comment by whit537** [comment]
Folding in from #932:

>We take a nightly backup at Heroku. I do think we should have an offsite backup, at least at a different provider. I don't think we want backups on three different personal laptops, though. That is sloppy.
>
>What should we do, @clone1018 @rohitpaulk?

----------------------

>I think me and @rohitpaulk 's backups are on DigitalOcean (that's where I run payday). I'm used to storing backups on S3 with the file encrypted. Not sure if that would be easy for us or not

-----------------------

> Heroku wraps AWS so that wouldn't do much for us. DO could work but we should be more intentional about it.

**Comment by whit537** [comment]
[Slack](http://gratipay.slackarchive.io/gratipay/-/1480708543.000914/1480710694.001015/1480709808000999/) re: db size after removing readmes: still big, but ...

**Comment by whit537** [comment]
"[Creating Disaster Recovery backups](https://summitroute.com/blog/2016/12/25/creating_disaster_recovery_backups/)"
