### ISSUE TITLE
reconnect with Nadia Eghbal

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#471]
Reticketed from #405.

Nadia and I did a [call](https://www.youtube.com/watch?v=tNhncmK5r2U) together a little over a year ago. With "[How I Stumbled Upon The Internet’s Biggest Blind Spot](https://medium.com/@nayafia/how-i-stumbled-upon-the-internet-s-biggest-blind-spot-b9aa23618c58)," it seems like it might be a good time to reconnect. :-)

@nayafia Up for another Hangout to catch up? :)

**Comment by whit537** [comment]
(I've also sent a private email.)

**Comment by whit537** [comment]
Oops! @collaborativefund.com bounced. ;-)

To: [gmail]
Subject: reconnect re: funding open-source?

> Greetings! Chad here from Gratipay. We spoke a little over a year ago (here's the [video](https://www.youtube.com/watch?v=tNhncmK5r2U) ;). I just read "[How I Stumbled Upon The Internet’s Biggest Blind Spot](https://medium.com/@nayafia/how-i-stumbled-upon-the-internet-s-biggest-blind-spot-b9aa23618c58)"—looks like you haven't stopped thinking about alternative structures for funding the most valuable things on the Internet! :-)
>
Over here we've been thinking a lot about capital as well, particularly how it might fit into the "take-what-you-want" model that we're pioneering at Gratipay.
>
Would you be up for another Hangout to catch up? :)

**Comment by techtonik** [comment]
@whit537 can we make a query to find the most funded open source projects (in terms of people) before Gratipocalype to augment @nayafia spreadsheet? If you can send me the dump, I can do this.

**Comment by nayafia** [comment]
@whit537 Hey there! Yes, happy to catch up. As you can see, I never stopped thinking about our convo last year. :) How's next Wed 1/27 or Thurs 1/28, 4p PT?

@techtonik that would be very welcomed on the spreadsheet, thanks!

**Comment by whit537** [comment]
@nayafia Yay! :D Let's go for Thursday 1/28 at 4 pm your time. I'll email you a join link then. Looking forward to it! :-)

@techtonik I'm not ready to send you a production data dump. What are the metrics you want to run?

P.S. For the viewers at home, here's the [spreadsheet](https://docs.google.com/spreadsheets/d/11wXpAPkL3sfV7JWT6xD72xViUTfp7KUhjK3NxQLbeno/edit).

**Comment by whit537** [comment]
Follow-ups from @nayafia:

"[Open source infrastructure: the Q&A](https://medium.com/@nayafia/open-source-infrastructure-the-q-a-a44615861944)"

"[Why can’t we just charge for open source infrastructure?](https://medium.com/@nayafia/why-can-t-we-just-charge-for-open-source-infrastructure-371037965b45)"

**Comment by techtonik** [comment]
@whit537 in pseudo SQL - select project.name, count(person.id) as people from (projects vs person on person.donated_to) where person.donated > 0 sort on people limit 100

**Comment by nayafia** [comment]
great, speak then!

p.s. just moved to http://fundingoss.com for future project additions!

**Comment by techtonik** [comment]
@whit537 I may be able to build the exact query this weekend. Just need to find out the date with correct schema.

**Comment by techtonik** [comment]
Added Gratipay to http://fundingoss.com/69/ (spreadsheet replacement)

**Comment by whit537** [comment]
!m @techtonik 

Still need to get you that query ...

**Comment by techtonik** [comment]
@whit537 yes, I couldn't get around to it too..

**Comment by whit537** [comment]
@techtonik Okay, ball is in your court to get me the query you want to run.

**Comment by techtonik** [comment]
Yep. Do you use any good DB inspection tools to start with? It might be faster than digging SQL dump once I get it.

**Comment by whit537** [comment]
@techtonik I generally just use [`psql`](http://www.postgresql.org/docs/current/static/app-psql.html).

**Comment by whit537** [comment]
@nayafia We still on for a call at 4pm (your time) today?

**Comment by nayafia** [comment]
yep!

**Comment by whit537** [comment]
Awesome! I'll email you a link to join the Hangout when the time comes, and I'll post a view link here. Talk soon! :-)

**Comment by whit537** [comment]
View link: https://www.youtube.com/watch?v=CXPDtPhnhus.

**Comment by whit537** [comment]
Okay! Good call! Thank you, @nayafia! Please do consider Gratipay a gift for your quest, and if you ever want to check in on us or ping us about anything, feel free to drop in on [the Radar](http://inside.gratipay.com/howto/sweep-the-radar). In the mean time, keep up the great work! :-)

**Comment by nayafia** [comment]
woot! so fun! hope to chat again soon. likewise keep up the good fight 👊
