### ISSUE TITLE
use a custom domain with Medium

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#475]
Medium added a custom domain [feature](https://medium.com/the-story/move-your-domain-to-medium-21fd74abbbe6) a while back. I think we should avoid subdomains of `gratipay.com` as a rule, because subdomains increase our security exposure. How about something like `gratipay.news`?

The purpose would be to brand our blog more.

**Comment by whit537** [comment]
Kinda hard to believe `.blog` hasn't launched yet.

**Comment by whit537** [comment]
Maybe we should just wait for that?

**Comment by rohitpaulk** [comment]
Is blog.gratipay.com really a security threat?

**Comment by whit537** [comment]
@rohitpaulk "Threat" is probably a strong word, but it's a consideration, yes. For example. it complicates [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security).

**Comment by whit537** [comment]
I bought `gratipay.news` and have emailed Medium to configure it, per [their instructions](https://medium.com/the-story/move-your-domain-to-medium-21fd74abbbe6).

https://gratipay.freshdesk.com/helpdesk/tickets/4271

**Comment by whit537** [comment]
DNS configured. Apparently it should start resolving properly within 24 hours:

https://medium.com/gratipay-blog
https://gratipay.news/

**Comment by whit537** [comment]
> Any update on our custom domain request? We've set up DNS as instructed, but we're still getting 404 and broken SSL:
>
https://gratipay.news/
>
Thanks! :-)

**Comment by whit537** [comment]
> Your records look good. We need to issue the cert for you. It's done automatically, usually within a day. Looking into it.

----------

> Thanks [], Let me know if you need anything from this end ...

**Comment by whit537** [comment]
Still not working.

**Comment by whit537** [comment]
https://gratipay.news/

:dancer:
