### ISSUE TITLE
Grant @rohitpaulk access to Transifex

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/inside.gratipay.com#476]
As of now - whenever I deploy code, I manually comment out the lines in `release.sh` that deal with translations.

**Comment by whit537** [comment]
Gosh, that's no good! Let's see here ...

**Comment by whit537** [comment]
@rohitpaulk Do you have access via LastPass?

**Comment by rohitpaulk** [comment]
No, I don't. (I haven't been added to LastPass)

**Comment by whit537** [comment]
@rohitpaulk I've sent you an invite to LastPass. See if you can use that to access Transifex, ya?

**Comment by whit537** [comment]
@rohitpaulk Did you get what you need herE?

**Comment by rohitpaulk** [comment]
Yep
