### ISSUE TITLE
partner with Atmosphere.js

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#483]
Reticketed from https://github.com/gratipay/inside.gratipay.com/issues/441#issuecomment-175746259.

> Atmospherejs.com has a similar problem: https://atmospherejs.com/i/publishing
> 
> > Why is Gratipay important? Well, consider the dreaded Dead Package Syndrome :-). Someone releases a cool and useful package as a fun creative effort. But months later, it no longer works with the latest version of Meteor... pull requests go unanswered... issues pile up. Creating a package is rewarding, but ongoing maintenance can be a lot of work (and often, not nearly as much fun :)
> > 
> > Happen to have more money than time right now? Fund the efforts important to you, and avoid having packages you rely on slowly die. Or, happen to have more time than money at the moment? Become a Gratipay recipient and get support for the community work you put in. 
> > @awwx, Andrew Wilcox

**Comment by whit537** [comment]
They are sending people to the old communities page for Meteor.

@mattbk Wanna reach out and see if they want to talk about a partnership a la Chocolatey (#441)?

**Comment by nobodxbodon** [comment]
Re-ticketed to https://github.com/gratipay/inside.gratipay.com/issues/982 for further discussion and planning. After deciding on concrete implementation plan and dev work starts, this will be reopened for tracking purpose.
