### ISSUE TITLE
Revise "Train new contributors" page or make a response

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#484]
Looks like "Train new contributors" needs an update" now that we don't have anyone in chat http://inside.gratipay.com/howto/train-new-contributors

This page also got me "inspired" to spend few hours trying to get my thoughts together, so I wrote my response on Gratipocalypse. It is a first draft that I reread only once, and I thought that maybe it can be an official statement that brings our public voice back on Twitter - explaining that happened using one more angle from inside. But now it is late and it turns out to be some kind of strange text and I don't even know where to publish it. Perhaps you could review it and fix some facts so we can publish it? I still don't know what the purpose of this publication should be, but for me it is important to bring the facts in order so that people could learn from this somehow and make their own opinion. http://piratepad.net/gratipocalypse

**Comment by mattbk** [comment]
Is this a lot like https://github.com/gratipay/inside.gratipay.com/issues/319?

**Comment by techtonik** [comment]
Yes, but #319 is already 57 pages. =/

**Comment by mattbk** [comment]
Specifically https://github.com/gratipay/inside.gratipay.com/issues/319#issuecomment-172876404?

> explaining that happened using one more angle from inside

I like this. Gratipay at the Medium blog isn't defined as a person; rather it sounds like "the organization" is speaking rather than an individual. I think multiple viewpoints from within Gratipay are totally valid to have available.

**Comment by whit537** [comment]
> Trapped in the middle between parties we could not do anything except feeling how buckets of perfectly aimed :hankey: land on through Twitter on our IRC channel, and the sticky brown stains start to gather over you face and back and then get more weight and slip under you neck.

A sad tale, @techtonik. :disappointed: 

I've removed the "Train New Contributors" page in #496.
