### ISSUE TITLE
onboard @deivid-rodriguez

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#489]
Reticketed from https://github.com/gratipay/gratipay.com/pull/3911. :dancer:

**Comment by whit537** [comment]
> I also wanted to ask for some beginner pending tasks for someone who knows nothing about coding in python, but wants to learn. :)

I believe @rohitpaulk has been inviting folks to chip away at  https://github.com/gratipay/gratipay.com/issues/835 as a way to get your feet wet. Does that sound right, @rohitpaulk?

**Comment by whit537** [comment]
@aandis also recently went through onboarding, so maybe he can point you in a good direction as well? :-)

**Comment by whit537** [comment]
@deivid-rodriguez May I add you as a collaborator on GitHub? That way you can work on branches in the main repo (our preferred method) instead of on a fork.

**Comment by deivid-rodriguez** [comment]
Of course!

**Comment by whit537** [comment]
Invite sent! :)

**Comment by deivid-rodriguez** [comment]
Invite accepted!! ;)

**Comment by whit537** [comment]
!m @deivid-rodriguez :dancer: 

^^^ Our goofy way of saying "[You're doing good work!](http://motivate.im/)" :-)

**Comment by whit537** [comment]
If https://github.com/gratipay/gratipay.com/issues/3684 is too overwhelming then maybe one of the subtasks on https://github.com/gratipay/gratipay.com/issues/835 would make more sense for a first PR. See @aandis's recent work linked from the description there for examples of what is involved.

**Comment by whit537** [comment]
> first PR

Second! Second. :)

gratipay/gratipay.com#3911

**Comment by deivid-rodriguez** [comment]
Ok, I'll have a look at both and choose the one I like more!

**Comment by aandis** [comment]
!m @deivid-rodriguez  In case you decide to go with [#835](https://github.com/gratipay/gratipay.com/issues/835) have a look at https://github.com/gratipay/gratipay.com/pull/3893#issuecomment-172375788 to get a good idea about what is involved. :)

**Comment by deivid-rodriguez** [comment]
Thank you @aandis ! #835 seems like a good way to meet the data model...

**Comment by deivid-rodriguez** [comment]
Hei, I changed my mind regarding contributing... Feel free to remove me from the organization since I won't be doing any work here in the near future.

**Comment by whit537** [comment]
Okay, thanks for the heads-up. I've removed you from the org.

Best wishes, @deivid-rodriguez! Come back any time! :-)

**Comment by deivid-rodriguez** [comment]
Thanks @whit537 !
