### ISSUE TITLE
Get Luke into Paypal

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/inside.gratipay.com#490]
Reticketed from https://github.com/gratipay/inside.gratipay.com/issues/488#issuecomment-180011749

**Comment by whit537** [comment]
Password reset and emailed to @clone1018.

**Comment by whit537** [comment]
@clone1018 [Looks like](https://github.com/gratipay/inside.gratipay.com/issues/488#issuecomment-180090359) you're good here, ya? Closing.

**Comment by clone1018** [comment]
Yup, all good
