### ISSUE TITLE
list public disclosures

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#512]
We should list all of our public security disclosures. Mail to support@hackerone:

Subject: listing of our public disclosures?

> Greetings!
>
We'd like to provide a listing of our public disclosures. Is this something HackerOne supports directly? If not, do you have an API we can use?
>
Thanks!

https://gratipay.freshdesk.com/helpdesk/tickets/4125

**Comment by TheHmadQureshi** [comment]
Make sure to discuss here everything before going live. We are still getting a lot of reports our first priority is to clean or triaged reports for now then we can move onto this list.

**Comment by whit537** [comment]
Agreed.

**Comment by TheHmadQureshi** [comment]
That way we will get NEW reports instead of getting duplicates.

**Comment by whit537** [comment]
Yeah. :confounded:

**Comment by TheHmadQureshi** [comment]
Gratipay security team is on Fire!!!  😎

**Comment by whit537** [comment]
:fire: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; :fire_engine: 

> We don't have a listing as of now. That's something in discussion. 
But would this work for you in the meantime ? https://hackerone.com/gratipay/reports/public
This give you a list of public disclosures from GratiPay. The api is very minimal at this point.

----------

> Nice! That endpoint should do the trick ...
>
Any chance we could get aggregate bounty awarded as an additional key? :-)

**Comment by whit537** [comment]
> We don't support that right now. But I will file a task internally to support bounty awarded amount in the endpoint. I will let you know once its available in the API.

-----------

> Thanks, []! :-)
