### ISSUE TITLE
fill @rummik's spot on the Safety Team

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#520]
@rummik has stepped down from the Safety Team, due to competing time commitments. We should find someone to take her place.

Also as part of this, we should formalize a process for filling spots on the Safety Team.

**Comment by whit537** [comment]
I've removed @rummik from @gratipay/safety. P.S. She and I met for tea/coffee yesterday morning and had a nice time catching up. You're welcome back any time, @rummik! :-)

I've been talking to a friend about possibly joining us to fill the empty spot. They're local here in Ambridge so, @dmk246: we could meet with them in person. Maybe we can get together some evening at my place and we can skype @chrisdev in?

**Comment by whit537** [comment]
In terms of process, I'm expecting to appoint someone with the existing Safety Team's approval.

**Comment by rummik** [comment]
@whit537 Thanks :)  I feel like I should have said something, since I kind of fell out of the loop a long time ago. <.<;

It was nice to catch up though, and gave me a good break from my usual Monday morning.
