### ISSUE TITLE
clean up Freshdesk a bit more

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#521]
Following on from https://github.com/gratipay/inside.gratipay.com/issues/513#issuecomment-188466295 ...

I've had recent contact with @chrisdev and @dmk246, they're still active, as are @clone1018 and @rohitpaulk.

@rummik is definitely _in_active now (#520).

For @captn3m0 @ericmeltzer @greggles ... could I get a ping from you if you want to keep your Gratipay Freshdesk account active? Otherwise I'll deactivate it for the time being. :-)

**Comment by captn3m0** [comment]
You can deactivate my account for now.

**Comment by whit537** [comment]
Cool, thanks @captn3m0. :-)

**Comment by whit537** [comment]
This got handled somewhere along the line.
