### ISSUE TITLE
set up Freshdesk-GitHub integration

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#525]
Wanna look into this, @mattbk? On the surface it seems right up our alley.

> Track bugs, fix issues and make customers happy in one fell swoop with the Freshdesk-GitHub integration

http://blog.freshdesk.com/github-integration/

**Comment by mattbk** [comment]
I can look into it.

**Comment by whit537** [comment]
!m @mattbk

**Comment by mattbk** [comment]
Looks like I need more access in Freshdesk to set it up. I don't have an "Admin" menu.
https://support.freshdesk.com/support/solutions/articles/214680-integration-with-github

**Comment by mattbk** [comment]
It also looks like it syncs FD messages right into GitHub. If so, this is something that customers will need to be aware of when contacting support so they can opt out.

**Comment by whit537** [comment]
Hrm ... maybe not what we want after all, then.

> Every reply or note on your Freshdesk tickets gets reflected as comments in the linked GitHub issue and vice versa.

Eep! We don''t want that. We want to keep GitHub public, and Freshdesk private.

Oh well.

**Comment by mattbk** [comment]
You can turn that off and only sync one way if you want.

**Comment by whit537** [comment]
I don't think we want that, either. The only way we could go is from GitHub (public) to Freshdesk (private), and we don't want one Freshdesk ticket for every GitHub ticket.

**Comment by mattbk** [comment]
We wouldn't get that. You link a FD ticket to a GH issue or not, and then you have an option to turn on flow back and forth. Even if not, it looks like you see GH issue status in FD.

It would be helpful if there were a "notify" option to go from FD to GH, just to easily indicate a +1.

**Comment by mattbk** [comment]
Hard to say whether this is simpler than what we do now, though. You need GH open in order to search for issues anyway.
