### ISSUE TITLE
drop star priority labels

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#527]
Anyone care about those still? They're cute, but it seems like we're now prioritizing by gathering tickets into milestones.

https://github.com/gratipay/gratipay.com/labels/★☆☆
https://github.com/gratipay/gratipay.com/labels/★★☆
https://github.com/gratipay/gratipay.com/labels/★★★

**Comment by rohitpaulk** [comment]
They still make sense within a milestone, don't they? :)

**Comment by whit537** [comment]
Yeah, fair enough. I've removed the ★☆☆ and ★★☆ labels from tickets that aren't also on a milestone.  I couldn't quite bring myself to lose the ★★★ queue, since those are presumably important enough to address more promptly.
