### ISSUE TITLE
phase out tip migration

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#536]
After the Gratipocalypse we added the ability to migrate tips from a ~user to a Team, and we've been doing that every week during payday for all newly approved Teams that week. At https://github.com/gratipay/inside.gratipay.com/issues/526#issuecomment-191952642 I started asking how long we're going to continue this practice, and at https://github.com/gratipay/inside.gratipay.com/issues/535#issuecomment-194914382 this came to a head because I accidentally migrated my own ~whit537 tips to the new Aspen Team.

Clearly it doesn't make sense to be migrating tips 10 years from now. We're at 10 months out, and even a year seems to me to be at the upper edge of what makes sense. We remind people what we're charging them for every week. They forget two months out, let alone a year. @kaguillera's suggestion is that we stop migrating tips automatically, yet leave the option available on a case-by-case basis for another year (through April, 2017).

Eh?

**Comment by mattbk** [comment]
In light of https://github.com/gratipay/inside.gratipay.com/issues/836#issuecomment-258726644, let's cut off tip migration.

> I think we maybe need to let go of the past. Let go of the Gittip bump. Start fresh. Beginner's mind. Think of ourselves as pre-launch.

I was tempted to include "...but let's see how much money is being left on the table by doing this," but that's the wrong mindset again. Gittip grew once, Gratipay can grow the same way.

**Comment by whit537** [comment]
Counterargument would be this recent tip migration (first/biggest in a while?): https://github.com/gratipay/inside.gratipay.com/issues/879#issuecomment-258269570.

**Comment by whit537** [comment]
But actually I agree with you. Time to cut with the past.

**Comment by whit537** [comment]
What do we need to do to land this? What docs do we need to change? Any site copy?

**Comment by whit537** [comment]
> or by applying for [a new Gratipay Team](https://gratipay.com/new) (in which case we’ll also migrate your old tips into payments to your Team).

https://gratipay.news/1-0-money-available-indefinitely-39c07bd031b

Seems like good timing with the move from Teams to Projects to get this done. Added to the "[Relax Open Work Requirement](https://github.com/orgs/gratipay/projects/5?fullscreen=true)" project.

**Comment by whit537** [comment]
Where else do we promise that we'll migrate payments?

**Comment by whit537** [comment]
On the [team application](https://github.com/gratipay/gratipay.com/blob/2014/www/new.spt#L113-L126). I've added removal of that to the task list on https://github.com/gratipay/gratipay.com/pull/4130.

**Comment by whit537** [comment]
Other than that I think it's just the payday howto (it's already off the payday ticket).

**Comment by whit537** [comment]
Moving to PR in #935 ...
