### ISSUE TITLE
Guidelines and rules for communication

### ISSUE THREAD

**Issue by duckinator** [gratipay/inside.gratipay.com#54]
As  @whit537 mentioned in https://github.com/gittip/building.gittip.com/issues/49#issuecomment-43395707, there are four main areas where Gittip communicates with others:

* Conversations we have with each other in the course of building Gittip.
*  Conversations we have _about_ our users.
* Conversations we have _with_ our users.
* Conversations we have with our business partners.

We should come up with a set of guidelines and rules, including whether to use public or private communication, for each of these situations.

**Comment by whit537** [comment]
Reviewing old tickets. I think we're actually pretty close to having implemented this ticket. Current status:

 - **Conversations with each other**: we're basically all-GitHub right now, with periodic-but-extra Hangouts for Aspen (and we've been trying to cross-link the calls from GitHub where it matters). I guess some face-to-face as well. All binding decisions happen on GitHub, though. We could make that explicit somewhere.
 - **Conversations <i>about</i> users**: these happen in private notes on Freshdesk. Works great. Documented on "[How to Support Users](http://inside.gratipay.com/howto/support-users)" (under "Protecting User Privacy."
 - **Conversations <i>with</i> users**: publicly on GitHub, or privately on email (Freshdesk). We've got a consent policy in place on "[How to Support Users](http://inside.gratipay.com/howto/support-users)" (under "Protecting User Privacy." We are doing very little on marketing 
 - **Conversations with business partners**: this is being worked out on #411.

Here's what I'm seeing to close this ticket:

 - [ ] Say explicitly somewhere that most decisions, and certainly important community-defining ones, are expected to happen in public on GitHub (though maybe eventually Loomio, too? #420), except for sensitive legal, safety, and security issues, which happen in private.
 - [ ] Land the consent with third parties doc (#411).
