### ISSUE TITLE
speak at Code & Supply

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#556]
Picking up from #543 and #552 ...

http://www.codeandsupply.co/speakers/

**Comment by whit537** [comment]
Submitted!

**Comment by whit537** [comment]
> [], let's schedule this one for late July

----------

> Awesome, thanks [@justinxreese]!
>
[]: the week of the 24th would be ideal for me. How's that look? :-)

**Comment by whit537** [comment]
http://www.meetup.com/Pittsburgh-Code-Supply/events/230151701/ :D

> "This talk will be fascinating to anyone interested in the question of money and open-source" http://www.meetup.com/Pittsburgh-Code-Supply/events/230151701/ Summer @codeandsupply

https://twitter.com/Gratipay/status/717450640956514305

**Comment by whit537** [comment]
👍

It was [streamed](https://www.youtube.com/watch?v=0v-Qe7CsUxA) but apparently not archived? I'll drop a link if I get one from @justinxreese.

**Comment by justinxreese** [comment]
Archive should be up now. Here are the notes I took. Could benefit from
slides that visualize large concepts and keep you on track. Also think the
problem statement could be more effectively defined as splitting up money
on a team where there's no boss.

**Comment by whit537** [comment]
@justinxreese Still not seeing the archive at https://www.youtube.com/watch?v=0v-Qe7CsUxA, but I'm not too worried about that since I didn't even know we were streaming until late yesterday. :)

Were your notes in an email attachment? If so I think GitHub stripped it. :( Mind resending to chad@zetaweb.com?

**Comment by rohitpaulk** [comment]
Here it is: https://www.youtube.com/watch?v=ZCyfQUupPTM

**Comment by whit537** [comment]
Thanks @rohitpaulk! Long and rambling, but I think the basic outline of a good talk is in there somewhere. Here's to #534! :-)
