### ISSUE TITLE
go to PyCon 2016!

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#557]
I'm not going to make it this year, because it's too close to OuiShare Fest (#314).

@chrisdev @citruspi Will you be there? Wanna rep Gratipay again? :-)

**Comment by whit537** [comment]
https://us.pycon.org/2016/

**Comment by whit537** [comment]
We might be too late for a booth, not sure ...

**Comment by kzisme** [comment]
I was considering trying to make it out for the first time... Not sure yet

**Comment by whit537** [comment]
@kzisme Oooh, nice! Keep us posted, we can at least send stickers and pennies with you. :-)

**Comment by citruspi** [comment]
@whit537 Unfortunately, I don't think I'll be able to make it. I'd love to, but PyCon sold out before I got to register. I was literally a few minutes late. :cry:

**Comment by whit537** [comment]
Oh no! :scream:

**Comment by chrisdev** [comment]
@citruspi :sob:

**Comment by chrisdev** [comment]
@whit537 is not to late to do the booth thing? I'll be there so I can help out

**Comment by whit537** [comment]
@chrisdev Dunno. I say go for it! :-) I can punch a bunch of pennies again if you like ...

**Comment by whit537** [comment]
@chrisdev Did you make it to PyCon? How was it? Any discussions of Gratipay?
