### ISSUE TITLE
publish something about our security program

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#560]
Reticketed from https://github.com/gratipay/inside.gratipay.com/issues/558#issuecomment-206426101.

We've put a lot of effort over the past few months into setting up our HackerOne program. Let's blog about it!

**Draft 1**: "[**An Open Vulnerability Program: Announcing Gratipay on HackerOne**](https://medium.com/@Gratipay/c864d03d6f60)"

**Comment by whit537** [comment]
Draft 1: "[An Open Vulnerability Program: Announcing Gratipay on HackerOne](https://medium.com/@Gratipay/c864d03d6f60)"

**Comment by TheHmadQureshi** [comment]
Awesome! 👍

**Comment by whit537** [comment]
I've been tinkering with Draft 1 rather than making a new draft.

**Comment by whit537** [comment]
Is it too bold to title this, "[A New Standard in Transparent Security](https://medium.com/@Gratipay/c864d03d6f60)"?

**Comment by whit537** [comment]
Maybe just "Transparent Security"

**Comment by whit537** [comment]
Any objections to publishing?

"[Transparent Security: Introducing Gratipay's Program on HackerOne](https://medium.com/@Gratipay/c864d03d6f60)"

**Comment by whit537** [comment]
Alright, here we go ...

**Comment by whit537** [comment]
I added some stats. A quarter of our reports are duplicates, and half our reports are low-quality.

**Comment by whit537** [comment]
- [ ] make a page listing our disclosures
 - [ ] figure out an image

**Comment by whit537** [comment]
![screen shot 2016-04-08 at 11 09 43 am](https://cloud.githubusercontent.com/assets/134455/14388095/6f4e8e7c-fd7a-11e5-9dbc-1f2226fd71b4.png)

**Comment by whit537** [comment]
![screen shot 2016-04-08 at 11 28 28 am](https://cloud.githubusercontent.com/assets/134455/14388649/0a6983ba-fd7d-11e5-8e73-006647b9021a.png)

**Comment by whit537** [comment]
Two points make a line? :-)

-----------------

![logo-049c93004a425a8472da247aa44c4edd](https://cloud.githubusercontent.com/assets/134455/14390506/72bbd7a8-fd85-11e5-9a6f-33d9f8d54fad.png)

https://hackerone.com/blog/uber-launches-first-of-its-kind-hacker-loyalty-program-with-hackerone-bonuses

------------

![hackerone-logo-300x206](https://cloud.githubusercontent.com/assets/134455/14390527/84a49ef0-fd85-11e5-8781-f0f2c1db3963.jpg)

https://blog.newrelic.com/2016/03/14/responsible-disclosure-security/

**Comment by whit537** [comment]
![screen shot 2016-04-08 at 12 34 44 pm](https://cloud.githubusercontent.com/assets/134455/14390679/546aecac-fd86-11e5-9a59-8b50b4701824.png)

**Comment by whit537** [comment]
Ready? I think we're ready ...

**Comment by whit537** [comment]
Published! :flushed: 

https://twitter.com/Gratipay/status/718480331666550784

**Comment by whit537** [comment]
To: chad@zetaweb.com
From: Mårten Mickos, HackerOne CEO
Subject: HackerOne Greetings

> Chad,
>
It's great to have Gratipay on our platform, and thanks for this wonderful blog posting!
>
https://gratipay.news/transparent-security-c864d03d6f60#.14zdb6i5l
>
Kind regards,
>
Marten

💃 

> Thanks for reaching out, Mårten! I like to think that between DoD and now Gratipay you've got both ends of some spectrum or other pinned down. The mighty and the meek, perhaps? ;-)
>
Keep up the good work! :-)

**Comment by whit537** [comment]
> Ha that's a great portrayal! Thanks for the quick response. 
>
We are still waiting for the Pentagon to write a blog posting as insightful as yours, so I'll put Gratipay in the mighty category.

-----------------

> :-)

**Comment by whit537** [comment]
I've received a kind note in private email from HackerOne's CEO. I've asked him if I can share it here.

**Comment by whit537** [comment]
> Kudos to the Gratipay team for the Transparent Security blog posting. It should be essential reading for anyone doing bug bounty programs or vulnerability coordination. You don't know how proud we are to have you on the H1 platform!

**Comment by whit537** [comment]
Also some encouraging feedback on Twitter:

> @whit537 Nice article about the @Gratipay bounty program!

https://twitter.com/mrusschen/status/718485981075283971

> Holy cow @Gratipay, this is a goldmine of feedback. Great writeup!

https://twitter.com/Magoo/status/718487174350409728
