### ISSUE TITLE
make Gratipay work for Asciidoctor [invoiced payins]

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#563]
@mojavelinux Picking up from https://github.com/gratipay/gratipay.com/issues/777#issuecomment-203940948, replied in email as well ([FD4494](https://gratipay.freshdesk.com/helpdesk/tickets/4494)) ...

Can we try to find a way to make Gratipay work for Asciidoctor? Happy to discuss here (or in email), but I think a video chat might be our best bet to cut to the chase. Any of these times work for you?
- Friday April 8 (tomorrow) at 11am Denver time
- Tuesday, April 12 at 11am
- Wednesday, April 13 at 11am

**Comment by mojavelinux** [comment]
Thanks for reaching out, @whit537! Tomorrow April 8th works best for me, as does the 11am Denver time. Skype works best for me (because it's the only video call that doesn't fail halfway through). I'm mojavelinux on Skype.

One item on the agenda will be the limitation that donations are anonymous (as I understand it). We have to know who is donating so we can credit those donors. It's a critical part of how we run our fundraiser and community. Names, names, names. I'd also like to discuss how we can accept money from companies (who seem to have their own way of doing things).

**Comment by mojavelinux** [comment]
Regard the anonymous issue, it's fine if the contributors are anonymous on the Gratipay site. I just need to know who they are so that I can properly credit them on the asciidoctor site.

See http://asciidoctor.org/supporters/

This is even a huge limitation of Salt right now. I only know who is contributing by matching usernames and pictures, assuming they are the same. If it's a username or picture I don't recognize, it might as well be anonymous because I have no way of knowing who it is.

**Comment by whit537** [comment]
> Tomorrow April 8th works best for me, as does the 11am Denver time. 

Awesome. Let's do it.

> Skype works best for me (because it's the only video call that doesn't fail halfway through). 

Skype can work. You've had technical issues with Google Hangouts, it sounds like? I ask because if we do a Hangout we can stream it and archive it to YouTube, which means others in the Asciidoctor and Gratipay communities can watch along, and we can deep-link to it from relevant tickets. If Hangouts (or having the call public) is bad then Skype will work and we can summarize on tickets.

> I'm mojavelinux on Skype.

Contact request sent! :-)

**Comment by whit537** [comment]
Ready when you are @mojavelinux ... we in Skype?

**Comment by whit537** [comment]
Okay! Just wrapped 1.5 hrs on the horn, quite the interesting counterpoint to https://github.com/gratipay/inside.gratipay.com/issues/316#issuecomment-205985573. :smile: 

The shortest short story is that our immediate task is to **facilitate a relatively large payment from a corporate sponsor to Asciidoctor**. That'll take some manual doin':

 1. First we'll need to connect with the corporate sponsor, make sure they're on board, and get them signed up on Gratipay.
 1. In parallel, Asciidoctor will need to [apply](https://gratipay.com/new) and go through our [Team review process](http://inside.gratipay.com/howto/review-teams).
 1. Then we'll send an invoice (our second, after https://github.com/gratipay/gratipay.com/issues/1199#issuecomment-68461948), collect the payment one way or another (ACH? check?!), and pay it out to Asciidoctor via our usual weekly PayPal MassPay.

There were about a million other things we talked about around the needs of an open-source project looking for sustainable funding, and how Gratipay can help and how we should evolve. Not much we don't already have tickets for, and the corporate giving piece is the biggest one to sort out _right now_. As we run through https://github.com/gratipay/gratipay.com/issues/1199 again let's really look at how to streamline this process.

@mojavelinux Thank you for the call! I look forward to helping Asciidoctor reach sustainability! :dancer: Let's keep this ticket open to track the (public side of the) process until the money lands in your bank account. :bow:

**Comment by mojavelinux** [comment]
What makes this contribution especially crucial is that it's our first corporate sponsor. We've been working under the assumption that once we get that first one, and promote that company as a visionary, others will follow.

**Comment by mojavelinux** [comment]
I just submitted the application for Asciidoctor. See https://github.com/gratipay/team-review/issues/200.

**Comment by whit537** [comment]
I've responded in private email re: connecting w/ the company in question.

**Comment by mojavelinux** [comment]
I'll follow-up with a summary of the issues discussed in the call for the record.

**Comment by whit537** [comment]
@mojavelinux Awesome, thank you. We covered a lot of ground, interested to see notes from your perspective. :-)

**Comment by whit537** [comment]
Sent:

> Greetings! Dan Allen from OpenDevise (copied here) has asked me to get in touch with you to facilitate a payment from [] to OpenDevise for the Asciidoctor project.
>
I've attached an invoice for $[], payable by check or bank deposit. Please advise if we need to change any info there.
>
Then, could we talk about setting up an account for [] on Gratipay? This can be done by using the [] Twitter account to sign in here:
>
https://gratipay.com/on/twitter/[]/
>
That's the easiest way for us to keep track of your payment in our system, but if you don't have access to []'s Twitter then let me know and we can explore other options.
>
Okay, thanks for working with us, []! Looking forward to landing this important contribution to Asciidoctor.

**Comment by whit537** [comment]
> I haven't heard back from [] yet. I tried the phone number just now and got a busy signal.
>
Would you like me to reach out again? I'm happy to do that, but I also don't want to be too forward since I don't really have a relationship with [] yet.
>
Let me know how you'd like to proceed ...

**Comment by mojavelinux** [comment]
@whit537 I forgot to mention that the point of contact at [] is on vacation for the next two weeks with limited connectivity. That person will be back on Apr 25th. I'll be visiting the offices later that week, so I will be sure to discuss it if you haven't heard anything.

**Comment by whit537** [comment]
Awesome, thanks @mojavelinux! :-)

**Comment by whit537** [comment]
Ping @mojavelinux. I'm going to be traveling over the next couple weeks, and wanted to make sure we don't leave this hanging out there longer than necessary. Any movement here? I'm happy to reach out again if that makes sense ...

**Comment by mojavelinux** [comment]
I'll be honest that I forgot to bring it up when I was on site (so busy with other things). I know that the point of contact is back in the office now, and caught up on e-mail, so you could reach out again. I'll check that the person got your message.

**Comment by whit537** [comment]
No worries, just wanted to make sure we don't let this slip too long.

Sent as a reply to my first mail:

> Greetings! I understand from Dan that you were traveling for a bit ... I'm actually heading out next week myself, and I wanted to make sure this doesn't fall _completely_ off our radar. Is this payment to Asciidoctor something you're interested in making happen? Can I do anything to help move this along?

If we don't hear back by Monday, then let's plan to pick up with this the following week. Thanks @mojavelinux! :-)

P.S. I've been fraternizing with your old employer—published [a piece on OpenSource.com](https://opensource.com/open-organization/16/5/want-best-employees-let-them-hire-themselves) recently. ;-)

**Comment by mattbk** [comment]
[Here's](https://news.ycombinator.com/item?id=11868496) another "B2B" request for what I could see as an invoicing system being used:

> What I'd really like to see is some sort of business account for Patreon or one of the others. Lots of companies use open source projects as an integral part of their day-to-day work, yet it does not seem straightforward to set up a monthly contribution to this work for a company. Obviously, they can use one-time grants to the Apache Software Foundation or someone else, but sometimes it is really just a single developer or a couple of developers that develop a crucial software package (webpack and others). Would be great if a company could support this easily as well.

**Comment by whit537** [comment]
Dan reports in private email that we have another lead here, from a different company. I've initiated contact from support@gratipay.com:

https://gratipay.freshdesk.com/helpdesk/tickets/5381

🎲 🎲

**Comment by mojavelinux** [comment]
Thanks @whit537! I'll follow-up with the lead to help move things along.

**Comment by whit537** [comment]
@mojavelinux Have you seen http://phk.freebsd.dk/VML/? It's basically what we're trying to do here, invoicing companies to pay for open source. PHK seems to be having some success with it. I don't know how much effort he puts into sales (so to speak), but it does sound like there's a negotiation pipeline, with companies leaking out at various points. I'm looking forward to making this whole process easier on Gratipay!

**Comment by whit537** [comment]
For the team: @mojavelinux and I have had a little back and forth in private email. Sounds like we need to keep our expectations in line with the typical corporate sales cycle (as well as European holiday schedules!). If we stay patient and focused we will start seeing success eventually! 🐢 > 🐇
