### ISSUE TITLE
firm up our midterm roadmap

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#569]
Reticketing from #558.

@rohitpaulk @mattbk @aandis Can we build some consensus around our mid-term roadmap? How should we organize our milestones and what should we prioritize?

http://github.com/gratipay/gratipay.com/milestones
http://github.com/gratipay/inside.gratipay.com/milestones
http://github.com/gratipay/grtp.co/milestones

**Comment by whit537** [comment]
Alright, working this through w/ @kaguillera IRL over here. First, a few preliminaries ...

 - In the `grtp.co` repo:
  - I've folded [Cleanup 2015](https://github.com/gratipay/grtp.co/milestones/Cleanup%202015) down into [Widgets 2.0](https://github.com/gratipay/grtp.co/milestones/Widgets%20for%20Gratipay%202.0), aaaaand ...
  - I've renamed [Widgets 2.0](https://github.com/gratipay/grtp.co/milestones/Widgets%20for%20Gratipay%202.0) to [Pivot](https://github.com/gratipay/grtp.co/milestones/Pivot) to line up with [Pivot](https://github.com/gratipay/gratipay.com/milestones/Pivot) in `gratipay.com`
 - I've slightly renamed the two milestones in this repo, `inside.gratipay.com`, to align with existing milestones in `gratipay.com`:
  - AML Program &rarr; [Implement an AML Program](https://github.com/gratipay/inside.gratipay.com/milestones/Implement%20an%20AML%20Program)
  - Payroll &rarr; [Bring Back Payroll](https://github.com/gratipay/inside.gratipay.com/milestones/Bring%20Back%20Payroll)

Let's use the `gratipay.com` milestones as the main ones, with subsidiary milestones in other repos indicated as such by their name.

**Comment by whit537** [comment]
Also, the "[Making it Right](https://gratipay.news/making-it-right-f8e1eccb46e)" blog post from last month is the wider context here. Basically what we're trying to do here is update our milestones to reflect the thinking in that blog post.

**Comment by whit537** [comment]
Flip-flop: grtp.co/Pivot &rarr; [Make Widgets 2.0](https://github.com/gratipay/grtp.co/milestones/Make%20Widgets%202.0)

**Comment by whit537** [comment]
Okay! So here's what we're thinking over here ...

 1. [Bring Back Payroll](https://github.com/gratipay/gratipay.com/milestones/Bring%20Back%20Payroll)—but scoped way down to _just_ the Gratipay Team and six ~users.`*`
 1. Finish cleaning up from the Gratipocalypse:
  1. [Finish Team Basics](https://github.com/gratipay/gratipay.com/milestones/Finish%20Team%20Basics)
  1. [Make Widgets 2.0](https://github.com/gratipay/grtp.co/milestones/Make%20Widgets%202.0)
  1. [Pivot](https://github.com/gratipay/gratipay.com/milestones/Pivot)
 1. Knock payments out of the park:
  1. [Tighten Onboarding Flow](https://github.com/gratipay/gratipay.com/milestones/Tighten%20Onboarding%20Flow)
  1. [Solve Corporate Sponsorship of Open-Source](https://github.com/gratipay/gratipay.com/milestones/Solve%20Corporate%20Sponsorship%20of%20Open-Source)
 1. Knock payroll out of the park:
  1. [Implement an AML Program](https://github.com/gratipay/gratipay.com/milestones/Implement%20an%20AML%20Program)
  1. Expand Payroll Beyond Gratipay

----------------------

`*` @kaguillera @mattbk @rohitpaulk @aandis @whit537 @clone1018

**Comment by whit537** [comment]
Notes:

 - This is a *product* roadmap. We've still got to do support, marketing, accounting, security, putting out fires, ...
 - Regarding "additional payin and payout routes"(https://github.com/gratipay/inside.gratipay.com/issues/571#issuecomment-208981158), I think those fall somewhere under (3).

**Comment by whit537** [comment]
@rohitpaulk Where are you at with diversifying payouts? If we get Dwolla (https://github.com/gratipay/gratipay.com/issues/726) done, would that take the pressure off for now until we get around to (3)?

**Comment by mattbk** [comment]
I added https://github.com/gratipay/grtp.co/issues/107 to [Make Widgets 2.0](https://github.com/gratipay/grtp.co/milestones/Make%20Widgets%202.0) because deployment will be needed at some point.

If these are midterm product goals, what does long-term look like? (4) in particular might not be midterm.

**Comment by whit537** [comment]
> I added gratipay/grtp.co#107 to Make Widgets 2.0 because deployment will be needed at some point.

Cool.

> If these are midterm product goals, what does long-term look like? (4) in particular might not be midterm.

Fair point. Probably (3) is beyond the "mid-term" horizon as well.

**Comment by whit537** [comment]
> Where are you at with diversifying payouts?

(... by which I mean, "What are your thoughts?" and not "Where is the code!" :-)

**Comment by whit537** [comment]
I was able to trim up and close the Bring Back Payroll milestone in the `inside.gratipay.com` repo.

**Comment by whit537** [comment]
I'm looking for how to update the [roadmap](https://github.com/gratipay/inside.gratipay.com/issues/575#issue-148933111) on the Radar with the info on this issue.

**Comment by whit537** [comment]
Done. See activity on https://github.com/gratipay/inside.gratipay.com/issues/575 and the new product radar at https://github.com/gratipay/inside.gratipay.com/issues/581.
