### ISSUE TITLE
Link to a  style guide for CSS

### ISSUE THREAD

**Issue by ESWAT** [gratipay/inside.gratipay.com#57]
Would be useful to have a convention going for CSS. Difficulty would be finding one with sane rules and works mostly with what we have already, so we don’t have to make a lot of changes to wedge into one.

The [GitHub](https://github.com/styleguide/css) and [mdo’s](http://codeguide.co/#css) style guides come to mind right now, but by all means feel free to link to others that we can repurpose for our needs.

**Comment by whit537** [comment]
https://github.com/darcyclarke/DSS

**Comment by whit537** [comment]
Old: https://github.com/gratipay/gratipay.com/issues/1054

**Comment by whit537** [comment]
http://mdo.github.io/code-guide/
