### ISSUE TITLE
go to PyOhio 2016

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#574]
July 30-31

http://pyohio.org/

CFP is open until May 15

**Comment by whit537** [comment]
Talk idea: "Now where did that $1,000,000 go?" Talk about the Great Accounting Cleanup of 2016, and all the Python scripts we've written along the way. Could be fun. :-)

**Comment by whit537** [comment]
- [scraping](https://github.com/gratipay/logs/blob/master/misc/308/raw/balanced/download.py) (maybe? this could be too trivial to be interesting, or could be a nice warmup)
 - [converting JSON to CSV via SQLite](https://github.com/gratipay/logs/blob/3f78119ae8734a3d8941dd6de07ed981401911e9/misc/308/raw/balanced/transactions-json2csv.py)
 - [backfilling](https://github.com/gratipay/gratipay.com/pull/3807)
 - [backfilling, again](https://github.com/gratipay/gratipay.com/pull/3912/files)
 - [extracting from PDFs via TETML](https://gist.github.com/whit537/4f07fe2a893a71f5f2c93118fc44c224)
 - whatever Python we land on for the books themselves (cf. https://github.com/gratipay/finances/issues/22)

**Comment by whit537** [comment]
Could be fun to organize this around [*Inception*](http://www.imdb.com/title/tt1375666/). Levels something like:

 1. **Plane**: We need to run Gratipay!
 1. **LA**: We need financial reports!
  - balance sheet
  - income statement
  - cashflow statement
 1. **Hotel**: We need an accounting system!
  - Ledger, GnuCash, tooling around it/them ...
 1. **Mountain**: We need data!
  - Scraping HTML, JSON, CSV, PDF, ...
 1. **Limbo**: We need clean data!
  - Matching transactions and exchanges 

The "kick" is the loading of data back up into the system.

Hmm ... [ETL](https://en.wikipedia.org/wiki/Extract,_transform,_load) as inception ... :-)

**Comment by whit537** [comment]
Or maybe Snow Fortress is ETL, and Limbo is schema fixes (https://github.com/gratipay/gratipay.com/issues/3822).

**Comment by whit537** [comment]
1. **Reality**: We need to run Gratipay!
 1. **Van Chase**: We need financial reports!
  - balance sheet
  - income statement
  - cashflow statement
 1. **Hotel**: We need an accounting system!
  - Ledger, GnuCash, tooling around it/them ...
 1. **Snow Fortress**: We need data! [ETL](https://en.wikipedia.org/wiki/Extract,_transform,_load):
  - Extract data from HTML, JSON, CSV, PDF (via XML), microfilm (via dead trees) ...
  - Transform data—matching transactions to exchaaaaaaaaaaaaaanges.
  - Load data into the database (easy part).
 1. **Limbo**: We need to fix our schema!
  - `NOT NULL` constraints (https://github.com/gratipay/gratipay.com/issues/3822)
  - immutable primary keys (https://github.com/gratipay/gratipay.com/issues/835)

**Comment by whit537** [comment]
> The call for proposals has been extended to June 4!

https://twitter.com/pyohio/status/731506166036041730

**Comment by kzisme** [comment]
I just got tickets as well :dancer:

**Comment by kzisme** [comment]
@whit537 Are you still planning on heading out on Saturday?  I plan on making my way there!

**Comment by whit537** [comment]
Yes! My plan is to be at PyOhio on Saturday morning for a bit. Look for the penny puncher! 💃

**Comment by kzisme** [comment]
I shall!  How long are you planning on sticking around for?  

Anything I should know as a first time conf go-er?

**Comment by whit537** [comment]
I'll probably leave around lunchtime. Meet people and have fun! 😄

**Comment by whit537** [comment]
Missed you, @kzisme! Next year? :)

![coofcf0xgaa3_ol](https://cloud.githubusercontent.com/assets/134455/17350774/8ed72212-58f7-11e6-81bd-822eda6d9d14.jpg)


https://twitter.com/cmbeelby/status/759425485789167616

**Comment by whit537** [comment]
Also rep'd COS. :)

![cootzj2xgaaoqeo](https://cloud.githubusercontent.com/assets/134455/17350815/cbf13c00-58f7-11e6-820d-7352cdea82ea.jpg)

https://twitter.com/heartdefense/status/759469405562699776
https://twitter.com/whit537/status/759871631934185472

**Comment by whit537** [comment]
The most important part of PyOhio for me was apologizing face-to-face to some people for the Gittip crisis (cf. https://github.com/gratipay/inside.gratipay.com/issues/319#issuecomment-233127225). Not everyone I may have liked but to several. There was one apology in particular that was super awkward and difficult ... and good. 😥

**Comment by whit537** [comment]
Other than that it was fun to be there. I like that conference a lot. :-)

Okay! To next year! :)
