### ISSUE TITLE
Tech Radar 0

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#577]
------------

#### Docs

http://inside.gratipay.com/howto/sweep-the-radar

#### Mission

The mission of the tech team is to support the product team in solving problems in the market.

#### Scope

 - dev
 - ops
 - PagerDuty
 - UptimeRobot
 - Heroku
 - Digital Ocean
 - AWS
 - Payday
 - Librato
 - https://github.com/gratipay/postgres.py
 - https://github.com/gratipay/gip.rocks
 - https://github.com/gratipay/honcho
 - https://github.com/gratipay/environment.py

#### Roadmap

- Move to Amazon SES (#515), **April 27th Deadline**!!
- stop using immutable ids as primary key (https://github.com/gratipay/gratipay.com/issues/835)
-  other [embarrassments](https://github.com/gratipay/gratipay.com/labels/Pretty%20Embarrassing)

**Comment by rohitpaulk** [comment]
I guess https://github.com/gratipay/inside.gratipay.com/issues/515 belongs here?

**Comment by rohitpaulk** [comment]
#515 is now blocked on https://github.com/gratipay/inside.gratipay.com/issues/585

**Comment by whit537** [comment]
#### Email ([what?](http://inside.gratipay.com/howto/sweep-the-radar))

![screen shot 2016-04-27 at 9 51 43 am](https://cloud.githubusercontent.com/assets/134455/14854479/eb32c05c-0c5d-11e6-8802-ba30dfc14282.png)
