### ISSUE TITLE
Add our DNSimple credentials to Lastpass

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/inside.gratipay.com#585]
To verify our domain for https://github.com/gratipay/inside.gratipay.com/issues/515, I'll need to add a `TXT` record and a few `CNAME` records. 

Where are our DNS records managed? Let's use team accounts if they are supported by that service, else we'll share credentials over Lastpass

**Comment by rohitpaulk** [comment]
I'm looking at http://inside.gratipay.com/appendices/tools, and I don't see anything there..

**Comment by rohitpaulk** [comment]
Hmm, https://github.com/gratipay/gratipay.com/issues/1512#issuecomment-25214184 suggests that we use DNSimple

**Comment by whit537** [comment]
Here's our domain registration and DNS situation:

 - All domains are registered at [IWantMyName](https://iwantmyname.com/). However, they [don't support](https://iwantmyname.com/blog/2014/01/why-alias-type-records-break-the-internet.html) any of the DNS extensions that allow for apex `CNAME`s (e.g., `ALIAS`).
 - 10 of our domains have DNS hosted at [DNSimple](https://dnsimple.com/), which [does provide](https://support.dnsimple.com/articles/alias-record/) `ALIAS` records. We're on a grandfathered pricing tier of $3/mo for 10 domains.

**Comment by whit537** [comment]
> I'll need to add a `TXT` record and a few `CNAME` records.

May I do this for now? What are the records we need?

> Let's use team accounts if they are supported by that service, else we'll share credentials over Lastpass

[Multi-user accounts](https://support.dnsimple.com/articles/account-users/) will require an upgrade at DNSimple.

**Comment by whit537** [comment]
To get team accounts will have to go from $3/mo to $35/mo.

**Comment by whit537** [comment]
https://dnsimple.com/pricing

**Comment by rohitpaulk** [comment]
> May I do this for now? What are the records we need?

Yes, that'll be fine :) Might be easier if you visit the SES page yourself.. https://us-west-2.console.aws.amazon.com/ses/home?region=us-west-2#verified-senders-domain:

<img width="1685" alt="screen shot 2016-04-19 at 9 12 50 pm" src="https://cloud.githubusercontent.com/assets/3893573/14645502/8a26be5c-0673-11e6-9cec-4f1e43488810.png">
