### ISSUE TITLE
Investigate MassPay failures on Apr 28 2016

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/inside.gratipay.com#604]
https://github.com/gratipay/inside.gratipay.com/issues/595#issuecomment-216264530

> None of our Paypal payments got sent out last payday

> The reason code is mentioned as `3141`, and I can't find that anywhere in [Paypal's list](https://developer.paypal.com/docs/classic/mass-pay/integration-guide/MassPayUsingAPI/#ipnreasoncodes)

**Comment by rohitpaulk** [comment]
Sent an email to Paypal support. 

<img width="1232" alt="screen shot 2016-05-02 at 8 54 37 pm" src="https://cloud.githubusercontent.com/assets/3893573/14958363/1dec1fb8-10a8-11e6-8546-12af8566f91b.png">

**Comment by whit537** [comment]
😶

**Comment by whit537** [comment]
![screen shot 2016-05-02 at 1 55 36 pm](https://cloud.githubusercontent.com/assets/134455/14962587/93f695de-106d-11e6-8b33-3199bacbfd48.png)

**Comment by whit537** [comment]
Login retry worked ...

**Comment by whit537** [comment]
I'm gonna go ahead and call. This could be a big deal.

**Comment by whit537** [comment]
I mean, it already is a big deal, since we failed to pay out to people.

**Comment by whit537** [comment]
Here's the MassPay receipt from last Thursday: https://gratipay.freshdesk.com/helpdesk/tickets/4788

**Comment by whit537** [comment]
Finally made it through the phone queue ... bumped to someone else ...

**Comment by whit537** [comment]
Okay, I have someone on the phone ...

Meanwhile, noticed this reply to @rohitpaulk's email ...

> Thank you for contacting PayPal Customer Support. My name is [] and I am happy to assist you.
After viewing your account I do not see a denial reason on your account that would decline the transaction. I would suggest to try the payment again. It could have been a connection issue or internet interruption causing the error.

https://gratipay.freshdesk.com/helpdesk/tickets/4815

On hold again ...

**Comment by whit537** [comment]
@rohitpaulk Same basic response from phone support, but he did say that we're not the only ones affected. It's an "intermittent" issue that others are reporting as well; he added us to the list of those affected.

Okay! @rohitpaulk wanna retry the payout? Prolly apologize in the note.

**Comment by rohitpaulk** [comment]
Retrying...

**Comment by rohitpaulk** [comment]
> Prolly apologize in the note.

"We're a bit late this week, sorry about that! Check https://github.com/gratipay/inside.gratipay.com/issues/604 for details."

Does that work? cc: @mattbk

**Comment by mattbk** [comment]
Maybe be more specific? "This payout is for April 28 and was delayed, sorry about that! Check #604 for details."

**Comment by rohitpaulk** [comment]
I was impatient, sorry 😞 

Masspay posted back. I manually checked for the user that wrote to support, their payment has been processed.

**Comment by whit537** [comment]
!m @rohitpaulk @mattbk
