### ISSUE TITLE
onboard @sseerrggii

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#616]
> I have been following gratipay in recent years because I think it's a really interesting project and really necessary! I want to know if I can contribute improving gratipay, maybe I can help with translations or maybe with other product/marketing/UX/business details. I think it would be better to collaborate to improve gratipay instead of creating a similar project on my own.

**Comment by whit537** [comment]
(The above is from @sseerrggii in private email. Moving the conversation here with his permission.)

@sseerrggii Thanks again for reaching out! As discussed, here is [our translation howto](http://inside.gratipay.com/howto/translate-gratipay). Please feel free to ask any and all questions here on this ticket as you get oriented to working with us on Gratipay. We're happy to have you! :-)

**Comment by sseerrggii** [comment]
I did some translations. Transifex is a really simple way to perform translations!! :100: 

I have some questions:

* In Spanish we have a tense to refer to someone in a very formal way, like Mr., but in our case it changes the verb tense. Most websites use more colloquial and close tense of referring to someone, like a friend, I'm making suggestions to translations already maded to improve this aspect as well as some rare expressions (at least in the Spanish of Spain :grin: )

* Another question that comes to me in a few sentences to understand the context, for example `Fix your card` For better translation I need to know if it is a button that retries a payment, or if it link to modify data card or something else... Maybe in the future I could test as a user in Spanish and make a second review of translations

When I have more translations made I will find someone fluent in English (better than me :grinning: ) and also know Spanish to perform a general review, what do you think?

**Comment by sseerrggii** [comment]
@whit537

**Comment by mattbk** [comment]
@whit537 is [out for the week](https://github.com/gratipay/inside.gratipay.com/issues/619#issuecomment-219482607).

Your plans sound good to me. Do you have a list of terms without context, or is it just those you mention?

**Comment by sseerrggii** [comment]
Thanks @mattbk I had problems especially with these words and concepts, but I think I'll understand better when I understand the whole flow of gratipay

**Comment by mattbk** [comment]
- ["Fix your card" ](https://github.com/gratipay/gratipay.com/blob/f211a35bba1f90fb396a242a6dc1c1931f89041d/gratipay/utils/notifications.py#L13) is in relation to updating the information on a failed credit card.
- "payroll" is explained [here](https://gratipay.com/about/features/payroll) but [will be replaced soon](https://github.com/gratipay/inside.gratipay.com/issues/325#issuecomment-217332752).
- "statement" is the word used for where a ~user can add information about him- or herself on his or her profile page. This is a holdover from when ~users could directly receive funds, so the "statement" in that case was an explanation of why that ~user deserves a donation.

**Comment by whit537** [comment]
@sseerrggii Looks like I dropped the ball here (though thanks @mattbk for picking it up). Sorry about that. 😞  Are you still interested in helping translate Gratipay? Did your translations ever make it out into production?

**Comment by sseerrggii** [comment]
Hello @whit537 
Yes, I'm still interested!!
I don't know if my translations came to production.
Which would be the next step?

**Comment by whit537** [comment]
Huzzah! 💃 

Could you check to see if any of your translations made it through onto the website? We ship new translations automatically during deployment (and we've certainly deployed since May) but they may need to be "reviewed" first. I'm about to hop on a plane (#867) ... I will check back in a bit! :-)

**Comment by sseerrggii** [comment]
Hello @whit537 

Yes, my translations are in production!!

Right now spanish translation is 100% in transifex!! Pending to test in the application and change some expressions that may be confusing... could I have a test account with teams?

**Comment by whit537** [comment]
@sseerrggii Awesome! May I add you to our [money distribution](https://gratipay.com/Gratipay/distributing/)? What's your Gratipay account?

In terms of a test account with teams ... I would say go ahead and [apply for a new team](https://gratipay.com/new) yourself, it's pretty common to have security researchers (for example) do this.

**Comment by sseerrggii** [comment]
Thanks @whit537 !  My account is https://gratipay.com/~sseerrggii/

I see many untranslated sentences in the web application. Can you tell me when there is a production update and I will check everything?

**Comment by whit537** [comment]
> My account is https://gratipay.com/~sseerrggii/

Cool. Before I can add you to the money distribution, you'll need to:

- link a [PayPal](https://gratipay.com/about/me/routes/)
- fill out a [national identity](https://gratipay.com/about/me/identities/)

> I see many untranslated sentences in the web application. Can you tell me when there is a production update and I will check everything?

Hmm ... maybe the strings need to be reviewed after all? Let's see here ...

**Comment by whit537** [comment]
I reviewed one of the strings, [deployed](https://github.com/gratipay/inside.gratipay.com/issues/900#issuecomment-262000622), and it looks like it is now showing up!

--------------------

![before](https://cloud.githubusercontent.com/assets/134455/20492682/b6b4398a-afe3-11e6-9ef8-53128db43155.png)

![after](https://cloud.githubusercontent.com/assets/134455/20492683/b6b47dfa-afe3-11e6-8523-99c77c706849.png)

--------------------

I [checked](http://docs.transifex.com/client/pull/#file-mode) on the [plumbing](https://github.com/gratipay/gratipay.com/blob/2008/Makefile#L106) and I think the best option is to review the strings in the Transifex UI. Do you have permissions to do that in Transifex? Maybe we should reach out on Twitter to see if there is anyone else who would be willing to help you? :)

**Comment by whit537** [comment]
> Maybe we should reach out on Twitter to see if there is anyone else who would be willing to help you?

Waddya say, @mattbk? :)

**Comment by whit537** [comment]
I went for it. :-)

> Anyone up for reviewing the Spanish translation that @sseerrggii has been working on? Here's how to get plugged in: http://inside.gratipay.com/big-picture/welcome.

https://twitter.com/Gratipay/status/800818426671267841

**Comment by whit537** [comment]
@sseerrggii If we don't get any takers soon, then I'm happy to trust your translations and mark them as reviewed, if you don't have permission to do that yourself.

**Comment by sseerrggii** [comment]
OK @whit537 

I think that for the first iteration it is best to have translations even if they are not accurate (better than having untranslated sentences) in future I will do revisions to improve them, I can find someone to help me from Spain Time Banks ;)

I have already filled in Paypal and National identity

**Comment by whit537** [comment]
> I think that for the first iteration it is best to have translations even if they are not accurate

Agreed. I've made you a Coordinator in Transifex, so you should be able to self-review your translations now. Note that there are three other Spanish translators who have been active on Transifex fairly recently. Perhaps you can coordinate with them?

> I have already filled in Paypal and National identity

Awesome, added! Welcome aboard! 💃

**Comment by sseerrggii** [comment]
Wow!! Coordinator, lots of responsibility! ;)
ok, I will contact the other translators to continue working on it

**Comment by whit537** [comment]
@sseerrggii Sweet! See also https://github.com/gratipay/inside.gratipay.com/issues/189, where I'm doing some more Transifex and translator team maintenance ...
