### ISSUE TITLE
adapt to GitHub's new pricing

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#617]
GitHub just announced a new [pricing](https://github.com/blog/2164-introducing-unlimited-private-repositories) scheme. tl;dr They're moving us from $25/mo to $196/mo. 😞 

![screen shot 2016-05-11 at 2 46 30 pm](https://cloud.githubusercontent.com/assets/134455/15192476/57a636cc-1787-11e6-9a71-362b5237de9e.png)

**Comment by rohitpaulk** [comment]
Let's move the private repositories to GitLab?

**Comment by rohitpaulk** [comment]
> And while we're currently not enforcing a timeline to move, rest assured that you'll have at least 12 months notice before any mandated change to your plan.

**Comment by whit537** [comment]
Things suuuuure are heatin' up!

https://about.gitlab.com/2016/05/11/git-repository-pricing/#pricing-overview

![screen shot 2016-05-11 at 6 28 38 pm](https://cloud.githubusercontent.com/assets/134455/15198581/3b4b920a-17a6-11e6-884b-57e6fdc4bacc.png)

**Comment by whit537** [comment]
Posted about it:

> We're looking at $196/mo with @GitHub's new pricing, up from $25. Disincentivizes sharing. 😞

https://twitter.com/Gratipay/status/730526107829731328

**Comment by whit537** [comment]
> Let's move the private repositories to GitLab?

Or everything? #617

**Comment by holic** [comment]
> We want everyone to have a plan with unlimited private repositories, but don’t worry—you are welcome to stay on your current plan while you evaluate the new cost structure and understand how to best manage your organization members and their private repository access. And while we're currently not enforcing a timeline to move, rest assured that you'll have at least 12 months notice before any mandated change to your plan.

**Comment by whit537** [comment]
@holic Yeah, it's good that we don't have to rush. :-)

**Comment by nobodxbodon** [comment]
Github has [sponsored](https://github.com/gratipay/inside.gratipay.com/issues/928#issuecomment-268284897) us.
