### ISSUE TITLE
Fast-track approval for owners who already have approved teams

### ISSUE THREAD

**Issue by mattbk** [gratipay/inside.gratipay.com#648]
If an owner "in good standing" applies for another team and has checked all the TOS boxes, should they need to wait a week for the team to be approved? Even though payday is weekly, I'm sure people would like to get set up and advertise that they are accepting donations as soon as possible.

Example:
https://gratipay.com/~bbatsov/, who is up to four teams now.

**Comment by whit537** [comment]
I had this thought as well on https://github.com/gratipay/team-review/issues/215. Looks like we don't actually give any timeframes on the [Review Teams](http://inside.gratipay.com/howto/review-teams) howto. I thought we said "at least a week" somewhere ... is that just on the application form or what?

**Comment by mattbk** [comment]
It's included in each application issue, but I can't find it anywhere in the documentation, and not at /new. I know you must have mentioned it before setting that up, but I can't find it.

Does it say it in the "thanks for applying" email?

**Comment by mattbk** [comment]
Do we have a "thanks for applying" email?

**Comment by aandis** [comment]
Surprisingly, we don't. :hushed:

**Comment by mattbk** [comment]
It's in the application issue (created [here](https://github.com/gratipay/gratipay.com/blob/f659ac92c7ac3c31ff847169263fcfc9e1dd5977/gratipay/models/team.py#L220)).

**Comment by mattbk** [comment]
It's in the [TOS](https://gratipay.com/about/policies/terms-of-service), but a week is not specified:

> Establishing a Team on Gratipay involves an application and approval process. As part of this process, the Gratipay community will have the opportunity to publicly evaluate and provide commentary about the Team. However, all decisions regarding whether to accept, reject, suspend, remove, or take any other action regarding a Team belong solely to Gratipay.

(ht https://github.com/gratipay/inside.gratipay.com/issues/210#issue-80760361)

**Comment by mattbk** [comment]
A week must have been chosen because everything else at Gratipay runs on a weekly basis, and the original review tickets were opened on a weekly basis.

With this in mind, I think a fast track of three days for Teams whose owners already own another Team would be fair.

**Comment by whit537** [comment]
> I think a fast track of three days for Teams whose owners already own another Team would be fair.

👍

**Comment by mattbk** [comment]
I suppose http://inside.gratipay.com/howto/review-teams is the place to document this.
