### ISSUE TITLE
run Gratipay 209

### ISSUE THREAD

**Issue by mattbk** [gratipay/inside.gratipay.com#649]
[&larr; Payday 208](https://github.com/gratipay/inside.gratipay.com/issues/638)

-------------

##### Docs

http://inside.gratipay.com/howto/run-payday

##### Rotation

| Month | Pilot | Copilot |
|:------|:----|:--------|
| June | @whit537 :airplane: | @clone1018 |
| July | @rohitpaulk | @whit537 |
| August | @clone1018 | @rohitpaulk |
| September | @whit537 | @clone1018 |
| October | @rohitpaulk | @whit537 |
| November | @clone1018 | @rohitpaulk |
| December | @whit537 | @clone1018 |
| January | @rohitpaulk | @whit537 |
| February | @clone1018 | @rohitpaulk |
| March | @whit537 | @clone1018 |
| April | @rohitpaulk | @whit537 |
| May | @clone1018 | @rohitpaulk |

**Comment by whit537** [comment]
On it ... once I find @kaguillera at Old Crow (new name for Blue Canary!) 🐦

**Comment by kaguillera** [comment]
I am here already

**Comment by whit537** [comment]
No accounts or 1.0 payouts to review.

**Comment by whit537** [comment]
> I am here already

😛

**Comment by whit537** [comment]
```
[gratipay] $ heroku config -s -a gratipay | ./env/bin/honcho run -e /dev/stdin ./env/bin/python ./bin/migrate-tips.py > migrate-tips.log
[gratipay] $ cat migrate-tips.log 
Done.
[gratipay] $
```

**Comment by whit537** [comment]
Script started.

**Comment by whit537** [comment]
Script ran for two minutes (0:02:01.834607).

**Comment by whit537** [comment]
```
gratipay::MAROON=> update exchange_routes set fee_cap = 20.00 where fee_cap is null and network = 'paypal';
UPDATE 7
```

**Comment by whit537** [comment]
MassPay submitted. No fee errors.

**Comment by whit537** [comment]
POSTed MassPay back to Gratipay for 54 users.

**Comment by whit537** [comment]
Logs in https://github.com/gratipay/logs/commit/ea6bebeb3e7c61797a34c46d9a3d36b76b695bca.

**Comment by whit537** [comment]
Added 1,677.81 to PayPal.

**Comment by whit537** [comment]
![screen shot 2016-06-02 at 12 42 52 pm](https://cloud.githubusercontent.com/assets/134455/15753152/8ff665ee-28bf-11e6-920c-72aada20dc8c.png)

**Comment by whit537** [comment]
11 / 63 = 17.5% decline rate

**Comment by whit537** [comment]
Decline rate for the past 30 days is 25 / 324 = 7.7%. I'm not going to report to Braintree risk.
