### ISSUE TITLE
upgrade Sentry

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#658]
> ##### Upgrade to capture more data
> 
> 1,769 of the 11,721 events sent from Jun 01 to 02 — 15.1% of all events sent by Gratipay — were rejected due to rate limits.
> 
> Your organization's current Small plan allows recording up to 25 events per minute. To ensure that all of the events that you send are recorded, upgrade your subscription to a larger plan.
> 
> For more detailed information about your organization's quota usage, including hourly statistics, you can [view your organization statistics](https://app.getsentry.com/organizations/gratipay/stats/).

https://gratipay.freshdesk.com/helpdesk/tickets/5043

**Comment by whit537** [comment]
I don't think we should actually upgrade yet, but I wanted to start a ticket so we can track this over time. If we keep getting clipped and don't want to upgrade then we should look at reducing our usage (by fixing bugs, or perhaps with #561).

**Comment by nobodxbodon** [comment]
Sentry has [sponsored](https://github.com/gratipay/inside.gratipay.com/issues/928#issuecomment-268097102) us. Has the rate limit changed?

**Comment by whit537** [comment]
Yes. Our current limit is 100 EPM, up from 25 when this issue was created. Closing.
