### ISSUE TITLE
Privacy error in Chrome when accessing IG

### ISSUE THREAD

**Issue by mattbk** [gratipay/inside.gratipay.com#659]
![image](https://cloud.githubusercontent.com/assets/3729038/15861762/fcfee22a-2c92-11e6-9616-1945f57d44a9.png)

**Comment by whit537** [comment]
We serve IG over HTTP, not HTTPS, though we may have a ticket open for converting to HTTPS.

**Comment by mattbk** [comment]
HTTPS link at https://github.com/gratipay/team-review/blob/master/README.md.
