### ISSUE TITLE
pursue venture capital

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#68]
Over at https://github.com/gittip/www.gittip.com/issues/239 we've been talking about what it would look like for Gittip to take venture capital in the context of a conversation with one firm. Here's a ticket to talk about the idea in general.

**Comment by whit537** [comment]
With [Gratipay 2.0](https://medium.com/gratipay-blog/gratipay-2-0-2453d3c53077), payments to teams are no longer no-strings attached. Reopening from #384.

**Comment by whit537** [comment]
From http://www.collaborativefund.com/about/alignment-holdings/:

https://www.omidyar.com/
http://www.knightfoundation.org/
http://casefoundation.org/
http://www.kaporcapital.com/

**Comment by mattbk** [comment]
Is Ambridge a Knight Foundation city?

**Comment by whit537** [comment]
Uh ... don't know much about that. Probably not? But maybe (probably) Pittsburgh is?

**Comment by mattbk** [comment]
Philadelphia is...

**Comment by whit537** [comment]
Looks like Pittsburgh isn't.

**Comment by whit537** [comment]
> Seed venture capital and operational expertise for entrepreneurs building the Bottom Up Economy.
>
What's the Bottom Up Economy? Enabling small businesses and individual consumers and developers to more easily and cost effectively access technology, information and customers so that they can create, transact, communicate and grow.

http://www.homebrew.co/

via http://www.disruption.vc/blog/what-if-facebook-were-a-nonprofit

**Comment by whit537** [comment]
I've got a meeting with [Aaron Tainter](https://www.innovationworks.org/About-Us/Team/Experts/Aaron-Tainter) at AlphaLab this afternoon (follow-on from last Wednesday's [event](https://twitter.com/Gratipay/status/710117565977206784)).

**Comment by whit537** [comment]
Good meeting, I felt like I was able to communicate what Gratipay is about. AlphaLab is an accelerator, a 20-week program (summer and winter sessions), with $25,000 for 5% of the company, plus another $25,000 (as a convertible note) if we raise another $50,000.

**Comment by whit537** [comment]
http://firstround.com/

**Comment by whit537** [comment]
If we do decide to pursue venture capital per https://github.com/gratipay/inside.gratipay.com/issues/405#issuecomment-286713221, then #1033 may be a good launching point. The ideal scenario would be that we see an uptick following #948 #920 and therefore in a stronger position to pursue funding.

**Comment by whit537** [comment]
List of enlightened investors on https://www.zebrasunite.com/resources.

**Comment by whit537** [comment]
Especially interesting is http://www.indie.vc/. I know I've noticed that before, but apparently haven't noted it here. They make their money via payouts from revenue, not from liquidity events.

**Comment by whit537** [comment]
O'Reilly's [behind it](http://oatv.com/).

**Comment by whit537** [comment]
Reticketed as https://github.com/gratipay/inside.gratipay.com/issues/1034.

**Comment by whit537** [comment]
> [I]t’s both tragic and amazing that the company, in all its handmade, anticapitalist, pro-composting glory, became significant enough for activist investors to bicker over it.

https://www.bloomberg.com/news/features/2017-05-18/the-barbarians-are-at-etsy-s-hand-hewn-responsibly-sourced-gates
