### ISSUE TITLE
publish second article on OpenSource.com

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#683]
Follow-on from #551. Ping @semioticrobotic.

##### Drafts

1. [~~Part 2~~](https://medium.com/@whit537/part-2-308ffbfdf15d)
1. [~~Part 2~~](https://medium.com/@whit537/part-2-490d93857f82)
1. [**on Google Docs**](https://docs.google.com/document/d/1EGHLGRGnbs6ppsUd91EGpNMivcq5koWF857HCRJt8iI/edit?usp=sharing)

**Comment by whit537** [comment]
Dug up the IRC announcement for the switch to take-what-you-want:

https://botbot.me/freenode/gratipay/2013-06-27/?msg=4128376&page=4

**Comment by whit537** [comment]
Actively working on a draft here: https://medium.com/@whit537/308ffbfdf15d

Part 1: https://opensource.com/open-organization/16/5/employees-let-them-hire-themselves

The main serendipity for part 2 is that I've learned about a lot of other organizations already doing so-called "self-set salaries." I think I had sort of convinced myself that I thought up the idea myself after failing with a rankings-based system. Now I admit to myself and yinz that I got the idea from _Maverick_, a book which @pjz gave me back in 2013, when we were [first iterating](https://github.com/gratipay/inside.gratipay.com/issues/534#issuecomment-202671259) teams. At #314 and #464 I heard that [_Reinventing Organizations_](http://www.reinventingorganizations.com/) gives examples of self-set salaries—Semco, yes, but also [Morning Star](http://morningstarco.com/) and one or two others (I bought that book, and just reordered _Maverick_).

So the story here is less "Check out what we invented/discovered" and more "Here's Gratipay's take on self-set salaries."

**Comment by whit537** [comment]
Alright, draft 1: https://medium.com/@whit537/part-2-308ffbfdf15d.

**Comment by semioticrobotic** [comment]
Love the draft, @whit537. I think it's shaping up nicely. Especially valuable is the section on "tensions"—those moments in which the program seemed to strain or sputter—and the concrete action you undertook to address these moments. I see you're planning to build on those bits, and I applaud that. Happy to keep looking as it continues to take shape.

**Comment by whit537** [comment]
@semioticrobotic Can we aim to publish on July 19th? I can aim to deliver a second draft next Monday, the 11th, giving us a week for final edits. Does that work for you?

**Comment by semioticrobotic** [comment]
Yes, @whit537. We can absolutely do that. Looking forward to seeing the next draft.

**Comment by whit537** [comment]
@semioticrobotic Awesome, thanks. Here's the [second draft](https://medium.com/@whit537/part-2-490d93857f82#.3autvmmju)—just copied/pasted from the first for now. I'll drop you a line when it's ready for review! :-)

**Comment by whit537** [comment]
Looks like I'm not gonna get to this today. I'll try again tomorrow!

**Comment by semioticrobotic** [comment]
No worries, @whit537! We'll catch up tomorrow.

**Comment by whit537** [comment]
Okay, @semioticrobotic! Here's [a second draft](https://medium.com/@whit537/part-2-490d93857f82)! Looks like it's weighing in at 1,800+ words, so we'll have to see what we can trim. Let me know if you think we can get this down, or if we should split out a _third_ part!

**Comment by semioticrobotic** [comment]
Looking at this now, @whit537. Heads up: It' easier and preferable for me to edit in a word processor, so I am plunking the text in there and doing the work that way.

**Comment by whit537** [comment]
Sounds good, @semioticrobotic. Besides being too long, I'm not satisfied that the conclusion is punchy enough. Interested to see your take.

**Comment by semioticrobotic** [comment]
This is awesome, @whit537. Yes, it's longer than some of the stories we typically run on Opensource.com, but it's just chock full of insights, including a well-balanced bit of background that really sets the stage for the experiment and provides offshoots for folks looking to dig deeper. On top of that, it's pretty tightly written, so I don't see much we can cut without damaging the integrity of the piece.

I did edit a few things for style, readability and (a little for) length. Per your request, I also toyed with the ending a bit.

Looks like I'm not allowed to upload my ODT file (sorry about that), so I hope a DOCX will suffice. let me know what you think of the changes.
[gratipay_twyw.docx](https://github.com/gratipay/inside.gratipay.com/files/361635/gratipay_twyw.docx)

**Comment by whit537** [comment]
Thanks @semioticrobotic! I've thrown the DOCX into a [Google Doc](https://docs.google.com/a/zetaweb.com/document/d/1EGHLGRGnbs6ppsUd91EGpNMivcq5koWF857HCRJt8iI/edit?usp=sharing) for easier sharing. Reviewing your changes now ...

P.S. I've also emailed support@github.com to ask for ODT file attachment support. :)

**Comment by whit537** [comment]
> his or her

I think we should use the singular "their," to avoid unnecessarily excluding folks who use other [pronouns](http://pronoun.is/).

**Comment by whit537** [comment]
We need to update all the links to remove the Medium redirects.

**Comment by whit537** [comment]
Hey @simonsarazin, do you have the screenshot of the take-what-you-want listing for Gittip back in the day? The one you used during the session in Lille? (And did I ask you this already somewhere else? :) Mind sharing that here so we can consider including it in this article for OpenSource.com? I think it really helps to give people a concrete picture of what the system looked like—a 🎨  is worth a thousand 📝 ! :)

**Comment by semioticrobotic** [comment]
> I think we should use the singular "their," to avoid unnecessarily excluding folks who use other pronouns.

I'm on board with that!

**Comment by whit537** [comment]
@semioticrobotic I'm actively revising in Google Docs. I haven't used that much before—I think it'll give us a nice editing history.

**Comment by whit537** [comment]
I'm experimenting with their commenting features a bit as well, not sure yet what the best usage pattern for us will be ...

**Comment by whit537** [comment]
I've made a pass through everything but the conclusion, hoping to return to that after lunch.

The biggest structural change I made was moving the first paragraph under "Stress testing" up into the previous "Take-what-you-want in practice" section, and the two-item list of abuse prevention measures down into a new intro under "Stress testing". My thinking is that "Twyw in practice" is now about the system's _normal_ operation, and "Stress testing" is about the system _under load_ (as it were).

**Comment by SimonSarazin** [comment]
@ChadWhitacre is it this photo :
http://simons.fr/1_blog/wp-content/uploads/2013/11/S%C3%A9lection_355.png
 ?

You also have it whit the team of young people of a cooperative using the
take what you want system :
http://pix.toile-libre.org/upload/original/1452243419.jpg

I'd like to find a photo of gratipay team when it was at his top ;)

Le mer. 13 juil. 2016 18:51, Chad Whitacre <notifications@github.com> a
écrit :

> I've made a pass through everything but the conclusion, hoping to return
> to that after lunch.
>
> The biggest structural change I made was moving the first paragraph under
> "Stress testing" up into the previous "Take-what-you-want in practice"
> section, and the two-item list of abuse prevention measures down into a new
> intro under "Stress testing". My thinking is that "Twyw in practice" is now
> about the system's *normal* operation, and "Stress testing" is about the
> system *under load* (as it were).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/gratipay/inside.gratipay.com/issues/683#issuecomment-232416628>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAl2jrYKFwxexE5mtmFQRFXMbl-rm0gJks5qVReDgaJpZM4I6EZm>
> .
>
-- 

Simon
0684284240
http://simons.fr

**Comment by whit537** [comment]
@simonsarazin Oui, merci !

> a photo of gratipay team when it was at his top

Hmm ... I could probably reconstruct this from a backup ...

**Comment by whit537** [comment]
Inlining the pictures ...

![selection_355](https://cloud.githubusercontent.com/assets/134455/16814063/40575e72-4902-11e6-8134-af829ea9051a.png)

**Comment by whit537** [comment]
![1452243419](https://cloud.githubusercontent.com/assets/134455/16814072/4482ef34-4902-11e6-9693-375b0b8babc1.jpg)

**Comment by whit537** [comment]
After some digging around, it looks like January 22, 2015, is "the top." Changaco and I were both taking $110. It was right before our third stress test (#136). I've dug up a backup from that date, and I'm rebuilding 766ec58b714cfdfad7c13cadd135a88b0688c0f7. Lessee what we see!

**Comment by semioticrobotic** [comment]
When you're pleased with a final draft, @whit537, just flag me and point me to the version that we'll publish. I'll need to get it proofed, prepared, and to you for final approval by tomorrow (going out of town after that).

**Comment by whit537** [comment]
> I'll need to get it proofed, prepared, and to you for final approval by tomorrow (going out of town after that).

Roger that! Thanks, @semioticrobotic! :-)

**Comment by whit537** [comment]
👍

![takes-1 0](https://cloud.githubusercontent.com/assets/134455/16816419/c732b884-490b-11e6-8fe4-af69e8368e04.png)

**Comment by whit537** [comment]
Alright, finished a pass through the conclusion.

@semioticrobotic If you want I can give you permissions on this Google Doc to edit it directly. Let me know an account to invite if so.

**Comment by whit537** [comment]
> We need to update all the links to remove the Medium redirects.

Done.

**Comment by whit537** [comment]
> just flag me and point me to the version that we'll publish

I don't see a good way to refer to a snapshot of a Google Doc, so here's the basic link again (also added to the description on this ticket):

https://docs.google.com/document/d/1EGHLGRGnbs6ppsUd91EGpNMivcq5koWF857HCRJt8iI/edit?usp=sharing

I suspect I'll revisit this again tomorrow morning, but I don't expect to make any more big changes. :)

**Comment by whit537** [comment]
>> Looks like I'm not allowed to upload my ODT file

Here's what I heard back from GitHub support:

> I can certainly add your request for ODT files to be added to list of supported file types.
>
I can't promise if or when we would implement but as a workaround you could add your file to a ZIP and upload the ZIP.
>
Hope this helps and please let me know if you need anything else!

**Comment by semioticrobotic** [comment]
Great! Thanks, all. Just a note that I've pulled the version currently in GDocs and am working with that as the canonical version.

**Comment by whit537** [comment]
@semioticrobotic Thanks for getting the post proofed and ready to go! I read through it [note: link received in private email] and made two changes, hopefully non-controversial:

- I corrected one obvious error ("MorningStar" to "Morning Star" in the second instance).
- I split the sentence beginning, "If you'd like to dig deeper," out into its own paragraph, as a compromise between attaching it to the last paragraph (original) and second-to-last paragraph (proofed).

Last request: **Can we change the title?** I'm not comfortable changing it without your permission, but it is currently:

- Does 'take-what-you-want' work for employee compensation?

This runs us afoul of [Betteridge's law of headlines](https://en.wikipedia.org/wiki/Betteridge%27s_law_of_headlines), wherein the answer to yes-no questions in headlines is assumed to be "no." How about one of these instead?

- 3 lessons from a 2-year 'take-what-you-want' experiment
- How Gratipay solved money & motivation in open source
- Mixing open source and money with 'take-what-you-want'

This last might be the strongest, because it echoes DHH's "[The perils of mixing open source and money](http://david.heinemeierhansson.com/2013/the-perils-of-mixing-open-source-and-money.html)." DHH painted a dire picture, and we are giving a concrete counter-example.

Thoughts?

**Comment by semioticrobotic** [comment]
@whit537 Our content manager has final say on all headline decisions, but I will certainly send these suggestions to her and see what we can do. If anything, we'll riff off them to generate something more appropriate than what we have there now. Thanks for catching and fixing those typos.

**Comment by whit537** [comment]
Sounds good, thanks @semioticrobotic.

P.S. She doesn't by chance have a GitHub account, does she? 😁

**Comment by semioticrobotic** [comment]
> She doesn't by chance have a GitHub account, does she?

I don't believe so, but I'll check!

**Comment by whit537** [comment]
She'd be welcome to join us here! :)

**Comment by whit537** [comment]
> This last might be the strongest, because it echoes DHH

On the other hand, we may decide it's better to avoid casting this too strongly as a direct response to DHH's post. We reference his post, but I think ours stands on its own.

**Comment by whit537** [comment]
Actually, now that I check I see it's been changed to "3 lessons from Gratipay's take-what-you-want compensation experiment," so I guess we're good! Thanks @semioticrobotic! :-)

**Comment by whit537** [comment]
We're live! 👍

https://opensource.com/open-organization/16/7/compensating-employees-letting-them-take-what-they-want

https://twitter.com/opensourceway/status/755367591741231104

Thanks for all your hard work on this, @semioticrobotic and OS.com team!

**Comment by semioticrobotic** [comment]
Woo hoo! Great job, @whit537. We're promoting via all our usual channels today.

**Comment by whit537** [comment]
@semioticrobotic How about a link from Part 1 to Part 2?

https://opensource.com/open-organization/16/5/employees-let-them-hire-themselves
https://opensource.com/open-organization/16/7/compensating-employees-letting-them-take-what-they-want

**Comment by semioticrobotic** [comment]
@whit537 Yes, for sure. Looks like you beat me to it. Great idea (one I should have thought of before publication).

**Comment by whit537** [comment]
> Looks like you beat me to it.

Hmm ... I'm seeing the second article under "Related Content" at the bottom, but I was thinking of something like an "**Update:**" after the "Stay tuned for Part 2!" (or maybe just link "Part 2"?). Are you seeing a link somewhere else that I'm not noticing?

**Comment by semioticrobotic** [comment]
@whit537 Ah! I mis-read your original message. Had the logic reversed. I'll get on that right away.

**Comment by whit537** [comment]
Failed to reach the [top ten](https://www.redhat.com/archives/osdc-list/2016-July/msg00004.html), as [before](https://github.com/gratipay/inside.gratipay.com/issues/551#issuecomment-221681728).

**Comment by semioticrobotic** [comment]
The editorial team included this story in our weekly newsletter, sent to more than 100,000 subscribers. I suspect that'll get more than a few extra eyes on it!

**Comment by whit537** [comment]
Thank you! 🙇 I actually noticed that in my email right before seeing the notification about your message here, and thought "Huh ... that's cool." :-)

![screen shot 2016-07-27 at 9 08 56 am](https://cloud.githubusercontent.com/assets/134455/17176275/de03ae00-53d9-11e6-9558-fcd5f6efb5d5.png)

**Comment by semioticrobotic** [comment]
~200 more people read the story yesterday!
