### ISSUE TITLE
protect the Gratipay brand

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#692]
One of the naivetes of Gittipay 1.0 was a desire not to legally enforce our brand. Here's the sort of mess that can lead to:

https://letsencrypt.org//2016/06/23/defending-our-brand.html

We should probably submit to this system.

**Comment by whit537** [comment]
> This is where protecting your trademark is essential. You are the one who creates the strategy for “Bar”, you’re the one who invests hours into quality assurance and testing, and you’re the one who’s taking on the risk by making a substantial investment in the product. Therefore, you are the only one who gets to create a product called “Bar”, assuming, of course, that you took the time to register the mark in the first place. It’s equally important to protect the mark of the open source platform, Foo. The last thing you want is some other company claiming that their version of “Foo” is “just like ‘Bar’”! Thus, it’s important that whoever controls the mark for “Foo”, whether it’s a software vendor or a vendor-neutral organization, also engages in vigorous defense of the trademarks.

https://www.linux.com/news/how-make-money-open-source-platforms-part-3-creating-product

**Comment by whit537** [comment]
+1 from @ShaneCurcuru at https://opensource.com/comment/138571#comment-138571:

> The brand is (for a short definition) what the world perceives as the product or organization's identity. It's how new users (and potential contributors of all sorts) find you, and it's the symbol everyone else associates with who you or your organization are.
>
>Trademarks are the legal instantiation of a brand. Trademark laws are both fairly complex, rely on tiny details of how your web pages are presented in the real world, and - on top of that - are widely misunderstood. More to the point, you generally can't share a trademark across organizations, because the entire point of a trademark is that consumers associate a *single* entity with the product they're buying or using.
>
>Obviously, it depends on each organization and their goals - and how the marketplace of potential competitors acts - if trademark law will actually matter in daily life for your project. Unfortunately, when trademark disputes do come up, they can be very messy, and can be hard for traditional open source projects (especially nonprofits) to fix once a problem comes up.
>
>And your example is a perfect one: Gratipay versus Liberapay - forks in code and business models, but different brands and trademarks. While the differences are obvious and intuitive for people working on these projects, the main difference to other humans is the world is the brand.

**Comment by whit537** [comment]
> We should probably submit to this system.

I'm more inclined to do so in this post-#118 world. Bad actors are real.

**Comment by ShaneCurcuru** [comment]
Let me know if there are ways I can help the legal governance of your project figure this out.  
When it comes to trademarks, the lawyers expect to see people listed as board directors or as officers of the corporation making the decisions and setting any policies.

**Comment by whit537** [comment]
@ShaneCurcuru Thanks for joining us here! @clone1018 and myself are the legal owners of Gratipay.

> [T]here are a bunch of fairly simple things you can do that give you decent insurance about protecting your trademark later. Picture it like insurance: you have to pay (a tiny bit - in project organization, not money) up front, for protection later.
>
> If you don't act at all to protect your trademarks now, *if* something comes up later, you'll be stuck. But with a little work beforehand, you have a reasonable ability later to *choose* if you want to defend the trademark or not.

Any links to share to existing documentation on this?

**Comment by ShaneCurcuru** [comment]
The Practical Trademark Law slides, and the ones from ApacheCon Seville:

http://shaneslides.com/

The ASF's own guidance to our projects about properly displaying their brands:

https://www.apache.org/foundation/marks/pmcs

The first two steps:
- Always use the trademark consistently on your site.
- Use the ™ symbol on the first and most prominent uses of your trademark on each major landing page.

My collected list of useful articles on the Apache site:

https://www.apache.org/foundation/marks/resources#other

Especially the FOSSMarks and Model Trademark Guidelines links.

Read up some, then email me and we can chat more if that will help.

**Comment by ShaneCurcuru** [comment]
@whit537 said:

> Bad actors are real

Absolutely true.  What isn't obvious is that there are more bad actors out there than you've ever heard about.  Many trademark issues in #opensource are solved privately, to allow everyone to save face - so for every case like you point to in #118, there are at least a half-dozen similar cases that never got **public** attention.

I don't worry about the kinda-bad actors who will correct behavior once they are contacted privately, and once you explain yes, FOSS projects can own their own trademarks.  I worry about the bad actors who either 1) keep changing a little, but keep pushing the boundaries, and 2) the true infringements from companies that simply don't care about you.

**Comment by whit537** [comment]
> Read up some, then email me and we can chat more if that will help.

Thanks @ShaneCurcuru, will do!
