### ISSUE TITLE
story: help Ludum Dare

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#693]
http://ludumdare.com/compo/2016/06/08/well-this-is-awkward-2/

Ludum Dare needs to be registered as charity and there is a problem handling donations from U.S. to Canada and paying taxes.

**Comment by whit537** [comment]
Thanks for sharing this with us, @techtonik. Closing this out, in the future I think the Core Radar could be a good place to share this kind of thing. :-)
