### ISSUE TITLE
participate in O'Reilly's Next:Economy

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#711]
October 10–11, 2016, San Francisco

> For the first time in generations, our children may be worse off than we are. Many point to technology as the culprit, arguing that AI and robotics will destroy far more jobs than they create. Are the prospects really that dark for our children and grandchildren, our businesses and our economy, our cities and our way of life?
>
**We have a choice: We can create a better future for all.**
>
At the Next:Economy Summit, business leaders, policy makers, and technologists will chart a course from the economy we experience today—full of wonders and horrors in equal measure—to a Next Economy that brings prosperity to all.

http://conferences.oreilly.com/nextcon/economy-us/

([h/t](https://medium.com/the-wtf-economy/machine-money-and-people-money-29b497eeb9d0))

**Comment by whit537** [comment]
$2500 to register (early bird). Let's see about speaking?

**Comment by whit537** [comment]
> @|timoreilly I've got some good stories to tell about @|Gratipay since you and I met at the first @|xoxo. https://opensource.com/open-organization/16/5/employees-let-them-hire-themselves for a taste.
>
> @|timoreilly Perhaps a good fit for the Next:Economy program? Who should I talk to?

https://twitter.com/whit537/status/752828171158900738

Let's start there. :-)

**Comment by whit537** [comment]
Early-bird ends on Friday. Let's see about ...

> Have a suggestion for a speaker or topic at Next:Economy?
Send an email to: suggestions@oreilly.com

http://conferences.oreilly.com/nextcon/economy-us/public/content/contact

**Comment by whit537** [comment]
Gosh, I can't quite bring myself to cold-email them. Feels too much like groveling. I think I'd rather pay to play. :-(

**Comment by whit537** [comment]
To: suggestions@oreilly.com
Subject: Gratipay a good fit for Next:Economy?
Self: brought. 😶

> Greetings!
>
Chad Whitacre here, founder of Gratipay (a payments startup and open organization).
>
Tim's piece on "[Machine Money and People Money](https://medium.com/the-wtf-economy/machine-money-and-people-money-29b497eeb9d0)" crossed my radar recently, and I found much to resonate with in it. In particular, his discussion of "the job" as an "artificial construct" reminds me of [a piece](https://opensource.com/open-organization/16/5/employees-let-them-hire-themselves) I published on OpenSource.com a couple months ago:
>>
Work is infinite. So why are jobs scarce? 
>>
Gratipay operates on the assumption that "jobs" are a mechanism for creating artificial scarcity, something imposed on the infinite abundance of available work in the world.
>
Obviously some overlap in thinking here! :-)
>
We published a follow-up last week, reporting on an experiment with "[take-what-you-want](https://opensource.com/open-organization/16/7/compensating-employees-letting-them-take-what-they-want)" compensation. In May, I participated in a panel [at OuiShare Fest](https://www.youtube.com/watch?v=JgynSbU0uOY) on related topics, and I'm also scheduled to speak about this [at Abstractions](http://abstractions.io/schedule/#session-full-73) coming up next month.
>
Would our "take-what-you-want" story, or some other aspect of Gratipay's work, be of interest to Next:Economy attendees?
>
P.S. Gratipay is an open company, so I'll need to at least summarize our private email conversation in [this public GitHub ticket](https://github.com/gratipay/inside.gratipay.com/issues/711), for the Gratipay community.

**Comment by techtonik** [comment]
With entry barrier being this high, it looks like a "white-collar" meeting with the subject "how can we save our money from AI". They say "We can create a better future for all.", but apparently they can not even bring people without $2500 - their children and people from countries without economics to their agenda.  

They want to believe they could solve it, but I the same old rusty train behind the fresh paint.

**Comment by techtonik** [comment]
With entry barrier being this high, it looks like a "white-collar" meeting with the subject "how can we save our money from AI". They say "We can create a better future for all.", but apparently they can not even bring people without $2500 - their children and people from countries without economics to their agenda.  

They want to believe they could solve it, but I see the same old rusty train behind the fresh paint.

**Comment by whit537** [comment]
Could be some truth to that, @techtonik. $2,500 is a lot of money for {us,me} right now. It's far from clear that this would be the best way for us to spend it.

**Comment by whit537** [comment]
Three nights in the conference hotel would add $1,200, with meals/drinks besides. This would be a $4,000+ expense.

**Comment by whit537** [comment]
From: O'Reilly Media

> Thank you for reaching out. Our schedule is full and we're currently not accepting any more speakers, but I will forward this to our speaker managers  in case something opens up.

**Comment by whit537** [comment]
> This would be a $4,000+ expense.

Plus a $400 ✈️ ticket. :)

**Comment by whit537** [comment]
I'm torn. Going to meetups and conferences has been an important source of traction for us. The formal program is less than half the story. The point of going to this conference is not to cosign on O'Reilly Media's marketing copy, it's to meet [these people](http://conferences.oreilly.com/nextcon/economy-us/public/content/2015-attendees). I [count](https://cloud.githubusercontent.com/assets/134455/17219528/b191a170-54b9-11e6-9456-d0ad7a9e2a4b.png) 400 attendees last year. I can ask how many again this year, but for now let's assume it'll be roughly the same.

The question is: who are we trying to meet right now, and will they be here?

**Comment by whit537** [comment]
> it looks like a "white-collar" meeting with the subject "how can we save our money from AI"

Skimming the list of last year's attendees, there's no doubt that they're pulling some powerful players ... Ev Williams, Yancey Strickler, Sebastian Thrun, Satya Nadella, etc. While it's somewhat daunting to encounter such high levels of influence, part of my understanding of Gratipay's identity is actually that we _belong_ here. Not because we're fully comfortable with how many companies and people might wear their power, but precisely because we want to influence the way that "the next economy" turns out. We have a lot to offer—the ladder of love, heart coins, gratitude, generosity, {pay,take}-what-you-want—and we should be equally comfortable sharing these gifts with both the powerful and the lowly.

Gratipay didn't fully align with the leftist rhetoric at #384 and #314, but I think it was good for us to be at those events, to make friends and share our story and ourselves. We won't be comfortable with all of the bluster at Next:Economy either, but I think that making relationships in this scene could be something Gratipay wants to do. We're not going to see any sort of meaningful chunk of the world's wealth start to move through Gratipay if we're afraid or ideologically opposed to talking to the people who presently control that wealth.

**Comment by mattbk** [comment]
> Going to meetups and conferences has been an important source of traction for us.

Can that be quantified?

**Comment by whit537** [comment]
> The estimated attendance is 700-800 this year.

We shouldn't expect the specific folks who were there last year to be there again this year, of course.

**Comment by whit537** [comment]
> Can that be quantified?

I only have anecdotes at the moment. 😞 

- Back in [the day](https://gratipay.news/gittip-year-one-f1217a9f0bf0), we got our very first burst of activity through Jordan Messina, Steve Klabnik, and others from the local Pgh tech scene.
- Eric Holscher (Read the Docs) caught the vision initially at XOXO 2012 and various PyCons.
- Other PyCon connections include Mike Bayer ([SQLAlchemy](https://gratipay.com/sqlalchemy/)) and the [Pylons](https://gratipay.com/pylonsproject/) crew.
- More recently, our connection with Nathan Schneider ([IoO](https://gratipay.com/internet-of-ownership/)) is due directly to #384 and #314. Also ran into [Inventaire.io](https://gratipay.com/inventaire-io/) at #314.

**Comment by whit537** [comment]
I mean, what we want to get to is companies giving money to open-source projects through Gratipay. Right? We need to a) build product, and b) sell. Is Next:Economy a good place to find people who are decision makers at companies who have money to spend on open source?

**Comment by whit537** [comment]
> Is Next:Economy a good place to find people who are decision makers at companies who have money to spend on open source?

San Francisco certainly is, at any rate.

Another second question: Can we have product far enough along by October? What will we have to sell?

**Comment by whit537** [comment]
> And the way you stay on the right path in the early stages of a startup is to build stuff and talk to users. And nothing else.
>
**2. Stay focused.**

http://themacro.com/articles/2016/06/how-not-to-fail/

**Comment by whit537** [comment]
Alright, pulling the plug on this. Maybe next year.

For the remainder of this year, let's keep up the [product-building momentum](https://github.com/gratipay/gratipay.com/issues/3994)!
