### ISSUE TITLE
onboard @nashe

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#712]
https://github.com/gratipay/gratipay.com/issues/4081
https://github.com/gratipay/inside.gratipay.com/pull/134#issuecomment-231973825
https://github.com/gratipay/inside.gratipay.com/issues/704#issuecomment-232007397

> Do you have any wishes actually related to the translation process? Like more documentation, automation…
> 
> I'm somewhat interested by security-related stuff too, since I'm working in this area. 
> I'll try to catch you on IRC one of these days, so we can talk about this :-)

**Comment by whit537** [comment]
> Do you have any wishes actually related to the translation process?

@nashe Mostly I want to make sure we're paying attention to activity on Transifex and responding to work from translators in a timely fashion. I have a nagging sense that our translators are second-class citizens around here, partly because we're so GitHub-centric. I want to make sure our translators are communicating with each other and with the rest of us effectively.

> I'm somewhat interested by security-related stuff too, since I'm working in this area.

Nice! We could sure use help there, as well; here's [our docs](http://inside.gratipay.com/howto/handle-security-issues). @TheHmadQureshi has been helping with triage in HackerOne. Are you familiar with HackerOne? Where do you see yourself contributing security-wise? Can you help us actually fix some of the issues piling up on our security radar (#705)? :-)

> I'll try to catch you on IRC one of these days, so we can talk about this :-)

I'm actually not using IRC right now. Can we talk here on GitHub? :)

**Comment by whit537** [comment]
Case in point: I just noticed that we have "7 issues" ... questions about translations, some of which appear to be [quite old](https://www.transifex.com/gratipay/gratipay/translate/#it/$/38680518?issue=yes). :-(

![screen shot 2016-07-12 at 8 41 51 am](https://cloud.githubusercontent.com/assets/134455/16767257/93d7b26e-480c-11e6-8753-46ad6c4db8db.png)

We need someone to stay on top of these kinds of things in Transifex. Does that sound like a good fit for you, @nashe?

**Comment by whit537** [comment]
@nashe I've made you an administrator of the Gratipay org on Transifex.

**Comment by whit537** [comment]
Wanna answer those 7 issues? :-)

**Comment by nashe** [comment]
> @nashe Mostly I want to make sure we're paying attention to activity on Transifex and responding to work from translators in a timely fashion. I have a nagging sense that our translators are second-class citizens around here, partly because we're so GitHub-centric. I want to make sure our translators are communicating with each other and with the rest of us effectively.

It seems to be the case for the all projects I've been translating for. Let's try to figure a way to improve this relationship. Transifex seems to offer inter-teams forums and public announcements, it may be a way to improve it!

> Nice! We could sure use help there, as well; here's our docs. @TheHmadQureshi has been helping with triage in HackerOne. Are you familiar with HackerOne? Where do you see yourself contributing security-wise? Can you help us actually fix some of the issues piling up on our security radar (#705)? :-)

Not especially with the HackerOne UI, but I'm following what's happening on this platform (though [@disclosedh1](https://twitter.com/disclosedh1)). I may try to do some triage, depend of how much free time I have. But I'll definitely interest me. Regarding the issues, same thing, I'll take a look :-)

> We need someone to stay on top of these kinds of things in Transifex. Does that sound like a good fit for you, @nashe? 

Sure! I plan to improve the `inside.gratipay.com` page related to translation in order to explain how to find the current context (spoiler: using the "Details" tab + Github).

> Wanna answer those 7 issues? :-)

Yep \o

**Comment by whit537** [comment]
> Let's try to figure a way to improve this relationship.

I think having someone take responsibility for it will go a long way. @mattbk has been doing a great job staying on top of customer support (Freshdesk) and team review. @TheHmadQureshi has been helping out with security triage (HackerOne). We need someone to do the same for translations, to act as a bridge between Transifex and GitHub. Seems like you're comfortable in both! :-)

> I may try to do some triage,

Cool. I've sent you an invite to our HackerOne program so you can browse our security queue.

> Yep \o

💃

**Comment by nashe** [comment]
> Cool. I've sent you an invite to our HackerOne program so you can browse our security queue.

Can you send me another one? I had to create a new account to redeem it and it's now giving me a "Page not found".

**Comment by whit537** [comment]
Done!

**Comment by nashe** [comment]
> You're now part of team Gratipay.

Sounds like it worked 👍

**Comment by nashe** [comment]
How are you handling the H1 reports? Should we only triage it and leave the resolution/closing stuff for you? (eg. [#136720](https://hackerone.com/reports/136720) [has been resolved](https://github.com/gratipay/grtp.co/commit/34e259a0f8401e4d9940d3cb8c3514f4416ea417) but forgot).

**Comment by whit537** [comment]
> How are you handling the H1 reports? Should we only triage them and leave the resolution/closing stuff for you?

I'm happy for others to move H1 reports through the workflow, I don't need to be the one to do it. We just may need to evolve the [docs](http://inside.gratipay.com/howto/handle-security-issues) to make sure we're all on the same page. :)

> (e.g. #136720 has been resolved but forgot)

@nashe 136720 is about error pages, not the `Server` header.

**Comment by nashe** [comment]
> @nashe 136720 is about error pages, not the Server header.

You made me doubt, so I checked the documentation and it appears to be the same configuration directive for the two, cf. http://nginx.org/en/docs/http/ngx_http_core_module.html#server_tokens: 
> Enables or disables emitting nginx version in error messages and in the “Server” response header field.

So you fixed it without willing to :^) 

If you have some time, can you review https://github.com/gratipay/grtp.co/pull/141? You'll be able to close another H1 ticket at once 👍

**Comment by whit537** [comment]
May I add you as a collaborator on GitHub? We prefer to make PRs from topic branches in the same repo rather than from personal forks, so that multiple people can commit to the same PR.

**Comment by nashe** [comment]
You can :-)

**Comment by whit537** [comment]
Invite sent! I've added you to the @gratipay/gratipay and @gratipay/security teams.

**Comment by nashe** [comment]
Aaand accepted, thanks!

**Comment by whit537** [comment]
Welcome aboard! :-)

**Comment by whit537** [comment]
Picking up from https://github.com/gratipay/grtp.co/pull/141#issuecomment-232102911 ...

> I can't close the related report

I double-checked permissions, and you should be able to. If you're still can't, can you contact support@hackerone?

![screen shot 2016-07-12 at 1 52 14 pm](https://cloud.githubusercontent.com/assets/134455/16777535/edc6580e-4837-11e6-8740-cf499d2a1498.png)

**Comment by nashe** [comment]
It was not displayed inside the little dropdown… it's now the case after logout && login. Weird. Thanks for the double-check!

**Comment by whit537** [comment]
@nashe Do you use Twitter? If so, what's your handle? And may I thank you there? :)

**Comment by nashe** [comment]
I'm not using Twitter atm, sorry!

**Comment by whit537** [comment]
@nashe No worries! Just thought I'd ask. :-)

**Comment by nashe** [comment]
@whit537: Just to know, in which timezone are you?

**Comment by whit537** [comment]
@nashe UTC-4 (US/Eastern, Pittsburgh :)

You're in Europe, ya?

**Comment by nashe** [comment]
@whit537 Yep, Berlin atm.

**Comment by whit537** [comment]
@nashe My primary availability for Gratipay work is Wednesday and Thursday from 9am to 5pm local time, and often Tuesday as well.

**Comment by nashe** [comment]
@whit537 It's nice to know, thanks ;-)

**Comment by whit537** [comment]
:)

**Comment by whit537** [comment]
@nashe Re: [118699](https://hackerone.com/reports/118699), our habit is to not use "Team only" comments, because we want to be able to publish the entire record when we disclose. All comments, including severity discussions, should be posted to "All participants."

**Comment by nashe** [comment]
Noted, I'll make it public next time 😭

**Comment by whit537** [comment]
Thanks. :)

**Comment by nashe** [comment]
What's the goal of a participant's`is_free_rider` attribute? I'm saw something like "can use Gratipay for free" but it's not making much more sense to me.

**Comment by whit537** [comment]
[Free riders](https://en.wikipedia.org/wiki/Free_rider_problem) are those who benefit without paying. In our case, the attribute refers to those who have clicked the "No thanks" link on our global call to action, explicitly opting out of supporting Gratipay.

![screen shot 2016-07-21 at 9 52 11 pm](https://cloud.githubusercontent.com/assets/134455/17044360/687681ee-4f8d-11e6-9eee-8141620754f0.png)

**Comment by nashe** [comment]
Thanks :)

**Comment by nashe** [comment]
@whit537: how is assets.gratipay.com working? Same question for downloads.gratipay.com. It seems to be on Heroku but I can't find any other information about it.

**Comment by nashe** [comment]
(and for the record, I just moved to Paris for some years, if somebody is around and wants to grab a coffee!)

**Comment by whit537** [comment]
> I just moved to Paris for some years

Ah, oui ! Tres bien ! Peut-être que je vais vous trouver l'année prochaine ? ;-)

> how is assets.gratipay.com working?

Hmm ... we should document this somewhere (maybe on gratipay.rtfd.io?). Both `assets.` and `downloads.` are hosted by MaxCDN. The former is a so-called "pull zone", the latter a "push zone." `assets.` proxies through to https://gratipay.com/assets/. Does that get you pointed in the right direction, at least?

**Comment by Changaco** [comment]
@whit537 Do you mean you may be going to OuiShare Fest again next year?

@nashe I rarely go to Paris, but next time I do maybe we can meet. Also if you're ever in Normandy you're welcome to drop by. ;-)

**Comment by nashe** [comment]
> Ah, oui ! Tres bien ! Peut-être que je vais vous trouver l'année prochaine ? ;-)

I hope so! I guess that OuiShare Fest may be one very interesting place to meet—I never attended to this conference before.

@Changaco: Just drop me a line on this issue or by email and it'll be a pleasure! Lower or Upper Normandy? ;-)

**Comment by whit537** [comment]
> Do you mean you may be going to OuiShare Fest again next year?

Too soon to tell, but I haven't ruled it out! :-)

**Comment by Changaco** [comment]
> Lower or Upper Normandy? ;-)

Well, officially they've been reunited. ;-) Where I am specifically is (sometimes) called *Suisse Normande* ([Norman Switzerland](https://en.wikipedia.org/wiki/Norman_Switzerland)).

**Comment by whit537** [comment]
Seems like you're pretty well onboarded by this point, eh @nashe? We good to close here? :)

**Comment by nashe** [comment]
Can I talk you in private, @whit537? Like email, webrtc… the one you prefer :-)

**Comment by whit537** [comment]
@nashe Sure thing, let's start with email (chad@zetaweb.com), and we can schedule a face-to-face from there, ya?

**Comment by whit537** [comment]
For the record, @nashe has had to back away from Gratipay work for the time being, due to other commitments. I am closing this ticket, therefore ... perhaps we'll be able to reopen it someday. 😁

Thanks for all your efforts, @nashe! Best wishes! :-)

!m @nashe 💃

**Comment by whit537** [comment]
P.S. @nashe has removed himself from the Gratipay orgs on HackerOne and GitHub, and I've removed him from the Gratipay team on Gratipay.

**Comment by whit537** [comment]
Now removed from Transifex as well (https://github.com/gratipay/inside.gratipay.com/issues/189#issuecomment-262289034).

**Comment by nashe** [comment]
> For the record, @nashe has had to back away from Gratipay work for the time being, due to other commitments. I am closing this ticket, therefore ... perhaps we'll be able to reopen it someday. 😁

Aloha @whit537! How about opening this issue again? 💃
