### ISSUE TITLE
Gratipay code hosting currently fails GNU Ethical Repository Criteria Evaluations

### ISSUE THREAD

**Issue by sampablokuper** [gratipay/inside.gratipay.com#724]
Please could Gratipay migrate its entire code-base and bug tracker to a code hosting and bug-tracking service that does not *fail* the [GNU Ethical Repository Criteria Evaluations](https://www.fsf.org/news/gnu-releases-ethical-evaluations-of-code-hosting-services)?

GitLab is probably a reasonable compromise:

- it *[passes](https://www.gnu.org/software/repo-criteria-evaluation.html)* (albeit imperfectly) the GNU Ethical Repository Criteria;
- it supports Git as a first-class DVCS;
- its interface is quite similar to GitHub's;
- it has a large and active user base.

Other possible hosts, albeit lacking some of those features, so probably not currently a great fit for Gratipay: 

- [NotABug](https://notabug.org)
- [GNU Savannah](https://savannah.nongnu.org/)

Thanks!

**Comment by whit537** [comment]
Folding this into https://github.com/gratipay/inside.gratipay.com/issues/446.
