### ISSUE TITLE
check in with @nayafia

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#732]
@nayafia has finished up her report on [funding digital infrastructure](www.fordfoundation.org/library/reports-and-studies/roads-and-bridges-the-unseen-labor-behind-our-digital-infrastructure/). It is a major contribution, nine months in the making, that translates the conversation about FLOSS sustainability into the language of decision makers in philanthropy, government, and business. I reached out for a [call](https://www.youtube.com/watch?v=CXPDtPhnhus) (#471) just after she initially [announced](https://medium.com/@nayafia/how-i-stumbled-upon-the-internet-s-biggest-blind-spot-b9aa23618c58) the project (and I was tickled to hear at the start of the call that, "I think you were probably the first person I ever [talked to](https://www.youtube.com/watch?v=tNhncmK5r2U) about this stuff[.] It got the wheels turning" :). Towards the end of our call, I made [an offer](https://www.youtube.com/watch?v=CXPDtPhnhus#t=54m46s):

> Gratipay is here, and it's something that I think could help the open source community, and—if you want to—I offer it to you as something to use in your quest to fund open source infrastructure.

She replied that she _is_ thinking of her project as a quest and so was appreciative of the gift, and then we started talking a bit about Gratipay as a platform for individual crowdfunding vs. corporate sponsorship before our time ran out.

When I saw her report, I [reached out](https://twitter.com/whit537/status/753933383894388741) on Twitter:

>> Seems like your quest is proceeding apace. Up for another check-in soon? :-)
>
> yes! Might be an email check-in as I'm bouncing about but yes :)

... and so here we are! :D

On this ticket I hope to a) digest "Roads and Bridges", and b) pick up with @nayafia where we left off at the end of our last call: what do we need to do to (once again) make Gratipay a great place for companies to support open source? How can we jumpstart this thing again? :)

**Comment by whit537** [comment]
First ... errata! 💃

Here are the typos I found while reading "Roads and Bridges" (and here's the [version](https://github.com/gratipay/inside.gratipay.com/files/367782/roads-and-bridges-the-unseen-labor-behind-our-digital-infrastructure.pdf) I have). Most of these are obviously errors, though a few may be open to interpretation.

| page | current | proposed | notes |
|----:|:---------|:----------|:---------|
|  21 | Databases: | **Databases:** | should be bold |
|  39 | prevented funding infrastructure from being funded | prevented infrastructure from being funded | |
|  83 | endless stream out people | endless stream out [sic] people | |
| 103 | notes that that the contributor | notes that the contributor | |
| 114 | embracing open source as way to build trust | embracing open source as a way to build trust | |
| 115 | to work on full-time on an open source project | to work full-time on an open source project | |
| 119 | Mozilla Open Source Support Program | Mozilla Open Source Support program | |
| 121 | the VP engineering | the engineering VP | |
| 121 | a $80M 'Slack fund' | an $80M 'Slack Fund' | |
| 130 | to aggregate data open source projects | to aggregate data on open source projects | |
| 132 | growing numbers of just new developers | growing numbers of not just new developers | |
| 136 | that statement that has become canon | that statement has become canon | |
| 140 | gratis - 'free' | gratis—'free' | em dash instead of en dash |
| 140 | and Free Software Foundation | and the Free Software Foundation | |

Two other issues that are more subjective:

On p. 52:

> The remainder of this paper will focus on how and why open source contributors maintain projects of massive scale and impact, and why it matters to all of us.

Here, "this paper" seems to refer only to the rest of the _section_, pp. 53-57. Elsewhere (e.g., on p. 32), the scope of "this paper" is the entire report.

Lastly, it's a stretch to call Mailman a "company" on p. 94. It's an open source project with basically a single maintainer (Barry Warsaw), fiscally sponsored by the FSF. In fact, it's a fantastic example of a digital infrastructure project that is "trapped somewhere in the middle: large enough to require significant maintenance, but not quite so large that corporations are clamoring to offer support" (p. 63).

**Comment by whit537** [comment]
Now, as to the applicability of the paper for Gratipay, I think the main message is clear: keep doing what we're doing. [Stay focused](http://themacro.com/articles/2016/06/how-not-to-fail/). Basically we are looking to productize PHK's [VML](http://phk.freebsd.dk/VML/) (first I've seen of this, and it looks really interesting for us; [noted](https://github.com/gratipay/gratipay.com/issues/1199#issuecomment-233178150)). This fits under "Improving relationships between projects and external stakeholders" (pp. 133-134) in @nayafia's concluding chapter:

> Companies can also provide financial support for projects, but sometimes find it difficult to figure out how to structure their sponsorship. Creating sponsorship budgets for engineering departments or employees, or creating documents to make it easy for projects to "invoice" companies, could increase financial contributions to open source. [p. 134]

That's exactly where we're headed, per the roadmap on our product radar (#732): step 3.ii is "[Solve Corporate Sponsorship of Open-Source](https://github.com/gratipay/gratipay.com/milestone/19)". Of course, we've got the 🐔 and 🐣 problem of _also_ being an underfunded open source project ourselves. :)

Perhaps @nayafia's report will help us in approaching Mozilla (#637)?

**Comment by whit537** [comment]
Actually ...

@nayafia Would you be willing to endorse us for a MOSS [Mission Partners](https://wiki.mozilla.org/MOSS/Mission_Partners) grant? :)

The ask is for "a paragraph or two on why supporting [Gratipay's] work via this grant is a great idea."

**Comment by whit537** [comment]
> I think the main message is clear: keep doing what we're doing.

I had [occasion](https://github.com/gratipay/gratipay.com/issues/1199#issuecomment-235269944) to email w/ PHK. After asking about the VML, I mentioned this [quote](http://queue.acm.org/detail.cfm?id=2636165): "This is the funding model I want to 'sell' for other FOSS projects, because it works"; and offered, "Us, too! How can we help?" His reply? "By going out and doing it!" 💃 👍

@nayafia I'm going to go ahead and close this ticket. You're busy, and Gratipay has plenty to get done as well. Perhaps it'll make sense to reconnect when Gratipay is further along on productizing the VML. :)

Thank you for _Roads and Bridges_! :-)

**Comment by nayafia** [comment]
@whit537 hey! I'm sorry I've been so unresponsive. I've been traveling most of the past two weeks while also starting a new project, my inbox has been flooded from the report, and email + Twitter as communication channels get prioritized over GitHub Issues. :)

I'm not sure whether there was a clear question or call-to-action for me here. I'm supportive of all experiments around open source sustainability, but I'm sure I've also mentioned my skepticism that crowdfunded sponsorship can significantly move the needle. That being said, it still serves an important place in the ecosystem, filling in gaps where income needs are less dire, or crowdfunding is more about community engagement than $$.

Lastly, thank you so much for reading the report with a sharp eye to detail! I really appreciate your support thus far, and you did indeed first get the wheels turning, so I am always thankful for that. <3

**Comment by whit537** [comment]
No worries, @nayafia, my bad! I had a hunch that email might not be the best channel, on top of everything else. :-)

I've private-emailed you to pick up the thread [above](https://github.com/gratipay/inside.gratipay.com/issues/732#issuecomment-233180233) about possibly working with us on a MOSS application (#637).
