### ISSUE TITLE
apply for Stripe Open-Source Retreat

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#733]
> We’ll host three to four developers at our office in SF for three months to work full-time on an open-source project. While we’ll ask that they give a couple of internal tech talks over the course of the program, the grant itself is no-strings-attached.

https://stripe.com/blog/open-source-retreat-2016

Let's keep an eye out for the next iteration of this (assuming they run one).

**Comment by techtonik** [comment]
I'll be happy to participate in one.
