### ISSUE TITLE
investigate PayPal denials

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#736]
We've had a regular trickle of denials for our masspay payouts—shooting from the hip, 10%. Now with  #734 we're seeing 50%! 🙀

https://gratipay.freshdesk.com/helpdesk/tickets/5353

![screen shot 2016-07-22 at 9 37 13 am](https://cloud.githubusercontent.com/assets/134455/17058820/1fad47aa-4ff0-11e6-8844-8b4a5b996cd1.png)

What the heck is _that_ about?

**Comment by whit537** [comment]
blip

**Comment by rohitpaulk** [comment]
Hmm, do we send out emails to users when this happens?

**Comment by whit537** [comment]
Back down to [nine](https://gratipay.freshdesk.com/helpdesk/tickets/5397) out of 67 (13.4%) this week. Are we resending to those folks?

**Comment by whit537** [comment]
> Hmm, do we send out emails to users when this happens?

I'm not sure that we do. We should if we don't ... new ticket?

**Comment by whit537** [comment]
https://www.paypal.com/us/cgi-bin/webscr?cmd=_history-details&info=pXx1llQAxA8DhXVnzmdd75PnXTn0j7WxghhBYvBQrfuPE2gYMb1FlNU_ZMi

> Your payment was returned because it was not claimed by the recipient for 30 days. Here are some possible reasons that the payment was not accepted: The payment was sent to the wrong email address. The recipient didn't accept the payment, or the recipient's PayPal account is not confirmed. Contact the recipient to confirm you have the correct email address.

![screen shot 2016-09-29 at 11 55 49 am](https://cloud.githubusercontent.com/assets/134455/18961658/bd801f12-863b-11e6-8a68-fa583c7a4df4.png)

**Comment by whit537** [comment]
> (The recipient of this payment is **Unregistered**)

**Comment by whit537** [comment]
See also: https://github.com/gratipay/gratipay.com/issues/4136.

**Comment by whit537** [comment]
Bringing over from #674:

>E.g. from #673:
>
![screen shot 2016-06-16 at 9 14 21 am](https://cloud.githubusercontent.com/assets/134455/16117953/c4e65a8c-33a2-11e6-8cbf-7e0a0fdba166.png)
>
Makes me nervous. Are we accounting for this properly?

**Comment by whit537** [comment]
From a customer:

> PayPal decided to lump [us] in with software sharing sites awhile back and decided to cut ties. That means the PayPal bits stopped working, and that's how we were receiving payouts from Gratipay.

In other words, this leads into https://github.com/gratipay/inside.gratipay.com/issues/305. 😞

**Comment by whit537** [comment]
> Are we accounting for this properly?

Yes, afaict. After a failed payout the balance stays the same and carries forward. E.g.:

![screen shot 2016-11-21 at 2 54 29 pm](https://cloud.githubusercontent.com/assets/134455/20498271/7d76a79a-affa-11e6-8bf9-18b96507ac8a.png)
