### ISSUE TITLE
fold Missive and blog into Medium

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#74]
I propose that we fold the [Missive](http://tinyletter.com/gittip) and the [blog](http://blog.gittip.com/) into the [Medium collection](https://medium.com/building-gittip). The reason is to further reduce the number of sources of truth, so that we all have an easier time keeping up.

Medium is a blogging platform with an incredible user experience. It's a delight to use and an inspiration. The big downside for us is that we can't co-brand it. We can only use it on medium.com with their branding and visual design.

The Missive was an attempt on my part to communicate at a higher level on a weekly basis with people building Gittip. The problem with it is that I become a bottleneck and it became a chore for me. I don't want to be the bottleneck and I don't want to do busywork if I can help it. With a Medium "[collection](https://medium.com/help-center/collections-d23372baede0)" we can have multiple authors from across the Gittip community writing higher-level analysis. Using a Medium collection is a lot like a "planet" in an RSS-aggregated blog context.

I see our blog as a perfunctory PR organ. What if we just blogged everything on Medium? Why not?

**Comment by whit537** [comment]
This is done: http://blog.gittip.com/post/96092973886/new-name-new-blog/.

**Comment by patcon** [comment]
I realize the gittip.com blog is retired, but should the CSS be gone?

**Comment by whit537** [comment]
I don't believe the CSS is gone, just greatly simplified. If you want to make a PR the repo is https://github.com/gratipay/blog.gittip.com (straight GH pages site now).

**Comment by patcon** [comment]
Gotcha. Good as-is if intentional :+1:
