### ISSUE TITLE
decide on initial available

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#747]
Now that [bringing back](https://github.com/gratipay/gratipay.com/issues/3994) team takes for Team Gratipay is [nearing reality](https://github.com/gratipay/gratipay.com/pull/4077), we need to decide what to set our weekly _available_ at. It should be high enough to be interesting, but low enough to a) let enough fall to Gratipay, LLC to cover our bills, and b) not run the risk of outpacing our [weekly income](https://gratipay.com/Gratipay/receiving/) (NB: `500` for anon 😕).

![screen shot 2016-07-28 at 5 53 35 pm](https://cloud.githubusercontent.com/assets/134455/17230791/3ed87338-54ec-11e6-9dc3-fa62631a204c.png)

**Comment by whit537** [comment]
Our bills are roughly $500 per month ~= $115 per week, and our income is roughly $200/wk ~= $850/mo. How about we start out with $50/wk available for payouts? That should give us a safe cushion to pay our bills and keep saving a little, while also letting us TASTE THE GLORYYYYYYYYYYY!!!!!!!!

**Comment by mattbk** [comment]
As a table so I understand. Looks good to me.

Account | Week | Month
---|---|---
Income | $200 | $850
Expense | $115 | $500
Leftover | $85 | $350
Keep | $35 | $140
Available | $50 | $200

**Comment by kaguillera** [comment]
👍

**Comment by whit537** [comment]
Last call here. Current proposal is that we start with $50 available for Team @Gratipay ... starting this week! 😳

**Comment by whit537** [comment]
Okay! $50 it is! 💃

**Comment by whit537** [comment]
```
gratipay::MAROON=> select id, slug, available from teams where slug='Gratipay';
┌────┬──────────┬───────────┐
│ id │   slug   │ available │
├────┼──────────┼───────────┤
│  1 │ Gratipay │      0.00 │
└────┴──────────┴───────────┘
(1 row)

gratipay::MAROON=> update teams set available=50 where id=1;
UPDATE 1
gratipay::MAROON=> select id, slug, available from teams where slug='Gratipay';
┌────┬──────────┬───────────┐
│ id │   slug   │ available │
├────┼──────────┼───────────┤
│  1 │ Gratipay │     50.00 │
└────┴──────────┴───────────┘
(1 row)

gratipay::MAROON=>
```

https://gratipay.com/Gratipay/distributing/

![screen shot 2016-08-31 at 12 14 00 pm](https://cloud.githubusercontent.com/assets/134455/18136920/78199efe-6f74-11e6-9b4c-3aa5fba0d831.png)
