### ISSUE TITLE
go to All Things Open

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#757]
Reticketed from #672.

> A CONFERENCE EXPLORING OPEN SOURCE, OPEN TECH, AND THE OPEN WEB IN THE ENTERPRISE

https://allthingsopen.org/

October 26-27 in Raleigh. Speaker line-up seems full already, but early bird is only $149 (ends August 19th).

**Comment by whit537** [comment]
Pulling out. I want to build stuff! Going to Abstractions (#506) was good, but a) it was way cheaper, since I spoke and it was in Pittsburgh, and b) it took precious time. I'm already loading myself up with #672. I don't want to lose a week or more in October to another conference. We've got Platform Cooperativism (#756) the month after, which I think I'd be more inclined to go to to alternate FLOSS and New Economy. But even there I might rather stay home and hack, unless I'm invited to speak.

**Comment by whit537** [comment]
Okay! Reopening in light of an invitation in private email from @semioticrobotic and @jhibbets  to participate in the [All Things Open](https://allthingsopen.org/) conference (thank you both for reaching out, and for the private conversation leading back to this ticket). In addition to a gracious offer from Red Hat to help with registration and travel costs, the invitation also includes:

- participation in an Open Organization Ambassadors (#672) event the day before the conference, and
- a five-minute lightning talk about open leadership on the main stage ([looks like](https://allthingsopen.org/schedule/) Thursday at 12:30pm).

This looks a lot like a slam dunk 🏀  from a community and marketing point of view, but let's let this mellow at least through the ([long in the U.S.A.](https://en.wikipedia.org/wiki/Labor_Day)) weekend to make sure we're comfortable giving up the time otherwise spent on shipping product.

Thanks again, @semioticrobotic @jhibbets! Let's circle back here next week!

**Comment by semioticrobotic** [comment]
You bet, @whit537. Looking forward to the conversation.

**Comment by whit537** [comment]
Alright, haven't heard any pushback on this one. Let's go for it!

**Comment by whit537** [comment]
I've confirmed with @jhibbets in private email that I'm interested in participating in the lightning talks. Topic TBD ...

> I was hoping you could talk about working in the open with your experience at Gratipay. I'm open to suggestions on what your talk could be about, but it must be in the realm of open source in order to fit with our content. I want to give you some flexibility, because I know you've got a few different directions you could take this if you want to have fun with us on the main stage.
>
[...] If you are able to participate, my plan is to collect title talks and bios soon. I would need to collect slides by October 14. Also, our plan is to record the talks and publish them on Opensource.com after the conference.

**Comment by whit537** [comment]
Reticketed the lightning talk as https://github.com/whit537/openorg/issues/6.

**Comment by jhibbets** [comment]
Main stage aspect ration = 16:9
Jason

**Comment by jhibbets** [comment]
Hello lightning talks speakers!

I have a few important details for you, please let me know if you have
any questions between now and then. Thanks again for speaking.

1) In order to promote your talk and add it to the conference schedule,
please complete this short form by October 7

https://docs.google.com/forms/d/e/1FAIpQLSdvuPSxS0-cqAQ9xSUqRUHS58svZT_o-0BqYpgiiAUiFRYhGg/viewform

2) We have a very tight schedule on October 27. Talks will be strictly
limited to 5 minutes. We have 1 minute between talks to transition. In
order to help us stay on time, we ask that all speakers arrive at the
front of the main stage at 12:15 pm. We will have reserved seating for
all of you. We will also have a visible timer for you. (Grab a boxed
lunch and join us in the main ballrooms.)

3) Slides are due on or before October 17. You can submit them to me or
add them to the following Dropbox:
https://www.dropbox.com/home/Events/All%20Things%20Open%202016

Submit your slides in PDF format so we don't lose any formatting you
require.

Pro Tips:
- Include your Twitter handle and the conference hashtag, #ATO2016 on
every slide

4) Practice, practice, practice. For those of you that have experience
with lightning talks, you know these 5 minutes will go by fast. Be sure
to get a couple of dry-runs under your belt.

5) Talks will be recorded and Opensource.com will publish them on our
YouTube channel under a Creative Commons license.

We're excited!
Jason

**Comment by whit537** [comment]
There was a semi truck on fire on the highway this morning. Consequently, I was an hour late getting to the airport, and missed my flight. I'm on standby for another flight, about to find out if I get on. If so I may make Raleigh before dinner. Otherwise it's looking like I won't get there until almost 10pm. Airport wifi is spotty but I should be able to hack here for the afternoon if need be.

**Comment by semioticrobotic** [comment]
No! Sorry to hear that, Chad. Stay safe and try to relax (if that's possible at the airport!). Keep us posted.

**Comment by whit537** [comment]
Thanks @semioticrobotic. What's more, with the Steelers game yesterday, flights are very full leaving Pittsburgh. I was not able to get on the flight I was on standby for. I called the travel agency, and I believe they have me booked on a flight later this evening. Unfortunately, that means I'll have to miss the kick-off dinner tonight. Please convey my regrets. 😞 

Fingers crossed, I will be in the Red Hat Tower lobby at 11:30 tomorrow morning for our Ambassadors session. For now I am posted up at the far end of the terminal with a sandwich and uncongested wifi. Time to get some work done! See you tomorrow!

**Comment by whit537** [comment]
Okay! I have my new boarding passes, which put me in Raleigh at 9:20. 👍

**Comment by techtonik** [comment]
@whit537 what talks do you plan to attend?

**Comment by whit537** [comment]
Made it! O.o

**Comment by whit537** [comment]
@techtonik The six I have pre-picked out are:

https://allthingsopen.org/talk/morning-keynotes/
https://allthingsopen.org/talk/open-source-is-people/
https://allthingsopen.org/talk/panel-discussion-how-to-be-more-open-collaborative-and-inclusive-at-work/
https://allthingsopen.org/talk/civic-hacking-201-successful-techniques-for-civic-tech/
https://allthingsopen.org/talk/freeloaders-are-essential-and-other-open-source-product-truths/
https://allthingsopen.org/talk/designing-for-participation/

**Comment by jhibbets** [comment]
Really looking forward to this one: https://allthingsopen.org/
talk/civic-hacking-201-successful-techniques-for-civic-tech/ ;) Guess I
better get my slides done!

**Comment by jhibbets** [comment]
FYI - ground transportation has all your updated details for pick-up.

**Comment by whit537** [comment]
Interesting day today at #ATO2016! Quite stimulating. ☕️  💡 

Today we had the [Open Organization Ambassadors](https://opensource.com/open-organization/resources/meet-ambassadors) (OOA) meeting. The conference itself is tomorrow and the day after.

The Open Organization Ambassadors are a group assembled to discuss and further the ideas and values set forth in Red Hat CEO Jim Whitehurst's 2015 book, [_The Open Organization_](https://www.amazon.com/-/dp/1625275277). There were ten of us in the meeting today, which kicked off at about 1:00, after lunch with the rest of the Opensource.com team, and wrapped up around 5:30, reconvening again with the rest of the team for dinner. We also were together with the whole team for an hour in the middle of the afternoon to meet with Jim. Of the ten Ambassadors present, half were from Red Hat. Going around the room:

- Allison Matlack*
- Jono Bacon
- Jason Hibbets*
- Rebecca Fernandez*
- Brook Manville
- Robin Muilwijk
- Sam Knuth*
- Chad Whitacre
- Laura Hilliger
- Bryan Berenshausen*

&nbsp; &nbsp; &nbsp; &nbsp;_\* Red Hat_

In a lot of ways, the meeting was reminiscent of the Open Company Initiative (OCI) events we held with Balanced in 2013 and 2014. Linkdump:

- http://www.opencompany.org/summit/
- http://www.opencompany.org/summit/2014/
- http://diane.bz/being-open-about-being-open
- http://blog.balancedpayments.com/open-business-open-house/
- https://www.youtube.com/watch?v=e4E7kNQSBeY

That is, this was a similarly sized group of good folks, talking about similar themes. It turns out that another attendee, Sam, participated in another similar group, the [Management Innovation Exchange](http://www.managementexchange.com/) (MIX), with a similar arc as OCI: a year or two of enthusiasm, which eventually dissipated once the prime movers got distracted. One crucial question today (in my view) was how OOA is going to succeed where OCI or MIX failed, seeing as how we are similarly constituted, and at about that two-year mark.

One approach that I sort of championed for much of the meeting was "having teeth." In other words, pulling together an institution to define what an open organization is and to drive adoption. Touchpoints here include [OSI](https://opensource.org/), [CMMI](https://en.wikipedia.org/wiki/Capability_Maturity_Model_Integration), [TOP](https://cos.io/top/), [B Corporations](https://www.bcorporation.net/), and [PBCs](https://en.wikipedia.org/wiki/Public-benefit_corporation), and to some extent [cooperativism](https://en.wikipedia.org/wiki/Cooperative). Red Hat's own [Open Decision Framework](https://github.com/red-hat-people-team/open-decision-framework) and attendant [maturity model](https://github.com/red-hat-people-team/open-decision-framework/tree/master/maturity-model) could in this scenario form the basis.

By the end of the meeting, it was clear that we are not ready to go this route—if indeed we'll ever be! Where we dialed it back to was basically where we are today, perhaps incrementally intensified: writing stories about open organizations, with a heightened focus on case studies, examples, and practical advice. Opensource.com at this point seems as good a place as any to house the conversation (Bryan made an interesting analogy to BuzzFeed, which uses the flood of listicles to fund the occasional heavy-hitting investigative piece). Interestingly, this is basically where OCI [ended up](https://github.com/opencompany/www.opencompany.org/issues/24). Though, interestingerly, I now find this ticket about an "[open company pattern library](https://github.com/opencompany/www.opencompany.org/issues/129)" which refers to the blog tack as having been abandoned "for lack of interest." The concept of the "design pattern" did come up today (from Jono). This is reminiscent of Frederic Laloux's [work](http://www.reinventingorganizations.com/), especially his [wiki](http://www.reinventingorganizationswiki.com/Main_Page).

I was interested to hear references to Morning Star, Semco, and Gore—transition economy mainstays—alongside references to mainstream companies like J.P. Morgan, Microsoft, and General Motors. With Jim and Red Hat (10,000 employees, $2 B/yr in revenue and growing) driving the conversation, this seems like a moment where some of the work that has been happening around the edges could start to move towards the center. The task seems to be to make it accessible to the mainstream—CEOs, managers, and employees alike. Perhaps Red Hat signals the transition economy's shift to "early majority"?

![diffusion-of-innovation-adoption-curve](https://cloud.githubusercontent.com/assets/134455/19710711/636b6478-9afe-11e6-8259-19314a21f59a.jpg)

Certainly Red Hat has the wherewithal to support this sort of effort much more effectively than the OCI partners did at the time, or the MIX folks from what I gather. That said, the open organization conversation is basically a "hobby" for Jim (someone else's words; his words: "I do have a day job"). Yes, Red Hat is able to sustain it—for now. But what about in five or ten years? We need to diversify for a number of reasons, existential security being one of them. Perhaps with Red Hat's help, we can reach critical mass.

Another topic of conversation squeezed in at the end of the day was the governance and process of the OOA itself. At a minimum we are looking at increasing the visibility of the publishing queue. A further step would be to open up more-or-less strategic decision-making to outside influence.

Okay! That's my summary. It was a full day with lots of contributions. Thanks especially to Laura and Brook for facilitating, and to Jason, Brian, Allison, Rebecca, Sam, and the rest of Red Hat for hosting us. Here's to more open organizationing in 2017! 💃 🌻

**Comment by whit537** [comment]
The OOA group had a follow-up meeting with Red Hat CMO [Jackie Yeaney](https://twitter.com/jackieyeaney) this afternoon, summarizing yesterday's session. There were initial rumblings of a spring meeting.

I had lunch with [Justin Dorfman](https://twitter.com/jdorfman) today. He was a huge partner while at MaxCDN. Now he's at Sticker Mule. Our old leaderboard was a big part of MaxCDN's motivation for giving on Gratipay. I think we reach out to Justin again once we have something back along those lines.

I'm on for a chat tomorrow morning with [Adam Stacoviak](https://twitter.com/adamstac) of [Changelog](https://changelog.com/). We did a [show](https://changelog.com/podcast/123) together in 2014.

**Comment by whit537** [comment]
Okay! Back to the room with a couple beers in me, had a great time with friends I didn't know were here, might have a new backend dev recruit ("Let's make it $6/wk so I can at least buy a beer." :D) Now eating leftovers from last night and ready to hack on https://github.com/gratipay/gratipay.com/issues/4148! I probably have four or five hours tonight. Let's go! :rage4:

**Comment by whit537** [comment]
I'm at the airport about to board. What a trip!

I met [Brandon Keepers](https://twitter.com/bkeepers) last night. He's the open source lead at GitHub. He shared an anecdote that recently he'd asked the design team to work on something, and they came back with a heart on a brown background. He said, "Ya, we can't use that," and showed them Gratipay. :-) ❤️

**Comment by whit537** [comment]
Back in Pittsburgh! Waiting for the penny puncher. I am excited to keep hacking and hustling! 💃 🌻

**Comment by whit537** [comment]
> I'm on for a chat tomorrow morning with Adam Stacoviak of Changelog.

P.S. He stood me up. I caught him at the end of the day, and helped him pack up while waiting for his last interview. He was basically like, "Dude, why don't you give up already? I recommend you read [*The Dip*](https://www.amazon.com/-/dp/1591841666)." 😶

**Comment by whit537** [comment]
I also met [Katrina Owen](https://twitter.com/kytrinyx) (also at GitHub), and we talked about https://github.com/gratipay/gratipay.com/issues/3481 and https://github.com/gratipay/gratipay.com/issues/3602 (cf. https://github.com/gratipay/inside.gratipay.com/issues/637#issuecomment-246519445).

**Comment by whit537** [comment]
> He was basically like, "Dude, why don't you give up already? I recommend you read [*The Dip*](https://www.amazon.com/-/dp/1591841666)."

Which gets me really h*ckin' 🔥 d up, to be honest.

**Comment by whit537** [comment]
I was actually pretty moved by the contrast between my experience as someone with access to Red Hat's corporate largesse, and the situations of some of the people I met on the street in downtown Raleigh. There was one dude in particular who was _so happy_ for $4 to buy some McDonald's—and here I am, casually having a second plane ticket purchased for me at the last minute for $736.50. The point of Gratipay is to extend the boundaries of this community of abundance as wide as we can! 💸 It's not just about money, though, but also _belonging_—welcoming people into radically inclusive communities of work. Let's do it! 💃 🌻

**Comment by whit537** [comment]
> casually having a second plane ticket purchased for me at the last minute

I interacted with two people at the travel agency during that episode. The first was Paula, and the second was Jeanie. When I called back just now to find out the price, I talked to Jeanie again—I assume that's how she spells it, but just now I wrote down Genie. Like, I have a genie who grants my wishes. 😳

**Comment by jhibbets** [comment]
It is Jeanie - and both her and Paula have been awesome to work with.

**Comment by whit537** [comment]
Lightening talks [are up](https://opensource.com/article/16/11/watch-now-5-minute-videos-linux-and-more)! Here's [mine](https://www.youtube.com/watch?v=Rj88uGUB7tw). Not super high-energy, but gets across what I was trying to say, I think.

Thanks again for having me, @jhibbets @semioticrobotic et al.! :-)
