### ISSUE TITLE
Upgrade aspen to the last released version (0.42)

### ISSUE THREAD

**Issue by nashe** [gratipay/inside.gratipay.com#766]
This website is still using `aspen 0.37` while the last release is `0.42`. It introduced interesting security improvements/fixes, so it's useful.

[I asked @whit537 to do it](https://github.com/gratipay/inside.gratipay.com/issues/760#issuecomment-238564481) since… yeah, it's his framework and I'm sure he'll have to spend way less time than me on this task. Thanks! 💃

**Comment by techtonik** [comment]
@nashe asking @whit537 to do everything is a bad idea, because it decreases project bus factor.

**Comment by techtonik** [comment]
@nashe if it is hard for you, then it is worthy to document the process and try to improve it. Having direct access to @whit537 you may save valuable time for other people.

**Comment by whit537** [comment]
PR in #788! :)

**Comment by whit537** [comment]
Moving to PR ...
