### ISSUE TITLE
Consider using Scrollback/Gitter

### ISSUE THREAD

**Issue by seanlinsley** [gratipay/inside.gratipay.com#79]
Moved over from https://github.com/gittip/www.gittip.com/issues/2618:

@gjsrivastava [suggested on IRC](https://botbot.me/freenode/gittip/msg/19311792/) that we try out http://scrollback.io which, among other things:

+ is open source
+ provides IRC logging similar to what we currently get from Botbot
+ provides a JS widget for people to easily join our IRC channel from within our site

An example chat room: https://scrollback.io/dogecoin

**Comment by rohitpaulk** [comment]
[Gitter](https://gratipay.com/gitchat/) is similar, and they're on Gratipay already :)

**Comment by whit537** [comment]
How open-source is Gitter?

https://github.com/gitterHQ/

**Comment by whit537** [comment]
Closing along with #59.
