### ISSUE TITLE
implement http://status.gratipay.com/

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#790]
I observe a very long response time from Gratipay today. It would be very nice to see some independent status dashboard with monitored parameters, such as response time at http://status.gratipay.com/

What options are available to implement something like https://status.github.com/ and https://status.python.org/ ?

**Comment by nashe** [comment]
Something like http://inside.gratipay.com/appendices/health but on his own subdomain?

**Comment by whit537** [comment]
Let's remember to steer clear of subdomains of gratipay.com to minimize our cookie attack surface.

**Comment by techtonik** [comment]
@whit537 status.gratipay.com is an exception so that it could be run it on decoupled IP/infrastructure.

**Comment by whit537** [comment]
I don't think we should make an exception. I think we'd want to use a different domain—is there a `.status` tld yet? ;-) Something like `https://gratipay.status/`. ;-)

**Comment by techtonik** [comment]
Can we apply as a regulator and charge fees for status domains? =) https://newgtlds.icann.org/en/

**Comment by whit537** [comment]
@techtonik Go for it! ;-)

**Comment by whit537** [comment]
> This new feature helps creating such a public status page in seconds where the page will be displaying all the major details needed (uptime status and ratio for the last 7 days, response time and down events).

http://blog.uptimerobot.com/introducing-public-status-pages-yay/
https://gratipay.freshdesk.com/helpdesk/tickets/5821

**Comment by whit537** [comment]
I think by this point people expect `status.` to exist.

https://status.github.com/
https://status.heroku.com/
https://status.stripe.com/
https://status.braintreepayments.com/

**Comment by whit537** [comment]
That doesn't mean we have to use that, but it means people will wonder where ours is and have to think about it.

**Comment by techtonik** [comment]
Sorry, I am subscribed to all notifications for Gratipay and things are washing off my radar like with windshield wiper in the heavy rain. I am still looking into this.

I wonder how many 404 error are there on https://status.github.com during a day.. =)

![image](https://cloud.githubusercontent.com/assets/515889/19597823/a8dd51cc-979f-11e6-8bff-7f7157bec0d3.png)

**Comment by techtonik** [comment]
@whit537 I try to think would be the best place to list and maintain our domain inventory. I've already got code to check it at https://github.com/kubernetes/k8s.io/pull/30#issuecomment-255094491

We list only 2 domains from our resources at http://inside.gratipay.com/big-picture/product and http://inside.gratipay.com/appendices/tools#toc-3 mentions there are at least 10 of them, but no exact number. And http://inside.gratipay.com/appendices/access page is Oops.

![image](https://cloud.githubusercontent.com/assets/515889/19599261/a47d2c52-97a8-11e6-9261-d0ed53975875.png)

(why Ruby?)

**Comment by whit537** [comment]
> Meet Cachet
> The open source status page system

https://cachethq.io/

**Comment by whit537** [comment]
Generous offer from @laCour in private email:

> I saw this issue: https://github.com/gratipay/inside.gratipay.com/issues/790
>
>I'm a co-founder at Hund.io, a newer status page provider. We'd be thrilled to provide Gratipay with our OSS plan at no cost to show our support. Here's an example: https://serverbase-status.net/
Many companies have been switching from StatusPage.io and Cachet to Hund. Our platform supports custom domains with free HTTPS, metrics graphs, custom metrics, automation, granular subscriptions, and custom styling.
>
>If you're interested, sign up and we'll be pinged so we can place you on the OSS plan.

Anyone want to take him up on this? ☺️
