### ISSUE TITLE
track my.enspiral

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#792]
In the grand tradition of #421, #420, and #554, we now come to ... my.enspiral! This "virtual bank" is best described in "[Grow Your Own Economy in a Company](https://medium.com/enspiral-tales/grow-your-own-economy-in-a-company-a88efc4ba0d)." Now I'm hearing in private email about [a letter inviting user requirements](https://docs.google.com/document/d/1r0pAlz3LXgdNmhRg_tjJdP7g9PrfloXLJC05mSeSun0/edit?usp=sharing) from entities potentially interested in using a productized version.

> Wondering if you would be open & interested to take a short moment to share why/ how you would need/ use such an app?

Thoughts, @Gratipay?

![1-3lga0ixlwlyq99aemwfjpa](https://cloud.githubusercontent.com/assets/134455/17982436/d4f3cc10-6ad5-11e6-8b00-5d0e0b3c44ad.png)

**Comment by coopchange** [comment]
Thanks for this warm welcome & great facilitation @whit537. V. cool to be in Gratipay-space (was geekin' a bit when I read your articles about take-what-you-want compensation, kudos to that experiment!)

Myself and the market analysis team (I see Mikey Williams has been in here before) have opted to use _[job stories](https://jtbd.info/replacing-the-user-story-with-the-job-story-af7cdee10c27#.1b4vvj55i)_ as our generic prompt for input; basically the format is: ***When [situation] , I want to [motivation] , so I can [outcome]***.

Thus far, we've found it useful to do interviews and general hashing towards potential collaboration through video chat with folks like Outlandish & Robin Hood Collective (chatting with Hylo next week); this has enabled us to describe what we've used the program for now and in the past, and here a general story as to what collaborative budgeting and open accounting looks & feels like in your org, and what you'd like it to be: 

what banking levers, buttons, or visualisations would you like your guests/ contributors/ members/ stewards to have? to what end?

Thanks again! In Reciprocity, --john

**Comment by whit537** [comment]
Thanks for joining us here, @coopchange! :-)

Video call sounds great. You up for livestreamining/archiving for easier reference to our conversation in the future? I've had luck with Google Hangouts on Air for this (though they're switching to YouTube Live after September 12). I believe Indianapolis is in EDT, yes? If so we're in the same timezone (I'm in Pittsburgh :). Any of these times work for you?

 - Tuesday, August 30 at 1:30 pm
 - Wednesday, August 31 at 1:30 pm
 - Tuesday, September 6 at 1:30 pm

**Comment by coopchange** [comment]
Wednesday sounds great, thanks!

 I'm happy to set-up the Hangouts on Air for a recording, I like to circle (or spiral) back to stuff myself; cheers to open access as well. I'll send you an invite by end of monday. Thanks also for the connect with your associate from Catapult; getting even more excited about the potentials as the outreach flowers outwards... Cheers!

**Comment by whit537** [comment]
Awesome, thanks @coopchange. Invite received and confirmed. Talk Wednesday! 💃

**Comment by coopchange** [comment]
direct link to hangout: https://hangouts.google.com/call/ahn6ibjpdrctfjber2hsw33glqe

**Comment by coopchange** [comment]
Thanks so much for the inspiring meet-up Chad; I think there's some awesome collaboration points that will mutually build up Enspiral & Gratipay together- I think the survival of groups like ours is interdependent on our mutual growth (and not that capitalist infinite out-of-control growth dontcha know ;) )

I'll post those deliverables here by mid-time next week if not earlier. @whit537

**Comment by whit537** [comment]
Thank you as well, @coopchange! It was great to talk to you and knit another stitch in the relationship between Gratipay and Enspiral. :-)

**Comment by whit537** [comment]
P.S. Do we have a YouTube link for the archive of the call?

**Comment by coopchange** [comment]
Definitely, and glad you mentioned as I was just grabbing the [YouTube link](https://www.youtube.com/watch?v=gFxlArkajHE) for you :) Chances are I'll pull it down and edit it in about a week to remove the hiccups and the beginning before you joined the call

**Comment by coopchange** [comment]
I'm curious to dig further into your concept of collaborating on budget before the fact or after the fact; I'm going to let it bounce around in my head a bit longer.

**Comment by whit537** [comment]
> I'm curious to dig further into your concept of collaborating on budget before the fact or after the fact

Raw thoughts on that at https://www.youtube.com/watch?v=gFxlArkajHE#t=47m12s.

I appreciated [your response](https://www.youtube.com/watch?v=gFxlArkajHE#t=51m28s). I especially like the idea of different account or bucket types, with "take-what-you-want" (twyw) being one of those that fits within a larger account structure: "[that would probably be a pod in and of itself](https://www.youtube.com/watch?v=gFxlArkajHE#t=53m04s)." Whenever I glance toward the future of twyw and how it might scale up, one expectation is that we'll need to split twyw groups at some [Dunbar](https://en.wikipedia.org/wiki/Dunbar%27s_number)-ish size and then nest these groups somehow (cf. [Ostrom's eighth principle](https://github.com/gratipay/inside.gratipay.com/issues/409#issuecomment-181522284)).

We did manage to [bring back twyw for Team Gratipay](https://github.com/gratipay/gratipay.com/issues/3994) yesterday (yay! 💃 ), and the [way](https://github.com/gratipay/gratipay.com/issues/3994#issuecomment-229796292) we're doing it this time around is that we specify a certain amount of money that's available every week (we're [starting](https://github.com/gratipay/inside.gratipay.com/issues/747) with $50/wk for Team Gratipay). Whatever else we earn that week, as well as whatever we don't take (yesterday we left $42.60 on the table), drains to our operations bank account. So we've already got this idea of nesting going on, with a $50 twyw "[draw pool](https://www.youtube.com/watch?v=gFxlArkajHE#t=53m00s)" inside of a larger budget. Two differences that strike me are that Gratipay's larger budget is not yet large enough for us to have hit much pain in needing to segment it further, and owners/staff/contractors access our twyw draw pool on a _recurring_ basis rather than having to issue one-time invoices against it.

Is there perhaps a future in which Gratipay is a plugin for My.Enspiral?

**Comment by coopchange** [comment]
great thoughts & links @whit537 - much alignment methinks... I'm back from vacation/travels starting Wed. morning and I'll respond in detailed kind! Cheers ^^

**Comment by whit537** [comment]
@coopchange Another possible future might be that Gratipay ends up focusing on the lower-level regulatory and processing parts of payments, interfacing with the existing global financial system, while Enspiral's work with Cobudget and [future my.enspiral](https://www.youtube.com/watch?v=gFxlArkajHE#t=11m58s) (FME) ends up covering the higher-level "virtual" side—everything that happens inside the safe walled collective garden. We'll see how things evolve! :-)

**Comment by coopchange** [comment]
Digging your thoughts towards collaboration, from the video segment where you mention federating in the vein of clearing houses to twyw-plug-in (above) to Gratipay's functionality as an intake mechanism that works with upstream providers... a keen focus on APIs and capacity to integrate with the various parts of the operational value chain will likely be integral to the success of FMEnspiral. Luckily, a big part of what Enspiral brings to the table is a lot of experience in compliance and dealing with regulatory and upstream financial institutions; their accounting/legal/ops team are pretty experienced. 

It sounds like future collaboration with Gratipay could be revealing to both parties as to what regulations look like in the respective countries and give insights towards OS scaling of each... I look forward to seeing how things pan out, and hope we stay in the loop.

Here's one of the my.enspiral specs [video](https://www.youtube.com/watch?v=SYAGeKBMBE8)s... if desired I'll root around for the 2nd one and see about permissions.

_aside re: Ostrom_ - I'll be interested to compare notes when I get around to that sometime in the next half year; I was intrigued that Rachel O'Dwyer suggested that Ostrom's principles may propagate the neo-liberal subject in terms of spreading a narrative of self-interest... personally I leverage the concept of self-interest a lot in my community organizing work, so not sure how I feel about it.

I cut out the disconnects and the time before we started from the video, but it may take a couple hours to upload as I mistakenly exported it as a .mov (18GB file :P); I'll toss it in here when it's up. Peace.

**Comment by coopchange** [comment]
This [video ](https://www.youtube.com/watch?v=C6K_WB1sFGw&feature=youtu.be) may describe my.enspiral even better (might be in 10-15 min.); but please don't share onwards without permissions thanks!

**Comment by coopchange** [comment]
oh! **correction**: I meant * Jessy Kate Schingler, not Jess Ducey,  in regards to Embassy Network.

**Comment by coopchange** [comment]
Uploaded my edited V. of above-linked chat. Here's the **preferred [video-link](https://youtu.be/WPn5MMVUpY0)** of Chad & john on gratipay + my.enspiral** for sharing**.

**Comment by whit537** [comment]
Awesome. Thanks for your work on this and for circling back around, @coopchange. I'm going to go ahead and leave this ticket open, changing the scope to "track my.enspiral." Feel free to drop by here as you like with any updates on progress! :-)

**Comment by coopchange** [comment]
Hi Gratipay Folks! Hope all goes swell.
Here's what I derived from our meeting; maybe some more job statements ( _When [situation] , I want to [motivation] , so I can [outcome]_ ) come to mind yet @whit537 ?
__________________________________________________________________________________________
_2 main accounts: Ops Account (which Chad was intrigued as to the potential of using Cobudget to manage), and the Take-What-You-Need account

Left overs, after take-what-you-need process, in that account move to Ops Account._

When money comes in I want to auto-distribute it (per value equation) to various accounts so I can fund the different ops of a business

When money comes in I want to know pertinent details like from whom, why, so I can easily understand the circumstances of financial flows

When money’s sitting in an account I want members to be able to allocate it so that I can respond to opportunities

When money’s sitting in an account I want to view it by different kinds of buckets, but with consistency of UI, so that I may more easily understand the data.

When someone’s abusing their power, want to be able to cut them off to preserve funds and the integrity of the org. or network

When someone shows up I want to be able to assign them to a take-what-you-want bucket so they feel valued.

When someone meets certain criteria I want to be able to change their permissions as to what they can allocate/ change what accounts they have read/write access so that group can sanction/reward levels of accountability and certain behaviours.

When I add someone, I want that to be open on the internet so we can be transparent
(Push to iframe)

**Comment by whit537** [comment]
> Take-What-You-Need

Note that it's take-what-you-*want*—abundance, not scarcity! :-)

**Comment by coopchange** [comment]
++
hey look, Transformap mentioning both of us: https://diigo.com/08xbav , and in regards to funding models no less, _go figure_
