### ISSUE TITLE
find a design firm

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#812]
We have a CPA and a lawyer. We need a design partner. I think a relationship with a company will be easier than a relationship with an individual freelancer, to avoid the confusion between mercenary and quasi-volunteer to which we, as an open organization, are prone (cf. #298). We want a design mercenary. A hired gun. Clean. Contractual. Transactional.

Let's find the right one!

**Comment by whit537** [comment]
http://inquiri.com/
https://www.walltowall.com/
http://metalab.co/
https://bocoup.com/
http://newkind.com/
http://smashingboxes.com/
http://www.bearded.com/

**Comment by whit537** [comment]
I want to list 50 agencies.

**Comment by whit537** [comment]
https://andyet.com/
https://lincolnloop.com/

**Comment by kzisme** [comment]
http://www.canny-creative.com/services/

**Comment by kzisme** [comment]
https://madebymany.com/
http://domain7.com/

**Comment by whit537** [comment]
http://alistapart.com/authors &larr; 495 designers, let's scrape for firms! 💃

Authors in one list: https://gist.github.com/whit537/9e11cc7bf584b7be8f00b59fa7d28e1b

**Comment by whit537** [comment]
Let's collect them on https://public.etherpad-mozilla.org/p/gratipay-list-of-design-firms.

**Comment by whit537** [comment]
Here's a pen w/ the list of ALA authors to click through ... http://codepen.io/anon/pen/RGWoEG?editors=1000

**Comment by whit537** [comment]
@kzisme I'm starting at the top of that list, wanna start at the bottom when you're outta examples of your own? :-)

**Comment by kzisme** [comment]
@whit537 Will do

**Comment by kzisme** [comment]
Pen is a little off (unless i'm doing it wrong)  

http://s.codepen.io/author/yoavweiss

**Comment by whit537** [comment]
Sorry, should be fixed?

**Comment by whit537** [comment]
Made it through the first 100. Not as many useful links as I would've hoped, maybe 1 in 10?

**Comment by kzisme** [comment]
Yup!  @whit537 Yeah I clicked randomly though for a bit, but mostly they are just individuals or just short intros about designers. :surfer:

**Comment by kzisme** [comment]
I'm going out for a bit!  We're at 40 on the list now! :dancer:

**Comment by whit537** [comment]
Made it through 149. If we go in order we can avoid duplication. :-)

**Comment by whit537** [comment]
Another source: https://github.com/gztchan/awesome-design.
