### ISSUE TITLE
Radar bot spams notifications

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#828]
It is hard to see if there is any human activity when bot triggers so much notifications.

**Comment by whit537** [comment]
+1 from @mattbk at the [retreat](https://github.com/gratipay/inside.gratipay.com/issues/392#issuecomment-240693047).

**Comment by mattbk** [comment]
To clarify, my criticism of multiple radars is mostly that it a) slows me down when I need to stop and figure out which radar to post in and b) dilutes conversation, which makes each radar feel lonelier. I don't think the Gratipay team is large enough that this many radars is justified.

**Comment by rohitpaulk** [comment]
Agreed, I think we have radar bloat 😛

**Comment by whit537** [comment]
I've folded Marketing, Support, Product, Accounting, and Tech into Core. Security holds our queue, so I think we should leave that separate for now.

Better? :-)

**Comment by techtonik** [comment]
Still looks overwhelming, but signal now passes better, thanks. =)
