### ISSUE TITLE
start paying for space

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#831]
Yesterday was my favorite day in a long time. We had a small crew working on Gratipay around the table at 716 Park (@kaguillera @dmk246 and myself, almost Chaz) with people coming and going (Maya to talk about the new [theatre](http://www.ironhorsetheatrecompany.com/), Pierce with his banjo on the way to the farmer's market, Sweet Mama @JessWhit and the Whitakids). I _loved_ it. A teensy tiny society of people freely serving one another. The Evolution! 🌻 💃

I want to figure out how to continue and amplify _that_, because it's what Gratipay is all about. One thing I think is true is that even though we are a distributed software company, place still matters. The times we've been able to be together at the retreats have been really special.

I propose that we budget for space for people working on Gratipay. For now I think @kaguillera and I should keep paying for [Catapult](http://catapultpgh.org/) and [Stack](http://www.stackpgh.com/) separately, because when I'm there on Fridays I'm actually working on [COS](http://cos.io/) for now. What [seems](https://twitter.com/whit537/status/779067780758921216) to make sense for the fall here is to spend Wednesdays at 716 Park, and Thursdays at [Paramount](http://www.paparamount.com/) (_assuming_ I'm not allergic to it—we'll find out next week!).

I think Gratipay should pay for Paramount. We should be able to reach an agreement with them where we pay a set amount for one day a week of zero or more people. The fluid community boundary is important. I want to be able to invite people to stop by and see who sticks around (we found Pierce playing banjo with a can out, in front of the dollar store).

Looking at their [pricing](http://www.paparamount.com/membership-info.html), I would expect to negotiate something between $125/mo and $250/mo.

**Comment by whit537** [comment]
Any blockers?

P.S. I think we could do this in other cities as well if/when yinz bring together enough people. :-)

**Comment by whit537** [comment]
> (_assuming_ I'm not allergic to it—we'll find out next week!)

Just got here, sat down ... and sneezed. 😞

**Comment by whit537** [comment]
@dmk246 @kaguillera and I are getting ready to go for it on this one. It adds $30/wk to our [budget](https://docs.google.com/spreadsheets/d/1p3DpF9ZLEsViBx0685FwJaYN1vVScKVUgXHb2zyqXZg/pub?output=html&widget=true), but it gives us a place to be. Though we could also be at my house. For free. Like we're going to do tomorrow.

I don't know. AAAAHHHHHH!!!!!!!!!!!!!!!!!

**Comment by mattbk** [comment]
If you're not allergic, it's probably worth it.

If I were more flexible with work I'd go to https://the-701.com, which is opening soon here.

**Comment by whit537** [comment]
Woo-hoo! Thanks, @mattbk. Not allergic, no. :-)

Here is their [membership agreement](https://github.com/gratipay/inside.gratipay.com/files/540274/CoOp.Membership.Agreement.2015.pdf) (shared with permission). We're going to use our [checks](https://github.com/gratipay/inside.gratipay.com/issues/439#issuecomment-166739591) to save credit card fees. :-) We are Client #0000! 💃

**Comment by whit537** [comment]
(P.S. They're waving the $25 one-time admin fee for us.)
