### ISSUE TITLE
turn off roobot

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#834]
We have a [bot](https://github.com/gratipay/roobot) for the IRC channel, but the IRC channel is moribund (#288). It's good security practice to remove unused services, in order to decrease attack surface, especially since unused services can lag behind in security updates. I think we should turn off roobot at Heroku and remove it at Uptime Robot and PagerDuty, and wherever else it currently appears.

**Comment by rohitpaulk** [comment]
I've been getting calls from pagerduty saying that roobot-prod is down, so I guess this is a good time to get this done :P

**Comment by rohitpaulk** [comment]
Removed from pagerduty.

**Comment by rohitpaulk** [comment]
Removed from uptimerobot.

**Comment by rohitpaulk** [comment]
I've reduced the dynos to 0 and removed the linked instance on Heroku. Can't delete the app, only the vendors@gratipay.com account has the permissions to do that.

https://dashboard.heroku.com/apps/roobot-prod

**Comment by rohitpaulk** [comment]
Also left a note on the repo - https://github.com/gratipay/roobot/commit/a73724e8b64a09a821b77a09567535d451cbb1d4

**Comment by whit537** [comment]
> Can't delete the app, only the vendors@gratipay.com account has the permissions to do that.

Done!

!m @rohitpaulk

**Comment by whit537** [comment]
I just removed the `roobot-prod` webhook from the `inside.gratipay.com` and `gratipay.com` repos.
