### ISSUE TITLE
onboard @chrisdev

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#835]
@chrisdev is a member of our Safety Team. I've been working with him in private email to get him back on the distribution list. Let's do it!

**Comment by whit537** [comment]
```
>>> Participant.from_id(11997).set_identity_verification(226, True)
>>>
```

Yay TT! 💃

![screen shot 2016-09-28 at 4 12 11 pm](https://cloud.githubusercontent.com/assets/134455/18930525/6302885e-8596-11e6-841e-5bcdbe91916d.png)

**Comment by whit537** [comment]
👍

![screen shot 2016-09-28 at 4 14 43 pm](https://cloud.githubusercontent.com/assets/134455/18930627/b9cde3cc-8596-11e6-9091-06e45a7d27b8.png)

You good, @chrisdev?

**Comment by chrisdev** [comment]
👍
