### ISSUE TITLE
teams table is wider than header on mobile version

### ISSUE THREAD

**Issue by see-ya-leah** [gratipay/inside.gratipay.com#839]
#### Steps to reproduce:
1. Go to https://gratipay.com on my iPhone.
2. Zoom out to see all of the information regarding teams. 
#### Expected result:

I expected the information at the top (including the logo, search bar, sign in button, etc.) to fill the page when I zoomed out. 
#### Actual result:

The column with all of the teams and their info takes up more room than the "header."

![img_1272](https://cloud.githubusercontent.com/assets/18368870/19014968/6b0c45d8-87c8-11e6-9118-516fb7fd645a.PNG)

**Comment by whit537** [comment]
Can you reticket in the gratipay.com repo please? This repo is for http://inside.gratipay.com/. 🙇
