### ISSUE TITLE
Recruit companies

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#844]
#### Companies and Organizations

.
.
.
.
[List of companies moved into Pipedrive (#851)]
.
.
.
.
# _Was:_ Talk to companies still giving on Gratipay

![screen shot 2016-10-06 at 6 08 37 am](https://cloud.githubusercontent.com/assets/134455/19148588/65789a7e-8b8b-11e6-8e9d-15484c50aa29.png)

> Your users are your guidepost. And the way you stay on the right path in the early stages of a startup is to build stuff and talk to users. And nothing else.
> 
> **2. Stay focused.**
> 
> One of the most conspicuous patterns we’ve seen among the thousand startups we’ve funded is that the most successful founders are always totally focused on their product and their users. To the point of being fanatical. The best founders don’t have time to get caught up in other things.

http://themacro.com/articles/2016/06/how-not-to-fail/

**Comment by whit537** [comment]
Did some database digging. It's basically just Teespring. 😶

**Comment by whit537** [comment]
From https://github.com/gratipay/inside.gratipay.com/issues/836#issuecomment-251540409:

> What companies need:
>
- a paper trail
- quarterly or annual budgets ($10 M for the year ...)
- decentralized budget allocation (... to 10,000 projects)
- multiple-user accounts
- SSO
- recognition

Let's maybe see if that's true?

**Comment by whit537** [comment]
To: Walker at Teespring

> Okay! Application sent. Thanks for the awesome input, it really helped us put a point on it.
>
Also ... thanks for using Gratipay! :D Could I ask your input on which product areas to focus on from a company's point of view?
>
- better invoicing / paper trail
- bank transfers instead of credit card charges
- monthly / quarterly / annual funding instead of weekly
- better budget allocation tools / easier to manage giving
- multiple people can sign in to manage the account
- sign in with email instead of social
- SSO
- better recognition for your contributions
- more projects to give to
>
If you had to pick one for us to focus on next, which would it be? Anything else that should be on our radar?
>
Thanks for any input you can provide, Walker. I owe you a beer or three for sure. Have a great day! :-)

**Comment by whit537** [comment]
I have an email from Justin Dorfman still sitting in my inbox from last year. He was at MaxCDN, now he's at StickerMule. I should be able to connect with him at All Things Open.

https://twitter.com/whit537/status/784004814053126144

**Comment by whit537** [comment]
I replied to the email from Justin that has been in my inbox since May, 2015(!).

**Comment by whit537** [comment]
I've emailed the VP Engineering of [Wombat](https://www.wombatsecurity.com/), who is an acquaintance of mine.

> I was actually hoping to introduce you to the startup I'm working on. We help tech companies fund the open source projects they depend on. Is that something you'd be interested in hearing about with your Wombat hat on? Maybe next Friday (Oct 14) at 8:30 at 21st Street? I could also do tomorrow ...

I [told](https://github.com/gratipay/inside.gratipay.com/issues/393#issuecomment-248697385) Dan I'd make 10 sales calls this quarter. I guess this ticket is turning into a tracker for that. Three leads! Who else ... ?

**Comment by mattbk** [comment]
Based on https://twitter.com/stephen_mcd/status/784008515954184192, maybe reach out to others who have posted on the blog?

**Comment by whit537** [comment]
> who have posted on the blog?

Sorry, wazzat mean? Which blog?

**Comment by whit537** [comment]
> Is that something you'd be interested in hearing about with your Wombat hat on? Maybe next Friday (Oct 14) at 8:30 at 21st Street?

"I would be delighted to." 💃

**Comment by mattbk** [comment]
I was in a hurry. Stephen has this as his Gratipay profile:

> I am making the world better by http://blog.gittip.com/post/28595064070/back-the-stack-mezzanine-and-cartridge

**Comment by whit537** [comment]
I've pinged a couple Pittsburgh connectors for more local introductions, and I've also asked Walker for "two or three introductions to other companies who should be involved."

**Comment by whit537** [comment]
> Stephen has this as his Gratipay profile:

Ah, yeah. We tried a "back the stack" series back in the day. I think our focus here is connecting with companies to give, if we can unlock some funding flow from there then I think attracting projects won't be a problem—well, the problem will be the review bottleneck, especially #432. ;-)

**Comment by whit537** [comment]
From Walker:

> If I were you, I'd really focus on an accountability campaign. You need to make big companies feel like it's their duty to support the projects they rely upon. Right now we all rely on so many open source projects but don't contribute, I think you need to reset expectations that it's okay for a cash making company to take without giving back.
>
>> Do you think the Gratipay product is good enough to launch a marketing campaign like that? I hate to drive traffic and then leak it all over the place. :(
>
> Market test it, I don't think it's marketing campaign I think it's calling orgs or doing a blog series on a "support open source" month. Get a few marquee partners to sign up, do a huge PR push, a hashtag, etc. -- some big companies will love the PR of sounding like they support opensource and will hopefully put a couple K per month towards projects they use.
>
You should have a "recommended donation" scale based on company size/usage of product. Make it cheap, but much higher than it is today. Google, FB, Teespring, Airbnb, etc. etc. should all be paying thousands a month across all the projects we use.

**Comment by whit537** [comment]
Feels sloppy to use chad@zetaweb.com instead of chad@gratipay.com. :-/

**Comment by mattbk** [comment]
I'm so excited by this.

**Comment by whit537** [comment]
Me, too! :D

**Comment by whit537** [comment]
> I've pinged a couple Pittsburgh connectors for more local introductions

One: "I have ideas! I will ping you soon"

The other:

>> Happy to fwd a quick proposal summary to some of the folks you mentioned, if you've got something specific in mind
>
> How about this?
>
-------------
>
> Heartbleed showed that open source has "a free rider problem," according to the Ford Foundation's recent Roads and Bridges report. Gratipay is a Pittsburgh-based startup that helps companies sustainably fund the open source projects you depend on. We are in public beta and are looking to market test our product with Pittsburgh tech companies. Let's make Pittsburgh the leader in addressing the open source funding problem!
>
To schedule a call or coffee to learn about funding open source through Gratipay:
>
Chad Whitacre
chad@zetaweb.com
412-925-4220
>
Thank you! 🙇
>
-------------

💃

**Comment by whit537** [comment]
https://www.youtube.com/watch?v=dzOHq5WbQ8k

**Comment by whit537** [comment]
Others I'd like to ping:

http://jedgar.co/
https://gregbrockman.com/

**Comment by whit537** [comment]
> I replied to the email from Justin that has been in my inbox since May, 2015(!).

All set to connect at All Things Open (#757)! 👍

**Comment by whit537** [comment]
Of course! Added Center for Open Science to the list. And Khan Academy.

**Comment by whit537** [comment]
Pinged a friend at Pinterest.

**Comment by whit537** [comment]
I've emailed Greg Brockman.

**Comment by whit537** [comment]
Sooner or later we'll want a CRM for this, let's see how far we can get without one ...

**Comment by whit537** [comment]
We've got an ear to the ground at Pinterest.

**Comment by whit537** [comment]
Just had a phone call with our HackerOne account rep under #675, and I was given the impression that we're known and well-liked there. ☺️ I've [interacted](https://github.com/gratipay/inside.gratipay.com/issues/560#issuecomment-207620634) with CEO Mårten Mickos before. Perhaps I will email him again under this ticket, and/or perhaps I will visit [if/when](https://github.com/gratipay/inside.gratipay.com/issues/836#issuecomment-252289463) we make it out in November.

**Comment by mattbk** [comment]
We use Sticker Mule for ENDracing ([storefront](https://www.stickermule.com/user/1070673068/stickers)). Not much volume, but glad to keep using them.

**Comment by whit537** [comment]
Adding [PensionBee](https://www.pensionbee.com/) to the list. CTO mentions Gratipay [here](https://medium.com/@jayfresh/open-source-projects-are-a-lot-more-exciting-than-roads-and-bridges-4743948f82a6).

**Comment by whit537** [comment]
I am noticing people who follow me on Twitter and work at companies that we'd love to recruit. I am thinking about how best to ask them for help. :)

**Comment by whit537** [comment]
Maybe like [this](https://twitter.com/whit537/status/786602429936640000)? :)

**Comment by whit537** [comment]
![screen shot 2016-10-13 at 12 31 12 pm](https://cloud.githubusercontent.com/assets/134455/19357766/fc09dbe6-9140-11e6-8dac-a920d6037432.png)

https://cocoapods.org/

**Comment by whit537** [comment]
Okay! I had my first #BackTheStack sales meeting this morning. It was great! 🐝 

The person, a VP of Engineering, definitely "gets" that there is an imbalance between the value companies derive from open source, and the compensation to projects for that value. He has many more _immediate_ pain points (like shipping software!), but as a higher-level issue, keeping FLOSS healthy is definitely something he's aware of and seemed genuinely interested to address. Let's make it easy for him!

We started by talking about his company's current relationship to open source, which is pretty standard: 

1. They leaned heavily on open-source to launch on a shoe-string.
1. Now they have about 45 engineers, doubling in the past year or two.
1. They use ~200 open source projects, about 80% in the Java ecosystem.
1. They have a different perception of "commercial" open source (Java) and "independent" projects (Sidekiq, Ember, etc.).
1. They buy commercial licenses for a handful of independent projects (because they want support, features, and/or to avoid the GPL).
1. They open-source a handful of their own tools.
1. A handful of their engineers participate in open source (PRs, projects, conferences).

I walked him through the Gratipay product and asked where he'd get stuck:

1. Sign up with Twitter.
1. Find projects.
1. Set an amount.
1. Add an email address.
1. Add a credit card.

Twitter jumped out right away as an obvious obstacle, because marketing owns the Twitter account and wouldn't trust him with it. On the other hand, weekly credit card billing was not a big obstacle for him (it would become an issue when the company was larger; they're on the cusp).

He had two big questions.

First, how do I make the case to my CFO? The CFO's question is going to be: **what do I get out of this?** What am I paying for? Like it or not, pure altruism is not going to be enough to crack this nut. Thankfully, he gave us a possible angle: IP liability management. Companies spend a fair bit of effort vetting open source projects, making sure they're not introducing IP risk (copyright, patents). _That_ is a pain point we can potentially address, for which CFOs could be willing to pay.

Second, **how much should I be putting in?** Apple anchored the MP3 market at 99¢. Where are we anchoring the market for open source software? One suggestion was to bucket based on top-line annual revenue. He mentioned zero to 2M as a first "start-up" bucket. My extrapolation based on 1% of profit of 7% of bucket mean + fudging (add zeroes as appropriate):

| from ($/yr) | to ($/yr) | pay ($/wk) |
|------:|------:|--------:|
| 0 | 2,000,000 | 10 |
| 2,000,000 | 5,000,000 | 20 |
| 5,000,000 | 10,000,000 | 35 |
| 10,000,000 | 20,000,000 | 70 |

To address the CFO's pain point, we would need for all the projects they depend on to be included. Even if we don't allow moving money to projects without the project's approval ([cf.](https://github.com/gratipay/gratipay.com/issues/28)), we could at least have the project's licensing listed as guidance (can we use GitHub's [license API](https://developer.github.com/v3/licenses/#get-a-repositorys-license)?). This is similar to what HackerOne did to jump start their ecosystem by copying and pasting security programs to pages on their own site ([see also](https://gratipay.news/transparent-security-c864d03d6f60)). Maybe we'd have three tiers:

 - project unclaimed, license inferred
 - project claimed, license confirmed
 - project claimed, license confirmed, and funding accepted

Gratipay wants to stay away from being a party to the transaction. Any IP agreement exists between the project and the company. Gratipay is not a party.

A few additional points he mentioned:

- He would want to keep the list of dependencies private, to avoid security or patent troll risk.
- He was fine listing the number of projects supported, but balked at listing dollar amounts.
- I asked whether he had an opinion on whether Gratipay should be non-profit or for-profit, and he offered that companies are looking for vendors who are stable and long-lived. Insofar as "non-profit" means "fly-by-night," then for-profit is better.

**Comment by whit537** [comment]
I've been talking with a friend here at Catapult a lot today about how to address the CFO's pain point. It might mean creating a separate product aimed at them, and it might mean keeping that product closed(!).

**Comment by whit537** [comment]
Basically something to compete with http://www.whitesourcesoftware.com/ that would also drive donations.

**Comment by whit537** [comment]
Which seems like a crap-ton of work on a Friday night. 😩

**Comment by whit537** [comment]
What about a partnership with WhiteSource instead?

**Comment by whit537** [comment]
It's so frustrating, because the socio-pathic, short-term, selfish "What's in it for me?" attitude is _exactly_ what we're trying to overcome here. That's the whole mission of Gratipay! This CFO attitude "What do I get out of this?" is the heart of the problem. Fiduciary responsibility. The Almighty Dollar. Maximizing shareholder value above all else. :rage4: 

What about leaving C corps alone, and instead focusing on B corps (Etsy) and PBCs (Kickstarter)?

> In the United States, a benefit corporation is a type of for-profit corporate entity, authorized by 30 U.S. states and the District of Columbia[1] that includes positive impact on society, workers, the community and the environment in addition to profit as its legally defined goals.

https://en.wikipedia.org/wiki/Benefit_corporation

> Public-benefit corporations are a specific type of corporation that allow for public benefit to be a charter purpose in addition to the traditional corporate goal of maximizing profit for shareholders.

https://en.wikipedia.org/wiki/Public-benefit_corporation

**Comment by whit537** [comment]
https://twitter.com/wearpants/status/787044094401019904

cc: @wearpants

Here's the ticket.

**Comment by whit537** [comment]
Who is Ben & Jerry's CFO?

**Comment by whit537** [comment]
Let's see how this plays ...

> Would Etsy be interested in joining a movement of software companies dedicating a portion of their engineering budget to fund open source? We think this could have a big impact on the sustainability of the open source ecosystem, and we'd love to have Etsy on board.

**Comment by whit537** [comment]
I think we need one or three high-profile companies plus a half dozen other companies before launching an all-out campaign.

**Comment by whit537** [comment]
And I feel like we need a few fresh high-profile companies on board before we can reapproach some of the folks that were giving under Gittipay 1.0.

**Comment by whit537** [comment]
Things will die down over the next couple months. I think we should focus on building the first wave of ~10 companies who will partner with us for a #BackTheStack launch in January.

**Comment by whit537** [comment]
"What do I get out of it?"

Um ... you already *got* all of this software!

**Comment by mattbk** [comment]
> Who is Ben & Jerry's CFO?

They've been owned by Unilever for a while now, but:
http://www.benjerry.com/about-us/how-were-structured#1timeline
http://www.benjerry.com/about-us/b-corp

**Comment by nobodxbodon** [comment]
Have you considered or tried to partner with some big open source project, like Eclipse? As I imagine, those with large user base, yet slow bug/improvements fix rate because of short of hands will be better candidates.

**Comment by whit537** [comment]
@nobodxbodon Want to help us reach out? Do you have any contacts at the Eclipse Foundation?

**Comment by nobodxbodon** [comment]
@whit537 sorry I am just a long time Eclipse user. I just reached out to a contact in Mozilla Addon community, as IMO many addon authors may prefer gratipay over usual donation channels. Will update if any progress.

**Comment by nobodxbodon** [comment]
Sorry I am only a long time Eclipse user. I might be able to reach out to
Mozilla add-on group, as there are hundreds of popular add-ons that are
lack of maintenance manpower and the authors might like to have some extra
motivation.

**Comment by whit537** [comment]
@nobodxbodon Hadn't thought of Mozilla Addons, that's an interesting idea. The big insight for us recently is to bundle/aggregate, so consumers/users pay one price, and that gets shared out across an ecosystem.

**Comment by mattbk** [comment]
Mozilla Addons sounds a lot like the [relationship we had talked about](https://github.com/gratipay/inside.gratipay.com/issues/441) with Chocolatey.

**Comment by nobodxbodon** [comment]
Seems Chocolatey is one team, and they need to add involved package authors into the team to receive payroll? It feels a bit strange to have all the authors in one "team" as they work on different projects. Similar will be applied to Mozilla Addon. I'm not sure if the authors would want another method of donation other than Mozilla's built-in donation channel, if gratipay doesn't provide certain additional features. 
The first feature in my mind is to put "bounty" on a certain issue/improvement, but that may require a "judge" to decide when that requirement is fulfilled. An altenative is to allow those who put the bounty decide when it's fulfilled, and release the bounty. 
Now I'm wondering why github doesn't have this feature :)

**Comment by nobodxbodon** [comment]
Excuse me as it's off topic. Just a followup of comment above. A quick search leads me to bountysource and that addresses my wonder. After reading your post [track Bountysource](https://github.com/gratipay/inside.gratipay.com/issues/316), seems you already have good picture about the competition.

**Comment by whit537** [comment]
I'm going to close this as having been completed with #851. I'll note deals of note on the radar in the future.

**Comment by mattbk** [comment]
> Seems Chocolatey is one team, and they need to add involved package authors into the team to receive payroll? It feels a bit strange to have all the authors in one "team" as they work on different projects. Similar will be applied to Mozilla Addon. 

The solution (not yet in place) for Chocolatey is to create a new type of entity, so it's not necessarily that they would all be on one team.
