### ISSUE TITLE
Apply for open data incubator

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#845]
https://opendataincubator.eu/about/

Open performance data for open companies.

**Comment by whit537** [comment]
> ODINE’s call is a rolling process of 8 rounds lasting two months each. After the deadline of each round, we take roughly one month for the selection, which includes evaluation and interview, and one month for the negotiation of the milestones and contract agreement with the selected companies.
>
Applications have now been closed and we will update the content of this page soon.

https://opendataincubator.eu/apply/
