### ISSUE TITLE
switch disclosure page away from API

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#847]
We're losing the HackerOne API on December 1 (#675). Maybe instead we can (cronishly?) download a CSV or something?

http://inside.gratipay.com/appendices/disclosures

**Comment by mattbk** [comment]
Bummer. Why isn't there a page like this on HackerOne itself? Or do I need to be logged in to see it?

**Comment by whit537** [comment]
There's somewhat of a listing on our project page, but not what we want.

**Comment by whit537** [comment]
> Just caught my VP this morning. 
>
Your account will keep API after December 1. I've made the case for it to be included in our open source categorization. 
>
I hope it helps! Keep up the great work you're doing. 

💃  👍
