### ISSUE TITLE
Set boundaries for Pipedrive

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#855]
So now that we've got a CRM set up (#851) to help with recruiting companies (#844), let's talk about what I'm allowed to do in there. We know what's allowed to happen in other private channels ...

> As an open company, most of our internal communication happens on channels with open registration and public logging. The exceptions are legal, safety, security, and support matters.

http://inside.gratipay.com/appendices/channels

... specifically:
- In [HackerOne](https://hackerone.com/gratipay), the members of our [Security](https://github.com/orgs/gratipay/teams/security) team can triage security issues and award bounties.
- In the [legal](https://github.com/gratipay/legal) repo and my private email and phone communications with our counsel, I can discuss legal advice.
- In the [violations](https://github.com/gratipay/violations) repo, the members of the [Safety](https://github.com/orgs/gratipay/teams/safety) and [Payday Runners](https://github.com/orgs/gratipay/teams/payday-runners) teams can discuss violations of our terms of service.
- In [Freshdesk](https://gratipay.freshdesk.com/), the members of our Support team can discuss support issues with users.
### Doing Deals in Pipedrive

So how about Pipedrive? The point of Pipedrive is **deals**—getting to formal relationships with other organizations. The interface is built around "deals" moving through a "pipeline." Here's what I'd propose we allow to happen in there:
1. Discuss with potential customers the possibility of using our product.
2. Discuss with potential partners the possibility of partnering together in some way.

I propose these three constraints:
1. Any changes to the product need to go through public review as usual. We need to be able to publicly name the potential customer/partner as part of that process, so that the Gratipay community can make an informed decision together. Otherwise we have the potential for hidden agendas, and an information asymmetry (lack of transparency) that leads to a power asymmetry (lack of openness) about matters that properly belong to the entire Gratipay community.
2. Our public Team (Project) review process still applies. I can't promise anything privately in Pipedrive.
3. No gossip, defined as _private info that isn't directly related to a deal_.

(3) is the one that really brought this to a head. @dmk246 @kaguillera and I hashed this out today at Paramount. Basically, the situation is that I'm into a partnership conversation, and the person is offering me "early info" on something that as far as I can tell isn't _directly_ related to the relationship Gratipay wants to have with their organization. They're offering this in the context of deciding between doing a private Skype call and a Hangout on Air. My gut says "no." Even if we do a private call, I want the things we say to be on the record, unless there's a reason _related to the deal_. I don't need to know about other things going on. I feel that participating in that kind of communication would create too much of an "insiders" group that would be antithetical to the openness we strive for. No cliques! 😮  👐 

Thoughts?

**Comment by nobodxbodon** [comment]
About the gossip definition, IMO the extent of relation to a deal is quite subjective. On the other hand, I see the necessity of keeping some info private before the deal is closed. Another question is, is it OK/necessary to publicize those private info after closing the deal?

**Comment by whit537** [comment]
> IMO the extent of relation to a deal is quite subjective.

Sure. I'm not sure what to do about that. Thoughts?

For the presenting case, (and for the record) they ended up telling me anyway. 😕

> is it OK/necessary to publicize those private info after closing the deal?

I think negotiating what can be made public is part of doing the deal, but from Gratipay's perspective I think it should be non-negotiable that we can't make final decisions about deals without first vetting the decision in public here on GitHub. The side effect of that commitment is that we can't finalize a deal without having it be publicly discoverable prior to being finalized. If that's a deal breaker, then we'd rather not do the deal.

**Comment by whit537** [comment]
Seems like this is how we're gonna roll with Pipedrive ...
