### ISSUE TITLE
Inventorize domains

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#858]
Why?

- https://github.com/gratipay/access-dashboard/issues/29
- https://github.com/gratipay/inside.gratipay.com/issues/511
- https://github.com/gratipay/inside.gratipay.com/issues/790

**Comment by whit537** [comment]
See the "domains" tab of the [budget](https://docs.google.com/spreadsheets/d/1p3DpF9ZLEsViBx0685FwJaYN1vVScKVUgXHb2zyqXZg/pub?output=html&widget=true).

**Comment by techtonik** [comment]
@whit537 awesome ([link to tab](https://docs.google.com/spreadsheets/d/1p3DpF9ZLEsViBx0685FwJaYN1vVScKVUgXHb2zyqXZg/pub?output=html&widget=true#gid=2)). Have you seen any best practices how to maintain such table in GitHub?

**Comment by whit537** [comment]
GitHub wraps CSVs pretty nicely, we could maybe take advantage of that. However, we don't have automatic sums as we do with a spreadsheet.
