### ISSUE TITLE
Personal queue projects

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#859]
How do you like the idea of personal project queues? Is that helpful for you to see what am I up to? https://github.com/gratipay/inside.gratipay.com/projects/2

The only drawback is that I can not add issues from other repos, like https://github.com/gratipay/access-dashboard/issues/29

**Comment by techtonik** [comment]
![image](https://cloud.githubusercontent.com/assets/515889/19601476/26d3895e-97b2-11e6-9556-0ebd0de4e08c.png)

**Comment by mattbk** [comment]
I didn't even know this was possible. :+1:

**Comment by techtonik** [comment]
Me too. That's a ratrher fresh feature of GitHub https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features

**Comment by techtonik** [comment]
> The only drawback is that I can not add issues from other repos, like gratipay/access-dashboard#29

Found a way to add notes. Neat. =)

**Comment by whit537** [comment]
Nice! 💃

**Comment by techtonik** [comment]
Okay, so you don't mind if a play with it for a while. Great. =)

**Comment by whit537** [comment]
No, I don't mind at all. I say go for it! :)

**Comment by techtonik** [comment]
Now in https://github.com/orgs/gratipay/projects =)

**Comment by whit537** [comment]
I've moved the remaining open items from your IG project to your new org project, and I've closed the IG project. 👍
