### ISSUE TITLE
RSVP List

### ISSUE THREAD

**Issue by clone1018** [gratipay/inside.gratipay.com#86]
## What?

The purpose of the Gratipay company retreat is to strategize about the year ahead, sprint on Gratipay and related projects, and to continue to build meaningful relationships.

## When?

![countdown!](http://secondapps.com/countdown/t1420236000z1.png)
(Due to GitHub's image caching this may be out of date)

Starts: Friday January 2, 2014 at 5:00pm
Ends: Monday, January 5, 2014 at 12:00pm

## Where?

716 Park Road, Ambridge, PA 15003

### Yes: 7
1 @clone1018
1 @seanlinsley 
1 @whit537 
1 @rummik 
1 @colindean 
1 @kaguillera 
1 @oakes

### Maybe: 3

1 @dmk246 
1 @weallhave24hrs
1 @hurlothrumbo

### No: 2
1 @chrisdev
1 @patcon

**Comment by patcon** [comment]
Sorry guys, the airline lost all my luggage on the way to Toronto, so I think that's the final complication that's going to derail this plan for me :(

Wish I could make it, but I really can't afford it right now! Love you guys, obvs

**Comment by patcon** [comment]
*you all

**Comment by whit537** [comment]
*yinz ;-)

Love you, too, @patcon! Sorry to hear about the luggage and that you can't make it. :-(

**Comment by whit537** [comment]
Heard from @kaguillera in private email, sounds like he's planning to make it!

**Comment by clone1018** [comment]
I'll be in Ambridge tomorrow, if anyone needs to contact us my number is 262-299-4601

**Comment by whit537** [comment]
I just put @oakes @dmk246 @weallhave24hrs @hurlothrumbo down as Maybes.

**Comment by oakes** [comment]
I will be there! Sorry for not confirming earlier; I am at a strange time in my life.

**Comment by whit537** [comment]
@oakes Huzzah! What else is new. :-P

**Comment by whit537** [comment]
I think @rummik and @kaguillera could use a ride out from Pittsburgh, because otherwise they're both left with the bus.

@oakes @colindean Any chance either of you could pick them up?

**Comment by galuszkak** [comment]
Have good time on Retreat

**Comment by whit537** [comment]
Thanks, @galuszkak! :dancer:

**Comment by joeyespo** [comment]
Have a good time, all!

**Comment by whit537** [comment]
Thanks, @joeyespo! Off to a good start. @clone1018 and @seanlinsley totally made some excellent cottage pie tonight. :D
