### ISSUE TITLE
Join Hacktoberfest

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#860]
Hey! =) It's a bit late, but how about adding hacktoberfest label to interesting issues for newcomers? https://hacktoberfest.digitalocean.com/

**Comment by mattbk** [comment]
> Here are tips for creating a good Hacktoberfest issue in your project:
> 
> - Add a CONTRIBUTING.md file with contribution guidelines to your repo.
> - Choose issues that have a well-defined scope and are self-contained.
> - They should serve as good introductions to the codebase.
> - Consider adopting a code of conduct to foster a greater sense of community.

**Comment by mattbk** [comment]
Done for the year. Closing until 2017.
