### ISSUE TITLE
Onboard @JessaWitzel

### ISSUE THREAD

**Issue by JessaWitzel** [gratipay/inside.gratipay.com#866]
Onboard me please! You are fabulous.

**Comment by whit537** [comment]
Okay! So! First thing is to get Gratipay running locally. Hopefully [the README](https://github.com/gratipay/gratipay.com#welcome-to-gratipay-) has what you need. If not, the rule of thumb is "spend an hour, but not more." You should spend an hour bashing your head against the wall and trying to figure out whatever-the-problem is, but after an hour you should ask someone for help to avoid simply spinning your wheels. This ticket is your place to ask whatever questions you have about anything Gratipay-related, including installing the software for the first time, but anything else as well. Can you work with that?

Depending on your comfort level we can also start off with a video call if that's helpful. Let me know and we can schedule something (maybe @kaguillera would be up for helping with that?).

May I add you to https://gratipay.com/Gratipay/distributing/? You'll need to a) join [Gratipay](https://gratipay.com/), b) [verify an email address](https://gratipay.com/about/me/emails/), and c) [add a national identity](https://gratipay.com/about/me/identities/) before I can do that.

**Comment by JessaWitzel** [comment]
Hey! 



You may add me to /distributing. I've gone ahead and taken the join steps. I will get Gratipay running locally later today by hook or by crook and if I get stuck I'll let you know through the ticket! 



Thank you!



Jessa




---- On Sat, 29 Oct 2016 06:53:17 -0700Chad Whitacre &lt;notifications@github.com&gt; wrote ----




Okay! So! First thing is to get Gratipay running locally. Hopefully the README has what you need. If not, the rule of thumb is "spend an hour, but not more." You should spend an hour bashing your head against the wall and trying to figure out whatever-the-problem is, but after an hour you should ask someone for help to avoid simply spinning your wheels. This ticket is your place to ask whatever questions you have about anything Gratipay-related, including installing the software for the first time, but anything else as well. Can you work with that?

Depending on your comfort level we can also start off with a video call if that's helpful. Let me know and we can schedule something (maybe @kaguillera would be up for helping with that?).

May I add you to https://gratipay.com/Gratipay/distributing/? You'll need to a) join Gratipay, b) verify an email address, and c) add a national identity before I can do that.

**Comment by whit537** [comment]
> You may add me to /distributing.

Done! Thank you and welcome aboard! 💃 

I'm pretty sure I communicated this the other night, but if not: it's your responsibility to set your own take. You can see everyone else's on the distributing page, along with the total available we've budgeted for weekly payouts (i.e., $50). You should set your amount to whatever best balances your own internal guilt and resentment. :-) As you get to know the rest of the team, if ever you feel that someone else's take is out of line, you may either bring it up directly with them (via a GitHub ticket if you wish), or you can mention it to me privately (chad@zetaweb.com) and I can start the public conversation.

> I will get Gratipay running locally later today by hook or by crook and if I get stuck I'll let you know through the ticket!

Awesome! Another technique I often employ is to basically live-stream my work on a GitHub ticket. It helps me a) stay focused, b) give others visibility into what I'm working on, and c) have something to refer to later (e.g., I just used [this comment](https://github.com/gratipay/gratipay.com/issues/3994#issuecomment-243819578) as the basis for [this script](https://github.com/gratipay/gratipay.com/pull/4165) to verify your identity). Especially if you go that route, you should @mention me or whoever else to get our attention.

**Comment by JessaWitzel** [comment]
Out of curiosity's sake, what did you verify about that information? Did you look up my DL # in some public db?

**Comment by whit537** [comment]
@JessaWitzel Great question! Looking up your info in some db is [the eventual plan](https://github.com/gratipay/gratipay.com/issues/2449), but for now I just trusted you (though actually, I  _did_ fix a typo in your name ;).

**Comment by JessaWitzel** [comment]
The name on my license is Jessica but I go by Jessa. So you might want to have a "Legal Name" if you are going to actually verify the DL and a "preferred name". <3

**Comment by whit537** [comment]
@JessaWitzel I corrected "Wtizel" to "Witzel." Should've asked first, I guess. Sorry.

I expect we'll have to evolve the identity form one way or another once we start working with a third-party vendor to programmatically verify identities, based on their APIs. At this point we're only using the identity feature for people on the Gratipay team (it's generally available but not linked anywhere in the UI), so it's pretty low pressure.

**Comment by JessaWitzel** [comment]
Lol look at me not knowing my own last name. :)

**Comment by JessaWitzel** [comment]
@whit537 I have forked and am running locally! In the process I learned about keys. :) Now I will read code and try to get context. Let me know what you think I should do next.

**Comment by whit537** [comment]
Awesome! Let's find a good ticket for you to work on ... hmmm ...

**Comment by whit537** [comment]
I'm looking through the tickets that are on [a milestone](https://github.com/gratipay/gratipay.com/milestones). The one that maybe jumps out at me is https://github.com/gratipay/gratipay.com/issues/3602. I think that will mostly be backend work with a little bit of front end (mostly adding a "Close" button). We'll need to break that down into pieces to make it doable. Want to start thinking about that ticket and exploring the code that might be related? If you're up for it we can pick up on that ticket with talking about what exactly needs to happen there.

**Comment by JessaWitzel** [comment]
I can do that. How do I get a freshdesk log in? I don't believe that I set one up. 




---- On Sun, 30 Oct 2016 05:18:12 -0700Chad Whitacre &lt;notifications@github.com&gt; wrote ----




I'm looking through the tickets that are on a milestone. The one that maybe jumps out at me is gratipay/gratipay.com#3602. I think that will mostly be backend work with a little bit of front end (mostly adding a "Close" button). We'll need to break that down into pieces to make it doable. Want to start thinking about that ticket and exploring the code that might be related? If you're up for it we can pick up on that ticket with talking about what exactly needs to happen there.

**Comment by whit537** [comment]
> I can do that.

👍 💃 🌻 

> How do I get a freshdesk log in?

Let me know your email address (privately to chad@zetaweb.com if you like) and I will add you as an "Occasional" Freshdesk user. Each time you login you'll use a $2 "day pass". Make sure you observe points (2) and (3) under "[Protecting User Privacy](http://inside.gratipay.com/howto/support-users)."

**Comment by whit537** [comment]
Also, I've invited you to Gratipay's GitHub org so you can make pull requests in the main repo (whether gratipay.com or inside.gratipay.com, cf. https://github.com/gratipay/inside.gratipay.com/issues/873) rather than having to fork.

**Comment by kaguillera** [comment]
I know that I am a little on this ticket but I am willing to help in anyway that I can.

**Comment by JessaWitzel** [comment]
Thanks @kaguillera  I'm jumping right in but am a brand spanking new programmer so am still trying to get the feel for everything. @whit537 my email address is Jessa@riotousliving.com. Does the day pass mean that gratipay is charged $2 for me logging in? I only wanted the log in because you reference two freshbooks links in the aforementioned ticket I could possibly work on. Is freshbooks your customer service/support system?

**Comment by JessaWitzel** [comment]
I also set my take at $1 for several reasons, primarily because then I can say that I made my first $1 programming but also because this week I will likely spend the most time with this code, reading and trying to understand the context. After this week I will set lower (I won't be contributing on part with others for a while I am certain).

**Comment by whit537** [comment]
> my email address is 

Cool, thanks. Freshdesk invite sent!

> Is freshbooks your customer service/support system?

Yup! We have two "full-time" seats, currently occupied by @mattbk (who handles most of our customer support) and myself (other things like our bank statements, etc. also funnel into Freshdesk).

> Does the day pass mean that gratipay is charged $2 for me logging in?

Yes. I say that not to dissuade you but to empower you with financial decision making. :-) We buy day passes in blocks of 10, automatically whenever we run out. Don't feel bad using them as needed to accomplish your hopes and dreams for Gratipay—understanding the context for the [team closing ticket](https://github.com/gratipay/gratipay.com/issues/3602) is certainly a valid use. Just (again) be careful to maintain the confidentiality of the info in Freshdesk. Thank you. :)

> I also set my take at $1 for several reasons

I was expecting you to set it to $6 based on our conversation. ;-)

> I made my first $1 programming

Woo-hoo! Let's do it! 💃

Have you ever made a PR before? Especially if not, I think we should start you off with a PR on #873, just to get the hang of things. The team closing ticket will be much more involved—I'd love to see you get code deployed to production sooner than that. Thoughts?

**Comment by whit537** [comment]
> I think we should start you off with a PR on 

Holy heck, I can't [keep up](https://github.com/gratipay/inside.gratipay.com/pull/874)! 😱 

!m @JessaWitzel &larr; that [means](http://motivate.im/) "You're doing good work!"
!m @kaguillera

**Comment by mattbk** [comment]
Hi @JessaWitzel!

If you (or anyone else) come across a reference to Freshdesk without context, give me a tag and I can check to see if I can anonymize it here (although I think crossposting is pretty standard). But as @whit537 said, log in if you need to. I didn't even realize I had a "seat." Since I'm not the best programmer, I usually spend time making sure I understand how things are supposed to work in order to explain them to people having problems.

**Comment by whit537** [comment]
@JessaWitzel Do you have the [test suite running locally](https://github.com/gratipay/gratipay.com#testing-)? That could be a good next step for you, because changes to Python will need to have tests with them, and you'll want to be able to run those locally before pushing to GitHub. Maybe give that a shot if you haven't already and let us know if you get stuck?

**Comment by JessaWitzel** [comment]
I get 50 errors in 3.17 seconds when I try to run make pytest. 
Makefile:70: recipe for target 'pytest' failed 
make: *** [pytest] Error 1

What am I doing wrong besides everything?

**Comment by rohitpaulk** [comment]
@JessaWitzel Is that all you see? Nothing else? 

One common fix is - Try running `make clean` followed by `make env` once again

**Comment by JessaWitzel** [comment]
@rohitpaulk no, I see a lot of stuff. Does this help? 
OperationalError: FATAL: database "gratipay-test" does not exist

Does that mean I don't have the test files downloaded?

**Comment by whit537** [comment]
@JessaWitzel That looks like a good clue to investigate, yes. :-) What have you tried so far to fix that error? Any hypotheses on what is causing it?

P.S. Debugging is Science Lite&trade;. :-)

**Comment by whit537** [comment]
> Any hypotheses on what is causing it?

Sorry, you already gave us a hypothesis!

> Does that mean I don't have the test files downloaded?

What experiment could you perform to test your hypothesis? :-)

**Comment by whit537** [comment]
Could you unpack your thinking behind the move from "database 'gratipay-test' does not exist" to "I don't have the test files downloaded"?

**Comment by JessaWitzel** [comment]
Welp, I have explored the various files I have in the gratipay.com project and I can see a bunch of tests when I 'ls' them in terminal. So I actually do know that I have them downloaded. I guess my thought process is that the error is reading that I do not have a database called gratipay-test that it is trying to locate and run?

**Comment by kaguillera** [comment]
Well done
!m @JessaWitzel 
Good thing I did not answer I did not know that this was a learning exercise @whit537

😸

**Comment by whit537** [comment]
@JessaWitzel Okay, so what's your mental model of how "the various files I have in the gratipay.com project" are related to "a database called gratipay-test"? What's the connection between the two?

**Comment by whit537** [comment]
@JessaWitzel And how much of the [README](https://github.com/gratipay/gratipay.com#local-database-setup) have you read? ;-)

**Comment by JessaWitzel** [comment]
So much of it but I don't understand a lot of it. Maybe I shall start working on a readme for brand new beginners? @wwitzel3 pointed out that I stopped reading about tests too soon when it failed and so we created the local database. Now I just have 5 tests failing so MUCH IMPROVE.

**Comment by whit537** [comment]
@JessaWitzel Good work! 💃 

Handy to have a @wwitzel3 around. ;-)

Let us know if yinz get stuck on the 5 failing tests! Progress! :D

**Comment by JessaWitzel** [comment]
@kaguillera what is !m?

**Comment by JessaWitzel** [comment]
I now have 4 failing tests. 
AttributeError: 'NoneType' object has no attribute 'package_manager" on test_sn_inserts_packages
same on test_sn_handles_quoting
same on test_sn_handles_empty_description_and_emails
and AssertionError on test_rs_syncs_a_readme

Halp?

**Comment by kaguillera** [comment]
if I had to hazard a guess without doing full research it is because you did not rebase. 
I am assuming that you don't have the most up-to-date master which you need to rebase on your branch. That would bring your branch up-to-date with the changes that were made on production/master ( including the package_manager table that we introduced recently)
@whit537 I hope that I am not give too much away.

P.S. !m - means good work

**Comment by JessaWitzel** [comment]
Looks like I was set up to match against my fork, which I set up before i was added as a contributor. But I now have it pulling from the correct place and it says I am "already up to date" when I git pull. I now have 3 errors but they are all related to the package_manager .

**Comment by JessaWitzel** [comment]
Also thank you so much! I am going to sleep and will try again in the AM. :)

**Comment by whit537** [comment]
> I now have 3 errors but they are all related to the package_manager .

@JessaWitzel Are they errors or skips? As of https://github.com/gratipay/gratipay.com/pull/4173 the test suite is supposed to skip the `package_manager` tests if you don't have the correct dependencies installed.

**Comment by whit537** [comment]
If they are skips, then I think you have succeeded in getting the test suite running locally, and we are ready to find an issue for you to dive into! 💃

**Comment by JessaWitzel** [comment]
They are not skips. Skips are Xs yes?

**Comment by JessaWitzel** [comment]
3 Fs, all Attribute Errors related to package_manager in tests/py/test_sync_npm.py

**Comment by mattbk** [comment]
Interesting, I have the same tests failing locally. Perhaps we are both missing something.

**Comment by mattbk** [comment]
Are you getting a message about `phantomjs` not being in PATH?

**Comment by JessaWitzel** [comment]
@mattbk I did get that message but it was because I didn't have phantomjs installed at all. Once I put it in the right place and cleaned and ran, that error went away.

**Comment by whit537** [comment]
@JessaWitzel What's the output of the following command? (Are you on a Mac?)

```
git log | head -n1
```

The output should look something like this:

```
$ git log | head -n1
commit add5c33923a61282c35e0ba66f07576ea9596b72
```

That will tell us precisely what code you are running.

**Comment by JessaWitzel** [comment]
commit f610ea21bc3b703c3d860cc762f34567be6e6328

**Comment by mattbk** [comment]
Looks like you're at https://github.com/gratipay/gratipay.com/commit/f610ea21bc3b703c3d860cc762f34567be6e6328.

**Comment by whit537** [comment]
Which _does_ [include](https://github.com/gratipay/gratipay.com/commits/f610ea21bc3b703c3d860cc762f34567be6e6328) #4180. Hmm ... @mattbk you say you're getting the same error?

**Comment by whit537** [comment]
I mean, we should get to the bottom of this, but @JessaWitzel you don't need to let this slow you down. Most of the time you'll be running just one or two test files, not the entire test suite. Let's find you a ticket to work on! :-)

**Comment by whit537** [comment]
How about https://github.com/gratipay/gratipay.com/pull/4130?

**Comment by whit537** [comment]
@JessaWitzel Do you use Slack? You are cordially invited to join us in http://inside.gratipay.com/appendices/chat! :-)

**Comment by JessaWitzel** [comment]
I feel pretty onboarded! Thanks!

**Comment by whit537** [comment]
Welcome aboard! 💃 🌻

**Comment by whit537** [comment]
Reopening to propose that we give @JessaWitzel Twitter access. [Technically](http://inside.gratipay.com/big-picture/operating-agreement) needs a vote of "100% of the subset of members who already have access to the system." I'm the only coop member with Twitter access (ya, @clone1018?), and the other person with Twitter access, @mattbk, [approves](https://gratipay.slackarchive.io/gratipay/page-100/ts-1506349090000163). Leaving this open for three days so that the rule of law may prevail. ☺️

**Comment by whit537** [comment]
Planning to grant Twitter access to @JessaWitzel on Thursday if no-one objects.
