### ISSUE TITLE
switch to Heroku Teams

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#871]
> We noticed you've been working with collaborators on apps such as **gratipay and gip-rocks**. We've got just the thing to help make your team even more productive on Heroku. We've now released [Heroku Teams](https://www.heroku.com/teams), and by moving your app and collaborators over, you can start to enjoy the many benefits of Teams, which lets you:
> - Keep all your team’s apps together, which makes it simple to onboard your team members and have a shared space to work on projects.
> - Give control to your team members by letting them manage paid add-ons.
> - Stop worrying about billing, because all your team apps and add-ons get billed to a single credit card.
> - And more — such as more granular permission controls, integration with Heroku Pipelines, and support for up to 25 teammates.
> 
> Once you’ve created your Heroku Team by clicking the button below, you can migrate your apps and collaborators over easily.

https://gratipay.freshdesk.com/helpdesk/tickets/5979

**Comment by rohitpaulk** [comment]
FINALLY

**Comment by rohitpaulk** [comment]
> Free upto 1-5 users

**Comment by whit537** [comment]
I've made a Gratipay team and invited @rohitpaulk (as admin) and @clone1018 (as member—we can upgrade if you want?).

I've transferred the `gratipay.com` app to the new team, however:

> App "inside-gratipay-com" could not be updated:
>
> App inside-gratipay-com could not be transferred. Upgrade your app to a hobby dyno or higher to transfer to a Heroku Team.

**Comment by whit537** [comment]
I've upgraded `inside.gratipay.com` to a hobby dyno and transferred it to the `gratipay` team. I've updated the budget to reflect the new $7/mo.

**Comment by whit537** [comment]
I've dropped `shields-io`, `img-shields-io`, and `badgr-co`, which are way old.

![screen shot 2016-10-31 at 7 37 21 am](https://cloud.githubusercontent.com/assets/134455/19852995/e7113798-9f3c-11e6-8cb1-1fadd14a071c.png)

**Comment by whit537** [comment]
I've dropped `heroku-postgres-38ec6efc` as well. There was no database connected to it, even.

**Comment by whit537** [comment]
That leaves `aspen-io`, `gratipay-access-dashboard` (horribly broken 😞 ), and `motivate-im` as personal apps for the vendors@gratipay.com account. I think we should leave those as personal apps for now to avoid paying another $21/mo.

**Comment by whit537** [comment]
(P.S. I've removed @pjz from the `aspen-io` Heroku app—hi @pjz! 👋 :)

**Comment by whit537** [comment]
I also transferred `gip-rocks` to the `gratipay` team, so current team apps are: `gratipay-com`, `inside-gratipay-com`, and `gip-rocks`.

**Comment by whit537** [comment]
Gosh. We've been paying $20/mo for an SSL endpoint on `img-shields-io`—an app that hasn't been routed to for years! :-/

![screen shot 2016-10-31 at 7 51 16 am](https://cloud.githubusercontent.com/assets/134455/19853325/e874d192-9f3e-11e6-8e03-0b6cd8736ef0.png)

**Comment by whit537** [comment]
I'm pretty sure our new monthly bill is $95:

- `gratipay`—$7 web dyno + $50 db + $20 SSL + ~$4 scheduler dynos
- `inside-gratipay-com`—$7 dyno
- `gip-rocks`—$7 dyno

**Comment by whit537** [comment]
[Budget](https://docs.google.com/spreadsheets/d/1p3DpF9ZLEsViBx0685FwJaYN1vVScKVUgXHb2zyqXZg/pub?output=html&widget=true) updated. Anything else here?

**Comment by whit537** [comment]
I've also removed @patcon from the `gratipay-access-dashboard` Heroku app. Hi @patcon! 👋  ❤️  ☺️

**Comment by whit537** [comment]
I've removed @clone1018 as an "App Member" from `gratipay` and `inside-gratipay-com`. You should be added back as a "Team Member" when you accept the invite.

Final formation:

| app | level | members | admins |
|:------|:-------|:-----------|:--------|
| `gratipay` | team | @clone | @rohitpaulk @whit537 @Gratipay |
| `inside-gratipay-com` | team | @clone | @rohitpaulk @whit537 @Gratipay |
| `gip-rocks` | team | @clone | @rohitpaulk @whit537 @Gratipay |
| `aspen-io` | personal | @whit537 | @Gratipay |
| `gratipay-access-dashboard` | personal | @whit537 | @Gratipay |
| `motivate-im` | personal | @whit537 | @Gratipay |

**Comment by JessaWitzel** [comment]
What do you use for budgeting? I see it reported on here in excel sheet format but how do you reconcile accounts?

**Comment by nobodxbodon** [comment]
@JessaWitzel maybe you have some similar thoughts like I mentioned in my [onboarding issue](https://github.com/gratipay/inside.gratipay.com/issues/878#issuecomment-260264820)?

**Comment by whit537** [comment]
@JessaWitzel We don't reconcile accounts. In addition to his onboarding issue, @nobodxbodon and I discussed this extensively under https://github.com/gratipay/inside.gratipay.com/issues/867#issuecomment-260169067. Let's move discussion to https://github.com/gratipay/finances/issues/28 ...
