### ISSUE TITLE
Release @gittip on Twitter

### ISSUE THREAD

**Issue by mattbk** [gratipay/inside.gratipay.com#877]
> Remember when @Gittip used to be daily tips on git. Maybe time to hand it back @Gratipay ?

https://twitter.com/MotoWilliams/status/793467125092409345

What say we? Has it been long enough since the name change?

**Comment by whit537** [comment]
I would be happy to hand it back. Wanna dig up the ticket where we did the transfer in the first place and figure out the reverse dance?

**Comment by rohitpaulk** [comment]
Hmm - What all are we willing to give back? How about the domain gittip.com?

**Comment by rohitpaulk** [comment]
> Wanna dig up the ticket where we did the transfer in the first place and figure out the reverse dance?

Ooh, I didn't know that we transferred it from someone.

**Comment by rohitpaulk** [comment]
https://github.com/gratipay/gratipay.com/issues/742 is the ticket

**Comment by mattbk** [comment]
Ping @codereflection. Would you be interested in [@gittip](https://twitter.com/gittip) again?

**Comment by whit537** [comment]
Pinged [on Twitter[(https://twitter.com/whit537/status/800902223496478720) as well.

**Comment by whit537** [comment]
No bites. We can reopen if that changes.

**Comment by motowilliams** [comment]
I'd be willing to take this over.  Happy to stand up a a site for of the domain as well. Thinking just a simple static gh pages account so the community can start collecting some cool tips and tricks for our favorite scm again.

Do you folks run github.com/gittips as well?

**Comment by whit537** [comment]
@motowilliams Let's do it! Drop me an email chad@gratipay.com and I will send you the password for the Twitter account.

**Comment by whit537** [comment]
> Do you folks run github.com/gittips as well?

Nope. [Looks like](https://github.com/gittips/gittips.github.io/commits/master) that is @anurse?

We do have https://github.com/gittip, though, if you're interested in that.

> How about the domain gittip.com?

I think we want to keep that, to preserve redirects. Maybe gittip.org though?

**Comment by anurse** [comment]
"gittips" was just a random site I created when I had some git tips to share. It's not related to any twitter account or domain name currently.

**Comment by whit537** [comment]
@anurse Interested in collaborating with @motowilliams on a new Git Tips effort? :)

**Comment by anurse** [comment]
Afraid I don't have a lot of free time right now, sorry!

**Comment by whit537** [comment]
No worries, cheers! :-)

**Comment by codereflection** [comment]
Glad to see someone is willing to take this over. Apologies for the late response, life has been far to busy and I wouldn't be able to put any effort into maintaining the handle on Twitter.

**Comment by whit537** [comment]
For the record, this will break links such as at https://github.com/gratipay/gratipay.com/issues/1031#issuecomment-19545684.

**Comment by whit537** [comment]
I've heard from @motowilliams in private email, asking for Twitter, the @gittip org, and gittip.org. And my furniture. :P

🏀  is in my court ...

**Comment by whit537** [comment]
I updated that one link, and I've closed https://gratipay.com/~Gittip/.

**Comment by whit537** [comment]
@motowilliams I've invited you to be an owner of the @gittip org, and I've emailed you the password to the Twitter account. Now for the domain ...

**Comment by whit537** [comment]
I've also mailed you an iwantmyname.com transfer authorization code for gittip.org. I believe that's everything you need to achieve your dreams! 💖

**Comment by whit537** [comment]
Domain transfer approved under https://gratipay.freshdesk.com/helpdesk/tickets/6775.

**Comment by whit537** [comment]
I've deleted `gittip.org` in DNSimple.

**Comment by mattbk** [comment]
Looks like we're done?

**Comment by clone1018** [comment]
gittip.org and www.gittip.org are now removed from our SSL certificate at LetsEncrypt/Heroku.
