### ISSUE TITLE
onboard @nobodxbodon

### ISSUE THREAD

**Issue by nobodxbodon** [gratipay/inside.gratipay.com#878]
My name is Xuan, and [here](https://www.linkedin.com/in/xuanwu)'s my linkedin page, and in my repository are some of my small OS projects. 

My main interest is to volunteer for marketing:

- take the most advantage of openness, to market the brand
- attract more contributers

First question:

- could I use other web framework than Aspen when contributing code?

**Comment by whit537** [comment]
Huzzah! Thanks for stepping forward! 💃 

(For reference: https://github.com/gratipay/inside.gratipay.com/issues/316#issuecomment-257278115.)

> could I use other web framework than Aspen when contributing code?

We use Aspen for three sites, [`gratipay.com`](https://github.com/gratipay/gratipay.com), [`inside.gratipay.com`](https://github.com/gratipay/gratipay.com), and [`gip.rocks`](https://github.com/gratipay/gip.rocks). If you like JavaScript you might check out our widget server, [`grtp.co`](https://github.com/gratipay/grtp-co). If you like Rails, see [`gratipay-access-dashboard`](https://github.com/gratipay/gratipay-access-dashboard), which is woefully broken, and should probably be killed if no-one is going to maintain it.

> My main interest is to volunteer for marketing:

Awesome! What are your ideas here? What do you think we should do?

> my linkedin page

Are you still in San Francisco? I just booked a trip (#867) out there for the next two weeks! We should get together!

**Comment by mattbk** [comment]
/me crosses fingers that @nobodxbodon likes JS...

**Comment by nobodxbodon** [comment]
I'm considering to focus on the accounting part and build some kind of monitor/dashboard for cost&income of Gratipay (example: Buffer's [matrix](https://buffer.baremetrics.com/)). If it already exists, I'll try to improve and integrate it with other parts of the business. This can serve multiple purposes:
- avoid irrelevant cost like [this](https://github.com/gratipay/inside.gratipay.com/issues/871#issuecomment-257274836)
- better forecast and planning
- last but not least, highlight the openness of the business

I'm currently in the Bay area, but is about 1 hour away from SF. I developed with Python in some school projects, but not quite in business apps, similar with RoR. My main programming languages are Java (in work) and then Javascript (personal projects like browser extensions). Plus MySQL (in work) and a little PostgreSQL in personal project (one small personal project deployed on Heroku used that). I do like JS, mostly as ameteur, why?

**Comment by mattbk** [comment]
> I do like JS, mostly as ameteur, why?

I was mostly joking...by default I've been the most recent person responsible for widgets since I really wanted them to work again.

**Comment by nobodxbodon** [comment]
> I was mostly joking...by default I've been the most recent person responsible for widgets since I really wanted them to work again.

Cool. Your reply drove me to explore why the widgets were broken, in related ticket [#103](https://github.com/gratipay/grtp.co/issues/103#issuecomment-215236272), and [this open issue](https://github.com/gratipay/gratipay.com/issues/3924) (is there any blocker for this one? sounds like a short change in source code).

Another notice is, there are so many open issues, that a new comer like me can hardly tell which has high priority or severity. Is there some high-level roadmap kind of document that outlines the plan and priorities?

**Comment by whit537** [comment]
@nobodxbodon Our roadmap (such as it is) is in the ticket description on the weekly core [radar](https://github.com/gratipay/inside.gratipay.com/labels/Radar) ticket. We do have an [accounting system](https://github.com/gratipay/finances) that could use some attention. Want to get together in person next week or the week after? What is your availability?

**Comment by nobodxbodon** [comment]
@whit537 thanks the radar is pretty comprehensive. I wonder if there's an easy way to show diff between each radar reports, which may tell more clearly what's accomplished and newly added.
The best time for me are lunch time in most weekdays. Otherwise maybe the afternoons of weekends, or some evenings if those don't work. BTW I'm in Sunnyvale.

**Comment by whit537** [comment]
> I wonder if there's an easy way to show diff between each radar reports, which may tell more clearly what's accomplished and newly added.

I think it will be better to move most of that content to pages on [Inside Gratipay](http://inside.gratipay.com/) (#880). That way we can track history w/ Git. The reason the core radar is so overloaded is that we tried having multiple radars, but that got to be too much (#828) and copying all the extra content to the core radar was the lowest hanging fruit.

> [this open issue](https://github.com/gratipay/gratipay.com/issues/3924) (is there any blocker for this one? sounds like a short change in source code).

@nobodxbodon Wanna tackle this one? :-)

**Comment by whit537** [comment]
@nobodxbodon May I add you as a GitHub contributor (so you can make a PR for https://github.com/gratipay/gratipay.com/issues/3924 in the main repo rather than in a personal fork) and to the Gratipay money [distribution](https://gratipay.com/Gratipay/distributing/) (so you can start taking money! :)?

**Comment by nobodxbodon** [comment]
@whit537 sure glad to be a contributor. I've no problem with being added to Gratipay money distribution, but most likely I won't take any for a while.

**Comment by whit537** [comment]
> glad to be a contributor

Invite sent! :-)

> I've no problem with being added to Gratipay money distribution

Cool. You'll need to [add and verify an email](https://gratipay.com/about/me/emails/), set it as [your PayPal](https://gratipay.com/about/me/routes/paypal), and [add an identity](https://gratipay.com/about/me/identities/) before I can add you to the distribution list.

**Comment by whit537** [comment]
@nobodxbodon Picking up from https://github.com/gratipay/inside.gratipay.com/issues/878#issuecomment-258068304 and https://github.com/gratipay/finances/issues/3#issuecomment-258594695 ... any interest/availability in getting together this Saturday the 12th to bring you up to speed on the finances? SF or Sunnyvale or in between? Coupa in Palo Alto?

**Comment by nobodxbodon** [comment]
@whit537 sounds good to me. I'm not sure if morning or afternoon is better for me on Saturday. Shall we confirm on Thursday or Friday through email?

**Comment by whit537** [comment]
@nobodxbodon Sure, sounds good. chad@zetaweb.com :)

**Comment by nobodxbodon** [comment]
Here's a mock of the cost part, based on current finance spreadsheet. After discussion, it occurs to me that links of related issues in github can address the "why" and "how" to each cost for business handlers clearly. They serve as sources for (especially external) tech guys to check details and comment, as well as index of internal how-to documents. It's not a strict UI mock of the page, and mainly demo the content that needs to be associated.
![mock - accounting cost 20161112_220131](https://cloud.githubusercontent.com/assets/392497/20243993/575b313e-a924-11e6-85b9-8983cc26596a.jpg)

**Comment by nobodxbodon** [comment]
As a [pretotype](http://www.pretotyping.org/), how about I start with some mostly static page(s), instead of a Django app, and see if they look right?

**Comment by nobodxbodon** [comment]
@whit537 may I ask if there's traffic monitoring carried out currently? I see some efforts [before](https://github.com/gratipay/inside.gratipay.com/issues/101).

**Comment by nobodxbodon** [comment]
@whit537 I wonder if Buffer.com can be used to some important announcements? The free plan seems sufficient for that usage for now.

**Comment by mattbk** [comment]
@nobodxbodon re: analytics, here's some more: https://github.com/gratipay/gratipay.com/issues/3121

**Comment by nobodxbodon** [comment]
@mattbk thanks, but wrong link?

**Comment by mattbk** [comment]
Yes, oops. Will dig it up again.

**Comment by nobodxbodon** [comment]
@whit537 as I'm looking at the finance spreadsheet again, it seems the top 3 items makes more than half of the cost. I'm interested in the finer breakdown, like the heroku instances involved, etc. These will be necessary for the mock [above](https://github.com/gratipay/inside.gratipay.com/issues/878#issuecomment-260169164) as well. My guess is there can be savings somewhere, but I won't be sure unless I see what detailed items are burning money and why. Could you point me to some reference issues please?

**Comment by whit537** [comment]
> Could you point me to some reference issues please?

I'm not sure what issues to point you to about where we might be burning money. :-( Is that what you're asking for here?

**Comment by nobodxbodon** [comment]
> I'm not sure what issues to point you to about where we might be burning money. :-( Is that what you're asking for here?

Kind of. According to the [design](https://github.com/gratipay/inside.gratipay.com/issues/878#issuecomment-260169164), each cost should be associated with the reasons and related tech documents like setup steps, so that it'll be easier to review (is it necessary? any alternatives? etc).

As mentioned, the top 3 services (Paramount, Heroku, Travis) makes half of the cost, according to the current finances spreadsheet. So I'm particularly interested in the issues that describe the initial considerations and decision making to choose these services (plans)

**Comment by whit537** [comment]
Searching for "paramount" in this repo turns up https://github.com/gratipay/inside.gratipay.com/issues/831.

Searching "pay for travis" turns up https://github.com/gratipay/inside.gratipay.com/issues/102.

We've been hosted on Heroku since the beginning, so there's no ticket about _initial_ considerations and decision there. You've seen some of the more recent discussion about Heroku.

I should say that in general we want to pay for services, even if we could get them for free. The reason is to be consistent with our own principles: the whole point of Gratipay is to pay people for things you're grateful they provide! :-)

**Comment by nobodxbodon** [comment]
> we want to pay for services

I'm all for it, but just want to make sure if we are not overpaying. Heroku takes $95/month now. Without knowing the configs, I can't tell if it's worthwhile. Still [this](https://blog.jalada.co.uk/heroku-is-no-longer-the-hobbyists-friend/) seems to indicate there's cheaper and not worse performed alternatives. I only used heroku for hobby projects so I can be ignorant about the extra goodies heroku brings.

HEADS UP: I see "Always free for open source projects" on [Travis](https://travis-ci.com/plans)??

**Comment by nobodxbodon** [comment]
> even if we could get them for free

This depends IMO. If we can get Travis for free, I think it make sense, especially when it takes 13% of our fixed cost

**Comment by nobodxbodon** [comment]
More reviews of current services:

- PagerDuty: any extra features compared with free services like http://uptimerobot.com/?
- FreshDesk: seems the two starting levels (free and $19/month) can be enough for our needs. Besides I don't see $38/month plan
- iwantmyname: maybe worthwhile to compare with [other providers](https://stackshare.io/stackups/iwantmyname-vs-godaddy-vs-namecheap)
- Github: are we having private repository at all?
- Sentry: is free plan not enough for us? Besides, I don't see corresponding plan [here](https://sentry.io/pricing/)
- Transifex: don't see corresponding plan [here](https://www.transifex.com/pricing/)
- MaxCDN: don't see corresponding plan [here](https://www.stackpath.com/pricing/?utm_campaign=MaxCDN%20Redirect&utm_medium=home&utm_source=maxcdn)

**Comment by mattbk** [comment]
- FD might be $19 per seat and we have two seats
- iwantmyname might have been chosen for philosophical reasons
- GitHub: Yes, we have some private repos for security and logs

I don't know about the others. Nice work on the price comparisons!

**Comment by whit537** [comment]
@nobodxbodon How about making a new ticket in the inside.gratipay.com repo to talk about our budget and our spending and trimming it up? :-)

**Comment by kaguillera** [comment]
!m @nobodxbodon... Clearly he is here to whip us in shape finance wise.

**Comment by whit537** [comment]
@nobodxbodon Do you use Slack? You are cordially invited to join us in http://inside.gratipay.com/appendices/chat! :-)

**Comment by nobodxbodon** [comment]
About reviewing PR, may I ask if there's protocol documented somewhere? Seems we go with procedure below:

- A request for review from B, C...
- get +1 from B and/or C...
- B/C ... submit and delete branch

If A request review from 3 persons, does she need +1 from all 3? If not, how can the person who submit know if other reviewers don't have comments before submitting? Or is there some period for reviewing?

**Comment by mattbk** [comment]
Using the review system is pretty new, as is having more than one person around to review (in recent memory). So this is good to talk about.

**Comment by whit537** [comment]
> Using the review system is pretty new

GitHub's review system itself is [pretty new](https://github.com/universe-2016). ;-)

> If A request review from 3 persons, does she need +1 from all 3?

No. Think of those simply as invitations.

> If not, how can the person who submit know if other reviewers don't have comments before submitting? Or is there some period for reviewing?

There's no period for reviewing. Anyone can add comments or commits to a PR at any time, and when two or more agree that it's ready, then it's ready. The only rule of thumb is that the last person to commit should not merge (we do break this rule occasionally, usually because we don't have enough reviewers and we need to keep shipping).

Think of PRs as being owned by the Gratipay team as a whole. Unfortunately, GitHub's review workflow encourages a rather individualistic and bureaucratic relation, where a PR is owned by a single person, who has to seek formal approval from others—but that's not how we operate.

Does that help?

**Comment by whit537** [comment]
Though now that I think about it, the reality is more subtle than that. The rule of thumb still applies, but basically anyone who wants to care about a given PR is responsible to get in there and be part of the conversation. We need at least two people, but if a third sticks their head in then the PR now has three people who need to agree by consensus before someone besides the last committer merges.

**Comment by whit537** [comment]
@nobodxbodon May I give you permissions on the logs private repo? We store our raw financial data there.

**Comment by nobodxbodon** [comment]
@whit537 sounds good, thanks. May I check, if it's private only because we need to mask the bank account numbers?

**Comment by whit537** [comment]
@nobodxbodon Not just bank account numbers, but also phone numbers and such that leak through bank statements in the description field. That's for our operations accounts. For our escrow accounts we want to protect the privacy of participants for individual transfers. We're comfortable reporting aggregates but we need to take care with personally identifiable transactions.

**Comment by whit537** [comment]
I've added you to the @gratipay/logs team alongside @kaguillera.

![screen shot 2017-01-10 at 3 02 18 pm](https://cloud.githubusercontent.com/assets/134455/21822623/e981b52a-d745-11e6-87fb-428ba5effaaf.png)

**Comment by whit537** [comment]
P.S. Do you feel as though you're onboarded by now? :-)

**Comment by nobodxbodon** [comment]
Thanks for explaining the privacy policy. I suppose it's already on our website somewhere? 

Yes I feel quite onboarded :)

**Comment by whit537** [comment]
!m @nobodxbodon 💃

**Comment by whit537** [comment]
Reopening from @mattb at https://github.com/gratipay/inside.gratipay.com/issues/993#issuecomment-274228691 ...

May I give you admin privileges on gratipay.com, @nobodxbodon?

**Comment by nobodxbodon** [comment]
@whit537 yes please. Thanks. Could you also share some reference about what admin can/should do? I don't see obvious link in inside. portal. 

Besides, is there an existing issue about adding text search ability in inside.gratipay.com? Like those search bar powered by some search engine?

**Comment by whit537** [comment]
Grep the code for `ADMIN` to see what admins can do, we don't have docs.

> Besides, is there an existing issue about adding text search ability in inside.gratipay.com? Like those search bar powered by some search engine?

Not that I know of.

Added as admin!

**Comment by whit537** [comment]
```
gratipay::MAROON=> select username from participants where is_admin;
┌─────────────┐
│  username   │
├─────────────┤
│ clone1018   │
│ rohitpaulk  │
│ whit537     │
│ aandis.     │
│ nobodxbodon │
│ mattbk      │
└─────────────┘
(6 rows)
```

**Comment by whit537** [comment]
Next step: shall we give you permissions on the logs repo so you have access to bank statements for https://github.com/gratipay/finances/issues/3#issuecomment-275812805?

**Comment by nobodxbodon** [comment]
@whit537 is it the same log repo in https://github.com/gratipay/inside.gratipay.com/issues/878#issuecomment-271682275? I see the latest statements are 2016/10. Could you add 2017/01 or if that's not avaible yet then 2016/12?

**Comment by whit537** [comment]
> is it the same log repo in https://github.com/gratipay/inside.gratipay.com/issues/878#issuecomment-271682275?

Yes!

> Could you add 2017/01 or if that's not avaible yet then 2016/12?

Done in https://github.com/gratipay/logs/commit/a20223548edaeb72c372c77142d4547117d2df22 through 2017-01!

Unfortunately we lost the detailed CSV for PNC for 2016-11. I thought they gave us 90 days but it appears to be three calendar months. Missed it by two days. :-/ We still have the PDF from that month though, so we can produce a CSV if needed.

**Comment by whit537** [comment]
Anything else needed here for now, or can we reclose?

**Comment by nobodxbodon** [comment]
Thanks!

**Comment by whit537** [comment]
Reopening once again to ask ... shall we grant you access to the vendors@gratipay.com account? That is where we collect invoices and receipts, which you will need if you're to start recording our finances as at https://github.com/gratipay/finances/issues/3#issuecomment-277424062.

**Comment by nobodxbodon** [comment]
Is that an email account? A bit unusual to me, but OK.

**Comment by whit537** [comment]
Why unusual? Sharing access to the vendors@gratipay.com email account means that we can distribute the work that is associated with that account, including tracking our finances, and managing our billing relationships.

**Comment by whit537** [comment]
@nobodxbodon What is the best email to use to invite you to Freshdesk (where we manage vendors@)?

**Comment by nobodxbodon** [comment]
@whit537 fromwheretowhere.service@gmail.com please.

**Comment by whit537** [comment]
I've invited you to a full-time seat as an agent role with access to the vendors group. You should see a backlog of four pages of tickets that are waiting to be entered into our finances since December when @kaguillera and I started batching those up.

**Comment by nobodxbodon** [comment]
@whit537 thanks. As this seat costs, is there any other tasks (hopefully not too time intensive) than reviewing receipts, that you think proper for me to handle through freshdesk?

**Comment by whit537** [comment]
@nobodxbodon I dropped myself to an occasional seat, so this is not adding to our cost. I think once you get in there, you will find that there is plenty to do to stay on top of the vendors@ queue. :)

**Comment by whit537** [comment]
@nobodxbodon I guess let's give you PayPal access for https://github.com/gratipay/finances/pull/38#issuecomment-280390947, ya?

**Comment by whit537** [comment]
They have a pretty fine-grained permission model, so we should be able to limit you to read-only reporting perms if that's cool.

**Comment by nobodxbodon** [comment]
@whit537 read only reporting perms sounds good to me. Thanks.

**Comment by whit537** [comment]
Let's try this to start with, may not be permissive enough. Sending login info in private email ...

![screen shot 2017-02-16 at 5 26 45 pm](https://cloud.githubusercontent.com/assets/134455/23044194/2aaa7afc-f46d-11e6-8876-080115c9603f.png)

**Comment by mattbk** [comment]
Should update http://inside.gratipay.com/appendices/access.

**Comment by whit537** [comment]
@nobodxbodon I've dropped you back to occasional on Freshdesk per [slack](https://gratipay.slackarchive.io/gratipay/page-76/ts-1489816174214625) (and I've bumped myself back up to full-time).
