### ISSUE TITLE
Go to US PyCon 2017!

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#889]
&larr; [2016](https://github.com/gratipay/inside.gratipay.com/issues/557)

May 17-25, 2017 in Portland, Oregon.

http://pycon.blogspot.ca/2016/11/registration-is-open-for-pycon-2017.html

EuroPython 2017: #894.

**Comment by JessaWitzel** [comment]
90% sure I'm going to Euro Py so if you figure out a way for me to rep gratipay usefully through your time at Pycon let me know. :)

**Comment by whit537** [comment]
@JessaWitzel Nice! Let's get you some stickers and/or heartcoins or something. Wanna make a separate ticket for Euro Python?

**Comment by whit537** [comment]
(I've clarified the scope of this one to US PyCon.)

**Comment by whit537** [comment]
I think we should go to PyCon this year. That was our strongest community base back in the day. Now that we're ramping up again we should reconnect.

**Comment by kaguillera** [comment]
Where and when is it?

**Comment by whit537** [comment]
Early bird registration is probably over soon if it's not already.

**Comment by JessaWitzel** [comment]
Talk proposals are due this year on 3 January 2017: https://us.pycon.org/2017/speaking/talks/
Registration just opened Nov 7th. Early bird is for the first 800 tickets sold.

**Comment by whit537** [comment]
Ah, I didn't realize talk proposals were still open! I may pitch one presenting our audit of Cryptography (https://github.com/gratipay/gratipay.com/pull/3998).

**Comment by whit537** [comment]
Talk proposals are due today. I am letting this slide.

**Comment by whit537** [comment]
Leaning against this, in favor of OSCON, which is two weeks earlier. I've never been to OSCON.

**Comment by whit537** [comment]
I am letting go of this. It's in Cleveland the [next two years](https://twitter.com/mpirnat/status/729835027106762752), which is much easier for me to get to. If anyone else is going we can talk about sending more pennies or something, but I'm going to close this for now.
