### ISSUE TITLE
come up with a growth framework

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#89]
Started as: "go through bullseye exercise." Scope expanded to be about coming up with a growth framework generally.

### Bullseye

http://tractionbook.com/bullseye.pdf

#### Long-shot

**Comment by whit537** [comment]
Another tack: What is the pain point we address?

Patreon addresses [a crystal-clear pain point](https://www.youtube.com/watch?v=l1-3AYgZRFQ#t=34m04s):

> Patreon is not for people starting making content, it's not for people with no fans. Patreon is for people on the cusp of making a living, who have hundreds of thousands of fans. It's for people who are micro-celebrities, and for people who are making stuff and having tremendous success, and are still working at Starbucks for ten dollars an hour, two days a week, because they can't afford to do it with just their ad revenue.

In thinking through [how we're different from Patreon](https://medium.com/gratipay-blog/how-is-gratipay-different-from-patreon-1f828d977935), it strikes me that we don't have nearly so crisp an answer.

**Comment by whit537** [comment]
Speaking for myself, Gratipay addresses the pain point of wanting to be a productive contributor to society but not being able to stomach working for a closed company.

**Comment by Changaco** [comment]
Gratipay tries to address the pain point of sending and receiving recurrent payments easily without paying extra fees. The original use case was funding free software, and that generalizes to funding the commons (i.e. non-rival goods that are free to use), but really Gratipay is a neutral tool, like the Internet, and the beauty of such a tool is that it can have lots of uses its creators hadn't thought of.

**Comment by whit537** [comment]
["Teams Work"](https://medium.com/inside-gratipay/teams-work-dd2c35e5cd3) and [IRC](https://botbot.me/freenode/gratipay/2015-02-13/?msg=31935600&page=1)

**Comment by Changaco** [comment]
Reworded:

The original pain point was not being able to work on free software. That generalizes to not being able to work on improving the commons, i.e. non-rival goods that are free to use, because many business models don't apply to them, so it's difficult to fund that kind of work.

The way Gratipay tries to address this pain point is by providing a service that allows people to send and receive recurrent payments easily, so they can fund their work with donations.

But funding the commons is not the only use case for a payment service that doesn't have fees, and that's why you can't find *the* pain point that Gratipay addresses, because there are more than one.

**Comment by whit537** [comment]
[IRC](https://botbot.me/freenode/gratipay/2015-03-02/?msg=33172608&page=1)

**Comment by whit537** [comment]
Sent in private email:

> [Scott](https://twitter.com/scalgaro),
> 
Been thinkin'.
> 
Gratipay is a product for entrepreneurs who are building the next Wikipedia and need a payments & payroll platform. A relationship with an accelerator could be mutually beneficial since they would represent so many entrepreneurs, some of whom might be looking for Gratipay. :-)
> 
Any chance you'd be willing to share [Dave Blanchard](https://twitter.com/dave_blanchard)'s email address with me?
> 
> 
chad

**Comment by whit537** [comment]
Here's an organization that seems like a good fit for Gratipay:

http://www.therealjunkfoodproject.co.uk/

I just don't feel good about cranking up our sales engine right now when our product is so bad. :-(

**Comment by whit537** [comment]
Like, if I had more confidence in our product, I would compile a list of as many TRJFPs as I could, and I would contact them methodically.

**Comment by whit537** [comment]
1. We've had good luck with in-person marketing channels (user groups, conferences).
1. We want to reach non-geeks.
1. ∴ Let's try shopping malls!

**Comment by whit537** [comment]
Also, truck (#172) and pop-up store (#173).

**Comment by whit537** [comment]
Music festivals: #174.

**Comment by whit537** [comment]
The growth framework is:

 1. Build a kick-ass v1 product.
 1. Spread the word via in-person marketing channels.

I'm glad we got our feet wet with formal A/B testing and metric-driven development. !m @webmaven. I want to revisit those tools after v1 is out and we have another order or two of magnitude in scale.

**Comment by webmaven** [comment]
Just note that you should be A/B testing your in-person marketing efforts too.

**Comment by whit537** [comment]
Filing this here, at the risk of stirring the pot ... 🍯

> Stepping away from A/B testing does not mean we have abandoned efforts to improve conversion. Rather we are improving our conversion through other methods (yes, A/B testing isn't your only option).

https://www.stickermule.com/blog/hidden-costs-of-AB-testing

**Comment by webmaven** [comment]
Pot stirring is what some of us do best! 🥄🌪️🍯
