### ISSUE TITLE
how to fund individual OS contributors to big project like Python

### ISSUE THREAD

**Issue by nobodxbodon** [gratipay/inside.gratipay.com#892]
I just read this [Why I took October off from OSS volunteering](http://www.snarky.ca/why-i-took-october-off-from-oss-volunteering). Gets me thinking, as there are usually tens or hundreds of developers voluneerily contribute to big projects like Linux or Python, seems it's reasonable to allow individuals to get fund without "owning" a project. Is that possible currently or discussed before?

**Comment by whit537** [comment]
For this case the natural thing would be for this to go through the PSF. As a parallel, the Linux Foundation has a budget of $65 M ([up from](https://www.linkedin.com/in/mikewoster) $5 M seven years ago), and one thing they do with that is pay [Linus and others](https://www.linuxfoundation.org/about/linux-foundation-fellows).

**Comment by whit537** [comment]
What's the concrete task here on this ticket? How do we know when this ticket is done?

**Comment by nobodxbodon** [comment]
Maybe this is already supported? Say, @brettcannon (author of the post I referenced) can create a team on Gratipay and states he's active Python core developer, and be approved?

**Comment by whit537** [comment]
Yeah, that would work, too. A parallel example might be https://gratipay.com/debian-lts-by-freexian/.

P.S. Hi, @brettcannon! :-) 👋

**Comment by nobodxbodon** [comment]
Closing, as it's already supported.

**Comment by techtonik** [comment]
How it is supported? Where is the prooflink?

**Comment by whit537** [comment]
@techtonik https://github.com/gratipay/inside.gratipay.com/issues/892#issuecomment-260421128

**Comment by kaguillera** [comment]
Concern...is this not bring us back to Gratipay 1.0 where we were funding individuals and was that not an issue?

**Comment by mattbk** [comment]
That's my question as well. Gratipay can't be all things to all users. Some people will be left out because the team/project is not interested im being involved.
