### ISSUE TITLE
represent potential givers to reach out to project/site owners

### ISSUE THREAD

**Issue by nobodxbodon** [gratipay/inside.gratipay.com#893]
I imagine some givers would love to fund some project/site that are not registered on Gratipay. How about, let users freely give +1 to any project/site that they want to fund (need to avoid spam somehow), and then (or after accumulating certain numbers of supports) Gratipay try to reach out to the owner(s), and ask them to register if they want the fund?

A following thought is, create some browser extension, to allow people give the +1 easier when they browse the web, and the extension can also show the stats (amount of fund, etc) if the site/project is already on Gratipay?

**Comment by mattbk** [comment]
I would be careful with this. It would be easy for someone to accuse us of manipulating the numbers in order to fake a reason to initiate contact.

**Comment by nobodxbodon** [comment]
For sure, however IMO it's better than initiating contact without any number :) Besides, is it legally possible to allow givers give money to some target (project/site) who is not registered yet, and Gratipay keeps those money for them (having clear objects), and reach out to owners? That way it'll be "see how much you can receive through us" than just "see how many people +1'ed your project".

**Comment by mattbk** [comment]
> Besides, is it legally possible to allow givers give money to some target (project/site) who is not registered yet, and Gratipay keeps those money for them (having clear objects), and reach out to owners?

This was part of 1.0. There were legal implications (but no action) of accepting money on behalf of someone else without that person's explicit permission. Still in place as of https://github.com/gratipay/inside.gratipay.com/issues/180#issuecomment-100377966, but there is a point at which it was removed.

**Comment by nobodxbodon** [comment]
Now I see part of reason why we chose to fund organization/projects over individual contributors. Generally, OS contributors have much fewer "fans" than media content creators (like those on Patreon). Individual OS contributor can only get recognized in a very limited group, even if they contribute a lot. Org/projects are much more recognized. On the other hand, org/projects are only recognized by the tech world, which is very small, compared to the general public. Maybe that's why we don't grow like Pateon. 

Another thought is, most of the OS contributs are actually already "funded" by corporate businesses, as most of them have a "day job". So cooperative businesses owns OS projects in this way. 

From this point of view, corporate businesses would hardly be willing to "donate" through third party to OS teams/projects, without having a say about how those money gets distributed within the team. So many big OS projects that I see have commitees/boards consisting of representives from big businesses.

@whit537 Shall Gratipay be targeting at even larger group? Say, creators of internet contents (bloggers, etc) ? After all, the internet is only thriving because of the open content, and I consider OS projects as just a tiny part of it.

> At the session on Tuesday, computer scientists talked about how new payment technologies could increase individual control over money. For example, if people adapted the so-called ledger system by which digital currencies are used, a musician might potentially be able to sell records without intermediaries like Apple’s iTunes. News sites might be able to have a system of micropayments for reading a single article, instead of counting on web ads for money.

> “Ad revenue is the only model for too many people on the web now,” Mr. Berners-Lee said. “People assume today’s consumer has to make a deal with a marketing machine to get stuff for ‘free,’ even if they’re horrified by what happens with their data. Imagine a world where paying for things was easy on both sides.”
-- http://www.nytimes.com/2016/06/08/technology/the-webs-creator-looks-to-reinvent-it.html?_r=0

**Comment by whit537** [comment]
> Still in place as of https://github.com/gratipay/inside.gratipay.com/issues/180#issuecomment-100377966, but there is a point at which it was removed

Really? I thought we removed giving without registering way back in https://github.com/gratipay/gratipay.com/issues/28. I think the distinction is that, after #180, you couldn't even _pledge_—is that it?

**Comment by whit537** [comment]
> OS contributors have much fewer "fans" than media content creators (like those on Patreon). 

See https://github.com/gratipay/gratipay.com/issues/737 for our history on that one.

**Comment by nobodxbodon** [comment]
@whit537 thanks for the reference. Obviously Patreon got the group of active Youtube users (plus other video contents, as [Crashcourse](https://github.com/gratipay/gratipay.com/issues/737#issuecomment-21350979) is under their brand now), but a much larger opportunity would be the non-video or independent contents/sites, and OS-related projects are just a small part of it.

**Comment by whit537** [comment]
> a much larger opportunity would be the non-video or independent contents/sites

That's what [Flattr](https://flattr.com/) and others went for—there's a bunch listed on [See Also](http://inside.gratipay.com/appendices/see-also/). It's just such a hard sell, to get people to pay for free stuff. 😞

![screen shot 2016-11-15 at 4 27 52 pm](https://cloud.githubusercontent.com/assets/134455/20329991/80446038-ab50-11e6-8fda-d0b1f29b9818.png)

**Comment by whit537** [comment]
> A following thought is, create some browser extension, to allow people give the +1 easier when they browse the web, and the extension can also show the stats (amount of fund, etc) if the site/project is already on Gratipay?

Ooh! That's right, you like browser extensions. Have you noticed https://github.com/gratipay/gratipay-everywhere?

**Comment by whit537** [comment]
> I imagine some givers would love to fund some project/site that are not registered on Gratipay. How about, let users freely give +1 to any project/site that they want to fund (need to avoid spam somehow), and then (or after accumulating certain numbers of supports) Gratipay try to reach out to the owner(s), and ask them to register if they want the fund?

Reticketed as https://github.com/gratipay/gratipay.com/issues/4195. I think that's everything here?

**Comment by nobodxbodon** [comment]
> Ooh! That's right, you like browser extensions. Have you noticed https://github.com/gratipay/gratipay-everywhere?

Great to know it exists. @whit537 may I ask why it's designed to add button on each website? Seems pretty costly to maintain, as it'll break once the website changes layout. I did a quick test, and seems only github works now.

**Comment by whit537** [comment]
I don't remember who originally made it, but I think @clone1018 was involved? Happy to see alternate proposals, it's currently rather moribund.

**Comment by whit537** [comment]
@nobodxbodon What would you propose instead? :)

**Comment by nobodxbodon** [comment]
@whit537 IMHO, the extension's should have following features, ordered by priority:

1.  directly donate/pledge. If it's not possible (need login, etc), then link to corresponding page on gratipay.com. Ideally It should require no or little additional work to support additional websites.
2.  show simple stats of current site/project, including # of backers and/or donation volume
3.  show stats of user
4.  recommend the projects you may want to donate to (this requires some data of relevance between site/project)

**Comment by clone1018** [comment]
@nobodxbodon Would you still have a button on each site?

**Comment by nobodxbodon** [comment]
@clone1018 Hi Luke, glad to see your input. As mentioned [above](https://github.com/gratipay/inside.gratipay.com/issues/893#issuecomment-261748130), I hope not to dynamically insert element into each site that the extension wants to support.

**Comment by clone1018** [comment]
What would the functionality look like? What's an example user flow?

**Comment by nobodxbodon** [comment]
One possiblity of feature No.1 is to use the toolbar button (currently link to gratipay.com) to link to corresponding team/project page on gratipay.com, instead of using an inserted button on each website's page. The other features (No. 2,3,4) may be put in a popup that the toolbar button opens. Before making decision about the UI design, I'd prefer to confirm the features first.

**Comment by mattbk** [comment]
https://github.com/gratipay/gratipay.com/milestone/3 seems relevant here.

**Comment by nobodxbodon** [comment]
@mattbk are you refering to [#3183](https://github.com/gratipay/gratipay.com/issues/3183), which is the same as No. 4? Thanks for the reference, and glad to see it's already discussed. As I imagine the extension will just show a selected subset of what is shown on gratipay, and preferrably use the same layout to reuse as much as possible while developing. If the feature isn't yet implemented on server side, the extension just won't show the corresponding part.
