### ISSUE TITLE
Go to EuroPython 2017!

### ISSUE THREAD

**Issue by JessaWitzel** [gratipay/inside.gratipay.com#894]
And figure out how to rep gratipay when I'm so green/newb/know nothing. <3

--------------

US PyCon: #889.

Reticketed from https://github.com/gratipay/inside.gratipay.com/issues/889#issuecomment-259855573.

**Comment by whit537** [comment]
Woo-hoo! When is it? Link?

**Comment by JessaWitzel** [comment]
http://ep2017.europython.eu/ July 2017 in Rimini, Italy.

**Comment by whit537** [comment]
[slack](http://gratipay.slackarchive.io/gratipay/-/1483546508.001613/1483566398.001713/1483561861001668/)—@jessa is still planning to go, and would like to receive swag (pennies, stickers, etc.?) closer to the date.

**Comment by whit537** [comment]
Bouncing back here from https://github.com/gratipay/inside.gratipay.com/issues/990#issuecomment-276442658 ... are there sprints at EuroPython?

**Comment by whit537** [comment]
Event is past.
