### ISSUE TITLE
Improve payday documentation

### ISSUE THREAD

**Issue by mattbk** [gratipay/inside.gratipay.com#895]
...at inside.gratipay.com.

https://github.com/gratipay/inside.gratipay.com/issues/888#issuecomment-260427733 and other comments within.

**Comment by whit537** [comment]
Are you thinking we should update http://inside.gratipay.com/howto/run-payday? Or should we document this better on Gratipay.com?

**Comment by mattbk** [comment]
Howto/payday explains what to do but not how it works. Or should this be at readthedocs?

**Comment by whit537** [comment]
Yeah, probably readthedocs if internal, gratipay.com/about if external.
