### ISSUE TITLE
Apply for NLnet

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#896]
> Do you have a valuable idea in the area of the network and Internet technology, and are you looking for financial means to make your ideas come through? Or do you have an existing project that requires additional means to enable further development? Then submit your proposal to NLnet foundation before the next following deadline and see if we can help you.
>
>We are independent and put our money where our mouth is: that is to increase the use of open technologies for society. What is important for us is that the technology you develop or help promote is usable for others and has real impact.

https://www.nlnet.nl/news/2016/20161201-call-en.html ([h/t](https://twitter.com/nayafia/status/796793736952889344))

**Comment by whit537** [comment]
> especially where these are aimed at development and dissemination of open standards and (network related) open source technology. Additionally the foundation wants to contribute to the societal debate on these subjects.
>
>NLnet foundation supports a large array of activities, from software development, standardisation work and development of educational material up to hacker festivals, digital rights activities and the international development of open source software licences.

Not exactly a slam-dunk.

**Comment by whit537** [comment]
Current projects: https://www.nlnet.nl/project/current.html

Also, they extended their deadline two weeks.

**Comment by nobodxbodon** [comment]
deadline passed. closing.
