### ISSUE TITLE
Get our details updated on CodeMontage

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/inside.gratipay.com#91]
https://www.codemontage.com/organizations/gittip

**Comment by whit537** [comment]
You on this, @rohitpaulk?

**Comment by whit537** [comment]
Ping @DBNess cc: @codemontage. Could you help us update [our organization page](https://www.codemontage.com/organizations/gittip) on CodeMontage? We've [renamed](https://gratipay.news/gratitude-gratipay-ef24ad5e41f9) to Gratipay. :-)

**Comment by DBNess** [comment]
:+1: @whit537 https://www.codemontage.com/organizations/gratipay

**Comment by rohitpaulk** [comment]
Thanks @DBNess!
