### ISSUE TITLE
Set up Slack

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#913]
Reticketed from https://github.com/gratipay/inside.gratipay.com/issues/900#issuecomment-262465962.

**Comment by whit537** [comment]
https://github.com/gratipay/inside.gratipay.com/issues/900#issuecomment-262515991

>> Wanna set up slackin?
>
>Done! 
>
>https://gratipay-slackin.herokuapp.com/

**Comment by whit537** [comment]
@rohitpaulk Now how about http://slackarchive.io/? :-)

**Comment by whit537** [comment]
Re-added to Inside Gratipay in #915.

http://inside.gratipay.com/appendices/chat (should appear soon)

**Comment by mattbk** [comment]
I know this has happened, but what about an OSS alternative like RocketChat?

**Comment by whit537** [comment]
@mattbk Is there a hosted version or would we have to host it?

**Comment by mattbk** [comment]
We'd have to host on Heroku or something.

**Comment by whit537** [comment]
Okay. I think it's better for us to use a hosted product, to save time. Also, Slack is fairly ubiquitous by now. Part of what's motivating me here is to be less idiosyncratic compared to Open Collective.

**Comment by whit537** [comment]
> I went through the sign-up and was surprised to land on MailChimp. What's next to bring http://gratipay.slackarchive.io/ online? 🙇

https://twitter.com/whit537/status/801526755899142144

**Comment by whit537** [comment]
> Submit this form together with your email, so we can activate it and let you know when the archive bot is ready.

http://slackarchive.io/ sign-up

**Comment by whit537** [comment]
I see the slackarchive.io bot in our Slack but it hasn't joined any channels and I don't see how to make it do that.

![screen shot 2016-11-23 at 3 53 03 pm](https://cloud.githubusercontent.com/assets/134455/20578353/f715fad8-b194-11e6-858a-9b64e41cd91b.png)

https://gratipay.slack.com/services/108590827620

![screen shot 2016-11-23 at 3 53 31 pm](https://cloud.githubusercontent.com/assets/134455/20578359/004165c0-b195-11e6-86dc-6fc00ea08a4c.png)

**Comment by whit537** [comment]
@clone1018 Wanna spin up https://github.com/kamaln7/karmabot for us? :-)

**Comment by whit537** [comment]
I found a way to invite slackarchive.io into #gratipay but now I can't find it again. 😆

**Comment by whit537** [comment]
Still not archiving tho ... http://gratipay.slackarchive.io/

**Comment by whit537** [comment]
Okay! Made some customizations (logo, messages, :heartcoin:). Eeeee! :-)

**Comment by whit537** [comment]
@clone1018 has his friend setting up karmabot for us.

**Comment by clone1018** [comment]
Looks like karmabot is setup and working! We can always self-host or move away or w/e

![image](https://cloud.githubusercontent.com/assets/226638/20579730/125db750-b194-11e6-8397-26dcd4cdddcb.png)

**Comment by nl5887** [comment]
You can try this as well to invite the archivebot into your channel:

```/invite @<your_bot_name>
```

**Comment by nl5887** [comment]
And in team view you should have the possibility to invite bots as well.

**Comment by whit537** [comment]
Thanks @nl5887! At this point the bot is in the channel, but it shows as "away" and http://gratipay.slackarchive.io/ is still spinning. Any ideas?

---------------------

![screen shot 2016-11-23 at 8 05 34 pm](https://cloud.githubusercontent.com/assets/134455/20583488/45bad046-b1b8-11e6-9f48-325d8c4864d9.png)

---------------------

![screen shot 2016-11-23 at 8 06 13 pm](https://cloud.githubusercontent.com/assets/134455/20583496/508d294c-b1b8-11e6-8b60-d26ea3d3e557.png)

**Comment by whit537** [comment]
I'm waiting on archiving to close this.

**Comment by whit537** [comment]
Bump. Any update, @nl5887? So close! :-)

**Comment by clone1018** [comment]
Alternative, with some self hosting required:

https://github.com/stevedomin/slack_to_html

Example: http://slack.elixirhq.com/general/2016-02-29/

**Comment by nl5887** [comment]
Apparently something went wrong during the enrollment, just resetted everything. If archivebot is still in the channels, it should start archiving quickly.

**Comment by whit537** [comment]
Thanks @nl5887, looks [better](http://gratipay.slackarchive.io/gratipay/)! Waiting for messages to start showing up before closing ...

![screen shot 2016-11-28 at 7 40 46 am](https://cloud.githubusercontent.com/assets/134455/20668669/0e2af050-b53e-11e6-8b33-c012c3f430e4.png)

**Comment by whit537** [comment]
We're live! Thanks @nl5887! 💃 

![screen shot 2016-11-28 at 7 44 20 am](https://cloud.githubusercontent.com/assets/134455/20668768/81f9eaf4-b53e-11e6-85bb-6c6b58b03ae0.png)

**Comment by whit537** [comment]
"Public or no, for some reason I am far more comfortable typing my silliness in here. Probably familiarity with the platform." —@JessaWitzel in [slack](http://gratipay.slackarchive.io/gratipay/-/1480531229.000399/1480534846.000501/1480534774000497/)

👍 💃 🌻

**Comment by techtonik** [comment]
@whit537 I accepted you invitation, but..
```
Please update your browser to use Slack

We are no longer supporting this version of your browser, so you’ll need to update it to keep using Slack. We know this can be a pain, and we’re sorry for asking you to do it. You can learn more about why we no longer support some older browsers in our FAQ.
```

https://demo.rocket.chat/ have some issue with logging me in with GitHub, and https://discordapp.com/ just works.

**Comment by techtonik** [comment]
Okay. `rocket.chat` finally loaded. May be some issue with server load.
