### ISSUE TITLE
Guest-post from Justin Dorfman

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#914]
https://twitter.com/whit537/status/801405802682740737

**Comment by jdorfman** [comment]
Outline (WIP): https://gist.github.com/jdorfman/aee6f7faef0b69682795d15cb04a8154

**Comment by jdorfman** [comment]
I think this post will be hopefully announcing $ustain. Need to think about it.

**Comment by whit537** [comment]
@jdorfman That sounds awesome! 💃

**Comment by jdorfman** [comment]
join:
- slack.opencollective.com
- #sustainunconf

**Comment by jdorfman** [comment]
Still working on it.
