### ISSUE TITLE
Convert to a non-profit

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#916]
Remake of https://github.com/gratipay/gratipay.com/issues/101.

@timothyfcook Can you help me with this? 🐭

**Comment by JessaWitzel** [comment]
Is this instead of #196 ?

**Comment by whit537** [comment]
@JessaWitzel Yeah, more or less. Which should we do, #196 or this?

**Comment by nobodxbodon** [comment]
Some quotes from other threads. I must have missed a lot:

https://github.com/gratipay/inside.gratipay.com/issues/836#issuecomment-251448285


>>    It's weird to apply in the non-profit track and say "We are going to make something people want."

> We can make something people want/need and don't charge them for it. Isn't that what we are trying to make? And isn't that what open source and non-profit organizations kind-of are?

>>     Rather than "We are going to cure disease" or whatever.

> Not all non-profits cure disease. e.g. non profit programs that try to promote the arts and music. These organizations are not curing diseases but I think that most people would agree that it is necessary to make well rounded individuals

https://github.com/gratipay/inside.gratipay.com/issues/844#issuecomment-253926018
> I asked whether he had an opinion on whether Gratipay should be non-profit or for-profit, and he offered that companies are looking for vendors who are stable and long-lived. Insofar as "non-profit" means "fly-by-night," then for-profit is better.

https://github.com/gratipay/inside.gratipay.com/issues/836#issuecomment-258862377
>>  if Gratipay can find a successful business model, it will be more influential, especially if it's potentially reproducible by other for-profit businesses.

> 👍 I think we want to be influential and show that this stuff can work (along with letting people run experiments*, of course).

>> I'd argue additionally that, unless there is a pressing reason, there is no need to move toward nonprofit right now.

>> *I don't know who brought this up (maybe @rohitpaulk? My search-fu is weak this morning see ETA at bottom), but one potential use for allowing multiple split-up-the-money methods (beside take-what-you-want) and multiple ways of giving (bundles, corporate, others we've brainstormed) is to see what works financially and what doesn't. With enough entities using Gratipay, it could be a good resource for some economic papers.

> ETA: It was this issue and also this comment within this very issue!
