### ISSUE TITLE
Participate in Sustain

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#920]
@jdorfman is organizing an unconference about open source sustainability:

https://twitter.com/jdorfman/status/801949075469832192

**Comment by whit537** [comment]
![slack-imgs](https://cloud.githubusercontent.com/assets/134455/21432783/028ca6de-c83b-11e6-89a7-e4e585d3424d.png)

**Comment by whit537** [comment]
![sustain-project](https://cloud.githubusercontent.com/assets/134455/21432789/097182a8-c83b-11e6-86e9-c866e284cc22.jpg)

**Comment by whit537** [comment]
Design work ongoing ...

**Comment by whit537** [comment]
![sustain-logo](https://cloud.githubusercontent.com/assets/134455/21432805/1bfc5cd6-c83b-11e6-8025-04b2b1094b18.jpg)

**Comment by jdorfman** [comment]
All feedback wanted/needed

**Comment by whit537** [comment]
![sustain-project_2version](https://cloud.githubusercontent.com/assets/134455/21508921/a947c1a0-cc52-11e6-8b02-ea0e11df997c.jpg)

**Comment by whit537** [comment]
![sustain-logo-2version](https://cloud.githubusercontent.com/assets/134455/21508925/ad1b7df8-cc52-11e6-8053-df03c4852447.jpg)

**Comment by whit537** [comment]
It looks like this is going to be the week after OSCON (#948) in SF, so budgeting falls under #921.

**Comment by whit537** [comment]
I've proposed in [slack](http://gratipay.slackarchive.io/gratipay/-/1483309670.001498/1483566398.001713/) that @clone1018 represent us at $ustain. He's considering it.

**Comment by whit537** [comment]
Thoughts, @clone1018? I'm up in the air on whether to send just you or whether we should both be there. If we wanna make a strong showing like "GRATIPAY IS HERE!!!!!!!!!!!!!" then maybe we should both go?

**Comment by jdorfman** [comment]
Kick down the door


![](http://i.giphy.com/Ud0Dtf92fA8aA.gif)

**Comment by whit537** [comment]
[slack](http://gratipay.slackarchive.io/gratipay/-/1483656610.001975/1483739561.002084/1483739420002079/)

**Comment by whit537** [comment]
@nobodxbodon You live down the valley. Would you have any interest in joining @clone1018 and/or myself?

**Comment by nobodxbodon** [comment]
@whit537 thanks for asking. Yes I do have interests now. I suppose I won't add extra cost, so maybe re-check around the end of May?

**Comment by whit537** [comment]
> May 17th it is

**Comment by whit537** [comment]
Ping @Changaco @rappo @wkonkel. We're havin' a shindig! @jdorfman from Sticker Mule (formerly MaxCDN) is organizing a one-day unconference for open source software sustainers called $ustain. The venue is GitHub headquarters in San Francisco, and we just finalized the date: Wednesday, May 17, 2017. You are cordially invited! :-)

Further organizing is happening in the #sustainunconf channel on the Open Collective [slack](https://slack.opencollective.com).

**Comment by Changaco** [comment]
Coming to SF isn't an option for me in the short term, it's far and foreign, but thanks for the invite. ;-)

**Comment by whit537** [comment]
Repo here: https://github.com/sustainers/website/issues.

**Comment by whit537** [comment]
![sustain_logo_draft2_1024](https://cloud.githubusercontent.com/assets/134455/21910249/2b150d3a-d8e9-11e6-86e2-f928f12d4d29.jpg)

**Comment by whit537** [comment]
I've paid $50/ea for two tickets for @clone1018 and I. That means Gratipay is now [on Open Collective](https://opencollective.com/gratipay)! :-)

**Comment by whit537** [comment]
P.S. I contributed coding for the website: https://sustainers.github.io/website/.

**Comment by nobodxbodon** [comment]
I wonder what's the $13.20 used for..can't find a history of expenses:
![screen shot 2017-01-19 at 3 23 37 pm](https://cloud.githubusercontent.com/assets/392497/22129510/4f54c362-de5b-11e6-8399-3379edecceb2.png)

**Comment by clone1018** [comment]
@whit537 Also means we're locked in!

**Comment by mattbk** [comment]
@nobodxbodon, they take a cut, plus fees.

**Comment by nobodxbodon** [comment]
@mattbk ah right. Thanks for reminding. I was so used to our own giving model lol.

**Comment by whit537** [comment]
Looks like this is [shifting](https://github.com/sustainers/website/issues/27) to June.

**Comment by whit537** [comment]
Aaaaaaand it looks like the Whitacrew might in fact roadtrip. 😱

cc: @JessWhit @see-ya-leah

**Comment by clone1018** [comment]
:bus:

**Comment by whit537** [comment]
Awesome. Maybe we could swing through Dallas on the way? :)

**Comment by whit537** [comment]
@clone1018 is not going to make it (and our slackarchive is down, https://github.com/gratipay/inside.gratipay.com/issues/1087).

I've booked a flight, going out Sunday and redeye home Tuesday night.

**Comment by whit537** [comment]
We are half-way through rolling our bank account (due to a low-risk security issue, abundance of caution). We have $848.80 in the old account and $818.77 in the new account. The flight cost $766 and I put it on the old account. We should be able to get the old account closed out before I depart, but I believe we will start getting hit with a service fee for having a balance under $1500 in the new account. Our income is down:

![screen shot 2017-05-27 at 2 09 56 pm](https://cloud.githubusercontent.com/assets/134455/26523467/307dd6e6-42e6-11e7-8c34-744db569816c.png)

https://gratipay.com/Gratipay/receiving/

**Comment by whit537** [comment]
I booked a room in Oakland, two nights for $146. Half the price of San Francisco, while only a short BART ride away from GitHub and a mile from npm's office. 👍

I put it on the new PNC account.

**Comment by whit537** [comment]
I've pinged @nobodxbodon in email to see if he's around then, and he asks:

>  May I ask if you have some specific goals for this conference?

My answer:

> 1. Make sure everyone has a good time! We are primary co-organizers of the conference along with StickerMule, Open Collective, and Libraries.io.
> 2. Follow the conversation wherever it goes. There will be about 100 people here and we have a top-notch facilitator to guide us throughout the day.
> 3. Share about our work as appropriate, especially our vision for aggregation represented by our > recent features around npm.

**Comment by whit537** [comment]
I am in Oakland! This Airbnb is pretty quiet, though I walked through some rougher-seeming patches of neighborhood to get here from the train station. Heading out now to meet folks for a pre-event dinner. I've pinged a few folks about meeting up apart from Sustain itself:

- @nobodxbodon,
- @/isaacs at npm (I'm not seeing it on the ticket here, but he responded to a six-month-old email when he saw "[Integrating npm](https://gratipay.news/integrating-npm-39333109419d)" and we are scheduled for lunch on Tuesday! [slack](https://gratipay.slackarchive.io/gratipay/page-80/ts-1495225083418204)), and
- someone at Y Combinator. ¯\\\_(ツ)\_/¯

Stay tuned! 📺 💃

**Comment by whit537** [comment]
In general I am charging things to PNC. It is a bit ambiguous but I might be able to [expense](https://github.com/gratipay/gratipay.com/issues/4339) the whole thing to the [Sustain collective](https://opencollective.com/sustainoss) due to details of sponsorship from LLNL (we put two days of [M&IE](https://www.gsa.gov/portal/content/104877) in the proposal in addition to flight/room, but I don't think anyone else from the organizers is expensing meals and incidentals).

P.S. I'm officially a Thought Leader&trade; now! 😆  Written by guy at LLNL in jdorfman's name:

![screen shot 2017-06-18 at 5 18 54 pm](https://user-images.githubusercontent.com/134455/27265426-3f80636e-544a-11e7-982c-c3b9f14f571b.png)

**Comment by whit537** [comment]
Some rogue fire alarm woke me up even earlier than planned, but tbh it as about when I really should've gotten up anyway. Gotta be at GitHub by 7:45 and it'll take me a good hour to get there, and I'm on the hook for pastries, too ... thinking [Acme](https://www.google.com/maps/dir/''/88+Colin+P+Kelly+Jr+St,+San+Francisco,+CA+94107/@37.7876698,-122.4027112,15z/data=!4m14!4m13!1m5!1m1!1s0x808580668e8f3159:0xb9085c4b33471950!2m2!1d-122.3936453!2d37.7957545!1m5!1m1!1s0x80858077fe6ae953:0x1cf829f1248fb8f4!2m2!1d-122.3912479!2d37.7822671!3e2)?

Cheesecake Factory was kinda ridiculous in terms of the tourist factor and it was really stuffy, but the food was fine and the people were, of course, the point. Richard, Ben, Devon, Xavier, Gunner, Justin, Pia, Jerod, Gregor and myself. Honestly, I would've gone to McDonald's. 😃

**Comment by whit537** [comment]
Here I go! 💃

**Comment by whit537** [comment]
Wow. 😳

**Comment by whit537** [comment]
Still wow! It was great but now I am trying to turn around and head out on a roadtrip! Writeup pending ...

P.S. though ... I submitted expenses for the flight and room and those have been paid and are pending in our PNC account. I also submitted an expense for $94.86 in meals.

**Comment by rappo** [comment]
@whit537 I'm way late to the party, but are you still in Oakland? Seems like I'm too late :(

I live in West Oakland, we should grab a beer/coffee tomorrow if you haven't already left.

**Comment by whit537** [comment]
Hah, love it! Thanks for the invite, @rappo! I am back in Ambridge now, yes, but will keep that in mind for next time! I was staying on Linden near Grand and walked to both 19th and West Oakland stations ... so I probably walked within a block of your place at some point if you live anywhere below Grand. :-)

**Comment by rappo** [comment]
ARE YOU @#($%(@* SERIOUS. I live on Chestnut between 10th and 12th, near Lowell park. You were just one short block over.

Let's do a video Hangout soon? I'd love to catch up on how things are on your end and maybe kick around some ideas.

**Comment by whit537** [comment]
Nice! :D Seemed like a great neighborhood for being so close to SF, one hop on BART hard to beat.

Hangout will be tough ... I leave in 5 hours (if we're lucky!) for six weeks on the road with the fam. Let's try again in the fall?

**Comment by whit537** [comment]
Had another 94.86 reimbursed for a couple breakfasts I floated.

I think that's it?

**Comment by whit537** [comment]
[![](https://user-images.githubusercontent.com/134455/27545516-375cb51c-5a4d-11e7-8eef-535cdb52cfd2.jpg)](https://twitter.com/zahedab/status/877004717301223424)

---------------------

[![](https://user-images.githubusercontent.com/134455/27545663-9ca798c4-5a4d-11e7-82f7-c4fc00fd0440.jpg)](https://twitter.com/saikofish/status/876863604670304257)

---------------------

[![](https://user-images.githubusercontent.com/134455/27545730-ced440ae-5a4d-11e7-915e-5d54b1ed767a.jpg)](https://twitter.com/saikofish/status/876838183756980225)

**Comment by whit537** [comment]
I never wrote this up. The day of, that is.

I took the BART to Embarcadero and stopped in at Acme to pick up croissants then walked down to GitHub. I arrived at about 7:25. Doors at 7:45 per @jdorfman. Walked around the block, ran into @/bkeepers, he let me in the side door and then Matt the doorman registered me. Too early! @/nayafia and @/alnermcgunn outside, sent 'em around to the side door, still not open. First attendees arrived, we're off and running. I left the building at about 8:00 PM, over twelve hours later. 😳 

First hour was setup, moving furniture into the configuration you see above.

Then registration and breakfast. Meeting lots of people.

Gunner is amazing. A performer and a maestro. He'd rattle off 12 sessions and call for more, then stand up all 14 facilitators at points around the room and circle through, soliloquizing their offerings in 45-second improvisations with nary an "ah" or "um" but rather replete with wit and a thorough comprehension of their topics and, indeed, personalities. Then we'd break and he'd catch his breath. Yes, he ate lunch. A few folks found him imposing and abrasive (not unfair), but most were happy to ride the rapids with him as guide.

In terms of the goals articulated above at https://github.com/gratipay/inside.gratipay.com/issues/920#issuecomment-308224640:

1. *Almost* everyone had a good time. Perfection is elusive. We came close to it but there was still room for improvement. Alackaday. 😞
1. The conversation was skewed towards non-monetary meanings of "sustainability" for open source. To my mind it shaded too much into [Maintainerati](http://maintainerati.org/) territory—onboarding new contributors, avoiding and dealing with burnout, etc.—more time than money. We were missing open-source startups like Sentry, npm, Meteor, and Docker. We had a few Red Hat folks but no strong business voice from that front that I heard. I wanted more of [the whole spectrum](https://twitter.com/eigenjoy/status/862412458517962752). There was a digital infrastructure research meeting convened by the Ford and Sloan Foundations a few days later in New York, and some of the folks from Sustain were headed there (@/gr2m, @/benjam, etc.). One of the threads they were carrying there was mapping out the open source ecosystem so we can be more specific about what is working and what isn't, and thus target our efforts better. I'm interested in the outcome of that. I think 90% of open source is fine with current models—a stark difference from other Sustain participants. More research required!
1. The most in-depth conversation I had was with @/gr2m and @/jerodsanto. I pitched them on the bigger picture of open work, twyw, etc. Making jobs obsolete. I think they sort of started to get the breadth of Gratipay's vision. This was at Cheesecake Factory.

In general I think this event started to galvanize a community of folks who care about this issue. I don't think [ossfriendly](https://github.com/ossfriendly/open-source-sponsors) was an immediate response to Sustain but the timing was great and it's carrying the momentum forward. For me the event was mostly about building relationships with people. I got to deepen friendships with some folks and start friendships with others. In terms of the outputs, it was pretty much exactly what I expected and hoped it would be (final tally is happening at https://github.com/sustainers/discussions/issues/2).

At the end of the day, though, I wanted to **_hack_**! Sustain ultimately made me want to keep shipping product on Gratipay to help solve the problems we surfaced. Talk is cheap! :-)

P.S. The most touching moment for me was at the end when we were going around the room sharing brief expressions of gratitude for whatever. @tmcw used his turn to say something like, "I'm grateful to Chad for his fearlessness in experimenting over the years," or words to that effect. It was towards the end of the round, and he caught me by surprise. That meant a lot to me, @tmcw. Thank you. 🙇 ☺️

**Comment by whit537** [comment]
P.P.S. After the event I went [back](https://github.com/gratipay/inside.gratipay.com/issues/867#issuecomment-260138759) to Marlow and ate a burger and drank a Macallan 12 and got yelled at by the barkeep for grabbing the drink too early before he'd stirred it. Onboarding. ;-)
