### ISSUE TITLE
reference to "state laws" in TOS

### ISSUE THREAD

**Issue by tieguy** [gratipay/inside.gratipay.com#925]
Sec. 11.i refers to "certain state laws". Unless other counsel have specifically recommended this language to refer to particular PA laws, I would say it is fine to simply say "local laws" here.

**Comment by mattbk** [comment]
> Unless other counsel have specifically recommended this language

Question for you, @whit537.

**Comment by whit537** [comment]
I don't recall any conversation specifically about that verbiage. Changing to "local laws" is fine with me.
