### ISSUE TITLE
Clarify terms around notification

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#926]
Reticketed from https://github.com/gratipay/inside.gratipay.com/issues/204 via https://github.com/gratipay/gratipay.com/pull/4117#issuecomment-262336157.

>> Regarding the “without notice to you” provisions in §11.4 and §12.1, I would **very** much like to be informed of it, just as under §17.2.
>
>I think these clauses mean "without prior notice to you." We certainly notify people of things after the fact, but it's Gratipay's discretion what to keep or remove in any context. "With prior notice" would imply that we're asking permission, which is not what will happen under pending legal action (copyright notice, etc.).
>
>>On that topic, it would be really nice if you could add a possibility for community involvement in the process of changing the ToS & PP, similar to the one in §4.5 (when a Team is being estabilshed).
>
>I think this is implied?

(Note that section numbers will change when https://github.com/gratipay/gratipay.com/pull/4117 lands.)

**Comment by whit537** [comment]
Here's our current language:

> Gratipay may change the Service at any time, without notice to you. Gratipay may also stop providing one or more services or features, introduce new limits on use of the Service, or change the terms upon which the Service is available.

It seems that we should remove this:

https://medium.com/@jlkoepke/we-can-change-these-terms-at-anytime-the-detritus-of-terms-of-service-agreements-712409e2d0f1
http://blog.ericgoldman.org/archives/2009/06/stop_saying_we_1.htm
https://en.wikipedia.org/wiki/Terms_of_service#Zappos

**Comment by mattbk** [comment]
For clarification, my comment you copied above was referring to this instance (now at 12.v):
> Removal and Termination for Infringement: Gratipay will terminate, under appropriate circumstances, the accounts of Participants who repeatedly use the Service to infringe copyrights. Gratipay also reserves the right, in its sole discretion, to remove allegedly or apparently infringing content without notice to you.
