### ISSUE TITLE
 Gratipay Retreat 2017

### ISSUE THREAD

**Issue by clone1018** [gratipay/inside.gratipay.com#927]
Let's get the ball rolling on this!

----------------------

#### Previous Installments

- [2014](http://blog.gittip.com/post/74460469599/with-first-retreat-gittip-team-becomes-a-reality/)
- [2015](https://gratipay.news/at-our-second-retreat-we-met-our-third-users-5b473a2d1464)
- [2016](https://github.com/gratipay/inside.gratipay.com/issues/392#issuecomment-240693047) :grin:

**Comment by clone1018** [comment]
Where do we host it?

**Comment by whit537** [comment]
I can check with @JessWhit about our place if you want.

**Comment by clone1018** [comment]
I think since you just want to SF that might be the cheapest option

**Comment by JessaWitzel** [comment]
You can host it at my house in NC but only if you teach me coding things.

**Comment by whit537** [comment]
@JessaWitzel Nice!

[slack](http://gratipay.slackarchive.io/gratipay/-/1480518734.00036/1480533970.000463/1480533776000444/) re: cat farms and RVs. :)

**Comment by whit537** [comment]
Durham is eight or nine hours [drive](https://www.google.com/maps/dir/Ambridge,+PA/Durham,+NC/@38.272099,-81.6854493,7z/data=!4m19!4m18!1m10!1m1!1s0x883466fa393863b7:0x7cb5a696f998d13d!2m2!1d-80.22506!2d40.5892339!3m4!1m2!1d-80.6640412!2d38.7958189!3s0x884bd0428c76327b:0xd9721840f0ed2bc1!1m5!1m1!1s0x89ace471120f66f1:0xe17ada898a46f27e!2m2!1d-78.898619!2d35.9940329!3e0) from Ambridge. @dmk246 @kaguillera and I are ruminating on a roadtrip! 🚗

**Comment by whit537** [comment]
In terms of dates, can we push it back further into the year? @JessWhit and I were talking about keeping the kids time off school clear. Also, @kaguillera has company through Jan 18. I have something Jan 27-28. Can we look at weekends in February?

**Comment by clone1018** [comment]
I'm fine with mostly anything we have a 1 month plan for

**Comment by whit537** [comment]
Month-long retreat!!! 😱

**Comment by clone1018** [comment]
Haha, I meant 1 month warning about :)

**Comment by whit537** [comment]
:-)

**Comment by whit537** [comment]
Bump for date votes!
You can vote for more than one.
Vote for all the ones that are currently open for you.

👍  February 4
😄  February 11
🎉  February 18
❤️  February 25

Location tbd, either Ambridge, PA or Durham, NC.

**Comment by jhannah** [comment]
My mobile lifestyle means I chase 70° around the US and Canada. Those dates + locations sound way colder then where I'll be. :)

**Comment by whit537** [comment]
@lyndsysimon Want to join us for the Gratipay retreat this year? :-)

**Comment by whit537** [comment]
@kennethreitz points out that Feb 4 or 25 might be better since they're further from Valentine's Day. ❤️  😊

**Comment by whit537** [comment]
I'm backing out of Feb 25 because of a birthday ... so let's say either February 4, or bump to August on the strength of https://github.com/gratipay/inside.gratipay.com/issues/392#issuecomment-240693047. ([slack](http://gratipay.slackarchive.io/gratipay/-/1483477112.00159/1483564218.001691/1483564218001691/)).

**Comment by whit537** [comment]
The leaning on Slack seems to be towards August.

**Comment by whit537** [comment]
@mattbk [clinches it](http://gratipay.slackarchive.io/gratipay/-/1483555113.001617/1483567290.001717/1483567281001716/):

> The only way I can make any part of a retreat is if it's in August.

**Comment by whit537** [comment]
New date vote!
You can vote for more than one.
Vote for all the ones that are currently open for you.

👍  August 5
😄  August 12
🎉  August 19
❤️  August 26

**Comment by whit537** [comment]
Fizzled.

**Comment by mattbk** [comment]
😢

**Comment by clone1018** [comment]
We had two retreats this year right?

**Comment by whit537** [comment]
And a mini-retreat two or three times a week when @dmk246 @kaguillera and I get together! :D
