### ISSUE TITLE
pin down retreat schedule

### ISSUE THREAD

**Issue by clone1018** [gratipay/inside.gratipay.com#93]

**Comment by whit537** [comment]
Reopening, @seanlinsley. ;-P

**Comment by clone1018** [comment]
@colindean Last time, we had friday for our "meet and greet", saturday was "talking" and sunday was "hackathon"

**Comment by whit537** [comment]
I've started inviting locals to an open house on Friday at 6pm. Shepherd's pie.

**Comment by whit537** [comment]
There's a fun jam night later on Friday that I've been playing at. Last time it seemed like we just wanted to hang out at my place, but if we want to get out and blow off some steam this would be a good chance.

**Comment by whit537** [comment]
Obviously we're going to have to spend time on #118. What are our expectations there in terms of what we'll be able to accomplish while we're together? At this point I feel like we need to be more or less open ended, take it as it comes once we're together.

What else do we want to have on the agenda? #89 comes to mind.

**Comment by whit537** [comment]
I've invited about 22 people so far for Friday evening. We won't see everyone, but I'll probably think of a few more to invite. +~8 of us, so ... shepherd's pie for 30 for the open house? I think menu should be shepherd's pie, caesar salad, and box wine.

**Comment by whit537** [comment]
> There's a fun jam night later on Friday that I've been playing at.

I think we should just expect to be at my place on Friday. Maybe I can get @clone1018 out the following Friday. :-)

**Comment by whit537** [comment]
And IIRC @seanlinsley has already experienced the speakeasy.

**Comment by clone1018** [comment]
@whit537 I'm down for everything and anything.

**Comment by seanlinsley** [comment]
@whit537 I would link you to @clone1018's plans for his friend that's arriving on Friday from IRC, but Freenode seems to be having trouble, and I'm too lazy to find the stuff @clone1018 said previously & copy/paste it here ¯\\_(ツ)_/¯

**Comment by whit537** [comment]
I've asked @weallhave24hrs (https://gratipay.com/AmbridgeConnect/) to join us for an hour on Saturday, tentatively at 11am. As I believe I've mentioned before, I see her as a key target user as we build the product out for a mass audience. I want us to hear about her business and have a conversation together about how Gratipay can serve her needs.

**Comment by whit537** [comment]
I'm also talking with a friend and business mentor of mine, Dan Telep, about joining us for a session re: #89. Maybe we do that 9-11 on Saturday morning, and then segue from more abstract discussion into a conversation with a specific target user? Maybe it would be helpful to have a few other target users present?

**Comment by whit537** [comment]
I talked with @weallhave24hrs and she's open to broadening the 11 session into a focus group with two or three other (potential) users. Reaching out to a few folks ...

**Comment by whit537** [comment]
Made a schedule with Dan for 9-12 tomorrow. Felicia will be with use 1:00 to 1:45. After that ... we hack! :dancer:
