### ISSUE TITLE
Revise offsite backup procedure

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#932]
We take a nightly backup at Heroku. I do think we should have an offsite backup, at least at a different provider. I don't think we want backups on three different personal laptops, though. That is sloppy.

What should we do, @clone1018 @rohitpaulk?

**Comment by clone1018** [comment]
I think me and @rohitpaulk 's backups are on DigitalOcean (that's where I run payday). I'm used to storing backups on S3 with the file encrypted. Not sure if that would be easy for us or not

**Comment by whit537** [comment]
Heroku wraps AWS so that wouldn't do much for us. DO could work but we should be more intentional about it.

**Comment by whit537** [comment]
Actually ... closing as a dupe of #470.
