### ISSUE TITLE
Go to Open

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#940]
> hey @whit537 be great to have you/ @Gratipay at https://2017.open.coop/  - you available on 16-17 Feb 2017?

https://twitter.com/open_coop/status/808403971614375936

It's in the UK.

**Comment by whit537** [comment]
Conflicts w/ #930.

**Comment by jdaviescoates** [comment]
gah, another clash! also clashes with Enspiral retreat which means none of them can make it :-/

**Comment by whit537** [comment]
> also clashes with Enspiral retreat

Ouch. 😞

**Comment by jdaviescoates** [comment]
Still going to be a fantastic event thought :-D

**Comment by whit537** [comment]
That's the spirit! 😄

The two factors for us would be cost & benefit. We are running a pretty tight ship right now. Would you be able to provide any transportation assistance?

**Comment by whit537** [comment]
Bump. If you aren't able to provide travel assistance, that is totally understandable, @jdaviescoates. We're working through our events budget for 2017 (#960) and need to make a decision here one way or another.

**Comment by jdaviescoates** [comment]
I'd personally love you to be there @whit537 and we do have a bit of money and are paying for some people already... doing lots of work on programme this Thurs/ Fri so should know lots more next week (might turn out we don't even have room in programme for more people!)

**Comment by jdaviescoates** [comment]
@whit537 where would you be travelling from? (so we can guestimate costs and make an more informed decision) and would you need a hotel or would crashing with a local be preferred/ OK? :) (again, this could save us money and make it more viable)

**Comment by whit537** [comment]
> where would you be travelling from?

Pittsburgh (PIT) ... a quick out and back looks to be about $1,300. Quite happy to crash w/ a local and eat ramen. :-)

Would love to be there if it makes sense on your end—no hard feelings if not! Let me know! :-)

**Comment by whit537** [comment]
Any word, @jdaviescoates? How is the programme shaping up? :)

**Comment by whit537** [comment]
Today I'm seeing a flight for $540!

**Comment by whit537** [comment]
Too good to be true. 😞

![screen shot 2017-01-20 at 10 14 37 am](https://cloud.githubusercontent.com/assets/134455/22154389/50aa14ee-def9-11e6-9f55-cff161a4f07b.png)

> Your ticket price changed from $534.73 to $1,135.78. The airline could not confirm the original price due to pricing or availability changes that occurred after we posted the latest prices on our site.

**Comment by jdaviescoates** [comment]
Hey Chad,  it would been really great to have gratipay at the conference, but for the sake of our sanity we're now no longer adding any more [contributors](https://2017.open.coop/contributors/) to our [programme](https://2017.open.coop/programme/) (and have basically run out of travel budget apart from maybe very cheap much more local ones :-/ )

**Comment by whit537** [comment]
Thanks for circling back, @jdaviescoates. You're in the home stretch! Best of luck and have a great conference! 💃
