### ISSUE TITLE
onboard @simonmichael

### ISSUE THREAD

**Issue by simonmichael** [gratipay/inside.gratipay.com#949]
Hi Gratipayers, [I am](http://joyful.com) a consultant and FOSS developer, leading the [hledger project](https://github.com/simonmichael/hledger/issues/446). I'm inspired by your organization and curious to see more detail in the roadmap, hence this onboarding request.

Best - Simon

**Comment by whit537** [comment]
Welcome, @simonmichael! You're talking about [this roadmap document](http://inside.gratipay.com/big-picture/roadmap), I take it, yes? I agree that more detail is warranted there. I'm putting this ticket on [my radar](https://github.com/orgs/gratipay/projects/4?fullscreen=true) to remind myself to make a revision. In the mean time, are there specific questions that come to mind that I can be sure to address?

**Comment by mattbk** [comment]
Any of the core radars before and including [Core Radar 83](https://github.com/gratipay/inside.gratipay.com/issues/868) may have slightly more detail and diagrams.

**Comment by simonmichael** [comment]
Thank you @whit537! To be clear, I'm not asking for a more detailed roadmap, rather I was exploring the todo items and at some point I reached a page linking to many repos (issues ?) which I could not view, and there was some text saying in effect "sorry github requires special access to view, onboard yourself". Sorry, I don't remember where that was.

**Comment by simonmichael** [comment]
Possibly related, http://inside.gratipay.com/big-picture/roadmap -> Relax Open Work Requirement gives me a 404. I thought I had seen a roadmappy page with more of these errors. It's always possible I dreamed it.

**Comment by whit537** [comment]
Ah, yes! That sounds familiar. :-)

May I add you as a contributor to our GitHub org? Then you should be able to view our projects in GitHub ...

**Comment by simonmichael** [comment]
Certainly, thank you.

**Comment by whit537** [comment]
Invite sent! Try w/ that?

**Comment by simonmichael** [comment]
Thank you Chad. I appreciate all the work so far on this terrific project.
