### ISSUE TITLE
 show gratitude to company sponsors of gratipay

### ISSUE THREAD

**Issue by nobodxbodon** [gratipay/inside.gratipay.com#950]
reticket from https://github.com/gratipay/inside.gratipay.com/issues/928#issuecomment-268388381
As we are getting more sponsors (Travis, Sentry, GitHub, etc), addition to the existing ones, it seems necessary to decide how.

>> I am starting to warm to the idea of doing the same at the bottom of our homepage.

> But let's not forget that if we do that, then we should do so as part of promoting people and organizations that back us financially on our own platform (cf. gratipay/gratipay.com#236).

**Comment by nobodxbodon** [comment]
How about separating the part for sponsors (organizations) and for individual contributors? As I understand gratipay/gratipay.com#236 is about the second part, and this ticket focuses on the first part.

I do think the second part has at least the same importantance, but will take more time, while this one is simpler to implement as the list is relatively static.

**Comment by nobodxbodon** [comment]
Here's an ugly pretotype, with incomplete 'powered by' list. Please review:
![sponsered powered concise](https://cloud.githubusercontent.com/assets/392497/21476308/257a87e8-caec-11e6-93a2-3a4e7a1e980e.png)

**Comment by EdOverflow** [comment]
I love the idea! I made a little mock up too:

![sponsered_by](https://cloud.githubusercontent.com/assets/18099289/21479966/1b16fb34-cb59-11e6-9681-3dc28ee516aa.png)

**Comment by EdOverflow** [comment]
If we use svg logos we can use a `fill` animation like this: https://codepen.io/anon/pen/xRNNYq/

**Comment by nobodxbodon** [comment]
@whit537 does [mock](https://github.com/gratipay/inside.gratipay.com/issues/950#issuecomment-269193201) from @EdOverflow above look good to you? If so will try to work on a PR.

**Comment by techtonik** [comment]
I don't like it. It makes system humanless. I know some people that do not like that their company spends money on charity without asking them. Those guys would prefer to choose their own charity instead. If Gratipay wants to be truly different from the dozens of startups around there, it should invent mechanism where specific people at those companies are supporting us, not all nameless company. Because enforcing each and other person on a company to support Gratipay contradicts with its core principle of gratitude. IMO.

**Comment by EdOverflow** [comment]
@techtonik That is a really interesting point you raised. Would testimonials be a better solution?

**Comment by techtonik** [comment]
@EdOverflow a better solution would be stories from people teaching how they've adopted Gratipay and explain them how to use it and what are we trying to achieve https://github.com/gratipay/gratipay.com/issues/1153

**Comment by nobodxbodon** [comment]
> If Gratipay wants to be truly different from the dozens of startups around there

I don't think being different in every aspect is part of Gratipay's goal.

> it should invent mechanism where specific people at those companies are supporting us, not all soulless company.

Do you consider Gratipay, as a company and a brand, soulless? Besides, sponsoring is company-level action. Why do we want to avoid that fact?

> a better solution would be stories from people teaching how they've adopted Gratipay and explain them how to use it 

That's a different task IMO.

**Comment by nobodxbodon** [comment]
Similar in nature with https://github.com/gratipay/gratipay.com/issues/2695. According to https://github.com/gratipay/inside.gratipay.com/issues/928#issuecomment-272614469 they are bound.

**Comment by whit537** [comment]
Well, but gratipay/gratipay.com#2695 is about companies that give to _anyone_ on Gratipay, not just to Gratipay itself.

**Comment by nobodxbodon** [comment]
According to https://github.com/gratipay/inside.gratipay.com/issues/987#issuecomment-274151963, seems this is part of "Recognize Companies", but separate task than "breaking anonymity", as the sponsors don't belong to 'givers'?

**Comment by JessaWitzel** [comment]
I think this idea is in line with our values and allows us to recognize the companies that are supporting us. I think it should be done on our team page in addition to our home page. That is where we will put recognition for other teams when it is done, yes?

**Comment by whit537** [comment]
I think we should show gratitude to our company sponsors with [a blog post](https://github.com/gratipay/inside.gratipay.com/issues/928#issuecomment-272556837). I think we should punt on  putting logos on Gratipay itself in view of gifts in kind until we have a generalized solution for that.

**Comment by whit537** [comment]
Okay! https://github.com/gratipay/inside.gratipay.com/issues/928 is done! Now to write that blog post ...

**Comment by whit537** [comment]
Draft: https://medium.com/@whit537/appreciating-our-vendors-ae3ccbea3c5a.
