### ISSUE TITLE
Join the IoO Project Council?

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#954]
From @ntnsndr in https://github.com/gratipay/gratipay.com/issues/4260:

> For some months, @devinbalkind and I have been developing a Project Council as an institutional frame for The Internet of Ownership, a federated resource network for the platform co-op ecosystem. We already use Gratipay for our fundraising, and we'd love to work more closely with you. Would Gratipay be interested in joining our Project Council? Right now, the meaning of this is still being worked out, but the goal is to work together to develop a democratic, shared resource pool for platform co-op efforts. Right now we're quite small, but we're about to add a third project, and we'd love if you might be interested in co-creating this effort with us. The expectations are quite modest. We have a Loomio group for decisions. And [here's some information about it, such as there is](http://internetofownership.net/project-council/).
>
>Would this be of interest?

**Comment by whit537** [comment]
http://internetofownership.net/ is sadly timing out for me right now. In general I am excited at the prospect. Cooperation among cooperatives is one of the seven principles of cooperatives, of course, and "nesting" is one of Ostrom's eight design principles for CPR management institutions. So this seems like a good intitiative! Looking forward to reading more when the link is back ...

**Comment by ntnsndr** [comment]
Should be working now!

**Comment by whit537** [comment]
Is the Loomio group open and browseable? Link?

**Comment by ntnsndr** [comment]
Yes, though we haven't really started using it. We're currently migrating from relying on email threads.
https://www.loomio.org/g/GxT2CoI8/the-internet-of-ownership

**Comment by whit537** [comment]
Cool. I'm open to being a part of this if no-one from @Gratipay objects. :-)

**Comment by ntnsndr** [comment]
Let me know what you decide!

∴
Nathan Schneider
nathanschneider.info <http://nathanschneider.info/>
encryption key <http://nathanschneider.info/nathanschneider.asc> (?
<https://emailselfdefense.fsf.org/en/>)

**Comment by nobodxbodon** [comment]
May I ask some questions to @ntnsndr:

> Funding: We manage a pool of money it allocates to member projects. 

What are the potential sources of the money? And is there plan about how to allocate?

> Fiscal Sponsorship: We maintain a contract with a 501.c.3 nonprofit that enables us to receive tax-deductible donations and comply with regulations.

Does this mean the financies will be open? Is there difference between being a nonprofit and maintaining contract with a nonprofit?

**Comment by ntnsndr** [comment]
Thanks for your questions. 

Currently the IoO pool comes from anyone who gives to [our Gratipay account](https://gratipay.com/internet-of-ownership/). Allocation, for now, will be handled by consensus [in Loomio](https://www.loomio.org/g/GxT2CoI8/the-internet-of-ownership).

We have not committed to open finances, but I think that would be perfectly reasonable for an organization like ours. Any recommendations on a tool to use for open bookkeeping? Maybe something that works on Sandstorm? Or old Goog sheet? @devinbalkind?

We are fiscally sponsored by the nonprofit, [Sarapis](http://sarapis.org), which means we are legally a nonprofit right now. This may change. But we are committed to developing this into a democratic membership organization of some sort, and it will be effectively nonprofit, regardless of the actual legal structure. Our purpose is the provision of services, not the distribution of profits.

**Comment by devinbalkind** [comment]
I agree with everything Nathan said.

There are two sets of funds: (a) collective funds raised through our Gratipay and whatever other mechanisms we create and (b) project funds which are raised specifically for that project. 

Collective funds are allocated through a peer-budgeting process. Loomio is a great tool for this. In other iterations of this process we created a budget template Google Sheet and projects would maintain that and then the group would come together, negotiate for the available funds and come to a consensus on the budgets. At this early stage I think we'll do fine agreeing on a per/purchase basis (ex. agreeing on paying for Loomio service.) The only stipulation on this is that, if the funds were raised for nonprofit purposes, then they'd have to be spent for nonprofit purposes. That shouldn't be a problem but we should keep that in mind. 

Project funds are autonomously managed by the project. It's none of our business how any project in IoO council spends money it raises for itself. If a project needs/want to raise money through a nonprofit, then they could create a fiscal sponsorship agreement with Sarapis or another nonprofit.

As for "open finances", I'm 100% committed to running finances that way with the only stipulation being for security concerns. I've run open finances in a Google Sheet in the past. I'm currently using AirTable.com as a financial process and documentation system for another organization and have been enjoying that so I might advocate for such a system in the future.

Happy to answer any questions. :)

Happy New Year!

**Comment by nobodxbodon** [comment]
Thanks @ntnsndr and @devinbalkind for the detailed explanations. 

A side note about the project guildlines in the charter. "Utilize open source technologies" sounds quite relaxed, as most websites uses at least some open source Javascript libraries.

Speaking of which, is http://ioo.coop/ open source?

Happy new year to you!

**Comment by ntnsndr** [comment]
The website itself runs on WordPress, not interesting or custom enough to bother open sourcing. We currently rely on a Google Sheets database, as well as the awesometable plugin. I'd love to port that to a more open platform, but for now at least the raw data is publicly viewable and downloadable. 


∴
Nathan Schneider
nathanschneider.info

**Comment by whit537** [comment]
> Any recommendations on a tool to use for open bookkeeping?

We've gone around the block on this one. We started with Xero in #308, but that's so cumbersome and non-open (let alone libre) that we [invented](https://github.com/gratipay/finances/pull/1) a system using [Ledger](http://www.ledger-cli.org/) (see [also]()) and GitHub. Our CPA actually [likes it](https://github.com/gratipay/inside.gratipay.com/issues/350#issuecomment-176242898), but we never really got off the ground with entering data into the system, either historical or current. We [considered](https://github.com/gratipay/finances/issues/22) porting to GnuCash and ([briefly](https://github.com/gratipay/finances/issues/27)) Odoo. Now with @nobodxbodon getting involved, we've been [porting](https://github.com/gratipay/finances/pull/35) the Ledger system to [Beancount](http://furius.ca/beancount/), which is a Ledger clone with better architecture, [documentation](https://docs.google.com/document/d/1RaondTJCS_IUPBHFNdT8oqFKJjVJDsfsn6JEjBG04eA/edit), and a built-in web reporting interface.

I'm pretty sure that a plaint-text accounting solution will be a good fit for Gratipay, but it may be too technical for your needs. Unfortunately there's not enough market demand for openness yet that products like Xero or QuickBooks would make it easy.

On the other hand we've used a simple Google spreadsheet for four years so that's not a bad option when starting out. :-)

**Comment by ntnsndr** [comment]
Thanks for all this. I think that, because of our current use of Goog Sheets, and the basic flexibility of that file format, and the simplicity of our books at this point, that will be the best approach.

But it would be awesome to have more open bookkeeping/distribution functionality in Gratipay:)

**Comment by whit537** [comment]
Agreed, anything more would be overkill for IoO at this point, and potentially for a long while. Gratipay is a more complicated scenario. I'm actually pretty excited about the accounting system we're developing, once we actually start _using_ it I hope to share about it more widely. :-)

@nobodxbodon Based on what you've seen so far, what are your thoughts on Gratipay joining the IoO Project Council?

**Comment by ntnsndr** [comment]
Sounds good.

On the other side, @whit537, can you TLDR the current state of the Gratipay nonprofit/co-op discussion?

**Comment by whit537** [comment]
From my pov, #72 is basically on hold until Gratipay is [growing again](https://gratipay.com/about/stats):

> Despite these relatively low barriers to entry, a collective that hopes to build a scalable platform business with a cooperative ownership model faces other challenges. During a panel that Juliet Schor and I participated in at the Platform Cooperativism conference, Schor highlighted an issue her research had uncovered about sharing economy cooperatives: that their value system was often better articulated than their value proposition. Put differently, cooperatives tended to focus too much on how the value would be shared rather than on a compelling offer to create the value in the first place.

—Arun Sundararajan in _Ours to Hack and to Own_, p. 142

Also of note: the Center for Open Science only recently fully transferred governance to their non-profit board from their two co-founders—this is after several years operating with a 5-10 MM budget.

**Comment by ntnsndr** [comment]
Hugely in agreement with your approach. Same with IoO. We're exploring, and I don't want to prescribe too much ahead of time. But I do think that Gratipay would be a great partner in this process of exploration.

**Comment by nobodxbodon** [comment]
@whit537 I wonder if the co-op companies/organizations have needs to raise funds. If so and they choose to use Gratipay, I'm not sure if that will cause any conflict of interests, as Gratipay can participate in deciding how the pool of funding is allocated.

According to the [charter](https://docs.google.com/document/d/1t_hrd4piQKvvpB-Uvoe4ofnHOd5pd9JIrmFnoS79uZM/edit#), Gratipay seems to meet all requirements. The requirement part sounds to me a bit ambiguous, but I suppose the charter is still under development and there'll likely be a continuous revising process for a while.

BTW the second project [coopdata](http://coopdata.org/) in IoO seems to be hacked:
![screen shot 2017-01-02 at 3 26 52 pm](https://cloud.githubusercontent.com/assets/392497/21597456/ed776b12-d0ff-11e6-9c96-e16752f07cdd.png)

**Comment by devinbalkind** [comment]
I wouldn't worry about a conflict of interest. Your website says Gratipay doesn't take a percentage of funds raised - so there is no direct financial incentive for people to use your product. Even if there were, I wouldn't worry about that.

Yes it seems you all quality.

Thanks for the heads up about coopdata. The site has been unhacked so you can learn more about it now.

**Comment by whit537** [comment]
Not hearing any objection ...

What are next steps, @ntnsndr?

**Comment by ntnsndr** [comment]
Thanks, Chad. The application is pretty brief, right here:
https://ioo.coop/project-council-application/

**Comment by whit537** [comment]
Relevant:

> IoOCloud (pronounced “yo-cloud”?!) is a proposal to create one such organization, demonstrating the viability of an alternative system of clouds built on community-built software and cooperative ownership.

https://ioo.coop/2017/01/14/prospectus-ioocloud-a-cloud-services-cooperative/
