### ISSUE TITLE
Adopt CVSS scoring system

### ISSUE THREAD

**Issue by EdOverflow** [gratipay/inside.gratipay.com#956]
I would highly recommend we start using [CVSS](https://www.first.org/cvss) terminology and scores to classify security reports.

Here is a CVSS v3 calculator: https://nvd.nist.gov/CVSS/v3-calculator

**Comment by whit537** [comment]
Of course there's a calculator inline on HackerOne as well:

![screen shot 2017-01-02 at 10 54 00 am](https://cloud.githubusercontent.com/assets/134455/21592241/e1f0fd88-d0d9-11e6-950f-c27bb43744f2.png)

That's on https://hackerone.com/reports/176396. @dmk246 Are you okay with adopting this? It's more complicated but more accurate as a result.

**Comment by EdOverflow** [comment]
@whit537 I just wanted our team to play around with CVSS, before coming to a conclusion. ;)

**Comment by whit537** [comment]
Did you fudge the calculation to get it to come out "Medium," or was that a happy coincidence? :)

**Comment by EdOverflow** [comment]
Let's call it a happy coincidence. ;)

In all seriousness, I am fairly confident that my calculation is correct. Feel free to check it and let me know if you find something wrong.

**Comment by dmk246** [comment]
@EdOverflow can you check out [#165313](https://hackerone.com/reports/165313) and see if it is rated correctly?  @whit537 and I went through this one to help me understand it better.

**Comment by EdOverflow** [comment]
@dmk246 CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N is spot on! :)

**Comment by dmk246** [comment]
Thanks @EdOverflow!!!
 and @whit537 for your help!!

**Comment by whit537** [comment]
> if we’re going to go with CVSS then I think we’ll need to revise our bounties along with that.

[slack](http://gratipay.slackarchive.io/gratipay/-/1486070506.005159/1486211624.005334/1486211624005334/)

**Comment by whit537** [comment]
I don't find the slack link now, but @EdOverflow commented that "Everything is coming out medium" is a known problem with CVSS v3. If that's the case then it may be better to stick with the simple five-point scale instead of going with CVSS.

**Comment by whit537** [comment]
Let's try and close this with https://github.com/gratipay/inside.gratipay.com/pull/1018.

@EdOverflow @dmk246 Can you go ahead and reclassify all triaged reports according to CVSS? That should give us enough info to decide on bounty amounts. We're leaning towards $0 for Medium, but it would be good to have a sense of how common High will be before committing to a revised amount there.

**Comment by EdOverflow** [comment]
> Can you go ahead and reclassify all triaged reports according to CVSS?

I'm on to it.
