### ISSUE TITLE
Prioritize and budget for 2017 events

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#960]
Okay, @gratipay, can we talk about how we want to use funds for [events](https://github.com/gratipay/inside.gratipay.com/labels/Events) this year?

- I am interested in going to **OSCON** (#948), because it's the most significant open source conference, and I / Gratipay have never been. If we're gonna play in open source, we can't have never gone to OSCON! Especially if we want to tap into _corporate_ open source, which we do, because that's where the money is. I [estimate](https://github.com/gratipay/inside.gratipay.com/issues/948#issuecomment-270432522) I could do OSCON for $1,200.

- Then there's **$ustain** (#920), which I really think we need to participate in if we're going to stay relevant. For budgeting purposes that would come under #921. I'm [putting](https://github.com/gratipay/inside.gratipay.com/issues/921#issuecomment-270440960) that at $1,330. @clone1018 is also interested in attending—maybe we can split a room?

- **EuroPython** (#894) is @JessaWitzel. Do you want to make a proposal for using some Gratipay funds for that trip, @JessaWitzel? I think even a small amount would be good, to start branching out beyond me as the sole goer-out-there-er.

- **Open** (#940)—I will bump that to see if there is any travel assistance available. Not sure we can get there otherwise.

- And then there's the **Retreat** (#927). Do we still want to try to pull that off in February? Does it make more sense to [bump](https://github.com/gratipay/inside.gratipay.com/issues/392#issuecomment-240693047) to August? How much money do we want to use from Gratipay for that?

We have $2,800 in the bank right now, and are accumulating approximately $55 per week ([150](https://gratipay.com/Gratipay/receiving/) - [95](https://docs.google.com/spreadsheets/d/1p3DpF9ZLEsViBx0685FwJaYN1vVScKVUgXHb2zyqXZg/edit#gid=1)) after #928 (!m @nobodxbodon), which is about $230/mo and $2,900 per year. I'm willing to put up some personal cash for a May trip to Austin and SF for OSCON and $ustain. How much Gratipay cash do we want to allocate for each of these events?

**Comment by clone1018** [comment]
If Gratipay wants me to go to $ustain and representing Gratipay, I'd like to be compensated for any event costs, however I'm fine with the flight. Maybe I can sleep on a floor or a couch of someones?

Could we share a room for OSCON?

**Comment by whit537** [comment]
There may not be fixed event costs but it'd probably be good for us to chip in since our logo is [apparently](https://github.com/gratipay/inside.gratipay.com/issues/920#issuecomment-269386135) going on a poster. ;-)

**Comment by whit537** [comment]
> Could we share a room for OSCON?

I'm game. Let's develop a budget/plan together on #948.

**Comment by nobodxbodon** [comment]
Trying to think of any potential additional costs, other than the fixed costs. Some things in mind:

- extra web traffic we need to handle if integrating npm takes off. I suppose the service handled heavy load before, so maybe we don't need to upgrade service plan on Heroku.
- any extra resources needed by [performance project](https://github.com/orgs/gratipay/projects/11) ?

**Comment by whit537** [comment]
@nobodxbodon Sounds like you're expanding the scope beyond events, ya? Not a bad thing to do but we may want to look at that in a dedicated ticket.

**Comment by nobodxbodon** [comment]
@whit537 I agree. Only reason is that I want to make sure we won't be short in the hard cost.

**Comment by nobodxbodon** [comment]
@whit537 some thoughts **without** taking budget into account. If N>1 contributors go to OSCON, there can be more exposure and feedback (closer to xN). Whilest $ustain sounds like a small round-table meeting, and I don't quite see much extra benefits to have more then 1 representitives. 

That said, as far as we can afford it, the more people the merrier, for all events!

**Comment by whit537** [comment]
> Whilest $ustain sounds like a small round-table meeting

But also [highly focused on our domain](https://sustainers.github.io/website/about.html):

> ### Sustainer?
>
>A sustainer is someone who evangelizes and passionately advocates for needs of open source contributors.
>
>They educate the public through blog posts, talks & social media about the digital infrastructure that they use everyday and for the most part, take for granted.
>
>They convince the companies that they work for to donate money, infrastructure, goods and/or services to the community at large. They also talk to the companies that they don’t work for about the benefits of doing the same things.

We _definitely_ want to meet those people!

**Comment by whit537** [comment]
Alright, I'm ready to pull the trigger on @clone1018 and I going to both OSCON (#948) and $ustain (#920) together. Let's figure out what Gratipay can commit.

**Comment by whit537** [comment]
$2,800 in the bank. How about $750 or $1000 for May? We should be able to save up another $1,250 or so to use for EuroPython and the retreat come summertime.

**Comment by whit537** [comment]
Flight to London for #940 is only $540 right now!

**Comment by whit537** [comment]
[Too good to be true](https://github.com/gratipay/inside.gratipay.com/issues/940#issuecomment-274096064). :-/

**Comment by whit537** [comment]
OSCON, Sustain: ✅ 
EuroPython, Open, Retreat: ❌ 

Latter half of 2017 I'm looking at All Things Open (#1106) and Open Source Summit (#1044). Both are roughly comparable to OSCON I think. More touchpoints with the corporate open source scene. ATO we've done before. I'm slated to speak this year ... could maybe go fishing for travel help? Summit is a Linux Foundation event, could stand to make more connections with them. They're the big fish in the small pond that is [current value capture](https://gratipay.news/open-source-captures-almost-none-of-the-value-it-creates-9015eb7e293e).

Both probably $1,200 each? Would have to invest into Gratipay to afford since cash is at about $1,600 and barely holding steady (cf. #1129).

**Comment by whit537** [comment]
I've put money down for #1044.

Since we're focusing on npm support we should probably think about JS conferences in 2018 vs. generalist enterprise-y ones (OSCON, OSSummit, ATO).

**Comment by whit537** [comment]
Last event is coming up, don't see any more this year.

**Comment by whit537** [comment]
> Both probably $1,200 each?

Managed to clock in under $600 for #1044, on target for even less for #1106.
