### ISSUE TITLE
onboard @PeterDaveHello

### ISSUE THREAD

**Issue by PeterDaveHello** [gratipay/inside.gratipay.com#965]
Thanks for invitation from @whit537 - https://github.com/gratipay/gratipay.com/pull/4276#issuecomment-270993677

I'm PeterDaveHello, currently, still a master degree student major in computer science, besides student role, I'm also a active free and open source project contributor.

 - https://www.peterdavehello.org/
 - https://twitter.com/PeterDaveHello
 - https://github.com/PeterDaveHello

**Comment by whit537** [comment]
Cool! So, the next step is to add you as a contributor on GitHub so you can make PR branches in the main repo instead of a fork. I've just posted some notes on [how we approach PRs](http://inside.gratipay.com/howto/use-github). May I send you an invite? :)

**Comment by PeterDaveHello** [comment]
@whit537 of course!

**Comment by whit537** [comment]
[slack](http://gratipay.slackarchive.io/gratipay/-/1483656409.00196/1483737498.002067/1483733739002022/)
