### ISSUE TITLE
one-page issue index

### ISSUE THREAD

**Issue by nobodxbodon** [gratipay/inside.gratipay.com#970]
Here's an ongoing attempt to index all the issues in one place. Maybe this is better to be in wiki, but I don't seem to have access. Please advise better forms and means, and welcome to edit.

- governance & process
  - mission
    - #987 Make it easier for companies to fund open source
    - #961 Backup Medium 
    - #916 Convert to a non-profit
    - #801 Articulate a brand story and positioning
    - #692 protect the Gratipay brand
    - #438 incorporate in Estonia
    - #325 distributing -> sharing
    - #324 implement Companies as a Service
    - #196 bring on a second owner
    - #72 adopt a cooperative operating agreement 
  - compliance
    - #528 we need a work contract
    - #222 join the U.S.-{EU,Swiss} Safe Harbor
    - #220 buy business insurance
    - #202 file for DMCA safe harbor
  - terms
    - #926 Clarify terms around notification
    - #918 Limit Gratipay's copyright license in Terms of Service (TOS)
    - ~~#972 Actually mail the terms notification~~
    - ~~#925 reference to "state laws" in TOS~~
  - process
    - #984 get any possible help by outsourcing with remaining weekly budget 
    - #875 establish process for reviewing account settings
    - #789 revise security program for higher signal
    - #661 appraise our CMMI maturity level
    - #648 Fast-track approval for owners who already have approved teams
    - #530 develop an incident response policy
    - #529 rotate all keys/passwords regularly
    - #520 fill @rummik's spot on the Safety Team
    - #495 Over-broad Criteria for Team Review
    - #379 formalize log retention policy
    - #376 Establish criteria for sending emails to all users
    - #289 Document how to change Team owner
    - #239 do sanction screening
    - #223 beef up the infosec portion of our risk program
    - #219 establish a customer due diligence (CDD) program
    - #214 implement a PCI self-assessment program
    - #189 better integrate translators
    - #119 establish a proper AML program
    - #113 howto: handle chargebacks
    - ~~#986 make sure our TWYW distribution is what we want~~
    - ~~#880 move radar content to Inside Gratipay~~
- finances
  - capital
    - #885 Apply for Purpose Fund
    - #870 do a kickstarter
    - #864 Apply for Lighter Capital
    - #845 Apply for open data incubator
    - #778 Use F6S
    - #733 apply for Stripe Open-Source Retreat
    - #637 seek funding from Mozilla
    - #407 apply for an Ashoka Fellowship
    - #406 apply for a Working World loan
    - #405 capitalize
    - #116 BountySource bounties
    - #68 pursue venture capital
    - ~~#896 Apply for NLnet~~
  - accounting
    - #993 Incongruity in payment amounts
    - #736 investigate PayPal denials
    - #491 Update MassPay documentation to reflect exchange_routes table
    - #401 watch transactions and consider getting a new PNC card
    - #306 draw $2,000 back to whit537
  - budget
    - #960 Prioritize and budget for 2017 events 
    - #928 review fixed cost 
    - #617 adapt to GitHub's new pricing
    - #333 pay for IcoMoon
- networking
  - partnerships
    - #954 Join the IoO Project Council?
    - #950 show gratitude to company sponsors of gratipay 
    - #421 become an Enspiral Venture
    - #305 get underwritten by PayPal
    - #256 partner with Trulioo 
    - #218 join the TPPPA 
    - #143 join the Open Innovation Network?
    - #483 ~~partner with Atmosphere.js~~
    - #441 ~~partner with Chocolatey~~
  - events
    - #990 Go to some CMU career fairs or something
    - #948 Go to OSCON 2017
    - #940 Go to Open
    - #927 Gratipay Retreat 2017
    - #921 Go to San Francisco 
    - #920 Participate in $ustain
    - #894 Go to EuroPython 2017!
    - ~~#930 Go to Open Source Leadership Summit~~
    - ~~#889 Go to US PyCon 2017!~~
  - follow others
    - #792 track my.enspiral
    - #554 track Cobudget
    - #458 track Open Collective
    - #316 track Bountysource
- marketing
  - #980 Use "free" linkedin ads for promoting
  - #969 reach out to the maintainers of the projects having potential giver
  - #914 Guest-post from Justin Dorfman
  - #413 make a "marketing for oss" microsite
  - #412 run an "open sales" experiment
  - #378 guest on Winning Slowly
  - #177 find next traction channel
  - #137 Create new Gratipay stickers
  - #51 Migrate marketing items to BG 
  - ~~#959 encourage contribution - make it obvious that gratipay is OS project~~
  - ~~#917 Actually, don't use Pipedrive~~
  - ~~#877 Release @gittip on Twitter~~
- infrastructure
  - communication and knowledge sharing
    - #970 one-page issue index (here)
    - ~~#913 Set up Slack~~
  - architecture
    - #976 continuous deployment 
    - #975 deploy branches to heroku automatically 
    - #957 Use Cloudflare 
    - #946 Review usage of Heroku
    - #503 standardize grtp.co and gip.rocks
    - #146 Simplify information architecture of Inside Gratipay
    - ~~#872 monitor Heroku db upgrade~~
    - ~~#871 switch to Heroku Teams~~
  - security
    - #971 Require GPG signing of commits
    - #956 Adopt CVSS scoring system 
    - #943 HTTPS support on inside.gratipay.com
    - #776 implement procedure for updating dependencies
    - #775 require 2FA to be on Gratipay GitHub org
    - #660 process DMARC reports
    - #561 set up a sandbox for security researchers
    - #522 Add search function to IG
    - #511 bring all domains into scope for security program
    - #493 renew PGP key
    - #480 Use LXD for testing and working with codebase
    - #159 make it easy to change all security credentials
  - backup
    - #939 backup github contents 
    - #470 Review and document backup policies
    - ~~#932 Revise offsite backup procedure~~
- development
  - requirement analysis
    - #991 Gratipay Experiments
    - #983 support more ways to login 
    - #982 integrate with software repositories / package manager 
    - #977 improve accessibility 
    - #974 support more means of payin and payout
    - #973 implement a basic income
    - #964 user stories of supporting paying to any packages in npm 
    - #941 Pivot to focus on givers
    - #895 Improve payday documentation
    - #790 implement http://status.gratipay.com/
    - #563 make Gratipay work for Asciidoctor [invoiced payins] 
    - #423 bring back no-strings-attached gifts to individuals
    - #309 find or make a library library 
    - #125 launch widgets v2
    - ~~#893 represent potential givers to reach out to project/site owners~~
    - ~~#892 how to fund individual OS contributors to big project like Python~~
  - out sourcing
    - #812 find a design firm
  - fixes
    - #839 teams table is wider than header on mobile version
    - #585 Add our DNSimple credentials to Lastpass
    - #461 Precompile all sass
    - #428 fix markdown regressions from switch to mistune
    - #417 inside.gratipay.com repo does not have a CONTRIBUTING.md file.
    - #341 SVG mime-type is incorrectly served by dev server
    - #307 propagate filesystem_tree.py changes to other libraries 
    - #245 Implement 404 testing strategy
    - #243 Add Glossary page
    - #147 switch to libre fonts 
    - #57 Link to a style guide for CSS 
    - ~~#947 Fix deployment again~~
    - ~~#873 404 Error on inside.gratipay.com~~
    - ~~#97 Web should be mouseless - shortcuts for paging~~
- onboarding
  - #952 onboard @EdOverflow
  - #949 onboard @simonmichael
  - #936 onboard @kaguillera
  - #878 onboard @nobodxbodon
  - #830 onboard @dmk246
  - #616 onboard @sseerrggii
  - ~~#965 onboard @PeterDaveHello~~
- others

**Comment by nobodxbodon** [comment]
Hopefully all the open issues till 01/08/2017 are covered. Working on the closed issues next.

**Comment by whit537** [comment]
Holy moly, @nobodxbodon. This is amazing! How about using [Labels](https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/)?

**Comment by whit537** [comment]
> Working on the closed issues next.

How about looking at the gratipay.com repo next?

**Comment by whit537** [comment]
Because classifying our open issues seems more valuable than our closed ones.

**Comment by nobodxbodon** [comment]
@whit537 I try to use the same labels (governance, events, etc) when applicable, and please feel free to change if you find any of the categories not proper.

OK I'll start on gratipay.com issues next. Any suggestion on how to categorize?

**Comment by whit537** [comment]
This is wierd but I like it. I like having a comprehensive view of all of our issues. Could we make an [appendix for Inside Gratipay](http://inside.gratipay.com/appendices/) that does this automatically based on labels?

**Comment by nobodxbodon** [comment]
Right I was thinking about using label mechanism to auto generate tree as well, but realized it wasn't a 1-hr project, plus I wanted to go over all the issues myself anyways. 

There'll definitely be more motivation when I'm overwhelmed by maintaining the page (currently with <5 new issues per day I'm still fine). Also, we may adjust the categories before using them as labels.

**Comment by nobodxbodon** [comment]
Speaking of indexing the issues in gratipay.com, how about closing those issues that are high-level discussions rather than actionable items (bug, quick improvements, feature with concrete design), and open new issue or merge with similar issues in inside.gratipay.com? This way, gratipay.com issues can be more in control, and the audiences who are more willing to involve in discussions without technical details can have one single place (here) to meet.

Besides, is there any explanation about the labels used in gratipay.com issues? Like TeamX and TeamX*, etc.

**Comment by mattbk** [comment]
http://inside.gratipay.com/howto/label-github-issues?

**Comment by nobodxbodon** [comment]
> how about closing those issues that are high-level discussions rather than actionable items (bug, quick improvements, feature with concrete design), and open new issue or merge with similar issues in inside.gratipay.com?

As example, I closed https://github.com/gratipay/gratipay.com/issues/84 and opened https://github.com/gratipay/inside.gratipay.com/issues/973. Looks OK?

**Comment by whit537** [comment]
Looks okay to me. :)

**Comment by nobodxbodon** [comment]
FYI I created an assembly issue [support more means of payin and payout](https://github.com/gratipay/inside.gratipay.com/issues/974) to assemble a dozen related issues in gratipay.com.

Besides I'll move the issues that are not user-oriented to here as well, like [deploy branches to heroku automatically](https://github.com/gratipay/gratipay.com/issues/1133)

**Comment by whit537** [comment]
> user-oriented

Why is that the criterion, rather than the scope of the issue (gratipay.com vs. Gratipay as an organization, or cross-repo product questions)?

**Comment by nobodxbodon** [comment]
IMHO it's the collaborators who are interested in non-user-oriented issues, as users should not be impacted by them directly. Plus I thought the "issues" section in the inside.gratipay.com repository are meant to keep all the issues for collaborators, which I suppose I was wrong about.

**Comment by whit537** [comment]
The user/collaborator [distinction](http://inside.gratipay.com/big-picture/welcome) does not map to the `gratipay.com` and `inside.gratipay.com` issue trackers. In fact, commenting on _any_ of [our 30 repos](https://github.com/gratipay) is a step on the way from user to collaborator! 💃

**Comment by nobodxbodon** [comment]
I see your point, and I will +100 for more user feedback like the latest https://github.com/gratipay/gratipay.com/issues/4293, not to mention how much I like to see users become collaborators. 

I hope to make user feedback like above to stand out, and to have higher priority than the non-user-oriented ones, which most likely are brought out by collaborators themselves. Those maybe 80% of the non-user-oriented issues just over-shadow the other 20%, which the collaborators and more importantly the potential contributors should have paid more attention to.

Seems to me, for potential contributors that see the issue list (like me before I join) at first sight, the issues that are 2-4 years old without updating in 1-2 years just seem like "we thought about it but that's it" or "we can't fix the blockers for those somehow". IMO it's discouraging contribution than encouraging, and for many of those issues it may be better to reference by category on a "TODO list" kind of page on the website, and/or linked by README of the repository, and then close them in tracker. The collaborators or whoever interested are still able to revisit them whenever they have time and reopen whenever decide to work on any, and potential contributors won't be scared off by them in the beginning.

**Comment by whit537** [comment]
> I hope to make user feedback like above to stand out, and to have higher priority than the non-user-oriented ones, which most likely are brought out by collaborators themselves.

How about a label? :)

**Comment by nobodxbodon** [comment]
> How about a label? :)

That can be helpful, if with proper document and obvious link on README to easily access the list of issues with this label. Currently the labels are kind of mixed (star, "Team_", "ready to start", etc) and can be confusing.

**Comment by whit537** [comment]
I agree that our labeling is due for an overhaul. We should also fold together these three pages:

http://inside.gratipay.com/howto/label-github-issues
http://inside.gratipay.com/howto/develop-software
http://inside.gratipay.com/howto/use-github

**Comment by nobodxbodon** [comment]
About labeling, it may be clearer to add different aspects (area/status/type, etc), like https://github.com/google/dagger/issues. Maybe 'priority' as well?

Something like:

area: design/UI/data/documentation
status: discuss/blocked/ready to start
type: bug/enhancement/new feature
priority: critical/major/normal/minor (same as https://www.drupal.org/core/issue-priority)

Still, maintaining labels are quite some work, as priority of issues can change over time.

**Comment by whit537** [comment]
I think we should handle prioritization via project boards, not labels. Our new work taxonomy is:

- [Roadmap](http://inside.gratipay.com/big-picture/roadmap)
  - Epic
    - Project
      - Issue/PR
        - Task

Other than that I think a hierarchy for labels would be great. Cloud Custodian provides [another example](https://github.com/capitalone/cloud-custodian/labels) of this pattern. Seems like the outline in the description on this ticket is a good starting point, ya?
