### ISSUE TITLE
Require GPG signing of commits

### ISSUE THREAD

**Issue by EdOverflow** [gratipay/inside.gratipay.com#971]
I would recommend that Gratipay developers start signing commits with their GPG key.

Here is GitHub's tutorial on getting this set up: https://help.github.com/articles/signing-commits-using-gpg/

**Comment by mattbk** [comment]
Maybe we could add to http://inside.gratipay.com/howto/develop-software?

**Comment by EdOverflow** [comment]
@mattbk Done. https://github.com/gratipay/inside.gratipay.com/commit/8cf856753747573bd22872ed9c3f8fb5939c75b9

**Comment by mattbk** [comment]
Sounds like this is done then!

**Comment by whit537** [comment]
Do we have a mechanism to _enforce_ this?

**Comment by EdOverflow** [comment]
@whit537 I currenty cannot come up with any mechanism in order to enforce GPG signing. How do you want to enforce this?

**Comment by whit537** [comment]
Skimming GitHub's tutorial, this sounds like a lot of work. What's the value? What's our threat model?

**Comment by EdOverflow** [comment]
I already sign some commits with GPG and I am not to sure why this would be a lot of work. I would like to make this a requirement for commits to the security repo. That way we can validate that the commits have come from an identified source.

**Comment by whit537** [comment]
I see GPG as somewhat complicated to set up and remember to use. I think it'll add too much friction to ask all @Gratipay developers to use it.

Can we limit signing to the master repo, or something like that? Does *every* commit need to be signed, or only the ones going out to production?

Again, what's the threat model here?

**Comment by EdOverflow** [comment]
> I see GPG as somewhat complicated to set up and remember to use. I think it'll add too much friction to ask all @Gratipay developers to use it.

Although it is possible to automatically sign commits, I agree with you that requiring all @Gratipay developers to sign commits is difficult.

> Can we limit signing to the master repo, or something like that? Does every commit need to be signed, or only the ones going out to production?

Not every commit needs to be signed. I suggest we only sign security patches in @gratipay/security that will be deployed to production.

> Again, what's the threat model here?

There is no serious threat, therefore this should not be a priority. Signing commits would simply allow us to verify that commits are actually from a trusted source.
