### ISSUE TITLE
Actually mail the terms notification

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#972]
gratipay/gratipay.com#4232 &rarr; gratipay/gratipay.com#4282 &rarr; &hellip;

- [x] Mail all of them, tracking bounces in SQS.
- [ ] Manually retrieve bad addresses from the queue—**within 14 days!**—and drop them to unverified in the database.

**Comment by whit537** [comment]
Testing with my account and with a test one that is bouncing. I'm looking for the bounce notification to queue up in SNS.

**Comment by whit537** [comment]
Well, SQS via SNS.

**Comment by whit537** [comment]
The queue is working! I see delivery notifications in it.

**Comment by whit537** [comment]
The subquery for recent exchanges is adding significant run time to `queue-branch-email`.

**Comment by whit537** [comment]
406, as [expected](https://github.com/gratipay/gratipay.com/pull/4282#issuecomment-271388271). 👍 

```
~ $ queue-branch-email all
Are you ready? [y/N]y
Are you REALLY ready? [y/N]y
... ? [y/N]y
Okay, you asked for it!
406
spotcheck: []
spotcheck: []
spotcheck: []
spotcheck: []
spotcheck: []
But really actually tho? I mean, ... seriously? [y/N]
```

**Comment by whit537** [comment]
Alright! I sent a final working test to myself. Ready? Nothing ventured, nothing gained! 😓

**Comment by dmk246** [comment]
Ready....set....GO!
You got this @whit537 !!

**Comment by whit537** [comment]
[slack](http://gratipay.slackarchive.io/gratipay/-/1483908942.002263/1483999228.002369/1483997483002361/)

**Comment by whit537** [comment]
Got mine!

![screen shot 2017-01-09 at 5 28 53 pm](https://cloud.githubusercontent.com/assets/134455/21786323/5228493c-d691-11e6-9d67-7f4731cb6c40.png)

**Comment by whit537** [comment]
Email queue is empty!

**Comment by whit537** [comment]
> We just emailed a notice about our recent Terms of Service change. ✉️  In case you missed it: https://gratipay.news/from-teams-to-projects-45c46718507b. 👍

https://twitter.com/Gratipay/status/818586939850772480

**Comment by whit537** [comment]
Hopefully tomorrow I can download the info from the SQS queue and see how many bounces and complaints we got.

**Comment by whit537** [comment]
Seems like we're in pretty good shape. 👍

![screen shot 2017-01-09 at 5 42 01 pm](https://cloud.githubusercontent.com/assets/134455/21786657/0e6c6f00-d693-11e6-9037-feb7c9eb5865.png)

![screen shot 2017-01-09 at 5 42 13 pm](https://cloud.githubusercontent.com/assets/134455/21786656/0e6b60d8-d693-11e6-8758-bf3736cc5a8d.png)

**Comment by whit537** [comment]
The spike back in December is interesting. Security researcher?

**Comment by whit537** [comment]
Branch file cleared in https://github.com/gratipay/gratipay.com/commit/da2bd9c0cab3b45dee8217bc048b2ce8f5bf3e9e.

**Comment by whit537** [comment]
http://boto3.readthedocs.io/en/latest/reference/services/sqs.html

**Comment by whit537** [comment]
http://boto3.readthedocs.io/en/latest/guide/sqs.html#processing-messages

**Comment by whit537** [comment]
Downloading raw json with:

```
[gratipay] $ run defaults.env local.env ./download-email-status-queue.py
.............................................
```

-------------------

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, print_function, unicode_literals

import json
import sys
import time

import boto3

sqs = boto3.resource('sqs')
queue = sqs.Queue('https://sqs.us-west-2.amazonaws.com/482083521290/email-status-notifications')

while 1:
    for message in queue.receive_messages():
        try:
            msg = json.loads(message.body)
        except:
            import pdb; pdb.set_trace()
        open('email_status_queue/{}.json'.format(msg['MessageId']), 'w+').write(message.body)
        message.delete()
        sys.stdout.write('.')
        sys.stdout.flush()
    time.sleep(0.5)
```

**Comment by whit537** [comment]
Oh that's right. ☺️

```
(Pdb) message.body
'Blah blah.'
(Pdb) message.delete()
{'ResponseMetadata': {'HTTPStatusCode': 200, 'RequestId': '41bcbb9e-50dc-566c-b606-eb71059f18ed'}}
(Pdb)
```

**Comment by whit537** [comment]
Got 'em! 👍

```
[gratipay] $ ls *.json|wc -l
     428
[gratipay] $
```

**Comment by whit537** [comment]
Committed to a local git repo just to be safe ...

**Comment by whit537** [comment]
Polled the queue through the AWS console. It's empty. 👍

Gonna leave that so we can keep collecting bounce messages ahead of https://github.com/gratipay/gratipay.com/issues/4284.

**Comment by whit537** [comment]
I've deleted the secret key that I used for this.

**Comment by whit537** [comment]
Okay! Signed out of AWS. Now to inspect the files and see how many bounces and complaints we got!

**Comment by whit537** [comment]
```
[gratipay] $ ./process-emails.py 
423  Delivery
  4  Bounce
[gratipay] $
```

----------------------

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, print_function, unicode_literals

import collections
import json
import os


counts = collections.defaultdict(int)


for filename in os.listdir('email_status_queue'):
    if not filename.endswith('.json'): continue
    try:
        raw = open('email_status_queue/'+filename).read()
        message = json.loads(raw)
        message = json.loads(message['Message'])  # Aaaah, Jeff Bezos! :)
    except Exception as exc:
        print(exc)
        import pdb; pdb.set_trace()
    counts[message['notificationType']] += 1

for nmessages, notification_type in reversed(sorted((v,k) for k,v in counts.items())):
    print('{:>3}  {}'.format(nmessages, notification_type))
```

**Comment by whit537** [comment]
Two were me testing, two were legit—we caught two bounces! 💃

**Comment by whit537** [comment]
Now I guess we just manually mark those as unverified, ya?

**Comment by whit537** [comment]
I'm working up a SQL script to do the unverifying. We don't have that API in Python or HTTP. I'm snagging an `add_event` example payload to include an `unset` event.

**Comment by whit537** [comment]
Actually, we don't have an event associated specifically with verification (only `add` and `set` primary), so I'm not going to worry about that.

**Comment by whit537** [comment]
Working with [`remove_email`](https://github.com/gratipay/gratipay.com/blob/2035/gratipay/models/participant/__init__.py#L516-L522) instead of unverifying ...

**Comment by whit537** [comment]
Tested locally with:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, print_function, unicode_literals

import sys

from gratipay import wireup
from gratipay.models.participant import Participant


bad_address = sys.argv[1]
db = wireup.db(wireup.env())

participant = db.one('select p.*::participants from participants p '
                     'where email_address=%s', (bad_address,))
db.run('update participants set email_address=null where email_address=%s', (bad_address,))
participant = Participant.from_id(participant.id)  # refresh self.email_address
participant.remove_email(bad_address)
```

**Comment by whit537** [comment]
Ooh! Even better. :-)

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, print_function, unicode_literals

import sys

from gratipay import wireup


bad_address = sys.argv[1]
db = wireup.db(wireup.env())

participant = db.one('update participants p set email_address=null '
                     'where email_address=%s returning p.*::participants', (bad_address,))
participant.remove_email(bad_address)
```

**Comment by whit537** [comment]
Okay!

```
heroku run bash
```

**Comment by whit537** [comment]
```
cat > remove-bad-address.py << EOF
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, print_function, unicode_literals

import sys

from gratipay import wireup


bad_address = sys.argv[1]
db = wireup.db(wireup.env())

participant = db.one('update participants p set email_address=null '
                     'where email_address=%s returning p.*::participants', (bad_address,))
participant.remove_email(bad_address)
EOF
```

**Comment by whit537** [comment]
```
chmod +x remove-bad-address.py
./remove-bad-address.py []
./remove-bad-address.py []
```

**Comment by whit537** [comment]
Confirmed in the UI for email and events for both participants.

Huzzah! 💃

**Comment by whit537** [comment]
I've thrown away the email status queue. We are done here.
