### ISSUE TITLE
support more means of payin and payout

### ISSUE THREAD

**Issue by nobodxbodon** [gratipay/inside.gratipay.com#974]
As there are quite a few similar issues in gratipay.com, all are re-ticketed here for further discussion and planning. After deciding on concrete implementation plan and dev work starts, we'll reopen specific issue for tracking purpose.

| Service | Payin | Payout | Supported Processors (partial) |
| ------------- | ------------- | ------------- | ------------- |
| currencies other than USD | https://github.com/gratipay/gratipay.com/issues/13 https://github.com/gratipay/gratipay.com/issues/1165 https://github.com/gratipay/gratipay.com/issues/3135 | |
|Uphold | https://github.com/gratipay/gratipay.com/issues/3870 | https://github.com/gratipay/gratipay.com/issues/3870 |
| ACH debit |  https://github.com/gratipay/gratipay.com/issues/777 | https://github.com/gratipay/gratipay.com/issues/3920 | Braintree Stripe |
| dwolla | https://github.com/gratipay/gratipay.com/issues/65 | https://github.com/gratipay/gratipay.com/issues/726 |
| Paypal | https://github.com/gratipay/gratipay.com/issues/63 | | Braintree Stripe |
| SEPA / IBAN | https://github.com/gratipay/gratipay.com/issues/3967 | |
| TransferWise | | https://github.com/gratipay/gratipay.com/issues/3855 |
| Trans-pay | | https://github.com/gratipay/gratipay.com/issues/417 |
| PaySafeCard | https://github.com/gratipay/gratipay.com/issues/3889 | |
| Nochex | https://github.com/gratipay/gratipay.com/issues/2325 | |
| Foreign Bank Account | [Canadian](https://github.com/gratipay/gratipay.com/issues/2179) | | Payoneer |
| mobile payments | [iphone in-app purchases](https://github.com/gratipay/gratipay.com/issues/183) | | Braintree Stripe(Apple) | Apple Pay |
| Create script for doing credit card pay-ins of specified [large] value | https://github.com/gratipay/gratipay.com/issues/2221 | |
| Skrill | https://github.com/gratipay/gratipay.com/issues/718 | https://github.com/gratipay/gratipay.com/issues/718 |
| bitcoin (dropped) | https://github.com/gratipay/gratipay.com/issues/4310 | https://github.com/gratipay/gratipay.com/issues/4310 | Braintree Stripe |
| venmo (dropped) | https://github.com/gratipay/gratipay.com/issues/1839 | | Braintree |
| visa checkout | | | Braintree |
| master pass | | | Braintree |
| Alipay | | | Stripe |  |
| faircoin | https://github.com/gratipay/gratipay.com/issues/4402 | https://github.com/gratipay/gratipay.com/issues/4402 | |

**Comment by whit537** [comment]
@nobodxbodon One of the values of having individual tickets for each payment option was that we could more naturally collect details as well as gauge user demand scoped to the particular option, which helps in evaluating the options. What are your thoughts on how to do that with this single mega-ticket?

**Comment by nobodxbodon** [comment]
@whit537 as you mention there are two folds - details and user demand. It's proved that there's user demand for each of the means above, while having 10 +1's in one issue doesn't guarantee higher priority than the other which has 5. IMO we as a project are better to set priority and discuss with the whole picture in mind, which this ticket is trying to provide.

About the details, I agree it's natural to put the specific details for an individual payment method in the corresponding issue, even if it's closed for now. If the details is relevant for other payment methods, we can extend the discussion here. For instance, based on gratipay/gratipay.com#4310, maybe it's worthwhile to add a column in the table "supported by Braintreee", to research which has built-in support from our processor.

**Comment by whit537** [comment]
> even if it's closed for now

That doesn't sound right to me. I think we should generally only comment on open tickets. GitHub may even suppress notifications for comments on closed tickets, if I'm not mistaken.

>  IMO we as a project are better to set priority and discuss with the whole picture in mind, which this ticket is trying to provide.

Fair enough, but can't we have both? Individual tickets to track details and user feedback for the individual options, plus this ticket or some other mechanism for decision-making?

**Comment by mattbk** [comment]
> add a column in the table "supported by Braintreee"

More than I thought! https://www.braintreepayments.com/payment-methods

**Comment by nobodxbodon** [comment]
> GitHub may even suppress notifications for comments on closed tickets, if I'm not mistaken.

As I just tested, at least the reporter of the issue still gets updates after issue is closed.

> Fair enough, but can't we have both?

Sure we can. There are just benefits in discuss in one place that I don't see otherwise. First, it lowers managing cost. Second, it gives user a clear view of the similar tasks we have on our plate and they will likely not just simply +1 to a specific payment method, but join in discussion of the overall plan. If we don't "push" user to this ticket, I don't see they will care so much about other similar (but competing in priority) requests.

Besides, I don't think closing the individual tickets hinders user feedback, as user are more likely to just open new ticket like gratipay/gratipay.com#4310 . And IMO they are proved to be legit feature request, and we already have enough knowledge about the relative popularity.

That all being said, plus [my preference to close 'hibernated' issues](https://github.com/gratipay/inside.gratipay.com/issues/970#issuecomment-272658288), managing issues needs team effort, and managing this kind of mega-ticket especially so. So, please reopen whichever you see necessary (last suggestion is to reopen "After deciding on concrete implementation plan and dev work starts", but feel free to ignore)

**Comment by whit537** [comment]
> There are just benefits in discuss in one place that I don't see otherwise.

Fair enough. Both benefits you name are valid. Since our mega-ticket here is the new status quo, it would take management cost to go back to individual tickets ... and I for one don't want to pay it right now. :) I'm willing to keep running with the new status quo and see how it continues to shape up.

**Comment by mattbk** [comment]
Here's one that fits well with the meta-ticket: [ShareX is based in Turkey, which can't receive PayPal payouts](https://getsharex.com/donate/). This is a +1 for "any payout method that isn't PayPal."

![image](https://cloud.githubusercontent.com/assets/3729038/22385964/84152e6c-e49a-11e6-9c51-3c699c0be073.png)

**Comment by nobodxbodon** [comment]
As Pareon [uses](https://patreon.zendesk.com/hc/en-us/articles/214796706-Where-is-my-Payout-) Stripe and Payoneer, they are included in the new column "Supported Processors" as well, besides Braintree.

**Comment by whit537** [comment]
For Payoneer, see https://github.com/gratipay/gratipay.com/issues/481.

**Comment by whit537** [comment]
Added faircoin: https://github.com/gratipay/gratipay.com/issues/4402.

**Comment by jhabdas** [comment]
@nobodxbodon @whit537 please update OP with info from #1094 and delete this comment. thanks.

**Comment by mattbk** [comment]
A repeated +1, here for consistency:

>  I totally understand the annoyance in donation methods, I've been trying to find services that would make it easy for distributed teams like this for a while but have had no such luck finding ones that support payins via a variety of options, and payouts for people no matter where they live via services other than PayPal. 

https://github.com/streamlink/streamlink/issues/1016#issuecomment-309307242
http://twitter.com/failvarez/status/877610541476331521

**Comment by mattbk** [comment]
Would it be possible to add Transferwise or ACH, but only for amounts over $xxx? That makes us seem a little more flexible. #dothingsthatdontscale

**Comment by whit537** [comment]
Braintree is rolling out ACH: https://www.braintreepayments.com/en-ee/features/ach-direct-debit.

**Comment by mattbk** [comment]
Does that mean we can build it in "relatively easily"?

**Comment by whit537** [comment]
I think so.
