### ISSUE TITLE
deploy branches to heroku automatically

### ISSUE THREAD

**Issue by nobodxbodon** [gratipay/inside.gratipay.com#975]
Reticket from https://github.com/gratipay/gratipay.com/issues/1133. Latest reference:

> Today, we are happy to announce the graduation of Heroku Review apps from an exceptionally popular beta to being generally available to all Heroku users.

> Review apps are the instant, disposable Heroku app environments that can spin up automatically with each GitHub pull request. They allow developers and their teams to automatically build and test any pull request, updated at every push, at a temporary, shareable URL. When the pull request is closed or merged, the Review app is deleted. GitHub users are notified of all this, right in the pull request web interface.

> https://blog.heroku.com/heroku-review-apps-ga.

**Comment by whit537** [comment]
This one is only relevant to gratipay.com, though. Why reticket it here?

**Comment by nobodxbodon** [comment]
I thought it's generally applicable for all our heroku apps, even if there's no branch for now in other apps.

**Comment by whit537** [comment]
Okay, I guess.
