### ISSUE TITLE
improve accessibility

### ISSUE THREAD

**Issue by nobodxbodon** [gratipay/inside.gratipay.com#977]
Related issues: 

[make gittip accessible to vision impaired people](https://github.com/gratipay/gratipay.com/issues/154)
[Web should be mouseless - shortcuts for paging](https://github.com/gratipay/inside.gratipay.com/issues/97)

I don't see feasibility without using existing front-end framework with good support in accessiblity.

**Comment by EdOverflow** [comment]
I believe the first step is to increase the contrast of the individual elements. That requirement is on this list: #4262

**Comment by nobodxbodon** [comment]
@EdOverflow the color contrast sounds like usability issue, while this is meant to focus on accessibility.

**Comment by whit537** [comment]
Contrast is definitely part of accessibility, though I'm not sure how it's part of performance (gratipay/gratipay.com#4262).
