### ISSUE TITLE
Spot -> Point -> Repair  --  bonus points for actions

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#98]
When as a user, I spot the problem, it still takes energy to report it and even more to repair. It will be nice to reward people for solving this quest. Because gratipay knows who you are on Github, it can reward with one-time achievements (solving the quest for the first time) and with score to compete monthly. See https://twistedmatrix.com/highscores/

**Comment by whit537** [comment]
> It will be nice to reward people for solving this quest.

PRs welcome.

> Because gratipay knows who you are on Github

Not always. Many users have only Twitter or Facebook linked.

Closing as out-of-scope. We need to stay focused.
