### ISSUE TITLE
Use "free" linkedin ads for promoting

### ISSUE THREAD

**Issue by nobodxbodon** [gratipay/inside.gratipay.com#980]
I get $50 LinkedIn ad credits occasionally (having one to expire on 1/26) . Shall we put some simple ads for gratipay? Linkedin sounds like a proper platform, with the professional exposure and targeted groups.

I'm not sure if the coupon code will be good for my only or anyone.

**Comment by whit537** [comment]
Thanks for offering to donate your ad credits, @nobodxbodon! I'm open to exploring ads as a channel. Do you think it's worth experimenting with before we have https://github.com/gratipay/gratipay.com/issues/4148 done?

**Comment by nobodxbodon** [comment]
@whit537 as the code expires on 1/26, I suppose it's worthwhile for simple promoting purpose without much efforts putting into designing Ads and managing it. BTW I think it's for text ads, not exactly sure about the restrictions, but I guess at least fonts and layouts are customizable to some extent.

**Comment by whit537** [comment]
I'm not going to invest attention in this right now, but if you want to, go for it! :-)

**Comment by nobodxbodon** [comment]
How's the preview? The empty blocks below are for other ads I guess.
![screen shot 2017-01-14 at 9 22 39 am](https://cloud.githubusercontent.com/assets/392497/21956714/29676ff2-da3b-11e6-99a1-4aab19f53ce2.png)

Clicking ad will lead to https://gratipay.com/

**Comment by nobodxbodon** [comment]
Maybe change "Project" to "Projects"?

**Comment by whit537** [comment]
Looks good to me, with that one correction. 👍

**Comment by nobodxbodon** [comment]
Do you want to highlight the open nature like below?
![screen shot 2017-01-16 at 10 38 03 am](https://cloud.githubusercontent.com/assets/392497/21995102/ec4ab270-dbd7-11e6-9b7c-ce9f9ec0cfcd.png)

**Comment by whit537** [comment]
I think that's confusing. At the point of contact on Linked In nobody cares that we're an open company. What problem are they already trying to solve themselves in an inefficient way, which we'll be able to help them solve more efficiently?

**Comment by nobodxbodon** [comment]
> What problem are they already trying to solve themselves in an inefficient way, which we'll be able to help them solve more efficiently?

That's a such big question that I don't think is in this the scope of this issue. I'll just go with the simple promote as confirmed before:
![screen shot 2017-01-16 at 1 03 17 pm](https://cloud.githubusercontent.com/assets/392497/21998913/3cfe5b68-dbec-11e6-9207-830694ac3c2c.png)

**Comment by nobodxbodon** [comment]
Campaign starts with targets below (240,000+ members):
```
    area: San Francisco Bay Area, Greater Pittsburgh Area

    industry: Computer Software, Information Services, Internet

    age: 35-54, 25-34, 18-24

    work experience: 1+ years

    Audience expansion: Enabled 
```

**Comment by nobodxbodon** [comment]
$10 credit spent, 4998 impressions, 0 click. With fine tuned target (140,000+ members):
```
    San Francisco Bay Area, Greater Pittsburgh Area

    Computer Software, Internet, Information Services

    Manager, Senior, VP, Owner, Director

    35-54, 25-34

    3+ years

    Audience expansion:Enabled
```

Changed to "Cost per click (CPC)" with $10 bid per click. Will see.

**Comment by nobodxbodon** [comment]
9,693 impressions, 1 click, $18.62 credit spent

**Comment by nobodxbodon** [comment]
148,516 impressions; 3 clicks; Spent $31.21. Not sure if I can spend the rest without chaning target user group.

**Comment by whit537** [comment]
So our click through rate is 0.003%. That's pretty bad. :-) The next question is whether any of the three clicks converted into either givers or receivers. Depending on the answer, our cost to acquire a customer through this channel is $10, $20, $30, or ∞.
