### ISSUE TITLE
get any possible help by outsourcing with remaining weekly budget

### ISSUE THREAD

**Issue by nobodxbodon** [gratipay/inside.gratipay.com#984]
With currently weekly budget, we can still put ~$40 to 1 or 2 issues that are high-severity/priority but low workload (for domain experts) on crowdsourcing site like BountySource. It'll require some additional burden to get new developers on board, but IMO still worth it.

**Comment by whit537** [comment]
Have you ever completed a bounty on BountySource? We've been on BS for years and have never gotten any traction from it. I don't think it's worth spending time on, personally.

**Comment by nobodxbodon** [comment]
The 4 issues that have >$10 bounty are:
```
allow for one-off tips
should be able to give non-anonymously
Make a tool to provide "backer updates" to your donors
Clean up db schema
```

IMO they are all way too big to be attractive issues for bounty hunters. None of them have clear scope, and the minimum workload needed of any one seems to be weeks if not more. 

This can be just wishful thinking, but I think it will be different if we:
1) aim the issues that have high visibility/severity but little estimated workload: 1-2 day for new developer with average expertise skills required for the issue, or hours for former developer that had experience with gratipay dev with environment setup already.
2) put at least $20 bounty on each

In case still no external developer is interested with those in time (1 week), let's raise the bounty, up-to the point where any of our internal collaborators feel it's worth their effort. In case that happens, I'd say we do a twyw internally with the earned bounty, among those who are involved in the issue.
 
One reason to bring this up at this point is, if we decide to roll out npm integration and make a hit, IMO it's better to polish the whole project as much as possible, and I see quite a few issues in tracker that seem to be good candidates. Will try to list some here.

**Comment by mattbk** [comment]
I would like to see money put toward TWYW...but I think there is some social pressure holding people back from taking more than @whit537 does. I know that TWYW is take what _you_ want, but do you see what I mean?

Not implying that Chad wants to hold people back--I think he wants the opposite.

**Comment by nobodxbodon** [comment]
@mattbk great point you raised. IMO it's one of the most critical issues in current twyw model. 

One thought, we use group intelligence instead of personnal intelligence to help this issue: 
1. a list of contributors is assembled for the pool we want to distribute
2. every contributor in the list who want to vote, put a number/percentage to any contributors on that list (need to sum to 100%)
3. get average of the votes above, which will be used to calculate the final number
4. of course not everyone will take the exact number in the final result, but that will ease the social pressure at least IMO

**Comment by nobodxbodon** [comment]
And:
5. @whit537 is the last one who takes, to make it even less pressure for all others to take :)

**Comment by mattbk** [comment]
Actually, I think he's the last anyway if TWYW is still operating under "kids eat first," where the newest members of the ~~team~~ project get first crack at taking.

**Comment by nobodxbodon** [comment]
Seems we don't have an issue discussing about twyw procedure internally. Maybe we need to re-ticket that part, and only focus on the BS topic here?

**Comment by whit537** [comment]
I'm happy to discuss our current twyw spread. If there's a way we can use that money more productively then by all means let's find it. I'm much more interested in that convo than in trying to make bounties work. I see bounties as a failed model, and one that is more or less antithetical to Gratipay. I think we should invest our time and effort in building a strong team using twyw, and retire BountySource if anything.

**Comment by nobodxbodon** [comment]
Moved TWYW to separate thread. 

@whit537 IMO $ amount is a reasonable scale to quantify exactly how much we want a certain issue done, no matter we use BS or not. We may put label like "$50" or "$20" to issue internally if we just want to do everything internally. Using BS (or any other similar service) is just to broaden our audience and increase level of public envolvement in our developing, which will result in more motivations for the internal collaborators even with no external interest attracted, and any additional help from the public would be just a bonus. 

> I see bounties as a failed model, and one that is more or less antithetical to Gratipay.

If it can accelarate our growing, IMO it's fine to grow together. We should be able to see the effectiveness of different models in the long run, but we need to grow first.

**Comment by nobodxbodon** [comment]
Here are some potential bounty candidate issues with relatively high visibility/severity, clear scope, and hopefully little estimated workload based on my very limited knowledge of Aspen. By "little" I mean: 
1-2 day for new developer with average expertise skills required for the issue with some pointers from internal developers, or hours for former developer that had experience with gratipay dev with environment setup already.

[make Team explorer pageable](https://github.com/gratipay/gratipay.com/issues/3738)
[Adjust tips from /%username/giving summary](https://github.com/gratipay/gratipay.com/issues/3107)
["Contact Me" link on ~user/Team profiles](https://github.com/gratipay/gratipay.com/issues/3831)
[Sharing is empty for teams; should at least include team owner](https://github.com/gratipay/gratipay.com/issues/3803)
[Team list for users with multiple teams is poorly spaced](https://github.com/gratipay/gratipay.com/issues/4133)

**Comment by whit537** [comment]
> If it can accelarate our growing

I don't think it can. 

> IMO $ amount is a reasonable scale to quantify exactly how much we want a certain issue done, no matter we use BS or not. We may put label like "$50" or "$20" to issue internally if we just want to do everything internally.

This doesn't sound right to me at all. Are you suggesting that we start adopting bounties internally? 😳

**Comment by nobodxbodon** [comment]
> I don't think it can.

Shall I put some bounty on one of the low-hanging fruits to see if it'll get external interest? If so could you check which of the [issues I listed](https://github.com/gratipay/inside.gratipay.com/issues/984#issuecomment-273024022) is most low-hanging? That is "1-2 day for new developer with average expertise skills required for the issue with some pointers from internal developers, or hours for former developer that had experience with gratipay dev with environment setup already."

> This doesn't sound right to me at all. Are you suggesting that we start adopting bounties internally? 😳

Either that or some kind of label that reflects the weight of the issue. By weight I mean benefit/cost.

**Comment by whit537** [comment]
I like the idea of recruiting more collaborators, but I don't think BountySource is the place to do it. We want community members, not mercenaries.
