### ISSUE TITLE
Run a hackathon at CMU

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#990]
@jimmyfabrizio works in career services at Carnegie Mellon University. He is telling me about the career fairs at CMU. There are a certain number of tables for companies of various sizes.

- huge tech fair in the fall, Technical Opportunities Conference (TCO), $1300 for one day (one price regardless of company size)
- huge general fair in the fall, Encompass, $475(?)
- smaller Encompass in the spring, $475 for small companies
- Creative Arts Opportunities Conference (CAOC—@jimmyfabrizio runs this one), $250
- Spark startup fair $0

CMU is of course a world-class research university right in Gratipay's backyard. We should make connections there both for collaborator recruiting and also marketing more generally.

We could also do a one-off hackathon or something. Discussing ...

**Comment by whit537** [comment]
- 4:30 pm to 5:30 pm
- bring pizza (@jimmyfabrizio might have leftover budget available for this)
- schedule it right after spring break, so ... mid to late march
- capacity of the room is 50
- pre-reg optional
- @jimmyfabrizio would market with students in the School of Design (his focus) as well as the School of Computer Science (with a coworker)
- value to students is (unpaid) internship opportunity in a startup environment—suitable for a segment of students, need to target that segment somehow

**Comment by whit537** [comment]
Just had a meeting with Tepper MBA student about a possible internship. Can we add them to the mix? Would love some bizdev.

Mostly I just want to get in front of a roomful of smart and energetic CMU folks so I can turn them on to the wonder of Gratipay! Give me 50 in a room and let me find the five that get it and the one or two that _really_ get it.

**Comment by JessaWitzel** [comment]
I have a close friend who is an Event Coordinator for the Computer Science dpt at Cornell University. She organizes their hack-a-thons alongside students. I am also an academic advisor at a community college in NC with graphic design and programming AAS programs (2 year). Just throwing that out there. I think a hack-a-thon could be GREAT for several reasons but has to be entered into very intentionally.

1. Get new contributors to Gratipay. I tell students who are interested in programming all the time that Github is their new best friend and that they need to find a way to contribute to open source software. We may get some ambitious students who want to contribute long term.
2. If you go in with a few project ideas you will see some progress on those ideas and get new ideas/questions you might not have thought of. You may see the idea completed but not in the way you expected.
3. You are putting Gratipay in the heads of the people who will be writing the next big projects. Even if it doesn't pay off immediately with new projects I think it has potential future implications for the next generation of software peeps. 

If you do this you should bring several people (depending on attendance of the event) who will spend their time mentoring and answering questions. You will have time to code but about half of your time will be spent helping everyone else. You should also have very clear goals and projects set up for them and a short "intro" talk scheduled to try to get everyone up to speed.

**Comment by whit537** [comment]
> I have a close friend who is an Event Coordinator for the Computer Science dpt at Cornell University. 

Nice! Cornell has a [great](http://grad-schools.usnews.rankingsandreviews.com/best-graduate-schools/top-science-schools/computer-science-rankings) CS program and Ithaca is about 5½ hours away from me by car. Maybe let's start with some events around Pittsburgh and if they prove fruitful we can branch out? Or should we open multiple conversations for this spring since we have to work within the academic year cycle?

> Even if it doesn't pay off immediately with new projects I think it has potential future implications for the next generation of software peeps.

Heck yeah! Same with the business school types on the other side of the equation (company givers).

**Comment by JessaWitzel** [comment]
I'm a fan of slow growth but that's up to you. :) I would have one in the Spring and if it's successful we can plan two or three in the Fall. I'm happy to help with this as THIS is totally in my wheel house. What percentage of CMU's career fairs is internship seekers? And how many interns do you think you can reasonably mentor while still being individually productive? I'm not sure a career fair is the right move, honestly but I love the idea of a hack-a-thon.

**Comment by whit537** [comment]
> I'm happy to help with this as THIS is totally in my wheel house.

Awesome! Where do you want to run it? CMU or your community college or Cornell or ... ?

**Comment by JessaWitzel** [comment]
CMU is great. I can get to Pittsburgh when needed.

**Comment by whit537** [comment]
> I can get to Pittsburgh when needed.

So awesome! Let's do it! 💃

**Comment by whit537** [comment]
I had a thought: at the end of the session we could do an in-real-life take-what-you-want split using gratipennies or something, like the Catalyst collective did [with pasta](https://github.com/gratipay/inside.gratipay.com/issues/683#issuecomment-232437204) ("pasta pay" 🍝  💸  💃 ).

**Comment by whit537** [comment]
Fizzled.
