### ISSUE TITLE
Gratipay Experiments

### ISSUE THREAD

**Issue by mattbk** [gratipay/inside.gratipay.com#991]
This is one of those meta-issues that may not have a way to easily close. I'm going to use it as a place to take notes.

I've mentioned this in a few issues. What works for one project may not work for another, so we should build Gratipay as a place where you can experiment with things within your project, but also see the aggregate data for what other projects are doing as well. 

- Weekly/monthly/oneoff giving
- TWYW vs even vs random
- Anon/not
- donating to basic income
- kids eat first vs. adults or smallest value first
- if funding a bundle of projects, distribution of funds: specifically allocated vs random vs even
- others?

Encourage projects to see what works for them, and track the data. Use to help projects fund themselves the best. This turns Gratipay into more than just a platform for receiving funding, it's a playground/lab for crowdfunders to analyze behavior.

- [ ] what are some metrics by which success of receiving could be measured?
- [ ] what are some metrics by which success of giving could be measured?

**Comment by whit537** [comment]
> random

😄

**Comment by whit537** [comment]
> This is one of those meta-issues that may not have a way to easily close.

Paging @techtonik! 😁

**Comment by mattbk** [comment]
> random

Psychology!

* http://www.nirandfar.com/2012/03/want-to-hook-your-users-drive-them-crazy.html
* and related https://getpocket.com/a/read/1538831147

**Comment by whit537** [comment]
https://blog.mixpanel.com/2017/04/11/mixpanel-signal-launch/

**Comment by whit537** [comment]
We've looked at cohort analysis in the past.

**Comment by techtonik** [comment]
Oh, I like that. I you would allow me to bloat it a little.. =) For some reason I see it (Gratipay Experiments) as a [polymer](https://www.polymer-project.org/) components that could be switched on and off without affecting too much of the rest of site structure.

Place each **Experiment-in-the-Box** with defined input data that is required from Gratipay, desired location or interface, and some docs how to turn it on and off.

I'd like to have a interface like a circle where you turn experiments on and off (checklists are boring) which will also be a voting interface. It will also answer questions like if your giving/receiving stats are public.

**Comment by techtonik** [comment]
My experiments (legalize):
* calculate tax for your country
* show your status and help you validate it
* donate to specific expenses that person registered
  * domain name
  * hosting
  * guns and drugs (a sanity test)
  * etc.?
  * isolate to open companies? or companies with public API?

**Comment by techtonik** [comment]
Also, experiment with `money-laundering` - what is money laundering and what is not, how to comply with legal requirements. Ouch.. I opened the floodgate again.. )

**Comment by mattbk** [comment]
Your examples seem almost like things a project owner would run through as part of a "complete your account setup" process, to teach them dos and don'ts.

Your Experiment-in-a-Box is what I was thinking of, though. A tool that could be used to maximize income, based on the donation history available.

**Comment by mattbk** [comment]
+1 at https://github.com/gratipay/inside.gratipay.com/issues/969#issuecomment-272311233

**Comment by mattbk** [comment]
Gratipay should be the "big data*" of OSS funding.


*Not really big data, but a large enough dataset to have fun with.
