### ISSUE TITLE
Payday 243

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/inside.gratipay.com#994]
[&larr; Payday 242](https://github.com/gratipay/inside.gratipay.com/issues/989)

---

##### Docs

http://inside.gratipay.com/howto/run-payday

##### Checklist

- [x] [Review accounts](http://inside.gratipay.com/howto/review-accounts)
  - [x] [New givers](https://gratipay.com/dashboard/)
  - [x] [1.0 Payout applications](https://gratipay.com/dashboard/1.0-payouts)
- [x] Trigger backup
- [x] Run payday script
- [x] Commit payday logs
- [x] [Run masspay](http://inside.gratipay.com/howto/run-masspay)
  - [x] DB query to update broken paypal fees
  - [x] Generate paypal inputs
  - [x] Verify there is no fee mismatch
  - [x] Submit masspay on paypal
  - [x] Post back masspay
- [x] Commit masspay logs
- [x] Review decline rate
- [x] Shuffle escrow

##### Rotation

| Month | Pilot | Copilot |
| :-- | :-- | :-- |
| February | @clone1018 :airplane: | @rohitpaulk |
| March | @whit537 | @clone1018 |
| April | @rohitpaulk | @whit537 |
| May | @clone1018 | @rohitpaulk |
| June | @whit537 | @clone1018 |
| July | @rohitpaulk | @whit537 |
| August | @clone1018 | @rohitpaulk |
| September | @whit537 | @clone1018 |
| October | @rohitpaulk | @whit537 |
| November | @clone1018 | @rohitpaulk |
| December | @whit537 | @clone1018 |
| January | @rohitpaulk | @whit537 |

**Comment by rohitpaulk** [comment]
Had to create this ticket manually, ref: https://gratipay.slack.com/archives/gratipay/p1485444553003803

**Comment by whit537** [comment]
And then the power went out! Picking up ...

**Comment by whit537** [comment]
http://gratipay.slackarchive.io/gratipay/-/1485354929.003756/1485461673.003863/1485458034003824/

**Comment by whit537** [comment]
> Masspay reports generated and uploaded to logs repo
> Next step is to upload to paypal

**Comment by whit537** [comment]
MassPay submitted .

**Comment by whit537** [comment]
POSTed MassPay back to Gratipay for 63 users.

**Comment by whit537** [comment]
Lowest yet, I think?

![screen shot 2017-01-26 at 4 15 49 pm](https://cloud.githubusercontent.com/assets/134455/22350679/bc59db32-e3e2-11e6-8b03-9389bb065b46.png)

**Comment by whit537** [comment]
6 / 43 = 14% decline on Braintree
9 / 63 = 14.2% on PayPal

**Comment by whit537** [comment]
#### Escrow Shuffle

|         | $        |
|:--------|---------:|
| MassPay | 1,587.30 |
| 5x      | 7,936.5 |
| Balance | 9,607.38 |
| Added   |     0.00 |

**Comment by whit537** [comment]
Logs in https://github.com/gratipay/logs/commit/6934fb730b3d50dd38e78c2ad24dc16c5995b861 https://github.com/gratipay/logs/commit/c6c97c3a23b7d1bf34cb49e5ccfa2fc2196f9842 https://github.com/gratipay/logs/commit/f5dfd750e9a5ab5a383637820f1ad6d0d49f34f7.

**Comment by whit537** [comment]
Let's see about manual overrides ...

**Comment by whit537** [comment]
We're down from 21 (17) to 18 (14) negative balances and we're holding steady at one remaining manual override.

```sql
SELECT username, balance FROM participants WHERE balance < 0 ORDER BY balance;
```

```sql
    SELECT balance, username, braintree, ngiving_to, giving, paypal
      FROM (    SELECT id
                     , username
                     , balance
                     , ngiving_to
                     , giving
                     , (SELECT address
                          FROM current_exchange_routes
                         WHERE participant=participants.id
                           AND network='paypal'
                        ) AS paypal
                     , (SELECT error
                          FROM current_exchange_routes
                         WHERE participant=participants.id
                           AND network='braintree-cc'
                        ) AS braintree
                  FROM participants
                 WHERE balance < 0
            ) _ join affected ON email=paypal
  ORDER BY affected is null
         , paypal is null
         , braintree is null
         , braintree
         , ngiving_to desc
         , balance asc
         , paypal
          ;
```

**Comment by whit537** [comment]
Actually tho what happened to @gratipay-bot?

**Comment by whit537** [comment]
`ssh root@bot` worked for me to get in (I have an entry in `.ssh/config`).

I see the entries in crontab:

```
root@bot:~/bot# crontab -l
# Suppress attempts to mail output. We'll check syslog.
MAILTO=""
PYTHON=/root/bot/env/bin/python

# Rotate the Radar every Sunday.
0    5    *    *    0    $PYTHON /root/bot/rotate-radar.py 2>&1 | logger -t ROTATE-RADAR
 
# Kick off Payday every Thursday.
0    5    *    *    4    $PYTHON /root/bot/kick-off-payday.py 2>&1 | logger -t KICK-OFF-PAYDAY
 
# Poll for updates every minute.
*    *    *    *    *    /root/bot/update-if-needed.sh 2>&1 | logger -t UPDATE-BOT

#    ┬    ┬    ┬    ┬
#    │    │    │    │
#    │    │    │    └─ day of week (0 - 6) (0 is Sunday, or use names)
#    │    │    └─────── month (1 - 12)
#    │    └───────────── day of month (1 - 31)
#    └─────────────────── hour (0 - 23)
#───────────────────────── min (0 - 59)
root@bot:~/bot#
```

Let's check logs ...

**Comment by whit537** [comment]
```
root@bot:~/bot# grep 'KICK-OFF-PAYDAY' /var/log/syslog*
/var/log/syslog.1:Jan 26 05:00:01 bot CRON[26607]: (root) CMD ($PYTHON /root/bot/kick-off-payday.py 2>&1 | logger -t KICK-OFF-PAYDAY)
/var/log/syslog.1:Jan 26 05:00:03 bot KICK-OFF-PAYDAY: Traceback (most recent call last):
/var/log/syslog.1:Jan 26 05:00:03 bot KICK-OFF-PAYDAY:   File "/root/bot/kick-off-payday.py", line 43, in <module>
/var/log/syslog.1:Jan 26 05:00:03 bot KICK-OFF-PAYDAY:     main()
/var/log/syslog.1:Jan 26 05:00:03 bot KICK-OFF-PAYDAY:   File "/root/bot/kick-off-payday.py", line 39, in main
/var/log/syslog.1:Jan 26 05:00:03 bot KICK-OFF-PAYDAY:     paydays.create_next(previous)
/var/log/syslog.1:Jan 26 05:00:03 bot KICK-OFF-PAYDAY:   File "/root/bot/kick-off-payday.py", line 15, in create_next
/var/log/syslog.1:Jan 26 05:00:03 bot KICK-OFF-PAYDAY:     assert re.match(r"run Gratipay [0-9]+", prev_title), prev_title
/var/log/syslog.1:Jan 26 05:00:03 bot KICK-OFF-PAYDAY: AssertionError: Show detailed info about future payments
root@bot:~/bot#
```

**Comment by whit537** [comment]
Somehow Gratipay bought picked up https://github.com/gratipay/inside.gratipay.com/issues/993? Is that what's going on?

**Comment by whit537** [comment]
Yeah, we originally labeled it `Payday`, removing that label seven hours ago. 👍

**Comment by whit537** [comment]
Okay! So now that the latest `Payday` issue is this one, we should be back on track.

!m @gratipay-bot

**Comment by whit537** [comment]
I had to update the ticket name so that @gratipay-bot could find it and get back on track again. [slack](http://gratipay.slackarchive.io/gratipay/-/1486041435.004234/1486048954.004337/1486048626004318/)

**Comment by whit537** [comment]
```
ssh root@bot
cd bot
source env/bin/activate
./kick-off-payday.py
```
