### ISSUE TITLE
Procure a .coop domain and migrate to it

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#996]
Part of #995.

**Comment by clone1018** [comment]
So our goal here is to move the gratipay website from .com to .coop?

**Comment by whit537** [comment]
Yes, that is the proposal. Thoughts?

**Comment by clone1018** [comment]
I think a weird TLD like that causes customer confusion.

**Comment by clone1018** [comment]
I'm not against it however I'm just curious behind the driving force and financial / marketing gains.

**Comment by whit537** [comment]
The purpose of this would be to more fully identify as a cooperative (#72 &rarr; #992 &rarr; #995). The  fifth cooperative principle (#992) is education of the public, and using the cooperative [marque](http://www.identity.coop/) and domain name would be part of that. If we believe in cooperatives enough to identify as one, then in my view we should go "all in" and proudly further the broader cooperative vision by differentiating ourselves as such. Yes, `gratipay.coop` is weirder than `gratipay.com`. Is it the _right kind_ of weird?

![screen shot 2017-02-02 at 2 15 55 pm](https://cloud.githubusercontent.com/assets/134455/22564340/2697efc4-e952-11e6-8923-01cfaf399e85.png)

P.S. Should go without saying but of course `.com` would redirect.

**Comment by clone1018** [comment]
Alright! I understand now, thanks @whit537

**Comment by whit537** [comment]
We could also do like Loomio: They use loomio.org for the product, and loomio.coop for their internal stuff. So we could stick with gratipay.com for user-facing, and migrate inside.gratipay.com to gratipay.coop. Would be good to reduce our cookie surface anyway.

**Comment by kaguillera** [comment]
My concern with changing to a .coop is that people may not find us and worry that the site is a spoof of the original .com

**Comment by whit537** [comment]
@kaguillera We would redirect gratipay.com to gratipay.coop if we wanted to use the .coop for the main site. That said, I lean towards gratipay.coop replacing inside.gratipay.com, because I think too often cooperatives overemphasize that they are cooperatives. Very few users care!
